import { createHash } from 'node:crypto'
import { normalizeRequestId, normalizeUserId, normalizeWorkflowId, normalizeWorkflowIdentifier } from './workflow-identifiers.ts'
import { AGENT_WORKFLOW_STATUSES, freezeAgentWorkflowState, isTerminalWorkflowStatus, type AgentWorkflowState, type AgentWorkflowStatus } from './workflow-state.ts'
import type { AgentWorkflowDatabaseRow } from './workflow-store-supabase-types.ts'

export type AgentWorkflowCodecErrorCode='invalid_row'|'invalid_identifier'|'invalid_status'|'invalid_version'|'invalid_timestamp'|'invalid_capabilities'|'invalid_cost'|'invalid_lease'|'invalid_terminal_state'|'unsafe_field'
export class AgentWorkflowCodecError extends Error { constructor(readonly code:AgentWorkflowCodecErrorCode){super(code);this.name='AgentWorkflowCodecError'} }
const bad=(code:AgentWorkflowCodecErrorCode):never=>{throw new AgentWorkflowCodecError(code)}
const safe=(value:unknown,max=128):string=>{if(typeof value!=='string')bad('invalid_identifier'); const text=value as string; try{return normalizeWorkflowIdentifier(text,max)}catch{ return bad('invalid_identifier') }}
const timestamp=(value:unknown, nullable=false):string|null=>{if(value===null&&nullable)return null;if(typeof value!=='string')bad('invalid_timestamp'); const text=value as string;if(!Number.isFinite(Date.parse(text)))bad('invalid_timestamp');return new Date(text).toISOString()}
const optional=(value:unknown,max=128)=>value===null?null:safe(value,max)
const unsafe=['source','test','stdout','stderr','artifact','prompt','environment','token','secret','credential','authorization']
const forbidden=(value:Record<string,unknown>)=>Object.keys(value).some(k=>unsafe.some(x=>k.toLowerCase().includes(x))&&!['lease_token_hash','leaseToken'].includes(k))
export function hashAgentWorkflowLeaseToken(token:string):string { if(typeof token!=='string'||token.trim().length===0||token.length>512) bad('invalid_lease'); return createHash('sha256').update(token.trim(),'utf8').digest('hex') }
export function encodeAgentWorkflowState(state:AgentWorkflowState):AgentWorkflowDatabaseRow {
  if(forbidden(state as any)) bad('unsafe_field'); const status=state.status; if(!AGENT_WORKFLOW_STATUSES.includes(status))bad('invalid_status'); if(!Number.isSafeInteger(state.version)||state.version<1)bad('invalid_version'); if(!Number.isSafeInteger(state.estimatedCostUnits)||state.estimatedCostUnits<0||state.estimatedCostUnits>1_000_000)bad('invalid_cost'); if(!Number.isSafeInteger(state.auditSequence)||state.auditSequence<0)bad('invalid_row'); if(!Array.isArray(state.capabilities)||state.capabilities.length>32||state.capabilities.some(x=>typeof x!=='string'||x.length>64))bad('invalid_capabilities'); const leaseTokenHash=state.leaseToken===null?null:hashAgentWorkflowLeaseToken(state.leaseToken); if((state.leaseOwner===null)!==(leaseTokenHash===null)||(leaseTokenHash===null)!==(state.leaseExpiresAt===null))bad('invalid_lease'); if(isTerminalWorkflowStatus(status)!==(state.completedAt!==null))bad('invalid_terminal_state'); if(state.quotaReleased&&state.quotaReservationId===null)bad('invalid_terminal_state');
  return Object.freeze({workflow_id:normalizeWorkflowId(state.workflowId),request_id:normalizeRequestId(state.requestId),user_id:normalizeUserId(state.userId),idempotency_key:safe(state.idempotencyKey),request_fingerprint:safe(state.requestFingerprint),status,version:state.version,lease_owner:optional(state.leaseOwner),lease_token_hash:leaseTokenHash,lease_expires_at:timestamp(state.leaseExpiresAt,true),provider_id:optional(state.providerId),language:safe(state.language,32),capabilities:Object.freeze([...state.capabilities]),estimated_cost_units:state.estimatedCostUnits,quota_reservation_id:optional(state.quotaReservationId),quota_released:state.quotaReleased,cancellation_requested:state.cancellationRequested,cancellation_reason_code:optional(state.cancellationReasonCode,64),started_at:timestamp(state.startedAt)!,updated_at:timestamp(state.updatedAt)!,completed_at:timestamp(state.completedAt,true),result_kind:state.resultKind, failure_category:optional(state.failureCategory),failed_stage:optional(state.failedStage),audit_sequence:state.auditSequence,created_at:timestamp(state.createdAt)!})
}
export function decodeAgentWorkflowRow(value:unknown):AgentWorkflowState {
  if(!value||typeof value!=='object'||forbidden(value as Record<string,unknown>))bad('invalid_row'); const row=value as AgentWorkflowDatabaseRow; if(!AGENT_WORKFLOW_STATUSES.includes(row.status as AgentWorkflowStatus))bad('invalid_status'); if(!Number.isSafeInteger(row.version)||row.version<1)bad('invalid_version'); if(!Array.isArray(row.capabilities)||row.capabilities.length>32||row.capabilities.some(x=>typeof x!=='string'||x.length>64))bad('invalid_capabilities'); if(!Number.isSafeInteger(row.estimated_cost_units)||row.estimated_cost_units<0||row.estimated_cost_units>1_000_000)bad('invalid_cost'); if(!Number.isSafeInteger(row.audit_sequence)||row.audit_sequence<0)bad('invalid_row'); const complete=timestamp(row.completed_at,true); if((row.lease_owner===null)!==(row.lease_token_hash===null)||(row.lease_token_hash===null)!==(row.lease_expires_at===null)||(row.lease_token_hash!==null&&!/^[a-f0-9]{64}$/.test(row.lease_token_hash)))bad('invalid_lease'); const status=row.status as AgentWorkflowStatus;if(isTerminalWorkflowStatus(status)!==(complete!==null)||(row.quota_released&&row.quota_reservation_id===null))bad('invalid_terminal_state');
  return freezeAgentWorkflowState({workflowId:normalizeWorkflowId(row.workflow_id),requestId:normalizeRequestId(row.request_id),userId:normalizeUserId(row.user_id),idempotencyKey:safe(row.idempotency_key),requestFingerprint:safe(row.request_fingerprint),status,version:row.version,leaseOwner:optional(row.lease_owner),leaseToken:null,leaseExpiresAt:timestamp(row.lease_expires_at,true),providerId:optional(row.provider_id),language:safe(row.language,32) as any,capabilities:Object.freeze([...row.capabilities]) as any,estimatedCostUnits:row.estimated_cost_units,quotaReservationId:optional(row.quota_reservation_id),quotaReleased:row.quota_released,cancellationRequested:row.cancellation_requested,cancellationReasonCode:optional(row.cancellation_reason_code,64),startedAt:timestamp(row.started_at)!,updatedAt:timestamp(row.updated_at)!,completedAt:complete,resultKind:row.result_kind as any,failureCategory:optional(row.failure_category),failedStage:optional(row.failed_stage),auditSequence:row.audit_sequence,createdAt:timestamp(row.created_at)!})
}
