import { decodeAgentWorkflowRow, encodeAgentWorkflowState, hashAgentWorkflowLeaseToken } from './workflow-store-supabase-codec.ts'
import { AgentWorkflowStoreError, classifyAgentWorkflowStoreError } from './workflow-store-supabase-errors.ts'
import type { AgentWorkflowStore } from './workflow-store.ts'; import type { AgentWorkflowState } from './workflow-state.ts'; import type { AgentWorkflowDatabasePort } from './workflow-store-supabase-types.ts'
export class SupabaseAgentWorkflowStore implements AgentWorkflowStore { constructor(private readonly database:AgentWorkflowDatabasePort){} private fail(error:unknown):never { try { throw error } catch(e) { if(e instanceof AgentWorkflowStoreError)throw e; throw classifyAgentWorkflowStoreError(e) } }
 async create(state:AgentWorkflowState){try{return decodeAgentWorkflowRow(await this.database.insertWorkflow(encodeAgentWorkflowState(state)))}catch(error:any){const classified=classifyAgentWorkflowStoreError(error); const message=String(error?.message??''); if(/workflow/i.test(message))throw new AgentWorkflowStoreError('duplicate_workflow');if(/idempotency/i.test(message))throw new AgentWorkflowStoreError('duplicate_idempotency_key');throw classified}}
 async get(id:string){try{const row=await this.database.selectWorkflow(id);return row===null?null:decodeAgentWorkflowRow(row)}catch(e){this.fail(e)}}
 async getByIdempotencyKey(userId:string,key:string){try{const rows=await this.database.selectWorkflowByIdempotency(userId,key);if(rows.length>1)throw new AgentWorkflowStoreError('integrity_failure');return rows[0]?decodeAgentWorkflowRow(rows[0]):null}catch(e){this.fail(e)}}
 async compareAndSet(input:{workflowId:string;expectedVersion:number;next:AgentWorkflowState;expectedLeaseOwner?:string|null;expectedLeaseToken?:string|null}){if(input.next.version!==input.expectedVersion+1)throw new AgentWorkflowStoreError('stale_version');try{const row=await this.database.compareAndSetWorkflow({workflowId:input.workflowId,expectedVersion:input.expectedVersion,row:encodeAgentWorkflowState(input.next),...(input.expectedLeaseOwner!==undefined?{expectedLeaseOwner:input.expectedLeaseOwner}:{}),...(input.expectedLeaseToken!==undefined?{expectedLeaseTokenHash:hashAgentWorkflowLeaseToken(input.expectedLeaseToken)}:{})});return row===null?null:decodeAgentWorkflowRow(row)}catch(e){this.fail(e)}}
 async listRecoverable(input:{now:number;limit:number}){if(!Number.isSafeInteger(input.limit)||input.limit<1||input.limit>100)throw new AgentWorkflowStoreError('operation_failed');try{return Object.freeze((await this.database.listRecoverableWorkflows({now:new Date(input.now).toISOString(),limit:input.limit})).map(decodeAgentWorkflowRow).sort((a,b)=>a.updatedAt.localeCompare(b.updatedAt)||a.workflowId.localeCompare(b.workflowId)))}catch(e){this.fail(e)}} }
