import type { ExecutorKind } from '../executors/executor-types.ts'
import { ExecutionPersistenceError } from './errors.ts'
import { canonicalTimestamp, serializableObject } from './serialization.ts'

export const executionRecordSchemaVersion = 'supervisor-execution-record-v1'
export const executionStatuses = ['requested','started','paused_for_approval','continuation_started','completed','failed','verification_failed','rejected','expired','abandoned_after_restart'] as const
export type ExecutionStatus = typeof executionStatuses[number]
export type VerificationStatus = 'pending' | 'verified' | 'failed' | 'not_required'
export type CheckpointStatus = 'none' | 'pending_approval' | 'approved' | 'expired' | 'abandoned'
export interface PersistentExecutionRecord { executionId: string; dispatchId: string; incidentId: string; planId: string; packageId?: string; packageFingerprint?: string; provider: string; targetEnvironment: 'sandbox'|'preview'|'production'; targetOrigin: string; executorKind: ExecutorKind; executionMode: 'dry_run'|'sandbox_execute'; status: ExecutionStatus; verificationStatus: VerificationStatus; checkpointStatus: CheckpointStatus; approvedStepIds: string[]; completedStepIds: string[]; skippedStepIds: string[]; startedAt: string; pausedAt?: string; completedAt?: string; failedAt?: string; createdAt: string; updatedAt: string; schemaVersion: string; sanitizedErrorCode?: string; sanitizedErrorMessage?: string; metadata: Record<string, import('../incident-schema.ts').SerializableValue> }
export const terminalExecutionStatuses = new Set<ExecutionStatus>(['completed','failed','verification_failed','rejected','expired','abandoned_after_restart'])
const allowed: Record<ExecutionStatus, ExecutionStatus[]> = { requested:['started','rejected','failed','abandoned_after_restart'], started:['paused_for_approval','failed','verification_failed','completed','expired','abandoned_after_restart'], paused_for_approval:['continuation_started','expired','abandoned_after_restart','failed'], continuation_started:['completed','failed','verification_failed','expired'], completed:[], failed:[], verification_failed:[], rejected:[], expired:[], abandoned_after_restart:[] }
export function assertTransition(from: ExecutionStatus, to: ExecutionStatus, verification: VerificationStatus) { if (!allowed[from]?.includes(to)) throw new ExecutionPersistenceError('invalid_status_transition', `Invalid execution status transition ${from} -> ${to}`); if (to === 'completed' && verification !== 'verified') throw new ExecutionPersistenceError('completion_requires_verified', 'Completed executions require verified verification status') }
function ids(v: unknown, p: string) { if (!Array.isArray(v) || !v.every(x => typeof x === 'string')) throw new ExecutionPersistenceError('invalid_step_ids', `${p} must be string[]`); return [...v] }
export function parseExecutionRecord(input: unknown): PersistentExecutionRecord { if (!input || typeof input !== 'object' || Array.isArray(input) || Object.getPrototypeOf(input) !== Object.prototype) throw new ExecutionPersistenceError('invalid_record', 'Execution record must be a plain object'); const r = input as Record<string, unknown>; const status = r.status as ExecutionStatus; if (!executionStatuses.includes(status)) throw new ExecutionPersistenceError('invalid_status','Unsupported execution status'); const verificationStatus = r.verificationStatus as VerificationStatus; if (!['pending','verified','failed','not_required'].includes(verificationStatus)) throw new ExecutionPersistenceError('invalid_verification_status','Unsupported verification status'); const rec: PersistentExecutionRecord = { executionId: s(r.executionId,'executionId'), dispatchId:s(r.dispatchId,'dispatchId'), incidentId:s(r.incidentId,'incidentId'), planId:s(r.planId,'planId'), packageId: opt(r.packageId), packageFingerprint: opt(r.packageFingerprint), provider:s(r.provider,'provider'), targetEnvironment:r.targetEnvironment as never, targetOrigin:s(r.targetOrigin,'targetOrigin'), executorKind:r.executorKind as never, executionMode:r.executionMode as never, status, verificationStatus, checkpointStatus:r.checkpointStatus as never, approvedStepIds:ids(r.approvedStepIds,'approvedStepIds'), completedStepIds:ids(r.completedStepIds ?? [],'completedStepIds'), skippedStepIds:ids(r.skippedStepIds ?? [],'skippedStepIds'), startedAt:canonicalTimestamp(r.startedAt,'startedAt'), pausedAt:r.pausedAt ? canonicalTimestamp(r.pausedAt,'pausedAt') : undefined, completedAt:r.completedAt ? canonicalTimestamp(r.completedAt,'completedAt') : undefined, failedAt:r.failedAt ? canonicalTimestamp(r.failedAt,'failedAt') : undefined, createdAt:canonicalTimestamp(r.createdAt,'createdAt'), updatedAt:canonicalTimestamp(r.updatedAt,'updatedAt'), schemaVersion:s(r.schemaVersion,'schemaVersion'), sanitizedErrorCode: opt(r.sanitizedErrorCode), sanitizedErrorMessage: opt(r.sanitizedErrorMessage), metadata: serializableObject(r.metadata ?? {}, 'metadata') }; if (rec.schemaVersion !== executionRecordSchemaVersion) throw new ExecutionPersistenceError('invalid_schema_version','Invalid execution schema version'); if (rec.targetEnvironment !== 'sandbox') throw new ExecutionPersistenceError('production_blocked','Only sandbox execution history is supported'); if (rec.executionMode !== 'sandbox_execute' && rec.executionMode !== 'dry_run') throw new ExecutionPersistenceError('invalid_execution_mode','Unsupported execution mode'); if (rec.status === 'completed' && rec.verificationStatus !== 'verified') throw new ExecutionPersistenceError('completion_requires_verified','Completed executions require verified verification status'); return rec }
function s(v: unknown, p: string) { if (typeof v !== 'string' || !v.trim()) throw new ExecutionPersistenceError('invalid_field', `${p} is required`); return v }
function opt(v: unknown) { return v === undefined || v === null || v === '' ? undefined : String(v) }
