import type { LearningConnectorSearch, LearningConnectorResult } from './connectors'

const TRANSIENT_STATUS=new Set([408,425,429,500,502,503,504])
function delay(ms:number){return new Promise(resolve=>setTimeout(resolve,ms))}
async function getJson(url:string):Promise<any>{let lastError:unknown;for(let attempt=0;attempt<3;attempt++){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),12000);try{const response=await fetch(url,{headers:{accept:'application/json','user-agent':'SignalBoost-COS/1.0 (https://signalboostapp.com)'},signal:controller.signal});if(!response.ok){const error=new Error(`COS learning source failed: ${response.status}`);if(!TRANSIENT_STATUS.has(response.status))throw error;lastError=error}else{return await response.json()}}catch(error){lastError=error;if(attempt>=2)throw error}finally{clearTimeout(timer)}await delay(250*(attempt+1))}throw lastError instanceof Error?lastError:new Error('COS learning source failed')}
function clean(value:unknown):string{return String(value??'').replace(/<[^>]+>/g,' ').replace(/\s+/g,' ').trim()}
function compactQuery(query:string,maxTerms=10):string{return clean(query).split(/\s+/).filter(Boolean).slice(0,maxTerms).join(' ')}

/** Crossref: use bibliographic search instead of a long natural-language query and avoid select,
 * which can fail as Crossref evolves its permitted field list. */
export const crossrefScientificSearch:LearningConnectorSearch=async(query,limit)=>{const q=compactQuery(query);const json=await getJson(`https://api.crossref.org/works?query.bibliographic=${encodeURIComponent(q)}&rows=${Math.min(limit,10)}`);return(json?.message?.items??[]).map((item:any):LearningConnectorResult=>({uri:item.URL||(item.DOI?`https://doi.org/${item.DOI}`:''),title:clean(item.title?.[0]),text:clean(item.abstract||`${item.title?.[0]??''}. Publisher: ${item.publisher??''}. Subject: ${(item.subject??[]).slice(0,6).join(', ')}.`),license:'metadata/abstract as supplied by Crossref'})).filter((x:LearningConnectorResult)=>x.uri&&x.text)}

/** OpenAlex: compact search terms reduce 400s from oversized curriculum questions. */
export const openAlexScientificSearch:LearningConnectorSearch=async(query,limit)=>{const q=compactQuery(query,8);const json=await getJson(`https://api.openalex.org/works?search=${encodeURIComponent(q)}&per-page=${Math.min(limit,10)}&mailto=hello%40signalboostapp.com`);return(json?.results??[]).map((item:any):LearningConnectorResult=>({uri:item.doi||item.id,title:clean(item.title),text:clean(`${item.title??''}. ${item.primary_topic?.display_name??''}. ${(item.keywords??[]).slice(0,6).map((k:any)=>k.display_name).join(', ')}. Cited by ${item.cited_by_count??0}.`),license:item.open_access?.is_oa?'open-access metadata':'metadata only'})).filter((x:LearningConnectorResult)=>x.uri&&x.text)}

export const openLibrarySearch:LearningConnectorSearch=async(query,limit)=>{const json=await getJson(`https://openlibrary.org/search.json?q=${encodeURIComponent(compactQuery(query,8))}&limit=${Math.min(limit,10)}`);return(json?.docs??[]).map((item:any):LearningConnectorResult=>({uri:item.key?`https://openlibrary.org${item.key}`:'',title:clean(item.title),text:clean(`${item.title??''}. ${item.author_name?.join(', ')??''}. First published ${item.first_publish_year??'unknown'}. Subjects: ${item.subject?.slice(0,8).join(', ')??''}.`),license:'Open Library metadata'})).filter((x:LearningConnectorResult)=>x.uri&&x.text)}

export const europePmcScientificSearch:LearningConnectorSearch=async(query,limit)=>{const json=await getJson(`https://www.ebi.ac.uk/europepmc/webservices/rest/search?query=${encodeURIComponent(compactQuery(query,8))}&pageSize=${Math.min(limit,10)}&format=json`);return(json?.resultList?.result??[]).map((item:any):LearningConnectorResult=>({uri:item.doi?`https://doi.org/${item.doi}`:item.pmcid?`https://europepmc.org/article/PMC/${item.pmcid.replace(/^PMC/,'')}`:'',title:clean(item.title),text:clean(`${item.title??''}. ${item.authorString??''}. ${item.journalTitle??''} ${item.pubYear??''}.`),license:item.isOpenAccess==='Y'?'open-access metadata':'metadata only'})).filter((x:LearningConnectorResult)=>x.uri&&x.text)}
