import { createHash } from 'crypto'
import { DeterministicVercelThinker } from './vercel-thinker.ts'
import { sanitizeString } from './incident-mapper.ts'
import type { RepairPlan, RepairStep, SupervisorIncident, VercelObservationDeps, VercelReadOnlyClient } from '../../index.ts'
import { VercelObserver } from './vercel-observer.ts'

export const vercelHealthSchemaVersion = 'vercel-deployment-health-intelligence-v1'
export type VercelHealthStatus = 'healthy' | 'incident_detected' | 'read_failed' | 'verification_failed'
export interface VercelHealthEvidence { evidenceId: string; kind: 'deployment'|'deployment_events'|'project_env_names'|'production_aliases'|'verification'; stepId: string; capturedAt: string; summary: string; reference?: string; metadata: Record<string, string | number | boolean | string[] | null> }
export interface VercelHealthRun { runId: string; projectId: string; providerConnectionId: string; environment: 'sandbox'|'preview'|'production'; status: VercelHealthStatus; startedAt: string; completedAt: string; incident?: SupervisorIncident; plan?: RepairPlan; completedStepIds: string[]; evidence: VercelHealthEvidence[]; verification: { status: 'verified'|'failed'; checkedAt: string; summary: string }; schemaVersion: string }
export interface VercelHealthStore { saveRun(run: VercelHealthRun): Promise<void>; listRuns(query?: { limit?: number; status?: string; environment?: string }): Promise<VercelHealthRun[]> }
export type VercelHealthClient = VercelReadOnlyClient & { getDeploymentEvents?(input: { deploymentId: string; teamId?: string; token: string }): Promise<{ events: unknown[] }>; listProjectEnvNames?(input: { projectId: string; teamId?: string; target: string; token: string }): Promise<{ names: string[] }>; listProductionAliases?(input: { projectId: string; teamId?: string; token: string }): Promise<{ aliases: string[] }> }
const hash = (v: string) => createHash('sha256').update(v).digest('hex').slice(0, 16)
const ev = (runId: string, stepId: string, kind: VercelHealthEvidence['kind'], summary: string, metadata: VercelHealthEvidence['metadata'] = {}, reference?: string): VercelHealthEvidence => ({ evidenceId: `${runId}:${stepId}:${kind}`, stepId, kind, capturedAt: new Date().toISOString(), summary: sanitizeString(summary, 500), reference: reference ? sanitizeString(reference, 240) : undefined, metadata })

export class InMemoryVercelHealthStore implements VercelHealthStore { private runs: VercelHealthRun[] = []; async saveRun(run: VercelHealthRun) { this.runs.unshift(JSON.parse(JSON.stringify(run))) } async listRuns(query: { limit?: number; status?: string; environment?: string } = {}) { return this.runs.filter(r => (!query.status || r.status === query.status) && (!query.environment || r.environment === query.environment)).slice(0, Math.min(Math.max(query.limit ?? 25, 1), 100)).map(r => JSON.parse(JSON.stringify(r))) } }

export class SupabaseVercelHealthStore implements VercelHealthStore { private readonly db: any
  constructor(db: any) { this.db = db }
  async saveRun(run: VercelHealthRun) { const { error } = await this.db.from('vercel_deployment_health_runs').upsert({ run_id: run.runId, project_id: run.projectId, provider_connection_id: run.providerConnectionId, environment: run.environment, status: run.status, started_at: run.startedAt, completed_at: run.completedAt, incident: run.incident ?? null, plan: run.plan ?? null, completed_step_ids: run.completedStepIds, evidence: run.evidence, verification: run.verification, schema_version: run.schemaVersion }, { onConflict: 'run_id' }); if (error) throw new Error(`vercel_health_save_failed:${error.message}`) } async listRuns(query: { limit?: number; status?: string; environment?: string } = {}) { let q = this.db.from('vercel_deployment_health_runs').select('*').order('completed_at', { ascending: false }).limit(Math.min(Math.max(query.limit ?? 25, 1), 100)); if (query.status) q = q.eq('status', query.status); if (query.environment) q = q.eq('environment', query.environment); const { data, error } = await q; if (error) throw new Error('vercel_health_list_failed'); return (data ?? []).map((r: any) => ({ runId: r.run_id, projectId: r.project_id, providerConnectionId: r.provider_connection_id, environment: r.environment, status: r.status, startedAt: r.started_at, completedAt: r.completed_at, incident: r.incident ?? undefined, plan: r.plan ?? undefined, completedStepIds: r.completed_step_ids ?? [], evidence: r.evidence ?? [], verification: r.verification, schemaVersion: r.schema_version })) } }

export class VercelDeploymentHealthIntelligence { private readonly deps: VercelObservationDeps & { client: VercelHealthClient; store: VercelHealthStore }
  constructor(deps: VercelObservationDeps & { client: VercelHealthClient; store: VercelHealthStore }) { this.deps = deps }
  async run(): Promise<VercelHealthRun> { const startedAt = this.deps.config.clock.now().toISOString(); const runId = `vercel-health-${hash(`${this.deps.config.projectId}:${startedAt}`)}`; const incidents = await new VercelObserver(this.deps).observe({ provider: 'vercel', environment: this.deps.config.environment }); const incident = incidents[0]; let status: VercelHealthStatus = incident ? 'incident_detected' : 'healthy'; const evidence: VercelHealthEvidence[] = []; const completedStepIds: string[] = []; let plan: RepairPlan | undefined; try { const token = await this.deps.secretResolver(this.deps.config.providerConnectionId); if (!token) throw new Error('missing_token'); if (incident) { plan = new DeterministicVercelThinker().proposeRepairPlan(incident); for (const step of [...plan.steps, ...plan.verificationSteps]) { if (step.action === 'stop') continue; evidence.push(await this.readStep(runId, step, token)); completedStepIds.push(step.stepId) } } else { evidence.push(ev(runId, 'verify-healthy-observation', 'verification', 'No deployment incident was detected by read-only Vercel observation.', { incidentCount: 0 })) } } catch (error) { status = 'read_failed'; evidence.push(ev(runId, 'read-failed', 'verification', `Read-only Vercel health workflow failed: ${sanitizeString(error instanceof Error ? error.message : error, 220)}`)) } const verification = this.verify(status, incident, plan, evidence); if (verification.status === 'failed' && status !== 'read_failed') status = 'verification_failed'; const run: VercelHealthRun = { runId, projectId: this.deps.config.projectId, providerConnectionId: this.deps.config.providerConnectionId, environment: this.deps.config.environment, status, startedAt, completedAt: this.deps.config.clock.now().toISOString(), incident, plan, completedStepIds, evidence, verification, schemaVersion: vercelHealthSchemaVersion }; await this.deps.store.saveRun(run); return run }
  private async readStep(runId: string, step: RepairStep, token: string): Promise<VercelHealthEvidence> { const p = step.parameters; const deploymentId = typeof p.deploymentId === 'string' ? p.deploymentId : undefined; if (step.stepId.startsWith('read-deployment-events') && deploymentId) { const events = await this.deps.client.getDeploymentEvents?.({ deploymentId, teamId: this.deps.config.teamId, token }); return ev(runId, step.stepId, 'deployment_events', `Read ${events?.events?.length ?? 0} deployment events/log entries for ${deploymentId}.`, { eventCount: events?.events?.length ?? 0, sanitized: true }, deploymentId) } if (step.stepId.startsWith('read-deployment') && deploymentId) { const d = await this.deps.client.getDeployment({ deploymentId, teamId: this.deps.config.teamId, token }); return ev(runId, step.stepId, 'deployment', `Deployment ${d.id} state is ${d.state}.`, { state: sanitizeString(d.state, 80), target: sanitizeString(d.target, 80) || null }, d.id) } if (step.stepId === 'read-project-env-names') { const names = await this.deps.client.listProjectEnvNames?.({ projectId: this.deps.config.projectId, teamId: this.deps.config.teamId, target: this.deps.config.environment, token }); return ev(runId, step.stepId, 'project_env_names', `Read ${names?.names?.length ?? 0} environment variable names; values were not requested.`, { names: (names?.names ?? []).map(n => sanitizeString(n, 120)).slice(0, 100), valuesRead: false }) } if (step.stepId === 'read-production-aliases') { const aliases = await this.deps.client.listProductionAliases?.({ projectId: this.deps.config.projectId, teamId: this.deps.config.teamId, token }); return ev(runId, step.stepId, 'production_aliases', `Read ${aliases?.aliases?.length ?? 0} production aliases.`, { aliases: (aliases?.aliases ?? []).map(a => sanitizeString(a, 160)).slice(0, 100) }) } return ev(runId, step.stepId, 'verification', step.description, { readOnly: true }) }
  private verify(status: VercelHealthStatus, incident: SupervisorIncident | undefined, plan: RepairPlan | undefined, evidence: VercelHealthEvidence[]) { const checkedAt = this.deps.config.clock.now().toISOString(); if (status === 'read_failed') return { status: 'failed' as const, checkedAt, summary: 'A required read-only Vercel evidence read failed.' }; if (!incident) return { status: 'verified' as const, checkedAt, summary: 'Healthy result verified because observation completed and found no incidents.' }; const required = [...(plan?.steps ?? []), ...(plan?.verificationSteps ?? [])].filter(s => s.action !== 'stop').map(s => s.stepId); const have = new Set(evidence.map(e => e.stepId)); const missing = required.filter(id => !have.has(id)); return missing.length ? { status: 'failed' as const, checkedAt, summary: `Missing evidence for steps: ${missing.join(', ')}` } : { status: 'verified' as const, checkedAt, summary: 'Incident health intelligence verified with read-only deployment evidence.' } }
}
