import { createHash } from 'crypto'
import { createBrowserProviderDiagnosticsSnapshot, type BrowserProviderCapabilityDiagnostics } from '../../../browser-provider/index.ts'
import { ExecutionChannelSelector, StaticCapabilityRegistry, classifyApiFailure, type ApiFailureCategory, type ExecutionDecision } from '../../execution-policy/index.ts'
import { auditRecordSchemaVersion, type PersistentAuditEvent } from '../../persistence/index.ts'
import { ownershipIdentity, terminalWorkItemStates, type CoordinationStore, type Lease, type OwnershipIdentity, type WorkItem } from '../../coordination/index.ts'
import { DeterministicVercelThinker } from './vercel-thinker.ts'
import { sanitizeString } from './incident-mapper.ts'
import type { RepairPlan, RepairStep, SupervisorIncident, VercelObservationDeps, VercelReadOnlyClient } from '../../index.ts'
import { VercelObserver } from './vercel-observer.ts'

export const vercelHealthSchemaVersion = 'vercel-deployment-health-intelligence-v2'
export type VercelHealthStatus = 'healthy' | 'incident_detected' | 'read_failed' | 'verification_failed' | 'rejected'
export type VercelHealthVerificationStatus = 'verified'|'partially_verified'|'unverifiable'|'failed'|'rejected'
export type VercelHealthComparisonStatus = 'completed'|'unavailable'|'metadata-ready'|'comparison-pending'
export interface VercelHealthEvidence { evidenceId: string; kind: 'deployment'|'deployment_events'|'project_env_names'|'production_aliases'|'verification'; stepId: string; capturedAt: string; summary: string; reference?: string; metadata: Record<string, string | number | boolean | string[] | null> }
export interface VercelHealthGovernance { workItemId:string; ownerInstanceId:string; ownerRuntimeId:string; leaseId:string; fencingToken:number; provider:'vercel'; projectId:string; deploymentId?:string; environment:'sandbox'|'preview'|'production'; tenantId?:string; providerConnectionId:string; leaseExpiresAt?:string }
export interface VercelHealthBpalSelection { capabilityId:string; capabilityVersion:string; adapterVersion:string; policyVersion:string; schemaVersion:string; riskClass:string; maturity:string; originIds:string[]; exactOrigins:string[]; navigationProfileId:string|null; evidenceProfileId:string; verificationProfileId:string; productionExecutionEnabled:false }
export interface VercelHealthAuditEvent { eventId:string; eventType:string; occurredAt:string; payload:Record<string, unknown>; schemaVersion:string }
export interface VercelHealthRun { runId: string; projectId: string; providerConnectionId: string; environment: 'sandbox'|'preview'|'production'; status: VercelHealthStatus; startedAt: string; completedAt: string; incident?: SupervisorIncident; plan?: RepairPlan; completedStepIds: string[]; approvedStepIds:string[]; selectedChannel:'api'|'browser'|'manual'|'none'; apiFailureCategory?:ApiFailureCategory; comparisonStatus:VercelHealthComparisonStatus; governance?:VercelHealthGovernance; bpalSelections:VercelHealthBpalSelection[]; auditEvents:VercelHealthAuditEvent[]; evidence: VercelHealthEvidence[]; verification: { status: VercelHealthVerificationStatus; checkedAt: string; summary: string; reasons:string[] }; schemaVersion: string }
export interface VercelHealthStore { saveRun(run: VercelHealthRun): Promise<void>; listRuns(query?: { limit?: number; status?: string; environment?: string }): Promise<VercelHealthRun[]> }
export type VercelHealthClient = VercelReadOnlyClient & { getDeploymentEvents?(input: { deploymentId: string; teamId?: string; token: string }): Promise<{ events: unknown[] }>; listProjectEnvNames?(input: { projectId: string; teamId?: string; target: string; token: string }): Promise<{ names: string[] }>; listProductionAliases?(input: { projectId: string; teamId?: string; token: string }): Promise<{ aliases: string[] }> }
export interface VercelHealthRunContext { coordinationStore:CoordinationStore; workItemId:string; ownerInstanceId:string; ownerRuntimeId:string; leaseId:string; fencingToken:number; executionMode?:'api_only'|'smart_failover'|'browser_on_demand'; approvedStepIds?:string[]; capabilityId?:string; capabilityVersion?:string; auditSink?:{ write(event:Readonly<PersistentAuditEvent|VercelHealthAuditEvent>):Promise<void>|void } }
const hash = (v: string) => createHash('sha256').update(v).digest('hex').slice(0, 16)
const safe = (v: unknown, n=220) => sanitizeString(String(v ?? ''), n).replace(/Bearer\s+[^\s]+/gi,'Bearer [redacted]').replace(/token[_-]?[a-z0-9]*/gi,'[redacted]')
const ev = (runId: string, stepId: string, kind: VercelHealthEvidence['kind'], summary: string, metadata: VercelHealthEvidence['metadata'] = {}, reference?: string): VercelHealthEvidence => ({ evidenceId: `${runId}:${stepId}:${kind}`, stepId, kind, capturedAt: new Date().toISOString(), summary: safe(summary, 500), reference: reference ? safe(reference, 240) : undefined, metadata })
function clone<T>(v:T):T { return JSON.parse(JSON.stringify(v)) }

export class InMemoryVercelHealthStore implements VercelHealthStore { private runs: VercelHealthRun[] = []; async saveRun(run: VercelHealthRun) { this.runs.unshift(clone(run)) } async listRuns(query: { limit?: number; status?: string; environment?: string } = {}) { return this.runs.filter(r => (!query.status || r.status === query.status) && (!query.environment || r.environment === query.environment)).slice(0, Math.min(Math.max(query.limit ?? 25, 1), 100)).map(clone) } }

export class SupabaseVercelHealthStore implements VercelHealthStore { private readonly db: any
  constructor(db: any) { this.db = db }
  async saveRun(run: VercelHealthRun) { const { error } = await this.db.from('vercel_deployment_health_runs').upsert({ run_id: run.runId, project_id: run.projectId, provider_connection_id: run.providerConnectionId, environment: run.environment, status: run.status, started_at: run.startedAt, completed_at: run.completedAt, incident: run.incident ?? null, plan: run.plan ?? null, completed_step_ids: run.completedStepIds, approved_step_ids: run.approvedStepIds, selected_channel: run.selectedChannel, api_failure_category: run.apiFailureCategory ?? null, comparison_status: run.comparisonStatus, governance: run.governance ?? null, bpal_selections: run.bpalSelections, audit_events: run.auditEvents, evidence: run.evidence, verification: run.verification, schema_version: run.schemaVersion }, { onConflict: 'run_id' }); if (error) throw new Error(`vercel_health_save_failed:${safe(error.message)}`) } async listRuns(query: { limit?: number; status?: string; environment?: string } = {}) { let q = this.db.from('vercel_deployment_health_runs').select('*').order('completed_at', { ascending: false }).limit(Math.min(Math.max(query.limit ?? 25, 1), 100)); if (query.status) q = q.eq('status', query.status); if (query.environment) q = q.eq('environment', query.environment); const { data, error } = await q; if (error) throw new Error('vercel_health_list_failed'); return (data ?? []).map((r: any) => ({ runId: r.run_id, projectId: r.project_id, providerConnectionId: r.provider_connection_id, environment: r.environment, status: r.status, startedAt: r.started_at, completedAt: r.completed_at, incident: r.incident ?? undefined, plan: r.plan ?? undefined, completedStepIds: r.completed_step_ids ?? [], approvedStepIds:r.approved_step_ids ?? r.completed_step_ids ?? [], selectedChannel:r.selected_channel ?? 'api', apiFailureCategory:r.api_failure_category ?? undefined, comparisonStatus:r.comparison_status ?? 'unavailable', governance:r.governance ?? undefined, bpalSelections:r.bpal_selections ?? [], auditEvents:r.audit_events ?? [], evidence: r.evidence ?? [], verification: r.verification, schemaVersion: r.schema_version })) } }

export class VercelDeploymentHealthIntelligence { private readonly deps: VercelObservationDeps & { client: VercelHealthClient; store: VercelHealthStore }
  constructor(deps: VercelObservationDeps & { client: VercelHealthClient; store: VercelHealthStore }) { this.deps = deps }
  async run(context?: VercelHealthRunContext): Promise<VercelHealthRun> { const startedAt = this.deps.config.clock.now().toISOString(); const runId = `vercel-health-${hash(`${this.deps.config.projectId}:${startedAt}:${context?.workItemId ?? 'test'}`)}`; const auditEvents:VercelHealthAuditEvent[]=[]; const audit=async(eventType:string,p:Record<string,unknown>={})=>{ const a={eventId:`${runId}:${eventType}:${auditEvents.length+1}`,eventType,occurredAt:this.deps.config.clock.now().toISOString(),payload:this.scrub({...p,runId,workItemId:context?.workItemId,provider:'vercel',projectId:this.deps.config.projectId,environment:this.deps.config.environment}),schemaVersion:auditRecordSchemaVersion}; auditEvents.push(a); if(context?.auditSink) await context.auditSink.write(a) }
    let governance:VercelHealthGovernance|undefined; let work:WorkItem|undefined; let lease:Lease|undefined
    try { if (context) { work = await context.coordinationStore.getWorkItem(context.workItemId); if(!work) throw new Error('missing_work_item'); if(terminalWorkItemStates.has(work.state)) throw new Error('terminal_work_item'); lease = await context.coordinationStore.getCurrentLease(context.workItemId); if(!lease) throw new Error('missing_lease'); if(lease.leaseId!==context.leaseId||lease.ownerInstanceId!==context.ownerInstanceId||lease.ownerRuntimeId!==context.ownerRuntimeId||lease.fencingToken!==context.fencingToken) throw new Error('ownership_mismatch'); if(Date.parse(lease.expiresAt)<=this.deps.config.clock.now().getTime()) throw new Error('expired_lease'); await context.coordinationStore.assertFence(context.workItemId, ownershipIdentity(lease), this.deps.config.clock.now()); governance={workItemId:context.workItemId,ownerInstanceId:context.ownerInstanceId,ownerRuntimeId:context.ownerRuntimeId,leaseId:context.leaseId,fencingToken:context.fencingToken,provider:'vercel',projectId:work.projectId || this.deps.config.projectId,deploymentId:work.resourceId,environment:work.environment,tenantId:work.tenantId,providerConnectionId:this.deps.config.providerConnectionId,leaseExpiresAt:lease.expiresAt}; if(governance.projectId!==this.deps.config.projectId||governance.environment!==this.deps.config.environment||work.provider!=='vercel') throw new Error('identity_mismatch'); await audit('lease_validated',{leaseId:lease.leaseId,fencingToken:lease.fencingToken}); await audit('fence_validated',{leaseId:lease.leaseId,fencingToken:lease.fencingToken}); await context.coordinationStore.transitionWorkItem({workItemId:context.workItemId,from:'leased',to:'processing',owner:ownershipIdentity(lease),now:this.deps.config.clock.now(),executionId:runId}).catch(()=>undefined); await audit('work_claimed') } } catch (error) { const run=this.rejectedRun(runId,startedAt,governance,auditEvents,`ownership_rejected:${safe(error instanceof Error?error.message:error)}`); await this.deps.store.saveRun(run); return run }
    await audit('observation_started'); const incidents = await new VercelObserver(this.deps).observe({ provider: 'vercel', environment: this.deps.config.environment }); await audit('observation_completed',{incidentCount:incidents.length}); const incident = incidents[0]; let status: VercelHealthStatus = incident ? 'incident_detected' : 'healthy'; const evidence: VercelHealthEvidence[] = []; const completedStepIds: string[] = []; let plan: RepairPlan | undefined; let approvedStepIds:string[]=[]; let selectedChannel:VercelHealthRun['selectedChannel']='api'; let apiFailureCategory:ApiFailureCategory|undefined; let bpalSelections:VercelHealthBpalSelection[]=[]; let comparisonStatus:VercelHealthComparisonStatus='unavailable'
    try { const token = await this.deps.secretResolver(this.deps.config.providerConnectionId); if (!token) throw new Error('missing_token'); if (incident) { await audit('incident_detected',{incidentId:incident.incidentId,severity:incident.severity}); plan = new DeterministicVercelThinker().proposeRepairPlan(incident); await audit('thinker_plan_created',{incidentId:incident.incidentId,planId:plan.planId}); approvedStepIds = this.approveScope(plan, context?.approvedStepIds); const selection=this.selectPolicy(context, approvedStepIds); selectedChannel=selection.decision.selectedChannel; apiFailureCategory=selection.decision.apiFailureCategory; bpalSelections=[selection.bpal]; comparisonStatus=selectedChannel==='manual'?'metadata-ready':'comparison-pending'; await audit('policy_evaluated',{selectedChannel,decisionCode:selection.decision.decisionCode,apiFailureCategory}); await audit('bpal_capability_resolved',{capabilityId:selection.bpal.capabilityId,verificationProfileId:selection.bpal.verificationProfileId}); await audit('inspection_scope_approved',{approvedStepIds}); if(selectedChannel!=='api') throw new Error(`inspection_channel_not_executable:${selectedChannel}`); await audit('inspection_dispatched',{selectedChannel}); for (const step of [...plan.steps, ...plan.verificationSteps].filter(s=>approvedStepIds.includes(s.stepId))) { evidence.push(await this.readStep(runId, step, token)); completedStepIds.push(step.stepId) } await audit('api_inspection_completed',{completedStepIds}); } else { approvedStepIds=['verify-healthy-observation']; evidence.push(ev(runId, 'verify-healthy-observation', 'verification', 'No deployment incident was detected by read-only Vercel observation.', { incidentCount: 0, providerMutation:false, browserExecution:false })); completedStepIds.push('verify-healthy-observation'); comparisonStatus='unavailable' } } catch (error) { status = 'read_failed'; apiFailureCategory=classifyApiFailure({ category: error instanceof Error && error.message==='missing_token' ? 'authentication_failed' : undefined }); evidence.push(ev(runId, 'read-failed', 'verification', `Read-only Vercel health workflow failed: ${safe(error instanceof Error ? error.message : error, 220)}`)) }
    const verification = this.verify(status, incident, plan, approvedStepIds, completedStepIds, evidence, governance, comparisonStatus); if (verification.status === 'failed' && status !== 'read_failed') status = 'verification_failed'; if(['verified','partially_verified'].includes(verification.status)) await audit('verification_completed',{verificationStatus:verification.status}); else await audit('workflow_failed',{verificationStatus:verification.status}); await audit(verification.status==='rejected'?'workflow_rejected':verification.status==='failed'?'workflow_failed':'workflow_completed',{verificationStatus:verification.status}); const run: VercelHealthRun = { runId, projectId: this.deps.config.projectId, providerConnectionId: this.deps.config.providerConnectionId, environment: this.deps.config.environment, status, startedAt, completedAt: this.deps.config.clock.now().toISOString(), incident, plan, completedStepIds, approvedStepIds, selectedChannel, apiFailureCategory, comparisonStatus, governance, bpalSelections, auditEvents, evidence, verification, schemaVersion: vercelHealthSchemaVersion }; await this.deps.store.saveRun(run); if(context && lease) await context.coordinationStore.transitionWorkItem({workItemId:context.workItemId,to:verification.status==='verified'?'completed':'failed',owner:ownershipIdentity(lease),now:this.deps.config.clock.now(),executionId:runId}).catch(()=>undefined); return run }
  private rejectedRun(runId:string, startedAt:string, governance:VercelHealthGovernance|undefined, auditEvents:VercelHealthAuditEvent[], reason:string):VercelHealthRun { return {runId,projectId:this.deps.config.projectId,providerConnectionId:this.deps.config.providerConnectionId,environment:this.deps.config.environment,status:'rejected',startedAt,completedAt:this.deps.config.clock.now().toISOString(),completedStepIds:[],approvedStepIds:[],selectedChannel:'none',comparisonStatus:'unavailable',governance,bpalSelections:[],auditEvents:[...auditEvents,{eventId:`${runId}:workflow_rejected`,eventType:'workflow_rejected',occurredAt:this.deps.config.clock.now().toISOString(),payload:{runId,reason:safe(reason),provider:'vercel',projectId:this.deps.config.projectId,environment:this.deps.config.environment},schemaVersion:auditRecordSchemaVersion}],evidence:[],verification:{status:'rejected',checkedAt:this.deps.config.clock.now().toISOString(),summary:reason,reasons:[reason]},schemaVersion:vercelHealthSchemaVersion} }
  private approveScope(plan:RepairPlan, override?:string[]):string[]{ const ordered=[...plan.steps,...plan.verificationSteps].filter(s=>s.action!=='stop').map(s=>s.stepId); const ids=override ?? ordered; if(ids.length===0) throw new Error('empty_approved_scope'); if(new Set(ids).size!==ids.length) throw new Error('duplicate_approved_step'); if(ids.some((id,i)=>id!==ordered[i])) throw new Error('approved_scope_not_exact_order'); for(const id of ids) if(!ordered.includes(id)) throw new Error('unknown_approved_step'); for(const s of [...plan.steps,...plan.verificationSteps].filter(s=>ids.includes(s.stepId))) if(!['read','verify'].includes(s.action)) throw new Error('mutation_step_rejected'); return ids }
  private selectPolicy(context:VercelHealthRunContext|undefined, approvedStepIds:string[]):{decision:ExecutionDecision;bpal:VercelHealthBpalSelection}{ const snapshot=createBrowserProviderDiagnosticsSnapshot(); const provider=snapshot.providers.find(p=>p.providerId==='vercel'); if(!provider) throw new Error('unknown_provider'); const cap=provider.capabilities.find(c=>c.capabilityId===(context?.capabilityId ?? 'compare_dashboard_with_api')); if(!cap) throw new Error('missing_bpal_capability'); this.validateBpal(provider,cap,context?.capabilityVersion); const registry=new StaticCapabilityRegistry([{capabilityId:cap.capabilityId,provider:'vercel',operation:cap.operation,channels:{api:true,browser:cap.channels.browser,manual:cap.channels.manual},riskClass:cap.riskClass as any,maturity:cap.maturity as any,reversible:cap.reversible,idempotent:cap.idempotent,supportsAutoFailover:false,supportsBrowserOnDemand:cap.supportsBrowserOnDemand,requiresHumanApproval:cap.requiresHumanApproval,approvedOrigins:[...cap.allowedOriginIds],verificationProfileId:cap.verificationProfileId,browserAdapterId:provider.adapterVersion,policyVersion:cap.policyVersion,capabilityVersion:cap.capabilityVersion,allowedEnvironments:['sandbox','preview','production'],approvedStepIds:[],schemaVersion:'supervisor-capability-v1'}]); const decision=new ExecutionChannelSelector(registry,cap.policyVersion).select({workItemId:context?.workItemId ?? 'test-work',executionMode:context?.executionMode ?? 'api_only',capabilityId:cap.capabilityId,capabilityVersion:cap.capabilityVersion,environment:this.deps.config.environment,apiAttempted:false,retryCount:0,maxRetries:this.deps.config.maxAttempts,ownerInstanceId:context?.ownerInstanceId ?? 'test-owner',ownerRuntimeId:context?.ownerRuntimeId ?? 'test-runtime',fencingToken:context?.fencingToken ?? 1,now:this.deps.config.clock.now(),flags:{productionBrowserExecutionEnabled:false}}); decision.auditMetadata.leaseId=context?.leaseId; const exactOrigins=cap.allowedOriginIds.map(id=>provider.origins.find((o:any)=>o.originId===id)?.exactOrigin || '').filter(Boolean); return {decision,bpal:{capabilityId:cap.capabilityId,capabilityVersion:cap.capabilityVersion,adapterVersion:provider.adapterVersion,policyVersion:cap.policyVersion,schemaVersion:provider.schemaVersion,riskClass:cap.riskClass,maturity:cap.maturity,originIds:[...cap.allowedOriginIds],exactOrigins,navigationProfileId:cap.navigationProfileId ?? null,evidenceProfileId:cap.evidenceProfileId,verificationProfileId:cap.verificationProfileId,productionExecutionEnabled:false}} }
  private validateBpal(provider:any, cap:BrowserProviderCapabilityDiagnostics, expected?:string){ if(provider.providerId!=='vercel'||provider.support.productionExecutionEnabled||provider.worker.maximumConcurrentWork!==0||provider.worker.executionDependencies.length!==0||!cap.readOnly||cap.riskClass!=='read_only'||cap.maturity==='suspended'||cap.productionExecutionEnabled||cap.allowedOriginIds.length===0||!cap.navigationProfileId||!cap.evidenceProfileId||!cap.verificationProfileId||!provider.adapterVersion||!cap.capabilityVersion||!cap.policyVersion||!provider.schemaVersion) throw new Error('bpal_capability_rejected'); if(expected&&expected!==cap.capabilityVersion) throw new Error('capability_version_mismatch') }
  private async readStep(runId: string, step: RepairStep, token: string): Promise<VercelHealthEvidence> { const p = step.parameters; const deploymentId = typeof p.deploymentId === 'string' ? p.deploymentId : undefined; if (step.stepId.startsWith('read-deployment-events') && deploymentId) { const events = await this.deps.client.getDeploymentEvents?.({ deploymentId, teamId: this.deps.config.teamId, token }); return ev(runId, step.stepId, 'deployment_events', `Read ${events?.events?.length ?? 0} deployment events/log entries for ${deploymentId}.`, { eventCount: events?.events?.length ?? 0, sanitized: true }, deploymentId) } if (step.stepId.startsWith('read-deployment') && deploymentId) { const d = await this.deps.client.getDeployment({ deploymentId, teamId: this.deps.config.teamId, token }); return ev(runId, step.stepId, 'deployment', `Deployment ${d.id} state is ${d.state}.`, { deploymentId:safe(d.id,120), state: safe(d.state, 80), target: safe(d.target, 80) || null }, d.id) } if (step.stepId === 'read-project-env-names') { const names = await this.deps.client.listProjectEnvNames?.({ projectId: this.deps.config.projectId, teamId: this.deps.config.teamId, target: this.deps.config.environment, token }); return ev(runId, step.stepId, 'project_env_names', `Read ${names?.names?.length ?? 0} environment variable names; values were not requested.`, { names: (names?.names ?? []).map(n => safe(n, 120)).slice(0, 100), valuesRead: false }) } if (step.stepId === 'read-production-aliases') { const aliases = await this.deps.client.listProductionAliases?.({ projectId: this.deps.config.projectId, teamId: this.deps.config.teamId, token }); return ev(runId, step.stepId, 'production_aliases', `Read ${aliases?.aliases?.length ?? 0} production aliases.`, { aliases: (aliases?.aliases ?? []).map(a => safe(a, 160)).slice(0, 100) }) } return ev(runId, step.stepId, 'verification', step.description, { readOnly: true, providerMutation:false, browserExecution:false }) }
  private verify(status: VercelHealthStatus, incident: SupervisorIncident | undefined, plan: RepairPlan | undefined, approved:string[], completed:string[], evidence: VercelHealthEvidence[], governance:VercelHealthGovernance|undefined, comparisonStatus:VercelHealthComparisonStatus) { const checkedAt = this.deps.config.clock.now().toISOString(); const reasons:string[]=[]; if (status === 'read_failed') return { status: 'failed' as const, checkedAt, summary: 'A required read-only Vercel evidence read failed.', reasons:['read_failed'] }; if (status === 'rejected') return { status: 'rejected' as const, checkedAt, summary: 'Ownership, policy, or scope validation rejected the run.', reasons:['rejected'] }; if (!incident) return { status: 'verified' as const, checkedAt, summary: 'Healthy result verified because observation completed and found no incidents.', reasons:[] }; const required = approved.length ? approved : [...(plan?.steps ?? []), ...(plan?.verificationSteps ?? [])].filter(s => s.action !== 'stop').map(s => s.stepId); if(JSON.stringify(required)!==JSON.stringify(completed)) reasons.push('completed_steps_do_not_match_approved_scope'); const have = new Set(evidence.map(e => e.stepId)); for(const id of required) if(!have.has(id)) reasons.push(`missing_evidence:${id}`); if(governance?.deploymentId && incident.metadata?.deploymentId && governance.deploymentId!==incident.metadata.deploymentId) reasons.push('deployment_identity_mismatch'); if(governance && governance.projectId!==this.deps.config.projectId) reasons.push('project_identity_mismatch'); if(comparisonStatus==='completed') reasons.push('browser_comparison_must_not_complete_without_browser'); if(JSON.stringify(evidence).match(/token_secret|Bearer secret|envValue|authorization/i)) reasons.push('unsafe_evidence_payload'); return reasons.length ? { status: 'failed' as const, checkedAt, summary: `Verification failed: ${reasons.join(', ')}`, reasons } : { status: 'verified' as const, checkedAt, summary: 'Incident health intelligence verified with exact read-only deployment evidence, identity binding, and no mutation/browser execution.', reasons } }
  private scrub(v:Record<string,unknown>):Record<string,unknown>{ return JSON.parse(JSON.stringify(v, (k,val)=>/token|secret|authorization|cookie|password/i.test(k)?'[redacted]':typeof val==='string'?safe(val,300):val)) }
}
