'use client'
import { useState } from 'react'
import ToggleSwitch from './ToggleSwitch'
import Modal from './Modal'
import { mockApi } from './mockApi'
export default function GovernancePanel({ governance, onGovernance }: { governance: { requires_approval: boolean; secrets_backend_only: boolean; supervisor_monitoring: boolean }; onGovernance: (v: typeof governance) => void }) {
  const [logs, setLogs] = useState<string[]>([]); const [status, setStatus] = useState(''); const [open, setOpen] = useState(false)
  async function test() { setStatus('Testing…'); const result = await mockApi.testIntegration(); setLogs(result.logs); setStatus(result.ok ? 'Success: mock integration test passed.' : 'Failed: review generated logs.') }
  return <section className="sb-glass-panel" style={{ padding: 18, display: 'grid', gap: 14 }}><h2 style={{ margin: 0, fontSize: 18 }}>Governance & Supervisor</h2><ToggleSwitch label="Requires Approval" help="Sensitive and mutating actions require human approval." checked={governance.requires_approval} onChange={(v) => onGovernance({ ...governance, requires_approval: v })} /><ToggleSwitch label="Secrets Backend Only" help="Secrets are represented only by backend references and never exposed in this blueprint." checked={governance.secrets_backend_only} onChange={(v) => onGovernance({ ...governance, secrets_backend_only: v })} /><ToggleSwitch label="Enable Supervisor Monitoring" help="Route test and runtime telemetry to the supervisor log stream." checked={governance.supervisor_monitoring} onChange={(v) => onGovernance({ ...governance, supervisor_monitoring: v })} /><div style={{ display: 'flex', gap: 10, flexWrap: 'wrap' }}><button type="button" onClick={test} style={{ border: 0, borderRadius: 12, background: '#ffc300', color: '#000', padding: '10px 14px', fontWeight: 900 }}>Test Integration</button><button type="button" onClick={() => setOpen(true)} style={{ border: '1px solid rgba(255,255,255,.14)', borderRadius: 12, background: 'rgba(255,255,255,.06)', color: '#fff', padding: '10px 14px', fontWeight: 900 }}>View Logs</button></div>{status && <p style={{ margin: 0, color: status.startsWith('Success') ? '#86efac' : '#ffc300' }}>{status}</p>}{logs.slice(0, 2).map((log) => <small key={log} style={{ color: 'rgba(255,255,255,.6)' }}>{log}</small>)}{open && <Modal title="Supervisor log preview" onClose={() => setOpen(false)}>{(logs.length ? logs : ['2026-07-16T12:00:00Z Waiting for test integration run.', '2026-07-16T12:00:03Z Blueprint panel is read-only.']).map((log, i) => <p key={log} style={{ color: 'rgba(255,255,255,.7)' }}>2026-07-16T12:00:0{i}Z · {log}</p>)}</Modal>}</section>
}
