// saas/components/integration-builder/IntegrationMetadataPanel.tsx
'use client'

import { LocalizedText } from '@/components/i18n/LocalizedText'
import SearchableDropdown from './SearchableDropdown.tsx'
import type { Option, Provider } from './mockApi.ts'
import { uiText } from '@/lib/i18n/uiText'

export default function IntegrationMetadataPanel({ name, description, tags, providerId, tagOptions, providers, onName, onDescription, onTags, onProvider }: { name: string; description: string; tags: string[]; providerId: string; tagOptions: Option[]; providers: Provider[]; onName: (v: string) => void; onDescription: (v: string) => void; onTags: (v: string[]) => void; onProvider: (v: string) => void }) {
  return <section className="sb-glass-panel" style={{ padding: 18, display: 'grid', gap: 16 }}><h2 style={{ margin: 0, fontSize: 18 }}><LocalizedText fallback={uiText('generatedUi.u_5270326827176bda')} /></h2><label style={{ display: 'grid', gap: 7, color: '#fff', fontWeight: 850, fontSize: 13 }}><LocalizedText fallback={uiText('generatedUi.u_1001108309d142c3')} /><input type="text" value={name} onChange={(e) => onName(e.target.value)} placeholder={uiText('generatedUi.u_8e0a7e77128f6a19')} style={{ border: '1px solid rgba(255,255,255,.14)', borderRadius: 14, background: 'rgba(2,6,23,.78)', color: '#fff', padding: 12 }} /></label><label style={{ display: 'grid', gap: 7, color: '#fff', fontWeight: 850, fontSize: 13 }}>{uiText('generatedUi.u_526e0087cc3f254d')}<textarea value={description} onChange={(e) => onDescription(e.target.value)} placeholder={uiText('generatedUi.u_e1e99514e5c8a4ad')} rows={4} style={{ border: '1px solid rgba(255,255,255,.14)', borderRadius: 14, background: 'rgba(2,6,23,.78)', color: '#fff', padding: 12, resize: 'vertical' }} /></label><SearchableDropdown label={uiText('generatedUi.u_1331275bc537b4c2')} options={tagOptions} value={tags} onChange={(v) => onTags(v as string[])} multiple placeholder={uiText('generatedUi.u_93bc41f4de1b16ed')} /><SearchableDropdown label={uiText('generatedUi.u_472590ae974d4c1f')} options={providers.map((p) => ({ id: p.id, label: p.name, description: p.description, icon: p.icon }))} value={providerId} onChange={(v) => onProvider(v as string)} placeholder={uiText('generatedUi.u_c63a3f5870fa451c')} /></section>
}
