'use client'
import SearchableDropdown from './SearchableDropdown'
import RequestFormBuilder from './RequestFormBuilder'
import type { Endpoint, Provider, SchemaField } from './mockApi'
export default function ProviderEndpointPanel({ provider, endpoints, endpointId, method, requestFields, requestValues, onEndpoint, onMethod, onRequestValues }: { provider?: Provider; endpoints: Endpoint[]; endpointId: string; method: string; requestFields: SchemaField[]; requestValues: Record<string, unknown>; onEndpoint: (v: string) => void; onMethod: (v: string) => void; onRequestValues: (v: Record<string, unknown>) => void }) {
  const endpoint = endpoints.find((item) => item.id === endpointId)
  return <section className="sb-glass-panel" style={{ padding: 18, display: 'grid', gap: 18 }}><h2 style={{ margin: 0, fontSize: 18 }}>Provider, Endpoint & Request</h2><div style={{ border: '1px solid rgba(255,255,255,.1)', borderRadius: 16, padding: 14, display: 'grid', gap: 10 }}><h3 style={{ margin: 0, fontSize: 15 }}>Authentication</h3>{!provider && <p style={{ margin: 0, color: 'rgba(255,255,255,.55)' }}>Select a provider to load authentication controls.</p>}{provider?.auth.type === 'oauth' && <button type="button" style={primaryButton}>Connect via OAuth</button>}{provider?.auth.type === 'apiKey' && <div style={{ display: 'grid', gap: 8 }}><code style={masked}>•••••••••••• backend credential reference</code><button type="button" style={secondaryButton}>Manage Credentials</button></div>}{provider?.auth.type === 'bearer' && <div style={{ display: 'grid', gap: 8 }}><code style={masked}>Bearer •••••••••••• backend reference</code><button type="button" style={secondaryButton}>Manage Credentials</button></div>}</div><SearchableDropdown label="Endpoint" options={endpoints.map((e) => ({ id: e.id, label: e.name, description: e.description }))} value={endpointId} onChange={(v) => onEndpoint(v as string)} placeholder="Select provider endpoint" /><label style={{ display: 'grid', gap: 7, color: '#fff', fontWeight: 850, fontSize: 13 }}>HTTP Method<select value={method} onChange={(e) => onMethod(e.target.value)} disabled={!endpoint} style={{ border: '1px solid rgba(255,255,255,.13)', borderRadius: 12, background: '#020617', color: '#fff', padding: 11 }}>{(endpoint?.methods || []).map((m) => <option key={m} value={m}>{m}</option>)}</select></label><div style={{ display: 'grid', gap: 10 }}><h3 style={{ margin: 0, fontSize: 15 }}>Request Body · Visual Form Builder</h3><RequestFormBuilder fields={requestFields} values={requestValues} onChange={onRequestValues} /></div></section>
}
const primaryButton = { border: 0, borderRadius: 12, background: '#ffc300', color: '#000', padding: '11px 14px', fontWeight: 900, cursor: 'pointer' }
const secondaryButton = { border: '1px solid rgba(26,240,255,.35)', borderRadius: 12, background: 'rgba(26,240,255,.1)', color: '#1af0ff', padding: '10px 12px', fontWeight: 900, cursor: 'pointer' }
const masked = { border: '1px solid rgba(255,255,255,.12)', borderRadius: 12, background: 'rgba(2,6,23,.78)', color: 'rgba(255,255,255,.72)', padding: 12 }
