// saas/components/integration-builder/ProviderEndpointPanel.tsx
'use client'

import { LocalizedText } from '@/components/i18n/LocalizedText'
import SearchableDropdown from './SearchableDropdown.tsx'
import RequestFormBuilder from './RequestFormBuilder.tsx'
import type { Endpoint, Provider, SchemaField } from './mockApi.ts'
import { uiText } from '@/lib/i18n/uiText'

export default function ProviderEndpointPanel({ provider, endpoints, endpointId, method, requestFields, requestValues, onEndpoint, onMethod, onRequestValues }: { provider?: Provider; endpoints: Endpoint[]; endpointId: string; method: string; requestFields: SchemaField[]; requestValues: Record<string, unknown>; onEndpoint: (v: string) => void; onMethod: (v: string) => void; onRequestValues: (v: Record<string, unknown>) => void }) {
  const endpoint = endpoints.find((item) => item.id === endpointId)
  return <section className="sb-glass-panel" style={{ padding: 18, display: 'grid', gap: 18 }}><h2 style={{ margin: 0, fontSize: 18 }}>{uiText('generatedUi.u_a14d15bc804a3e6a')}</h2><div style={{ border: '1px solid rgba(255,255,255,.1)', borderRadius: 16, padding: 14, display: 'grid', gap: 10 }}><h3 style={{ margin: 0, fontSize: 15 }}>{uiText('generatedUi.u_66880d2d8216260d')}</h3>{!provider && <p style={{ margin: 0, color: 'rgba(255,255,255,.55)' }}><LocalizedText fallback={uiText('generatedUi.u_bc7e583fb5455b95')} /></p>}{provider?.auth.type === 'oauth' && <code style={masked}>{provider.name}</code>}{provider?.auth.type === 'apiKey' && <code style={masked}>{uiText('generatedUi.u_937940c31f607f86')}</code>}{provider?.auth.type === 'bearer' && <code style={masked}>{uiText('generatedUi.u_d3be0e3b35d4a159')}</code>}</div><SearchableDropdown label={uiText('generatedUi.u_3df9726c68ba76d6')} options={endpoints.map((e) => ({ id: e.id, label: e.name, description: e.description }))} value={endpointId} onChange={(v) => onEndpoint(v as string)} placeholder={uiText('generatedUi.u_dbaad6de6328f363')} /><label style={{ display: 'grid', gap: 7, color: '#fff', fontWeight: 850, fontSize: 13 }}><LocalizedText fallback={uiText('generatedUi.u_596fe2e088b39234')} /><select value={method} onChange={(e) => onMethod(e.target.value)} disabled={!endpoint} style={{ border: '1px solid rgba(255,255,255,.13)', borderRadius: 12, background: '#020617', color: '#fff', padding: 11 }}>{(endpoint?.methods || []).map((m) => <option key={m} value={m}>{m}</option>)}</select></label><div style={{ display: 'grid', gap: 10 }}><h3 style={{ margin: 0, fontSize: 15 }}>{uiText('generatedUi.u_f9d091538c9454d8')}</h3><RequestFormBuilder fields={requestFields} values={requestValues} onChange={onRequestValues} /></div></section>
}
const masked = { border: '1px solid rgba(255,255,255,.12)', borderRadius: 12, background: 'rgba(2,6,23,.78)', color: 'rgba(255,255,255,.72)', padding: 12 }
