export type AdminMetric = {
  key: string
  label: string
  value?: string | number
  helper?: string
}

export type AdminSectionConfig = {
  key: string
  title: string
  description: string
  metrics: AdminMetric[]
  tableTitle: string
  tableColumns: string[]
  cockpit?: string[]
}

const unknown = 'Not tracked yet'

export const ADMIN_SECTIONS: Record<string, AdminSectionConfig> = {
  overview: {
    key: 'overview',
    title: 'Overview',
    description: 'Cross-platform command center for growth, activity, and business health.',
    metrics: [
      'total users','new users today','new users this week','new users this month','active users','total projects created','total websites created','total podcasts/audio jobs','total videos/captions','total reviews collected','total AI requests','total failed AI requests','total emails drafted/sent','total leads discovered','total sales pipeline value'
    ].map((label, i) => ({ key: `overview-${i}`, label, value: unknown })),
    tableTitle: 'Recent trend snapshots',
    tableColumns: ['Area', 'Latest', '7D change', 'Status'],
  },

  adm: { key: 'adm', title: 'Concierge Monitor', description: 'Unified Concierge telemetry for Marketplace and SaaS guidance, HMI onboarding, clear errors, and recommended actions.', metrics: ['concierge sessions','marketplace queries','saas module queries','partner intents','business owner intents','customer intents','HMI steps completed','telemetry events logged','proactive recommendations'].map((l,i)=>({key:`adm-${i}`,label:l,value:unknown})), tableTitle:'Concierge telemetry stream', tableColumns:['Audience role','Platform area','Intent','Recommended action'], cockpit:['Marketplace partners/categories/bookings','Promote Business, Reviews, Calendar, Spreadsheets, Outreach','Admin Console telemetry logging'] },
  signalboost: { key: 'signalboost', title: 'Marketplace Monitor', description: 'Traffic, search, partner conversion behavior, bookings, and category demand.', metrics: ['visitors','searches','concierge queries','partner clicks','top partner categories','top regions/countries','returning visitors','popular search terms','partner conversion clicks'].map((l,i)=>({key:`sb-${i}`,label:l,value:unknown})), tableTitle:'Top search and partner activity', tableColumns:['Metric','Value','Region','Notes'] },
  saas: { key: 'saas', title: 'SaaS Monitor', description: 'Product adoption across Promote Business, Reviews, Calendar, Spreadsheets, Outreach, and plan behavior.', metrics: ['signups','active users','projects per user','website builder usage','audio usage','video usage','review collector usage','AI assistant usage','language usage','plan distribution'].map((l,i)=>({key:`saas-${i}`,label:l,value:unknown})), tableTitle:'Product usage breakdown', tableColumns:['Feature','Users','Usage rate','Trend'] },
  sales: { key: 'sales', title: 'Unified Outreach Engine + CRM', description: 'Single campaign engine for Marketplace + SaaS social posts, emails, partner notifications, promotions, and Leads → Opportunities → Conversions.', metrics: ['prospects discovered','prospects approved','sketches generated','emails drafted','emails sent','replies received','meetings booked','clients won','daily outreach count','response rate','conversion rate','top industries','top countries','next follow-ups'].map((l,i)=>({key:`sales-${i}`,label:l,value:unknown})), tableTitle:'Pipeline and follow-ups', tableColumns:['Stage','Count','Conversion','Owner'] },
  revenue: { key: 'revenue', title: 'Financial Dashboard', description: 'Unified revenue totals, Marketplace vs SaaS breakdown, partner payouts, SaaS subscription ledger, churn, and plan economics.', metrics: ['free users','paid users','MRR','plan upgrades','cancellations','trial users','estimated monthly value','revenue by plan','revenue by country'].map((l,i)=>({key:`rev-${i}`,label:l,value:unknown})), tableTitle:'Plan and revenue performance', tableColumns:['Plan/Country','Users','Revenue','Change'] },
  ai: { key: 'ai', title: 'Forecasting + KPI Insights', description: 'Predictive analytics for 7/30/90 day revenue, campaign probability, partner churn risk, SaaS upsell likelihood, KPIs, and AI routing health.', metrics: ['AI requests by provider','OpenAI usage','Anthropic usage','failed AI calls','average response time','most common user intents','prompt intelligence results','action router intents','culture engine usage','cost estimate'].map((l,i)=>({key:`ai-${i}`,label:l,value:unknown})), tableTitle:'AI quality and cost', tableColumns:['Provider/Intent','Volume','Failure rate','Latency'] },
  email: { key: 'email', title: 'Email / Marketing', description: 'Marketing and sales email volume and performance.', metrics: ['marketing emails drafted','sales emails drafted','emails sent','bounce/failure counts','reply counts','campaign performance','best performing subject lines','unsubscribe/opt-out count'].map((l,i)=>({key:`email-${i}`,label:l,value:unknown})), tableTitle:'Campaign outcomes', tableColumns:['Campaign','Sent','Replies','Performance'] },
  partners: { key: 'partners', title: 'Partners', description: 'Partner demand, performance and supply gaps.', metrics: ['partner list','active partners','partner clicks','best performing partners','categories with most demand','countries with most partner activity','missing partner categories'].map((l,i)=>({key:`partner-${i}`,label:l,value:unknown})), tableTitle:'Partner performance table', tableColumns:['Partner/Category','Clicks','Country','Notes'] },
  system: { key: 'system', title: 'System Health', description: 'Operational reliability and automation status.', metrics: ['API errors','failed builds/deployments','Supabase connection status','Vercel/deployment status','cron job status','daily job results','last successful outreach run','last successful prospect discovery run'].map((l,i)=>({key:`sys-${i}`,label:l,value:unknown})), tableTitle:'Operational checks', tableColumns:['Service','Status','Last checked','Details'] },
  settings: { key: 'settings', title: 'Settings', description: 'Owner controls for admin access and automation safety.', metrics: ['admin users','email sending controls','daily outreach limits','AI provider preferences','safety controls','manual approval required toggle','competitor recommendation blocking','culture engine rules'].map((l,i)=>({key:`set-${i}`,label:l,value:unknown})), tableTitle:'Administrative controls', tableColumns:['Setting','Current value','Updated','Owner notes'] },
}

// Auto-generated 5-language translations for admin section data.
// translateSection() overlays the active language onto the English ADMIN_SECTIONS structure.
const NOT_TRACKED: Record<string,string> = { en: 'Not tracked yet', es: 'Aún no rastreado', pt: 'Ainda não rastreado', pl: 'Jeszcze nie śledzone', ru: 'Ещё не отслеживается' }

type SectionI18n = { title: string; description: string; metrics: string[]; tableTitle: string; tableColumns: string[]; cockpit?: string[] }
const SECTION_I18N: Record<string, Record<string, SectionI18n>> = {
  en: {
    overview: { title: 'Overview', description: 'Cross-platform command center for growth, activity, and business health.', metrics: ['total users', 'new users today', 'new users this week', 'new users this month', 'active users', 'total projects created', 'total websites created', 'total podcasts/audio jobs', 'total videos/captions', 'total reviews collected', 'total AI requests', 'total failed AI requests', 'total emails drafted/sent', 'total leads discovered', 'total sales pipeline value'], tableTitle: 'Recent trend snapshots', tableColumns: ['Area', 'Latest', '7D change', 'Status'] },
    adm: { title: 'Concierge Monitor', description: 'Unified Concierge telemetry for Marketplace and SaaS guidance, HMI onboarding, clear errors, and recommended actions.', metrics: ['concierge sessions', 'marketplace queries', 'saas module queries', 'partner intents', 'business owner intents', 'customer intents', 'HMI steps completed', 'telemetry events logged', 'proactive recommendations'], tableTitle: 'Concierge telemetry stream', tableColumns: ['Audience role', 'Platform area', 'Intent', 'Recommended action'], cockpit: ['Marketplace partners/categories/bookings', 'Promote Business, Reviews, Calendar, Spreadsheets, Outreach', 'Admin Console telemetry logging'] },
    signalboost: { title: 'Marketplace Monitor', description: 'Traffic, search, partner conversion behavior, bookings, and category demand.', metrics: ['visitors', 'searches', 'concierge queries', 'partner clicks', 'top partner categories', 'top regions/countries', 'returning visitors', 'popular search terms', 'partner conversion clicks'], tableTitle: 'Top search and partner activity', tableColumns: ['Metric', 'Value', 'Region', 'Notes'] },
    saas: { title: 'SaaS Monitor', description: 'Product adoption across Promote Business, Reviews, Calendar, Spreadsheets, Outreach, and plan behavior.', metrics: ['signups', 'active users', 'projects per user', 'website builder usage', 'audio usage', 'video usage', 'review collector usage', 'AI assistant usage', 'language usage', 'plan distribution'], tableTitle: 'Product usage breakdown', tableColumns: ['Feature', 'Users', 'Usage rate', 'Trend'] },
    sales: { title: 'Unified Outreach Engine + CRM', description: 'Single campaign engine for Marketplace + SaaS social posts, emails, partner notifications, promotions, and Leads → Opportunities → Conversions.', metrics: ['prospects discovered', 'prospects approved', 'sketches generated', 'emails drafted', 'emails sent', 'replies received', 'meetings booked', 'clients won', 'daily outreach count', 'response rate', 'conversion rate', 'top industries', 'top countries', 'next follow-ups'], tableTitle: 'Pipeline and follow-ups', tableColumns: ['Stage', 'Count', 'Conversion', 'Owner'] },
    revenue: { title: 'Financial Dashboard', description: 'Unified revenue totals, Marketplace vs SaaS breakdown, partner payouts, SaaS subscription ledger, churn, and plan economics.', metrics: ['free users', 'paid users', 'MRR', 'plan upgrades', 'cancellations', 'trial users', 'estimated monthly value', 'revenue by plan', 'revenue by country'], tableTitle: 'Plan and revenue performance', tableColumns: ['Plan/Country', 'Users', 'Revenue', 'Change'] },
    ai: { title: 'Forecasting + KPI Insights', description: 'Predictive analytics for 7/30/90 day revenue, campaign probability, partner churn risk, SaaS upsell likelihood, KPIs, and AI routing health.', metrics: ['AI requests by provider', 'OpenAI usage', 'Anthropic usage', 'failed AI calls', 'average response time', 'most common user intents', 'prompt intelligence results', 'action router intents', 'culture engine usage', 'cost estimate'], tableTitle: 'AI quality and cost', tableColumns: ['Provider/Intent', 'Volume', 'Failure rate', 'Latency'] },
    email: { title: 'Email / Marketing', description: 'Marketing and sales email volume and performance.', metrics: ['marketing emails drafted', 'sales emails drafted', 'emails sent', 'bounce/failure counts', 'reply counts', 'campaign performance', 'best performing subject lines', 'unsubscribe/opt-out count'], tableTitle: 'Campaign outcomes', tableColumns: ['Campaign', 'Sent', 'Replies', 'Performance'] },
    partners: { title: 'Partners', description: 'Partner demand, performance and supply gaps.', metrics: ['partner list', 'active partners', 'partner clicks', 'best performing partners', 'categories with most demand', 'countries with most partner activity', 'missing partner categories'], tableTitle: 'Partner performance table', tableColumns: ['Partner/Category', 'Clicks', 'Country', 'Notes'] },
    system: { title: 'System Health', description: 'Operational reliability and automation status.', metrics: ['API errors', 'failed builds/deployments', 'Supabase connection status', 'Vercel/deployment status', 'cron job status', 'daily job results', 'last successful outreach run', 'last successful prospect discovery run'], tableTitle: 'Operational checks', tableColumns: ['Service', 'Status', 'Last checked', 'Details'] },
    settings: { title: 'Settings', description: 'Owner controls for admin access and automation safety.', metrics: ['admin users', 'email sending controls', 'daily outreach limits', 'AI provider preferences', 'safety controls', 'manual approval required toggle', 'competitor recommendation blocking', 'culture engine rules'], tableTitle: 'Administrative controls', tableColumns: ['Setting', 'Current value', 'Updated', 'Owner notes'] },
  },
  es: {
    overview: { title: 'Resumen', description: 'Centro de mando multiplataforma para crecimiento, actividad y salud del negocio.', metrics: ['usuarios totales', 'nuevos usuarios hoy', 'nuevos usuarios esta semana', 'nuevos usuarios este mes', 'usuarios activos', 'proyectos creados', 'sitios web creados', 'trabajos de podcast/audio', 'videos/subtítulos', 'reseñas recopiladas', 'solicitudes de IA', 'solicitudes de IA fallidas', 'correos redactados/enviados', 'leads descubiertos', 'valor del pipeline de ventas'], tableTitle: 'Instantáneas de tendencias recientes', tableColumns: ['Área', 'Último', 'Cambio 7D', 'Estado'] },
    adm: { title: 'Monitor del Concierge', description: 'Telemetría unificada del Concierge para orientación de Marketplace y SaaS, incorporación HMI, errores claros y acciones recomendadas.', metrics: ['sesiones del concierge', 'consultas de marketplace', 'consultas de módulos SaaS', 'intenciones de socios', 'intenciones de dueños de negocio', 'intenciones de clientes', 'pasos HMI completados', 'eventos de telemetría registrados', 'recomendaciones proactivas'], tableTitle: 'Flujo de telemetría del Concierge', tableColumns: ['Rol de audiencia', 'Área de plataforma', 'Intención', 'Acción recomendada'], cockpit: ['Socios/categorías/reservas del Marketplace', 'Promote Business, Reseñas, Calendario, Hojas de cálculo, Alcance', 'Registro de telemetría de la Consola de administración'] },
    signalboost: { title: 'Monitor del Marketplace', description: 'Tráfico, búsqueda, conversión de socios, reservas y demanda por categoría.', metrics: ['visitantes', 'búsquedas', 'consultas del concierge', 'clics en socios', 'categorías de socios principales', 'regiones/países principales', 'visitantes recurrentes', 'términos de búsqueda populares', 'clics de conversión de socios'], tableTitle: 'Principal actividad de búsqueda y socios', tableColumns: ['Métrica', 'Valor', 'Región', 'Notas'] },
    saas: { title: 'Monitor SaaS', description: 'Adopción del producto en Promote Business, Reseñas, Calendario, Hojas de cálculo, Alcance y comportamiento de planes.', metrics: ['registros', 'usuarios activos', 'proyectos por usuario', 'uso del creador de sitios', 'uso de audio', 'uso de video', 'uso del recopilador de reseñas', 'uso del asistente de IA', 'uso de idiomas', 'distribución de planes'], tableTitle: 'Desglose de uso del producto', tableColumns: ['Función', 'Usuarios', 'Tasa de uso', 'Tendencia'] },
    sales: { title: 'Motor de alcance unificado + CRM', description: 'Motor único de campañas para publicaciones sociales de Marketplace + SaaS, correos, notificaciones a socios, promociones y Leads → Oportunidades → Conversiones.', metrics: ['prospectos descubiertos', 'prospectos aprobados', 'borradores generados', 'correos redactados', 'correos enviados', 'respuestas recibidas', 'reuniones agendadas', 'clientes ganados', 'alcance diario', 'tasa de respuesta', 'tasa de conversión', 'industrias principales', 'países principales', 'próximos seguimientos'], tableTitle: 'Pipeline y seguimientos', tableColumns: ['Etapa', 'Cantidad', 'Conversión', 'Responsable'] },
    revenue: { title: 'Panel financiero', description: 'Ingresos totales unificados, desglose Marketplace vs SaaS, pagos a socios, libro de suscripciones SaaS, cancelaciones y economía de planes.', metrics: ['usuarios gratuitos', 'usuarios de pago', 'MRR', 'mejoras de plan', 'cancelaciones', 'usuarios de prueba', 'valor mensual estimado', 'ingresos por plan', 'ingresos por país'], tableTitle: 'Rendimiento de planes e ingresos', tableColumns: ['Plan/País', 'Usuarios', 'Ingresos', 'Cambio'] },
    ai: { title: 'Previsiones + Análisis de KPI', description: 'Analítica predictiva de ingresos a 7/30/90 días, probabilidad de campañas, riesgo de baja de socios, probabilidad de upsell SaaS, KPIs y salud del enrutamiento de IA.', metrics: ['solicitudes de IA por proveedor', 'uso de OpenAI', 'uso de Anthropic', 'llamadas de IA fallidas', 'tiempo de respuesta promedio', 'intenciones de usuario más comunes', 'resultados de inteligencia de prompts', 'intenciones del enrutador de acciones', 'uso del motor cultural', 'estimación de costo'], tableTitle: 'Calidad y costo de IA', tableColumns: ['Proveedor/Intención', 'Volumen', 'Tasa de fallos', 'Latencia'] },
    email: { title: 'Correo / Marketing', description: 'Volumen y rendimiento de correos de marketing y ventas.', metrics: ['correos de marketing redactados', 'correos de ventas redactados', 'correos enviados', 'rebotes/fallos', 'respuestas', 'rendimiento de campañas', 'asuntos con mejor rendimiento', 'bajas/cancelaciones'], tableTitle: 'Resultados de campañas', tableColumns: ['Campaña', 'Enviados', 'Respuestas', 'Rendimiento'] },
    partners: { title: 'Socios', description: 'Demanda, rendimiento y brechas de oferta de socios.', metrics: ['lista de socios', 'socios activos', 'clics en socios', 'socios con mejor rendimiento', 'categorías con más demanda', 'países con más actividad de socios', 'categorías de socios faltantes'], tableTitle: 'Tabla de rendimiento de socios', tableColumns: ['Socio/Categoría', 'Clics', 'País', 'Notas'] },
    system: { title: 'Estado del sistema', description: 'Fiabilidad operativa y estado de la automatización.', metrics: ['errores de API', 'compilaciones/despliegues fallidos', 'estado de conexión de Supabase', 'estado de Vercel/despliegue', 'estado de tareas cron', 'resultados de tareas diarias', 'última ejecución exitosa de alcance', 'última ejecución exitosa de descubrimiento'], tableTitle: 'Comprobaciones operativas', tableColumns: ['Servicio', 'Estado', 'Última comprobación', 'Detalles'] },
    settings: { title: 'Configuración', description: 'Controles del propietario para acceso de administración y seguridad de automatización.', metrics: ['usuarios administradores', 'controles de envío de correo', 'límites diarios de alcance', 'preferencias de proveedor de IA', 'controles de seguridad', 'interruptor de aprobación manual', 'bloqueo de recomendación de competidores', 'reglas del motor cultural'], tableTitle: 'Controles administrativos', tableColumns: ['Ajuste', 'Valor actual', 'Actualizado', 'Notas del propietario'] },
  },
  pt: {
    overview: { title: 'Visão geral', description: 'Centro de comando multiplataforma para crescimento, atividade e saúde do negócio.', metrics: ['usuários totais', 'novos usuários hoje', 'novos usuários esta semana', 'novos usuários este mês', 'usuários ativos', 'projetos criados', 'sites criados', 'trabalhos de podcast/áudio', 'vídeos/legendas', 'avaliações coletadas', 'solicitações de IA', 'solicitações de IA com falha', 'e-mails redigidos/enviados', 'leads descobertos', 'valor do pipeline de vendas'], tableTitle: 'Resumos de tendências recentes', tableColumns: ['Área', 'Último', 'Variação 7D', 'Status'] },
    adm: { title: 'Monitor do Concierge', description: 'Telemetria unificada do Concierge para orientação de Marketplace e SaaS, integração HMI, erros claros e ações recomendadas.', metrics: ['sessões do concierge', 'consultas de marketplace', 'consultas de módulos SaaS', 'intenções de parceiros', 'intenções de donos de negócio', 'intenções de clientes', 'etapas HMI concluídas', 'eventos de telemetria registrados', 'recomendações proativas'], tableTitle: 'Fluxo de telemetria do Concierge', tableColumns: ['Papel do público', 'Área da plataforma', 'Intenção', 'Ação recomendada'], cockpit: ['Parceiros/categorias/reservas do Marketplace', 'Promote Business, Avaliações, Calendário, Planilhas, Prospecção', 'Registro de telemetria do Console de administração'] },
    signalboost: { title: 'Monitor do Marketplace', description: 'Tráfego, busca, conversão de parceiros, reservas e demanda por categoria.', metrics: ['visitantes', 'buscas', 'consultas do concierge', 'cliques em parceiros', 'principais categorias de parceiros', 'principais regiões/países', 'visitantes recorrentes', 'termos de busca populares', 'cliques de conversão de parceiros'], tableTitle: 'Principal atividade de busca e parceiros', tableColumns: ['Métrica', 'Valor', 'Região', 'Notas'] },
    saas: { title: 'Monitor SaaS', description: 'Adoção do produto em Promote Business, Avaliações, Calendário, Planilhas, Prospecção e comportamento de planos.', metrics: ['cadastros', 'usuários ativos', 'projetos por usuário', 'uso do construtor de sites', 'uso de áudio', 'uso de vídeo', 'uso do coletor de avaliações', 'uso do assistente de IA', 'uso de idiomas', 'distribuição de planos'], tableTitle: 'Detalhamento de uso do produto', tableColumns: ['Recurso', 'Usuários', 'Taxa de uso', 'Tendência'] },
    sales: { title: 'Motor de prospecção unificado + CRM', description: 'Motor único de campanhas para posts sociais de Marketplace + SaaS, e-mails, notificações a parceiros, promoções e Leads → Oportunidades → Conversões.', metrics: ['prospects descobertos', 'prospects aprovados', 'rascunhos gerados', 'e-mails redigidos', 'e-mails enviados', 'respostas recebidas', 'reuniões agendadas', 'clientes conquistados', 'prospecção diária', 'taxa de resposta', 'taxa de conversão', 'principais setores', 'principais países', 'próximos follow-ups'], tableTitle: 'Pipeline e follow-ups', tableColumns: ['Etapa', 'Contagem', 'Conversão', 'Responsável'] },
    revenue: { title: 'Painel financeiro', description: 'Receita total unificada, divisão Marketplace vs SaaS, pagamentos a parceiros, livro de assinaturas SaaS, churn e economia de planos.', metrics: ['usuários gratuitos', 'usuários pagantes', 'MRR', 'upgrades de plano', 'cancelamentos', 'usuários em teste', 'valor mensal estimado', 'receita por plano', 'receita por país'], tableTitle: 'Desempenho de planos e receita', tableColumns: ['Plano/País', 'Usuários', 'Receita', 'Variação'] },
    ai: { title: 'Previsões + Insights de KPI', description: 'Análise preditiva de receita em 7/30/90 dias, probabilidade de campanhas, risco de churn de parceiros, probabilidade de upsell SaaS, KPIs e saúde do roteamento de IA.', metrics: ['solicitações de IA por provedor', 'uso da OpenAI', 'uso da Anthropic', 'chamadas de IA com falha', 'tempo médio de resposta', 'intenções de usuário mais comuns', 'resultados de inteligência de prompts', 'intenções do roteador de ações', 'uso do motor cultural', 'estimativa de custo'], tableTitle: 'Qualidade e custo de IA', tableColumns: ['Provedor/Intenção', 'Volume', 'Taxa de falhas', 'Latência'] },
    email: { title: 'E-mail / Marketing', description: 'Volume e desempenho de e-mails de marketing e vendas.', metrics: ['e-mails de marketing redigidos', 'e-mails de vendas redigidos', 'e-mails enviados', 'rejeições/falhas', 'respostas', 'desempenho de campanhas', 'assuntos com melhor desempenho', 'descadastros/opt-outs'], tableTitle: 'Resultados de campanhas', tableColumns: ['Campanha', 'Enviados', 'Respostas', 'Desempenho'] },
    partners: { title: 'Parceiros', description: 'Demanda, desempenho e lacunas de oferta de parceiros.', metrics: ['lista de parceiros', 'parceiros ativos', 'cliques em parceiros', 'parceiros com melhor desempenho', 'categorias com mais demanda', 'países com mais atividade de parceiros', 'categorias de parceiros ausentes'], tableTitle: 'Tabela de desempenho de parceiros', tableColumns: ['Parceiro/Categoria', 'Cliques', 'País', 'Notas'] },
    system: { title: 'Saúde do sistema', description: 'Confiabilidade operacional e status da automação.', metrics: ['erros de API', 'builds/deploys com falha', 'status de conexão do Supabase', 'status do Vercel/deploy', 'status de tarefas cron', 'resultados de tarefas diárias', 'última execução de prospecção bem-sucedida', 'última execução de descoberta bem-sucedida'], tableTitle: 'Verificações operacionais', tableColumns: ['Serviço', 'Status', 'Última verificação', 'Detalhes'] },
    settings: { title: 'Configurações', description: 'Controles do proprietário para acesso de administração e segurança de automação.', metrics: ['usuários administradores', 'controles de envio de e-mail', 'limites diários de prospecção', 'preferências de provedor de IA', 'controles de segurança', 'interruptor de aprovação manual', 'bloqueio de recomendação de concorrentes', 'regras do motor cultural'], tableTitle: 'Controles administrativos', tableColumns: ['Configuração', 'Valor atual', 'Atualizado', 'Notas do proprietário'] },
  },
  pl: {
    overview: { title: 'Przegląd', description: 'Wieloplatformowe centrum dowodzenia dla wzrostu, aktywności i kondycji firmy.', metrics: ['łączna liczba użytkowników', 'nowi użytkownicy dziś', 'nowi użytkownicy w tym tygodniu', 'nowi użytkownicy w tym miesiącu', 'aktywni użytkownicy', 'utworzone projekty', 'utworzone strony', 'zadania podcast/audio', 'filmy/napisy', 'zebrane recenzje', 'żądania AI', 'nieudane żądania AI', 'wiadomości napisane/wysłane', 'znalezione leady', 'wartość lejka sprzedaży'], tableTitle: 'Migawki ostatnich trendów', tableColumns: ['Obszar', 'Najnowsze', 'Zmiana 7D', 'Status'] },
    adm: { title: 'Monitor Concierge', description: 'Ujednolicona telemetria Concierge dla wskazówek Marketplace i SaaS, wdrażania HMI, czytelnych błędów i rekomendowanych działań.', metrics: ['sesje concierge', 'zapytania marketplace', 'zapytania modułów SaaS', 'intencje partnerów', 'intencje właścicieli firm', 'intencje klientów', 'ukończone kroki HMI', 'zarejestrowane zdarzenia telemetrii', 'proaktywne rekomendacje'], tableTitle: 'Strumień telemetrii Concierge', tableColumns: ['Rola odbiorcy', 'Obszar platformy', 'Intencja', 'Rekomendowane działanie'], cockpit: ['Partnerzy/kategorie/rezerwacje Marketplace', 'Promote Business, Recenzje, Kalendarz, Arkusze, Pozyskiwanie', 'Rejestrowanie telemetrii konsoli administ.'] },
    signalboost: { title: 'Monitor Marketplace', description: 'Ruch, wyszukiwanie, konwersja partnerów, rezerwacje i popyt według kategorii.', metrics: ['odwiedzający', 'wyszukiwania', 'zapytania concierge', 'kliknięcia partnerów', 'najlepsze kategorie partnerów', 'najlepsze regiony/kraje', 'powracający odwiedzający', 'popularne wyszukiwania', 'kliknięcia konwersji partnerów'], tableTitle: 'Najlepsza aktywność wyszukiwania i partnerów', tableColumns: ['Metryka', 'Wartość', 'Region', 'Uwagi'] },
    saas: { title: 'Monitor SaaS', description: 'Adopcja produktu w Promote Business, Recenzje, Kalendarz, Arkusze, Pozyskiwanie i zachowanie planów.', metrics: ['rejestracje', 'aktywni użytkownicy', 'projekty na użytkownika', 'użycie kreatora stron', 'użycie audio', 'użycie wideo', 'użycie kolektora recenzji', 'użycie asystenta AI', 'użycie języków', 'rozkład planów'], tableTitle: 'Podział użycia produktu', tableColumns: ['Funkcja', 'Użytkownicy', 'Wskaźnik użycia', 'Trend'] },
    sales: { title: 'Ujednolicony silnik pozyskiwania + CRM', description: 'Jeden silnik kampanii dla postów społ. Marketplace + SaaS, e-maili, powiadomień partnerów, promocji oraz Leady → Szanse → Konwersje.', metrics: ['odkryci potencjalni klienci', 'zatwierdzeni potencjalni klienci', 'wygenerowane szkice', 'napisane e-maile', 'wysłane e-maile', 'otrzymane odpowiedzi', 'umówione spotkania', 'pozyskani klienci', 'dzienne pozyskiwanie', 'wskaźnik odpowiedzi', 'wskaźnik konwersji', 'najlepsze branże', 'najlepsze kraje', 'kolejne kontakty'], tableTitle: 'Lejek i kontakty', tableColumns: ['Etap', 'Liczba', 'Konwersja', 'Właściciel'] },
    revenue: { title: 'Panel finansowy', description: 'Ujednolicone przychody, podział Marketplace vs SaaS, wypłaty partnerów, księga subskrypcji SaaS, rezygnacje i ekonomia planów.', metrics: ['użytkownicy darmowi', 'użytkownicy płatni', 'MRR', 'ulepszenia planu', 'rezygnacje', 'użytkownicy próbni', 'szacowana wartość miesięczna', 'przychód wg planu', 'przychód wg kraju'], tableTitle: 'Wyniki planów i przychodów', tableColumns: ['Plan/Kraj', 'Użytkownicy', 'Przychód', 'Zmiana'] },
    ai: { title: 'Prognozy + Analizy KPI', description: 'Analityka predykcyjna przychodów 7/30/90 dni, prawdopodobieństwo kampanii, ryzyko odejścia partnerów, szansa upsell SaaS, KPI i kondycja routingu AI.', metrics: ['żądania AI wg dostawcy', 'użycie OpenAI', 'użycie Anthropic', 'nieudane wywołania AI', 'średni czas odpowiedzi', 'najczęstsze intencje użytkowników', 'wyniki inteligencji promptów', 'intencje routera akcji', 'użycie silnika kulturowego', 'szacowany koszt'], tableTitle: 'Jakość i koszt AI', tableColumns: ['Dostawca/Intencja', 'Wolumen', 'Wskaźnik błędów', 'Opóźnienie'] },
    email: { title: 'E-mail / Marketing', description: 'Wolumen i skuteczność e-maili marketingowych i sprzedażowych.', metrics: ['napisane e-maile marketingowe', 'napisane e-maile sprzedażowe', 'wysłane e-maile', 'odrzucenia/błędy', 'odpowiedzi', 'skuteczność kampanii', 'najlepsze tematy', 'wypisania/rezygnacje'], tableTitle: 'Wyniki kampanii', tableColumns: ['Kampania', 'Wysłane', 'Odpowiedzi', 'Skuteczność'] },
    partners: { title: 'Partnerzy', description: 'Popyt, wyniki i luki podaży partnerów.', metrics: ['lista partnerów', 'aktywni partnerzy', 'kliknięcia partnerów', 'najlepsi partnerzy', 'kategorie z największym popytem', 'kraje z największą aktywnością partnerów', 'brakujące kategorie partnerów'], tableTitle: 'Tabela wyników partnerów', tableColumns: ['Partner/Kategoria', 'Kliknięcia', 'Kraj', 'Uwagi'] },
    system: { title: 'Kondycja systemu', description: 'Niezawodność operacyjna i status automatyzacji.', metrics: ['błędy API', 'nieudane buildy/wdrożenia', 'status połączenia Supabase', 'status Vercel/wdrożenia', 'status zadań cron', 'wyniki zadań dziennych', 'ostatni udany przebieg pozyskiwania', 'ostatni udany przebieg wykrywania'], tableTitle: 'Kontrole operacyjne', tableColumns: ['Usługa', 'Status', 'Ostatnio sprawdzono', 'Szczegóły'] },
    settings: { title: 'Ustawienia', description: 'Kontrole właściciela dla dostępu administracyjnego i bezpieczeństwa automatyzacji.', metrics: ['użytkownicy administratorzy', 'kontrole wysyłania e-maili', 'dzienne limity pozyskiwania', 'preferencje dostawcy AI', 'kontrole bezpieczeństwa', 'przełącznik ręcznego zatwierdzania', 'blokowanie rekomendacji konkurencji', 'reguły silnika kulturowego'], tableTitle: 'Kontrole administracyjne', tableColumns: ['Ustawienie', 'Bieżąca wartość', 'Zaktualizowano', 'Notatki właściciela'] },
  },
  ru: {
    overview: { title: 'Обзор', description: 'Кросс-платформенный командный центр для роста, активности и состояния бизнеса.', metrics: ['всего пользователей', 'новые пользователи сегодня', 'новые за неделю', 'новые за месяц', 'активные пользователи', 'создано проектов', 'создано сайтов', 'задачи подкаст/аудио', 'видео/субтитры', 'собрано отзывов', 'запросы ИИ', 'неудачные запросы ИИ', 'письма составлено/отправлено', 'найдено лидов', 'стоимость воронки продаж'], tableTitle: 'Снимки последних трендов', tableColumns: ['Область', 'Последнее', 'Изм. 7Д', 'Статус'] },
    adm: { title: 'Монитор Concierge', description: 'Единая телеметрия Concierge для подсказок Marketplace и SaaS, онбординга HMI, понятных ошибок и рекомендуемых действий.', metrics: ['сессии concierge', 'запросы marketplace', 'запросы модулей SaaS', 'намерения партнёров', 'намерения владельцев бизнеса', 'намерения клиентов', 'завершённые шаги HMI', 'записанные события телеметрии', 'проактивные рекомендации'], tableTitle: 'Поток телеметрии Concierge', tableColumns: ['Роль аудитории', 'Область платформы', 'Намерение', 'Рекомендуемое действие'], cockpit: ['Партнёры/категории/брони Marketplace', 'Promote Business, Отзывы, Календарь, Таблицы, Привлечение', 'Логирование телеметрии админ-консоли'] },
    signalboost: { title: 'Монитор маркетплейса', description: 'Трафик, поиск, конверсия партнёров, бронирования и спрос по категориям.', metrics: ['посетители', 'поиски', 'запросы concierge', 'клики по партнёрам', 'топ категорий партнёров', 'топ регионов/стран', 'вернувшиеся посетители', 'популярные запросы', 'клики конверсии партнёров'], tableTitle: 'Топ активности поиска и партнёров', tableColumns: ['Метрика', 'Значение', 'Регион', 'Заметки'] },
    saas: { title: 'Монитор SaaS', description: 'Освоение продукта в Promote Business, Отзывы, Календарь, Таблицы, Привлечение и поведение планов.', metrics: ['регистрации', 'активные пользователи', 'проектов на пользователя', 'использование конструктора сайтов', 'использование аудио', 'использование видео', 'использование сбора отзывов', 'использование ИИ-ассистента', 'использование языков', 'распределение планов'], tableTitle: 'Разбивка использования продукта', tableColumns: ['Функция', 'Пользователи', 'Частота использования', 'Тренд'] },
    sales: { title: 'Единый движок привлечения + CRM', description: 'Единый движок кампаний для соцпостов Marketplace + SaaS, писем, уведомлений партнёрам, промоакций и Лиды → Возможности → Конверсии.', metrics: ['найдено потенц. клиентов', 'одобрено потенц. клиентов', 'создано черновиков', 'составлено писем', 'отправлено писем', 'получено ответов', 'назначено встреч', 'привлечено клиентов', 'охват за день', 'частота ответов', 'конверсия', 'топ отраслей', 'топ стран', 'следующие касания'], tableTitle: 'Воронка и касания', tableColumns: ['Этап', 'Количество', 'Конверсия', 'Ответственный'] },
    revenue: { title: 'Финансовая панель', description: 'Сводная выручка, разбивка Marketplace и SaaS, выплаты партнёрам, книга подписок SaaS, отток и экономика планов.', metrics: ['бесплатные пользователи', 'платные пользователи', 'MRR', 'апгрейды плана', 'отмены', 'пробные пользователи', 'оценочная месячная ценность', 'выручка по планам', 'выручка по странам'], tableTitle: 'Эффективность планов и выручки', tableColumns: ['План/Страна', 'Пользователи', 'Выручка', 'Изменение'] },
    ai: { title: 'Прогнозы + Аналитика KPI', description: 'Предиктивная аналитика выручки на 7/30/90 дней, вероятность кампаний, риск оттока партнёров, вероятность допродаж SaaS, KPI и состояние маршрутизации ИИ.', metrics: ['запросы ИИ по провайдеру', 'использование OpenAI', 'использование Anthropic', 'неудачные вызовы ИИ', 'среднее время ответа', 'частые намерения пользователей', 'результаты анализа промптов', 'намерения маршрутизатора действий', 'использование культурного движка', 'оценка затрат'], tableTitle: 'Качество и стоимость ИИ', tableColumns: ['Провайдер/Намерение', 'Объём', 'Частота сбоев', 'Задержка'] },
    email: { title: 'Email / Маркетинг', description: 'Объём и эффективность маркетинговых и продажных писем.', metrics: ['маркетинговых писем составлено', 'продажных писем составлено', 'писем отправлено', 'отказы/сбои', 'ответы', 'эффективность кампаний', 'лучшие темы писем', 'отписки/отказы'], tableTitle: 'Результаты кампаний', tableColumns: ['Кампания', 'Отправлено', 'Ответы', 'Эффективность'] },
    partners: { title: 'Партнёры', description: 'Спрос, эффективность и пробелы предложения партнёров.', metrics: ['список партнёров', 'активные партнёры', 'клики по партнёрам', 'лучшие партнёры', 'категории с наибольшим спросом', 'страны с наибольшей активностью партнёров', 'недостающие категории партнёров'], tableTitle: 'Таблица эффективности партнёров', tableColumns: ['Партнёр/Категория', 'Клики', 'Страна', 'Заметки'] },
    system: { title: 'Состояние системы', description: 'Операционная надёжность и статус автоматизации.', metrics: ['ошибки API', 'неудачные сборки/деплои', 'статус подключения Supabase', 'статус Vercel/деплоя', 'статус cron-задач', 'результаты ежедневных задач', 'последний успешный запуск охвата', 'последний успешный запуск поиска'], tableTitle: 'Операционные проверки', tableColumns: ['Сервис', 'Статус', 'Последняя проверка', 'Детали'] },
    settings: { title: 'Настройки', description: 'Элементы управления владельца для админ-доступа и безопасности автоматизации.', metrics: ['администраторы', 'управление отправкой писем', 'дневные лимиты охвата', 'предпочтения провайдера ИИ', 'элементы безопасности', 'переключатель ручного одобрения', 'блокировка рекомендаций конкурентов', 'правила культурного движка'], tableTitle: 'Административные элементы', tableColumns: ['Настройка', 'Текущее значение', 'Обновлено', 'Заметки владельца'] },
  },
}

export function translateSection(section: AdminSectionConfig, lang: string): AdminSectionConfig {
  const key = section.key
  const langPack = SECTION_I18N[lang] || SECTION_I18N.en
  const tr = langPack[key]
  if (!tr) return section
  const nt = NOT_TRACKED[lang] || NOT_TRACKED.en
  return {
    ...section,
    title: tr.title,
    description: tr.description,
    tableTitle: tr.tableTitle,
    tableColumns: tr.tableColumns,
    cockpit: tr.cockpit ?? section.cockpit,
    metrics: section.metrics.map((m, i) => ({ ...m, label: tr.metrics[i] ?? m.label, value: m.value === 'Not tracked yet' ? nt : m.value })),
  }
}
