import { NextRequest, NextResponse } from 'next/server'
import { POST as cosPrimaryPost } from '@/app/api/cos-primary/route'
import { evaluateRunpodWakePermission } from '@/lib/ai/cos/runpodWakePermission'
import { withRunpodWakePermission } from '@/lib/ai/local-inference'
import { callCosReasoner, resolveCosReasoner } from '@/lib/ai/cos/cosReasoner'
import { parseLocalResult } from '@/lib/ai/cos/reasonerOutput'
import { getAccess } from '@/lib/auth/access'
import { withPublicAuditIdentity } from '@/lib/auth/publicAuditIdentity'
import { withPublicDeliveryScope } from '@/lib/auth/publicDeliveryScope'
import { isProvenanceIntrospection } from '@/lib/ai/cos/cosOrchestration'

export const runtime = 'nodejs'
export const dynamic = 'force-dynamic'
export const maxDuration = 300

async function dynamicPublicSourceExplanation(input: {
  question: string
  priorAnswer: string
  language: string
}): Promise<string | null> {
  if (!resolveCosReasoner().config) return null
  const result = await callCosReasoner({
    temperature: 0.35,
    maxTokens: 260,
    systemPrompt: [
      'You are COS, explaining the origin of a previous public Concierge answer.',
      'Return ONLY strict JSON: {"answer":"...","confidence":0.0}.',
      'Write one or two natural, helpful sentences. Do not quote the user prompt.',
      'The previous answer was freshly generated by COS for this conversation, using the information in the conversation and general learned language knowledge.',
      'No external research, web sources, private company data, or private memory were used for that answer.',
      'Do not disclose models, providers, architecture, telemetry, or other internal implementation.',
      input.language ? `Reply in ${input.language}.` : 'Reply in the language of the user.',
    ].join(' '),
    prompt: [
      `USER QUESTION:\n${input.question}`,
      `PREVIOUS PUBLIC ANSWER:\n${input.priorAnswer.slice(0, 5000)}`,
      'Answer the user naturally now.',
    ].join('\n\n'),
  }).catch(() => null)
  const parsed = result?.text ? parseLocalResult(result.text) : null
  return parsed?.answer?.trim() || null
}

/**
 * Browser-only ingress wrapper for COS Primary.
 *
 * The stable /api/concierge endpoint is rewritten here by proxy.ts. This is therefore the REAL
 * public Concierge request boundary and must establish BOTH:
 *   1) request-scoped RunPod wake permission; and
 *   2) request-scoped public-delivery isolation.
 *
 * Public delivery isolation is applied before COS Primary performs auth, freshness routing,
 * reasoning, fallback, or persistence. Even if the browser belongs to the owner, nested access
 * checks see guest/public authority and COS cannot inherit owner/admin/private-company context.
 *
 * A separately captured request-local audit identity carries only the authenticated user id into
 * provenance persistence. It is not authorization context and is never exposed to COS reasoning,
 * private memory, tools, or prompts.
 *
 * Direct/server calls to /api/cos-primary do NOT pass through this wrapper and therefore are not
 * public Concierge traffic; they also cannot start a stopped RunPod unless separately authorized.
 */
export async function POST(req: NextRequest) {
  const body = await req.clone().json().catch(() => ({}))
  const messages = Array.isArray(body?.messages) ? body.messages : []
  const userMessages = messages.filter((message: any) => message?.role === 'user' && typeof message?.content === 'string')
  const latestUser = userMessages.at(-1)
  const prompt = typeof latestUser?.content === 'string' ? latestUser.content : ''
  const assistantMessages = messages.filter((message: any) => message?.role === 'assistant' && typeof message?.content === 'string')
  const priorAnswer = typeof assistantMessages.at(-1)?.content === 'string' ? assistantMessages.at(-1).content : ''
  const language = ['en', 'es', 'pt', 'pl', 'ru'].includes(String(body?.context?.language || '').toLowerCase())
    ? String(body.context.language).toLowerCase()
    : 'en'

  // This wrapper is the public Concierge boundary. Answer source questions here,
  // before COS Primary's private-only provenance policy can intercept them.
  if (isProvenanceIntrospection(prompt)) {
    const reply = await withPublicDeliveryScope(() => dynamicPublicSourceExplanation({
      question: prompt,
      priorAnswer,
      language,
    }))
    return NextResponse.json({
      reply: reply || 'I could not generate a source summary for the previous answer.',
      source: 'concierge-public-provenance-summary',
      external_ai_invoked: false,
    })
  }

  const permission = evaluateRunpodWakePermission({
    body,
    interactionHeader: req.headers.get('x-signalboost-user-interaction'),
    requestOrigin: req.headers.get('origin'),
    expectedOrigin: req.nextUrl.origin,
    secFetchSite: req.headers.get('sec-fetch-site'),
  })

  // Capture correlation identity BEFORE entering public-delivery scope. Only the user id is carried
  // forward. Once publicDeliveryScope starts, getAccess() still resolves to guest by design.
  const auditUserId = (await getAccess().catch(() => null))?.userId ?? null

  console.info('[cos-browser-runpod-wake-permission]', JSON.stringify({
    at: new Date().toISOString(),
    allowed: permission.allowed,
    source: permission.source,
    interactionId: permission.interactionId,
    ageMs: permission.ageMs,
    reason: permission.reason,
    auditIdentityCaptured: Boolean(auditUserId),
  }))

  return withPublicAuditIdentity(auditUserId, () =>
    withPublicDeliveryScope(() =>
      withRunpodWakePermission(permission, () => cosPrimaryPost(req)),
    ),
  )
}
