export type Region = 'us' | 'eu' | 'latam' | 'global'
export type Partner = { id: string; name: string; domain: string; category: string; description: string; logo: string; url: string; regional_urls: Partial<Record<Region, string>> }

const logo = (domain: string) => `https://logo.clearbit.com/${domain}`
const url = (domain: string) => `https://www.${domain}/`

export const partners: Partner[] = [
  { id: 'aviasales', name: 'Aviasales', domain: 'aviasales.com', category: 'Flights', description: 'Flight metasearch for flexible international travelers.', logo: logo('aviasales.com'), url: 'https://www.aviasales.com/', regional_urls: { global: 'https://www.aviasales.com/', us: 'https://www.aviasales.com/', eu: 'https://www.aviasales.com/', latam: 'https://www.aviasales.com/' } },
  { id: 'booking', name: 'Booking.com', domain: 'booking.com', category: 'Hotels', description: 'Global lodging inventory with cancellation and budget filters.', logo: logo('booking.com'), url: 'https://www.booking.com/', regional_urls: { global: 'https://www.booking.com/', us: 'https://www.booking.com/', eu: 'https://www.booking.com/', latam: 'https://www.booking.com/' } },
  { id: 'airalo', name: 'Airalo', domain: 'airalo.com', category: 'eSIM', description: 'Regional eSIM packages for travelers who need instant connectivity.', logo: logo('airalo.com'), url: 'https://www.airalo.com/', regional_urls: { global: 'https://www.airalo.com/', us: 'https://www.airalo.com/', eu: 'https://www.airalo.com/', latam: 'https://www.airalo.com/' } },
  { id: 'safetywing', name: 'SafetyWing', domain: 'safetywing.com', category: 'Insurance', description: 'Travel medical coverage and remote-work insurance workflows.', logo: logo('safetywing.com'), url: 'https://www.safetywing.com/', regional_urls: { global: 'https://www.safetywing.com/', us: 'https://www.safetywing.com/', eu: 'https://www.safetywing.com/', latam: 'https://www.safetywing.com/' } },
  { id: 'wise', name: 'Wise', domain: 'wise.com', category: 'Payments', description: 'Multi-currency accounts and international payment rails.', logo: logo('wise.com'), url: 'https://www.wise.com/', regional_urls: { global: 'https://www.wise.com/', us: 'https://www.wise.com/', eu: 'https://www.wise.com/', latam: 'https://www.wise.com/' } },
  { id: 'shopify', name: 'Shopify', domain: 'shopify.com', category: 'Commerce', description: 'Storefront, checkout, and commerce operations for growing brands.', logo: logo('shopify.com'), url: 'https://www.shopify.com/', regional_urls: { global: 'https://www.shopify.com/', us: 'https://www.shopify.com/', eu: 'https://www.shopify.com/', latam: 'https://www.shopify.com/' } },
  { id: 'stripe', name: 'Stripe', domain: 'stripe.com', category: 'Payments', description: 'Payment infrastructure for subscriptions, marketplaces, and SaaS.', logo: logo('stripe.com'), url: 'https://www.stripe.com/', regional_urls: { global: 'https://www.stripe.com/', us: 'https://www.stripe.com/', eu: 'https://www.stripe.com/', latam: 'https://www.stripe.com/' } },
  { id: 'canva', name: 'Canva', domain: 'canva.com', category: 'Creative', description: 'Fast design production for campaigns, social posts, and proof cards.', logo: logo('canva.com'), url: 'https://www.canva.com/', regional_urls: { global: 'https://www.canva.com/', us: 'https://www.canva.com/', eu: 'https://www.canva.com/', latam: 'https://www.canva.com/' } },
  { id: 'hubspot', name: 'HubSpot', domain: 'hubspot.com', category: 'CRM', description: 'CRM, landing pages, and marketing automation for sales teams.', logo: logo('hubspot.com'), url: 'https://www.hubspot.com/', regional_urls: { global: 'https://www.hubspot.com/', us: 'https://www.hubspot.com/', eu: 'https://www.hubspot.com/', latam: 'https://www.hubspot.com/' } },
  { id: 'mailchimp', name: 'Mailchimp', domain: 'mailchimp.com', category: 'Email', description: 'Email marketing journeys for review requests and nurture campaigns.', logo: logo('mailchimp.com'), url: 'https://www.mailchimp.com/', regional_urls: { global: 'https://www.mailchimp.com/', us: 'https://www.mailchimp.com/', eu: 'https://www.mailchimp.com/', latam: 'https://www.mailchimp.com/' } },
  { id: 'getyourguide', name: 'GetYourGuide', domain: 'getyourguide.com', category: 'Experiences', description: 'Bookable tours and activities for trip-planning marketplace flows.', logo: logo('getyourguide.com'), url: 'https://www.getyourguide.com/', regional_urls: { global: 'https://www.getyourguide.com/', us: 'https://www.getyourguide.com/', eu: 'https://www.getyourguide.com/', latam: 'https://www.getyourguide.com/' } },
  { id: 'viator', name: 'Viator', domain: 'viator.com', category: 'Experiences', description: 'Tours, activities, and local discovery inventory.', logo: logo('viator.com'), url: 'https://www.viator.com/', regional_urls: { global: 'https://www.viator.com/', us: 'https://www.viator.com/', eu: 'https://www.viator.com/', latam: 'https://www.viator.com/' } },
  { id: 'expedia', name: 'Expedia', domain: 'expedia.com', category: 'Travel', description: 'Travel booking bundles for flights, stays, and cars.', logo: logo('expedia.com'), url: 'https://www.expedia.com/', regional_urls: { global: 'https://www.expedia.com/', us: 'https://www.expedia.com/', eu: 'https://www.expedia.com/', latam: 'https://www.expedia.com/' } },
  { id: 'kayak', name: 'KAYAK', domain: 'kayak.com', category: 'Flights', description: 'Travel search across flights, cars, and stays.', logo: logo('kayak.com'), url: 'https://www.kayak.com/', regional_urls: { global: 'https://www.kayak.com/', us: 'https://www.kayak.com/', eu: 'https://www.kayak.com/', latam: 'https://www.kayak.com/' } },
  { id: 'skyscanner', name: 'Skyscanner', domain: 'skyscanner.com', category: 'Flights', description: 'Global flight comparison for price-sensitive travelers.', logo: logo('skyscanner.com'), url: 'https://www.skyscanner.com/', regional_urls: { global: 'https://www.skyscanner.com/', us: 'https://www.skyscanner.com/', eu: 'https://www.skyscanner.com/', latam: 'https://www.skyscanner.com/' } },
  { id: 'tripadvisor', name: 'Tripadvisor', domain: 'tripadvisor.com', category: 'Reviews', description: 'Destination reviews, planning, and experiences.', logo: logo('tripadvisor.com'), url: 'https://www.tripadvisor.com/', regional_urls: { global: 'https://www.tripadvisor.com/', us: 'https://www.tripadvisor.com/', eu: 'https://www.tripadvisor.com/', latam: 'https://www.tripadvisor.com/' } },
  { id: 'agoda', name: 'Agoda', domain: 'agoda.com', category: 'Hotels', description: 'Asia-forward hotel inventory with global coverage.', logo: logo('agoda.com'), url: 'https://www.agoda.com/', regional_urls: { global: 'https://www.agoda.com/', us: 'https://www.agoda.com/', eu: 'https://www.agoda.com/', latam: 'https://www.agoda.com/' } },
  { id: 'hostelworld', name: 'Hostelworld', domain: 'hostelworld.com', category: 'Hotels', description: 'Hostel and budget lodging discovery for younger travelers.', logo: logo('hostelworld.com'), url: 'https://www.hostelworld.com/', regional_urls: { global: 'https://www.hostelworld.com/', us: 'https://www.hostelworld.com/', eu: 'https://www.hostelworld.com/', latam: 'https://www.hostelworld.com/' } },
  { id: 'uber', name: 'Uber', domain: 'uber.com', category: 'Transport', description: 'On-demand rides and local mobility.', logo: logo('uber.com'), url: 'https://www.uber.com/', regional_urls: { global: 'https://www.uber.com/', us: 'https://www.uber.com/', eu: 'https://www.uber.com/', latam: 'https://www.uber.com/' } },
  { id: 'bolt', name: 'Bolt', domain: 'bolt.eu', category: 'Transport', description: 'Rides, scooters, and delivery coverage in many markets.', logo: logo('bolt.eu'), url: 'https://bolt.eu/', regional_urls: { global: 'https://bolt.eu/', us: 'https://bolt.eu/', eu: 'https://bolt.eu/', latam: 'https://bolt.eu/' } },
  { id: 'nordvpn', name: 'NordVPN', domain: 'nordvpn.com', category: 'Security', description: 'Privacy and VPN tools for remote teams and travelers.', logo: logo('nordvpn.com'), url: 'https://www.nordvpn.com/', regional_urls: { global: 'https://www.nordvpn.com/', us: 'https://www.nordvpn.com/', eu: 'https://www.nordvpn.com/', latam: 'https://www.nordvpn.com/' } },
  { id: 'notion', name: 'Notion', domain: 'notion.so', category: 'Productivity', description: 'Workspace docs and lightweight operating systems.', logo: logo('notion.so'), url: 'https://notion.so/', regional_urls: { global: 'https://notion.so/', us: 'https://notion.so/', eu: 'https://notion.so/', latam: 'https://notion.so/' } },
  { id: 'zapier', name: 'Zapier', domain: 'zapier.com', category: 'Automation', description: 'No-code automation between SaaS tools and workflows.', logo: logo('zapier.com'), url: 'https://www.zapier.com/', regional_urls: { global: 'https://www.zapier.com/', us: 'https://www.zapier.com/', eu: 'https://www.zapier.com/', latam: 'https://www.zapier.com/' } },
  { id: 'calendly', name: 'Calendly', domain: 'calendly.com', category: 'Scheduling', description: 'Scheduling links for sales, support, and review calls.', logo: logo('calendly.com'), url: 'https://www.calendly.com/', regional_urls: { global: 'https://www.calendly.com/', us: 'https://www.calendly.com/', eu: 'https://www.calendly.com/', latam: 'https://www.calendly.com/' } },
  { id: 'typeform', name: 'Typeform', domain: 'typeform.com', category: 'Forms', description: 'Conversational forms for reviews, onboarding, and lead capture.', logo: logo('typeform.com'), url: 'https://www.typeform.com/', regional_urls: { global: 'https://www.typeform.com/', us: 'https://www.typeform.com/', eu: 'https://www.typeform.com/', latam: 'https://www.typeform.com/' } },
]

export function getRegionalUrl(partner: Partner, region: Region) { return partner.regional_urls[region] || partner.regional_urls.global || partner.url }
