'use client'

// saas/components/hub/pages/ProviderExpansionPage.tsx
// Provider Manual — many small monitor pages. Maximum 2 providers per page.

import { useEffect, useMemo, useState } from 'react'
import { PageProps, TONES, cardStyle, labelStyle } from '../shared'

type ProviderIdea = { name: string; subtitle: string; visual: string[]; automate: string[]; why: string; phase: 'Phase 1' | 'Phase 2' | 'Phase 3' }
type ProviderPage = { id: string; icon: string; title: string; subtitle: string; providers: ProviderIdea[] }

const PREF_KEY = 'signalboost:enabledProviders'
const p = (name: string, subtitle: string, phase: ProviderIdea['phase'], visual: string[], automate: string[], why: string): ProviderIdea => ({ name, subtitle, phase, visual, automate, why })

const PAGES: ProviderPage[] = [
  { id: 'p1', icon: '🧱', title: 'Provider Monitor 1 — AWS', subtitle: 'AWS gets its own page because IAM, S3, and cloud risk need space.', providers: [p('AWS', 'Cloud operations', 'Phase 1', ['IAM', 'S3', 'Compute', 'Alerts'], ['Access review reminders', 'Storage exposure checks', 'Unused credential reminders', 'Cloud health signals'], 'AWS is powerful but complex. SignalBoost should make the most important risks easy to understand.')] },
  { id: 'p2', icon: '🧠', title: 'Provider Monitor 2 — OpenAI + Anthropic', subtitle: 'AI providers need their own cost, usage, and key governance page.', providers: [p('OpenAI', 'AI usage and cost', 'Phase 1', ['Usage', 'Cost', 'Limits', 'Models'], ['Usage visibility', 'Cost spike alerts', 'Rate-limit alerts', 'Credential age reminders'], 'AI usage can become expensive quickly. Owners need a simple way to see cost and limits.'), p('Anthropic', 'Claude API', 'Phase 2', ['Usage', 'Cost', 'Limits', 'Access'], ['Usage visibility', 'Cost alerts', 'Limit warnings', 'Access review'], 'AI providers need cost and usage visibility just like cloud providers.')] },
  { id: 'p3', icon: '🚀', title: 'Provider Monitor 3 — Supabase + Vercel', subtitle: 'The core platform runtime: database, auth, hosting, deploys, and environment coverage.', providers: [p('Supabase', 'Database and auth', 'Phase 1', ['Database', 'Auth', 'Storage', 'Coverage'], ['Database health', 'Auth status', 'Environment coverage', 'Storage policy review'], 'Supabase is core infrastructure. Data and auth status should always be visible.'), p('Vercel', 'Hosting and deploys', 'Phase 1', ['Deploys', 'Builds', 'Domains', 'Env'], ['Deployment health', 'Environment comparison', 'Domain status', 'Failed build alerts'], 'Vercel is where the product lives. Deployment and environment drift must be easy to catch.')] },
  { id: 'p4', icon: '🐙', title: 'Provider Monitor 4 — GitHub', subtitle: 'Code, releases, branches, and access deserve a focused operating view.', providers: [p('GitHub', 'Code and releases', 'Phase 1', ['Repos', 'PRs', 'Branches', 'Access'], ['Repository activity', 'Release visibility', 'Open PR summary', 'Access review guidance'], 'GitHub connects code, releases, and access. It belongs in the command center.')] },
  { id: 'p5', icon: '🏢', title: 'Provider Monitor 5 — Google Cloud + Azure', subtitle: 'Large enterprise clouds grouped together, but only two providers on the page.', providers: [p('Google Cloud', 'Cloud accounts and apps', 'Phase 2', ['Accounts', 'OAuth', 'Roles', 'Projects'], ['Account inventory', 'Role visibility', 'App review reminders', 'Environment mapping'], 'Google Cloud configuration can sprawl. SignalBoost should turn it into a clear checklist.'), p('Azure', 'Enterprise identity', 'Phase 2', ['Apps', 'Certificates', 'Roles', 'Tenant'], ['App expiration reminders', 'Certificate checks', 'Role visibility', 'Configuration warnings'], 'Azure identity and app settings need calm, readable monitoring.')] },
  { id: 'p6', icon: '🌐', title: 'Provider Monitor 6 — Firebase + Cloudflare', subtitle: 'Application config, DNS, SSL, rules, and edge protection.', providers: [p('Firebase', 'App backend', 'Phase 1', ['Auth', 'Rules', 'Storage', 'Usage'], ['Auth configuration', 'Rules review', 'Storage status', 'Usage visibility'], 'Firebase grows quickly and configuration drift is easy to miss.'), p('Cloudflare', 'DNS and edge', 'Phase 1', ['DNS', 'SSL', 'Workers', 'Proxy'], ['DNS health', 'SSL status', 'Worker status', 'Proxy review'], 'Cloudflare sits in front of everything. Small mistakes can affect the whole business.')] },
  { id: 'p7', icon: '📱', title: 'Provider Monitor 7 — Twilio', subtitle: 'SMS and verification costs deserve a focused page.', providers: [p('Twilio', 'SMS and verification', 'Phase 1', ['SMS', 'Verify', 'Cost', 'Delivery'], ['SMS usage', 'Cost alerts', 'Delivery visibility', 'Verification health'], 'Messaging failures block users and cost spikes can arrive fast.')] },
  { id: 'p8', icon: '✉️', title: 'Provider Monitor 8 — SendGrid + Postmark', subtitle: 'Transactional email, delivery, bounce, and domain health.', providers: [p('SendGrid', 'Transactional email', 'Phase 1', ['Delivery', 'Bounces', 'Domain', 'API'], ['Deliverability stats', 'Bounce alerts', 'Domain status', 'API health'], 'Email failure is business failure. Users need delivery visibility.'), p('Postmark', 'Email delivery', 'Phase 1', ['Delivery', 'Bounces', 'DKIM', 'SPF'], ['Delivery rate', 'Bounce alerts', 'Domain checks', 'Account health'], 'Transactional email powers receipts, logins, and alerts.')] },
  { id: 'p9', icon: '🗄️', title: 'Provider Monitor 9 — MongoDB Atlas + DigitalOcean', subtitle: 'Database and small-cloud infrastructure hygiene.', providers: [p('MongoDB Atlas', 'Database provider', 'Phase 2', ['Clusters', 'Backups', 'Network', 'Connections'], ['Cluster health', 'Backup status', 'Network review', 'Connection visibility'], 'Database health should not be discovered only after an outage.'), p('DigitalOcean', 'Cloud infrastructure', 'Phase 1', ['Droplets', 'Spaces', 'Firewalls', 'Usage'], ['Droplet health', 'Storage usage', 'Firewall review', 'Account usage'], 'Small teams need cloud hygiene without a full DevOps department.')] },
  { id: 'p10', icon: '🔐', title: 'Provider Monitor 10 — Auth0', subtitle: 'Identity configuration, clients, tenant settings, and MFA visibility.', providers: [p('Auth0', 'Identity provider', 'Phase 2', ['Clients', 'MFA', 'Tenant', 'Actions'], ['Client inventory', 'MFA visibility', 'Tenant review', 'Configuration alerts'], 'Identity settings are critical and rarely reviewed often enough.')] },
  { id: 'p11', icon: '🤖', title: 'Provider Monitor 11 — Hugging Face + Replicate', subtitle: 'Model operations, endpoints, spend, and usage signals.', providers: [p('Hugging Face', 'Models and endpoints', 'Phase 3', ['Models', 'Spaces', 'Endpoints', 'Access'], ['Endpoint health', 'Model usage', 'Access review', 'Space status'], 'Model operations should be understandable to non-technical owners.'), p('Replicate', 'Model runs', 'Phase 3', ['Runs', 'Spend', 'Models', 'Status'], ['Run status', 'Spend alerts', 'Model usage', 'Account health'], 'Model workloads can become expensive. Owners need early warning.')] },
  { id: 'p12', icon: '🛠️', title: 'Provider Monitor 12 — Observability + Incident Ops', subtitle: 'Error tracking, metrics, incidents, and uptime monitoring.', providers: [p('Sentry', 'Errors and releases', 'Phase 2', ['Errors', 'Releases', 'Alerts', 'Projects'], ['Error summary', 'Release health', 'Alert visibility', 'Trend detection'], 'Errors should become recommended actions, not noise.'), p('Datadog', 'Metrics and logs', 'Phase 3', ['Monitors', 'Logs', 'Metrics', 'Incidents'], ['Monitor summary', 'Incident visibility', 'Log volume alerts', 'Usage checks'], 'Datadog is powerful but can overwhelm small teams.')] },
  { id: 'p13', icon: '🚨', title: 'Provider Monitor 13 — PagerDuty + New Relic', subtitle: 'Incident response, APM, uptime, and escalation visibility.', providers: [p('PagerDuty', 'Incident response', 'Phase 3', ['Incidents', 'Services', 'Escalation', 'On-call'], ['Incident summary', 'Service health', 'Escalation visibility', 'On-call status'], 'Incident tools connect alerts to people. They belong in Command Control.'), p('New Relic', 'APM and uptime', 'Phase 3', ['APM', 'Logs', 'Alerts', 'Uptime'], ['App health', 'Alert visibility', 'Uptime checks', 'Performance trends'], 'Performance data is most useful when translated into next actions.')] },
]

const allProviderNames = PAGES.flatMap(page => page.providers.map(provider => provider.name))
function defaultPreferences(): Record<string, boolean> { return Object.fromEntries(allProviderNames.map(name => [name, true])) }

export default function ProviderExpansionPage(_props: PageProps) {
  const [pageIndex, setPageIndex] = useState(0)
  const [enabledProviders, setEnabledProviders] = useState<Record<string, boolean>>(defaultPreferences)
  const page = PAGES[pageIndex]

  useEffect(() => { try { const raw = localStorage.getItem(PREF_KEY); if (raw) setEnabledProviders({ ...defaultPreferences(), ...JSON.parse(raw) }) } catch {} }, [])
  useEffect(() => { try { localStorage.setItem(PREF_KEY, JSON.stringify(enabledProviders)) } catch {} }, [enabledProviders])

  const enabledCount = useMemo(() => Object.values(enabledProviders).filter(Boolean).length, [enabledProviders])
  const toggleProvider = (name: string) => setEnabledProviders(prev => ({ ...prev, [name]: prev[name] === false }))
  const setPageProviders = (enabled: boolean) => setEnabledProviders(prev => { const next = { ...prev }; for (const provider of page.providers) next[provider.name] = enabled; return next })

  return (
    <div className="provider-playbook" style={{ display: 'flex', flexDirection: 'column', height: '100%', minHeight: 0, gap: 12 }}>
      <style>{`.provider-visual{min-height:78px;border-radius:18px;border:1px solid rgba(255,255,255,.1);background:linear-gradient(135deg,rgba(26,240,255,.11),rgba(255,195,0,.08),rgba(255,255,255,.035));display:flex;align-items:center;justify-content:center;text-align:center;padding:12px;font-size:12px;font-weight:900;color:rgba(255,255,255,.78)}.provider-toggle,.provider-pref-chip,.tier-tab{white-space:nowrap}.provider-card.is-disabled{opacity:.48;filter:saturate(.65)}@media(max-width:780px){.provider-visual-grid{grid-template-columns:repeat(2,minmax(0,1fr))!important}.provider-content-grid{grid-template-columns:1fr!important}}`}</style>

      <section style={{ display: 'flex', flexWrap: 'wrap', justifyContent: 'space-between', alignItems: 'flex-start', gap: 12, flexShrink: 0 }}>
        <div><div style={labelStyle}>Monitor 4</div><h2 style={{ margin: '3px 0 4px', fontSize: 24, letterSpacing: '-.02em' }}>Provider Manual</h2><p style={{ margin: 0, color: 'rgba(255,255,255,.58)', fontSize: 13.5, maxWidth: 850 }}>Providers are now separated into {PAGES.length} small monitor pages. Maximum two providers per page.</p></div>
        <div style={{ display: 'flex', gap: 8, flexWrap: 'wrap', alignItems: 'center' }}><span style={{ padding: '8px 12px', borderRadius: 999, border: '1px solid rgba(26,240,255,.35)', background: 'rgba(26,240,255,.08)', color: '#1af0ff', fontSize: 12.5, fontWeight: 900 }}>{enabledCount} enabled</span><span style={{ padding: '8px 12px', borderRadius: 999, border: `1px solid ${TONES.gold.border}`, background: TONES.gold.soft, color: '#ffc300', fontSize: 12.5, fontWeight: 900 }}>{pageIndex + 1} / {PAGES.length}</span></div>
      </section>

      <section style={{ ...cardStyle, padding: 14, flexShrink: 0 }}>
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', gap: 12, flexWrap: 'wrap', marginBottom: 10 }}><div><div style={{ fontSize: 16, fontWeight: 950 }}>Provider Preferences</div><div style={{ color: 'rgba(255,255,255,.52)', fontSize: 12.5, marginTop: 2 }}>Enable only the providers your team uses.</div></div><div style={{ color: 'rgba(255,255,255,.52)', fontSize: 12.5 }}>{enabledCount} of {allProviderNames.length} active</div></div>
        <div style={{ display: 'flex', gap: 8, flexWrap: 'wrap' }}>{allProviderNames.map(name => { const enabled = enabledProviders[name] !== false; return <button key={name} onClick={() => toggleProvider(name)} className="hub-chip provider-pref-chip" style={{ padding: '7px 11px', borderRadius: 999, border: enabled ? '1px solid rgba(34,197,94,.38)' : '1px solid rgba(255,255,255,.14)', background: enabled ? 'rgba(34,197,94,.10)' : 'rgba(255,255,255,.045)', color: enabled ? '#86efac' : 'rgba(255,255,255,.52)', fontSize: 12, fontWeight: 900 }}>{enabled ? '●' : '○'} {name}</button> })}</div>
      </section>

      <section style={{ ...cardStyle, flexShrink: 0, overflow: 'hidden' }}>
        <div style={{ padding: '15px 17px', background: 'linear-gradient(135deg, rgba(255,195,0,.12), rgba(26,240,255,.06), rgba(3,7,18,0))', display: 'flex', justifyContent: 'space-between', gap: 12, flexWrap: 'wrap', alignItems: 'center' }}><div><div style={{ fontSize: 22, fontWeight: 950, letterSpacing: '-.02em' }}>{page.icon} {page.title}</div><div style={{ color: 'rgba(255,255,255,.58)', fontSize: 13.5, marginTop: 5 }}>{page.subtitle}</div></div><div style={{ display: 'flex', gap: 8, flexWrap: 'wrap' }}><button onClick={() => setPageIndex(Math.max(0, pageIndex - 1))} disabled={pageIndex === 0} className="hub-chip" style={{ padding: '7px 11px', borderRadius: 10, border: '1px solid rgba(255,255,255,.14)', background: 'rgba(255,255,255,.045)', color: pageIndex === 0 ? 'rgba(255,255,255,.28)' : 'rgba(255,255,255,.72)', fontSize: 12, fontWeight: 900 }}>Previous</button><button onClick={() => setPageIndex(Math.min(PAGES.length - 1, pageIndex + 1))} disabled={pageIndex === PAGES.length - 1} className="hub-chip" style={{ padding: '7px 11px', borderRadius: 10, border: `1px solid ${TONES.blue.border}`, background: TONES.blue.soft, color: pageIndex === PAGES.length - 1 ? 'rgba(255,255,255,.32)' : '#1af0ff', fontSize: 12, fontWeight: 900 }}>Next</button><button onClick={() => setPageProviders(true)} className="hub-chip" style={{ padding: '7px 11px', borderRadius: 10, border: '1px solid rgba(34,197,94,.38)', background: 'rgba(34,197,94,.08)', color: '#86efac', fontSize: 12, fontWeight: 900 }}>Enable page</button><button onClick={() => setPageProviders(false)} className="hub-chip" style={{ padding: '7px 11px', borderRadius: 10, border: '1px solid rgba(255,255,255,.14)', background: 'rgba(255,255,255,.045)', color: 'rgba(255,255,255,.68)', fontSize: 12, fontWeight: 900 }}>Disable page</button></div></div>
        <div style={{ display: 'flex', gap: 8, flexWrap: 'wrap', padding: '12px 14px', borderTop: '1px solid rgba(255,255,255,.08)' }}>{PAGES.map((item, index) => <button key={item.id} onClick={() => setPageIndex(index)} className="hub-chip tier-tab" style={{ padding: '8px 10px', borderRadius: 12, border: pageIndex === index ? `1px solid ${TONES.gold.border}` : '1px solid rgba(255,255,255,.12)', background: pageIndex === index ? TONES.gold.soft : 'rgba(255,255,255,.04)', color: pageIndex === index ? '#ffc300' : 'rgba(255,255,255,.68)', fontSize: 12, fontWeight: 900 }}>{item.icon} {index + 1}</button>)}</div>
      </section>

      <main className="provider-playbook-main hub-panel" style={{ flex: 1, minHeight: 0, overflowY: 'auto', paddingRight: 8 }}>
        <div style={{ display: 'grid', gridTemplateColumns: page.providers.length === 1 ? 'minmax(0, 1fr)' : 'repeat(2, minmax(0, 1fr))', gap: 16, alignItems: 'stretch' }}>
          {page.providers.map(provider => { const enabled = enabledProviders[provider.name] !== false; return <article key={provider.name} className={`provider-card ${enabled ? '' : 'is-disabled'}`} style={{ ...cardStyle, padding: 18, minHeight: 420, display: 'flex', flexDirection: 'column', gap: 14 }}><div style={{ display: 'flex', justifyContent: 'space-between', gap: 12, alignItems: 'flex-start', flexWrap: 'wrap' }}><div><div style={{ ...labelStyle, color: enabled ? '#ffc300' : 'rgba(255,255,255,.45)' }}>{provider.phase}</div><h3 style={{ margin: '4px 0 0', fontSize: 23, letterSpacing: '-.025em' }}>{provider.name}</h3><div style={{ color: 'rgba(255,255,255,.54)', fontSize: 13 }}>{provider.subtitle}</div></div><button onClick={() => toggleProvider(provider.name)} className="hub-chip provider-toggle" style={{ padding: '7px 11px', borderRadius: 999, border: '1px solid rgba(26,240,255,.3)', background: 'rgba(26,240,255,.08)', color: '#1af0ff', fontSize: 12, fontWeight: 900 }}>{enabled ? 'Disable' : 'Enable'}</button></div><div className="provider-visual-grid" style={{ display: 'grid', gridTemplateColumns: 'repeat(4, minmax(0, 1fr))', gap: 10 }}>{provider.visual.map(item => <div key={item} className="provider-visual">{item}</div>)}</div><div className="provider-content-grid" style={{ display: 'grid', gridTemplateColumns: 'minmax(0, 1fr) minmax(210px, .72fr)', gap: 14, alignItems: 'start' }}><div><h4 style={{ margin: '0 0 10px', fontSize: 16 }}>What SignalBoost can monitor:</h4><ul style={{ margin: 0, paddingLeft: 18, color: 'rgba(255,255,255,.74)', lineHeight: 1.7, fontSize: 13 }}>{provider.automate.map(item => <li key={item}>{item}</li>)}</ul></div><div style={{ padding: 14, borderRadius: 18, border: '1px solid rgba(255,255,255,.1)', background: 'linear-gradient(135deg, rgba(255,195,0,.08), rgba(255,255,255,.035))' }}><h4 style={{ margin: '0 0 8px', fontSize: 16 }}>Why users care:</h4><p style={{ margin: 0, color: 'rgba(255,255,255,.72)', lineHeight: 1.5, fontSize: 13 }}>{provider.why}</p></div></div></article> })}
        </div>
      </main>
    </div>
  )
}
