import { sendEmail } from '@/lib/email'

type EmailResult = { ok: boolean; skipped?: boolean; reason?: string; error?: string; id?: string }
type PreviewArgs = { campaignId: string; title: string; objective: string; channel: string; contact?: string; dashboardUrl?: string }
type PublishedArgs = PreviewArgs & { liveUrl?: string; publicationDate?: string }
function ownerEmail() { return String((process.env.OWNER_EMAILS || '').split(',')[0] || process.env.OWNER_EMAIL || process.env.SIGNALBOOST_OWNER_EMAIL || process.env.ADMIN_EMAIL || '').trim().toLowerCase() }
function appBaseUrl() { return (process.env.NEXT_PUBLIC_APP_URL || process.env.NEXT_PUBLIC_SITE_URL || 'https://saas.signalboostapp.com').replace(/\/$/, '') }
function dashboardLink(campaignId: string) { return `${appBaseUrl()}/dashboard/marketing/press-print?campaign=${encodeURIComponent(campaignId)}` }
async function sendOwnerMail(subject: string, html: string): Promise<EmailResult> { const to = ownerEmail(); if (!to) return { ok: false, skipped: true, reason: 'missing_owner_email' }; const sent = await sendEmail({ from: 'saasMarketing', to, subject, html }); if (!sent?.ok) return { ok: false, error: sent?.error || 'send failed' }; return { ok: true, id: sent.id } }
function escapeHtml(value: string) { return String(value || '').replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;').replace(/'/g, '&#39;') }
function buttonLink(url: string, label: string, background = '#ffc300', color = '#020617') { return `<a href="${escapeHtml(url)}" style="display:inline-block;margin:6px 8px 6px 0;padding:12px 16px;border-radius:10px;background:${background};color:${color};font-weight:800;text-decoration:none">${escapeHtml(label)}</a>` }
export async function sendPressPrintPreviewEmail(args: PreviewArgs): Promise<EmailResult> { const reviewUrl = args.dashboardUrl || dashboardLink(args.campaignId); return sendOwnerMail(`Press & Print preview ready for approval: ${args.title || 'campaign'}`, `<p>COS has prepared a Press & Print Media campaign for owner review.</p><p><strong>${escapeHtml(args.title || 'Press & Print campaign')}</strong></p><p><strong>Campaign:</strong> ${escapeHtml(args.campaignId)}</p><p><strong>Channel:</strong> ${escapeHtml(args.channel || 'press-print')}</p>${args.contact ? `<p><strong>Verified free publisher target:</strong> ${escapeHtml(args.contact)}</p>` : ''}<p><strong>Preview:</strong></p><div style="white-space:pre-wrap;border:1px solid #e2e8f0;border-radius:12px;padding:12px;background:#f8fafc;color:#0f172a">${escapeHtml(args.objective || 'No preview text was provided.')}</div><p>${buttonLink(reviewUrl, 'Open and approve campaign')}</p><p>Approval authorizes submission to the verified free newspaper, magazine, or publication target. It does not mean the article is already published.</p>`) }
export async function sendPressPrintPublishedEmail(args: PublishedArgs): Promise<EmailResult> { const location = args.liveUrl || args.dashboardUrl || dashboardLink(args.campaignId); return sendOwnerMail(`Press & Print published/completed: ${args.title || 'campaign'}`, `<p>A Press & Print Media campaign has been marked published/completed.</p><p><strong>${escapeHtml(args.title || 'Press & Print campaign')}</strong></p><p><strong>Campaign:</strong> ${escapeHtml(args.campaignId)}</p><p><strong>Channel:</strong> ${escapeHtml(args.channel || 'press-print')}</p>${args.contact ? `<p><strong>Publisher/contact:</strong> ${escapeHtml(args.contact)}</p>` : ''}${args.publicationDate ? `<p><strong>Publication date:</strong> ${escapeHtml(args.publicationDate)}</p>` : ''}<p><strong>Publication/proof location:</strong> <a href="${escapeHtml(location)}">${escapeHtml(location)}</a></p><p><strong>Final published/placed content preview:</strong></p><div style="white-space:pre-wrap;border:1px solid #e2e8f0;border-radius:12px;padding:12px;background:#f8fafc;color:#0f172a">${escapeHtml(args.objective || 'No campaign text was provided.')}</div>`) }
