// saas/app/api/hub/audit/pdf/route.ts
// Server-side PDF export for audit reports. The UI still supports browser print,
// but this route returns a real application/pdf download with no extra package.

import { NextResponse } from 'next/server'
import { requireAdmin } from '@/lib/auth/access'
import { getAdminSupabase } from '@/utils/supabase/server'
import { getReportSnapshot } from '@/lib/audit/snapshotCache'
import { createSimplePdf, objectLines, type PdfDoc } from '@/lib/audit/simplePdf'
import { buildExecutiveSummary } from '@/lib/audit/execSummary'
import { buildProviderInventory } from '@/lib/audit/providerInventory'
import { buildIdentityAccessReport } from '@/lib/audit/reports'
import { buildSecretsReport } from '@/lib/audit/secretsReport'
import { buildGithubReport } from '@/lib/audit/githubReport'
import { buildVercelReport } from '@/lib/audit/vercelReport'
import { buildSupabaseReport } from '@/lib/audit/supabaseReport'
import { buildStripeReport } from '@/lib/audit/stripeReport'
import { buildComplianceReport } from '@/lib/audit/complianceReport'
import { buildRemediationRoadmap } from '@/lib/audit/remediationRoadmap'

export const dynamic = 'force-dynamic'
export const runtime = 'nodejs'
export const maxDuration = 60

type ExportableReport =
  | 'executive-summary'
  | 'provider-inventory'
  | 'identity-access'
  | 'secrets-keys'
  | 'github-changes'
  | 'vercel-deployment'
  | 'supabase-security'
  | 'stripe-config'
  | 'compliance-readiness'
  | 'remediation-roadmap'

const TITLES: Record<ExportableReport, string> = {
  'executive-summary': 'Executive Risk Summary',
  'provider-inventory': 'Provider Inventory Report',
  'identity-access': 'Identity & Access Review',
  'secrets-keys': 'Secrets & API Key Exposure Report',
  'github-changes': 'Code Change Management Report',
  'vercel-deployment': 'Deployment & Env Var Report',
  'supabase-security': 'Database Security Report',
  'stripe-config': 'Billing Configuration Report',
  'compliance-readiness': 'Compliance Readiness Matrix',
  'remediation-roadmap': 'Remediation Roadmap',
}

function normalizeReport(value: string | null): ExportableReport | null {
  const v = String(value || '').trim().toLowerCase()
  return (Object.prototype.hasOwnProperty.call(TITLES, v) ? v : null) as ExportableReport | null
}

function buildPayload(report: ExportableReport, snapshot: any): unknown {
  switch (report) {
    case 'executive-summary': return buildExecutiveSummary(snapshot)
    case 'provider-inventory': return buildProviderInventory(snapshot)
    case 'identity-access': return buildIdentityAccessReport(snapshot)
    case 'secrets-keys': return buildSecretsReport(snapshot)
    case 'github-changes': return buildGithubReport(snapshot)
    case 'vercel-deployment': return buildVercelReport(snapshot)
    case 'supabase-security': return buildSupabaseReport(snapshot)
    case 'stripe-config': return buildStripeReport(snapshot)
    case 'compliance-readiness': return buildComplianceReport(snapshot)
    case 'remediation-roadmap': return buildRemediationRoadmap(snapshot)
  }
}

function summarize(report: ExportableReport, payload: any): string[] {
  if (report === 'executive-summary') {
    const s = payload?.score || {}
    return [
      `Readiness score: ${s.score ?? 'n/a'}/100`,
      `Findings: critical ${s.critical ?? 0}, high ${s.high ?? 0}, medium ${s.medium ?? 0}, low ${s.low ?? 0}, evidence required ${s.evidenceRequired ?? 0}`,
      `Top risks: ${Array.isArray(payload?.topRisks) ? payload.topRisks.length : 0}`,
    ]
  }
  if (payload?.summary && typeof payload.summary === 'object') return objectLines(payload.summary)
  if (Array.isArray(payload?.rows)) return [`Rows: ${payload.rows.length}`]
  return []
}

function buildPdfDoc(report: ExportableReport, payload: any): PdfDoc {
  const title = TITLES[report]
  const sections = [
    { heading: 'Summary', lines: summarize(report, payload) },
    { heading: 'Report Data', lines: objectLines(payload).slice(0, 320) },
  ]
  return {
    title,
    subtitle: 'SignalBoost Audit Center export. Readiness assessment only; this is not an official compliance certification.',
    sections,
    footer: 'Generated by SignalBoost. Secret values are never included in exported reports.',
  }
}

export async function GET(req: Request) {
  const guard = await requireAdmin()
  if (!guard.ok) return NextResponse.json({ ok: false, error: guard.error }, { status: guard.status })

  const url = new URL(req.url)
  const report = normalizeReport(url.searchParams.get('report'))
  if (!report) {
    return NextResponse.json({ ok: false, error: 'Unsupported report id.' }, { status: 400 })
  }

  try {
    const snapshot = await getReportSnapshot(getAdminSupabase())
    const payload = buildPayload(report, snapshot)
    const pdf = createSimplePdf(buildPdfDoc(report, payload))
    const pdfBody = new Uint8Array(pdf.length)
    pdfBody.set(pdf)
    const filename = `${report}-${new Date().toISOString().slice(0, 10)}.pdf`
    return new Response(pdfBody, {
      status: 200,
      headers: {
        'Content-Type': 'application/pdf',
        'Content-Disposition': `attachment; filename="${filename}"`,
        'Cache-Control': 'no-store',
      },
    })
  } catch (err) {
    const message = err instanceof Error ? err.message : 'Failed to generate PDF.'
    return NextResponse.json({ ok: false, error: message }, { status: 500 })
  }
}
