import { createHash } from 'node:crypto'
import type { LearningSourceDocument, RelevanceScore } from '../../cos-core/layers/learning/cycle.ts'
import type { ContinuousLearningSourceKind } from '../../cos-core/layers/learning/index.ts'
export type DirectedStudyGates={distinctTerms(text:string):string[];relevanceOf(doc:LearningSourceDocument,terms:{anchors:string[];supporting:string[]}):RelevanceScore;sourceAwareRelevant(doc:LearningSourceDocument,score:RelevanceScore,terms:{anchors:string[];supporting:string[]}):boolean;candidate0Confidence(doc:LearningSourceDocument,score:RelevanceScore):number}
export type DirectedMaterialKind='book'|'article'|'video'|'documentation'|'own_notes'
export const DIRECTED_SOURCE_KIND:Record<DirectedMaterialKind,ContinuousLearningSourceKind>={book:'library_material',article:'news_article',video:'video_transcript',documentation:'official_documentation',own_notes:'work_experience'}
export type DirectedStudySubmission={topic:string;studyIntent:string;materialKind:DirectedMaterialKind;license:string;sourceUri:string;sourceTitle?:string|null;text:string;submittedBy?:string|null;observedAt?:string|null}
export type DirectedChunkVerdict={index:number;contentHash:string;admitted:boolean;reason:'admitted'|'not_relevant_to_intent'|'too_short';confidence:number;coverage:number;matchedTerms:string[];summary:string}
export type DirectedStudyAssessment={ok:boolean;error?:string;sourceKind:ContinuousLearningSourceKind|null;subject:string;chunks:DirectedChunkVerdict[];admitted:number;rejected:number}
export const CHUNK_TARGET_CHARACTERS=4000,MAX_CHUNKS_PER_SUBMISSION=20,MINIMUM_CHUNK_CHARACTERS=200,MAX_SUBMISSION_CHARACTERS=CHUNK_TARGET_CHARACTERS*MAX_CHUNKS_PER_SUBMISSION
const clean=(v:unknown)=>String(v??'').replace(/\s+/g,' ').trim()
export function validateDirectedSubmission(s:DirectedStudySubmission){if(clean(s.topic).length<4)return'topic is required (min 4 characters)';if(clean(s.studyIntent).length<12)return'studyIntent is required (min 12 characters)';if(!clean(s.license))return'license is required';if(!(s.materialKind in DIRECTED_SOURCE_KIND))return'materialKind is invalid';if(!clean(s.sourceUri))return'sourceUri is required';if(String(s.text||'').trim().length<MINIMUM_CHUNK_CHARACTERS)return`text is too short to study (min ${MINIMUM_CHUNK_CHARACTERS} characters)`;return null}
export function chunkDirectedText(raw:string){const source=String(raw||'').replace(/\r\n/g,'\n').trim(),truncated=source.length>MAX_SUBMISSION_CHARACTERS;const paras=source.slice(0,MAX_SUBMISSION_CHARACTERS).split(/\n{2,}/).map(x=>x.trim()).filter(Boolean);const chunks:string[]=[];let current='';for(const paragraph of paras){if(current&&current.length+paragraph.length+2>CHUNK_TARGET_CHARACTERS){chunks.push(current);current=paragraph}else current=current?`${current}\n\n${paragraph}`:paragraph;if(chunks.length>=MAX_CHUNKS_PER_SUBMISSION)break}if(current&&chunks.length<MAX_CHUNKS_PER_SUBMISSION)chunks.push(current);return{chunks,truncated:truncated||chunks.length>=MAX_CHUNKS_PER_SUBMISSION}}
export const directedContentHash=(uri:string,chunk:string)=>createHash('sha256').update(`directed:${clean(uri)}:${chunk}`).digest('hex')
export function assessDirectedStudy(s:DirectedStudySubmission,g:DirectedStudyGates):DirectedStudyAssessment{const subject=clean(s.topic).slice(0,180),invalid=validateDirectedSubmission(s);if(invalid)return{ok:false,error:invalid,sourceKind:null,subject,chunks:[],admitted:0,rejected:0};const anchors=g.distinctTerms(subject).slice(0,8),set=new Set(anchors),terms={anchors,supporting:g.distinctTerms(clean(s.studyIntent)).filter(x=>!set.has(x)).slice(0,12)},sourceKind=DIRECTED_SOURCE_KIND[s.materialKind];const chunks=chunkDirectedText(s.text).chunks.map((chunk,index)=>{const contentHash=directedContentHash(s.sourceUri,chunk);if(chunk.length<MINIMUM_CHUNK_CHARACTERS)return{index,contentHash,admitted:false as const,reason:'too_short' as const,confidence:0,coverage:0,matchedTerms:[],summary:''};const doc:LearningSourceDocument={sourceKind,sourceUri:clean(s.sourceUri).slice(0,700),sourceTitle:clean(s.sourceTitle)||undefined,observedAt:s.observedAt||undefined,subject,text:chunk,license:clean(s.license).slice(0,300)};const score=g.relevanceOf(doc,terms),relevant=g.sourceAwareRelevant(doc,score,terms),confidence=relevant?g.candidate0Confidence(doc,score):0;return{index,contentHash,admitted:relevant&&confidence>0,reason:(relevant&&confidence>0?'admitted':'not_relevant_to_intent') as 'admitted'|'not_relevant_to_intent',confidence,coverage:Number(score.coverage.toFixed(3)),matchedTerms:[...score.anchorsMatched,...score.supportingMatched].slice(0,12),summary:relevant?clean(chunk).slice(0,1500):''}});const admitted=chunks.filter(x=>x.admitted).length;return{ok:true,sourceKind,subject,chunks,admitted,rejected:chunks.length-admitted}}
export function directedEvidence(s:DirectedStudySubmission){return['owner_directed_study',`submitted_by:${clean(s.submittedBy||'owner').slice(0,120)}`,`study_intent:${clean(s.studyIntent).slice(0,300)}`,`material_kind:${s.materialKind}`]}
