import { cosServiceDb } from '@/lib/cos-core/storage/supabase'
import { candidate0Confidence, distinctTerms, relevanceOf, sourceAwareRelevant } from '@/lib/cos-core/layers/learning/cycle'
import { fetchReadableDocument, isFetchableDocumentUrl } from '@/lib/cos-core/layers/learning/documentFetch'
import { assessDirectedStudy, chunkDirectedText, directedEvidence, type DirectedStudySubmission } from '@/lib/ai/cos/directedStudy'
const gates={candidate0Confidence,distinctTerms,relevanceOf,sourceAwareRelevant}
export type DirectedStudyResult={ok:boolean;error?:string;resolvedFrom:'document_fetch'|'pasted_text'|null;assessment:ReturnType<typeof assessDirectedStudy>|null;stored:number;duplicates:number;errors:string[]}
export async function runDirectedStudy(input:{submission:Omit<DirectedStudySubmission,'text'>&{text?:string|null};dryRun?:boolean}):Promise<DirectedStudyResult>{const result:DirectedStudyResult={ok:false,resolvedFrom:null,assessment:null,stored:0,duplicates:0,errors:[]};let text=String(input.submission.text||'').trim();if(text)result.resolvedFrom='pasted_text';else{if(!isFetchableDocumentUrl(input.submission.sourceUri)){result.error='URL is not fetchable under document-reader guards; paste text instead.';return result}text=await fetchReadableDocument(input.submission.sourceUri,{maxCharacters:80000})||'';if(!text){result.error='The page produced no readable text under document-reader guards.';return result}result.resolvedFrom='document_fetch'}const submission:DirectedStudySubmission={...input.submission,text};const assessment=assessDirectedStudy(submission,gates);result.assessment=assessment;if(!assessment.ok){result.error=assessment.error;return result}result.ok=true;if(input.dryRun)return result;const db=cosServiceDb();if(!db){result.errors.push('COS service database is not configured; nothing was stored.');return result}const chunks=chunkDirectedText(text).chunks,evidence=directedEvidence(submission),observedAt=submission.observedAt||new Date().toISOString();for(const verdict of assessment.chunks.filter(x=>x.admitted)){const write=await db.from('cos_continuous_learning').insert({content_hash:verdict.contentHash,source_kind:assessment.sourceKind,source_uri:submission.sourceUri.slice(0,700),source_title:submission.sourceTitle?.slice(0,300)||null,observed_at:observedAt,subject:assessment.subject,summary:clean(chunks[verdict.index]).slice(0,8000),facts:[],confidence:verdict.confidence,license:submission.license.slice(0,300),evidence});if(write.error){if(String(write.error.code)==='23505')result.duplicates++;else result.errors.push(`store:${write.error.message.slice(0,300)}`)}else result.stored++}return result}
const clean=(v:unknown)=>String(v??'').replace(/\s+/g,' ').trim()
export async function readDirectedStudyHistory(limit=50){const db=cosServiceDb();if(!db)return{ok:false,error:'COS service database is not configured'};const result=await db.from('cos_continuous_learning').select('content_hash,source_kind,source_uri,source_title,subject,confidence,license,observed_at,created_at').contains('evidence',['owner_directed_study']).order('created_at',{ascending:false}).limit(Math.max(1,Math.min(200,Math.floor(limit))));return result.error?{ok:false,error:result.error.message.slice(0,300)}:{ok:true,records:result.data||[]}}
