// saas/lib/ai/cos/evidenceSourceUseTurnContext.ts
//
// Request-local correlation envelope for learned-corpus source attribution and the reasoner turn id.
//
// The enterprise answer path already has three pieces at different moments:
//   1. selected learned rows (before prompt rendering),
//   2. the reasoner's generated turn_id,
//   3. final [CL#] citation indices.
// AsyncLocalStorage lets those pieces meet without global mutable state, duplicate retrieval, or
// threading a parallel structure through the large enterprise reasoner function.

import { AsyncLocalStorage } from 'node:async_hooks'
import { currentAdaptiveRetrievalShadowPolicy, type AdaptiveRetrievalShadowPolicy } from '@/lib/ai/cos/adaptiveRetrievalContext'

export type CapturedLearnedRetrievalItem = {
  sourceKind: string
  similarity: number | null
  contentHash: string | null
  summaryChars: number
}

export type CapturedEvidenceSourceUseTurn = {
  turnId: string
  sourceKinds: string[]
  items: CapturedLearnedRetrievalItem[]
  citedIndices: number[]
  retrievalPolicy: AdaptiveRetrievalShadowPolicy | null
}

type EvidenceSourceUseTurnState = {
  turnId: string | null
  selectedSourceKinds: string[]
  selectedItems: CapturedLearnedRetrievalItem[]
  retrievalPolicy: AdaptiveRetrievalShadowPolicy | null
  citedIndices: number[]
  answerAssessed: boolean
}

const storage = new AsyncLocalStorage<EvidenceSourceUseTurnState>()

function freshState(): EvidenceSourceUseTurnState {
  return {
    turnId: null,
    selectedSourceKinds: [],
    selectedItems: [],
    retrievalPolicy: null,
    citedIndices: [],
    answerAssessed: false,
  }
}

function state(): EvidenceSourceUseTurnState {
  const existing = storage.getStore()
  if (existing) return existing
  const created = freshState()
  storage.enterWith(created)
  return created
}

/** Explicitly reset correlation at the start of a top-level COS or benchmark turn. */
export function beginEvidenceSourceUseTurn(): void {
  const current = state()
  current.turnId = null
  current.selectedSourceKinds = []
  current.selectedItems = []
  current.retrievalPolicy = null
  current.citedIndices = []
  current.answerAssessed = false
}

function selectedValue(row: unknown): Record<string, unknown> {
  const value = row && typeof row === 'object' ? row as Record<string, unknown> : {}
  const item = value.item && typeof value.item === 'object' ? value.item as Record<string, unknown> : {}
  return { ...item, ...value }
}

function sourceKindFromSelectedRow(row: unknown): string {
  const value = selectedValue(row)
  const kind = String(value.source_kind ?? 'unknown').trim().toLowerCase()
  return /^[a-z0-9_-]+$/.test(kind) ? kind : 'unknown'
}

function itemFromSelectedRow(row: unknown): CapturedLearnedRetrievalItem {
  const value = selectedValue(row)
  const similarityRaw = value.similarity
  const similarityNumber = similarityRaw == null ? null : Number(similarityRaw)
  const summary = String(value.summary ?? '')
  const hash = String(value.content_hash ?? '').trim()
  return {
    sourceKind: sourceKindFromSelectedRow(row),
    similarity: similarityNumber != null && Number.isFinite(similarityNumber)
      ? Math.max(0, Math.min(1, similarityNumber))
      : null,
    contentHash: hash || null,
    summaryChars: Math.max(0, summary.length),
  }
}

/** Capture exact selected learned rows before they are converted to rendered [CL#] strings. */
export function captureSelectedLearnedRows(rows: readonly unknown[]): void {
  const current = state()
  // Selection marks the beginning of a new possible source-use measurement in this async chain.
  // Clear any stale correlation first so background/test reuse can never join one turn to another.
  current.turnId = null
  current.citedIndices = []
  current.answerAssessed = false
  current.selectedItems = Array.isArray(rows) ? rows.map(itemFromSelectedRow) : []
  current.selectedSourceKinds = current.selectedItems.map(item => item.sourceKind)
  current.retrievalPolicy = currentAdaptiveRetrievalShadowPolicy()
}

/** Backward-compatible alias retained for existing callers/tests. */
export function captureSelectedLearnedSourceKinds(rows: readonly unknown[]): void {
  captureSelectedLearnedRows(rows)
}

/** Capture the UUID already generated by callCosReasoner / turnExperience. */
export function captureEvidenceSourceUseTurnId(turnId: string): void {
  const value = String(turnId ?? '').trim()
  if (!value) return
  state().turnId = value
}

/** Read the active reasoner turn id without consuming source-use attribution. */
export function peekEvidenceSourceUseTurnId(): string | null {
  return storage.getStore()?.turnId ?? null
}

/** Mark that the final answer's learned-corpus citations were actually inspected — even if zero. */
export function captureLearnedCitationIndices(indices: readonly number[]): void {
  const current = state()
  current.citedIndices = [...new Set((Array.isArray(indices) ? indices : [])
    .map(value => Math.floor(Number(value)))
    .filter(value => Number.isFinite(value) && value > 0))]
  current.answerAssessed = true
}

/**
 * Consume once at the ordinary turn-learning boundary. No answer => no answer assessment => no row.
 * Cache hits likewise have no local reasoning turn_id and therefore cannot be miscounted as injected.
 */
export function consumeEvidenceSourceUseTurn(): CapturedEvidenceSourceUseTurn | null {
  const current = storage.getStore()
  if (!current) return null
  const snapshot = current.turnId && current.answerAssessed && current.selectedSourceKinds.length > 0
    ? {
        turnId: current.turnId,
        sourceKinds: [...current.selectedSourceKinds],
        items: current.selectedItems.map(item => ({ ...item })),
        citedIndices: [...current.citedIndices],
        retrievalPolicy: current.retrievalPolicy ? { ...current.retrievalPolicy } : null,
      }
    : null

  current.turnId = null
  current.selectedSourceKinds = []
  current.selectedItems = []
  current.retrievalPolicy = null
  current.citedIndices = []
  current.answerAssessed = false
  return snapshot
}
