import { cosServiceDb } from '@/lib/cos-core/storage/supabase'
import { MAX_RETEST_PROMOTIONS_PER_CYCLE, scanRetestCandidates, selectRetestBatch, summarizeRetestScan, type PendingCandidateRow, type RetainedKnowledgeRow } from '@/lib/ai/cos/evidenceTriggeredRetest'
export const RETEST_DEFAULT_LOOKBACK_DAYS=14
const candidateLimit=100,knowledgeLimit=200
export type EvidenceRetestSummary={enabled:boolean;candidatesExamined:number;knowledgeExamined:number;promoted:number;verdicts:ReturnType<typeof summarizeRetestScan>|null;promotedCases:Array<{candidateId:string;caseId:string;track:string;sourceKind:string|null;coverage:number}>;errors:string[]}
const since=(days:number)=>new Date(Date.now()-Math.max(1,Math.min(90,Math.floor(days)))*86400000).toISOString()
function candidate(row:Record<string,unknown>):PendingCandidateRow{return{id:String(row.id||''),track:String(row.track||''),sanitizedPrompt:String(row.sanitized_prompt||''),occurrenceCount:Number(row.occurrence_count??1),lastSeenAt:row.last_seen_at?String(row.last_seen_at):null}}
function knowledge(row:Record<string,unknown>):RetainedKnowledgeRow{return{contentHash:String(row.content_hash||''),subject:String(row.subject||''),summary:String(row.summary||''),sourceKind:String(row.source_kind||''),sourceTitle:row.source_title?String(row.source_title):null,observedAt:row.observed_at?String(row.observed_at):null,createdAt:row.created_at?String(row.created_at):null,confidence:Number(row.confidence??0)}}
export async function runEvidenceTriggeredRetest(options:{lookbackDays?:number;maxPromotions?:number;dryRun?:boolean}={}):Promise<EvidenceRetestSummary>{
 const summary:EvidenceRetestSummary={enabled:false,candidatesExamined:0,knowledgeExamined:0,promoted:0,verdicts:null,promotedCases:[],errors:[]};const db=cosServiceDb();if(!db)return summary;summary.enabled=true
 const [pendingResult,knowledgeResult]=await Promise.all([db.from('cos_capability_benchmark_candidates').select('id,track,sanitized_prompt,occurrence_count,last_seen_at').eq('status','pending').order('occurrence_count',{ascending:false}).order('last_seen_at',{ascending:false}).limit(candidateLimit),db.from('cos_continuous_learning').select('content_hash,subject,summary,source_kind,source_title,observed_at,created_at,confidence').gte('created_at',since(options.lookbackDays??RETEST_DEFAULT_LOOKBACK_DAYS)).order('created_at',{ascending:false}).limit(knowledgeLimit)])
 if(pendingResult.error)summary.errors.push(`candidates:${pendingResult.error.message.slice(0,300)}`);if(knowledgeResult.error)summary.errors.push(`knowledge:${knowledgeResult.error.message.slice(0,300)}`)
 const pending=((pendingResult.data||[])as Record<string,unknown>[]).map(candidate).filter(x=>x.id),facts=((knowledgeResult.data||[])as Record<string,unknown>[]).map(knowledge).filter(x=>x.contentHash);summary.candidatesExamined=pending.length;summary.knowledgeExamined=facts.length
 const assessed=scanRetestCandidates(pending,facts);summary.verdicts=summarizeRetestScan(assessed);const batch=selectRetestBatch(assessed,options.maxPromotions??MAX_RETEST_PROMOTIONS_PER_CYCLE);if(options.dryRun||!batch.length)return summary
 const source=new Map(pending.map(row=>[row.id,row]));for(const retest of batch){const item=source.get(retest.candidateId);if(!item)continue;const now=new Date().toISOString();const created=await db.from('cos_capability_benchmark_cases').insert({active:true,track:item.track,prompt:item.sanitizedPrompt,required_terms:[],forbidden_terms:[],requires_local_reasoning:true,origin:'evidence_arrival',source_candidate_id:item.id,difficulty_score:Math.min(5,1+Math.log2(Math.max(1,Number(item.occurrenceCount)||1))),promoted_at:now}).select('id').single();if(created.error||!created.data){summary.errors.push(`promote:${String(created.error?.message||'case insert failed').slice(0,300)}`);continue}const updated=await db.from('cos_capability_benchmark_candidates').update({status:'promoted',promoted_case_id:created.data.id,promoted_at:now}).eq('id',item.id).eq('status','pending').select('id').maybeSingle();if(updated.error||!updated.data){await db.from('cos_capability_benchmark_cases').delete().eq('id',created.data.id);summary.errors.push(`promote:${String(updated.error?.message||'candidate claim lost').slice(0,300)}`);continue}const event=await db.from('cos_evidence_retest_events').insert({candidate_id:item.id,benchmark_case_id:created.data.id,track:retest.track,content_hash:retest.contentHash,source_kind:retest.sourceKind,matched_terms:retest.matchedTerms,coverage:retest.coverage,rationale:retest.rationale});if(event.error)summary.errors.push(`event:${event.error.message.slice(0,300)}`);summary.promoted++;summary.promotedCases.push({candidateId:item.id,caseId:String(created.data.id),track:retest.track,sourceKind:retest.sourceKind,coverage:retest.coverage})}
 return summary
}
export async function readEvidenceRetestReport(limit=50){const db=cosServiceDb();if(!db)return{ok:false,error:'COS service database is not configured'};const[pending,events]=await Promise.all([db.from('cos_capability_benchmark_candidates').select('id',{count:'exact',head:true}).eq('status','pending'),db.from('cos_evidence_retest_events').select('candidate_id,benchmark_case_id,track,source_kind,coverage,created_at').order('created_at',{ascending:false}).limit(Math.max(1,Math.min(200,Math.floor(limit))))]);if(pending.error||events.error)return{ok:false,error:String(pending.error?.message||events.error?.message).slice(0,300)};return{ok:true,pendingCandidates:pending.count??0,evidenceArrivalRetests:events.data||[]}}
