// saas/lib/ai/cos/evidenceSourceUseTurnContext.ts
//
// Request-local correlation envelope for learned-corpus source attribution and the reasoner turn id.
//
// The enterprise answer path already has three pieces at different moments:
//   1. selected learned rows (before prompt rendering),
//   2. the reasoner's generated turn_id,
//   3. final [CL#] citation indices.
// AsyncLocalStorage lets those pieces meet without global mutable state, duplicate retrieval, or
// threading a parallel structure through the large enterprise reasoner function.

import { AsyncLocalStorage } from 'node:async_hooks'

export type CapturedEvidenceSourceUseTurn = {
  turnId: string
  sourceKinds: string[]
  citedIndices: number[]
}

type EvidenceSourceUseTurnState = {
  turnId: string | null
  selectedSourceKinds: string[]
  citedIndices: number[]
  answerAssessed: boolean
}

const storage = new AsyncLocalStorage<EvidenceSourceUseTurnState>()

function freshState(): EvidenceSourceUseTurnState {
  return { turnId: null, selectedSourceKinds: [], citedIndices: [], answerAssessed: false }
}

function state(): EvidenceSourceUseTurnState {
  const existing = storage.getStore()
  if (existing) return existing
  const created = freshState()
  storage.enterWith(created)
  return created
}

/** Explicitly reset correlation at the start of a top-level COS or benchmark turn. */
export function beginEvidenceSourceUseTurn(): void {
  const current = state()
  current.turnId = null
  current.selectedSourceKinds = []
  current.citedIndices = []
  current.answerAssessed = false
}

function sourceKindFromSelectedRow(row: unknown): string {
  const value = row as { source_kind?: unknown; item?: { source_kind?: unknown } } | null
  const raw = value?.source_kind ?? value?.item?.source_kind ?? 'unknown'
  const kind = String(raw ?? '').trim().toLowerCase()
  return /^[a-z0-9_-]+$/.test(kind) ? kind : 'unknown'
}

/** Capture exact selected learned rows before they are converted to rendered [CL#] strings. */
export function captureSelectedLearnedSourceKinds(rows: readonly unknown[]): void {
  const current = state()
  // Selection marks the beginning of a new possible source-use measurement in this async chain.
  // Clear any stale correlation first so background/test reuse can never join one turn to another.
  current.turnId = null
  current.citedIndices = []
  current.answerAssessed = false
  current.selectedSourceKinds = Array.isArray(rows) ? rows.map(sourceKindFromSelectedRow) : []
}

/** Capture the UUID already generated by callCosReasoner / turnExperience. */
export function captureEvidenceSourceUseTurnId(turnId: string): void {
  const value = String(turnId ?? '').trim()
  if (!value) return
  state().turnId = value
}

/** Read the active reasoner turn id without consuming source-use attribution. */
export function peekEvidenceSourceUseTurnId(): string | null {
  return storage.getStore()?.turnId ?? null
}

/** Mark that the final answer's learned-corpus citations were actually inspected — even if zero. */
export function captureLearnedCitationIndices(indices: readonly number[]): void {
  const current = state()
  current.citedIndices = [...new Set((Array.isArray(indices) ? indices : [])
    .map(value => Math.floor(Number(value)))
    .filter(value => Number.isFinite(value) && value > 0))]
  current.answerAssessed = true
}

/**
 * Consume once at the ordinary turn-learning boundary. No answer => no answer assessment => no row.
 * Cache hits likewise have no local reasoning turn_id and therefore cannot be miscounted as injected.
 */
export function consumeEvidenceSourceUseTurn(): CapturedEvidenceSourceUseTurn | null {
  const current = storage.getStore()
  if (!current) return null
  const snapshot = current.turnId && current.answerAssessed && current.selectedSourceKinds.length > 0
    ? {
        turnId: current.turnId,
        sourceKinds: [...current.selectedSourceKinds],
        citedIndices: [...current.citedIndices],
      }
    : null

  current.turnId = null
  current.selectedSourceKinds = []
  current.citedIndices = []
  current.answerAssessed = false
  return snapshot
}
