// Pure detector for COS's own deterministic provenance-report replies.
//
// Provenance replies are views over the previous substantive answer; they are intentionally not
// stored as new substantive answer lineage. A second paraphrase therefore needs to recognize that
// the preceding assistant text is a provenance report and keep reading the same stored turn.

export function isCosGeneratedProvenanceReply(text: string | undefined): boolean {
  const value = String(text || '').trim()
  if (!value) return false
  return /^(?:That answer was (?:generated by COS's reasoning model|reused from COS's semantic cache|produced by a COS server-side utility)|This is the real, recorded provenance|The immediately preceding reply is already the recorded provenance report|I don't have a real provenance record|No tengo un registro de procedencia real|Não tenho um registro de procedência real)/i.test(value)
    || /\b(?:Primary Reasoner|Material Contributors|Recorded Influence Interpretation|LIVE SYSTEM STATE)\b/i.test(value)
}
