'use client'

import { LocalizedText } from '@/components/i18n/LocalizedText'
import Link from 'next/link'
import { useEffect, useState, type CSSProperties } from 'react'
import { useTranslation } from '@/components/i18n/useTranslation'
import { uiText } from '@/lib/i18n/uiText'

type Campaign = { id: string; title?: string; objective?: string; status?: string; metadata?: Record<string, any> }
type Decision = 'ok' | 'no' | 'staff' | 'submitted' | 'published'
const PRESS_PRINT_CHANNELS = ['online-newspapers', 'print-newspapers', 'trade-press'] as const
const channelLabels: Record<string, string> = { 'online-newspapers': "Digital newspaper", 'print-newspapers': "Print newspaper", 'trade-press': "IT magazine / trade press" }
function channel(campaign: Campaign) { return String(campaign.metadata?.outreach_channel || campaign.metadata?.media_channel || '') }
function review(campaign: Campaign) { return String(campaign.metadata?.press_print_review || 'PENDING').toUpperCase() }
function stage(campaign: Campaign) { return String(campaign.metadata?.press_print_execution_stage || campaign.metadata?.press_print_execution?.stage || 'not_started') }
function labelStage(value: string) { if (value === 'approved') return 'Ready to submit'; if (value === 'submitted_to_publisher') return 'Submitted to publisher'; if (value === 'published') return 'Published / completed'; if (value === 'staff_support') return 'Staff support'; if (value === 'on_hold') return 'On hold'; if (value === 'rejected') return 'Rejected'; if (value === 'stopped') return 'Stopped'; if (value === 'target_selection_required') return 'Publisher target required'; return 'Needs review' }
function Action({ id, decision, children, primary = false }: { id: string; decision: Decision; children: React.ReactNode; primary?: boolean }) { return <form method="post" action="/api/marketing/press-print/decision" style={{ display: 'inline-grid', gap: 8 }}><input type="hidden" name="id" value={id} /><input type="hidden" name="decision" value={decision} /><button style={primary ? primaryButton : secondaryButton}>{children}</button></form> }
export default function PressPrintMediaPage() {
  const [campaigns, setCampaigns] = useState<Campaign[]>([])
  const [loading, setLoading] = useState(true)
  const { t } = useTranslation()
  useEffect(() => { let live = true; (async () => { try { const res = await fetch('/api/marketing/press-print', { cache: 'no-store' }); const json = await res.json(); if (live) setCampaigns((Array.isArray(json.campaigns) ? json.campaigns : []).filter((row: Campaign) => PRESS_PRINT_CHANNELS.includes(channel(row) as any))) } finally { if (live) setLoading(false) } })(); return () => { live = false } }, [])
  return <main style={shell}>
    <section style={hero}><p className="sb-eyebrow">{uiText('generatedUi.u_dcba31525bd63b56')}</p><h1 style={h1}><LocalizedText fallback={uiText('generatedUi.u_ba2f8d68f462717f')} /></h1><p style={body}>{t('marketingSales.pressPrint.description', "Automated Press & Print only accepts free, real newspaper/magazine/publication targets unless the user explicitly asks for paid advertising. The target must include a publisher/editor email or a real submit-news/contact form.")}</p><div style={{ display: 'flex', gap: 10, flexWrap: 'wrap' }}><Link href="/dashboard/marketing/press-print/direct" className="sb-button-primary">{t('marketingSales.pressPrint.startStaffLedCampaign', "Start staff-led campaign")}</Link></div></section>
    {loading ? <p className="sb-body">{uiText('generatedUi.u_ba3bbbe10d8bef66')}</p> : null}
    {!loading && campaigns.length === 0 ? <section style={card}><p style={body}><LocalizedText fallback={uiText('generatedUi.u_6899bd59ae3d5376')} /></p></section> : null}
    {campaigns.map((campaign) => { const currentReview = review(campaign), currentStage = stage(campaign), approved = currentReview === 'APPROVED', submitted = currentStage === 'submitted_to_publisher' || campaign.metadata?.publisher_submission_status === 'submitted', completed = currentStage === 'published', exec = campaign.metadata?.press_print_execution || {}; const publisher = String(campaign.metadata?.publisher_name || campaign.metadata?.publication_name || ''), publisherEmail = String(campaign.metadata?.publisher_email || ''), publisherForm = String(campaign.metadata?.publisher_submission_form_url || ''), sourceUrl = String(campaign.metadata?.publisher_discovery_source_url || ''); const hasPublisherTarget = Boolean(publisher && (publisherEmail || publisherForm)), paidRequested = campaign.metadata?.automation_mode === 'automated_paid_user_requested'; return <section key={campaign.id} style={card}>
      <div style={{ display: 'flex', justifyContent: 'space-between', gap: 12, flexWrap: 'wrap' }}><div><p className="sb-eyebrow">{channelLabels[channel(campaign)] || uiText('generatedUi.u_85c253de08e70759')}</p><h2 style={h2}>{String(campaign.title || "Press campaign").slice(0, 120)}</h2><p style={{ ...body, whiteSpace: 'pre-wrap', maxHeight: 120, overflow: 'hidden' }}>{String(campaign.objective || "Campaign prepared inside Marketing + Sales.").slice(0, 300)}{String(campaign.objective || '').length > 300 ? '…' : ''}</p></div><strong style={pill}>{currentReview} · {labelStage(currentStage)}</strong></div>
      <div style={targetBox}><h3 style={h3}>{paidRequested ? uiText('generatedUi.u_646f4403d6cb817a') : uiText('generatedUi.u_18238f7c9ad4b122')}</h3>{hasPublisherTarget ? <p style={body}>{uiText('generatedUi.u_a830b3f1a9dca539')}<strong>{publisher}</strong><br /><LocalizedText fallback={uiText('generatedUi.u_48708414bf63393e')} /><strong>{publisherEmail ? uiText('generatedUi.u_8c99309070b1681c') : paidRequested ? uiText('generatedUi.u_6e1e38f5115a6bd8') : uiText('generatedUi.u_ad314c1be14c24f4')}</strong><br />{uiText('generatedUi.u_890d34fffcde315c')}{publisherEmail || publisherForm}{sourceUrl ? <><br />{uiText('generatedUi.u_8b3d3d068d6ce833')}{sourceUrl}</> : null}{paidRequested ? <><br /><strong>{uiText('generatedUi.u_ee327964a14f18f5')}</strong>{uiText('generatedUi.u_1782911d66f12dbe')}</> : null}</p> : <p style={body}><LocalizedText fallback={uiText('generatedUi.u_51d4658bdbb5b25d')} /></p>}</div>
      {!approved && !completed ? <div style={actions}><Action id={campaign.id} decision="ok" primary>{uiText('generatedUi.u_6007acbe30b2cd98')}</Action><Action id={campaign.id} decision="no">{uiText('generatedUi.u_ab604a360777735f')}</Action><Action id={campaign.id} decision="staff"><LocalizedText fallback={uiText('generatedUi.u_9939e76315d42e7a')} /></Action></div> : null}
      <div style={workflowBox}><h3 style={h3}>{completed ? uiText('generatedUi.u_11a6767d5674c7e4') : submitted ? uiText('generatedUi.u_40bc8af163ec8a65') : approved ? uiText('generatedUi.u_298a9207a732a11d') : uiText('generatedUi.u_9928dd82f38fb093')}</h3>{!approved && !completed ? <p style={body}>{uiText('generatedUi.u_543d52ded0375c37')}{paidRequested ? uiText('generatedUi.u_90b990955bb94300') : uiText('generatedUi.u_f116f127ae72f12c')}{uiText('generatedUi.u_1d53ae482cffc842')}</p> : null}{approved && !submitted && !completed ? <div style={simpleForm}><p style={body}><LocalizedText fallback={uiText('generatedUi.u_eb46cf280f4dfbea')} /></p>{hasPublisherTarget ? <Action id={campaign.id} decision="submitted" primary><LocalizedText fallback={uiText('generatedUi.u_44e814ac93cf7593')} /></Action> : <p style={body}><LocalizedText fallback={uiText('generatedUi.u_fa4c51ae2cbe3dab')} /></p>}</div> : null}{submitted && !completed ? <form method="post" action="/api/marketing/press-print/decision" style={simpleForm}><input type="hidden" name="id" value={campaign.id} /><input type="hidden" name="decision" value="published" /><p style={body}><LocalizedText fallback={uiText('generatedUi.u_97f960ff55065de5')} /></p><input name="live_url" defaultValue={String(exec.live_url || '')} placeholder={uiText('generatedUi.u_e812fc5e43e4450a')} style={input} /><input name="publication_date" type="date" defaultValue={String(exec.publication_date || '')} style={input} /><button style={primaryButton}><LocalizedText fallback={uiText('generatedUi.u_57fc7131202225e3')} /></button></form> : null}{completed ? <div style={doneBox}><p style={body}><LocalizedText fallback={uiText('generatedUi.u_e43923a17647078e')} /></p>{exec.live_url ? <a href={String(exec.live_url)} target="_blank" rel="noreferrer" style={link}>{uiText('generatedUi.u_ce059a563b26bbaa')}</a> : null}{exec.publication_date ? <p style={body}>{uiText('generatedUi.u_d7c6c024083756dd')}{String(exec.publication_date)}</p> : null}</div> : null}</div>
    </section> })}
  </main>
}
const shell: CSSProperties = { maxWidth: 1160, margin: '0 auto', display: 'grid', gap: 18 }
const hero: CSSProperties = { border: '1px solid rgba(244,114,182,.24)', borderRadius: 24, padding: 24, background: 'linear-gradient(145deg, rgba(15,23,42,.94), rgba(2,6,23,.98))' }
const card: CSSProperties = { border: '1px solid rgba(255,255,255,.10)', borderRadius: 22, padding: 20, background: 'linear-gradient(145deg, rgba(3,7,18,.88), rgba(15,23,42,.76))' }
const workflowBox: CSSProperties = { border: '1px solid rgba(56,189,248,.22)', borderRadius: 14, padding: 14, marginTop: 16, background: 'rgba(56,189,248,.06)' }
const targetBox: CSSProperties = { border: '1px solid rgba(250,204,21,.22)', borderRadius: 14, padding: 14, marginTop: 16, background: 'rgba(250,204,21,.06)' }
const doneBox: CSSProperties = { display: 'grid', gap: 8, maxWidth: 640, marginTop: 10 }
const actions: CSSProperties = { display: 'flex', gap: 8, flexWrap: 'wrap', marginTop: 16 }
const simpleForm: CSSProperties = { display: 'grid', gap: 10, maxWidth: 560, marginTop: 12 }
const body: CSSProperties = { color: 'rgba(255,255,255,.72)', lineHeight: 1.65, maxWidth: 860 }
const h1: CSSProperties = { color: '#fff', fontSize: 34, margin: '8px 0' }
const h2: CSSProperties = { color: '#fff', fontSize: 24, margin: '6px 0' }
const h3: CSSProperties = { color: '#fff', margin: 0, fontSize: 18 }
const pill: CSSProperties = { color: '#fde68a', border: '1px solid rgba(255,195,0,.35)', borderRadius: 999, padding: '8px 12px', alignSelf: 'start' }
const input: CSSProperties = { width: '100%', borderRadius: 10, border: '1px solid rgba(255,255,255,.14)', background: 'rgba(15,23,42,.76)', color: '#fff', padding: '9px 10px' }
const primaryButton: CSSProperties = { border: 'none', background: '#ffc300', color: '#000', borderRadius: 12, padding: '10px 14px', fontWeight: 900, cursor: 'pointer' }
const secondaryButton: CSSProperties = { border: '1px solid rgba(255,255,255,.16)', background: 'rgba(255,255,255,.06)', color: '#fff', borderRadius: 12, padding: '10px 14px', fontWeight: 850, cursor: 'pointer' }
const link: CSSProperties = { color: '#67e8f9', fontWeight: 850, textDecoration: 'underline' }
