-- Mission 002: durable lifecycle records and a transactional, server-only outbox.
create table if not exists public.mission_records (
 mission_id text primary key, mission_type text not null, revision integer not null check (revision > 0), status text not null, environment text not null, title text not null, objective text not null, correlation_id text not null, source_event_ids jsonb not null, risk_level text not null, created_at timestamptz not null, updated_at timestamptz not null, metadata jsonb not null default '{}'::jsonb, schema_version text not null
);
create table if not exists public.mission_outbox (
 event_id text primary key, topic text not null, payload jsonb not null, status text not null default 'pending' check(status in ('pending','published','failed','dead_lettered')), retries integer not null default 0, created_at timestamptz not null, published_at timestamptz, failure_reason text
);
create index if not exists mission_outbox_pending_idx on public.mission_outbox(status, created_at);
create table if not exists public.mission_event_inbox (idempotency_key text primary key, first_processed_at timestamptz not null);
alter table public.mission_records enable row level security; alter table public.mission_outbox enable row level security; alter table public.mission_event_inbox enable row level security;
-- Only service-role/server RPCs mutate these tables; no client policies are granted.
create or replace function public.mission_create_with_outbox(p_mission jsonb, p_topic text, p_event jsonb) returns public.mission_records language plpgsql security definer set search_path=public as $$ declare result public.mission_records; begin insert into mission_records select (jsonb_populate_record(null::mission_records,p_mission)).* returning * into result; insert into mission_outbox(event_id,topic,payload,status,retries,created_at) values(p_event->>'eventId',p_topic,p_event,'pending',0,(p_event->>'occurredAt')::timestamptz); return result; end $$;
create or replace function public.mission_mark_outbox_failure(p_event_id text,p_reason text,p_dead_letter boolean) returns void language sql security definer set search_path=public as $$ update mission_outbox set retries=retries+1,failure_reason=left(p_reason,1000),status=case when p_dead_letter then 'dead_lettered' else 'failed' end where event_id=p_event_id $$;
create or replace function public.mission_outbox_diagnostics() returns jsonb language sql security definer set search_path=public as $$ select jsonb_build_object('pendingOutbox',count(*) filter(where status in ('pending','failed')),'oldestPendingEvent',min(created_at) filter(where status in ('pending','failed')),'publishedCount',count(*) filter(where status='published'),'failedCount',count(*) filter(where status='failed'),'retryCount',coalesce(sum(retries),0),'queueDepth',count(*) filter(where status in ('pending','failed')),'duplicateCount',0,'replayCount',0,'deadLetterCount',count(*) filter(where status='dead_lettered')) from mission_outbox $$;
