-- Durable, read-only observations for the Self-Healing Supervisor native probes.
-- Service-role only: RLS is enabled and no client policy is created.

create table if not exists public.self_healing_native_probe_samples (
  id bigint generated by default as identity primary key,
  probe_id text not null check (probe_id in ('api','database','storage','certificate')),
  target text not null,
  observed_at timestamptz not null default now(),
  status text not null check (status in ('healthy','warning','critical','error')),
  latency_ms integer,
  error_rate numeric(7,6),
  metric_value numeric,
  metric_unit text,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists self_healing_native_probe_samples_lookup_idx
  on public.self_healing_native_probe_samples (probe_id, target, observed_at desc);

create index if not exists self_healing_native_probe_samples_observed_idx
  on public.self_healing_native_probe_samples (observed_at desc);

alter table public.self_healing_native_probe_samples enable row level security;

-- Connection-pressure data cannot be obtained honestly through a normal table read.
-- This security-definer function exposes only bounded aggregate health values, never
-- query text, users, credentials, database names, or connection source addresses.
create or replace function public.self_healing_database_probe()
returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
  v_active_connections bigint := 0;
  v_active_queries bigint := 0;
  v_max_connections integer := 1;
  v_longest_query_seconds numeric := 0;
begin
  select count(*)
    into v_active_connections
    from pg_stat_activity
   where backend_type = 'client backend';

  select count(*)
    into v_active_queries
    from pg_stat_activity
   where backend_type = 'client backend'
     and state = 'active'
     and pid <> pg_backend_pid();

  select greatest(coalesce(current_setting('max_connections', true)::integer, 1), 1)
    into v_max_connections;

  select coalesce(max(extract(epoch from (clock_timestamp() - query_start))), 0)
    into v_longest_query_seconds
    from pg_stat_activity
   where backend_type = 'client backend'
     and state = 'active'
     and pid <> pg_backend_pid()
     and query_start is not null;

  return jsonb_build_object(
    'observed_at', clock_timestamp(),
    'active_connections', v_active_connections,
    'active_queries', v_active_queries,
    'max_connections', v_max_connections,
    'connection_pressure_pct', round((v_active_connections::numeric / v_max_connections::numeric) * 100, 2),
    'longest_query_seconds', round(v_longest_query_seconds, 2)
  );
end;
$$;

revoke all on function public.self_healing_database_probe() from public;
grant execute on function public.self_healing_database_probe() to service_role;

-- Storage health uses the actual Supabase Storage catalog. A deployment may provide
-- SELF_HEALING_STORAGE_QUOTA_BYTES; without a configured quota the probe still reports
-- real bytes/object/bucket counts but intentionally does not invent a capacity percent.
create or replace function public.self_healing_storage_probe(quota_bytes bigint default null)
returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, public, storage
as $$
declare
  v_bucket_count bigint := 0;
  v_object_count bigint := 0;
  v_bytes_used numeric := 0;
  v_capacity_pct numeric := null;
begin
  select count(*) into v_bucket_count from storage.buckets;
  select count(*) into v_object_count from storage.objects;

  select coalesce(sum(
    case
      when metadata ? 'size' and (metadata ->> 'size') ~ '^[0-9]+$'
        then (metadata ->> 'size')::numeric
      else 0
    end
  ), 0)
  into v_bytes_used
  from storage.objects;

  if quota_bytes is not null and quota_bytes > 0 then
    v_capacity_pct := round((v_bytes_used / quota_bytes::numeric) * 100, 2);
  end if;

  return jsonb_build_object(
    'observed_at', clock_timestamp(),
    'bucket_count', v_bucket_count,
    'object_count', v_object_count,
    'bytes_used', v_bytes_used,
    'quota_bytes', quota_bytes,
    'capacity_pct', v_capacity_pct
  );
end;
$$;

revoke all on function public.self_healing_storage_probe(bigint) from public;
grant execute on function public.self_healing_storage_probe(bigint) to service_role;
