-- saas/supabase/migrations/20260816_cos_knowledge_fact_revisions.sql
--
-- Item 3 (long-term memory quality) at the FACT level. Skills already have this — cognitiveConsolidation.ts
-- weakens stale skills and cos_learning_promotions audits every status change. cos_knowledge_facts had
-- neither: upsertFact() silently overwrote the object on any (task_id,subject,predicate) collision with
-- zero audit trail, and nothing ever revisited a fact's confidence as it aged. This table is the audit
-- trail; the decay/pruning/contradiction logic lives in cognitiveFactConsolidation.ts, not in SQL.

create table if not exists public.cos_knowledge_fact_revisions (
  id bigint generated by default as identity primary key,
  task_id text not null,
  subject text not null,
  predicate text not null,
  revision_kind text not null check (revision_kind in ('contradiction', 'staleness_decay', 'pruned')),
  previous_object text,
  previous_confidence double precision,
  new_object text,
  new_confidence double precision,
  reason text,
  created_at timestamptz not null default now()
);

create index if not exists cos_knowledge_fact_revisions_lookup_idx
  on public.cos_knowledge_fact_revisions(task_id, subject, predicate, created_at desc);

alter table public.cos_knowledge_fact_revisions enable row level security;

comment on table public.cos_knowledge_fact_revisions is
  'Audit trail for fact-level memory-quality events: a contradicting source overwriting a fact, confidence decaying with age, or a fact being pruned once confidence falls below the floor. Facts do not silently change under COS; every change is auditable, same as skill status changes already are.';
