-- COS skill composition / transfer learning.
--
-- A composite procedure is not validated because its member skills are validated. It must prove
-- independent transfer advantage over the strongest single member on the same unseen cases.

create table if not exists public.cos_cognitive_skill_compositions (
  id uuid primary key default gen_random_uuid(),
  composition_key text not null unique,
  source_gap_id uuid references public.cos_learning_gaps(id) on delete set null,
  title text not null,
  description text,
  problem_class text not null,
  member_skill_keys text[] not null,
  plan jsonb not null default '{}'::jsonb,
  status text not null default 'candidate' check (status in (
    'candidate','evaluated','practiced','validated','learned','weakened','quarantined'
  )),
  evaluator_approved boolean not null default false,
  practice_attempts integer not null default 0 check (practice_attempts >= 0),
  practice_successes integer not null default 0 check (practice_successes >= 0 and practice_successes <= practice_attempts),
  transfer_attempts integer not null default 0 check (transfer_attempts >= 0),
  transfer_successes integer not null default 0 check (transfer_successes >= 0 and transfer_successes <= transfer_attempts),
  distinct_transfer_variants integer not null default 0 check (distinct_transfer_variants >= 0),
  composite_score_total double precision not null default 0 check (composite_score_total >= 0),
  best_member_score_total double precision not null default 0 check (best_member_score_total >= 0),
  composite_win_count integer not null default 0 check (composite_win_count >= 0 and composite_win_count <= transfer_attempts),
  failure_count integer not null default 0 check (failure_count >= 0),
  last_validated_at timestamptz,
  weakened_at timestamptz,
  quarantined_at timestamptz,
  quarantine_reason text,
  promoted_skill_key text,
  provenance jsonb not null default '{}'::jsonb,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (cardinality(member_skill_keys) between 2 and 4)
);

create unique index if not exists cos_cognitive_skill_compositions_source_gap_unique_idx
  on public.cos_cognitive_skill_compositions(source_gap_id)
  where source_gap_id is not null;
create index if not exists cos_cognitive_skill_compositions_status_idx
  on public.cos_cognitive_skill_compositions(status, updated_at desc);

create table if not exists public.cos_cognitive_composition_trials (
  id uuid primary key default gen_random_uuid(),
  composition_key text not null references public.cos_cognitive_skill_compositions(composition_key) on delete cascade,
  variant_key text not null,
  exercise_kind text not null check (exercise_kind in ('practice','transfer')),
  prompt text not null,
  rubric jsonb not null default '{}'::jsonb,
  generation_source text not null check (generation_source in (
    'local_generator','frontier_teacher','curated','production_replay'
  )),
  status text not null default 'queued' check (status in (
    'queued','running','passed','failed','blocked','discarded'
  )),
  attempt_count integer not null default 0 check (attempt_count >= 0),
  max_attempts integer not null default 1 check (max_attempts between 1 and 2),
  composite_score double precision check (composite_score is null or (composite_score >= 0 and composite_score <= 1)),
  composite_success boolean,
  best_member_skill_key text,
  best_member_score double precision check (best_member_score is null or (best_member_score >= 0 and best_member_score <= 1)),
  best_member_success boolean,
  baseline_scores jsonb not null default '[]'::jsonb,
  evidence jsonb not null default '{}'::jsonb,
  next_attempt_at timestamptz not null default now(),
  started_at timestamptz,
  completed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(composition_key, exercise_kind, variant_key),
  check (exercise_kind <> 'transfer' or generation_source <> 'local_generator')
);

create index if not exists cos_cognitive_composition_trials_due_idx
  on public.cos_cognitive_composition_trials(status, next_attempt_at, created_at);
create index if not exists cos_cognitive_composition_trials_composition_idx
  on public.cos_cognitive_composition_trials(composition_key, created_at desc);

create table if not exists public.cos_cognitive_composition_promotions (
  id bigint generated by default as identity primary key,
  composition_key text not null references public.cos_cognitive_skill_compositions(composition_key) on delete cascade,
  from_status text not null,
  to_status text not null,
  evidence jsonb not null default '{}'::jsonb,
  policy_version text not null default 'composition-transfer-v1',
  reason text,
  created_at timestamptz not null default now()
);

create index if not exists cos_cognitive_composition_promotions_key_time_idx
  on public.cos_cognitive_composition_promotions(composition_key, created_at desc);

alter table public.cos_cognitive_skill_compositions enable row level security;
alter table public.cos_cognitive_composition_trials enable row level security;
alter table public.cos_cognitive_composition_promotions enable row level security;

comment on table public.cos_cognitive_skill_compositions is
  'Candidate and validated multi-skill procedures. Member validation is necessary but not sufficient; transfer advantage over the strongest single member is required.';
comment on table public.cos_cognitive_composition_trials is
  'Local practice and independent transfer trials for skill composition. Locally generated cases cannot count as transfer validation.';

create or replace function public.cos_record_cognitive_composition_trial_result(
  p_trial_id uuid,
  p_composite_success boolean,
  p_composite_score double precision,
  p_best_member_skill_key text default null,
  p_best_member_success boolean default null,
  p_best_member_score double precision default null,
  p_baseline_scores jsonb default '[]'::jsonb,
  p_evidence jsonb default '{}'::jsonb
) returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  q public.cos_cognitive_composition_trials%rowtype;
  c public.cos_cognitive_skill_compositions%rowtype;
  now_at timestamptz := now();
  next_attempt integer;
  next_status text;
  composite_won boolean := false;
begin
  if p_composite_score < 0 or p_composite_score > 1 then
    raise exception 'composite_score_out_of_range';
  end if;
  if p_best_member_score is not null and (p_best_member_score < 0 or p_best_member_score > 1) then
    raise exception 'best_member_score_out_of_range';
  end if;

  select * into q
  from public.cos_cognitive_composition_trials
  where id = p_trial_id
  for update;
  if q.id is null then raise exception 'composition_trial_not_found'; end if;
  if q.status <> 'running' then raise exception 'composition_trial_not_running'; end if;

  select * into c
  from public.cos_cognitive_skill_compositions
  where composition_key = q.composition_key
  for update;
  if c.id is null then raise exception 'composition_not_found'; end if;

  if q.exercise_kind = 'transfer' then
    if p_best_member_skill_key is null or p_best_member_score is null or p_best_member_success is null then
      raise exception 'transfer_requires_single_member_baseline';
    end if;
    if not (p_best_member_skill_key = any(c.member_skill_keys)) then
      raise exception 'baseline_skill_not_a_composition_member';
    end if;
    composite_won := p_composite_score >= p_best_member_score + 0.02;
  end if;

  next_attempt := q.attempt_count + 1;
  next_status := case
    when p_composite_success then 'passed'
    when next_attempt >= q.max_attempts then 'failed'
    else 'queued'
  end;

  update public.cos_cognitive_composition_trials
  set status = next_status,
      attempt_count = next_attempt,
      composite_score = p_composite_score,
      composite_success = p_composite_success,
      best_member_skill_key = p_best_member_skill_key,
      best_member_score = p_best_member_score,
      best_member_success = p_best_member_success,
      baseline_scores = coalesce(p_baseline_scores, '[]'::jsonb),
      evidence = coalesce(p_evidence, '{}'::jsonb),
      completed_at = case when next_status in ('passed','failed') then now_at else null end,
      next_attempt_at = case when next_status = 'queued' then now_at + interval '15 minutes' else next_attempt_at end,
      updated_at = now_at
  where id = q.id;

  update public.cos_cognitive_skill_compositions
  set practice_attempts = practice_attempts + case when q.exercise_kind = 'practice' then 1 else 0 end,
      practice_successes = practice_successes + case when q.exercise_kind = 'practice' and p_composite_success then 1 else 0 end,
      transfer_attempts = transfer_attempts + case when q.exercise_kind = 'transfer' then 1 else 0 end,
      transfer_successes = transfer_successes + case when q.exercise_kind = 'transfer' and p_composite_success then 1 else 0 end,
      distinct_transfer_variants = distinct_transfer_variants + case when q.exercise_kind = 'transfer' and q.attempt_count = 0 then 1 else 0 end,
      composite_score_total = composite_score_total + case when q.exercise_kind = 'transfer' then p_composite_score else 0 end,
      best_member_score_total = best_member_score_total + case when q.exercise_kind = 'transfer' then coalesce(p_best_member_score,0) else 0 end,
      composite_win_count = composite_win_count + case when q.exercise_kind = 'transfer' and composite_won then 1 else 0 end,
      failure_count = failure_count + case when p_composite_success then 0 else 1 end,
      last_validated_at = case when q.exercise_kind = 'transfer' and p_composite_success then now_at else last_validated_at end,
      updated_at = now_at
  where id = c.id;

  return jsonb_build_object(
    'trialId', q.id,
    'compositionKey', c.composition_key,
    'kind', q.exercise_kind,
    'status', next_status,
    'compositeWon', composite_won,
    'attemptCount', next_attempt
  );
end;
$$;

revoke all on function public.cos_record_cognitive_composition_trial_result(uuid,boolean,double precision,text,boolean,double precision,jsonb,jsonb) from public;
grant execute on function public.cos_record_cognitive_composition_trial_result(uuid,boolean,double precision,text,boolean,double precision,jsonb,jsonb) to service_role;
