-- Service-only delivery ledger for COS owner briefings and deduplicated alerts.
create table if not exists public.cos_owner_briefing_items (
  id bigint generated by default as identity primary key,
  owner_email text not null,
  source_type text not null check (source_type in ('gmail','supervisor')),
  source_id text not null,
  severity text not null check (severity in ('urgent','important','routine')),
  title text not null,
  detail text not null default '',
  observed_at timestamptz not null,
  first_seen_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  notified_at timestamptz,
  unique (owner_email, source_type, source_id)
);
create index if not exists cos_owner_briefing_items_pending_idx
  on public.cos_owner_briefing_items (owner_email, severity, observed_at desc)
  where notified_at is null;

create table if not exists public.cos_owner_briefing_runs (
  id bigint generated by default as identity primary key,
  owner_email text not null,
  report_date date not null,
  kind text not null check (kind = 'daily'),
  item_count integer not null default 0 check (item_count >= 0),
  delivered_at timestamptz not null default now(),
  unique (owner_email, report_date, kind)
);

alter table public.cos_owner_briefing_items enable row level security;
alter table public.cos_owner_briefing_runs enable row level security;
revoke all on public.cos_owner_briefing_items from anon, authenticated;
revoke all on public.cos_owner_briefing_runs from anon, authenticated;
grant select, insert, update, delete on public.cos_owner_briefing_items to service_role;
grant select, insert, update, delete on public.cos_owner_briefing_runs to service_role;
grant usage, select on sequence public.cos_owner_briefing_items_id_seq to service_role;
grant usage, select on sequence public.cos_owner_briefing_runs_id_seq to service_role;

comment on table public.cos_owner_briefing_items is
  'Service-only deduplication ledger for Gmail metadata and Self-Healing Supervisor items selected for the owner.';
comment on table public.cos_owner_briefing_runs is
  'Service-only proof of daily COS owner brief delivery.';
