-- COS active learning: durable practice/holdout work and auditable lifecycle promotions.
--
-- A queued exercise is not knowledge. Passing practice is not held-out validation. The queue keeps
-- those evidence classes explicit so a locally generated practice case can never masquerade as an
-- independent holdout. All writes are service-role runtime operations; RLS remains enabled.

create table if not exists public.cos_active_practice_queue (
  id uuid primary key default gen_random_uuid(),
  skill_key text not null references public.cos_cognitive_skills(skill_key) on delete cascade,
  teacher_lesson_id bigint references public.cos_teacher_lessons(id) on delete set null,
  variant_key text not null,
  exercise_kind text not null check (exercise_kind in ('practice','holdout')),
  prompt text not null,
  rubric jsonb not null default '{}'::jsonb,
  generation_source text not null check (generation_source in (
    'local_generator',
    'frontier_teacher',
    'curated',
    'production_replay'
  )),
  evaluator_mode text not null default 'deterministic_rubric' check (evaluator_mode in (
    'deterministic_rubric',
    'production_outcome'
  )),
  status text not null default 'queued' check (status in (
    'queued','running','passed','failed','blocked','discarded'
  )),
  attempt_count integer not null default 0 check (attempt_count >= 0),
  max_attempts integer not null default 1 check (max_attempts between 1 and 5),
  last_score double precision check (last_score is null or (last_score >= 0 and last_score <= 1)),
  last_error text,
  metadata jsonb not null default '{}'::jsonb,
  next_attempt_at timestamptz not null default now(),
  started_at timestamptz,
  completed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(skill_key, exercise_kind, variant_key),
  check (exercise_kind <> 'holdout' or generation_source <> 'local_generator')
);

create index if not exists cos_active_practice_queue_status_due_idx
  on public.cos_active_practice_queue(status, next_attempt_at, created_at);
create index if not exists cos_active_practice_queue_skill_idx
  on public.cos_active_practice_queue(skill_key, created_at desc);

create table if not exists public.cos_learning_promotions (
  id bigint generated by default as identity primary key,
  skill_key text not null references public.cos_cognitive_skills(skill_key) on delete cascade,
  from_status text not null,
  to_status text not null,
  evidence jsonb not null default '{}'::jsonb,
  policy_version text not null default 'cognitive-promotion-v1',
  reason text,
  created_at timestamptz not null default now()
);

create index if not exists cos_learning_promotions_skill_time_idx
  on public.cos_learning_promotions(skill_key, created_at desc);

alter table public.cos_active_practice_queue enable row level security;
alter table public.cos_learning_promotions enable row level security;

comment on table public.cos_active_practice_queue is
  'Durable COS practice and independent-holdout work. Local-generator exercises are practice only; holdouts must originate from an independent/curated/replay source.';
comment on table public.cos_learning_promotions is
  'Auditable evidence snapshots for cognitive-skill lifecycle transitions. Promotion evidence is separate from live answer confidence.';

-- Atomically finish one exercise and increment the matching evidence counters. The application
-- recomputes lifecycle eligibility afterward using the versioned deterministic promotion policy.
create or replace function public.cos_record_cognitive_practice_result(
  p_queue_id uuid,
  p_success boolean,
  p_score double precision,
  p_answer text,
  p_evidence jsonb default '{}'::jsonb
) returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  q public.cos_active_practice_queue%rowtype;
  next_attempt integer;
  next_status text;
  now_at timestamptz := now();
  skill_snapshot jsonb;
begin
  if p_score < 0 or p_score > 1 then
    raise exception 'score_out_of_range';
  end if;

  select * into q
  from public.cos_active_practice_queue
  where id = p_queue_id
  for update;

  if q.id is null then
    raise exception 'practice_item_not_found';
  end if;
  if q.status <> 'running' then
    raise exception 'practice_item_not_running';
  end if;

  next_attempt := q.attempt_count + 1;
  next_status := case
    when p_success then 'passed'
    when next_attempt >= q.max_attempts then 'failed'
    else 'queued'
  end;

  update public.cos_active_practice_queue
  set attempt_count = next_attempt,
      status = next_status,
      last_score = p_score,
      last_error = case when p_success then null else coalesce(p_evidence->>'reason','evaluation_failed') end,
      completed_at = case when next_status in ('passed','failed') then now_at else null end,
      next_attempt_at = case when next_status = 'queued' then now_at + interval '15 minutes' else next_attempt_at end,
      updated_at = now_at
  where id = q.id;

  insert into public.cos_cognitive_experiences(
    experience_hash, subject, experience_kind, skill_key, variant_key,
    source_kind, source_ref, success, score, evidence,
    first_observed_at, last_observed_at, updated_at
  )
  select
    'practice_queue:' || q.id::text || ':' || next_attempt::text,
    s.subject,
    q.exercise_kind,
    q.skill_key,
    q.variant_key,
    q.generation_source,
    'cos_active_practice_queue:' || q.id::text,
    p_success,
    p_score,
    jsonb_build_object(
      'answer', left(coalesce(p_answer,''), 12000),
      'rubric', q.rubric,
      'evaluation', coalesce(p_evidence,'{}'::jsonb),
      'exerciseKind', q.exercise_kind,
      'generationSource', q.generation_source,
      'teacherLessonId', q.teacher_lesson_id
    ),
    now_at, now_at, now_at
  from public.cos_cognitive_skills s
  where s.skill_key = q.skill_key
  on conflict (experience_hash) do nothing;

  update public.cos_cognitive_skills
  set practice_attempts = practice_attempts + case when q.exercise_kind = 'practice' then 1 else 0 end,
      practice_successes = practice_successes + case when q.exercise_kind = 'practice' and p_success then 1 else 0 end,
      holdout_attempts = holdout_attempts + case when q.exercise_kind = 'holdout' then 1 else 0 end,
      holdout_successes = holdout_successes + case when q.exercise_kind = 'holdout' and p_success then 1 else 0 end,
      distinct_holdout_variants = distinct_holdout_variants + case when q.exercise_kind = 'holdout' and q.attempt_count = 0 then 1 else 0 end,
      failure_count = failure_count + case when p_success then 0 else 1 end,
      last_practiced_at = now_at,
      last_validated_at = case when q.exercise_kind = 'holdout' and p_success then now_at else last_validated_at end,
      updated_at = now_at
  where skill_key = q.skill_key;

  select jsonb_build_object(
    'skillKey', skill_key,
    'status', status,
    'evaluatorApproved', evaluator_approved,
    'understandingApproved', understanding_approved,
    'practiceAttempts', practice_attempts,
    'practiceSuccesses', practice_successes,
    'holdoutAttempts', holdout_attempts,
    'holdoutSuccesses', holdout_successes,
    'distinctHoldoutVariants', distinct_holdout_variants,
    'productionAttempts', production_attempts,
    'productionSuccesses', production_successes,
    'failureCount', failure_count,
    'lastValidatedAt', last_validated_at,
    'quarantined', quarantined_at is not null
  ) into skill_snapshot
  from public.cos_cognitive_skills
  where skill_key = q.skill_key;

  return jsonb_build_object(
    'queueId', q.id,
    'queueStatus', next_status,
    'attemptCount', next_attempt,
    'skill', skill_snapshot
  );
end;
$$;

revoke all on function public.cos_record_cognitive_practice_result(uuid,boolean,double precision,text,jsonb) from public;
grant execute on function public.cos_record_cognitive_practice_result(uuid,boolean,double precision,text,jsonb) to service_role;
