-- COS Phase 2 persistent intelligence store.
-- Knowledge belongs to COS and survives application deployments/provider changes.

create extension if not exists vector;

create table if not exists public.cos_knowledge_records (
  id uuid primary key default gen_random_uuid(),
  task_id text not null,
  prompt_text text not null,
  context_text text not null default '',
  embedding vector(1536) not null,
  response_data jsonb not null,
  created_at timestamptz not null default now()
);
create index if not exists cos_knowledge_records_task_created_idx on public.cos_knowledge_records(task_id, created_at desc);

create table if not exists public.cos_knowledge_facts (
  id text primary key,
  task_id text not null,
  subject text not null,
  predicate text not null,
  object text not null,
  confidence double precision not null default 1 check (confidence >= 0 and confidence <= 1),
  source text not null,
  updated_at timestamptz not null default now(),
  unique(task_id, subject, predicate)
);
create index if not exists cos_knowledge_facts_subject_idx on public.cos_knowledge_facts(task_id, subject);

create table if not exists public.cos_context_summaries (
  cache_key text primary key,
  summary jsonb not null,
  created_at timestamptz not null default now()
);

create table if not exists public.cos_learning_observations (
  id bigint generated by default as identity primary key,
  task_id text not null,
  capability text not null,
  strategy text not null,
  succeeded boolean not null,
  latency_ms integer not null default 0,
  external_cost_usd numeric(14,8) not null default 0,
  reusable boolean not null default false,
  created_at timestamptz not null default now()
);
create index if not exists cos_learning_capability_idx on public.cos_learning_observations(task_id, capability, created_at desc);

create table if not exists public.cos_ai_roi_metrics (
  id bigint generated by default as identity primary key,
  task_id text not null,
  source text not null,
  provider_calls integer not null default 0,
  estimated_provider_cost_usd numeric(14,8) not null default 0,
  estimated_cost_avoided_usd numeric(14,8) not null default 0,
  prompt_characters_before integer not null default 0,
  prompt_characters_after integer not null default 0,
  latency_ms integer not null default 0,
  created_at timestamptz not null default now()
);
create index if not exists cos_ai_roi_created_idx on public.cos_ai_roi_metrics(created_at desc);

create or replace function public.cos_match_knowledge(
  query_embedding vector(1536),
  match_task_id text,
  match_count integer default 1
)
returns table(response_data jsonb, similarity double precision)
language sql stable
as $$
  select k.response_data,
         1 - (k.embedding <=> query_embedding) as similarity
  from public.cos_knowledge_records k
  where k.task_id = match_task_id
  order by k.embedding <=> query_embedding
  limit greatest(match_count, 1);
$$;

-- These are server-side COS tables. Access is through the service role only.
alter table public.cos_knowledge_records enable row level security;
alter table public.cos_knowledge_facts enable row level security;
alter table public.cos_context_summaries enable row level security;
alter table public.cos_learning_observations enable row level security;
alter table public.cos_ai_roi_metrics enable row level security;
