-- Phase 7 durable Agent Workflow control-plane metadata. No source, output, prompt, artifact, secret, or credential columns.
create table if not exists public.agent_workflows (
 workflow_id text primary key, request_id text not null, user_id uuid not null, idempotency_key text not null, request_fingerprint text not null,
 status text not null check (status in ('pending','leased','cancelled','failed','succeeded','abandoned')), version bigint not null default 1 check(version > 0),
 lease_owner text, lease_token_hash text, lease_expires_at timestamptz, provider_id text, language text not null check(length(language) between 1 and 32), capabilities jsonb not null default '[]'::jsonb check(jsonb_typeof(capabilities)='array'), estimated_cost_units integer not null check(estimated_cost_units >= 0), quota_reservation_id text, quota_released boolean not null default false,
 cancellation_requested boolean not null default false, cancellation_reason_code text check(cancellation_reason_code is null or length(cancellation_reason_code)<=64), started_at timestamptz not null, updated_at timestamptz not null, completed_at timestamptz, result_kind text, failure_category text, failed_stage text, audit_sequence bigint not null default 0 check(audit_sequence >= 0), created_at timestamptz not null default now(),
 unique(user_id,idempotency_key), check ((lease_owner is null and lease_token_hash is null and lease_expires_at is null) or (lease_owner is not null and lease_token_hash ~ '^[a-f0-9]{64}$' and lease_expires_at is not null)), check((status in ('cancelled','failed','succeeded','abandoned')) = (completed_at is not null)), check(not quota_released or quota_reservation_id is not null)
);
create index if not exists agent_workflows_recoverable_idx on public.agent_workflows(updated_at,workflow_id); create index if not exists agent_workflows_expired_lease_idx on public.agent_workflows(lease_expires_at) where status in ('pending','leased'); create index if not exists agent_workflows_cancellation_idx on public.agent_workflows(updated_at) where cancellation_requested; create index if not exists agent_workflows_unreleased_quota_idx on public.agent_workflows(updated_at) where status in ('cancelled','failed','succeeded','abandoned') and not quota_released;
create table if not exists public.agent_workflow_recovery_locks(lock_name text primary key check(lock_name='agent-workflow-recovery'),owner_id text not null,token_hash text not null check(token_hash ~ '^[a-f0-9]{64}$'),acquired_at timestamptz not null,expires_at timestamptz not null,updated_at timestamptz not null);
alter table public.agent_workflows enable row level security; alter table public.agent_workflow_recovery_locks enable row level security;
create or replace function public.agent_workflow_compare_and_set(p_workflow_id text,p_expected_version bigint,p_status text,p_updated_at timestamptz) returns setof public.agent_workflows language plpgsql security invoker set search_path=public as $$ begin return query update public.agent_workflows set status=p_status,version=version+1,updated_at=p_updated_at where workflow_id=p_workflow_id and version=p_expected_version and p_status in ('pending','leased','cancelled','failed','succeeded','abandoned') returning *; end $$;
create or replace function public.agent_workflow_acquire_recovery_lock(p_owner_id text,p_token_hash text,p_now timestamptz,p_duration_ms integer) returns boolean language plpgsql security invoker set search_path=public as $$ begin insert into public.agent_workflow_recovery_locks as l(lock_name,owner_id,token_hash,acquired_at,expires_at,updated_at) values('agent-workflow-recovery',p_owner_id,p_token_hash,p_now,p_now+(p_duration_ms||' milliseconds')::interval,p_now) on conflict(lock_name) do update set owner_id=excluded.owner_id,token_hash=excluded.token_hash,acquired_at=excluded.acquired_at,expires_at=excluded.expires_at,updated_at=excluded.updated_at where l.expires_at<=p_now; return found; end $$;
create or replace function public.agent_workflow_renew_recovery_lock(p_owner_id text,p_token_hash text,p_now timestamptz,p_duration_ms integer) returns boolean language plpgsql security invoker set search_path=public as $$ begin update public.agent_workflow_recovery_locks set expires_at=p_now+(p_duration_ms||' milliseconds')::interval,updated_at=p_now where lock_name='agent-workflow-recovery' and owner_id=p_owner_id and token_hash=p_token_hash and expires_at>p_now; return found; end $$;
create or replace function public.agent_workflow_release_recovery_lock(p_owner_id text,p_token_hash text) returns boolean language plpgsql security invoker set search_path=public as $$ begin delete from public.agent_workflow_recovery_locks where lock_name='agent-workflow-recovery' and owner_id=p_owner_id and token_hash=p_token_hash; return found; end $$;
revoke all on public.agent_workflows, public.agent_workflow_recovery_locks from anon, authenticated; revoke all on function public.agent_workflow_compare_and_set(text,bigint,text,timestamptz), public.agent_workflow_acquire_recovery_lock(text,text,timestamptz,integer), public.agent_workflow_renew_recovery_lock(text,text,timestamptz,integer), public.agent_workflow_release_recovery_lock(text,text) from public, anon, authenticated;
