-- External escalation is a teacher signal, not factual knowledge.
-- Keep it in a separate queue so COS can learn from successful escalations without
-- silently treating another model's answer as verified truth.
create table if not exists public.cos_teacher_lessons (
  id bigint generated by default as identity primary key,
  prompt_hash text not null unique,
  prompt text not null,
  subject text,
  local_answer text,
  local_confidence double precision,
  escalation_reason text,
  teacher_answer text not null,
  teacher_provider text,
  teacher_model text,
  status text not null default 'captured' check (status in ('captured','evaluated','promoted','rejected')),
  repeat_count integer not null default 1 check (repeat_count >= 1),
  reuse_count integer not null default 0 check (reuse_count >= 0),
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists cos_teacher_lessons_status_updated_idx
  on public.cos_teacher_lessons(status, updated_at desc);
create index if not exists cos_teacher_lessons_subject_updated_idx
  on public.cos_teacher_lessons(subject, updated_at desc);

alter table public.cos_teacher_lessons enable row level security;

comment on table public.cos_teacher_lessons is
  'Durable teacher examples captured only after a successful external escalation. These are training/evaluation signals, not automatically trusted factual knowledge.';
