// saas/lib/portable-products/manifests/selfHealingSupervisor.ts
import type { PortableProductManifest } from '../manifestTypes.ts'

export const selfHealingSupervisorManifest: PortableProductManifest = Object.freeze({
  productId: 'self-healing-supervisor',
  displayName: 'Self-Healing Supervisor',
  categoryLabel: 'self-healing software',
  executionModes: Object.freeze([
    'automatic-unattended-repair-of-steps-that-are-not-financial-destructive-or-credential',
    'signed-approval-required-only-for-money-deletion-or-credential-changes',
    'you-authorise-each-incident-plan-once-then-its-safe-steps-run-unattended',
    'automatic-failover-from-api-to-browser-or-to-a-human',
    'the-browser-agent-works-inside-your-own-runtime-under-your-own-credentials',
    'a-clean-state-checkpoint-is-captured-before-any-repair-changes-anything',
    'atomic-restore-of-the-whole-execution-context-when-a-repair-does-not-verify',
    'repairs-that-cannot-be-checkpointed-are-blocked-before-they-start-not-after',
    'a-person-is-called-whenever-an-undo-would-be-unsafe-or-does-not-restore',
    'manual-operator-control-available-at-any-step',
  ]),
  shortDescription: 'Self-healing software: an AI-driven operations system with the COS AI brain that fixes failures through pre-integrated provider/API connectors, a browser when no API exists, or an operator. It is buyer-hosted, keeps consequential actions under human approval, and records evidence, reasoning and actions in an audit trail.',
  // Product-specific COS outreach guidance belongs here so other products keep their own rules.
  longDescription: 'A governed, buyer-hosted, AI-driven self-healing operations system whose COS AI brain detects failures, diagnoses causes from evidence and repairs them through registered APIs, pre-integrated providers/connectors, a browser agent inside the buyer runtime, or an operator. It checkpoints before changes, verifies repairs, restores the execution context when verification fails, and records evidence, reasoning, rules and actions for audit. Money, deletion and credential changes require explicit human approval. SELF-HEALING SUPERVISOR OUTREACH ONLY: every COS draft must communicate the relevant combination of AI-driven operations, self-healing, COS AI brain, buyer-hosted architecture, human approval, audit trail, pre-integrated providers/connectors and concrete operational benefits. Adapt emphasis to the recipient rather than listing features. MSP/cloud/DevOps: prioritize self-healing and lower MTTR, then cloud operations, with browser automation supporting. Banks/financial institutions: prioritize governance, auditability and buyer-hosted control; present human approval as buyer control. Healthcare: prioritize compliance-oriented controls, availability and governance, with self-healing supporting continuity. These weights change emphasis only and never authorize claims outside this manifest. COS creates a personalized pending draft for owner review and approval; drafting does not itself send.',
  category: 'infrastructure',
  status: 'live',
  maturity: 'production',
  publicVisible: true,
  licensingAvailable: true,
  targetAudience: Object.freeze([
    'managed service providers',
    'managed cloud providers',
    'DevOps and SRE consultancies',
    'platform operators',
    'reliability teams',
    'banks and financial institutions',
    'healthcare organizations',
  ]),
  requiredCapabilities: Object.freeze([
    'ai-driven-operations',
    'self-healing',
    'cos-ai-reasoning',
    'buyer-hosted-operation',
    'failure-detection',
    'repair-proposals',
    'approved-repair-execution',
    'human-approval-for-consequential-actions',
    'post-repair-verification',
    'automatic-rollback-on-failed-verification',
    'transactional-execution-boundaries',
    'point-in-time-state-restore',
    'auditable-evidence-and-reasoning',
    'pre-integrated-provider-and-api-connectors',
  ]),
  optionalCapabilities: Object.freeze(['approval-gates']),
  dependencies: Object.freeze(['supervisor-policy']),
  exclusions: Object.freeze([
    'unapproved-financial-destructive-or-credential-changes',
    'automatic-reversal-of-effects-already-observed-outside-your-systems',
    'execution-outside-your-registered-capability-list',
  ]),
  architectureReferences: Object.freeze(['supervisor', 'policy-engine', 'durable-coordination']),
  documentationReferences: Object.freeze(['docs/portables/self-healing-integration-guide.md']),
  futureFeatures: Object.freeze(['operator-catalog']),
  supportedLanguages: Object.freeze(['en', 'pt', 'es', 'pl', 'ru']),
})
