// Shared dashboard/plan wording. Authorization remains in host policy, not copy.
const COPY = {
  en: {
    subtitle: 'Monitor dependencies, investigate findings, and prepare routine remediation without repeated approval requests.',
    prepareTitle: 'Prepare remediation',
    prepareDescription: 'Routine planning and eligible branch proposals do not need human approval. The server verifies repository scope and patched versions first. Missing evidence blocks preparation, is shown to the owner, and never becomes an approval request. Merge, deployment, and consequential actions retain their policy checks.',
    humanQueue: 'Approvals requiring your decision', humanEmpty: 'No approval is waiting for your decision.',
    activeWork: 'Autonomous work and investigations', reviewHistory: 'Completed and closed history', approvalNotRequired: 'No approval pending',
    remediationPrepared: 'Plan recorded for automatic verification and branch preparation. No human approval was recorded.',
    remediationApproved: 'Preparation result recorded. Check the work status below.',
    fixApproved: 'Preparation is queued; a verified repair or deployment has not yet been established.',
    prPrepared: 'Branch proposal available. Validation and release checks still apply.',
    issueReviewSubtitle: 'This report describes detected dependency advisories. Planning is routine work; a report or proposed branch does not prove a completed repair.',
    planSummary: 'Dependency remediation plan recorded. No code change or completed repair is claimed by this plan.',
    safety: ['Routine proposal preparation is authorized by host policy, not a fabricated human approval.', 'Only verified dependency changes in the connected repository may enter an isolated branch.', 'Lockfile, tests, CI, merge and deployment checks remain mandatory before release. Consequential actions retain their approval boundary.'],
    validateDiff: 'Verify the diff and the required checks before integration; proposal preparation is not deployment.',
  },
  es: {
    subtitle: 'Monitorea dependencias, investiga hallazgos y prepara remediaciones rutinarias sin solicitudes repetidas de aprobación.',
    prepareTitle: 'Preparar remediación',
    prepareDescription: 'La planificación rutinaria y las propuestas elegibles en una rama no necesitan aprobación humana. El servidor verifica primero el repositorio y las versiones corregidas. La falta de evidencia bloquea la preparación y se informa al propietario; no es una solicitud de aprobación. Las fusiones, despliegues y acciones de consecuencias importantes conservan sus controles.',
    humanQueue: 'Aprobaciones que requieren tu decisión', humanEmpty: 'No hay aprobaciones pendientes de tu decisión.',
    activeWork: 'Trabajo autónomo e investigaciones', reviewHistory: 'Historial completado y cerrado', approvalNotRequired: 'Sin aprobación pendiente',
    remediationPrepared: 'Plan registrado para verificación automática y preparación de rama. No se registró aprobación humana.',
    remediationApproved: 'Resultado de preparación registrado. Consulta el estado del trabajo.',
    fixApproved: 'Preparación en cola; todavía no se ha verificado una reparación ni un despliegue.',
    prPrepared: 'Propuesta de rama disponible. Se mantienen los controles de validación y publicación.',
    issueReviewSubtitle: 'Este informe describe avisos de dependencias detectados. Planificar es trabajo rutinario; un informe o una rama propuesta no demuestra una reparación completada.',
    planSummary: 'Plan de remediación registrado. Este plan no afirma cambios de código ni reparaciones completadas.',
    safety: ['La política del sistema autoriza la preparación rutinaria, sin inventar aprobación humana.', 'Solo cambios de dependencias verificados en el repositorio conectado pueden pasar a una rama aislada.', 'El lockfile, las pruebas, CI, fusión y despliegue requieren verificación antes de publicar. Las acciones de consecuencias importantes conservan su aprobación.'],
    validateDiff: 'Verifica el diff y los controles requeridos antes de integrar; preparar una propuesta no es desplegar.',
  },
  pt: {
    subtitle: 'Monitore dependências, investigue achados e prepare correções rotineiras sem pedidos repetidos de aprovação.',
    prepareTitle: 'Preparar correção',
    prepareDescription: 'O planejamento rotineiro e propostas elegíveis em um branch não precisam de aprovação humana. O servidor verifica primeiro o repositório e as versões corrigidas. A falta de evidências bloqueia a preparação e é informada ao proprietário; não é um pedido de aprovação. Merge, deploy e ações com consequências importantes mantêm seus controles.',
    humanQueue: 'Aprovações que exigem sua decisão', humanEmpty: 'Nenhuma aprovação aguarda sua decisão.',
    activeWork: 'Trabalho autônomo e investigações', reviewHistory: 'Histórico concluído e encerrado', approvalNotRequired: 'Sem aprovação pendente',
    remediationPrepared: 'Plano registrado para verificação automática e preparação de branch. Nenhuma aprovação humana foi registrada.',
    remediationApproved: 'Resultado da preparação registrado. Confira o status do trabalho.',
    fixApproved: 'Preparação na fila; ainda não há comprovação de correção ou deploy verificado.',
    prPrepared: 'Proposta em branch disponível. Os controles de validação e publicação continuam obrigatórios.',
    issueReviewSubtitle: 'Este relatório descreve avisos de dependências detectados. Planejar é trabalho rotineiro; um relatório ou branch proposto não comprova uma correção concluída.',
    planSummary: 'Plano de correção de dependências registrado. Este plano não comprova alteração de código nem correção concluída.',
    safety: ['A política do sistema autoriza a preparação rotineira, sem inventar aprovação humana.', 'Somente alterações de dependências verificadas no repositório conectado podem entrar em um branch isolado.', 'Lockfile, testes, CI, merge e deploy exigem verificação antes da publicação. Ações com consequências importantes mantêm o limite de aprovação.'],
    validateDiff: 'Verifique o diff e os controles exigidos antes da integração; preparar uma proposta não é fazer deploy.',
  },
  pl: {
    subtitle: 'Monitoruj zależności, badaj ustalenia i przygotowuj rutynowe naprawy bez powtarzania próśb o akceptację.',
    prepareTitle: 'Przygotuj naprawę',
    prepareDescription: 'Rutynowe planowanie i dozwolone propozycje w osobnej gałęzi nie wymagają akceptacji człowieka. Serwer najpierw sprawdza zakres repozytorium i poprawione wersje. Brak dowodów blokuje przygotowanie i jest zgłaszany właścicielowi; nie oznacza oczekiwania na akceptację. Scalanie, wdrożenie i działania o istotnych skutkach zachowują swoje kontrole.',
    humanQueue: 'Akceptacje wymagające Twojej decyzji', humanEmpty: 'Żadna akceptacja nie czeka na Twoją decyzję.',
    activeWork: 'Praca autonomiczna i badanie zdarzeń', reviewHistory: 'Historia ukończonych i zamkniętych spraw', approvalNotRequired: 'Brak oczekującej akceptacji',
    remediationPrepared: 'Plan zapisano do automatycznej weryfikacji i przygotowania gałęzi. Nie zapisano akceptacji człowieka.',
    remediationApproved: 'Zapisano wynik przygotowania. Sprawdź stan pracy poniżej.',
    fixApproved: 'Przygotowanie jest w kolejce; nie potwierdzono jeszcze naprawy ani wdrożenia.',
    prPrepared: 'Propozycja w gałęzi jest dostępna. Nadal obowiązują kontrole weryfikacji i wydania.',
    issueReviewSubtitle: 'Raport opisuje wykryte ostrzeżenia zależności. Planowanie jest rutynową pracą; raport lub propozycja w gałęzi nie dowodzą ukończenia naprawy.',
    planSummary: 'Zapisano plan naprawy zależności. Sam plan nie potwierdza zmiany kodu ani ukończonej naprawy.',
    safety: ['Polityka systemu zezwala na rutynowe przygotowanie bez udawania akceptacji człowieka.', 'Tylko zweryfikowane zmiany zależności w podłączonym repozytorium mogą trafić do osobnej gałęzi.', 'Lockfile, testy, CI, scalanie i wdrożenie wymagają weryfikacji przed wydaniem. Działania o istotnych skutkach zachowują wymóg akceptacji.'],
    validateDiff: 'Przed integracją sprawdź diff i wymagane kontrole; przygotowanie propozycji nie jest wdrożeniem.',
  },
  ru: {
    subtitle: 'Отслеживайте зависимости, исследуйте находки и готовьте обычные исправления без повторных запросов одобрения.',
    prepareTitle: 'Подготовить исправление',
    prepareDescription: 'Обычное планирование и допустимые предложения в отдельной ветке не требуют одобрения человека. Сервер сначала проверяет область репозитория и исправленные версии. Недостаток доказательств блокирует подготовку и сообщается владельцу; это не запрос одобрения. Слияние, развёртывание и действия с существенными последствиями сохраняют свои проверки.',
    humanQueue: 'Одобрения, требующие вашего решения', humanEmpty: 'Нет одобрений, ожидающих вашего решения.',
    activeWork: 'Автономная работа и расследования', reviewHistory: 'История завершённых и закрытых записей', approvalNotRequired: 'Одобрение не ожидается',
    remediationPrepared: 'План сохранён для автоматической проверки и подготовки ветки. Одобрение человека не записывалось.',
    remediationApproved: 'Результат подготовки записан. Проверьте состояние работы ниже.',
    fixApproved: 'Подготовка в очереди; проверенное исправление или развёртывание ещё не подтверждены.',
    prPrepared: 'Предложение в ветке доступно. Проверки и требования к выпуску сохраняются.',
    issueReviewSubtitle: 'Отчёт описывает обнаруженные предупреждения зависимостей. Планирование — обычная работа; отчёт или предложенная ветка не доказывают завершение исправления.',
    planSummary: 'План исправления зависимостей сохранён. Сам план не подтверждает изменение кода или завершение исправления.',
    safety: ['Политика системы разрешает обычную подготовку без выдуманного одобрения человека.', 'В отдельную ветку допускаются только проверенные изменения зависимостей подключённого репозитория.', 'Lockfile, тесты, CI, слияние и развёртывание требуют проверки перед выпуском. Действия с существенными последствиями сохраняют границу одобрения.'],
    validateDiff: 'Перед интеграцией проверьте diff и обязательные проверки; подготовка предложения не означает развёртывание.',
  },
}

export function remediationAutonomyCopy(lang: string) {
  return COPY[lang as keyof typeof COPY] || COPY.en
}
