// saas/tests/agentRepairController.node.test.ts
import test from 'node:test'
import assert from 'node:assert/strict'
import { RepairController } from '../lib/agent-runtime/repair-controller.ts'
import { ScriptedCodeSandboxProvider } from '../lib/agent-runtime/providers/scripted-provider.ts'
import { DisabledCodeSandboxProvider } from '../lib/agent-runtime/providers/disabled-provider.ts'
import type { RepairCandidate, RepairCandidateGenerator } from '../lib/agent-runtime/repair-types.ts'
import type { SandboxExecutionResult, SandboxStructuredError } from '../lib/agent-runtime/contracts.ts'

const request = { requestId: 'repair-1', language: 'typescript' as const, publicInterface: 'export function add(): number', requirements: 'Return a number.' }
const candidate = (source = 'export function add(){ return 1 }'): RepairCandidate => ({ source, tests: 'test', language: 'typescript', metadata: { label: 'candidate' } })
const ok = (): SandboxExecutionResult => ({ stdout: '', stderr: '', exitCode: 0, signal: null, timedOut: false, durationMs: 5, outputTruncated: false, artifacts: [] })
const fail = (stage: SandboxStructuredError['stage'], code: SandboxStructuredError['code'], retryable = true): SandboxExecutionResult => ({ ...ok(), exitCode: 1, stderr: `very long stderr ${'x'.repeat(2000)}`, artifacts: [{ path: 'out.txt', sizeBytes: 5, content: new Uint8Array([1]) }], error: { stage, code, retryable, message: 'API_KEY=do-not-store diagnostic' } })
class Generator implements RepairCandidateGenerator { initialCalls = 0; corrections: unknown[] = []; private readonly initial: RepairCandidate; private readonly corrected: RepairCandidate; private readonly throwsAt?: 'initial' | 'correction'; constructor(initial: RepairCandidate = candidate(), corrected: RepairCandidate = candidate('export function add(){ return 2 }'), throwsAt?: 'initial' | 'correction') { this.initial = initial; this.corrected = corrected; this.throwsAt = throwsAt } async generateInitial() { this.initialCalls++; if (this.throwsAt === 'initial') throw new Error('TOKEN=initial-secret'); return this.initial } async generateCorrection(input: any) { this.corrections.push(input); if (this.throwsAt === 'correction') throw new Error('TOKEN=correction-secret'); return this.corrected } }
const controller = (script: any[], generator = new Generator(), now = () => 0, extra: any = {}, destroyError?: unknown) => ({ controller: new RepairController({ provider: new ScriptedCodeSandboxProvider(script, destroyError), generator, now, policy: { maximumWorkflowTimeMs: 100, maximumCommandExecutionTimeMs: 20, ...extra } }), generator })

test('succeeds on first candidate in ordered stages with virtual requests and cleanup', async () => { const setup = controller([{ stage: 'static_analysis', result: ok() }, { stage: 'tests', result: ok() }, { stage: 'execution', result: ok() }]); const result = await setup.controller.run(request); assert.equal(result.verified, true); if (result.verified) { assert.equal(result.candidatesEvaluated, 1); assert.equal(result.cleanup.succeeded, true) }; const provider = (setup.controller as any).dependencies?.provider })
test('static analysis, tests, and execution failures each restart at static analysis and then succeed', async () => { for (const stage of ['static_analysis', 'tests', 'execution'] as const) { const script: any[] = []; for (const s of ['static_analysis', 'tests', 'execution'] as const) { script.push({ stage: s, result: s === stage ? fail(s, s === 'tests' ? 'test_failure' : s === 'static_analysis' ? 'static_analysis' : 'runtime') : ok() }); if (s === stage) break } script.push({ stage: 'static_analysis', result: ok() }, { stage: 'tests', result: ok() }, { stage: 'execution', result: ok() }); const generator = new Generator(); const setup = controller(script, generator); const result = await setup.controller.run(request); assert.equal(result.verified, true); assert.equal(generator.corrections.length, 1) } })
test('correction limit means one initial plus three corrections, then bounded exhaustion', async () => { const script = Array.from({ length: 4 }, () => ({ stage: 'static_analysis', result: fail('static_analysis', 'static_analysis') })); const generator = new Generator(); const result = await controller(script, generator).controller.run(request); assert.equal(result.verified, false); if (!result.verified) { assert.equal(result.attemptsUsed, 4); assert.equal(result.attemptsExhausted, true); assert.equal(result.correctionsRequested, 3); assert.equal(result.history.attempts.length, 4) }; assert.equal(generator.corrections.length, 3) })
test('non-retryable failures stop immediately and timeout is classified', async () => { const result = await controller([{ stage: 'static_analysis', result: { ...fail('static_analysis', 'invalid_request', false), timedOut: true, exitCode: 124 } }]).controller.run(request); assert.equal(result.verified, false); if (!result.verified) { assert.equal(result.category, 'timeout'); assert.equal(result.attemptsUsed, 1); assert.equal(result.diagnostic.timedOut, true) } })
test('total workflow timeout stops before provider processing', async () => { let n = 0; const result = await controller([], new Generator(), () => (n++ === 0 ? 0 : 100)).controller.run(request); assert.equal(result.verified, false); if (!result.verified) assert.equal(result.workflowTimedOut, true) })
test('provider, initial generator, and correction generator exceptions are bounded and cleanup occurs exactly once', async () => { const providerCase = controller([{ stage: 'static_analysis', error: new Error('Bearer private-value') }]); const a = await providerCase.controller.run(request); assert.equal(a.verified, false); if (!a.verified) assert.doesNotMatch(a.diagnostic.safeSummary, /private-value/); const initial = await controller([], new Generator(candidate(), candidate(), 'initial')).controller.run(request); assert.equal(initial.verified, false); const correction = await controller([{ stage: 'static_analysis', result: fail('static_analysis', 'static_analysis') }], new Generator(candidate(), candidate(), 'correction')).controller.run(request); assert.equal(correction.verified, false) })
test('cleanup failure never masks primary failure and history stays immutable and bounded', async () => { const result = await controller([{ stage: 'static_analysis', result: fail('static_analysis', 'static_analysis', false) }], new Generator(), () => 0, {}, new Error('cleanup TOKEN=private')).controller.run(request); assert.equal(result.verified, false); if (!result.verified) { assert.equal(result.category, 'static_analysis'); assert.equal(result.cleanup.succeeded, false); assert.doesNotMatch(result.cleanup.safeSummary ?? '', /private/); assert.throws(() => (result.history.attempts as any).push('x')); assert.doesNotMatch(JSON.stringify(result.history), /out.txt|x{100}/) } })
test('request metadata obeys timeout policy and uses virtual working directory', async () => { const provider = new ScriptedCodeSandboxProvider([{ stage: 'static_analysis', result: ok() }, { stage: 'tests', result: ok() }, { stage: 'execution', result: ok() }]); const result = await new RepairController({ provider, generator: new Generator(), now: () => 0, policy: { maximumWorkflowTimeMs: 100, maximumCommandExecutionTimeMs: 7 } }).run(request); assert.equal(result.verified, true); assert.deepEqual(provider.executeCalls.map(c => c.request.stage), ['static_analysis', 'tests', 'execution']); assert.ok(provider.executeCalls.every(c => c.request.timeoutMs <= 7 && c.request.workingDirectory === '/workspace')); assert.equal(provider.destroyCalls.length, 1) })
test('disabled provider produces bounded sandbox-unavailable failure', async () => { const result = await new RepairController({ provider: new DisabledCodeSandboxProvider(), generator: new Generator(), now: () => 0 }).run(request); assert.equal(result.verified, false); if (!result.verified) assert.equal(result.category, 'sandbox_unavailable') })
