import test from 'node:test'
import assert from 'node:assert/strict'
import { AgentWorkflowCoordinator } from '../lib/agent-runtime/workflow-coordinator.ts'
import { DEFAULT_SANDBOX_RUNTIME_POLICY } from '../lib/agent-runtime/policy.ts'
import type { AgentOperationActivityRecord } from '../lib/agent-runtime/activity-store.ts'
import type { AgentWorkflowCoordinatorDependencies } from '../lib/agent-runtime/workflow-types.ts'

const config: any = { providerId: 'remote', enabled: true, endpoint: 'https://fake.invalid', authenticationToken: 'fake', requestTimeoutMs: 10, maximumConcurrentSessions: 1, maximumSessionsPerUserPerHour: 10, maximumWorkflowCostUnits: 10, allowOutboundNetwork: false, allowEnvironmentInheritance: false, allowHostFilesystem: false, allowRepositoryWrites: false }
const request: any = { requestId: 'request-1', workflowId: 'workflow-1', userId: 'user-1', language: 'typescript', capabilities: [], estimatedCostUnits: 1, repairRequest: { requestId: 'request-1', language: 'typescript', publicInterface: 'x', requirements: 'x' } }
function setup(overrides: Partial<AgentWorkflowCoordinatorDependencies> = {}) { let reserve = 0, release = 0, run = 0; const activity: AgentOperationActivityRecord[] = []; const provider = { providerId: 'remote' }; const dependencies: any = { providerConfig: config, providerRegistry: { getConfiguredProvider: () => provider }, quotaLedger: { snapshot: () => ({ available: true }), reserve: () => { reserve++; return true }, release: () => { release++ } }, runtimePolicy: DEFAULT_SANDBOX_RUNTIME_POLICY, toolPolicy: { permitsCodeExecution: true }, supportedLanguages: ['typescript'], supportedCapabilities: [], createRepairController: () => ({ run: async () => { run++; return { verified: true, candidatesEvaluated: 1, correctionsRequested: 0 } } }), activityStore: { record: async (record: AgentOperationActivityRecord) => { activity.push(record) } }, now: () => 0, createAuditId: (() => { let n = 0; return () => `audit-${++n}` })(), ...overrides }; return { coordinator: new AgentWorkflowCoordinator(dependencies), counts: () => ({ reserve, release, run }), activity } }
test('authorized fake workflow succeeds, reserves and releases quota in deterministic order', async () => { const s = setup(); const result = await s.coordinator.run({ privileged: true, executionEntitled: true }, request); assert.equal(result.kind, 'success'); assert.deepEqual(s.counts(), { reserve: 1, release: 1, run: 1 }); assert.deepEqual(result.auditEvents.map(e => e.action), ['workflow_received', 'quota_reserved', 'provider_resolved', 'repair_started', 'repair_completed', 'quota_released', 'workflow_completed']); assert.equal(Object.isFrozen(result), true); assert.throws(() => (result.auditEvents as any).push('x')); assert.deepEqual(s.activity, [{ workflowId: 'workflow-1', requestId: 'request-1', providerId: 'remote', outcome: 'success', eventCount: 7, durationMs: 0 }]) })
test('authorization and quota denials do not invoke repair and are durably recorded', async () => { const denied = setup(); const r = await denied.coordinator.run({ privileged: false, executionEntitled: true }, request); assert.equal(r.kind, 'denial'); assert.deepEqual(denied.counts(), { reserve: 0, release: 0, run: 0 }); assert.equal(denied.activity[0]?.outcome, 'denial'); const quota = setup({ quotaLedger: { snapshot: () => ({ available: true }), reserve: () => false, release: () => {} } as any }); const q = await quota.coordinator.run({ privileged: true, executionEntitled: true }, request); assert.equal(q.kind, 'denial'); assert.equal(quota.counts().run, 0); assert.equal(quota.activity[0]?.outcome, 'denial') })
test('disabled providers and repair failures fail safely, release quota, and are recorded', async () => { const disabled = setup({ providerRegistry: { getConfiguredProvider: () => ({ providerId: 'disabled' }) } as any }); const a = await disabled.coordinator.run({ privileged: true, executionEntitled: true }, request); assert.equal(a.kind, 'failure'); assert.equal(disabled.counts().run, 0); assert.equal(disabled.activity[0]?.outcome, 'failure'); const failed = setup({ createRepairController: () => ({ run: async () => ({ verified: false, category: 'timeout', workflowTimedOut: true, attemptsUsed: 1, correctionsRequested: 0, diagnostic: { safeSummary: 'timeout' } }) }) as any }); const b = await failed.coordinator.run({ privileged: true, executionEntitled: true }, request); assert.equal(b.kind, 'failure'); if (b.kind === 'failure') assert.equal(b.category, 'timeout'); assert.equal(failed.counts().release, 1); assert.equal(failed.activity[0]?.outcome, 'failure') })
