import test from 'node:test'
import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { BrowserExecutor, ExecutorRegistry, InMemoryDispatchStore, SupervisorDispatcher } from '../lib/supervisor/index.ts'
import { BrowserRuntimeDryRunAdapter, browserRuntimeDryRunPackageSchema, verifyBrowserRuntimeDryRunPackage } from '../lib/supervisor/executors/browser/index.ts'
import { hydrateLocalizedSource } from './helpers/hydrateLocalizedSource.ts'


const clock = () => new Date('2026-07-16T12:00:00.000Z')
const incident = () => ({ incidentId: 'INC-B-001', provider: 'vercel', environment: 'sandbox', severity: 'warning', detectedAt: '2026-07-16T00:00:00.000Z', source: 'api', errorMessage: 'Deployment needs browser confirmation.', evidence: [{ evidenceId: 'EV-1', type: 'log', capturedAt: '2026-07-16T00:00:00.000Z', summary: 'safe' }], metadata: {} })
const target = { role: 'button', name: 'Save' }
const step = (o = {}) => ({ stepId: 'nav-1', action: 'navigate', description: 'Open approved origin.', protectedAction: false, parameters: { url: 'https://example.com/' }, expectedResult: 'Origin loaded.', ...o })
const verifyStep = (o = {}) => ({ stepId: 'verify-1', action: 'verify', description: 'Verify final status.', protectedAction: false, parameters: { target: { text: 'Ready' } }, expectedResult: 'Ready state is visible.', ...o })
const plan = (o = {}) => ({ planId: 'PLAN-B-001', incidentId: 'INC-B-001', diagnosis: 'Approved browser-only dry run.', confidenceScore: 80, requiresBrowser: true, riskLevel: 'medium', targetProvider: 'vercel', targetEnvironment: 'sandbox', targetOrigin: 'https://example.com', steps: [step(), step({ stepId: 'fill-1', action: 'fill', description: 'Fill safe value.', parameters: { target: { label: 'Project name' }, value: 'signalboost-preview' } }), step({ stepId: 'approval-1', action: 'request_approval', description: 'Pause for Browser Runtime signed approval.', parameters: {} }), step({ stepId: 'click-1', action: 'click', description: 'Click protected save.', protectedAction: true, parameters: { target } }), step({ stepId: 'shot-1', action: 'screenshot', description: 'Capture evidence.', protectedAction: false, parameters: { label: 'after-save' } })], verificationSteps: [verifyStep()], generatedAt: '2026-07-16T00:01:00.000Z', schemaVersion: 'supervisor-plan-v1', ...o })
const dispatch = { dispatchId: 'DISP-B-001', requestedExecutorKind: 'browser', requestedAt: '2026-07-16T00:03:00.000Z' }
const plaintextFixture = ['plain', 'text', 'fixture'].join('-')
const tokenFixture = ['sk', 'fixture', 'not', 'a', 'credential'].join('-')
function pkg(p = plan(), ids = p.steps.map(s => s.stepId)) { return new BrowserRuntimeDryRunAdapter().createPackage({ incident: incident() as any, repairPlan: p as any, approvedStepIds: ids, dispatch: dispatch as any, requestedExecutorKind: 'browser', clock }) }

test('valid approved browser plan creates a runtime-valid dry-run package without runtime approval tokens', () => { const p = pkg(); assert.equal(p.mode, 'dry_run'); assert.equal(p.targetOrigin, 'https://example.com'); assert.deepEqual(p.approvedStepIds, ['nav-1','fill-1','approval-1','click-1','shot-1']); assert.equal(p.browserTask.approvalToken, 'DRY_RUN_NO_RUNTIME_APPROVAL_TOKEN_CREATED'); assert.equal(p.approvalRequirements.browserRuntimeSignedTaskApproval.approvalTokenCreated, false); assert.equal(browserRuntimeDryRunPackageSchema.parse(p).packageFingerprint, p.packageFingerprint); assert.equal(verifyBrowserRuntimeDryRunPackage(p).valid, true) })
test('no Playwright browser page context launcher session factory or network dependency is imported', () => { for (const file of ['browser-runtime-adapter.ts','browser-runtime-mapper.ts','browser-runtime-compatibility.ts']) { const src = hydrateLocalizedSource(readFileSync(new URL(`../lib/supervisor/executors/browser/${file}`, import.meta.url), 'utf8')); assert.doesNotMatch(src, /playwright|chromium|BrowserSession|sessionFactory|fetch\(|axios|provider mutation|secretResolver|PolicyEngine|Thinker|Observer/i) } })
test('requiresBrowser false, missing origin, non-HTTPS origin, credentials, query, fragment are rejected', () => { assert.throws(() => pkg(plan({ requiresBrowser: false }) as any), /requiresBrowser/); assert.throws(() => pkg(plan({ targetOrigin: undefined }) as any), /targetOrigin/); assert.throws(() => pkg(plan({ targetOrigin: 'http://example.com' }) as any), /HTTPS/); assert.throws(() => pkg(plan({ targetOrigin: 'https://u:p@example.com' }) as any), /credentials/); assert.throws(() => pkg(plan({ targetOrigin: 'https://example.com?x=1' }) as any), /query/); assert.throws(() => pkg(plan({ targetOrigin: 'https://example.com#x' }) as any), /fragment/) })
test('approved step identity and order fail closed', () => { assert.throws(() => pkg(plan(), ['missing']), /exist/); assert.throws(() => pkg(plan(), ['nav-1','nav-1']), /unique/); assert.throws(() => pkg(plan(), ['fill-1','nav-1']), /order/) })
test('unapproved steps are excluded and mixed API browser scope is rejected', () => { const p = plan({ steps: [step(), step({ stepId:'read-1', action:'read', parameters:{ target:{ text:'safe' } } })] }) as any; assert.deepEqual(pkg(p, ['nav-1']).approvedStepIds, ['nav-1']); assert.doesNotMatch(JSON.stringify(pkg(p, ['nav-1'])), /read-1/); assert.throws(() => pkg(plan({ steps: [step(), step({ stepId:'api-1', action:'api_request' })] }) as any, ['nav-1']), /Mixed/) })
test('unsupported executable actions, arbitrary JavaScript, shell, and natural-language targets are rejected', () => { assert.throws(() => pkg(plan({ steps: [step({ action:'upload' })] }) as any, ['nav-1']), /supported|compatible/); assert.throws(() => pkg(plan({ steps: [step({ parameters:{ url:'javascript:alert(1)' } })] }) as any), /executable|origin/); assert.throws(() => pkg(plan({ steps: [step({ stepId:'click-1', action:'click', parameters:{ target:{ label:'Save' }, shell:'bash rm -rf /' } })] }) as any, ['click-1']), /executable/); assert.throws(() => pkg(plan({ steps: [step({ stepId:'click-1', action:'click', parameters:{ target:'the save button' } })] }) as any, ['click-1']), /structured/) })
test('selectors map deterministically and selector changes alter fingerprint', () => { const a = pkg(); assert.equal(a.browserTask.steps.find(s => s.id === 'click-1')?.kind, 'click'); assert.match(JSON.stringify(a.browserTask), /role=button/); const b = pkg(plan({ steps: plan().steps.map(s => s.stepId === 'click-1' ? { ...s, parameters: { target: { testId: 'save' } } } : s) }) as any); assert.notEqual(a.packageFingerprint, b.packageFingerprint) })
test('plaintext passwords and API tokens are rejected while secretRef and tokenRef are preserved unresolved', () => { assert.throws(() => pkg(plan({ steps:[step({ stepId:'fill-1', action:'fill', parameters:{ target:{ label:'Password' }, password: plaintextFixture } })] }) as any, ['fill-1']), /reference/); assert.throws(() => pkg(plan({ steps:[step({ stepId:'fill-1', action:'fill', parameters:{ target:{ label:'Token' }, apiKey: tokenFixture } })] }) as any, ['fill-1']), /reference/); const s = pkg(plan({ steps:[step({ stepId:'fill-1', action:'fill', parameters:{ target:{ label:'Password' }, secretRef:'vault://safe/password' } })] }) as any, ['fill-1']); assert.match(JSON.stringify(s), /vault:\/\/safe\/password/); assert.doesNotMatch(JSON.stringify(s), /plain-text-fixture/); const t = pkg(plan({ steps:[step({ stepId:'fill-1', action:'fill', parameters:{ target:{ label:'Token' }, tokenRef:'vault://safe/token' } })] }) as any, ['fill-1']); assert.match(JSON.stringify(t), /vault:\/\/safe\/token/) })
test('protected actions remain after checkpoint and approvals remain separate', () => { const p = pkg(); assert.deepEqual(p.approvalRequirements.browserRuntimeContinuationApproval.checkpointStepIds, ['approval-1']); assert.deepEqual(p.approvalRequirements.browserRuntimeContinuationApproval.postCheckpointStepIds, ['click-1','shot-1']); assert.deepEqual(p.approvalRequirements.protectedStepIds, ['click-1']); assert.equal(p.approvalRequirements.supervisorPolicyApproval.doesNotGrantRuntimeApproval, true); assert.equal(p.approvalRequirements.browserRuntimeContinuationApproval.approvalTokenCreated, false) })
test('fingerprints are deterministic and change on step origin and verification mutations', () => { const a = pkg(); assert.equal(a.packageFingerprint, pkg().packageFingerprint); assert.notEqual(a.packageFingerprint, pkg(plan({ steps: plan().steps.map(s => s.stepId === 'fill-1' ? { ...s, parameters:{ target:{ label:'Project name' }, value:'changed' } } : s) }) as any).packageFingerprint); assert.notEqual(a.packageFingerprint, pkg(plan({ targetOrigin:'https://app.example.com', steps: plan().steps.map(s => s.stepId === 'nav-1' ? { ...s, parameters:{ url:'https://app.example.com/' } } : s) }) as any).packageFingerprint); assert.notEqual(a.packageFingerprint, pkg(plan({ verificationSteps:[verifyStep({ expectedResult:'Different final assertion.' })] }) as any).packageFingerprint) })
test('BrowserExecutor returns dry_run_ready with no executed steps and does not claim completion', () => { const result = new BrowserExecutor({ clock }).execute({ incident: incident() as any, plan: plan() as any, approvedStepIds: plan().steps.map(s => s.stepId), executionContext:{ executionId:'EXEC-1', metadata:{} }, dispatch: dispatch as any }); assert.equal(result.status, 'dry_run_ready'); assert.deepEqual(result.executedStepIds, []); assert.deepEqual(result.skippedStepIds, plan().steps.map(s => s.stepId)); assert.doesNotMatch(JSON.stringify(result), /completed the repair|repair completed/i) })
test('dispatcher routes browser scope at most once and keeps audit serializable and sanitized', async () => { const events:any[]=[]; const registry = new ExecutorRegistry(); registry.register('browser', new BrowserExecutor({ clock })); const dispatcher = new SupervisorDispatcher({ registry, audit:{ write:e=>events.push(e) }, dispatchStore:new InMemoryDispatchStore() }); const req:any = { incident: incident(), plan: plan(), policyDecision:{ outcome:'approved', reason:'approved', evaluatedAt:'2026-07-16T00:02:00.000Z', policyVersion:'test', approvedStepIds: plan().steps.map(s=>s.stepId) }, approvedStepIds: plan().steps.map(s=>s.stepId), executionContext:{ executionId:'EXEC-1', metadata:{ token:'should-redact' } }, dispatchId:'DISP-ONCE', requestedExecutorKind:'browser' }; assert.equal((await dispatcher.dispatch(req)).status, 'dry_run_ready'); assert.equal((await dispatcher.dispatch(req)).status, 'failed'); assert.doesNotThrow(()=>JSON.stringify(events)); assert.doesNotMatch(JSON.stringify(events), /should-redact|token/i) })
test('audit failure before package creation fails closed', async () => { let calls=0; const registry = new ExecutorRegistry(); registry.register('browser', { kind:'browser', execute:()=>{ calls++; return new BrowserExecutor({ clock }).execute(arguments as any) } } as any); const dispatcher = new SupervisorDispatcher({ registry, audit:{ write:()=>{ throw new Error('audit down') } }, dispatchStore:new InMemoryDispatchStore() }); const r = await dispatcher.dispatch({ incident: incident() as any, plan: plan() as any, policyDecision:{ outcome:'approved', reason:'approved', evaluatedAt:'2026-07-16T00:02:00.000Z', policyVersion:'test', approvedStepIds: plan().steps.map(s=>s.stepId) } as any, approvedStepIds: plan().steps.map(s=>s.stepId), executionContext:{ executionId:'EXEC-1', metadata:{} }, dispatchId:'DISP-AUDIT', requestedExecutorKind:'browser' }); assert.equal(r.status, 'failed'); assert.equal(calls, 0) })
test('tampered packages fail fingerprint verification', () => { const p = pkg(); assert.throws(() => verifyBrowserRuntimeDryRunPackage({ ...p, targetOrigin:'https://evil.example.com' }), /fingerprint|origin/i) })
