import test from 'node:test'
import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { isConciergeBuilderObjective, isCosCodingObjective } from '../lib/ai/cos/cosReasoningRolePolicy.ts'
import { hydrateLocalizedSource } from './helpers/hydrateLocalizedSource.ts'


test('concrete coding objectives route to Builder, not a public execution endpoint', () => {
  assert.equal(isCosCodingObjective('Fix this TypeScript stack trace and run the test.'), true)
  assert.equal(isCosCodingObjective('Create a file named hello.js, run it with Node.js, and give me the file to download.'), true)
  assert.equal(isCosCodingObjective('Design a landing page for a travel service.'), true)
  assert.equal(isCosCodingObjective('I need a landing-page design.'), true)
  assert.equal(isConciergeBuilderObjective('I need a landing-page design.'), true)
  assert.equal(isConciergeBuilderObjective('What is a landing-page design?'), false)
  assert.equal(isCosCodingObjective('Explain the Bay of Pigs invasion.'), false)
  assert.equal(isConciergeBuilderObjective('What is a SQL query?'), false)
  assert.equal(isConciergeBuilderObjective('Debug this.'), false)
  assert.equal(isConciergeBuilderObjective('Design a modern website for a travel service.'), true)
  assert.equal(isConciergeBuilderObjective('Create a responsive landing page.'), true)
  assert.equal(isConciergeBuilderObjective('Build me a dashboard.'), true)
  const assistant = hydrateLocalizedSource(readFileSync(new URL('../app/dashboard/assistant/page.tsx', import.meta.url), 'utf8'))
  const transport = hydrateLocalizedSource(readFileSync(new URL('../components/AssistantTransportBoundary.tsx', import.meta.url), 'utf8'))
  assert.doesNotMatch(assistant, /window\.location\.assign\(`\/dashboard\/developer\?objective=/)
  assert.doesNotMatch(assistant, /cos-builder-handoff-files-v1/)
  assert.match(assistant, /builderWorkspaceId/)
  assert.match(assistant, /\/api\/builder\/workspaces\//)
  assert.match(transport, /isConciergeBuilderObjective\(userContent, builderRoutingContext\(body\)\)/)
  assert.match(transport, /executeBuilderFromConcierge/)
  assert.match(transport, /isConciergeArtifactObjective\(userContent\)/)
  assert.match(transport, /executeArtifactFromConcierge/)
  assert.match(transport, /fetchImpl\('\/api\/artifacts'/)
  assert.match(transport, /fetchImpl\('\/api\/builder'/)
  assert.match(transport, /\/api\/builder\?jobId=/)
  assert.doesNotMatch(transport, /window\.location\.assign/)
})

test('Concierge keeps its explicit design handoff while authenticated Assistant uses durable jobs', () => {
  const conciergeRoute = hydrateLocalizedSource(readFileSync(new URL('../app/api/concierge/route.ts', import.meta.url), 'utf8'))
  const concierge = hydrateLocalizedSource(readFileSync(new URL('../components/Concierge.tsx', import.meta.url), 'utf8'))
  assert.match(conciergeRoute, /isConciergeBuilderObjective\(objective, routingContext\)/)
  assert.match(conciergeRoute, /CONCIERGE_DESIGN_ARTIFACT/)
  assert.match(conciergeRoute, /CONCIERGE_DESIGN_REQUEST/)
  assert.match(conciergeRoute, /const objective = input\.trim\(\)/)
  assert.match(conciergeRoute, /designMatched/)
  assert.match(conciergeRoute, /directBuilder\(body, input\)/)
  assert.match(conciergeRoute, /hasAttachments\(body\)/)
  const browserRoute = hydrateLocalizedSource(readFileSync(new URL('../app/api/cos-browser/route.ts', import.meta.url), 'utf8'))
  assert.match(browserRoute, /isConciergeBuilderObjective\(prompt, routingContext\) \? legacyConciergePost\(req\) : cosPrimaryPost\(req\)/)
  assert.match(conciergeRoute, /publicAuditUserId\(\)/)
  assert.match(conciergeRoute, /travelLandingPageHtml\(\)/)
  assert.match(conciergeRoute, /index\.html/)
  assert.match(concierge, /builderWorkspaceId/)
  assert.match(concierge, /\/api\/builder\/workspaces\//)

  const builderRoute = hydrateLocalizedSource(readFileSync(new URL('../app/api/builder/route.ts', import.meta.url), 'utf8'))
  const jobRunner = hydrateLocalizedSource(readFileSync(new URL('../lib/builder/job-runner.ts', import.meta.url), 'utf8'))
  const toolLoop = hydrateLocalizedSource(readFileSync(new URL('../lib/builder/tool-loop.ts', import.meta.url), 'utf8'))
  assert.match(builderRoute, /await enqueueBuilderJob/)
  assert.match(builderRoute, /after\(async \(\) =>/)
  assert.match(builderRoute, /status: 'queued'/)
  assert.match(jobRunner, /new BuilderToolLoop/)
  assert.match(jobRunner, /priorLessons: \[\]/)
  assert.match(toolLoop, /MAX_MODEL_ROUND_ATTEMPTS = 2/)
  assert.match(toolLoop, /verified the proving command completed successfully/)
})
