// saas/tests/codeRepairApplication.node.test.ts
import test from 'node:test'
import assert from 'node:assert/strict'
import {
  CodeRepairApplicationOrchestrator, CodeRepairApprovalService, InMemoryCodeRepairExecutionAuditSink,
  createCodeRepairApprovalToken, createCodeRepairPatchProposal, fingerprintCodeRepairProposal,
} from '../lib/code-repair/index.ts'
import type { CodeRepairDisposableWorkspaceManager, CodeRepairPatchProposal } from '../lib/code-repair/index.ts'

const plan: any = { planId: 'plan', incidentId: 'incident', diagnosisFingerprint: 'd', problem: 'bug', rationale: 'evidence', riskLevel: 'low', filesToInspect: ['src/a.ts'], filesAllowedToModify: ['src/a.ts'], testsToRun: [], steps: [], requiresHumanApproval: true, patchGenerationAllowed: false, patchApplicationAllowed: false, mergeAllowed: false }
const diff = '--- a/src/a.ts\n+++ b/src/a.ts\n@@ -1 +1 @@\n-old\n+new\n'
function artifacts() { const proposal = createCodeRepairPatchProposal(plan, 'base-1', diff); const validation: any = { proposalId: proposal.proposalId, validated: true, results: [], cleanupSucceeded: true, repositoryModified: false, networkAccessAllowed: false }; const review: any = { reviewId: 'review', proposalId: proposal.proposalId, provider: 'reviewer', model: 'model', verdict: 'approve', confidence: 1, summary: 'ok', findings: [], validationPassed: true, requiresHumanApproval: true, applicationAllowed: false, mergeAllowed: false }; return { proposal, validation, review } }
class Workspace implements CodeRepairDisposableWorkspaceManager {
  created = 0; staged = 0; destroyed = 0; rollback = 0
  private readonly integrity: boolean
  constructor(integrity = true) {
    this.integrity = integrity
  }
  async create(input: any) { this.created++; return { id: input.workspaceId, root: '/tmp/isolated', baseCommitSha: input.baseCommitSha, isolation: 'disposable' as const, productionRepository: false as const } }
  async verifyIntegrity() { return this.integrity }
  async stageUnifiedDiff() { this.staged++ }
  async prepareRollback(_w: any, p: CodeRepairPatchProposal) { this.rollback++; return { rollbackId: `rollback:${p.proposalId}`, baseCommitSha: p.baseCommitSha } }
  async destroy() { this.destroyed++ }
}
function setup(workspace = new Workspace()) { const { proposal, validation, review } = artifacts(); const approvals = new CodeRepairApprovalService(); const token = approvals.issue({ proposal, validation, review, operator: { operatorId: 'owner' }, reason: 'Approved isolated dry run.', issuedAt: 1, expiresAt: 100 }); const audit = new InMemoryCodeRepairExecutionAuditSink(); const engine = new CodeRepairApplicationOrchestrator(approvals, workspace, audit); return { proposal, validation, review, token, workspace, audit, engine } }
function request(x: ReturnType<typeof setup>, overrides: any = {}) { return { executionId: 'exec-1', at: 10, expectedProposalFingerprint: fingerprintCodeRepairProposal(x.proposal), proposal: x.proposal, validation: x.validation, review: x.review, approvalToken: x.token, ...overrides } }

test('successful dry run stages only a disposable workspace, prepares rollback, audits, and measures execution', async () => { const x = setup(); const result = await x.engine.dryRun(request(x)); assert.equal(result.status, 'dry_run_staged'); assert.equal(result.repositoryMutationEnabled, false); assert.deepEqual(result.verifiedSteps, ['proposal_fingerprint', 'approval_token', 'validation_report', 'independent_reviewer_approval', 'workspace_integrity', 'patch_integrity']); assert.equal(x.workspace.staged, 1); assert.equal(x.workspace.rollback, 1); assert.equal(x.workspace.destroyed, 1); assert.deepEqual(x.engine.metricsSnapshot(), { attempted: 1, succeeded: 1, failed: 0, cleanedUp: 1, cleanupFailed: 0 }); assert.deepEqual(x.audit.history().map(x => x.event), ['started', 'verified', 'dry_run_staged', 'rollback_prepared', 'cleanup_completed']) })
test('fails closed for invalid proposal fingerprint before workspace creation', async () => { const x = setup(); const result = await x.engine.dryRun(request(x, { expectedProposalFingerprint: 'bad' })); assert.equal(result.failure, 'proposal_fingerprint_mismatch'); assert.equal(x.workspace.created, 0) })
test('expired, revoked, and replayed approval tokens fail closed', async () => { const expired = setup(); assert.equal((await expired.engine.dryRun(request(expired, { at: 100 }))).failure, 'approval_token_invalid'); const r = setup(); const service = new CodeRepairApprovalService(); const token = service.issue({ proposal: r.proposal, validation: r.validation, review: r.review, operator: { operatorId: 'owner' }, reason: 'approved', issuedAt: 1, expiresAt: 100 }); service.revoke(token.tokenId, { operatorId: 'owner' }, 'revoke', 2); const e = new CodeRepairApplicationOrchestrator(service, r.workspace); assert.equal((await e.dryRun({ ...request(r), approvalToken: token })).failure, 'approval_token_invalid'); const replay = setup(); assert.equal((await replay.engine.dryRun(request(replay))).status, 'dry_run_staged'); assert.equal((await replay.engine.dryRun(request(replay))).failure, 'approval_token_invalid') })
test('corrupted patches and workspace integrity failures never stage and always clean up created workspaces', async () => { const corrupted = setup(); const proposal = { ...corrupted.proposal, unifiedDiff: 'invalid' }; assert.equal((await corrupted.engine.dryRun(request(corrupted, { proposal, expectedProposalFingerprint: fingerprintCodeRepairProposal(proposal) }))).failure, 'approval_token_invalid'); const isolated = setup(new Workspace(false)); assert.equal((await isolated.engine.dryRun(request(isolated))).failure, 'workspace_integrity_invalid'); assert.equal(isolated.workspace.destroyed, 1) })
test('invalid validation and independent review fail closed in required order', async () => { const x = setup(); assert.equal((await x.engine.dryRun(request(x, { validation: { ...x.validation, validated: false } }))).failure, 'validation_report_invalid'); const y = setup(); assert.equal((await y.engine.dryRun(request(y, { review: { ...y.review, verdict: 'reject' } }))).failure, 'independent_review_invalid') })
test('Candidate Lab packet must be bound to the exact dry-run artifacts', async () => { const x = setup(); const packet: any = { proposal: x.proposal, validation: x.validation, review: x.review, evidence: { evaluation: { recommendedForHumanReview: true }, automaticPromotionAllowed: false }, humanApprovalRequired: true, applicationAllowed: false, mergeAllowed: false }; assert.equal((await x.engine.dryRun(request(x, { candidateLabPacket: packet }))).status, 'dry_run_staged'); const y = setup(); assert.equal((await y.engine.dryRun(request(y, { candidateLabPacket: { ...packet, proposal: y.proposal } }))).failure, 'candidate_lab_packet_invalid') })
