import test from 'node:test'
import assert from 'node:assert/strict'
import { CodeRepairApprovalService, createCodeRepairApprovalToken, deserializeCodeRepairApprovalToken, fingerprintCodeRepairProposal, serializeCodeRepairApprovalToken } from '../lib/code-repair/index.ts'
import type { CodeRepairIndependentReview, CodeRepairPatchProposal, CodeRepairPatchValidationReport } from '../lib/code-repair/index.ts'

const proposal: CodeRepairPatchProposal = Object.freeze({ proposalId: 'proposal-1', planId: 'plan-1', incidentId: 'incident-1', baseCommitSha: 'abc', unifiedDiff: 'diff', files: Object.freeze([]), totalAdditions: 1, totalDeletions: 1, requiresHumanApproval: true, applicationAllowed: false, mergeAllowed: false })
const validation: CodeRepairPatchValidationReport = Object.freeze({ proposalId: 'proposal-1', validated: true, results: Object.freeze([]), cleanupSucceeded: true, repositoryModified: false, networkAccessAllowed: false })
const review: CodeRepairIndependentReview = Object.freeze({ reviewId: 'review-1', proposalId: 'proposal-1', provider: 'reviewer', model: 'independent', verdict: 'approve', confidence: 1, summary: 'Validated.', findings: Object.freeze([]), validationPassed: true, requiresHumanApproval: true, applicationAllowed: false, mergeAllowed: false })
const issue = () => ({ proposal, validation, review, operator: { operatorId: 'operator-7', displayName: 'Operator' }, reason: 'Validation evidence and independent review support a future governed application.', issuedAt: 1_000, expiresAt: 2_000 })

test('issues and consumes a valid human approval exactly once without allowing application or merge', () => { const service = new CodeRepairApprovalService(); const token = service.issue(issue()); const result = service.verify({ token, proposal, validation, review, at: 1_500 }); assert.equal(result.authorized, true); assert.equal(token.applicationAllowed, false); assert.equal(token.mergeAllowed, false); assert.equal(service.verify({ token, proposal, validation, review, at: 1_500 }).code, 'consumed') })
test('rejects expired and revoked approvals', () => { const expired = new CodeRepairApprovalService(); const token = expired.issue(issue()); assert.equal(expired.verify({ token, proposal, validation, review, at: 2_000 }).code, 'expired'); const revoked = new CodeRepairApprovalService(); const other = revoked.issue(issue()); assert.equal(revoked.revoke(other.tokenId, { operatorId: 'operator-9' }, 'Superseded by new evidence.', 1_100), true); assert.equal(revoked.verify({ token: other, proposal, validation, review, at: 1_200 }).code, 'revoked') })
test('fails closed for proposal, validation, and review binding mismatches', () => { const service = new CodeRepairApprovalService(); const token = service.issue(issue()); assert.equal(service.verify({ token, proposal: { ...proposal, unifiedDiff: 'different' }, validation, review, at: 1_100 }).code, 'inconsistent'); assert.equal(service.verify({ token, proposal, validation: { ...validation, validated: false }, review, at: 1_100 }).code, 'inconsistent'); assert.equal(service.verify({ token, proposal, validation, review: { ...review, verdict: 'reject' }, at: 1_100 }).code, 'inconsistent') })
test('creates deterministic fingerprints and canonical immutable serialization', () => { const first = createCodeRepairApprovalToken(issue()); const second = createCodeRepairApprovalToken(issue()); assert.equal(first.tokenId, second.tokenId); assert.equal(fingerprintCodeRepairProposal(proposal), fingerprintCodeRepairProposal(proposal)); const serialized = serializeCodeRepairApprovalToken(first); const decoded = deserializeCodeRepairApprovalToken(serialized); assert.equal(serializeCodeRepairApprovalToken(decoded), serialized); assert.throws(() => deserializeCodeRepairApprovalToken(JSON.stringify({ ...first })), /canonical/) })
test('records immutable operator audit history', () => { const service = new CodeRepairApprovalService(); const token = service.issue(issue()); service.verify({ token, proposal, validation, review, at: 1_100, consume: false }); const audit = service.auditHistory(); assert.deepEqual(audit.map(item => item.action), ['issued', 'verified']); assert.equal(audit[0].operatorId, 'operator-7'); assert.equal(audit[0].reason, issue().reason); assert.throws(() => (audit as any).push({})) })
