import assert from 'node:assert/strict'
import test from 'node:test'
import { assessRetestCandidate, RETEST_MINIMUM_SOURCE_CONFIDENCE, scanRetestCandidates, selectRetestBatch } from '../lib/ai/cos/evidenceTriggeredRetest.ts'
const failure={id:'c1',track:'database operations',sanitizedPrompt:'How should postgres connection pool exhaustion be diagnosed when database operations stall under multi tenant load?',lastSeenAt:'2026-08-01T00:00:00Z',occurrenceCount:1}
const evidence={contentHash:'h1',subject:'database operations and postgres pooling',summary:'Guidance for diagnosing postgres pooler saturation and multi tenant connection load.',sourceKind:'official_docs',sourceTitle:'pooling',observedAt:'2026-08-15T00:00:00Z',createdAt:'2026-08-15T00:00:00Z',confidence:.86}
test('new anchored evidence promotes a one-off failure only for measurement',()=>{const verdict=assessRetestCandidate(failure,[evidence]);assert.equal(verdict.verdict,'promote_for_retest');assert.ok(verdict.matchedTerms.includes('postgres'))})
test('stale, weak, and unanchored evidence cannot spend a benchmark slot',()=>{assert.equal(assessRetestCandidate(failure,[{...evidence,createdAt:'2026-07-01T00:00:00Z',observedAt:'2026-07-01T00:00:00Z'}]).verdict,'evidence_predates_failure');assert.equal(assessRetestCandidate(failure,[{...evidence,confidence:RETEST_MINIMUM_SOURCE_CONFIDENCE-.01}]).verdict,'source_confidence_too_low');assert.equal(assessRetestCandidate(failure,[{...evidence,subject:'kubernetes autoscaling',summary:'multi tenant load stalls in kubernetes autoscaling'}]).verdict,'insufficient_overlap')})
test('general tracks and tiny prompts cannot promote',()=>{assert.equal(assessRetestCandidate({...failure,track:'general'},[evidence]).verdict,'track_not_matchable');assert.equal(scanRetestCandidates([{...failure,sanitizedPrompt:'help please'}],[evidence]).length,0)})
test('batch is bounded and spreads across tracks',()=>{const rows=scanRetestCandidates([failure,{...failure,id:'c2'},{...failure,id:'c3',track:'postgres pooling',sanitizedPrompt:'Why does postgres pooling saturation occur under database tenant load?'}],[evidence]);const batch=selectRetestBatch(rows);assert.ok(batch.length<=2);assert.equal(new Set(batch.map(x=>x.track)).size,batch.length);assert.ok(batch.every(x=>x.verdict==='promote_for_retest'))})
