import assert from 'node:assert/strict'
import test from 'node:test'
import { isConversationProvenanceQuestion } from '../lib/ai/cos/conversationProvenanceIntent.ts'
import { isProvenanceIntrospection } from '../lib/ai/cos/provenanceIntrospection.ts'
import { isCosGeneratedProvenanceReply } from '../lib/ai/cos/provenanceReplyContinuity.ts'
import { requiresFreshExternalEvidence } from '../lib/ai/cos/cosFreshnessPolicy.ts'

test('answer-origin and idea-origin paraphrases resolve to the same provenance intent family', () => {
  const paraphrases = [
    'where did you get the answer from?',
    'where did you get the idea from?',
    'where did the idea come from?',
    'where did the idea came from?',
    'how did you come up with that idea?',
    'what inspired that idea?',
    'where did this script come from?',
    'where did that story come from?',
  ]

  for (const prompt of paraphrases) {
    assert.equal(isProvenanceIntrospection(prompt), true, prompt)
    assert.equal(requiresFreshExternalEvidence(prompt), false, prompt)
  }
})

test('creative-origin paraphrases work across the five platform languages', () => {
  const prompts = [
    '¿de dónde vino esa idea?',
    'de onde veio essa ideia?',
    'skąd wziął się ten pomysł?',
    'откуда взялась эта идея?',
  ]
  for (const prompt of prompts) {
    assert.equal(isConversationProvenanceQuestion(prompt), true, prompt)
    assert.equal(requiresFreshExternalEvidence(prompt), false, prompt)
  }
})

test('topical origin questions and authoring requests are not hijacked into prior-answer provenance', () => {
  const prompts = [
    'Where did the idea of democracy come from?',
    'What inspired the idea of the European Union?',
    'Write a post explaining where this idea came from in the history of computing.',
    'Generate a script about where coffee comes from.',
  ]
  for (const prompt of prompts) {
    assert.equal(isConversationProvenanceQuestion(prompt), false, prompt)
  }
})

test('deterministic provenance replies are recognizable for repeated paraphrase continuity', () => {
  for (const reply of [
    "That answer was generated by COS's reasoning model (independent-local:qwen). No Enterprise Memory, Knowledge Graph, Learned Corpus, User Memory, or Cognitive Skills were material to that answer. No web search or external AI provider contributed.",
    "That answer was reused from COS's semantic cache; its original reasoning model was independent-local:qwen. No new web search ran for this reply.",
    'This is the real, recorded provenance for the immediately preceding answer.\nPrimary Reasoner: independent-local:qwen\nMaterial Contributors: none.',
    'The immediately preceding reply is already the recorded provenance report for the answer before it.',
  ]) {
    assert.equal(isCosGeneratedProvenanceReply(reply), true, reply)
  }
  assert.equal(isCosGeneratedProvenanceReply('Here is a normal answer about provenance in art history.'), false)
})
