import assert from 'node:assert/strict'
import fs from 'node:fs'
import path from 'node:path'
import test from 'node:test'

const ROOT = path.resolve(import.meta.dirname, '..')
const file = (relative: string) => fs.readFileSync(path.join(ROOT, relative), 'utf8')

test('University practice revalidates the exact plan round after inference and fences reconciliation', () => {
  const runner = file('lib/ai/cos/cosUniversityDeliberatePracticeRunner.ts')
  const inferenceAt = runner.indexOf('execution = await callCosReasoner')
  const postInferenceFenceAt = runner.indexOf("university_practice_post_inference_fence_failed")
  const resultRpcAt = runner.indexOf("db.rpc('cos_record_cognitive_practice_result'")
  assert.ok(inferenceAt >= 0)
  assert.ok(postInferenceFenceAt > inferenceAt)
  assert.ok(resultRpcAt > postInferenceFenceAt)
  assert.match(runner, /practice_round_advanced_during_inference/)
  assert.match(runner, /practice_round_advanced_before_reconciliation/)
  assert.match(runner, /select\('status,evidence,attempt_count'\)/)
  assert.match(runner, /\.eq\('status', 'studying'\)\s*\.eq\('attempt_count', practiceRound\)/)
  assert.match(runner, /return ready && Boolean\(update\.data\?\.id\)/)
})

test('committed practice failure remains a failure even though the atomic RPC reopens study', () => {
  const runner = file('lib/ai/cos/cosUniversityDeliberatePracticeRunner.ts')
  const rpcAt = runner.indexOf("db.rpc('cos_record_cognitive_practice_result'")
  const statusAt = runner.indexOf('const committedQueueStatus = clean(asRecord(rpc.data).queueStatus')
  const refreshAt = runner.indexOf('await refreshCognitiveSkillStatus(item.skill_key)', statusAt)
  const failedAt = runner.indexOf("committedQueueStatus === 'failed'", statusAt)
  const postCommitFenceAt = runner.indexOf('practice_round_advanced_before_reconciliation', failedAt)
  assert.ok(rpcAt >= 0)
  assert.ok(statusAt > rpcAt)
  assert.ok(refreshAt > statusAt)
  assert.ok(failedAt > refreshAt)
  assert.ok(postCommitFenceAt > failedAt)
  assert.match(runner, /status: 'failed',\s*passed: false/)
  assert.match(runner, /reasons: \[grade\.reason\]/)
  assert.match(runner, /committedQueueStatus === 'queued'/)
  assert.match(runner, /committedQueueStatus !== 'passed'/)
  assert.match(runner, /if \(run\.planId && run\.practiceRound && run\.status === 'passed'\)/)
  assert.equal((runner.match(/await reconcilePlan\(/g) || []).length, 1)
})

test('canonical practice-result transaction locks the University queue and exact accepted-study plan before mutation', () => {
  const migration = file('supabase/migrations/20260908234500_cos_university_practice_atomic_result_fence.sql')
  const queueLockAt = migration.indexOf('from public.cos_active_practice_queue')
  const planLockAt = migration.indexOf('from public.cos_university_study_plans')
  const failurePlanMutationAt = migration.indexOf("if university_plan_id is not null and next_status = 'failed' then")
  const queueMutationAt = migration.indexOf('update public.cos_active_practice_queue')
  const experienceMutationAt = migration.indexOf('insert into public.cos_cognitive_experiences')
  assert.ok(queueLockAt >= 0)
  assert.ok(planLockAt > queueLockAt)
  assert.ok(failurePlanMutationAt > planLockAt)
  assert.ok(queueMutationAt > failurePlanMutationAt)
  assert.ok(experienceMutationAt > queueMutationAt)

  assert.match(migration, /create or replace function public\.cos_record_cognitive_practice_result\(/i)
  assert.match(migration, /where id = p_queue_id\s+for update;/i)
  assert.match(migration, /q\.metadata->>'origin' = 'cos_university_deliberate_practice'/)
  assert.match(migration, /university_plan_id := \(q\.metadata->>'universityPlanId'\)::uuid/)
  assert.match(migration, /university_practice_round := \(q\.metadata->>'practiceRound'\)::integer/)
  assert.match(migration, /where id = university_plan_id\s+and agent_id = 'cos'\s+for update;/i)
  assert.match(migration, /university_plan\.attempt_count <> university_practice_round/)
  assert.match(migration, /university_proof->>'studyAttempt' <> university_practice_round::text/)
  assert.match(migration, /university_proof->>'source' <> 'continuous_learning_accepted_gap'/)
  assert.match(migration, /university_proof->'academicCredit' is distinct from 'false'::jsonb/)
  assert.match(migration, /jsonb_array_length\(university_proof->'evidenceRefs'\) < 1/)
  assert.match(migration, /university_proof_observed_at is distinct from university_plan\.last_attempt_at/)
  assert.match(migration, /university_remediation->'requiresNewStudyAttempt' = 'true'::jsonb/)
  assert.doesNotMatch(migration, /cos_record_university_cognitive_practice_result/)
})

test('terminal University failure versions and reopens the locked plan before releasing the result transaction', () => {
  const migration = file('supabase/migrations/20260908234500_cos_university_practice_atomic_result_fence.sql')
  const failureAt = migration.indexOf("if university_plan_id is not null and next_status = 'failed' then")
  const planUpdateAt = migration.indexOf('update public.cos_university_study_plans', failureAt)
  const queueUpdateAt = migration.indexOf('update public.cos_active_practice_queue')
  assert.ok(failureAt >= 0)
  assert.ok(planUpdateAt > failureAt)
  assert.ok(queueUpdateAt > planUpdateAt)
  assert.match(migration, /last_attempt_at = null/)
  assert.match(migration, /'practiceRemediation', jsonb_build_object/)
  assert.match(migration, /'practiceRound', university_practice_round/)
  assert.match(migration, /'requestedAt', now_at/)
  assert.match(migration, /'requiresNewStudyAttempt', true/)
  assert.match(migration, /'requiresIndependentRetest', true/)
  assert.match(migration, /'academicCredit', false/)
  assert.match(migration, /updated_at = now_at/)
  assert.match(migration, /and attempt_count = university_practice_round/)
  assert.match(migration, /university_practice_failure_remediation_fence_failed/)
})

test('SECURITY DEFINER practice-result mutation is service-role-only', () => {
  const lockdown = file('supabase/migrations/20260908234600_cos_university_practice_rpc_lockdown.sql')
  assert.match(lockdown, /revoke all on function public\.cos_record_cognitive_practice_result\(uuid, boolean, double precision, text, jsonb\) from public/i)
  assert.match(lockdown, /from anon, authenticated/i)
  assert.match(lockdown, /grant execute on function public\.cos_record_cognitive_practice_result\(uuid, boolean, double precision, text, jsonb\) to service_role/i)
  assert.match(lockdown, /Service-role-only canonical cognitive practice recorder/)
})
