import test from 'node:test'
import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'

const source = (path: string) => readFileSync(new URL(path, import.meta.url), 'utf8')

test('distilled evaluation is bounded and requires exact holdout, canary and authorization', () => {
  const evaluator = source('../lib/ai/cos/cosUniversityDistilledArtifactEvaluation.ts')
  assert.match(evaluator, /distilledEvaluationCallCeilings\(expectedHashes\.length\)/)
  assert.match(evaluator, /consumeEndpointCall\(input\.budget\)/)
  assert.match(evaluator, /consumeJudgeCall\(input\.budget\)/)
  assert.match(evaluator, /consumeSoloRetryCall\(input\.budget\)/)
  assert.match(evaluator, /withEvaluationCallAudit\(budget, async \(\) =>/)
  assert.match(evaluator, /distilledEvaluationCallUsageFromError/)
  assert.match(evaluator, /evaluation_approval_missing_or_expired/)
  assert.match(evaluator, /exact_runtime_canary_not_proven/)
  assert.match(evaluator, /holdout_revision_moved/)
  assert.match(evaluator, /holdout_manifest_mismatch/)
  assert.match(evaluator, /sha256Raw\(text\) !== itemHash/)
  assert.match(evaluator, /MIN_DISTILLED_RETENTION_DELAY_MS = DISTILLED_EVALUATION_RETENTION_DELAY_MS/)
})

test('RunPod chunks the exact pinned holdout under its manifest-derived call budget', () => {
  const evaluator = source('../lib/ai/cos/cosUniversityDistilledArtifactEvaluation.ts')
  const approvalPolicy = source('../lib/ai/cos/cosUniversityRuntimeApprovalPolicy.ts')
  assert.match(evaluator, /COS_DISTILLED_EVALUATOR_VERSION = DISTILLED_EVALUATOR_VERSION/)
  assert.match(approvalPolicy, /DISTILLED_EVALUATOR_VERSION = 'cos-distilled-exact-artifact-evaluator-v4'/)
  assert.match(evaluator, /MAX_BATCH_CASES = DISTILLED_EVALUATION_MAX_BATCH_CASES/)
  assert.match(evaluator, /MIN_BATCH_COMPLETION_TOKENS = 384/)
  assert.match(evaluator, /MAX_BATCH_COMPLETION_TOKENS = 960/)
  assert.match(evaluator, /BATCH_COMPLETION_TOKENS_PER_CASE = 80/)
  assert.match(evaluator, /at most 40 words per answer/)
  assert.match(evaluator, /chat_template_kwargs: \{ enable_thinking: false \}/)
  assert.match(evaluator, /Math\.min\(\s*MAX_BATCH_COMPLETION_TOKENS,/)
  assert.match(evaluator, /if \(!input\.cases\.length \|\| input\.cases\.length > MAX_BATCH_CASES\)/)
  assert.match(evaluator, /if \(expectedHashes\.length > MAX_SUITE_CASES\) throw new Error\('distilled_evaluation_holdout_batch_size_unsupported'\)/)
  assert.match(evaluator, /MAX_SUITE_CASES = DISTILLED_EVALUATION_MAX_HOLDOUT_CASES/)
  assert.doesNotMatch(evaluator, /Math\.min\(4096, Math\.max\(1024, input\.cases\.length \* 420\)\)/)
})

test('student never grades itself and teacher cannot be the independent evaluator', () => {
  const evaluator = source('../lib/ai/cos/cosUniversityDistilledArtifactEvaluation.ts')
  const inference = source('../lib/ai/local-inference.ts')
  assert.match(evaluator, /purpose: 'independent_assessment'/)
  assert.match(evaluator, /independentEvaluatorConfigFromEnv\(\)/)
  assert.match(evaluator, /signIndependentEvaluatorPayload/)
  assert.match(evaluator, /evaluatorIds\.has\(clean\(artifact\.teacher_model_id/)
  assert.match(evaluator, /DISTILLED_BASE_MODEL_ID/)
  assert.match(evaluator, /DISTILLED_MODEL_NAME/)
  assert.match(inference, /purpose\.includes\('independent_assessment'\)/)
  assert.match(inference, /protectedIndependentEvaluation/)
})

test('evaluation stores hashes and scores, never raw prompt or response columns', () => {
  const migration = source('../supabase/migrations/20260914122500_cos_distilled_evaluation_runs.sql')
  assert.match(migration, /cos_university_distilled_evaluation_runs/)
  assert.match(migration, /response_hashes jsonb/)
  assert.doesNotMatch(migration, /prompt text|response text|reference text|chain_of_thought|hidden_reasoning text/)
  assert.match(migration, /enable row level security/)
  assert.match(migration, /revoke all on table public\.cos_university_distilled_evaluation_runs from public, anon, authenticated/)
})

test('a saved verdict resumes idempotent evidence admission before any new paid authorization', () => {
  const evaluator = source('../lib/ai/cos/cosUniversityDistilledArtifactEvaluation.ts')
  const recoveryIndex = evaluator.indexOf('const priorRun = await savedDistilledEvaluationRun')
  const approvalIndex = evaluator.indexOf('const approval = await evaluationApproval')
  const completionIndex = evaluator.indexOf('async function completeSavedDistilledEvaluation')
  const finalizationIndex = evaluator.indexOf(".update({ status: outcome.nextStatus", completionIndex)
  const reconciliationIndex = evaluator.indexOf('runCosUniversityControlledFineTuning(input.now)', completionIndex)
  const retentionResumeIndex = evaluator.indexOf('resumedRetention: true as const')
  const holdoutFetchIndex = evaluator.indexOf('const holdoutCases = await fetchPinnedHoldout')
  assert.ok(recoveryIndex >= 0 && recoveryIndex < approvalIndex)
  assert.ok(completionIndex >= 0 && finalizationIndex > completionIndex && reconciliationIndex > finalizationIndex)
  assert.ok(retentionResumeIndex > approvalIndex && holdoutFetchIndex > retentionResumeIndex)
  assert.match(evaluator, /Every claim uses a deterministic idempotency key/)
  assert.match(evaluator, /completeSavedDistilledEvaluation/)
  assert.match(evaluator, /\.eq\('status', 'evaluation_pending'\)[\s\S]*\.select\('status'\)/)
  assert.match(evaluator, /decideCompletedDistilledEvaluation\(\{[\s\S]*retentionEligible:/)
  assert.match(evaluator, /recovered: true as const/)
  assert.match(evaluator, /endpointCalls: 0,[\s\S]*judgeCalls: 0,[\s\S]*soloRetryCalls: 0/)
  assert.match(evaluator, /distilled_evaluation_retention_delay_not_met/)
  assert.match(evaluator, /suiteName: 'retention'/)
})

test('independent evaluator cannot dispatch new training', () => {
  const evaluator = source('../lib/ai/cos/cosUniversityDistilledArtifactEvaluation.ts')
  const route = source('../app/api/cron/cos-university-distilled-evaluation/route.ts')
  assert.doesNotMatch(evaluator, /submitHuggingFaceJob|dispatchUniversityApprovedTraining|generate_teacher_dataset|operation:\s*['"]train['"]/)
  assert.match(route, /CRON_SECRET/)
  assert.match(route, /runUniversityDistilledArtifactEvaluation/)
})

test('evaluator-only signing key falls back to service-only Vault without sharing learner credentials', () => {
  const evaluatorAuth = source('../lib/ai/cos/cosUniversityIndependentEvaluator.ts')
  const route = source('../app/api/cron/cos-university-distilled-evaluation/route.ts')
  const migration = source('../supabase/migrations/20260914130000_cos_independent_evaluator_vault_secret.sql')
  assert.match(evaluatorAuth, /independentEvaluatorConfigFromEnv\(\)/)
  assert.match(evaluatorAuth, /cos_read_independent_evaluator_secret/)
  assert.match(route, /withinRouteDeadline\(independentEvaluatorConfig\(\), routeDeadlineMs\)/)
  assert.match(route, /process\.env\.COS_UNIVERSITY_INDEPENDENT_EVALUATOR_SECRET = evaluator\.secret/)
  assert.match(migration, /vault\.create_secret/)
  assert.match(migration, /gen_random_bytes\(48\)/)
  assert.match(migration, /security definer/)
  assert.match(migration, /revoke all on function public\.cos_read_independent_evaluator_secret\(\) from public, anon, authenticated/)
  assert.match(migration, /grant execute on function public\.cos_read_independent_evaluator_secret\(\) to service_role/)
  assert.doesNotMatch(migration, /RUNPOD_API_KEY|LOCAL_AI_API_KEY|TRAINING_EXECUTOR_SECRET/)
})

test('fresh canary authorization owns a fresh retry budget and produces promotion evidence', () => {
  const route = source('../app/api/cron/runpod-distilled-local-deploy/route.ts')
  assert.match(route, /approvalObservedAt/)
  assert.match(route, /Date\.parse\(String\(row\?\.observed_at/)
  assert.match(route, /authorizationObservedAt: approvalObservedAt/)
  assert.match(route, /recordProductionCanaryEvidence/)
  assert.match(route, /claim: 'production_canary_healthy'/)
  assert.match(route, /verifier: 'host_production_verifier'/)
  assert.match(route, /productionTrafficAuthorized: false/)
})

test('Vercel schedules evaluation independently and spaces canaries beyond their cold-start envelope', () => {
  const config = JSON.parse(source('../vercel.json'))
  assert.equal(config.crons.find((cron: { path: string }) => cron.path === '/api/cron/cos-university-distilled-evaluation')?.schedule, '4,14,24,34,44,54 * * * *')
  assert.equal(config.crons.find((cron: { path: string }) => cron.path === '/api/cron/runpod-distilled-local-deploy')?.schedule, '1,6,11,16,21,26,31,36,41,46,51,56 * * * *')
})

test('evaluation accepts only canonical verifier-bound production canary evidence', () => {
  const evaluator = source('../lib/ai/cos/cosUniversityDistilledArtifactEvaluation.ts')
  assert.match(evaluator, /FINE_TUNE_EVIDENCE_PROFILE/)
  assert.match(evaluator, /row\.verifier === 'host_production_verifier'/)
  assert.match(evaluator, /evidence\?\.claim === 'production_canary_healthy'/)
  assert.match(evaluator, /evidence\?\.trainedArtifactId/)
  assert.match(evaluator, /evidence\?\.revisionKey/)
  assert.match(evaluator, /evidence\?\.exactArtifact === true/)
  assert.match(evaluator, /evidence\?\.authorityExpanded === false/)
  assert.match(evaluator, /observedAt <= now\.getTime\(\)/)
  assert.match(evaluator, /expiresAt > now\.getTime\(\)/)
  assert.doesNotMatch(evaluator, /cos_local_distilled_runtime_deploy_v1/)
  assert.doesNotMatch(evaluator, /local_distilled_runtime_canary_passed/)
})
