import assert from 'node:assert/strict';
import test from 'node:test';
import { buildEnterpriseDecision, type DecisionCandidate } from '../lib/autonomous-systems/decision-engine.ts';

const tenant={tenantId:'tenant-a',environmentId:'prod',region:'us'};
function candidate(overrides:Partial<DecisionCandidate>={}):DecisionCandidate{return {candidateId:'c1',tenant,objectiveId:'o1',objectivePriority:10,capabilityId:'cap.publish',capabilityStatus:'available',policyEffect:'allow',riskLevel:'medium',evidenceRefs:['ev1'],...overrides};}

test('selects the highest-ranked eligible candidate deterministically',()=>{const input={tenant,maxCandidates:10,candidates:[candidate(),candidate({candidateId:'c2',objectivePriority:20})]};const a=buildEnterpriseDecision(input);const b=buildEnterpriseDecision(input);assert.equal(a.selectedCandidateId,'c2');assert.equal(a.disposition,'proceed');assert.equal(a.decisionId,b.decisionId);assert.ok(Object.isFrozen(a));});
test('policy denial and disabled capability are ineligible',()=>{const result=buildEnterpriseDecision({tenant,maxCandidates:10,candidates:[candidate({candidateId:'denied',objectivePriority:100,policyEffect:'deny'}),candidate({candidateId:'disabled',objectivePriority:90,capabilityStatus:'disabled'}),candidate()]});assert.equal(result.selectedCandidateId,'c1');});
test('review and escalation dispositions fail closed',()=>{assert.equal(buildEnterpriseDecision({tenant,maxCandidates:10,candidates:[candidate({policyEffect:'require_review'})]}).disposition,'require_review');assert.equal(buildEnterpriseDecision({tenant,maxCandidates:10,candidates:[candidate({policyEffect:'escalate'})]}).disposition,'escalate');assert.equal(buildEnterpriseDecision({tenant,maxCandidates:10,candidates:[]}).disposition,'block');});
test('degraded capability requires review',()=>{const result=buildEnterpriseDecision({tenant,maxCandidates:10,candidates:[candidate({capabilityStatus:'degraded'})]});assert.equal(result.disposition,'require_review');});
test('tenant boundary, duplicates, and bounds are enforced',()=>{assert.throws(()=>buildEnterpriseDecision({tenant,maxCandidates:10,candidates:[candidate({tenant:{tenantId:'other',environmentId:'prod'}})]}),/tenant_environment_boundary_violation/);assert.throws(()=>buildEnterpriseDecision({tenant,maxCandidates:10,candidates:[candidate(),candidate()]}),/duplicate_candidate_id/);assert.throws(()=>buildEnterpriseDecision({tenant,maxCandidates:0,candidates:[]}),/unbounded_decision_request_rejected/);});
test('ranking is bounded and reports truncation',()=>{const result=buildEnterpriseDecision({tenant,maxCandidates:1,candidates:[candidate(),candidate({candidateId:'c2',objectivePriority:20})]});assert.deepEqual(result.rankedCandidateIds,['c2']);assert.equal(result.truncated,true);});
