import assert from 'node:assert/strict';
import test from 'node:test';
import { simulateEnterpriseExecution } from '../lib/autonomous-systems/execution-orchestrator-simulation.ts';
import type { EnterpriseExecutionPlanSnapshot } from '../lib/autonomous-systems/execution-planner.ts';
import type { EnterpriseExecutionAuthorizationSnapshot } from '../lib/autonomous-systems/execution-authorization-gate.ts';

const tenant={tenantId:'tenant-a',environmentId:'prod',region:'us'};
const plan:EnterpriseExecutionPlanSnapshot={schemaVersion:'1.0.0',planId:'plan-1',tenant,decisionId:'decision-1',disposition:'proceed',executable:false,steps:[{stepId:'prepare',tenant,candidateId:'candidate-1',capabilityId:'content.prepare',action:'prepare',dependsOn:[],riskLevel:'low',requiresHumanApproval:false,evidenceRefs:['step-prepare'],ordinal:1,gate:'none'},{stepId:'publish',tenant,candidateId:'candidate-1',capabilityId:'content.publish',action:'publish',dependsOn:['prepare'],riskLevel:'high',requiresHumanApproval:true,rollbackAction:'unpublish',contingencyAction:'pause',evidenceRefs:['step-publish'],ordinal:2,gate:'human_review'}],approvalStepIds:['publish'],rollbackStepIds:['publish'],contingencyStepIds:['publish'],evidenceRefs:['plan-evidence'],truncated:false};
const authorization:EnterpriseExecutionAuthorizationSnapshot={schemaVersion:'1.0.0',authorizationId:'auth-1',tenant,planId:'plan-1',status:'ready_for_authorization',executable:false,externallyAuthorizable:true,satisfiedApprovalStepIds:['publish'],missingApprovalStepIds:[],reasons:['all_preconditions_satisfied'],evidenceRefs:['auth-evidence'],truncated:false};

function simulate(overrides:Partial<Parameters<typeof simulateEnterpriseExecution>[0]>={}){return simulateEnterpriseExecution({tenant,plan,authorization,simulatedFailureStepIds:[],maxTransitions:16,...overrides});}

test('builds deterministic immutable simulation timelines',()=>{const a=simulate();const b=simulate();assert.equal(a.simulationId,b.simulationId);assert.equal(a.status,'simulated_complete');assert.deepEqual(a.completedStepIds,['prepare','publish']);assert.ok(Object.isFrozen(a));assert.ok(Object.isFrozen(a.transitions[0]));assert.equal(a.executable,false);});
test('simulates rollback without executing actions',()=>{const result=simulate({simulatedFailureStepIds:['publish']});assert.equal(result.status,'simulated_with_rollback');assert.deepEqual(result.rolledBackStepIds,['publish']);assert.equal(result.transitions[1]?.state,'simulated_rollback');assert.equal(result.transitions[1]?.rollbackAction,'unpublish');});
test('preserves missing approval checkpoints',()=>{const waiting={...authorization,status:'approval_required' as const,externallyAuthorizable:false,satisfiedApprovalStepIds:[],missingApprovalStepIds:['publish'],reasons:['required_approval_missing']};const result=simulate({authorization:waiting});assert.equal(result.status,'waiting_for_approval');assert.equal(result.transitions[1]?.state,'waiting_for_approval');});
test('fails closed for blocked authorization',()=>{const blocked={...authorization,status:'blocked' as const,externallyAuthorizable:false,reasons:['policy_invalid']};const result=simulate({authorization:blocked});assert.equal(result.status,'blocked');assert.ok(result.transitions.every(t=>t.state==='blocked'));});
test('enforces tenant and plan boundaries',()=>{assert.throws(()=>simulate({tenant:{tenantId:'other',environmentId:'prod'}}),/plan_tenant_boundary_violation/);assert.throws(()=>simulate({authorization:{...authorization,planId:'other'}}),/authorization_plan_mismatch/);});
test('rejects duplicate and unknown simulated failures',()=>{assert.throws(()=>simulate({simulatedFailureStepIds:['publish','publish']}),/duplicate_simulated_failure_step/);assert.throws(()=>simulate({simulatedFailureStepIds:['missing']}),/unknown_simulated_failure_step/);});
test('bounds transitions and reports truncation',()=>{const result=simulate({maxTransitions:1});assert.equal(result.transitions.length,1);assert.equal(result.truncated,true);assert.throws(()=>simulate({maxTransitions:0}),/unbounded_simulation_rejected/);});
test('skips dependent steps after unrecoverable simulated failure',()=>{const noRollback={...plan,steps:[plan.steps[0]!,{...plan.steps[1]!,rollbackAction:undefined},{...plan.steps[1]!,stepId:'notify',action:'notify',dependsOn:['publish'],rollbackAction:undefined,requiresHumanApproval:false,gate:'none' as const,ordinal:3}],approvalStepIds:['publish'],rollbackStepIds:[]};const result=simulate({plan:noRollback,authorization:{...authorization,planId:noRollback.planId},simulatedFailureStepIds:['publish']});assert.equal(result.status,'blocked');assert.equal(result.transitions[1]?.state,'blocked');assert.equal(result.transitions[2]?.state,'skipped');});
