import assert from 'node:assert/strict';
import test from 'node:test';
import { EAE_ENTERPRISE_CONTEXT_SCHEMA_VERSION as V, EnterpriseRelationshipGraph, buildEnterpriseContextSnapshot, resolvePolicies, buildEnterpriseIntelligenceEnvelope, buildEnterpriseIntelligenceEnvelopeV2, buildWorldState, type DigitalTwinEntity, type EnterprisePolicy, type EnterpriseRelationship } from '../lib/autonomous-systems/index.ts';
const tenant={tenantId:'acme',environmentId:'prod',region:'us'}; const now='2026-07-24T00:00:00.000Z';
function entity(entityId:string, entityType:DigitalTwinEntity['entityType'], extra:Record<string,unknown>={}) { return {schemaVersion:V,entityId,tenant,entityType,displayName:entityId,status:'active',provenance:{source:'customer-cmdb',evidenceRefs:['ev-'+entityId]},observedAt:now,effectiveAt:now,metadata:{classification:'tested'},...extra} as DigitalTwinEntity; }
function edge(relationshipId:string,fromEntityId:string,toEntityId:string,type:EnterpriseRelationship['type']='depends_on') { return {schemaVersion:V,relationshipId,tenant,type,fromEntityId,toEntityId,provenance:{source:'customer-cmdb',evidenceRefs:['ev-'+relationshipId]},observedAt:now,effectiveAt:now,metadata:{}}; }
function graph(){ return new EnterpriseRelationshipGraph(tenant,[entity('bu','business_unit'),entity('app','application'),entity('db','system',{critical:true}),entity('cap','capability',{category:'verification',reference:'verify.health'}),entity('obj','objective',{ownerEntityId:'bu',priority:1,targetMetrics:{uptime:99.9},constraints:['no execution'],affectedBusinessUnitIds:['bu'],affectedSystemIds:['app']})],[edge('a','app','db'),edge('b','db','cap','monitored_by'),edge('c','obj','app','affects')]); }
function request(overrides={}) {return {tenant,affectedEntityIds:['app'],activeObjectiveIds:['obj'],maxDepth:3,maxEntities:10,snapshotAt:now,...overrides};}
test('isolates tenant and environment and rejects invalid or secret entities',()=>{assert.throws(()=>new EnterpriseRelationshipGraph(tenant,[entity('x','system',{tenant:{...tenant,tenantId:'other'}})]),/boundary/); assert.throws(()=>new EnterpriseRelationshipGraph(tenant,[entity('x','system',{metadata:{description:{token:'no'}}})]),/secret/); assert.throws(()=>new EnterpriseRelationshipGraph(tenant,[entity('x','system',{metadata:{description:Infinity}})]),/non_finite/);});
test('traverses deterministically, handles cycles, bounds depth, and rejects duplicate or unknown edges',()=>{const g=graph(); g.addRelationship(edge('cycle','cap','app')); assert.deepEqual(g.traverse(['app'],2),[['app'],['app','db'],['app','db','cap']]); assert.throws(()=>g.traverse(['app'],9),/unbounded/); assert.throws(()=>g.addRelationship(edge('duplicate','app','db')),/duplicate/); assert.throws(()=>g.addRelationship(edge('bad','app','missing')),/unknown/);});
test('selects bounded relevant context, objectives, capabilities, gaps, and immutable deterministic snapshots',()=>{const g=graph(); const one=buildEnterpriseContextSnapshot(g,request({maxEntities:2})); const two=buildEnterpriseContextSnapshot(g,request({maxEntities:2})); assert.equal(one.snapshotId,two.snapshotId); assert.equal(one.relevance.truncated,true); assert.ok(one.activeObjectives.some(x=>x.entityId==='obj')); assert.ok(Object.isFrozen(one)); assert.doesNotThrow(()=>JSON.stringify(one)); const gaps=buildEnterpriseContextSnapshot(g,request()); assert.ok(gaps.gaps.some(x=>x.code==='unknown_system_owner'));});
test('orders policies and detects critical conflicts fail closed',()=>{const policy=(id:string,effect:EnterprisePolicy['effect']):EnterprisePolicy=>entity(id,'policy',{scope:{riskLevel:'critical'},precedence:5,effect}) as EnterprisePolicy; const r=resolvePolicies([policy('z','deny'),policy('a','allow')],request({riskLevel:'critical'})); assert.deepEqual(r.policies.map(x=>x.entityId),['a','z']); assert.equal(r.blocked,true); assert.deepEqual(r.conflicts,['a','z']);});
test('extends only pre-COS envelope with serializable context and no executable surface',()=>{const ctx=buildEnterpriseContextSnapshot(graph(),request()); const observation={schemaVersion:'1.0.0' as const,observationId:'o',tenant,source:'cmdb',subject:'app',observedAt:now,receivedAt:now,critical:false,payload:{status:'ok'}}; const world=buildWorldState({tenant,observations:[observation],now,staleAfterMs:1}); const v1=buildEnterpriseIntelligenceEnvelope({snapshot:world,plans:[],policy:{riskTolerance:'low',minimumConfidence:.5,valueWeight:.2,confidenceWeight:.5,riskWeight:.2,urgencyWeight:.1},emittedAt:now}); const v2=buildEnterpriseIntelligenceEnvelopeV2({envelope:v1,enterpriseContext:ctx}); assert.equal(v2.boundary,'pre_cos_reasoning_only'); assert.equal(v2.enterpriseContext.snapshotId,ctx.snapshotId); assert.doesNotThrow(()=>JSON.stringify(v2)); assert.ok(v2.contextConfidence<1);});
