import assert from 'node:assert/strict';
import test from 'node:test';
import { buildEnterpriseHumanReviewOutcomeAcknowledgmentRegistry } from '../lib/autonomous-systems/human-review-outcome-acknowledgment.ts';

const tenant={tenantId:'tenant-a',environmentId:'prod'};
const outcome={schemaVersion:'1.0.0',outcomeId:'outcome-1',tenant,ledgerId:'ledger-1',disposition:'complete',readOnly:true,executable:false,approvedProposalIds:['p1'],rejectedProposalIds:['p2'],evidenceRequestedProposalIds:[],deferredProposalIds:[],items:[{proposalId:'p1',decision:'approve',reviewerIds:['r1'],ledgerEntryIds:['e1'],reasons:['ok'],valid:true,evidenceRefs:['ev1'],executable:false},{proposalId:'p2',decision:'reject',reviewerIds:['r2'],ledgerEntryIds:['e2'],reasons:['no'],valid:true,evidenceRefs:['ev2'],executable:false}],evidenceRefs:['ev2','ev1'],truncated:false} as const;

function request(){return {tenant,outcome,acknowledgments:[{outcomeItemProposalId:'p1',acknowledgedBy:'operator-1',note:'reviewed',evidenceRefs:['ack-2','ack-1']}],priorAcknowledgmentIds:[],maxAcknowledgments:10};}

test('is deterministic, immutable, read-only, and non-executable',()=>{const a=buildEnterpriseHumanReviewOutcomeAcknowledgmentRegistry(request());const b=buildEnterpriseHumanReviewOutcomeAcknowledgmentRegistry(request());assert.deepEqual(a,b);assert.ok(Object.isFrozen(a));assert.ok(Object.isFrozen(a.records));assert.equal(a.readOnly,true);assert.equal(a.executable,false);});
test('reports partial and unacknowledged proposals',()=>{const result=buildEnterpriseHumanReviewOutcomeAcknowledgmentRegistry(request());assert.equal(result.disposition,'partial');assert.deepEqual(result.unacknowledgedProposalIds,['p2']);});
test('reports complete when all proposals are acknowledged',()=>{const result=buildEnterpriseHumanReviewOutcomeAcknowledgmentRegistry({...request(),acknowledgments:[...request().acknowledgments,{outcomeItemProposalId:'p2',acknowledgedBy:'operator-2',note:'reviewed',evidenceRefs:[]}]});assert.equal(result.disposition,'complete');});
test('fails closed for unknown proposals and duplicate acknowledgments',()=>{const result=buildEnterpriseHumanReviewOutcomeAcknowledgmentRegistry({...request(),acknowledgments:[{outcomeItemProposalId:'missing',acknowledgedBy:'operator-1',note:'x',evidenceRefs:[]},{outcomeItemProposalId:'missing',acknowledgedBy:'operator-1',note:'x',evidenceRefs:[]}]});assert.equal(result.disposition,'invalid');assert.ok(result.records.some(record=>record.errors.includes('unknown_outcome_proposal')));assert.ok(result.records.some(record=>record.errors.includes('duplicate_acknowledgment')));});
test('preserves blocked and empty dispositions',()=>{assert.equal(buildEnterpriseHumanReviewOutcomeAcknowledgmentRegistry({...request(),outcome:{...outcome,disposition:'blocked'}}).disposition,'blocked');assert.equal(buildEnterpriseHumanReviewOutcomeAcknowledgmentRegistry({...request(),outcome:{...outcome,items:[],approvedProposalIds:[],rejectedProposalIds:[]},acknowledgments:[]}).disposition,'empty');});
test('enforces tenant, safety, and bounds',()=>{assert.throws(()=>buildEnterpriseHumanReviewOutcomeAcknowledgmentRegistry({...request(),tenant:{tenantId:'other',environmentId:'prod'}}),/tenant_boundary/);assert.throws(()=>buildEnterpriseHumanReviewOutcomeAcknowledgmentRegistry({...request(),outcome:{...outcome,executable:true as false}}),/unsafe/);assert.throws(()=>buildEnterpriseHumanReviewOutcomeAcknowledgmentRegistry({...request(),maxAcknowledgments:0}),/unbounded/);});
test('suppresses prior acknowledgments and reports truncation',()=>{const first=buildEnterpriseHumanReviewOutcomeAcknowledgmentRegistry(request());const result=buildEnterpriseHumanReviewOutcomeAcknowledgmentRegistry({...request(),priorAcknowledgmentIds:[first.records[0]!.acknowledgmentId],acknowledgments:[...request().acknowledgments,{outcomeItemProposalId:'p2',acknowledgedBy:'operator-2',note:'reviewed',evidenceRefs:[]}],maxAcknowledgments:1});assert.equal(result.records.length,1);assert.equal(result.records[0]!.proposalId,'p2');assert.equal(result.truncated,false);});
test('sorts and deduplicates evidence',()=>{const result=buildEnterpriseHumanReviewOutcomeAcknowledgmentRegistry(request());assert.deepEqual(result.records[0]!.evidenceRefs,['ack-1','ack-2']);assert.deepEqual(result.evidenceRefs,['ack-1','ack-2','ev1','ev2']);});
