import assert from 'node:assert/strict';
import test from 'node:test';
import type { EnterpriseHumanReviewNestedAttestationRegistryCertificateV2IntegrityResult } from '../lib/autonomous-systems/human-review-attestation-certificate-registry-attestation-registry-certificate-registry-attestation-registry-certificate-registry-attestation-registry-certificate-registry-attestation-registry-certificate-integrity-validator.ts';
import { buildEnterpriseHumanReviewNestedAttestationRegistryCertificateV2Registry } from '../lib/autonomous-systems/human-review-nested-attestation-registry-certificate-v2-registry.ts';
import { validateEnterpriseHumanReviewNestedAttestationRegistryCertificateV2RegistryIntegrity } from '../lib/autonomous-systems/human-review-nested-attestation-registry-certificate-v2-registry-integrity-validator.ts';

// This suite also serves as the preview-deployment smoke contract for this bounded EAE slice.
const tenant={tenantId:'tenant-a',environmentId:'env-a'};
function integrity(certificateId:string, certificateSerial:string, valid=true):EnterpriseHumanReviewNestedAttestationRegistryCertificateV2IntegrityResult { return {schemaVersion:'1.0.0',validationId:`validation-${certificateId}`,tenant,certificateId,certificateSerial,registryId:`source-${certificateId}`,sourceValidationId:`source-validation-${certificateId}`,issuerId:'issuer-a',disposition:valid?'valid':'invalid',valid,errors:valid?[]:['invalid'],validatedAttestationIds:['attestation-b','attestation-a'],evidenceRefs:['z','a'],truncated:false,readOnly:true,executable:false}; }
const registry=buildEnterpriseHumanReviewNestedAttestationRegistryCertificateV2Registry({tenant,integrityResults:[integrity('certificate-b','SERIAL-B'),integrity('certificate-a','SERIAL-A')],priorCertificateIds:[],maxEntries:10});

test('validates deterministic frozen registry integrity',()=>{ const first=validateEnterpriseHumanReviewNestedAttestationRegistryCertificateV2RegistryIntegrity({tenant,registry,maxEntries:10}); const second=validateEnterpriseHumanReviewNestedAttestationRegistryCertificateV2RegistryIntegrity({tenant,registry,maxEntries:10}); assert.deepEqual(first,second); assert.equal(first.disposition,'valid'); assert.equal(first.valid,true); assert.deepEqual(first.validatedCertificateIds,['certificate-a','certificate-b']); assert.deepEqual(first.evidenceRefs,['a','z']); assert.equal(Object.isFrozen(first),true); assert.equal(Object.isFrozen(first.errors),true); });

test('rejects forged registry identity and duplicate certificate identities',()=>{ const forged={...registry,registryId:'tampered',entries:[registry.entries[0],{...registry.entries[1],certificateId:registry.entries[0].certificateId,certificateSerial:registry.entries[0].certificateSerial}]}; const result=validateEnterpriseHumanReviewNestedAttestationRegistryCertificateV2RegistryIntegrity({tenant,registry:forged,maxEntries:10}); assert.equal(result.valid,false); for(const error of ['registry_id_digest_mismatch','duplicate_certificate_id','duplicate_certificate_serial']) assert.equal(result.errors.includes(error),true); });

test('enforces disposition consistency and prior/rejected exclusion',()=>{ const invalid={...registry,disposition:'complete' as const,priorCertificateIds:[registry.entries[0].certificateId],rejectedCertificateIds:[registry.entries[1].certificateId],entries:[{...registry.entries[0],valid:false,disposition:'invalid' as const},registry.entries[1]]}; const result=validateEnterpriseHumanReviewNestedAttestationRegistryCertificateV2RegistryIntegrity({tenant,registry:invalid,maxEntries:10}); assert.equal(result.valid,false); for(const error of ['complete_registry_contains_invalid_certificate','prior_certificate_reincluded','rejected_certificate_reincluded','registry_id_digest_mismatch']) assert.equal(result.errors.includes(error),true); });

test('enforces tenant, safety, bounds, and truncation',()=>{ assert.throws(()=>validateEnterpriseHumanReviewNestedAttestationRegistryCertificateV2RegistryIntegrity({tenant:{tenantId:'other',environmentId:'env-a'},registry,maxEntries:10}),/tenant_boundary_violation/); assert.throws(()=>validateEnterpriseHumanReviewNestedAttestationRegistryCertificateV2RegistryIntegrity({tenant,registry:{...registry,executable:true as false},maxEntries:10}),/unsafe/); assert.throws(()=>validateEnterpriseHumanReviewNestedAttestationRegistryCertificateV2RegistryIntegrity({tenant,registry,maxEntries:0}),/unbounded/); const result=validateEnterpriseHumanReviewNestedAttestationRegistryCertificateV2RegistryIntegrity({tenant,registry,maxEntries:1}); assert.equal(result.truncated,true); assert.deepEqual(result.validatedCertificateIds,['certificate-a']); });