import assert from 'node:assert/strict';
import test from 'node:test';
import type { EnterpriseHumanReviewNestedAttestationRegistryCertificateV2RegistryIntegrityResult } from '../lib/autonomous-systems/human-review-nested-attestation-registry-certificate-v2-registry-integrity-validator.ts';
import { buildEnterpriseHumanReviewNestedAttestationRegistryCertificateV2RegistryAttestation } from '../lib/autonomous-systems/human-review-nested-attestation-registry-certificate-v2-registry-attestation.ts';

const tenant={tenantId:'tenant-a',environmentId:'env-a'};
function integrity(overrides:Partial<EnterpriseHumanReviewNestedAttestationRegistryCertificateV2RegistryIntegrityResult>={}):EnterpriseHumanReviewNestedAttestationRegistryCertificateV2RegistryIntegrityResult { return {schemaVersion:'1.0.0',validationId:'validation-a',tenant,registryId:'registry-a',disposition:'valid',valid:true,errors:[],validatedCertificateIds:['certificate-b','certificate-a','certificate-a'],evidenceRefs:['z','a'],truncated:false,readOnly:true,executable:false,...overrides}; }

const request={tenant,integrity:integrity(),attestorId:' attestor-a ',statement:' registry reviewed ',evidenceRefs:['b','a']};

test('builds deterministic frozen attestation',()=>{ const first=buildEnterpriseHumanReviewNestedAttestationRegistryCertificateV2RegistryAttestation(request); const second=buildEnterpriseHumanReviewNestedAttestationRegistryCertificateV2RegistryAttestation(request); assert.deepEqual(first,second); assert.equal(first.disposition,'attested'); assert.equal(first.attestorId,'attestor-a'); assert.equal(first.statement,'registry reviewed'); assert.deepEqual(first.certificateIds,['certificate-a','certificate-b']); assert.deepEqual(first.evidenceRefs,['a','b','z']); assert.equal(Object.isFrozen(first),true); assert.equal(Object.isFrozen(first.certificateIds),true); });

test('propagates rejected, empty, and truncation states',()=>{ const rejected=buildEnterpriseHumanReviewNestedAttestationRegistryCertificateV2RegistryAttestation({...request,integrity:integrity({disposition:'invalid',valid:false,errors:['bad'],truncated:true})}); assert.equal(rejected.disposition,'rejected'); assert.equal(rejected.sourceTruncated,true); const empty=buildEnterpriseHumanReviewNestedAttestationRegistryCertificateV2RegistryAttestation({...request,integrity:integrity({disposition:'empty',validatedCertificateIds:[]})}); assert.equal(empty.disposition,'empty'); });

test('enforces tenant, safety, required fields, and bounds',()=>{ assert.throws(()=>buildEnterpriseHumanReviewNestedAttestationRegistryCertificateV2RegistryAttestation({...request,tenant:{tenantId:'other',environmentId:'env-a'}}),/tenant_boundary_violation/); assert.throws(()=>buildEnterpriseHumanReviewNestedAttestationRegistryCertificateV2RegistryAttestation({...request,integrity:{...request.integrity,executable:true as false}}),/unsafe/); assert.throws(()=>buildEnterpriseHumanReviewNestedAttestationRegistryCertificateV2RegistryAttestation({...request,attestorId:' '}),/attestor_id_required/); assert.throws(()=>buildEnterpriseHumanReviewNestedAttestationRegistryCertificateV2RegistryAttestation({...request,statement:' '}),/attestation_statement_required/); assert.throws(()=>buildEnterpriseHumanReviewNestedAttestationRegistryCertificateV2RegistryAttestation({...request,statement:'x'.repeat(2049)}),/unbounded/); });
