import assert from 'node:assert/strict';
import test from 'node:test';
import { evaluateEnterpriseOutcome } from '../lib/autonomous-systems/outcome-evaluator.ts';
import type { EnterpriseExecutionSimulationSnapshot } from '../lib/autonomous-systems/execution-orchestrator-simulation.ts';

const tenant={tenantId:'tenant-a',environmentId:'prod',region:'us'};
const simulation:EnterpriseExecutionSimulationSnapshot={schemaVersion:'1.0.0',simulationId:'sim-1',tenant,planId:'plan-1',authorizationId:'auth-1',status:'simulated_complete',executable:false,transitions:[],completedStepIds:['prepare'],rolledBackStepIds:[],blockedStepIds:[],evidenceRefs:['simulation-evidence'],truncated:false};
function evaluate(overrides:Partial<Parameters<typeof evaluateEnterpriseOutcome>[0]>={}){return evaluateEnterpriseOutcome({tenant,simulation,policyCompliant:true,metrics:[{metricId:'quality',target:100,actual:100,weight:2,evidenceRefs:['quality-evidence']},{metricId:'speed',target:10,actual:10,weight:1,evidenceRefs:['speed-evidence']}],maxMetrics:16,...overrides});}

test('builds deterministic immutable validated outcomes',()=>{const a=evaluate();const b=evaluate();assert.equal(a.evaluationId,b.evaluationId);assert.equal(a.disposition,'validated');assert.equal(a.weightedScore,1);assert.equal(a.readOnly,true);assert.equal(a.executable,false);assert.ok(Object.isFrozen(a));assert.ok(Object.isFrozen(a.metrics[0]));});
test('flags missed metrics for review',()=>{const result=evaluate({metrics:[{metricId:'quality',target:100,actual:50,weight:1,evidenceRefs:[]}]});assert.equal(result.disposition,'needs_review');assert.equal(result.metrics[0]?.status,'missed');assert.deepEqual(result.recommendations,['review_missed_outcome_metrics']);});
test('blocks policy noncompliance',()=>{const result=evaluate({policyCompliant:false});assert.equal(result.disposition,'blocked');assert.ok(result.recommendations.includes('resolve_policy_noncompliance'));});
test('preserves simulation rollback and approval signals',()=>{const rollback=evaluate({simulation:{...simulation,status:'simulated_with_rollback'}});assert.equal(rollback.disposition,'needs_review');assert.ok(rollback.recommendations.includes('review_rollback_path'));const waiting=evaluate({simulation:{...simulation,status:'waiting_for_approval'}});assert.ok(waiting.recommendations.includes('obtain_required_approvals'));});
test('handles unavailable metric evidence',()=>{const result=evaluate({metrics:[{metricId:'quality',target:100,weight:1,evidenceRefs:[]}]});assert.equal(result.metrics[0]?.status,'unavailable');assert.equal(result.weightedScore,0);assert.ok(result.recommendations.includes('collect_missing_metric_evidence'));});
test('enforces tenant and executable boundaries',()=>{assert.throws(()=>evaluate({tenant:{tenantId:'other',environmentId:'prod'}}),/simulation_tenant_boundary_violation/);assert.throws(()=>evaluate({simulation:{...simulation,executable:true as never}}),/executable_simulation_rejected/);});
test('rejects duplicate and invalid metrics',()=>{assert.throws(()=>evaluate({metrics:[{metricId:'x',target:1,actual:1,weight:1,evidenceRefs:[]},{metricId:'x',target:1,actual:1,weight:1,evidenceRefs:[]}]}),/duplicate_metric_id/);assert.throws(()=>evaluate({metrics:[{metricId:'x',target:1,actual:1,weight:0,evidenceRefs:[]}]}),/invalid_metric_definition/);});
test('bounds metrics and reports truncation',()=>{const result=evaluate({maxMetrics:1});assert.equal(result.metrics.length,1);assert.equal(result.truncated,true);assert.throws(()=>evaluate({maxMetrics:0}),/unbounded_outcome_evaluation_rejected/);});
