import assert from 'node:assert/strict';
import test from 'node:test';
import { prioritizeEnterpriseAdaptationProposals } from '../lib/autonomous-systems/proposal-prioritization-engine.ts';
import type { EnterpriseAdaptationProposalSnapshot } from '../lib/autonomous-systems/adaptation-proposal-engine.ts';

const tenant={tenantId:'tenant-a',environmentId:'prod',region:'us'};
const proposalSet:EnterpriseAdaptationProposalSnapshot={schemaVersion:'1.0.0',proposalSetId:'set-1',tenant,feedbackId:'feedback-1',evaluationId:'evaluation-1',disposition:'ready_for_human_review',readOnly:true,executable:false,proposals:[{proposalId:'proposal-a',signalId:'signal-a',target:'plan',action:'adjust',rationale:'missed',confidence:0.8,requiresHumanApproval:true,executable:false,evidenceRefs:['b','a']},{proposalId:'proposal-b',signalId:'signal-b',target:'policy',action:'hold',rationale:'review',confidence:0.6,requiresHumanApproval:true,executable:false,evidenceRefs:['c']}],acknowledgedProposalIds:[],evidenceRefs:['root'],truncated:false};
function prioritize(overrides:Partial<Parameters<typeof prioritizeEnterpriseAdaptationProposals>[0]>={}){return prioritizeEnterpriseAdaptationProposals({tenant,proposalSet,targetWeights:{plan:1,policy:0.2},maxRankedProposals:16,...overrides});}

test('ranks deterministically and freezes output',()=>{const a=prioritize();const b=prioritize();assert.equal(a.prioritizationId,b.prioritizationId);assert.equal(a.rankedProposals[0]?.proposalId,'proposal-a');assert.equal(a.rankedProposals[0]?.rank,1);assert.ok(Object.isFrozen(a));assert.ok(Object.isFrozen(a.rankedProposals[0]));assert.equal(a.executable,false);});
test('uses target weights and stable tie breaking',()=>{const result=prioritize({targetWeights:{plan:0,policy:1}});assert.equal(result.rankedProposals[0]?.proposalId,'proposal-b');const tied=prioritize({proposalSet:{...proposalSet,proposals:proposalSet.proposals.map(p=>({...p,confidence:0.5,target:'plan'}))},targetWeights:{plan:0.5}});assert.deepEqual(tied.rankedProposals.map(p=>p.proposalId),['proposal-a','proposal-b']);});
test('preserves blocked and evidence dispositions',()=>{assert.equal(prioritize({proposalSet:{...proposalSet,disposition:'blocked'}}).disposition,'blocked');assert.equal(prioritize({proposalSet:{...proposalSet,disposition:'needs_evidence'}}).disposition,'needs_evidence');});
test('enforces tenant and proposal set safety boundaries',()=>{assert.throws(()=>prioritize({tenant:{tenantId:'other',environmentId:'prod'}}),/proposal_set_tenant_boundary_violation/);assert.throws(()=>prioritize({proposalSet:{...proposalSet,executable:true as never}}),/unsafe_proposal_set_rejected/);});
test('rejects unsafe and duplicate proposals',()=>{assert.throws(()=>prioritize({proposalSet:{...proposalSet,proposals:[proposalSet.proposals[0]!,{...proposalSet.proposals[0]!} ]}}),/duplicate_proposal_id/);assert.throws(()=>prioritize({proposalSet:{...proposalSet,proposals:[{...proposalSet.proposals[0]!,requiresHumanApproval:false as never}]}}),/unsafe_proposal_rejected/);});
test('validates weights',()=>{assert.throws(()=>prioritize({targetWeights:{plan:2}}),/invalid_target_weight/);assert.throws(()=>prioritize({targetWeights:{plan:-1}}),/invalid_target_weight/);});
test('bounds ranking and reports truncation',()=>{const result=prioritize({maxRankedProposals:1});assert.equal(result.rankedProposals.length,1);assert.equal(result.truncated,true);assert.throws(()=>prioritize({maxRankedProposals:0}),/unbounded_proposal_prioritization_rejected/);});
test('sorts and deduplicates evidence',()=>{const result=prioritize();assert.deepEqual(result.rankedProposals[0]?.evidenceRefs,['a','b']);assert.deepEqual(result.evidenceRefs,['a','b','c','root']);});
