import assert from 'node:assert/strict';
import test from 'node:test';
import { EnterpriseRelationshipGraph, buildEnterpriseContextSnapshot, EAE_ENTERPRISE_CONTEXT_SCHEMA_VERSION, type DigitalTwinEntity } from '../lib/autonomous-systems/enterprise-context.ts';
import { EAE_OBJECTIVE_SCHEMA_VERSION, type ObjectiveEvaluation } from '../lib/autonomous-systems/objective-engine.ts';
import { assessEnterpriseRisks } from '../lib/autonomous-systems/risk-engine.ts';

const tenant = { tenantId: 'acme', environmentId: 'production', region: 'us' };
const now = '2026-07-24T00:00:00.000Z';
function entity(entityId: string, entityType: DigitalTwinEntity['entityType'], extra: Record<string, unknown> = {}): DigitalTwinEntity { return { schemaVersion: EAE_ENTERPRISE_CONTEXT_SCHEMA_VERSION, entityId, tenant, entityType, displayName: entityId, status: 'active', provenance: { source: 'cmdb', evidenceRefs: [`evidence-${entityId}`] }, observedAt: now, effectiveAt: now, metadata: { classification: 'internal', riskLevel: 'high' }, ...extra } as DigitalTwinEntity; }
function snapshot() { const graph = new EnterpriseRelationshipGraph(tenant, [entity('risk-payment', 'risk', { critical: true }), entity('application', 'application')]); return buildEnterpriseContextSnapshot(graph, { tenant, affectedEntityIds: ['risk-payment', 'application'], maxDepth: 1, maxEntities: 10, snapshotAt: now }); }
function request(overrides: Record<string, unknown> = {}) { return { tenant, snapshot: snapshot(), assessedAt: now, maxFindings: 10, ...overrides } as Parameters<typeof assessEnterpriseRisks>[0]; }

test('produces deterministic immutable, JSON-serializable pre-COS risk assessments', () => { const first = assessEnterpriseRisks(request()); const second = assessEnterpriseRisks(request()); assert.equal(first.assessmentId, second.assessmentId); assert.equal(first.boundary, 'pre_cos_reasoning_only'); assert.equal(first.overallRisk, 'high'); assert.equal(first.findings[0]?.source, 'context_risk'); assert.ok(Object.isFrozen(first)); assert.doesNotThrow(() => JSON.stringify(first)); });
test('bridges blocked objectives without creating actions or approvals', () => { const evaluation: ObjectiveEvaluation = { schemaVersion: EAE_OBJECTIVE_SCHEMA_VERSION, evaluationId: 'objectives-1', tenant, evaluatedAt: now, rankedObjectives: [], conflicts: [], dependencyOrder: [], blockedObjectiveIds: ['objective-1'], truncated: false }; const result = assessEnterpriseRisks(request({ objectiveEvaluation: evaluation })); assert.equal(result.sourceObjectiveEvaluationId, 'objectives-1'); assert.equal(result.findings.find(finding => finding.source === 'objective_evaluation')?.objectiveIds[0], 'objective-1'); });
test('fails closed for contradictory, cross-tenant, secret-shaped, and unbounded input', () => { assert.throws(() => assessEnterpriseRisks(request({ tenant: { ...tenant, environmentId: 'preview' } })), /boundary/); assert.throws(() => assessEnterpriseRisks(request({ maxFindings: 257 })), /unbounded/); assert.throws(() => assessEnterpriseRisks(request({ snapshot: { ...snapshot(), gaps: [{ code: 'policy_conflict', severity: 'critical', detail: 'contradiction' }] } })), /contradictory/); assert.throws(() => assessEnterpriseRisks(request({ snapshot: { ...snapshot(), entities: [{ ...snapshot().entities[0], metadata: { apiKey: 'forbidden' } }] } })), /secret/); const contradictory: ObjectiveEvaluation = { schemaVersion: EAE_OBJECTIVE_SCHEMA_VERSION, evaluationId: 'objectives-2', tenant, evaluatedAt: now, rankedObjectives: [], conflicts: [{ conflictId: 'conflict-1', type: 'metric_tension', objectiveIds: ['a', 'b'], severity: 'critical', explanation: 'opposing targets' }], dependencyOrder: [], blockedObjectiveIds: [], truncated: false }; assert.throws(() => assessEnterpriseRisks(request({ objectiveEvaluation: contradictory })), /contradictory/); });
test('bounds findings deterministically', () => { const result = assessEnterpriseRisks(request({ snapshot: { ...snapshot(), gaps: [{ code: 'unknown_system_owner', severity: 'warning', detail: 'missing owner' }, { code: 'missing_control', severity: 'critical', detail: 'missing control' }] }, maxFindings: 1 })); assert.equal(result.findings.length, 1); assert.equal(result.findings[0]?.severity, 'critical'); assert.equal(result.truncated, true); });
