import assert from 'node:assert/strict';
import test from 'node:test';
import { validateEnterpriseSimulationReplay } from '../lib/autonomous-systems/simulation-replay-validator.ts';
import type { EnterpriseExecutionSimulationSnapshot } from '../lib/autonomous-systems/execution-orchestrator-simulation.ts';

const tenant = { tenantId: 'tenant-a', environmentId: 'prod', region: 'us' };
const simulation: EnterpriseExecutionSimulationSnapshot = { schemaVersion: '1.0.0', simulationId: 'simulation-1', tenant, planId: 'plan-1', authorizationId: 'auth-1', status: 'simulated_complete', executable: false, transitions: [{ ordinal: 1, stepId: 'prepare', state: 'simulated_success', reason: 'simulation_only', evidenceRefs: ['z-ref', 'a-ref'] }, { ordinal: 2, stepId: 'publish', state: 'simulated_success', reason: 'simulation_only', evidenceRefs: ['a-ref', 'step-ref'] }], completedStepIds: ['prepare', 'publish'], rolledBackStepIds: [], blockedStepIds: [], evidenceRefs: ['plan-ref', 'a-ref'], truncated: false };
function validate(overrides: Partial<Parameters<typeof validateEnterpriseSimulationReplay>[0]> = {}) { return validateEnterpriseSimulationReplay({ tenant, simulation, maxTransitions: 16, ...overrides }); }
function codes(result: ReturnType<typeof validate>) { return result.errors.map(issue => issue.code); }

test('accepts a valid completed simulation with sorted unique evidence', () => { const result = validate(); assert.equal(result.valid, true); assert.equal(result.replayableForAudit, true); assert.deepEqual(result.evidenceRefs, ['a-ref', 'plan-ref', 'step-ref', 'z-ref']); });
test('produces deterministic deeply immutable output', () => { const first = validate(); const second = validate(); assert.equal(first.validationId, second.validationId); assert.ok(Object.isFrozen(first)); assert.ok(Object.isFrozen(first.errors)); assert.ok(Object.isFrozen(first.tenant)); });
test('rejects tenant and environment boundary violations', () => { const result = validate({ simulation: { ...simulation, tenant: { tenantId: 'other', environmentId: '' } } }); assert.ok(codes(result).includes('tenant_required')); assert.ok(codes(result).includes('simulation_tenant_boundary_violation')); });
test('rejects executable simulation input', () => { assert.ok(codes(validate({ simulation: { ...simulation, executable: true } as never })).includes('executable_simulation_rejected')); });
test('detects nonsequential ordinals and duplicate step IDs', () => { const result = validate({ simulation: { ...simulation, transitions: [{ ...simulation.transitions[0]!, ordinal: 2 }, { ...simulation.transitions[1]!, stepId: 'prepare' }] } }); assert.ok(codes(result).includes('invalid_transition_ordinal')); assert.ok(codes(result).includes('duplicate_transition_step_id')); });
test('detects mismatched completed rollback and blocked classifications', () => { const result = validate({ simulation: { ...simulation, completedStepIds: ['missing'], rolledBackStepIds: ['prepare'], blockedStepIds: ['publish'] } }); assert.ok(codes(result).includes('completed_step_state_mismatch')); assert.ok(codes(result).includes('rollback_step_state_mismatch')); assert.ok(codes(result).includes('blocked_step_state_mismatch')); });
test('detects conflicting terminal classifications', () => { assert.ok(codes(validate({ simulation: { ...simulation, rolledBackStepIds: ['prepare'] } })).includes('conflicting_terminal_classification')); });
test('detects inconsistent simulation status', () => { const result = validate({ simulation: { ...simulation, status: 'simulated_complete', transitions: [{ ...simulation.transitions[0]! }, { ...simulation.transitions[1]!, state: 'blocked' }] } }); assert.ok(codes(result).includes('simulation_status_inconsistent')); });
test('enforces expected plan and authorization IDs', () => { const result = validate({ expectedPlanId: 'other-plan', expectedAuthorizationId: 'other-auth' }); assert.ok(codes(result).includes('expected_plan_id_mismatch')); assert.ok(codes(result).includes('expected_authorization_id_mismatch')); });
test('bounds validation and reports truncation', () => { const result = validate({ maxTransitions: 1 }); assert.equal(result.verifiedTransitionCount, 1); assert.equal(result.truncated, true); assert.equal(result.replayableForAudit, false); assert.throws(() => validate({ maxTransitions: 0 }), /unbounded_replay_validation_rejected/); assert.throws(() => validate({ maxTransitions: 513 }), /unbounded_replay_validation_rejected/); });
test('always returns non-executable output', () => { assert.equal(validate().executable, false); });
