import test from 'node:test'
import assert from 'node:assert/strict'
import { InMemoryCoordinationStore, ownershipIdentity, ExecutionChannelSelector, StaticCapabilityRegistry, ProviderWorkerRegistry, ProviderWorkRouter, vercelProviderWorker, APIExecutor, ExecutorRegistry, InMemoryDispatchStore, SupervisorDispatcher } from '../lib/supervisor/index.ts'
import type { Capability, SupervisorInstance, WorkItem } from '../lib/supervisor/index.ts'

class FakeClock { t: Date; constructor(t=new Date('2026-07-16T00:00:00.000Z')){ this.t=t } now(){return this.t} add(ms:number){this.t=new Date(this.t.getTime()+ms)} }
const inst=(id:string,rt=id+'-rt'):SupervisorInstance=>({instanceId:id,runtimeId:rt,startedAt:'2026-07-16T00:00:00.000Z',heartbeatAt:'2026-07-16T00:00:00.000Z',softwareVersion:'test',schemaVersion:'supervisor-instance-v1',supportedProviderKinds:['vercel'],status:'healthy'})
const work=(id='w1',provider='vercel',state='queued' as const):WorkItem=>({workItemId:id,workItemType:'deployment_incident',incidentId:'inc1',provider,environment:'sandbox',state,priority:1,createdAt:'2026-07-16T00:00:00.000Z',availableAt:'2026-07-16T00:00:00.000Z',attempt:0,maxAttempts:3,policyVersion:'ha-policy-v1',schemaVersion:'work-item-v1'})
const cap=(o:Partial<Capability>={}):Capability=>({capabilityId:'vercel.deployment.read',provider:'vercel',operation:'deployment.read',channels:{api:true,browser:true,manual:true},riskClass:'read_only',maturity:'auto_failover_ready',reversible:true,idempotent:true,supportsAutoFailover:true,supportsBrowserOnDemand:true,requiresHumanApproval:false,approvedOrigins:['https://vercel.com'],verificationProfileId:'verify-read',browserAdapterId:'vercel-browser-v1',apiOperationId:'vercel.deployments.get',policyVersion:'ha-policy-v1',capabilityVersion:'cap-v1',approvedStepIds:['read-1'],schemaVersion:'capability-v1',...o})
function selector(c=cap()){return new ExecutionChannelSelector(new StaticCapabilityRegistry([c]))}

test('coordination leases fence active-active supervisors', async()=>{ const clock=new FakeClock(); const s=new InMemoryCoordinationStore(clock); await s.registerInstance(inst('a','ra')); await s.registerInstance(inst('b','rb')); await s.enqueueWorkItem(work()); const l1=await s.acquireLease({workItemId:'w1',ownerInstanceId:'a',ownerRuntimeId:'ra',leaseDurationMs:1000}); await assert.rejects(()=>s.acquireLease({workItemId:'w1',ownerInstanceId:'b',ownerRuntimeId:'rb',leaseDurationMs:1000}),/unexpired lease/); clock.add(1001); await s.reconcileExpiredLeases(); const l2=await s.acquireLease({workItemId:'w1',ownerInstanceId:'b',ownerRuntimeId:'rb',leaseDurationMs:1000}); assert.equal(l2.fencingToken,l1.fencingToken+1); await assert.rejects(()=>s.renewLease({...ownershipIdentity(l1),leaseDurationMs:1000}),/missing|stale/); await assert.rejects(()=>s.releaseLease(ownershipIdentity(l1)),/missing|stale/); await assert.rejects(()=>s.transitionWorkItem({workItemId:'w1',to:'completed',owner:ownershipIdentity(l1)}),/missing|stale/); await s.transitionWorkItem({workItemId:'w1',to:'processing',owner:ownershipIdentity(l2),executionId:'exec-new'}); assert.equal((await s.getWorkItem('w1'))!.executionId,'exec-new') })

test('process restart, draining, terminal work, and serialization fail closed', async()=>{ const clock=new FakeClock(); const s=new InMemoryCoordinationStore(clock); await s.registerInstance(inst('a','old')); await s.enqueueWorkItem(work('w2')); const l=await s.acquireLease({workItemId:'w2',ownerInstanceId:'a',ownerRuntimeId:'old',leaseDurationMs:1000}); await s.registerInstance(inst('a','new')); await assert.rejects(()=>s.renewLease({...ownershipIdentity(l),leaseDurationMs:1000}),/stale|missing|rejected/); await s.markInstanceDraining('a','new'); await assert.rejects(()=>s.acquireLease({workItemId:'w2',ownerInstanceId:'a',ownerRuntimeId:'new',leaseDurationMs:1000}),/healthy|unexpired/); await s.registerInstance(inst('b','rb')); clock.add(1001); await s.reconcileExpiredLeases(); const l2=await s.acquireLease({workItemId:'w2',ownerInstanceId:'b',ownerRuntimeId:'rb',leaseDurationMs:1000}); await s.transitionWorkItem({workItemId:'w2',to:'completed',owner:ownershipIdentity(l2)}); clock.add(1001); await s.reconcileExpiredLeases(); await assert.rejects(()=>s.acquireLease({workItemId:'w2',ownerInstanceId:'b',ownerRuntimeId:'rb',leaseDurationMs:1000}),/unavailable/); assert.doesNotThrow(()=>JSON.stringify(s)); await assert.rejects(()=>s.enqueueWorkItem({...work('bad'), tenantId:'token'}),/secret|unsafe/) })

test('provider workers are provider isolated',()=>{ const r=new ProviderWorkerRegistry(); r.register(vercelProviderWorker); const router=new ProviderWorkRouter(r); assert.equal(router.route(work()).providerKind,'vercel'); assert.throws(()=>router.route(work('x','stripe')),/unknown provider/); assert.throws(()=>router.route({...work('x'),workItemType:'billing'}),/unsupported/); r.register({providerKind:'future',supportedWorkItemTypes:['deployment_incident'],supportedCapabilities:[],adapterVersion:'x',health:'healthy',maximumConcurrentWork:1,executionDependencies:[]}); assert.equal(router.route(work('f','future')).providerKind,'future') })

test('HA policy deterministic API and browser decisions',()=>{ const base={workItemId:'w',executionMode:'smart_failover' as const,capabilityId:'vercel.deployment.read',environment:'sandbox' as const,apiAttempted:false,retryCount:0,maxRetries:2,ownerInstanceId:'a',ownerRuntimeId:'r',fencingToken:1,now:new Date('2026-07-16T00:00:00.000Z')}; assert.equal(selector().select(base).decisionCode,'use_api'); assert.equal(selector().select({...base,executionMode:'api_only',apiFailureCategory:'capability_missing'}).selectedChannel,'manual'); assert.equal(selector().select({...base,apiAttempted:true,apiFailureCategory:'timeout',retryCount:1}).decisionCode,'retry_api'); assert.equal(selector().select({...base,apiFailureCategory:'rate_limited'}).decisionCode,'retry_api'); for (const f of ['authentication_failed','permission_denied','invalid_request','unknown_failure'] as const) assert.equal(selector().select({...base,apiFailureCategory:f}).decisionCode,'block'); const reason={reason:'api_unavailable_after_bounded_retries' as const,retryCount:2,finalApiFailureCategory:'timeout' as const}; assert.equal(selector().select({...base,apiFailureCategory:'timeout',retryCount:2,browserReason:reason}).decisionCode,'use_browser_automatically'); assert.equal(selector(cap({riskClass:'low_risk_reversible'})).select({...base,apiFailureCategory:'capability_missing',browserReason:{reason:'api_capability_missing',finalApiFailureCategory:'capability_missing'}}).decisionCode,'use_browser_automatically') })

test('HA policy blocks or requires humans for unsafe browser conditions',()=>{ const base={workItemId:'w',executionMode:'smart_failover' as const,capabilityId:'vercel.deployment.read',environment:'sandbox' as const,apiAttempted:true,apiFailureCategory:'capability_missing' as const,browserReason:{reason:'api_capability_missing' as const,finalApiFailureCategory:'capability_missing' as const},retryCount:0,maxRetries:2,ownerInstanceId:'a',ownerRuntimeId:'r',fencingToken:1,now:new Date('2026-07-16T00:00:00.000Z')}; assert.throws(()=>selector().select({...base,browserReason:{reason:'bogus' as any}}),/browser reason/); assert.equal(selector(cap({maturity:'experimental'})).select(base).decisionCode,'require_human_approval'); assert.equal(selector(cap({maturity:'sandbox_verified'})).select(base).decisionCode,'require_human_approval'); assert.equal(selector(cap({riskClass:'medium'})).select(base).decisionCode,'require_human_approval'); assert.equal(selector(cap({riskClass:'high'})).select(base).decisionCode,'require_human_approval'); assert.equal(selector(cap({riskClass:'forbidden'})).select(base).decisionCode,'block'); assert.equal(selector(cap({maturity:'suspended',suspendedReason:'paused'})).select(base).decisionCode,'block'); assert.equal(selector(cap({verificationProfileId:undefined})).select(base).decisionCode,'block'); assert.equal(selector(cap({approvedOrigins:[]})).select(base).decisionCode,'block'); assert.equal(selector().select({...base,flags:{captcha:true}}).decisionCode,'require_human_approval'); assert.equal(selector().select({...base,flags:{twoFactor:true}}).decisionCode,'require_human_approval'); assert.equal(selector().select({...base,flags:{credentialMutation:true}}).decisionCode,'require_human_approval'); assert.equal(selector().select({...base,flags:{billingAction:true}}).decisionCode,'require_human_approval'); assert.equal(selector().select({...base,flags:{ownershipOrPermissionChange:true}}).decisionCode,'require_human_approval'); assert.equal(selector().select({...base,environment:'production'}).decisionCode,'require_human_approval') })

test('browser on demand records human_requested and keeps approval guardrails',()=>{ const d=selector().select({workItemId:'w',executionMode:'browser_on_demand',capabilityId:'vercel.deployment.read',environment:'sandbox',apiAttempted:false,retryCount:0,maxRetries:0,browserReason:{reason:'human_requested',requestingOperatorId:'op1'},ownerInstanceId:'a',ownerRuntimeId:'r',fencingToken:1,now:new Date('2026-07-16T00:00:00.000Z'),flags:{browserRuntimeApprovalRequired:true,continuationApprovalRequired:true}}); assert.equal(d.browserReason?.reason,'human_requested'); assert.equal(d.decisionCode,'use_browser_with_guardrails') })

test('dispatcher rejects expired and stale fenced dispatches', async()=>{ const clock=new FakeClock(); const store=new InMemoryCoordinationStore(clock); await store.registerInstance(inst('a','ra')); await store.enqueueWorkItem(work()); const lease=await store.acquireLease({workItemId:'w1',ownerInstanceId:'a',ownerRuntimeId:'ra',leaseDurationMs:1000}); const registry=new ExecutorRegistry(); let calls=0; registry.register('api',{kind:'api',execute:(i:any)=>{calls++; return new APIExecutor().execute(i)}}); const dispatcher=new SupervisorDispatcher({registry,audit:{write(){ }},dispatchStore:new InMemoryDispatchStore()}); const incident={incidentId:'inc1',provider:'vercel',environment:'sandbox',severity:'warning',detectedAt:'2026-07-16T00:00:00.000Z',source:'api',errorMessage:'x',evidence:[{evidenceId:'e',type:'log',capturedAt:'2026-07-16T00:00:00.000Z',summary:'x'}],metadata:{}} as any; const plan={planId:'p',incidentId:'inc1',diagnosis:'x',confidenceScore:1,requiresBrowser:false,riskLevel:'low',targetProvider:'vercel',targetEnvironment:'sandbox',steps:[{stepId:'read-1',action:'read',description:'x',protectedAction:false,parameters:{}}],verificationSteps:[{stepId:'verify-1',action:'verify',description:'verify',protectedAction:false,parameters:{}}],generatedAt:'2026-07-16T00:00:00.000Z',schemaVersion:'supervisor-plan-v1'} as any; const pol={outcome:'approved',reason:'x',evaluatedAt:'2026-07-16T00:00:00.000Z',policyVersion:'x',approvedStepIds:['read-1']} as any; const dec=selector().select({workItemId:'w1',executionMode:'smart_failover',capabilityId:'vercel.deployment.read',environment:'sandbox',apiAttempted:false,retryCount:0,maxRetries:1,ownerInstanceId:'a',ownerRuntimeId:'ra',fencingToken:lease.fencingToken,now:new Date(),decisionTtlMs:100000}); dec.auditMetadata.leaseId=lease.leaseId; const req={incident,plan,policyDecision:pol,approvedStepIds:['read-1'],executionContext:{executionId:'ex',metadata:{}},dispatchId:'d1',requestedExecutorKind:'api',executionDecision:dec,coordinationStore:undefined}; { const first = await dispatcher.dispatch(req); assert.equal(first.status,'not_implemented', first.error?.message); } req.coordinationStore=store; assert.equal((await dispatcher.dispatch({...req,dispatchId:'d2',executionDecision:{...dec,fencingToken:999}})).status,'failed'); clock.add(1001); assert.equal((await dispatcher.dispatch({...req,dispatchId:'d3'})).status,'failed'); assert.equal(calls,1) })
