import assert from 'node:assert/strict';
import test from 'node:test';
import { buildEnterpriseHumanReviewNestedAttestationRegistryCertificateV2 } from '../lib/autonomous-systems/human-review-attestation-certificate-registry-attestation-registry-certificate-registry-attestation-registry-certificate-registry-attestation-registry-certificate-registry-attestation-registry-certificate.ts';
import { validateEnterpriseHumanReviewNestedAttestationRegistryCertificateV2Integrity } from '../lib/autonomous-systems/human-review-attestation-certificate-registry-attestation-registry-certificate-registry-attestation-registry-certificate-registry-attestation-registry-certificate-registry-attestation-registry-certificate-integrity-validator.ts';

const tenant={tenantId:'tenant-a',environmentId:'env-a'};
const integrity={schemaVersion:'1.0.0' as const,validationId:'validation-1',tenant,registryId:'registry-1',disposition:'valid' as const,valid:true,errors:[],validatedAttestationIds:['attestation-b','attestation-a'],evidenceRefs:['z','a'],truncated:false,readOnly:true as const,executable:false as const};
const certificate=buildEnterpriseHumanReviewNestedAttestationRegistryCertificateV2({tenant,integrity,issuerId:'issuer-1',evidenceRefs:[]});

test('validates deterministic frozen certificate integrity',()=>{ const first=validateEnterpriseHumanReviewNestedAttestationRegistryCertificateV2Integrity({tenant,certificate,expectedIssuerId:'issuer-1',maxAttestationIds:10}); const second=validateEnterpriseHumanReviewNestedAttestationRegistryCertificateV2Integrity({tenant,certificate,expectedIssuerId:'issuer-1',maxAttestationIds:10}); assert.deepEqual(first,second); assert.equal(first.disposition,'valid'); assert.deepEqual(first.validatedAttestationIds,['attestation-a','attestation-b']); assert.deepEqual(first.evidenceRefs,['a','z']); assert.equal(Object.isFrozen(first),true); });

test('reports identity, serial, issuer, duplicate, and disposition errors',()=>{ const invalid={...certificate,certificateId:'',certificateSerial:'BAD',issuerId:'issuer-x',attestationIds:['a','a'],disposition:'empty' as const}; const result=validateEnterpriseHumanReviewNestedAttestationRegistryCertificateV2Integrity({tenant,certificate:invalid,expectedIssuerId:'issuer-1',maxAttestationIds:10}); assert.equal(result.disposition,'invalid'); assert.equal(result.valid,false); for(const error of ['certificate_id_digest_mismatch','duplicate_attestation_id','empty_certificate_contains_attestations','invalid_certificate_serial','issuer_id_mismatch','nested_attestation_registry_certificate_v2_identity_required']) assert.equal(result.errors.includes(error),true); });

test('rejects forged digest-bound certificate identities',()=>{ const forged={...certificate,certificateId:'tampered',certificateSerial:'EAE-HRARR2-TAMPERED'}; const result=validateEnterpriseHumanReviewNestedAttestationRegistryCertificateV2Integrity({tenant,certificate:forged,maxAttestationIds:10}); assert.equal(result.valid,false); assert.equal(result.errors.includes('certificate_id_digest_mismatch'),true); assert.equal(result.errors.includes('invalid_certificate_serial'),true); });

test('enforces tenant, safety, bounds, and truncation',()=>{ assert.throws(()=>validateEnterpriseHumanReviewNestedAttestationRegistryCertificateV2Integrity({tenant:{tenantId:'other',environmentId:'env-a'},certificate,maxAttestationIds:10}),/tenant_boundary_violation/); assert.throws(()=>validateEnterpriseHumanReviewNestedAttestationRegistryCertificateV2Integrity({tenant,certificate:{...certificate,executable:true as false},maxAttestationIds:10}),/unsafe/); assert.throws(()=>validateEnterpriseHumanReviewNestedAttestationRegistryCertificateV2Integrity({tenant,certificate,maxAttestationIds:0}),/unbounded/); const result=validateEnterpriseHumanReviewNestedAttestationRegistryCertificateV2Integrity({tenant,certificate,maxAttestationIds:1}); assert.equal(result.truncated,true); assert.deepEqual(result.validatedAttestationIds,['attestation-a']); });
