import test from 'node:test'
import assert from 'node:assert/strict'
import { canonicalize, fingerprintRepairPlan, fingerprintDecision } from '../lib/supervisor/missions/fingerprints.ts'
const plan = (steps = [{ stepId:'stop', action:'stop', description:'route', protectedAction:false, parameters:{ a: 1 } }]) => ({ planId:'p', incidentId:'m', diagnosis:'route', confidenceScore:100, requiresBrowser:false, riskLevel:'low', targetProvider:'none', targetEnvironment:'sandbox', steps, verificationSteps:[{stepId:'verify',action:'verify',description:'record',protectedAction:false,parameters:{}}], generatedAt:'2026-07-23T00:00:00.000Z', schemaVersion:'v1' } as any)
const fp = (p:any, revision=1) => fingerprintRepairPlan({missionId:'m',missionRevision:revision,decisionId:'d',environment:'sandbox',actionType:'route_to_manual_review',plan:p})
test('canonicalization sorts keys and stable plan vector is deterministic', () => { assert.equal(canonicalize({b:1,a:{z:2,y:3}}), canonicalize({a:{y:3,z:2},b:1})); assert.equal(fp(plan()), fp(plan())) })
test('step order, parameter, and mission revision are fingerprint-bound', () => { const a=plan([{stepId:'one',action:'stop',description:'one',protectedAction:false,parameters:{}},{stepId:'two',action:'stop',description:'two',protectedAction:false,parameters:{}}]); assert.notEqual(fp(a),fp(plan([...a.steps].reverse()))); assert.notEqual(fp(plan([{...a.steps[0],parameters:{x:1}}])),fp(plan([{...a.steps[0],parameters:{x:2}}]))); assert.notEqual(fp(plan()),fp(plan(),2)) })
test('duplicate step IDs, secrets, and non-serializable values are rejected', () => { assert.throws(() => fp(plan([{stepId:'x',action:'stop',description:'x',protectedAction:false,parameters:{}},{stepId:'x',action:'stop',description:'x',protectedAction:false,parameters:{}}]))); assert.throws(() => canonicalize({token:'secret'})); assert.throws(() => canonicalize({x:undefined})); assert.throws(() => canonicalize({x:NaN})) })
test('decision fingerprint is stable', () => { const p=plan(); const planFingerprint=fp(p); const d:any={decisionId:'d',missionId:'m',missionRevision:1,actionType:'route_to_manual_review',repairPlan:p,planFingerprint,riskLevel:'low',confidence:100,externalSideEffect:false,createdAt:'2026-07-23T00:00:00.000Z',expiresAt:'2026-07-23T00:15:00.000Z',schemaVersion:'v1',targetEnvironment:'sandbox'}; assert.equal(fingerprintDecision(d), fingerprintDecision({...d,repairPlan:{...p,steps:[...p.steps]}})) })
