import test from 'node:test'
import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { InMemoryMissionStore, InMemoryMissionManualReviewStore, fingerprintDecision, fingerprintPolicyBinding, fingerprintRepairPlan, type Mission } from '../lib/supervisor/missions/index.ts'
import { manualReviewDetailFields, manualReviewListFields, parseManualReviewListQuery } from '../lib/supervisor/missions/review-api.ts'

const now='2026-07-23T00:00:00.000Z', future='2026-07-23T00:15:00.000Z'
const mission=(id:string):Mission=>({missionId:id,missionType:'ci_failure_manual_review',revision:1,status:'NEW',environment:'sandbox',title:'CI failure requires manual review',objective:'Route only.',correlationId:`c-${id}`,sourceEventIds:[`e-${id}`],riskLevel:'low',createdAt:now,updatedAt:now,metadata:{internalNote:'not exposed'},schemaVersion:'mission-v1'})
function reviewInput(id:string, createdAt:string) { const plan:any={planId:`p-${id}`,incidentId:`m-${id}`,diagnosis:'route',confidenceScore:100,requiresBrowser:false,riskLevel:'low',targetProvider:'none',targetEnvironment:'sandbox',steps:[{stepId:'manual-route',action:'stop',description:'route',protectedAction:false,parameters:{}}],verificationSteps:[{stepId:'verify-route',action:'verify',description:'verify',protectedAction:false,parameters:{}}],generatedAt:now,schemaVersion:'v'}; const base:any={decisionId:`d-${id}`,missionId:`m-${id}`,missionRevision:1,actionType:'route_to_manual_review',repairPlan:plan,riskLevel:'low',confidence:100,externalSideEffect:false,createdAt:now,expiresAt:future,schemaVersion:'v',targetEnvironment:'sandbox'}; const planFingerprint=fingerprintRepairPlan({missionId:base.missionId,missionRevision:1,decisionId:base.decisionId,environment:'sandbox',actionType:'route_to_manual_review',plan}); const decision:any={...base,planFingerprint,decisionFingerprint:fingerprintDecision({...base,planFingerprint})}; const bindingBase:any={decisionId:decision.decisionId,missionId:decision.missionId,missionRevision:1,decisionFingerprint:decision.decisionFingerprint,planFingerprint,policyVersion:'v',policyOutcome:'approved',approvedStepIds:['manual-route'],evaluatedAt:now,expiresAt:future,schemaVersion:'v'}; return {reviewId:`r-${id}`,decision,binding:{...bindingBase,bindingFingerprint:fingerprintPolicyBinding(bindingBase)},title:'Manual review',summary:'Safe summary',routedAt:createdAt,schemaVersion:'mission-manual-review-v1'} }

test('authenticated list contract is bounded, cursor-paginated, and stable',async()=>{ const missions=new InMemoryMissionStore(); for(const id of ['a','b','c']) await missions.create(mission(`m-${id}`)); const store=new InMemoryMissionManualReviewStore(missions,()=>now); await store.route(reviewInput('a','2026-07-23T00:02:00.000Z')); await store.route(reviewInput('b','2026-07-23T00:01:00.000Z')); await store.route(reviewInput('c','2026-07-23T00:01:00.000Z')); const first=await store.list({limit:2}); const second=await store.list({limit:2,cursor:first.nextCursor}); assert.deepEqual(first.items.map(x=>x.reviewId),['r-a','r-c']); assert.deepEqual(second.items.map(x=>x.reviewId),['r-b']); assert.equal(first.nextCursor !== undefined,true) })
test('query validation rejects invalid status, mission ID, limits, and cursors',()=>{ for(const query of ['status=approved','missionId=bad%20id','limit=0','limit=101','limit=one','cursor=not-a-cursor']) assert.throws(()=>parseManualReviewListQuery(new URLSearchParams(query))) })
test('list allowlist excludes fingerprints and detail allowlist excludes arbitrary metadata and secrets',()=>{ const review:any={reviewId:'r',missionId:'m',missionRevision:1,decisionId:'d',status:'routed',title:'t',summary:'s',createdAt:now,routedAt:now,schemaVersion:'v',decisionFingerprint:'decision',planFingerprint:'plan',bindingFingerprint:'binding',metadata:{token:'secret'},authorization:'Bearer secret'}; const list=manualReviewListFields(review), detail=manualReviewDetailFields(review); assert.equal('decisionFingerprint' in list,false); assert.equal('planFingerprint' in list,false); assert.equal('bindingFingerprint' in list,false); assert.deepEqual(Object.keys(detail).sort(),['bindingFingerprint','createdAt','decisionFingerprint','decisionId','missionId','missionRevision','planFingerprint','reviewId','routedAt','schemaVersion','status','summary','title'].sort()); assert.equal('metadata' in detail,false); assert.equal('authorization' in detail,false) })
test('routes require admin authentication, keep inaccessible/missing details indistinguishable, and expose GET only',()=>{ const list=readFileSync(new URL('../app/api/internal/supervisor/missions/reviews/route.ts',import.meta.url),'utf8'); const detail=readFileSync(new URL('../app/api/internal/supervisor/missions/reviews/[reviewId]/route.ts',import.meta.url),'utf8'); for(const source of [list,detail]) { assert.match(source,/requireAdmin\(\)/); assert.doesNotMatch(source,/export async function (POST|PUT|PATCH|DELETE)/) }; assert.match(detail,/\{ error: 'Not found' \}, \{ status: 404 \}/); assert.match(list,/manualReviewListFields/); assert.match(detail,/manualReviewDetailFields/) })
