import test from 'node:test'
import assert from 'node:assert/strict'
import { InMemoryMissionStore, InMemoryMissionManualReviewStore, InMemoryMissionEventBus, NonMutatingMissionExecutor, fingerprintDecision, fingerprintPolicyBinding, fingerprintRepairPlan, missionTopics, type Mission } from '../lib/supervisor/missions/index.ts'
const now='2026-07-23T00:00:00.000Z', future='2026-07-23T00:15:00.000Z'
const mission=(status:Mission['status']='NEW',revision=1):Mission=>({missionId:'m',missionType:'ci_failure_manual_review',revision,status,environment:'sandbox',title:'CI failure requires manual review',objective:'Route only.',correlationId:'c',sourceEventIds:['e'],riskLevel:'low',createdAt:now,updatedAt:now,metadata:{},schemaVersion:'mission-v1'})
const input=(overrides:any={})=>{const plan:any={planId:'p',incidentId:'m',diagnosis:'route',confidenceScore:100,requiresBrowser:false,riskLevel:'low',targetProvider:'none',targetEnvironment:'sandbox',steps:[{stepId:'manual-route',action:'stop',description:'route',protectedAction:false,parameters:{}}],verificationSteps:[{stepId:'verify-route',action:'verify',description:'verify',protectedAction:false,parameters:{}}],generatedAt:now,schemaVersion:'v'};const base:any={decisionId:'d',missionId:'m',missionRevision:1,actionType:'route_to_manual_review',repairPlan:plan,riskLevel:'low',confidence:100,externalSideEffect:false,createdAt:now,expiresAt:future,schemaVersion:'v',targetEnvironment:'sandbox'};const planFingerprint=fingerprintRepairPlan({missionId:'m',missionRevision:1,decisionId:'d',environment:'sandbox',actionType:'route_to_manual_review',plan});const decision:any={...base,planFingerprint,decisionFingerprint:fingerprintDecision({...base,planFingerprint})};const bindingBase:any={decisionId:'d',missionId:'m',missionRevision:1,decisionFingerprint:decision.decisionFingerprint,planFingerprint,policyVersion:'v',policyOutcome:'approved',approvedStepIds:['manual-route'],evaluatedAt:now,expiresAt:future,schemaVersion:'v'};const binding:any={...bindingBase,bindingFingerprint:fingerprintPolicyBinding(bindingBase)};return {...{reviewId:'r',decision,binding,title:'CI failure requires manual review',summary:'Route only.',routedAt:now,schemaVersion:'mission-manual-review-v1'},...overrides}}
const setup=async(status:Mission['status']='NEW',revision=1)=>{const missions=new InMemoryMissionStore();await missions.create(mission(status,revision));return {missions,store:new InMemoryMissionManualReviewStore(missions,()=>now)}}
test('routes durably and duplicate/concurrent deliveries return the same review',async()=>{const {store}=await setup();const value=input();const [a,b,c]=await Promise.all([store.route(value),store.route({...value,reviewId:'r-2'}),store.route({...value,reviewId:'r-3'})]);assert.equal(a.reviewId,'r');assert.equal(b.reviewId,'r');assert.equal(c.reviewId,'r');assert.equal((await store.get('r'))?.status,'routed')})
test('rejects stale, canceled, and blocked missions',async()=>{for(const [status,revision] of [['NEW',2],['CANCELED',1],['BLOCKED',1]] as const){const {store}=await setup(status,revision);await assert.rejects(store.route(input()))}})
test('rejects expiration, fingerprints, and non-approved policy outcomes',async()=>{const cases=[(x:any)=>{x.decision.expiresAt=now},(x:any)=>{x.binding.expiresAt=now},(x:any)=>{x.decision.decisionFingerprint='wrong'},(x:any)=>{x.decision.planFingerprint='wrong'},(x:any)=>{x.binding.bindingFingerprint='wrong'},(x:any)=>{x.binding.policyOutcome='blocked'}];for(const change of cases){const {store}=await setup();const value=input();change(value);await assert.rejects(store.route(value))}})
test('duplicate approved event creates one review and one feedback only after insertion',async()=>{const {missions,store}=await setup();const bus=new InMemoryMissionEventBus();const feedback:any[]=[];await bus.subscribe<any>(missionTopics.executions,e=>{feedback.push(e.payload)});let n=0;await new NonMutatingMissionExecutor({eventBus:bus,missionStore:missions,manualReviewStore:store,clock:()=>now,id:(kind)=>`${kind}-${++n}`}).start();const value=input();const event:any={eventId:'approved',occurredAt:now,correlationId:'c',causationId:null,idempotencyKey:'approved',revision:1,schemaVersion:'v',payload:{decision:value.decision,binding:value.binding}};await bus.publish(missionTopics.approvedDecisions,event);await bus.publish(missionTopics.approvedDecisions,{...event,eventId:'approved-duplicate'});assert.equal(feedback.length,1);assert.ok(feedback[0].reviewId)})
test('database routing failure emits no execution feedback',async()=>{const {missions}=await setup();const bus=new InMemoryMissionEventBus();let feedback=0;await bus.subscribe<any>(missionTopics.executions,()=>{feedback++});const failing={route:async()=>{throw new Error('database_failed')},get:async()=>null,list:async()=>({items:[]}),diagnostics:async()=>({total:0,routed:0})};await new NonMutatingMissionExecutor({eventBus:bus,missionStore:missions,manualReviewStore:failing,clock:()=>now,id:(kind)=>kind}).start();const value=input();await bus.publish(missionTopics.approvedDecisions,{eventId:'approved',occurredAt:now,correlationId:'c',causationId:null,idempotencyKey:'approved',revision:1,schemaVersion:'v',payload:{decision:value.decision,binding:value.binding}});assert.equal(feedback,0)})
