// saas/tests/publicProvenanceRecast.node.test.ts
import test from 'node:test'
import assert from 'node:assert/strict'
import { acceptPublicNarrative, recastToFirstPerson } from '../lib/ai/cos/publicProvenanceNarrative.ts'

const NO_FACTS = { fromCache: false, cachedAt: null, liveSources: [] } as never

test('an adverb between the verb and the agent no longer evades the recast', () => {
  // Production 2026-08-26: "The previous answer was generated directly by COS using general
  // industry knowledge…". The first recast pattern required the agent immediately after the verb,
  // so "directly" slipped past it; the fallback pattern then produced "I generated it directly by
  // COS …" — first person that still names COS as a third party — and the acceptance check let it
  // through because it also required the agent to be adjacent.
  const out = recastToFirstPerson('The previous answer was generated directly by COS using general industry knowledge.')
  assert.match(out, /^I generated it using general industry knowledge/)
  assert.ok(!/by COS/i.test(out))
})

test('every self-attribution shape recasts without naming the system', () => {
  for (const input of [
    'The previous answer was generated by COS using general knowledge.',
    'The previous answer was generated directly by COS using general knowledge.',
    'That response was produced automatically by the system from my training data.',
    'This reply was written by the assistant from what I already knew.',
  ]) {
    const out = acceptPublicNarrative(input, NO_FACTS)
    assert.ok(out, input)
    assert.match(out as string, /^I /, input)
    assert.ok(!/\b(cos|the assistant|the system|the concierge)\b/i.test(out as string), out as string)
  }
})

test('report-style openers become first person, preserving the model content after them', () => {
  const out = acceptPublicNarrative(
    'The previous answer was generated fresh for this conversation using general language knowledge and creative writing principles.',
    NO_FACTS,
  )
  assert.ok(out)
  assert.match(out as string, /^I generated it fresh for this conversation/)
  assert.match(out as string, /creative writing principles/)
})

test('leftover third-person narration anywhere is still rejected', () => {
  // The recast only touches the opener; a report about "the previous answer" mid-text must fail.
  assert.equal(
    acceptPublicNarrative('I used my training for this. The previous answer was a separate matter entirely and stands apart.', NO_FACTS),
    null,
  )
})

test('a naturally first-person narrative passes untouched', () => {
  const natural = 'I wrote that from my own training rather than looking anything up, and I did not consult any private data while doing it.'
  assert.equal(acceptPublicNarrative(natural, NO_FACTS), natural)
})

test('the recast never invents an agent when none was present', () => {
  const out = recastToFirstPerson('The answer was composed while I worked through your figures step by step.')
  assert.match(out, /^I composed it while I worked through your figures/)
  assert.ok(!/\bby\b/.test(out.slice(0, 20)), 'no agent may be introduced')
})

test('empty and junk input is safe', () => {
  assert.equal(acceptPublicNarrative('', NO_FACTS), null)
  assert.equal(acceptPublicNarrative(null, NO_FACTS), null)
  assert.equal(recastToFirstPerson(''), '')
})
