// saas/tests/publicProvenanceNarrative.node.test.ts
import assert from 'node:assert/strict'
import test from 'node:test'
import {
  acceptPublicNarrative,
  buildPublicProvenanceInstruction,
  emergencyPublicProvenance,
  extractPublicProvenanceFacts,
  publicDisclosureViolation,
} from '../lib/ai/cos/publicProvenanceNarrative.ts'

const CACHE_RECORD = { provenance: { answer_origin: { from_cache: true, stored_at: '2026-08-20T11:00:00Z' } } }
const SOURCE_RECORD = {
  provenance: {
    answer_origin: { from_cache: false },
    live_external_evidence: { used: true, sources: [
      { id: 'LIVE1', title: 'Official guidance', url: 'https://example.gov/guide' },
      { id: 'LIVE2', title: 'Bad row', url: 'not-a-url' },
    ] },
  },
}

test('cache record extracts from_cache with its date', () => {
  const facts = extractPublicProvenanceFacts({ record: CACHE_RECORD, originalRequest: 'write a script' })
  assert.equal(facts.fromCache, true)
  assert.ok(facts.cachedAt?.includes('2026-08-20'))
})

test('live sources extract valid urls only, deduplicated', () => {
  const facts = extractPublicProvenanceFacts({ record: SOURCE_RECORD })
  assert.equal(facts.liveSources.length, 1)
  assert.equal(facts.liveSources[0].url, 'https://example.gov/guide')
})

test('the owner-requested voice is ALLOWED: training, memory, general knowledge, AI self-description', () => {
  const facts = extractPublicProvenanceFacts({ record: null, originalRequest: 'write a script' })
  for (const voice of [
    'That one came straight from my own training — I wrote the script fresh for you based on what you asked for.',
    'Honestly? From my memory and general knowledge. I composed it on the spot for your request, nothing was looked up.',
    'As an AI assistant I drew on my training to draft that script just for this conversation.',
  ]) {
    assert.equal(acceptPublicNarrative(voice, facts), voice)
  }
})

test('named models, vendors, infrastructure and internals are still rejected', () => {
  assert.equal(publicDisclosureViolation('It was generated by Qwen.'), 'model_name')
  assert.equal(publicDisclosureViolation('Our RunPod server produced it.'), 'infrastructure')
  assert.equal(publicDisclosureViolation('It came out of the semantic cache.'), 'internal_component')
  assert.equal(publicDisclosureViolation('Row in cos_knowledge_records.'), 'internal_table')
  assert.equal(publicDisclosureViolation('My confidence score: 0.85 on that one.'), 'confidence_metric')
  assert.equal(publicDisclosureViolation('I drew on my training and my memory to write it for you.'), null)
})

test('invented source urls are rejected; verified ones pass', () => {
  const anonymous = extractPublicProvenanceFacts({ record: null, originalRequest: 'x' })
  assert.equal(acceptPublicNarrative('I based it on https://invented.example.com/page which explains everything about this.', anonymous), null)
  const sourced = extractPublicProvenanceFacts({ record: SOURCE_RECORD })
  const ok = 'I checked the public page at https://example.gov/guide and built the answer around what it says for you.'
  assert.equal(acceptPublicNarrative(ok, sourced), ok)
})

test('third-person self-narration is rejected so the first-person retry fires', () => {
  const facts = extractPublicProvenanceFacts({ record: null, originalRequest: 'x' })
  assert.equal(acceptPublicNarrative('The previous answer was generated by COS based on general knowledge about AI system design principles.', facts), null)
  assert.equal(acceptPublicNarrative('That response was produced by the assistant using its general knowledge of the topic at hand.', facts), null)
  const firstPerson = 'I put that one together myself from my training — general knowledge about AI system design, shaped to our conversation.'
  assert.equal(acceptPublicNarrative(firstPerson, facts), firstPerson)
})

test('too-short and too-long output is rejected (forces a real sentence, blocks runaway)', () => {
  const facts = extractPublicProvenanceFacts({ record: null })
  assert.equal(acceptPublicNarrative('ok', facts), null)
  assert.equal(acceptPublicNarrative('a'.repeat(1300), facts), null)
})

test('instruction demands own voice + variety, forbids names and verbatim quoting, carries facts', () => {
  const facts = extractPublicProvenanceFacts({ record: null, originalRequest: 'write a compliance script', priorAnswer: 'TITLE: THE COMPLIANCE CHECK' })
  const instruction = buildPublicProvenanceInstruction(facts, 'where did you get the answer from?', 'en')
  assert.ok(/FIRST PERSON/.test(instruction.system))
  assert.ok(/never narrate yourself in the third person/i.test(instruction.system))
  assert.ok(/vary your wording/i.test(instruction.system))
  assert.ok(/never name any specific ai model/i.test(instruction.system))
  assert.ok(/name the TOPIC/i.test(instruction.system))
  assert.ok(/never refer to it generically/i.test(instruction.system))
  assert.ok(/drawing on your own training, memory and general knowledge/i.test(instruction.prompt))
  const cached = buildPublicProvenanceInstruction(extractPublicProvenanceFacts({ record: CACHE_RECORD }), 'source?', 'pt')
  assert.ok(/reusing a reply/i.test(cached.prompt))
  assert.ok(/Portuguese/.test(cached.system))
})

test('emergency line exists in all five languages and speaks in the owner-requested voice', () => {
  for (const language of ['en', 'es', 'pt', 'pl', 'ru']) {
    const line = emergencyPublicProvenance(language)
    assert.ok(line.length > 20, language)
  }
  assert.ok(/training and general knowledge/i.test(emergencyPublicProvenance('en')))
})
