// saas/tests/staleGatewayXsaInfrastructure.node.test.ts
import assert from 'node:assert/strict'
import test from 'node:test'
import { MASS_EVALUATION_ROLLING_AUTHORIZATION_REF, decideExhaustedMassEvaluationArtifacts, decideRollingMassEvaluationApproval, staleGatewayModelMismatch } from '../lib/ai/cos/cosUniversityMassEvaluationRollingAuthority.ts'
import { MASS_CANARY_PROFILE, decideMassCanaryRollingApproval, type CanaryArtifact, type CanaryEvent } from '../lib/ai/cos/cosUniversityMassCanaryRollingAuthority.ts'

const XSA_409 = 'mass_distilled_evaluation_runpod_http_409:baseline:cases=3:{"detail":"xsa_exact_model_mismatch"}'
const STANDARD_409 = 'mass_distilled_evaluation_runpod_http_409:baseline:cases=2:{"detail":"distilled_exact_model_mismatch"}'
const EXAM_PROFILE = 'cos_mass_distilled_independent_evaluation_runtime_v1'
const hash = 'a'.repeat(64)
const artifact = { candidateId:'mass:xsa-student', subjectId:'Law, Regulation & Governance', artifactHash:hash, revisionKey:'b'.repeat(64), createdAt:'2026-09-27T00:00:00.000Z' } as any
const evaluationEvent=(claim:string,observedAt:string,evidence:Record<string,unknown>={},verifier='host_controller')=>({candidateId:artifact.candidateId,observedAt,expiresAt:null,verifier,evidence:{profile:EXAM_PROFILE,claim,artifactHash:hash,...evidence}}) as any
const approval=(observedAt:string)=>evaluationEvent('distilled_independent_evaluation_approved',observedAt,{profile:'cos_distilled_independent_evaluation_authorization_v1',authorizationRef:MASS_EVALUATION_ROLLING_AUTHORIZATION_REF})
const healthyCanary=(observedAt:string,endpointId:string)=>evaluationEvent('production_canary_healthy',observedAt,{profile:'cos_university_fine_tune_evidence_v1',exactArtifact:true,internalVllmReady:true,productionTrafficAuthorized:false,authorityExpanded:false,endpointId,attentionArchitecture:'exclusive_self_attention_v1'},'host_production_verifier')

test('both gateway forms of baseline 409 are infrastructure',()=>{ assert.equal(staleGatewayModelMismatch(XSA_409),true); assert.equal(staleGatewayModelMismatch(STANDARD_409),true); assert.equal(staleGatewayModelMismatch(XSA_409.toUpperCase()),true); assert.equal(staleGatewayModelMismatch('mass_distilled_evaluation_runpod_http_409:candidate:cases=3:{"detail":"xsa_exact_model_mismatch"}'),false) })
test('three XSA baseline 409s never fail a student out',()=>{ const events=[approval('2026-09-28T10:00:00.000Z'),...[1,2,3].map(n=>evaluationEvent('mass_distilled_independent_evaluation_failed',`2026-09-28T1${n}:00:00.000Z`,{error:XSA_409}))]; assert.equal(decideExhaustedMassEvaluationArtifacts({artifacts:[artifact],events,now:new Date('2026-09-28T20:00:00.000Z')}).length,0) })
test('three real exam failures still fail a student out',()=>{ const events=[approval('2026-09-28T10:00:00.000Z'),...[1,2,3].map(n=>evaluationEvent('mass_distilled_independent_evaluation_failed',`2026-09-28T1${n}:00:00.000Z`,{error:'mass_distilled_evaluation_holdout_not_improved'}))]; assert.equal(decideExhaustedMassEvaluationArtifacts({artifacts:[artifact],events,now:new Date('2026-09-28T20:00:00.000Z')}).length,1) })
test('stale gateway blocks exam approval until a newer canary exists',()=>{ const now=new Date('2026-09-28T20:00:00.000Z'); const stale=[healthyCanary('2026-09-27T20:00:00.000Z','old-endpoint'),approval('2026-09-28T10:00:00.000Z'),evaluationEvent('mass_distilled_independent_evaluation_failed','2026-09-28T10:05:00.000Z',{error:XSA_409})]; const blocked:any=decideRollingMassEvaluationApproval({enabled:true,artifacts:[artifact],events:stale,now}); assert.equal(blocked.issue,false); assert.equal(blocked.skipped?.stale_gateway_awaiting_fresh_canary,1); const refreshed:any=decideRollingMassEvaluationApproval({enabled:true,artifacts:[artifact],events:[...stale,healthyCanary('2026-09-28T11:00:00.000Z','fresh-endpoint')],now}); assert.equal(refreshed.skipped?.stale_gateway_awaiting_fresh_canary,undefined) })

// Standard attention: while XSA exams are paused (cosUniversityXsaExamPause.ts) an XSA student gets no canary at all. The
// stale-gateway re-canary rule itself does not depend on the architecture (STANDARD_409 is the same gateway defect).
const canaryArtifact:CanaryArtifact={candidateId:'mass:xsa-student',subjectId:'Law, Regulation & Governance',artifactHash:hash,createdAt:'2026-09-27T00:00:00.000Z',attentionArchitecture:'standard_attention'} as CanaryArtifact
const other:CanaryArtifact={candidateId:'mass:other',subjectId:'History',artifactHash:'c'.repeat(64),createdAt:'2026-09-27T01:00:00.000Z'}
const canaryEvent=(a:CanaryArtifact,claim:string,observedAt:string,evidence:Record<string,unknown>={}):CanaryEvent=>({candidateId:a.candidateId,observedAt,expiresAt:null,verifier:'host_controller',evidence:{profile:MASS_CANARY_PROFILE,claim,artifactHash:a.artifactHash,...evidence}})
test('one stale-gateway 409 re-canaries the same student onto a fresh endpoint',()=>{ const events=[canaryEvent(canaryArtifact,'local_distilled_runtime_canary_passed','2026-09-28T09:00:00.000Z'),canaryEvent(canaryArtifact,'mass_distilled_independent_evaluation_failed','2026-09-28T10:05:00.000Z',{profile:EXAM_PROFILE,error:XSA_409})]; const d:any=decideMassCanaryRollingApproval({artifacts:[canaryArtifact,other],events,now:new Date('2026-09-28T20:00:00.000Z'),enabled:true}); assert.equal(d.artifact?.candidateId,'mass:xsa-student'); assert.equal(d.evidence?.endpointRefresh,true) })
