import test from 'node:test'
import assert from 'node:assert/strict'
import { InMemoryApprovalQueueStore, approvalRequestSchemaVersion, issueContinuationApproval, parseApproveDecision } from '../lib/supervisor/approvals/index.ts'
import { digestBrowserApprovalToken, verifyBrowserApprovalToken } from '../lib/browser-runtime/approval.ts'
import type { BrowserTask } from '../lib/browser-runtime/contracts.ts'
const now='2026-07-16T00:00:00.000Z'
function req(over:any={}){return {approvalRequestId:over.approvalRequestId||'req-1',executionId:over.executionId||'exec-1',dispatchId:'dispatch-1',incidentId:'incident-1',planId:'plan-1',packageId:'pkg-1',packageFingerprint:'f'.repeat(64),provider:'sandbox',environment:'sandbox',targetOrigin:'http://localhost:4173',checkpointId:'approval-checkpoint',remainingStepIds:['save','verify'],protectedStepSummaries:[{stepId:'save',summary:'step save'}],evidenceReferences:[],phaseOneApprovalDigest:'a'.repeat(64),requestedAt:now,expiresAt:'2026-07-16T00:10:00.000Z',status:'pending',schemaVersion:approvalRequestSchemaVersion,...over} as const}
function task():BrowserTask{return {taskId:'task-1',incidentId:'incident-1',provider:'sandbox',adapterId:'signalboost.sandbox.v1',mode:'prepare_change',issuedAt:now,expiresAt:'2026-07-16T00:10:00.000Z',allowedOrigins:['http://localhost:4173'],approvalToken:'phase-one',steps:[{id:'approval-checkpoint',kind:'checkpoint',label:'checkpoint',requiresApproval:true},{id:'save',kind:'click',selector:'#save'},{id:'verify',kind:'screenshot',label:'verify'}]}}
test('approval queue enforces sandbox and one active request per execution', async()=>{const s=new InMemoryApprovalQueueStore(); await s.createRequest(req()); await assert.rejects(()=>s.createRequest(req({approvalRequestId:'req-2'})),/active_request_exists/); await assert.rejects(()=>s.createRequest(req({approvalRequestId:'req-3',executionId:'exec-2',environment:'production'} as any)),/environment_invalid|non_sandbox/)})
test('client cannot override continuation claims',()=>{assert.throws(()=>parseApproveDecision({remainingStepIds:['x']}),/client_override/); assert.throws(()=>parseApproveDecision({targetOrigin:'https://evil.test'}),/client_override/); assert.throws(()=>parseApproveDecision({approvalToken:'x'}),/client_override/)})
test('server-generated continuation binds exact execution scope origin and phase-one digest',()=>{const t=task(); const issued=issueContinuationApproval({task:t,executionId:'b'.repeat(64),checkpointId:'approval-checkpoint',remainingStepIds:['save','verify'],phaseOneApprovalDigest:digestBrowserApprovalToken(t.approvalToken),signingSecret:'secret',now:new Date(now)}); assert.equal(JSON.stringify(issued).includes(issued.token),true); const claims=verifyBrowserApprovalToken(issued.token, issued.task, 'secret', new Date(now), {expectedPhase:2,expectedStepIds:['save','verify'],expectedCheckpointStepId:'approval-checkpoint',expectedExecutionId:'b'.repeat(64),expectedPreApprovalTokenDigest:digestBrowserApprovalToken(t.approvalToken)}); assert.equal(claims.executionId,'b'.repeat(64)); assert.deepEqual(claims.allowedOrigins,['http://localhost:4173'])})
test('approval one-time consumption and terminal rejection are fail closed', async()=>{const s=new InMemoryApprovalQueueStore(); await s.createRequest(req()); await s.approveRequest('exec-1','op',now); await s.markConsumed('exec-1',now); await assert.rejects(()=>s.markConsumed('exec-1',now),/request_not_actionable|terminal/); await s.createRequest(req({approvalRequestId:'req-2',executionId:'exec-2'})); await s.rejectRequest('exec-2','op','operator_rejected',undefined,now); await assert.rejects(()=>s.approveRequest('exec-2','op',now),/request_not_actionable|terminal/)})
