import test from 'node:test'
import assert from 'node:assert/strict'
import crypto from 'node:crypto'
import { readFileSync } from 'node:fs'
import { InMemoryCoordinationStore } from '../lib/supervisor/coordination/index.ts'
import { InMemoryVercelTriggerStore, acceptVercelTrigger, deterministicFingerprint, normalizeVercelWebhook, verifyVercelWebhookSignature } from '../lib/supervisor/providers/vercel/trigger-ingestion.ts'
import { hydrateLocalizedSource } from './helpers/hydrateLocalizedSource.ts'

const now=new Date('2026-07-17T00:00:00.000Z')
const conn={tenantId:'tenant_1',providerConnectionId:'conn_1',projectId:'prj_1',environment:'production',active:true}
async function store(){ const cs=new InMemoryCoordinationStore({now:()=>now}); return {ts:new InMemoryVercelTriggerStore(),cs} }
test('valid scheduled observation creates durable trigger and work item, duplicate reuses it', async()=>{ const s=await store(); const a=await acceptVercelTrigger({store:s.ts,coordinationStore:s.cs,connection:conn,triggerSource:'scheduled_observation',observationWindow:'w1',now}); assert.equal(a.outcome,'created'); assert.ok(await s.cs.getWorkItem(a.workItemId)); const b=await acceptVercelTrigger({store:s.ts,coordinationStore:s.cs,connection:conn,triggerSource:'scheduled_observation',observationWindow:'w1',now}); assert.equal(b.outcome,'reused'); assert.equal(b.workItemId,a.workItemId) })
test('one provider failure can defer without blocking other accepted triggers', async()=>{ const s=await store(); const bad={...s.cs, enqueueWorkItem:async()=>{throw new Error('db down')}}; const a=await acceptVercelTrigger({store:s.ts,coordinationStore:bad,connection:conn,triggerSource:'scheduled_observation',observationWindow:'w2',now}); assert.equal(a.outcome,'deferred'); const b=await acceptVercelTrigger({store:s.ts,coordinationStore:s.cs,connection:{...conn,projectId:'prj_2'},triggerSource:'scheduled_observation',observationWindow:'w2',now}); assert.equal(b.outcome,'created') })
test('valid Vercel webhook is normalized only against authorized connection',()=>{ const body={type:'deployment.error',payload:{projectId:'prj_1',deployment:{id:'dpl_1'},target:'production',message:'failed <script>secret</script>'},createdAt:now.toISOString()}; const n=normalizeVercelWebhook(body,[conn]); assert.equal(n.ok,true); assert.equal(n.event.deploymentId,'dpl_1'); assert.doesNotMatch(n.event.message,/<script>/); assert.equal(normalizeVercelWebhook({...body,payload:{...body.payload,projectId:'other'}},[conn]).code,'provider_identity_not_authorized') })
test('signature verifier rejects missing, invalid, and accepts canonical signed body',()=>{ const raw='{"type":"deployment.error"}'; const secret='whsec'; const ts=String(now.getTime()); const sig=crypto.createHmac('sha256',secret).update(`${ts}.${raw}`).digest('hex'); assert.equal(verifyVercelWebhookSignature(raw,new Headers(),secret,now.getTime()).code,'missing_signature'); assert.equal(verifyVercelWebhookSignature(raw,new Headers({'x-vercel-timestamp':ts,'x-vercel-signature':'00'}),secret,now.getTime()).code,'invalid_signature'); assert.equal(verifyVercelWebhookSignature(raw,new Headers({'x-vercel-timestamp':ts,'x-vercel-signature':sig}),secret,now.getTime()).ok,true) })
test('unsupported, malformed-sized and unsafe webhook persistence constraints are represented in routes and migration',()=>{ const route=hydrateLocalizedSource(readFileSync(new URL('../app/api/webhook/vercel/route.ts', import.meta.url),'utf8')); assert.match(route,/body_too_large/); assert.match(route,/malformed_body/); const mig=hydrateLocalizedSource(readFileSync(new URL('../supabase/migrations/20260717_vercel_observation_triggers.sql', import.meta.url),'utf8')); assert.doesNotMatch(mig,/raw_body|request_headers|signature text/i); assert.match(mig,/enable row level security/) })
test('webhook and observer same incident deduplicate atomically and active work is reused',async()=>{ const s=await store(); const a=await acceptVercelTrigger({store:s.ts,coordinationStore:s.cs,connection:conn,triggerSource:'vercel_webhook',eventType:'deployment.error',deploymentId:'dpl_1',incidentType:'deployment_failed',now}); const b=await acceptVercelTrigger({store:s.ts,coordinationStore:s.cs,connection:conn,triggerSource:'scheduled_observation',eventType:'deployment.error',deploymentId:'dpl_1',incidentType:'deployment_failed',now}); assert.equal(b.outcome,'reused'); assert.equal(a.workItemId,b.workItemId) })
test('materially changed incident has deterministic new fingerprint and work correlation',async()=>{ const s=await store(); const a=await acceptVercelTrigger({store:s.ts,coordinationStore:s.cs,connection:conn,triggerSource:'vercel_webhook',eventType:'deployment.error',deploymentId:'dpl_1',incidentType:'deployment_failed',now}); const b=await acceptVercelTrigger({store:s.ts,coordinationStore:s.cs,connection:conn,triggerSource:'vercel_webhook',eventType:'deployment.error',deploymentId:'dpl_2',incidentType:'deployment_failed',now}); assert.notEqual(a.record.fingerprint,b.record.fingerprint); assert.notEqual(a.workItemId,b.workItemId); assert.equal(deterministicFingerprint({b:2,a:1}),deterministicFingerprint({a:1,b:2})) })
test('route and operator UI expose read-only status and no mutation controls',()=>{ const cron=hydrateLocalizedSource(readFileSync(new URL('../app/api/cron/vercel-observation/route.ts', import.meta.url),'utf8')); const page=hydrateLocalizedSource(readFileSync(new URL('../app/dashboard/supervisor/vercel-health/page.tsx', import.meta.url),'utf8')); assert.match(cron,/CRON_SECRET/); assert.doesNotMatch(page,/<button|Redeploy|Cancel deployment|Edit environment/i); for(const lang of ['en','es','pt','pl','ru']){ const j=JSON.parse(hydrateLocalizedSource(readFileSync(new URL(`../locales/${lang}.json`, import.meta.url),'utf8'))); assert.ok(j.vercelHealth.labels.triggerSource); assert.ok(j.vercelHealth.readOnlyNotice) } })
