import test from 'node:test'
import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { InMemoryVercelHealthStore, VercelDeploymentHealthIntelligence } from '../lib/supervisor/index.ts'

const now = new Date('2026-07-17T00:00:00.000Z')
function deps(deployments) { const store = new InMemoryVercelHealthStore(); const calls = { deployment:0, events:0, env:0, alias:0 }; const client = { listRecentDeployments: async () => ({ deployments }), getProjectMetadata: async () => ({ id:'prj_1' }), getDeployment: async ({ deploymentId }) => { calls.deployment++; return { id: deploymentId, state:'ERROR', target:'production', createdAt: now.getTime() } }, getDeploymentEvents: async () => { calls.events++; return { events: [{ message:'failed without secrets' }] } }, listProjectEnvNames: async () => { calls.env++; return { names: ['NEXT_PUBLIC_SITE_URL','SUPABASE_URL'] } }, listProductionAliases: async () => { calls.alias++; return { aliases: ['saas.signalboostapp.com'] } } }; return { workflow: new VercelDeploymentHealthIntelligence({ config: { providerConnectionId:'conn', projectId:'prj_1', environment:'production', lookbackWindowMs:86400000, maxDeployments:10, repeatedFailureThreshold:2, stuckDeploymentThresholdMs:3600000, maxAttempts:1, clock:{ now: () => now }, sleeper:{ sleep: async () => {} } }, secretResolver: async () => 'token_secret', client, store }), store, calls } }

test('health workflow performs end-to-end read-only diagnosis and persists evidence', async () => { const s = deps([{ id:'dpl_1', state:'ERROR', target:'production', createdAt: now.getTime(), error:{ message:'build failed' } }]); const run = await s.workflow.run(); assert.equal(run.status, 'incident_detected'); assert.equal(run.verification.status, 'verified'); assert.equal(s.calls.deployment, 1); assert.equal(s.calls.events, 1); assert.equal(s.calls.env, 1); assert.equal(run.evidence.some(e => e.kind === 'project_env_names' && e.metadata.valuesRead === false), true); assert.equal((await s.store.listRuns()).length, 1) })

test('healthy observation is persisted with verified no-incident evidence', async () => { const s = deps([{ id:'dpl_ready', state:'READY', target:'production', createdAt: now.getTime() }]); const run = await s.workflow.run(); assert.equal(run.status, 'healthy'); assert.equal(run.incident, undefined); assert.equal(run.verification.status, 'verified'); assert.equal((await s.store.listRuns())[0].runId, run.runId) })

test('workflow stores no token or mutation capability', async () => { const source = readFileSync(new URL('../lib/supervisor/providers/vercel/health-intelligence.ts', import.meta.url), 'utf8'); assert.doesNotMatch(source, /redeploy|createDeployment|cancelDeployment|updateProject|delete|rotate|BrowserRuntime|Playwright|Chromium/); const s = deps([{ id:'dpl_1', state:'ERROR', target:'production', createdAt: now.getTime(), error:{ message:'Authorization: Bearer secret' } }]); const run = await s.workflow.run(); assert.doesNotMatch(JSON.stringify(run), /token_secret|Bearer secret/) })
