import { isPlainSerializable, type SerializableValue } from '../incident-schema.ts'
import { type Lease, type SupervisorInstance, type WorkItem, supervisorStatuses, workItemStates, OwnershipError } from './index.ts'

const secretKey = /(secret|token|cookie|password|authorization|api[_-]?key|credential)/i
export function assertSanitizedSerializable(value: unknown): asserts value is SerializableValue {
  if (!isPlainSerializable(value)) throw new OwnershipError('invalid_record', 'coordination payload must be serializable')
  if (secretKey.test(JSON.stringify(value))) throw new OwnershipError('unsafe_record', 'coordination payload contains secret-like material')
}
export function instanceToRow(i: SupervisorInstance) { assertSanitizedSerializable(i as unknown); return { instance_id:i.instanceId, runtime_id:i.runtimeId, region:i.region ?? null, availability_zone:i.availabilityZone ?? null, software_version:i.softwareVersion, supported_provider_kinds:i.supportedProviderKinds, status:i.status, started_at:i.startedAt, heartbeat_at:i.heartbeatAt, schema_version:i.schemaVersion } }
export function instanceFromRow(r: any): SupervisorInstance { const status = r.status; if (!supervisorStatuses.includes(status)) throw new OwnershipError('invalid_record','invalid supervisor instance status'); return { instanceId:r.instance_id, runtimeId:r.runtime_id, region:r.region ?? undefined, availabilityZone:r.availability_zone ?? undefined, softwareVersion:r.software_version, supportedProviderKinds:r.supported_provider_kinds ?? [], status, startedAt:r.started_at, heartbeatAt:r.heartbeat_at, schemaVersion:r.schema_version } }
export function workToRow(w: WorkItem & { idempotencyKey?: string; sanitizedMetadata?: Record<string, SerializableValue> }) { assertSanitizedSerializable(w as unknown); return { work_item_id:w.workItemId, idempotency_key:w.idempotencyKey ?? null, work_item_type:w.workItemType, incident_id:w.incidentId, dispatch_id:w.dispatchId ?? null, execution_id:w.executionId ?? null, provider:w.provider, tenant_id:w.tenantId ?? null, organization_id:w.organizationId ?? null, project_scope:w.projectId ?? null, resource_scope:w.resourceId ?? null, environment:w.environment, state:w.state, priority:w.priority, available_at:w.availableAt, attempt:w.attempt, max_attempts:w.maxAttempts, policy_version:w.policyVersion, capability_version:w.capabilityVersion ?? null, adapter_version:w.adapterVersion ?? null, fencing_generation:w.currentLease?.fencingToken ?? 0, schema_version:w.schemaVersion, sanitized_metadata:w.sanitizedMetadata ?? {} } }
export function workFromRow(r: any, lease?: Lease): WorkItem { const state = r.state; if (!workItemStates.includes(state)) throw new OwnershipError('invalid_record','invalid work item state'); return { workItemId:r.work_item_id, workItemType:r.work_item_type, incidentId:r.incident_id, dispatchId:r.dispatch_id ?? undefined, executionId:r.execution_id ?? undefined, provider:r.provider, tenantId:r.tenant_id ?? undefined, organizationId:r.organization_id ?? undefined, projectId:r.project_scope ?? undefined, resourceId:r.resource_scope ?? undefined, environment:r.environment, state, priority:r.priority, createdAt:r.created_at, availableAt:r.available_at, attempt:r.attempt, maxAttempts:r.max_attempts, policyVersion:r.policy_version, capabilityVersion:r.capability_version ?? undefined, adapterVersion:r.adapter_version ?? undefined, currentLease:lease, schemaVersion:r.schema_version } }
export function leaseFromRow(r: any): Lease { return { leaseId:r.lease_id, workItemId:r.work_item_id, ownerInstanceId:r.owner_instance_id, ownerRuntimeId:r.owner_runtime_id, fencingToken:r.fencing_token, acquiredAt:r.acquired_at, heartbeatAt:r.heartbeat_at, expiresAt:r.expires_at, policyVersion:r.policy_version, schemaVersion:r.schema_version } }
