import { isPlainSerializable, type SerializableValue } from '../incident-schema.ts'
export const supervisorStatuses = ['starting','healthy','draining','unavailable','stopped'] as const
export type SupervisorStatus = typeof supervisorStatuses[number]
export const workItemStates = ['queued','leased','processing','paused_for_approval','verification_pending','completed','failed','blocked','expired','abandoned'] as const
export type WorkItemState = typeof workItemStates[number]
export const terminalWorkItemStates = new Set<WorkItemState>(['completed','failed','blocked','expired','abandoned'])
export interface CoordinationClock { now(): Date }
export const systemClock: CoordinationClock = { now: () => new Date() }
export interface SupervisorInstance { instanceId:string; runtimeId:string; region?:string; availabilityZone?:string; startedAt:string; heartbeatAt:string; softwareVersion:string; schemaVersion:string; supportedProviderKinds:string[]; status:SupervisorStatus }
export interface WorkItem { workItemId:string; workItemType:string; incidentId:string; dispatchId?:string; executionId?:string; provider:string; tenantId?:string; organizationId?:string; projectId?:string; resourceId?:string; environment:'sandbox'|'preview'|'production'; state:WorkItemState; priority:number; createdAt:string; availableAt:string; attempt:number; maxAttempts:number; policyVersion:string; capabilityVersion?:string; adapterVersion?:string; currentLease?:Lease; schemaVersion:string }
export interface Lease { leaseId:string; workItemId:string; ownerInstanceId:string; ownerRuntimeId:string; fencingToken:number; acquiredAt:string; heartbeatAt:string; expiresAt:string; policyVersion:string; schemaVersion:string }
export interface OwnershipIdentity { leaseId:string; ownerInstanceId:string; ownerRuntimeId:string; fencingToken:number }
export class OwnershipError extends Error { readonly code:string
 constructor(code:string, message:string){ super(message); this.code=code; this.name='OwnershipError' } }
export type CoordinationAuditEvent = { eventType:string; occurredAt:string; payload:Record<string, SerializableValue> }
export interface CoordinationAuditSink { write(event:Readonly<CoordinationAuditEvent>): void|Promise<void> }
export interface CoordinationStore { registerInstance(i:SupervisorInstance):Promise<SupervisorInstance>; heartbeatInstance(instanceId:string,runtimeId:string,at?:Date):Promise<SupervisorInstance>; markInstanceDraining(instanceId:string,runtimeId:string):Promise<SupervisorInstance>; enqueueWorkItem(w:WorkItem):Promise<WorkItem>; listAvailableWork(input:{provider:string; limit:number; now?:Date; tenantId?:string}):Promise<WorkItem[]>; acquireLease(input:{workItemId:string; ownerInstanceId:string; ownerRuntimeId:string; leaseDurationMs:number; now?:Date}):Promise<Lease>; renewLease(input:OwnershipIdentity&{leaseDurationMs:number; now?:Date}):Promise<Lease>; releaseLease(input:OwnershipIdentity&{now?:Date}):Promise<void>; getCurrentLease(workItemId:string):Promise<Lease|undefined>; assertFence(workItemId:string, identity:OwnershipIdentity, now?:Date):Promise<void>; transitionWorkItem(input:{workItemId:string; from?:WorkItemState; to:WorkItemState; owner:OwnershipIdentity; now?:Date; executionId?:string}):Promise<WorkItem>; getWorkItem(id:string):Promise<WorkItem|undefined>; reconcileExpiredLeases(now?:Date):Promise<WorkItem[]> }
const secretKey=/(secret|token|cookie|password|authorization|api[_-]?key|credential)/i
function assertSerializableClean(v:unknown){ if(!isPlainSerializable(v)) throw new OwnershipError('invalid_record','record must be serializable'); const s=JSON.stringify(v); if(secretKey.test(s)) throw new OwnershipError('unsafe_record','coordination records must not include secret material') }
function iso(d:Date){return d.toISOString()} function clone<T>(v:T):T{return JSON.parse(JSON.stringify(v))}
export class InMemoryCoordinationStore implements CoordinationStore { private instances=new Map<string,SupervisorInstance>(); private work=new Map<string,WorkItem>(); private leases=new Map<string,Lease>(); private generations=new Map<string,number>(); private clock: CoordinationClock
 private audit?: CoordinationAuditSink
 constructor(clock:CoordinationClock=systemClock, audit?:CoordinationAuditSink){ this.clock=clock; this.audit=audit }
 private now(d?:Date){return d??this.clock.now()} private emit(eventType:string,p:Record<string,SerializableValue>){ this.audit?.write({eventType,occurredAt:iso(this.now()),payload:p}) }
 async registerInstance(i:SupervisorInstance){ if(!supervisorStatuses.includes(i.status)) throw new OwnershipError('invalid_instance','invalid instance status'); assertSerializableClean(i); const existing=this.instances.get(i.instanceId); if(existing && existing.runtimeId!==i.runtimeId){ for(const [wid,l] of [...this.leases]) if(l.ownerInstanceId===i.instanceId){ this.leases.delete(wid); const w=this.work.get(wid); if(w&&!terminalWorkItemStates.has(w.state)){ w.currentLease=undefined; w.state='queued' } } } const c=clone(i); this.instances.set(i.instanceId,c); this.emit('supervisor_instance_registered',{instanceId:i.instanceId,runtimeId:i.runtimeId,status:i.status}); return clone(c)}
 async heartbeatInstance(instanceId:string,runtimeId:string,at=this.now()){ const i=this.instances.get(instanceId); if(!i||i.runtimeId!==runtimeId||i.status==='stopped'||i.status==='unavailable') throw new OwnershipError('stale_owner_rejected','instance cannot heartbeat'); i.heartbeatAt=iso(at); if(i.status==='starting') i.status='healthy'; this.emit('supervisor_heartbeat',{instanceId,runtimeId}); return clone(i)}
 async markInstanceDraining(instanceId:string,runtimeId:string){ const i=this.instances.get(instanceId); if(!i||i.runtimeId!==runtimeId) throw new OwnershipError('stale_owner_rejected','instance identity mismatch'); i.status='draining'; this.emit('supervisor_draining',{instanceId,runtimeId}); return clone(i)}
 async enqueueWorkItem(w:WorkItem){ assertSerializableClean(w); if(this.work.has(w.workItemId)) throw new OwnershipError('conflict','work item exists'); const c=clone({...w,currentLease:undefined}); this.work.set(w.workItemId,c); this.emit('work_item_enqueued',{workItemId:w.workItemId,provider:w.provider}); return clone(c)}
 async listAvailableWork({provider,limit,now,tenantId}:{provider:string;limit:number;now?:Date;tenantId?:string}){ const t=this.now(now).getTime(); return [...this.work.values()].filter(w=>w.provider===provider&&(!tenantId||w.tenantId===tenantId)&&!terminalWorkItemStates.has(w.state)&&Date.parse(w.availableAt)<=t&&(!this.leases.get(w.workItemId)||Date.parse(this.leases.get(w.workItemId)!.expiresAt)<=t)).sort((a,b)=>b.priority-a.priority||Date.parse(a.availableAt)-Date.parse(b.availableAt)||a.workItemId.localeCompare(b.workItemId)).slice(0,Math.max(0,Math.min(limit,100))).map(clone) }
 async acquireLease(input:{workItemId:string;ownerInstanceId:string;ownerRuntimeId:string;leaseDurationMs:number;now?:Date}){ const at=this.now(input.now); const owner=this.instances.get(input.ownerInstanceId); if(!owner||owner.runtimeId!==input.ownerRuntimeId||owner.status!=='healthy') throw new OwnershipError('owner_unavailable','owner must be healthy'); const w=this.work.get(input.workItemId); if(!w||terminalWorkItemStates.has(w.state)) throw new OwnershipError('work_unavailable','work unavailable'); const cur=this.leases.get(w.workItemId); if(cur&&Date.parse(cur.expiresAt)>at.getTime()) throw new OwnershipError('lease_conflict','unexpired lease exists'); const token=(this.generations.get(w.workItemId)??0)+1; this.generations.set(w.workItemId,token); const lease={leaseId:`lease-${w.workItemId}-${token}`,workItemId:w.workItemId,ownerInstanceId:input.ownerInstanceId,ownerRuntimeId:input.ownerRuntimeId,fencingToken:token,acquiredAt:iso(at),heartbeatAt:iso(at),expiresAt:iso(new Date(at.getTime()+input.leaseDurationMs)),policyVersion:w.policyVersion,schemaVersion:'supervisor-lease-v1'}; this.leases.set(w.workItemId,lease); w.currentLease=clone(lease); w.state='leased'; w.attempt+=1; this.emit(token===1?'lease_acquired':'work_reassigned',{workItemId:w.workItemId,fencingToken:token}); return clone(lease)}
 async assertFence(workItemId:string,id:OwnershipIdentity,now=this.now()){ const cur=this.leases.get(workItemId); if(!cur||cur.leaseId!==id.leaseId||cur.ownerInstanceId!==id.ownerInstanceId||cur.ownerRuntimeId!==id.ownerRuntimeId||cur.fencingToken!==id.fencingToken||Date.parse(cur.expiresAt)<=now.getTime()){ this.emit('stale_owner_rejected',{workItemId,fencingToken:id.fencingToken}); throw new OwnershipError('stale_owner_rejected','stale or expired owner rejected') } }
 async renewLease(input:OwnershipIdentity&{leaseDurationMs:number;now?:Date}){ const cur=[...this.leases.values()].find(l=>l.leaseId===input.leaseId); if(!cur) throw new OwnershipError('stale_owner_rejected','missing lease'); await this.assertFence(cur.workItemId,input,this.now(input.now)); cur.heartbeatAt=iso(this.now(input.now)); cur.expiresAt=iso(new Date(this.now(input.now).getTime()+input.leaseDurationMs)); this.work.get(cur.workItemId)!.currentLease=clone(cur); this.emit('lease_renewed',{workItemId:cur.workItemId,fencingToken:cur.fencingToken}); return clone(cur)}
 async releaseLease(input:OwnershipIdentity){ const cur=[...this.leases.values()].find(l=>l.leaseId===input.leaseId); if(!cur) throw new OwnershipError('stale_owner_rejected','missing lease'); await this.assertFence(cur.workItemId,input,this.now()); this.leases.delete(cur.workItemId); const w=this.work.get(cur.workItemId); if(w&&!terminalWorkItemStates.has(w.state)){ w.currentLease=undefined; w.state='queued' } this.emit('lease_released',{workItemId:cur.workItemId,fencingToken:cur.fencingToken}) }
 async getCurrentLease(workItemId:string){ const l=this.leases.get(workItemId); return l?clone(l):undefined }
 async transitionWorkItem(input:{workItemId:string;from?:WorkItemState;to:WorkItemState;owner:OwnershipIdentity;now?:Date;executionId?:string}){ const w=this.work.get(input.workItemId); if(!w) throw new OwnershipError('missing_work','missing work'); if(terminalWorkItemStates.has(w.state)) throw new OwnershipError('terminal_work','terminal work cannot transition'); await this.assertFence(input.workItemId,input.owner,this.now(input.now)); if(input.from&&w.state!==input.from) throw new OwnershipError('state_conflict','state conflict'); w.state=input.to; if(input.executionId) w.executionId=input.executionId; return clone(w)}
 async getWorkItem(id:string){ const w=this.work.get(id); return w?clone(w):undefined }
 async reconcileExpiredLeases(now=this.now()){ const out:WorkItem[]=[]; for(const [id,l] of [...this.leases]) if(Date.parse(l.expiresAt)<=now.getTime()){ this.leases.delete(id); const w=this.work.get(id); if(w&&!terminalWorkItemStates.has(w.state)){ w.currentLease=undefined; w.state='queued'; out.push(clone(w)); this.emit('lease_expired',{workItemId:id,fencingToken:l.fencingToken}) }} this.emit('reconciliation_completed',{expiredCount:out.length}); return out }
}
export class SupervisorCoordinator { private store: CoordinationStore
 private identity: SupervisorInstance
 private leaseDurationMs: number
 constructor(store:CoordinationStore, identity:SupervisorInstance, leaseDurationMs=60000){ this.store=store; this.identity=identity; this.leaseDurationMs=leaseDurationMs } register(){return this.store.registerInstance(this.identity)} heartbeat(){return this.store.heartbeatInstance(this.identity.instanceId,this.identity.runtimeId)} drain(){return this.store.markInstanceDraining(this.identity.instanceId,this.identity.runtimeId)} acquire(workItemId:string){return this.store.acquireLease({workItemId,ownerInstanceId:this.identity.instanceId,ownerRuntimeId:this.identity.runtimeId,leaseDurationMs:this.leaseDurationMs})} }
export function ownershipIdentity(l:Lease):OwnershipIdentity{return {leaseId:l.leaseId,ownerInstanceId:l.ownerInstanceId,ownerRuntimeId:l.ownerRuntimeId,fencingToken:l.fencingToken}}
export { SupabaseCoordinationStore } from './supabase-coordination-store.ts'
export { createSupervisorCoordinationStore } from './durable-coordination-store.ts'
export { reconcileSupervisorCoordination } from './reconciliation.ts'
export * from './startup-reconciliation.ts'
