import type { SupabaseClient } from '@supabase/supabase-js'
import { type CoordinationStore, type Lease, type OwnershipIdentity, OwnershipError, type SupervisorInstance, type WorkItem, type WorkItemState, terminalWorkItemStates } from './index.ts'
import { instanceFromRow, instanceToRow, leaseFromRow, workFromRow, workToRow } from './coordination-row-mappers.ts'
import { normalizeDatabaseError } from './database-errors.ts'

type Db = SupabaseClient<any, any, any>
const clampLimit = (n: number) => Math.min(Math.max(Number.isFinite(n) ? n : 25, 1), 100)
const leaseOwner = (id: OwnershipIdentity) => ({ lease_id:id.leaseId, owner_instance_id:id.ownerInstanceId, owner_runtime_id:id.ownerRuntimeId, fencing_token:id.fencingToken })
export class SupabaseCoordinationStore implements CoordinationStore {
  private readonly supabase: Db
  constructor(supabase: Db) { this.supabase = supabase }
  private async event(eventType: string, payload: Record<string, unknown>) { await this.supabase.from('supervisor_coordination_events').insert({ event_id:`coord-${Date.now()}-${Math.random().toString(36).slice(2)}`, event_type:eventType, occurred_at:new Date().toISOString(), payload, schema_version:'supervisor-coordination-event-v1' }) }
  async registerInstance(i: SupervisorInstance) { const { data, error } = await this.supabase.from('supervisor_instances').upsert(instanceToRow(i), { onConflict:'instance_id,runtime_id' }).select('*').single(); if (error) throw normalizeDatabaseError(error); await this.event('supervisor_instance_registered',{instanceId:i.instanceId,runtimeId:i.runtimeId}); return instanceFromRow(data) }
  async heartbeatInstance(instanceId: string, runtimeId: string, at = new Date()) { const { data, error } = await this.supabase.rpc('supervisor_heartbeat_instance', { p_instance_id:instanceId, p_runtime_id:runtimeId, p_heartbeat_at:at.toISOString() }); if (error) throw normalizeDatabaseError(error,'stale_owner_rejected'); await this.event('supervisor_heartbeat_recorded',{instanceId,runtimeId}); return instanceFromRow(Array.isArray(data)?data[0]:data) }
  async markInstanceDraining(instanceId: string, runtimeId: string) { return this.markInstanceStatus(instanceId,runtimeId,'draining','supervisor_marked_draining') }
  async markInstanceUnavailable(instanceId: string, runtimeId: string) { return this.markInstanceStatus(instanceId,runtimeId,'unavailable','supervisor_marked_unavailable') }
  async markInstanceStopped(instanceId: string, runtimeId: string) { return this.markInstanceStatus(instanceId,runtimeId,'stopped','supervisor_marked_stopped') }
  private async markInstanceStatus(instanceId:string,runtimeId:string,status:string,event:string){ const { data,error }=await this.supabase.rpc('supervisor_mark_instance_status',{ p_instance_id:instanceId,p_runtime_id:runtimeId,p_status:status }); if(error) throw normalizeDatabaseError(error,'stale_owner_rejected'); await this.event(event,{instanceId,runtimeId}); return instanceFromRow(Array.isArray(data)?data[0]:data) }
  async enqueueWorkItem(w: WorkItem) { const row = workToRow(w); const { data, error } = await this.supabase.rpc('supervisor_enqueue_work_item', { p_work_item: row }); if (error) throw normalizeDatabaseError(error, error.message?.includes('idempotency') ? 'idempotency_conflict' : 'conflict'); await this.event(data?.deduplicated ? 'work_item_deduplicated':'work_item_enqueued',{workItemId:w.workItemId,provider:w.provider,tenantId:w.tenantId ?? null}); return workFromRow(data?.work_item ?? data) }
  async listAvailableWork(input: { provider: string; limit: number; now?: Date; tenantId?: string }) { let q = this.supabase.from('supervisor_work_items').select('*').eq('provider', input.provider).not('state','in','(completed,failed,blocked,expired,abandoned)').lte('available_at',(input.now??new Date()).toISOString()).order('priority',{ascending:false}).order('available_at').limit(clampLimit(input.limit)); if (input.tenantId) q = q.eq('tenant_id', input.tenantId); const {data,error}=await q; if(error) throw normalizeDatabaseError(error); return (data??[]).map(r=>workFromRow(r)) }
  async acquireLease(input: { workItemId: string; ownerInstanceId: string; ownerRuntimeId: string; leaseDurationMs: number; now?: Date }) { const { data,error }=await this.supabase.rpc('supervisor_acquire_lease',{ p_work_item_id:input.workItemId,p_owner_instance_id:input.ownerInstanceId,p_owner_runtime_id:input.ownerRuntimeId,p_lease_duration_ms:input.leaseDurationMs,p_now:(input.now??new Date()).toISOString() }); if(error) throw normalizeDatabaseError(error,error.message?.includes('conflict')?'lease_conflict':'owner_unavailable'); const row = data?.lease ?? (Array.isArray(data)?data[0]:data); await this.event('lease_acquired',{workItemId:input.workItemId,fencingToken:row.fencing_token}); return leaseFromRow(row) }
  async renewLease(input: OwnershipIdentity & { leaseDurationMs: number; now?: Date }) { const {data,error}=await this.supabase.rpc('supervisor_renew_lease',{...leaseOwner(input),p_lease_duration_ms:input.leaseDurationMs,p_now:(input.now??new Date()).toISOString()}); if(error) throw normalizeDatabaseError(error,'stale_owner_rejected'); await this.event('lease_renewed',{leaseId:input.leaseId,fencingToken:input.fencingToken}); return leaseFromRow(Array.isArray(data)?data[0]:data) }
  async releaseLease(input: OwnershipIdentity & { now?: Date }) { const {error}=await this.supabase.rpc('supervisor_release_lease',{...leaseOwner(input),p_now:(input.now??new Date()).toISOString(),p_reason:'voluntary'}); if(error) throw normalizeDatabaseError(error,'stale_owner_rejected'); await this.event('lease_released',{leaseId:input.leaseId,fencingToken:input.fencingToken}) }
  async getCurrentLease(workItemId: string) { const {data,error}=await this.supabase.from('supervisor_leases').select('*').eq('work_item_id',workItemId).eq('status','active').is('released_at',null).maybeSingle(); if(error) throw normalizeDatabaseError(error); return data?leaseFromRow(data):undefined }
  async assertFence(workItemId: string, identity: OwnershipIdentity, now = new Date()) { const {data,error}=await this.supabase.rpc('supervisor_assert_fence',{ p_work_item_id:workItemId, ...leaseOwner(identity), p_now:now.toISOString() }); if(error || data !== true) { await this.event('stale_fence_rejected',{workItemId,fencingToken:identity.fencingToken}); throw normalizeDatabaseError(error ?? 'stale fence','stale_owner_rejected') } }
  async transitionWorkItem(input: { workItemId: string; from?: WorkItemState; to: WorkItemState; owner: OwnershipIdentity; now?: Date; executionId?: string }) { if (terminalWorkItemStates.has(input.to) && input.to === 'completed') { /* verified outcome enforced by RPC/policy metadata */ } const {data,error}=await this.supabase.rpc('supervisor_transition_work_item',{ p_work_item_id:input.workItemId,p_from_state:input.from ?? null,p_to_state:input.to,p_execution_id:input.executionId ?? null,...leaseOwner(input.owner),p_now:(input.now??new Date()).toISOString()}); if(error) throw normalizeDatabaseError(error,'state_conflict'); await this.event('work_item_transitioned',{workItemId:input.workItemId,to:input.to,fencingToken:input.owner.fencingToken}); return workFromRow(Array.isArray(data)?data[0]:data) }
  async getWorkItem(id: string) { const {data,error}=await this.supabase.from('supervisor_work_items').select('*').eq('work_item_id',id).maybeSingle(); if(error) throw normalizeDatabaseError(error); return data?workFromRow(data, await this.getCurrentLease(id)):undefined }
  async reconcileExpiredLeases(now = new Date()) { const {data,error}=await this.supabase.rpc('supervisor_reconcile_expired_leases',{ p_now:now.toISOString(), p_limit:100 }); if(error) throw normalizeDatabaseError(error); await this.event('reconciliation_completed',{expiredCount:(data??[]).length}); return (data??[]).map((r:any)=>workFromRow(r)) }
}
