export type CosLearningLanguage='en'|'es'|'pt'|'pl'|'ru'
export type CosLearningCopy={title:string;subtitle:string;liveEnabled:string;liveDisabled:string;studyQuestions:string;sourceAdapters:string;retainedKnowledge:string;run:string;running:string;refresh:string;documentsAcquired:string;knowledgeAccepted:string;questionsProcessed:string;externalCost:string;rejected:string;sourceErrors:string;noRun:string;requestFailed:string}
export const COS_LEARNING_COPY:Record<CosLearningLanguage,CosLearningCopy>={
 en:{title:'COS Foundational Learning',subtitle:'Populate COS with governed, provenance-bearing knowledge from approved live sources.',liveEnabled:'Live learning enabled',liveDisabled:'Live learning disabled',studyQuestions:'Study questions',sourceAdapters:'Source adapters',retainedKnowledge:'Knowledge retained',run:'Run Foundational Learning',running:'Learning in progress…',refresh:'Refresh status',documentsAcquired:'Documents acquired',knowledgeAccepted:'Knowledge accepted this run',questionsProcessed:'Questions processed',externalCost:'External cost',rejected:'Rejected',sourceErrors:'Source errors',noRun:'No learning run has been completed on this page yet.',requestFailed:'Learning request failed.'},
 es:{title:'Aprendizaje Fundacional de COS',subtitle:'Puebla COS con conocimiento gobernado y con procedencia verificable desde fuentes en vivo aprobadas.',liveEnabled:'Aprendizaje en vivo habilitado',liveDisabled:'Aprendizaje en vivo deshabilitado',studyQuestions:'Preguntas de estudio',sourceAdapters:'Adaptadores de fuentes',retainedKnowledge:'Conocimiento retenido',run:'Ejecutar Aprendizaje Fundacional',running:'Aprendizaje en curso…',refresh:'Actualizar estado',documentsAcquired:'Documentos adquiridos',knowledgeAccepted:'Conocimiento aceptado en esta ejecución',questionsProcessed:'Preguntas procesadas',externalCost:'Costo externo',rejected:'Rechazado',sourceErrors:'Errores de fuentes',noRun:'Todavía no se ha completado ninguna ejecución de aprendizaje en esta página.',requestFailed:'La solicitud de aprendizaje falló.'},
 pt:{title:'Aprendizado Fundamental do COS',subtitle:'Preencha o COS com conhecimento governado e com proveniência verificável de fontes ao vivo aprovadas.',liveEnabled:'Aprendizado ao vivo ativado',liveDisabled:'Aprendizado ao vivo desativado',studyQuestions:'Perguntas de estudo',sourceAdapters:'Adaptadores de fontes',retainedKnowledge:'Conhecimento retido',run:'Executar Aprendizado Fundamental',running:'Aprendizado em andamento…',refresh:'Atualizar status',documentsAcquired:'Documentos adquiridos',knowledgeAccepted:'Conhecimento aceito nesta execução',questionsProcessed:'Perguntas processadas',externalCost:'Custo externo',rejected:'Rejeitado',sourceErrors:'Erros das fontes',noRun:'Nenhuma execução de aprendizado foi concluída nesta página ainda.',requestFailed:'A solicitação de aprendizado falhou.'},
 pl:{title:'Uczenie Podstawowe COS',subtitle:'Zasil COS zarządzaną wiedzą z potwierdzonym pochodzeniem z zatwierdzonych źródeł na żywo.',liveEnabled:'Uczenie na żywo włączone',liveDisabled:'Uczenie na żywo wyłączone',studyQuestions:'Pytania badawcze',sourceAdapters:'Adaptery źródeł',retainedKnowledge:'Zachowana wiedza',run:'Uruchom Uczenie Podstawowe',running:'Uczenie w toku…',refresh:'Odśwież stan',documentsAcquired:'Pozyskane dokumenty',knowledgeAccepted:'Wiedza przyjęta w tym uruchomieniu',questionsProcessed:'Przetworzone pytania',externalCost:'Koszt zewnętrzny',rejected:'Odrzucone',sourceErrors:'Błędy źródeł',noRun:'Na tej stronie nie ukończono jeszcze żadnego uruchomienia uczenia.',requestFailed:'Żądanie uczenia nie powiodło się.'},
 ru:{title:'Базовое обучение COS',subtitle:'Наполняйте COS управляемыми знаниями с подтверждённым происхождением из одобренных актуальных источников.',liveEnabled:'Обучение в реальном времени включено',liveDisabled:'Обучение в реальном времени отключено',studyQuestions:'Учебные вопросы',sourceAdapters:'Адаптеры источников',retainedKnowledge:'Сохранённые знания',run:'Запустить базовое обучение',running:'Идёт обучение…',refresh:'Обновить статус',documentsAcquired:'Получено документов',knowledgeAccepted:'Знания, принятые в этом запуске',questionsProcessed:'Обработано вопросов',externalCost:'Внешние расходы',rejected:'Отклонено',sourceErrors:'Ошибки источников',noRun:'На этой странице ещё не было завершено ни одного запуска обучения.',requestFailed:'Запрос на обучение завершился ошибкой.'}
}
