// saas/lib/i18n/outreachReleaseCopy.ts
export type OutreachReleaseLanguage = 'en' | 'es' | 'pt' | 'pl' | 'ru'
export type OutreachReleaseStatus = 'pending' | 'approved' | 'sent' | 'rejected'

export type OutreachContactsCopy = {
  eyebrow: string; title: string; subtitle: string; all: string; pending: string; approved: string; sent: string; rejected: string
  discover: string; delivery: string; batch: string; batching: string; batchConfirm: string; noBatch: string; batchDone: string
  loading: string; loadError: string; retry: string; empty: string; analyze: string; unnamed: string; recipient: string; noRecipient: string
  approveSend: string; sendApproved: string; reject: string; openEngine: string; show: string; hide: string; strategist: string
  sentNotice: string; alreadySent: string; notSent: string; rejectedNotice: string; updateError: string; previous: string; next: string
  statuses: Record<OutreachReleaseStatus, string>
}

export type OutreachDeliveryCopy = {
  link: string; eyebrow: string; title: string; subtitle: string; back: string; refresh: string; refreshing: string; loadError: string
  configured: string; missing: string; resendKey: string; webhook: string; replyTo: string; historicalSends: string; queueSent: string
  approvedWaiting: string; deliveryEvents: string; replyRows: string; checked: string; accepted: string; delivered: string; opened: string
  clicked: string; bounced: string; complained: string; recipient: string; subject: string; sentAt: string; status: string; opens: string
  clicks: string; noHistory: string; reconciliation: string; fallback: string; database: string; provider: string; unknown: string
}

const CONTACTS: Record<OutreachReleaseLanguage, OutreachContactsCopy> = {
  en: {
    eyebrow: 'Contacts', title: 'Your analyzed prospects, ready for human approval and release.', subtitle: 'Approve & Send is the human release gate. Resend acceptance moves the record to Sent; approved records that could not send remain visible with the exact reason.',
    all: 'All', pending: 'Pending', approved: 'Approved', sent: 'Sent', rejected: 'Rejected', discover: '+ Discover new lead', delivery: 'Resend delivery', batch: 'Send approved batch (up to 10)', batching: 'Sending approved batch…', batchConfirm: 'Send up to 10 already-approved outreach emails now? Duplicate protection, the panic switch, message guardrails, and the 50-per-day limit remain active.', noBatch: 'There are no unsent approved records with usable email addresses.', batchDone: 'Batch complete: {sent} sent, {skipped} skipped.',
    loading: 'Loading contacts…', loadError: 'The contacts could not be loaded.', retry: 'Try again', empty: 'There are no prospects in this view.', analyze: 'Analyze your first lead', unnamed: 'Unnamed business', recipient: 'Will send to', noRecipient: 'No valid published email was found — this cannot be sent.', approveSend: 'Approve & Send', sendApproved: 'Send approved', reject: 'Reject', openEngine: 'Open engine', show: 'Show full draft', hide: 'Hide draft', strategist: '🧠 Strategist',
    sentNotice: 'Approved and accepted by Resend. The record is now Sent.', alreadySent: 'This email was already in the send ledger. Its queue status was reconciled to Sent without a duplicate.', notSent: 'Approved, but the email was not sent.', rejectedNotice: 'The record was rejected. Nothing was sent.', updateError: 'The outreach update failed. Please try again.', previous: 'Previous', next: 'Next', statuses: { pending: 'pending', approved: 'approved', sent: 'sent', rejected: 'rejected' },
  },
  es: {
    eyebrow: 'Contactos', title: 'Tus prospectos analizados, listos para aprobación y envío humanos.', subtitle: 'Aprobar y enviar es la autorización humana. La aceptación de Resend cambia el registro a Enviado; los aprobados que no pudieron salir siguen visibles con la razón exacta.',
    all: 'Todos', pending: 'Pendientes', approved: 'Aprobados', sent: 'Enviados', rejected: 'Rechazados', discover: '+ Descubrir nuevo lead', delivery: 'Entrega de Resend', batch: 'Enviar lote aprobado (hasta 10)', batching: 'Enviando lote aprobado…', batchConfirm: '¿Enviar ahora hasta 10 correos ya aprobados? Siguen activos la protección contra duplicados, el interruptor de emergencia, las reglas de seguridad y el límite diario de 50.', noBatch: 'No hay registros aprobados sin enviar con correos utilizables.', batchDone: 'Lote completado: {sent} enviados, {skipped} omitidos.',
    loading: 'Cargando contactos…', loadError: 'No se pudieron cargar los contactos.', retry: 'Reintentar', empty: 'No hay prospectos en esta vista.', analyze: 'Analizar tu primer lead', unnamed: 'Negocio sin nombre', recipient: 'Se enviará a', noRecipient: 'No se encontró un correo publicado válido — no se puede enviar.', approveSend: 'Aprobar y enviar', sendApproved: 'Enviar aprobado', reject: 'Rechazar', openEngine: 'Abrir motor', show: 'Ver borrador completo', hide: 'Ocultar borrador', strategist: '🧠 Estratega',
    sentNotice: 'Aprobado y aceptado por Resend. El registro ahora figura como Enviado.', alreadySent: 'Este correo ya estaba en el registro de envíos. Se corrigió el estado a Enviado sin duplicarlo.', notSent: 'Aprobado, pero el correo no fue enviado.', rejectedNotice: 'El registro fue rechazado. No se envió nada.', updateError: 'No se pudo actualizar el registro. Inténtalo de nuevo.', previous: 'Anterior', next: 'Siguiente', statuses: { pending: 'pendiente', approved: 'aprobado', sent: 'enviado', rejected: 'rechazado' },
  },
  pt: {
    eyebrow: 'Contatos', title: 'Seus prospects analisados, prontos para aprovação e envio humanos.', subtitle: 'Aprovar e enviar é a liberação humana. Quando o Resend aceita, o registro muda para Enviado; aprovados que não puderam sair permanecem visíveis com o motivo exato.',
    all: 'Todos', pending: 'Pendentes', approved: 'Aprovados', sent: 'Enviados', rejected: 'Rejeitados', discover: '+ Descobrir novo lead', delivery: 'Entrega do Resend', batch: 'Enviar lote aprovado (até 10)', batching: 'Enviando lote aprovado…', batchConfirm: 'Enviar agora até 10 e-mails já aprovados? A proteção contra duplicatas, o interruptor de emergência, as regras de segurança e o limite diário de 50 continuam ativos.', noBatch: 'Não há registros aprovados e ainda não enviados com e-mails utilizáveis.', batchDone: 'Lote concluído: {sent} enviados, {skipped} ignorados.',
    loading: 'Carregando contatos…', loadError: 'Não foi possível carregar os contatos.', retry: 'Tentar novamente', empty: 'Não há prospects nesta visualização.', analyze: 'Analisar seu primeiro lead', unnamed: 'Negócio sem nome', recipient: 'Será enviado para', noRecipient: 'Nenhum e-mail publicado válido foi encontrado — não pode ser enviado.', approveSend: 'Aprovar e enviar', sendApproved: 'Enviar aprovado', reject: 'Rejeitar', openEngine: 'Abrir motor', show: 'Ver rascunho completo', hide: 'Ocultar rascunho', strategist: '🧠 Estrategista',
    sentNotice: 'Aprovado e aceito pelo Resend. O registro agora está como Enviado.', alreadySent: 'Este e-mail já estava no ledger de envios. O status foi reconciliado para Enviado sem duplicação.', notSent: 'Aprovado, mas o e-mail não foi enviado.', rejectedNotice: 'O registro foi rejeitado. Nada foi enviado.', updateError: 'Não foi possível atualizar o registro. Tente novamente.', previous: 'Anterior', next: 'Próxima', statuses: { pending: 'pendente', approved: 'aprovado', sent: 'enviado', rejected: 'rejeitado' },
  },
  pl: {
    eyebrow: 'Kontakty', title: 'Przeanalizowani potencjalni klienci gotowi do zatwierdzenia i wysłania przez człowieka.', subtitle: 'Zatwierdź i wyślij jest ludzką bramką wydania. Po przyjęciu przez Resend rekord przechodzi do Wysłane; zatwierdzone wiadomości, których nie udało się wysłać, pozostają widoczne z dokładnym powodem.',
    all: 'Wszystkie', pending: 'Oczekujące', approved: 'Zatwierdzone', sent: 'Wysłane', rejected: 'Odrzucone', discover: '+ Odkryj nowy lead', delivery: 'Dostawa Resend', batch: 'Wyślij zatwierdzoną partię (do 10)', batching: 'Wysyłanie zatwierdzonej partii…', batchConfirm: 'Wysłać teraz do 10 wcześniej zatwierdzonych wiadomości? Nadal działają zabezpieczenie przed duplikatami, wyłącznik awaryjny, reguły bezpieczeństwa i limit 50 dziennie.', noBatch: 'Brak niewysłanych zatwierdzonych rekordów z prawidłowymi adresami e-mail.', batchDone: 'Partia zakończona: wysłano {sent}, pominięto {skipped}.',
    loading: 'Ładowanie kontaktów…', loadError: 'Nie można załadować kontaktów.', retry: 'Spróbuj ponownie', empty: 'Brak potencjalnych klientów w tym widoku.', analyze: 'Przeanalizuj pierwszy lead', unnamed: 'Firma bez nazwy', recipient: 'Zostanie wysłane do', noRecipient: 'Nie znaleziono prawidłowego publicznego adresu e-mail — wysyłka niemożliwa.', approveSend: 'Zatwierdź i wyślij', sendApproved: 'Wyślij zatwierdzone', reject: 'Odrzuć', openEngine: 'Otwórz silnik', show: 'Pokaż pełny szkic', hide: 'Ukryj szkic', strategist: '🧠 Strateg',
    sentNotice: 'Zatwierdzono i przyjęto przez Resend. Rekord ma teraz status Wysłano.', alreadySent: 'Wiadomość była już w rejestrze wysyłek. Status uzgodniono jako Wysłano bez duplikatu.', notSent: 'Zatwierdzono, ale wiadomość nie została wysłana.', rejectedNotice: 'Rekord został odrzucony. Nic nie wysłano.', updateError: 'Nie udało się zaktualizować rekordu. Spróbuj ponownie.', previous: 'Poprzednia', next: 'Następna', statuses: { pending: 'oczekuje', approved: 'zatwierdzony', sent: 'wysłany', rejected: 'odrzucony' },
  },
  ru: {
    eyebrow: 'Контакты', title: 'Проверенные потенциальные клиенты готовы к одобрению и отправке человеком.', subtitle: '«Одобрить и отправить» — это человеческое разрешение. После принятия Resend запись получает статус «Отправлено»; неотправленные одобренные письма остаются видимыми с точной причиной.',
    all: 'Все', pending: 'Ожидают', approved: 'Одобрены', sent: 'Отправлены', rejected: 'Отклонены', discover: '+ Найти новый лид', delivery: 'Доставка Resend', batch: 'Отправить одобренную партию (до 10)', batching: 'Отправка одобренной партии…', batchConfirm: 'Отправить сейчас до 10 ранее одобренных писем? Защита от дубликатов, аварийный выключатель, правила безопасности и лимит 50 в сутки остаются включены.', noBatch: 'Нет неотправленных одобренных записей с пригодными адресами.', batchDone: 'Партия завершена: отправлено {sent}, пропущено {skipped}.',
    loading: 'Загрузка контактов…', loadError: 'Не удалось загрузить контакты.', retry: 'Повторить', empty: 'В этом представлении нет потенциальных клиентов.', analyze: 'Проанализировать первый лид', unnamed: 'Компания без названия', recipient: 'Будет отправлено на', noRecipient: 'Действительный опубликованный адрес не найден — отправка невозможна.', approveSend: 'Одобрить и отправить', sendApproved: 'Отправить одобренное', reject: 'Отклонить', openEngine: 'Открыть движок', show: 'Показать черновик', hide: 'Скрыть черновик', strategist: '🧠 Стратег',
    sentNotice: 'Одобрено и принято Resend. Запись теперь имеет статус «Отправлено».', alreadySent: 'Письмо уже было в журнале отправок. Статус исправлен на «Отправлено» без дубликата.', notSent: 'Одобрено, но письмо не отправлено.', rejectedNotice: 'Запись отклонена. Ничего не отправлено.', updateError: 'Не удалось обновить запись. Повторите попытку.', previous: 'Назад', next: 'Далее', statuses: { pending: 'ожидает', approved: 'одобрен', sent: 'отправлен', rejected: 'отклонён' },
  },
}

const DELIVERY: Record<OutreachReleaseLanguage, OutreachDeliveryCopy> = {
  en: { link: '📬 Resend', eyebrow: 'Resend delivery monitor', title: 'Verify what was really sent.', subtitle: 'This page reads the durable outreach_sends ledger, checks recent message IDs directly with Resend, reconciles stale Approved rows, and shows delivery, open, click, bounce, and reply-table evidence.', back: 'Back to Outreach Monitor', refresh: 'Sync Resend now', refreshing: 'Syncing…', loadError: 'Could not load outreach delivery history.', configured: 'Configured', missing: 'Missing', resendKey: 'Resend API key', webhook: 'Resend webhook', replyTo: 'Reply-to mailbox', historicalSends: 'Historical send records', queueSent: 'Queue marked sent', approvedWaiting: 'Approved waiting', deliveryEvents: 'Webhook events', replyRows: 'Reply records', checked: 'Recent checked', accepted: 'Accepted by Resend', delivered: 'Delivered', opened: 'Opened', clicked: 'Clicked', bounced: 'Bounced', complained: 'Complaints', recipient: 'Recipient', subject: 'Subject', sentAt: 'Sent at', status: 'Status', opens: 'Opens', clicks: 'Clicks', noHistory: 'No outreach_sends records were found.', reconciliation: 'Queue reconciliation', fallback: 'schema fallback', database: 'Database evidence', provider: 'Resend evidence', unknown: 'unknown' },
  es: { link: '📬 Resend', eyebrow: 'Monitor de entrega de Resend', title: 'Verifica qué se envió realmente.', subtitle: 'Esta página lee el registro durable outreach_sends, consulta los IDs recientes directamente en Resend, reconcilia filas Aprobadas obsoletas y muestra evidencia de entrega, apertura, clic, rebote y respuestas.', back: 'Volver al monitor de Outreach', refresh: 'Sincronizar Resend ahora', refreshing: 'Sincronizando…', loadError: 'No se pudo cargar el historial de entregas.', configured: 'Configurado', missing: 'Falta', resendKey: 'Clave API de Resend', webhook: 'Webhook de Resend', replyTo: 'Buzón de respuesta', historicalSends: 'Registros históricos de envío', queueSent: 'Cola marcada como enviada', approvedWaiting: 'Aprobados en espera', deliveryEvents: 'Eventos del webhook', replyRows: 'Registros de respuestas', checked: 'Recientes verificados', accepted: 'Aceptados por Resend', delivered: 'Entregados', opened: 'Abiertos', clicked: 'Clics', bounced: 'Rebotados', complained: 'Quejas', recipient: 'Destinatario', subject: 'Asunto', sentAt: 'Enviado', status: 'Estado', opens: 'Aperturas', clicks: 'Clics', noHistory: 'No se encontraron registros outreach_sends.', reconciliation: 'Reconciliación de cola', fallback: 'respaldo de esquema', database: 'Evidencia de base de datos', provider: 'Evidencia de Resend', unknown: 'desconocido' },
  pt: { link: '📬 Resend', eyebrow: 'Monitor de entrega do Resend', title: 'Verifique o que foi realmente enviado.', subtitle: 'Esta página lê o ledger durável outreach_sends, consulta IDs recentes diretamente no Resend, reconcilia linhas Aprovadas desatualizadas e mostra evidências de entrega, abertura, clique, rejeição e respostas.', back: 'Voltar ao Monitor de Outreach', refresh: 'Sincronizar Resend agora', refreshing: 'Sincronizando…', loadError: 'Não foi possível carregar o histórico de entrega.', configured: 'Configurado', missing: 'Ausente', resendKey: 'Chave API do Resend', webhook: 'Webhook do Resend', replyTo: 'Caixa de resposta', historicalSends: 'Registros históricos de envio', queueSent: 'Fila marcada como enviada', approvedWaiting: 'Aprovados aguardando', deliveryEvents: 'Eventos do webhook', replyRows: 'Registros de respostas', checked: 'Recentes verificados', accepted: 'Aceitos pelo Resend', delivered: 'Entregues', opened: 'Abertos', clicked: 'Cliques', bounced: 'Rejeitados', complained: 'Reclamações', recipient: 'Destinatário', subject: 'Assunto', sentAt: 'Enviado em', status: 'Status', opens: 'Aberturas', clicks: 'Cliques', noHistory: 'Nenhum registro outreach_sends foi encontrado.', reconciliation: 'Reconciliação da fila', fallback: 'fallback de esquema', database: 'Evidência do banco', provider: 'Evidência do Resend', unknown: 'desconhecido' },
  pl: { link: '📬 Resend', eyebrow: 'Monitor dostarczania Resend', title: 'Sprawdź, co naprawdę wysłano.', subtitle: 'Ta strona czyta trwały rejestr outreach_sends, sprawdza ostatnie identyfikatory bezpośrednio w Resend, uzgadnia nieaktualne rekordy Zatwierdzone oraz pokazuje dowody dostarczeń, otwarć, kliknięć, odbić i odpowiedzi.', back: 'Wróć do monitora Outreach', refresh: 'Synchronizuj Resend', refreshing: 'Synchronizacja…', loadError: 'Nie udało się wczytać historii dostarczania.', configured: 'Skonfigurowano', missing: 'Brak', resendKey: 'Klucz API Resend', webhook: 'Webhook Resend', replyTo: 'Skrzynka odpowiedzi', historicalSends: 'Historyczne rekordy wysyłki', queueSent: 'Kolejka oznaczona jako wysłana', approvedWaiting: 'Zatwierdzone oczekujące', deliveryEvents: 'Zdarzenia webhooka', replyRows: 'Rekordy odpowiedzi', checked: 'Sprawdzone ostatnie', accepted: 'Przyjęte przez Resend', delivered: 'Dostarczone', opened: 'Otwarte', clicked: 'Kliknięte', bounced: 'Odbite', complained: 'Skargi', recipient: 'Odbiorca', subject: 'Temat', sentAt: 'Wysłano', status: 'Status', opens: 'Otwarcia', clicks: 'Kliknięcia', noHistory: 'Nie znaleziono rekordów outreach_sends.', reconciliation: 'Uzgodnienie kolejki', fallback: 'awaryjny schemat', database: 'Dowody bazy danych', provider: 'Dowody Resend', unknown: 'nieznany' },
  ru: { link: '📬 Resend', eyebrow: 'Монитор доставки Resend', title: 'Проверьте, что действительно было отправлено.', subtitle: 'Страница читает журнал outreach_sends, проверяет последние идентификаторы напрямую в Resend, исправляет устаревшие статусы «Одобрено» и показывает данные о доставке, открытиях, кликах, возвратах и ответах.', back: 'Назад к монитору аутрича', refresh: 'Синхронизировать Resend', refreshing: 'Синхронизация…', loadError: 'Не удалось загрузить историю доставки.', configured: 'Настроено', missing: 'Отсутствует', resendKey: 'API-ключ Resend', webhook: 'Webhook Resend', replyTo: 'Адрес для ответов', historicalSends: 'Исторические записи отправки', queueSent: 'Очередь отмечена отправленной', approvedWaiting: 'Одобрено и ожидает', deliveryEvents: 'События webhook', replyRows: 'Записи ответов', checked: 'Проверено последних', accepted: 'Принято Resend', delivered: 'Доставлено', opened: 'Открыто', clicked: 'Клики', bounced: 'Возвращено', complained: 'Жалобы', recipient: 'Получатель', subject: 'Тема', sentAt: 'Отправлено', status: 'Статус', opens: 'Открытия', clicks: 'Клики', noHistory: 'Записи outreach_sends не найдены.', reconciliation: 'Сверка очереди', fallback: 'резерв схемы', database: 'Данные базы', provider: 'Данные Resend', unknown: 'неизвестно' },
}

export function outreachContactsCopyFor(lang: string): OutreachContactsCopy {
  return CONTACTS[(lang in CONTACTS ? lang : 'en') as OutreachReleaseLanguage]
}

export function outreachDeliveryCopyFor(lang: string): OutreachDeliveryCopy {
  return DELIVERY[(lang in DELIVERY ? lang : 'en') as OutreachReleaseLanguage]
}
