// saas/lib/i18n/studioHubCopy.ts
// Universal Media Hub + Concierge lead-magnet translations (EN/ES/PT/PL/RU).
// Key-major: each entry is [en, es, pt, pl, ru]. Additive drop consumed by
// lib/i18n/t.ts right after DASHBOARD_COPY, so English keys already living in
// dashboardCopy.ts keep working while ES/PT/PL/RU stop falling back to English.
// EN values mirror the fallbacks in lib/services/catalog.ts and dashboardCopy.ts.

type Five = [string, string, string, string, string]

const RAW: Record<string, Five> = {
  // ── Service cards (Home Page taxonomy, 9 services) ──────────────────────
  'services.promote.title': ['Promote Business', 'Promocionar negocio', 'Promover negócio', 'Promuj firmę', 'Продвигать бизнес'],
  'services.promote.desc': ['Launch localized campaigns, ad copy, outreach, and offers from one business brief.', 'Lance campañas localizadas, textos de anuncios, alcance y ofertas desde un solo brief de negocio.', 'Lance campanhas localizadas, textos de anúncio, prospecção e ofertas a partir de um único briefing de negócio.', 'Uruchamiaj zlokalizowane kampanie, teksty reklam, kontakt i oferty z jednego briefu biznesowego.', 'Запускайте локализованные кампании, рекламные тексты, аутрич и предложения из одного бизнес-брифа.'],
  'services.promote.cta': ['Open marketing tools', 'Abrir herramientas de marketing', 'Abrir ferramentas de marketing', 'Otwórz narzędzia marketingowe', 'Открыть маркетинговые инструменты'],
  'services.builder.title': ['Build Website', 'Crear un sitio web', 'Criar um site', 'Zbuduj stronę', 'Создать сайт'],
  'services.builder.desc': ['Generate a responsive multilingual site with structure, sections, and publish-ready calls to action.', 'Genere un sitio multilingüe y adaptable con estructura, secciones y llamadas a la acción listas para publicar.', 'Gere um site multilíngue e responsivo com estrutura, seções e chamadas para ação prontas para publicar.', 'Wygeneruj responsywną, wielojęzyczną stronę ze strukturą, sekcjami i gotowymi wezwaniami do działania.', 'Создайте адаптивный многоязычный сайт со структурой, разделами и готовыми призывами к действию.'],
  'services.builder.cta': ['Open website builder', 'Abrir creador de sitios', 'Abrir criador de sites', 'Otwórz kreator stron', 'Открыть конструктор сайтов'],
  'services.reviews.title': ['Collect Reviews', 'Recopilar reseñas', 'Coletar avaliações', 'Zbieraj recenzje', 'Собирать отзывы'],
  'services.reviews.desc': ['Create review links, follow-ups, and testimonial assets that turn trust into growth.', 'Cree enlaces de reseñas, seguimientos y testimonios que convierten la confianza en crecimiento.', 'Crie links de avaliação, follow-ups e depoimentos que transformam confiança em crescimento.', 'Twórz linki do recenzji, follow-upy i materiały z opiniami, które zamieniają zaufanie we wzrost.', 'Создавайте ссылки на отзывы, напоминания и материалы с отзывами, превращающие доверие в рост.'],
  'services.reviews.cta': ['Open review collection', 'Abrir recopilación de reseñas', 'Abrir coleta de avaliações', 'Otwórz zbieranie recenzji', 'Открыть сбор отзывов'],
  'services.audio.title': ['Generate Audio', 'Generar audio', 'Gerar áudio', 'Generuj audio', 'Создать аудио'],
  'services.audio.desc': ['Turn scripts into natural voice content for promos, podcasts, explainers, and social clips.', 'Convierta guiones en voz natural para promos, pódcasts, explicativos y clips sociales.', 'Transforme roteiros em voz natural para promos, podcasts, vídeos explicativos e clipes sociais.', 'Zamieniaj scenariusze w naturalny głos do promocji, podcastów, materiałów objaśniających i klipów.', 'Превращайте сценарии в естественный голос для промо, подкастов, объяснений и соцроликов.'],
  'services.audio.cta': ['Open audio studio', 'Abrir estudio de audio', 'Abrir estúdio de áudio', 'Otwórz studio audio', 'Открыть аудиостудию'],
  'services.video.title': ['Create Videos', 'Crear videos', 'Criar vídeos', 'Twórz filmy', 'Создавать видео'],
  'services.video.desc': ['Plan, script, generate, and package short-form videos with AI-guided production steps.', 'Planifique, escriba, genere y empaquete videos cortos con pasos de producción guiados por IA.', 'Planeje, roteirize, gere e finalize vídeos curtos com etapas de produção guiadas por IA.', 'Planuj, pisz, generuj i pakuj krótkie filmy z krokami produkcji prowadzonymi przez AI.', 'Планируйте, пишите, создавайте и упаковывайте короткие видео с шагами производства под руководством ИИ.'],
  'services.video.cta': ['Open video creator', 'Abrir creador de videos', 'Abrir criador de vídeos', 'Otwórz kreator filmów', 'Открыть создание видео'],
  'services.improve.title': ['Improve Website', 'Mejorar sitio web', 'Melhorar site', 'Ulepsz stronę', 'Улучшить сайт'],
  'services.improve.desc': ['Audit any URL for clarity, SEO, conversion, accessibility, and speed improvement opportunities.', 'Audite cualquier URL en busca de mejoras de claridad, SEO, conversión, accesibilidad y velocidad.', 'Audite qualquer URL em busca de melhorias de clareza, SEO, conversão, acessibilidade e velocidade.', 'Audytuj dowolny URL pod kątem przejrzystości, SEO, konwersji, dostępności i szybkości.', 'Проверяйте любой URL на ясность, SEO, конверсию, доступность и скорость.'],
  'services.improve.cta': ['Open website optimization', 'Abrir optimización del sitio', 'Abrir otimização do site', 'Otwórz optymalizację strony', 'Открыть оптимизацию сайта'],
  'services.podcastStudio.title': ['Optimize Podcast Studio', 'Optimizar estudio de pódcast', 'Otimizar estúdio de podcast', 'Optymalizuj studio podcastów', 'Оптимизировать студию подкастов'],
  'services.podcastStudio.desc': ['Improve episode workflow, transcript quality, clips, titles, metadata, and multilingual distribution.', 'Mejore el flujo de episodios, la calidad de transcripciones, clips, títulos, metadatos y distribución multilingüe.', 'Melhore o fluxo de episódios, a qualidade das transcrições, clipes, títulos, metadados e distribuição multilíngue.', 'Ulepsz przepływ odcinków, jakość transkrypcji, klipy, tytuły, metadane i dystrybucję wielojęzyczną.', 'Улучшайте процесс выпуска, качество транскриптов, клипы, заголовки, метаданные и многоязычную дистрибуцию.'],
  'services.podcastStudio.cta': ['Open podcast optimization', 'Abrir optimización de pódcast', 'Abrir otimização de podcast', 'Otwórz optymalizację podcastu', 'Открыть оптимизацию подкаста'],
  'services.lab.title': ['Lab', 'Laboratorio', 'Laboratório', 'Laboratorium', 'Лаборатория'],
  'services.lab.desc': ['Experiment with search, motion prompts, captions, and emerging AI workflows before they graduate.', 'Experimente con búsqueda, prompts de movimiento, subtítulos y flujos de IA emergentes antes de que se gradúen.', 'Experimente busca, prompts de movimento, legendas e fluxos de IA emergentes antes de eles se formarem.', 'Eksperymentuj z wyszukiwaniem, promptami ruchu, napisami i nowymi przepływami AI, zanim dojrzeją.', 'Экспериментируйте с поиском, motion-промптами, субтитрами и новыми ИИ-процессами до их выпуска.'],
  'services.lab.cta': ['Open lab', 'Abrir laboratorio', 'Abrir laboratório', 'Otwórz laboratorium', 'Открыть лабораторию'],
  'services.apprentice.title': ['Workshop Apprentice', 'Aprendiz del taller', 'Aprendiz da oficina', 'Uczeń warsztatu', 'Ученик мастерской'],
  'services.apprentice.desc': ['Follow guided tutorials and visual examples for every SignalBoost service.', 'Siga tutoriales guiados y ejemplos visuales de cada servicio de SignalBoost.', 'Siga tutoriais guiados e exemplos visuais de cada serviço da SignalBoost.', 'Korzystaj z prowadzonych samouczków i wizualnych przykładów każdej usługi SignalBoost.', 'Следуйте пошаговым руководствам и наглядным примерам по каждому сервису SignalBoost.'],
  'services.apprentice.cta': ['Start tutorial', 'Iniciar tutorial', 'Iniciar tutorial', 'Rozpocznij samouczek', 'Начать обучение'],

  // ── Studio catalog chrome ────────────────────────────────────────────────
  'studio.catalog.eyebrow': ['Universal Media Hub', 'Centro Universal de Medios', 'Hub Universal de Mídia', 'Uniwersalne Centrum Mediów', 'Универсальный медиахаб'],
  'studio.catalog.title': ['Choose the exact outcome you want.', 'Elija el resultado exacto que quiere.', 'Escolha exatamente o resultado que você quer.', 'Wybierz dokładnie ten rezultat, którego chcesz.', 'Выберите именно тот результат, который вам нужен.'],
  'studio.catalog.subtitle': ['Studio now mirrors the Home Page taxonomy: nine services and free utilities grouped by real intent, with COS Core v1 preparing drafts silently until you approve the next financial step.', 'El Studio ahora refleja la taxonomía de la página de inicio: nueve servicios y utilidades gratuitas agrupados por intención real, con COS Core v1 preparando borradores en silencio hasta que usted apruebe el siguiente paso financiero.', 'O Studio agora espelha a taxonomia da Home Page: nove serviços e utilitários gratuitos agrupados por intenção real, com o COS Core v1 preparando rascunhos em silêncio até você aprovar o próximo passo financeiro.', 'Studio odzwierciedla teraz taksonomię strony głównej: dziewięć usług i darmowych narzędzi pogrupowanych według realnej intencji, a COS Core v1 przygotowuje szkice po cichu, dopóki nie zatwierdzisz kolejnego kroku finansowego.', 'Studio теперь отражает таксономию главной страницы: девять сервисов и бесплатных утилит, сгруппированных по реальному намерению, а COS Core v1 тихо готовит черновики, пока вы не одобрите следующий финансовый шаг.'],
  'studio.catalog.aria': ['Universal Media Hub service catalog', 'Catálogo de servicios del Centro Universal de Medios', 'Catálogo de serviços do Hub Universal de Mídia', 'Katalog usług Uniwersalnego Centrum Mediów', 'Каталог сервисов Универсального медиахаба'],
  'studio.catalog.ledger': ['Starter Pack: 50 Credits = $15 · Pro Pack: 200 Credits = $50 when activation is enabled.', 'Paquete Inicial: 50 créditos = $15 · Paquete Pro: 200 créditos = $50 cuando la activación está habilitada.', 'Pacote Inicial: 50 Créditos = $15 · Pacote Pro: 200 Créditos = $50 quando a ativação estiver ligada.', 'Pakiet Startowy: 50 kredytów = 15 USD · Pakiet Pro: 200 kredytów = 50 USD, gdy aktywacja jest włączona.', 'Стартовый пакет: 50 кредитов = $15 · Пакет Pro: 200 кредитов = $50, когда активация включена.'],
  'studio.group.growth.title': ['Growth and proof', 'Crecimiento y prueba social', 'Crescimento e prova social', 'Wzrost i dowód społeczny', 'Рост и социальное доказательство'],
  'studio.group.growth.desc': ['Launch localized demand and collect proof users can trust.', 'Lance demanda localizada y recopile pruebas en las que los usuarios puedan confiar.', 'Lance demanda localizada e colete provas em que os usuários possam confiar.', 'Uruchamiaj zlokalizowany popyt i zbieraj dowody, którym użytkownicy mogą zaufać.', 'Запускайте локализованный спрос и собирайте доказательства, которым доверяют пользователи.'],
  'studio.group.media.title': ['Media creation', 'Creación de medios', 'Criação de mídia', 'Tworzenie mediów', 'Создание медиа'],
  'studio.group.media.desc': ['Generate pay-as-you-go video, native voice, and campaign-ready support audio.', 'Genere video de pago por uso, voz nativa y audio de apoyo listo para campañas.', 'Gere vídeo pay-as-you-go, voz nativa e áudio de apoio pronto para campanhas.', 'Generuj wideo w modelu pay-as-you-go, natywny głos i audio wspierające kampanie.', 'Создавайте видео по мере использования, нативный голос и вспомогательное аудио для кампаний.'],
  'studio.group.web.title': ['Website outcomes', 'Resultados web', 'Resultados de site', 'Efekty stron WWW', 'Результаты для сайта'],
  'studio.group.web.desc': ['Create a new web presence or improve an existing URL.', 'Cree una nueva presencia web o mejore una URL existente.', 'Crie uma nova presença na web ou melhore uma URL existente.', 'Stwórz nową obecność w sieci lub ulepsz istniejący URL.', 'Создайте новое веб-присутствие или улучшите существующий URL.'],
  'studio.group.utilities.title': ['Free utilities and learning', 'Utilidades gratuitas y aprendizaje', 'Utilitários gratuitos e aprendizado', 'Darmowe narzędzia i nauka', 'Бесплатные утилиты и обучение'],
  'studio.group.utilities.desc': ['Use lead magnets, labs, and guided lessons before committing credits.', 'Use imanes de clientes, laboratorios y lecciones guiadas antes de comprometer créditos.', 'Use iscas digitais, laboratórios e lições guiadas antes de comprometer créditos.', 'Korzystaj z lead magnetów, laboratoriów i prowadzonych lekcji, zanim wydasz kredyty.', 'Используйте лид-магниты, лаборатории и обучающие уроки, прежде чем тратить кредиты.'],
  'studio.intent.promote': ['Free-form business brief', 'Brief de negocio libre', 'Briefing de negócio livre', 'Swobodny brief biznesowy', 'Свободный бизнес-бриф'],
  'studio.intent.video': ['Pay-as-you-go AI video', 'Video IA de pago por uso', 'Vídeo IA pay-as-you-go', 'Wideo AI pay-as-you-go', 'ИИ-видео по мере использования'],
  'studio.intent.audio': ['Native voice generation', 'Generación de voz nativa', 'Geração de voz nativa', 'Generowanie natywnego głosu', 'Генерация нативного голоса'],
  'studio.intent.reviews': ['Social proof assets', 'Activos de prueba social', 'Assets de prova social', 'Materiały dowodu społecznego', 'Материалы социального доказательства'],
  'studio.intent.builder': ['Build from scratch', 'Crear desde cero', 'Criar do zero', 'Buduj od zera', 'Создание с нуля'],
  'studio.intent.improve': ['Optimize an existing URL', 'Optimizar una URL existente', 'Otimizar uma URL existente', 'Optymalizuj istniejący URL', 'Оптимизация существующего URL'],
  'studio.intent.podcastStudio': ['Podcast workflow utility', 'Utilidad de flujo de pódcast', 'Utilitário de fluxo de podcast', 'Narzędzie przepływu podcastów', 'Утилита подкаст-процесса'],
  'studio.intent.lab': ['Experimental utility', 'Utilidad experimental', 'Utilitário experimental', 'Narzędzie eksperymentalne', 'Экспериментальная утилита'],
  'studio.intent.apprentice': ['Guided learning', 'Aprendizaje guiado', 'Aprendizado guiado', 'Nauka z przewodnikiem', 'Обучение с наставником'],

  // ── Concierge lead-magnet + approval flow ───────────────────────────────
  'concierge.utilityOffer': ['I identified optimization opportunities on your URL. Would you like our media studio (COS Core v1) to automatically create a video campaign to boost your conversion for only 10 credits?', 'Identifiqué oportunidades de optimización en su URL. ¿Desea que nuestro estudio de medios (COS Core v1) cree automáticamente una campaña de video para impulsar su conversión por solo 10 créditos?', 'Identifiquei oportunidades de otimização na sua URL. Deseja que o nosso estúdio de mídia (COS Core v1) crie automaticamente uma campanha de vídeo para impulsionar sua conversão por apenas 10 créditos?', 'Zidentyfikowałem możliwości optymalizacji Twojego URL. Czy chcesz, aby nasze studio mediów (COS Core v1) automatycznie stworzyło kampanię wideo zwiększającą konwersję za jedyne 10 kredytów?', 'Я обнаружил возможности оптимизации вашего URL. Хотите, чтобы наша медиастудия (COS Core v1) автоматически создала видеокампанию для роста конверсии всего за 10 кредитов?'],
  'concierge.approvalReady': ['Your COS Core v1 asset is ready. Open the Studio financial approval card to review credits before release: /dashboard/cosa. Starter Pack: 50 Credits = $15 · Pro Pack: 200 Credits = $50.', 'Su asset de COS Core v1 está listo. Abra la tarjeta de aprobación financiera del Studio para revisar los créditos antes de publicar: /dashboard/cosa. Paquete Inicial: 50 créditos = $15 · Paquete Pro: 200 créditos = $50.', 'Seu asset do COS Core v1 está pronto. Abra o card de aprovação financeira do Studio para revisar os créditos antes da publicação: /dashboard/cosa. Pacote Inicial: 50 Créditos = $15 · Pacote Pro: 200 Créditos = $50.', 'Twój materiał COS Core v1 jest gotowy. Otwórz kartę zatwierdzenia finansowego w Studio, aby przejrzeć kredyty przed publikacją: /dashboard/cosa. Pakiet Startowy: 50 kredytów = 15 USD · Pakiet Pro: 200 kredytów = 50 USD.', 'Ваш материал COS Core v1 готов. Откройте карточку финансового одобрения в Studio, чтобы проверить кредиты перед публикацией: /dashboard/cosa. Стартовый пакет: 50 кредитов = $15 · Пакет Pro: 200 кредитов = $50.'],
  'concierge.assetReady': ['Your COS Core v1 asset is ready. Review it on the Studio financial approval card before release:', 'Su asset de COS Core v1 está listo. Revíselo en la tarjeta de aprobación financiera del Studio antes de publicar:', 'Seu asset do COS Core v1 está pronto. Revise no card de aprovação financeira do Studio antes da publicação:', 'Twój materiał COS Core v1 jest gotowy. Sprawdź go na karcie zatwierdzenia finansowego w Studio przed publikacją:', 'Ваш материал COS Core v1 готов. Проверьте его в карточке финансового одобрения Studio перед публикацией:'],
  'concierge.assetReadyCta': ['Open approval card', 'Abrir tarjeta de aprobación', 'Abrir card de aprovação', 'Otwórz kartę zatwierdzenia', 'Открыть карточку одобрения'],
  'credits.packs': ['Starter Pack: 50 Credits = $15 · Pro Pack: 200 Credits = $50.', 'Paquete Inicial: 50 créditos = $15 · Paquete Pro: 200 créditos = $50.', 'Pacote Inicial: 50 Créditos = $15 · Pacote Pro: 200 Créditos = $50.', 'Pakiet Startowy: 50 kredytów = 15 USD · Pakiet Pro: 200 kredytów = 50 USD.', 'Стартовый пакет: 50 кредитов = $15 · Пакет Pro: 200 кредитов = $50.'],
}

const LANGS = ['en', 'es', 'pt', 'pl', 'ru'] as const

export const STUDIO_HUB_COPY: Record<string, Record<string, string>> = {
  en: {}, es: {}, pt: {}, pl: {}, ru: {},
}

for (const [key, vals] of Object.entries(RAW)) {
  LANGS.forEach((lang, i) => {
    STUDIO_HUB_COPY[lang][key] = vals[i]
  })
}
