import type { SerializableValue } from '../incident-schema.ts'
export const executionModes=['api_only','smart_failover','browser_on_demand'] as const; export type ExecutionMode=typeof executionModes[number]
export const apiFailureCategories=['succeeded_verified','succeeded_unverified','timeout','rate_limited','temporarily_unavailable','provider_outage','capability_missing','result_inconsistent','authentication_failed','permission_denied','invalid_request','permanent_failure','unknown_failure'] as const; export type ApiFailureCategory=typeof apiFailureCategories[number]
export const browserReasons=['human_requested','api_capability_missing','api_unavailable_after_bounded_retries','api_result_inconsistent','ui_verification_required'] as const; export type BrowserReason=typeof browserReasons[number]
export const riskClasses=['read_only','low_risk_reversible','medium','high','forbidden'] as const; export type RiskClass=typeof riskClasses[number]
export const maturityLevels=['experimental','sandbox_verified','human_approved','auto_failover_ready','suspended'] as const; export type CapabilityMaturity=typeof maturityLevels[number]
export type ExecutionDecisionCode='use_api'|'retry_api'|'use_browser_automatically'|'use_browser_with_guardrails'|'require_human_approval'|'use_manual_operator'|'block'
export type ExecutionChannel='api'|'browser'|'manual'|'none'
export class PolicyError extends Error { readonly code:string; constructor(code:string,message:string){super(message);this.code=code;this.name='PolicyError'} }
export interface BrowserReasonEvidence { reason:BrowserReason; attemptedApiCapability?:string; retryCount?:number; finalApiFailureCategory?:ApiFailureCategory; inconsistencyCategory?:string; verificationRequirement?:string; requestingOperatorId?:string }
export interface Capability { capabilityId:string; provider:string; operation:string; channels:{api:boolean;browser:boolean;manual:boolean}; riskClass:RiskClass; maturity:CapabilityMaturity; reversible:boolean; idempotent:boolean; supportsAutoFailover:boolean; supportsBrowserOnDemand:boolean; requiresHumanApproval:boolean; approvedOrigins:string[]; verificationProfileId?:string; browserAdapterId?:string; apiOperationId?:string; policyVersion:string; capabilityVersion:string; suspendedReason?:string; allowedEnvironments?:('sandbox'|'preview'|'production')[]; approvedStepIds:string[]; schemaVersion:string }
export interface CapabilityRegistry { getCapability(id:string,version?:string): Capability|undefined; listCapabilities(): Capability[] }
export class StaticCapabilityRegistry implements CapabilityRegistry { private caps=new Map<string,Capability>(); constructor(caps:Capability[]){ for(const c of caps) this.caps.set(`${c.capabilityId}@${c.capabilityVersion}`,Object.freeze({...c,channels:{...c.channels},approvedOrigins:[...c.approvedOrigins],approvedStepIds:[...c.approvedStepIds]})) } getCapability(id:string,version?:string){ const vals=[...this.caps.values()].filter(c=>c.capabilityId===id&&(!version||c.capabilityVersion===version)); return vals[0] } listCapabilities(){ return [...this.caps.values()] } }
export interface ExecutionDecision { decisionId:string; workItemId:string; selectedChannel:ExecutionChannel; executionMode:ExecutionMode; decisionCode:ExecutionDecisionCode; apiFailureCategory?:ApiFailureCategory; browserReason?:BrowserReasonEvidence; capabilityId:string; capabilityVersion:string; policyVersion:string; riskClass:RiskClass; maturity:CapabilityMaturity; approvedStepIds:string[]; requiresHumanApproval:boolean; verificationProfileId?:string; ownerInstanceId:string; ownerRuntimeId:string; fencingToken:number; decidedAt:string; expiresAt:string; auditMetadata:Record<string,SerializableValue>; schemaVersion:string }
export interface SelectInput { workItemId:string; executionMode:ExecutionMode; capabilityId:string; capabilityVersion?:string; environment:'sandbox'|'preview'|'production'; apiAttempted:boolean; apiFailureCategory?:ApiFailureCategory; retryCount:number; maxRetries:number; browserReason?:BrowserReasonEvidence; ownerInstanceId:string; ownerRuntimeId:string; fencingToken:number; now:Date; decisionTtlMs?:number; flags?:{ captcha?:boolean; twoFactor?:boolean; credentialMutation?:boolean; billingAction?:boolean; ownershipOrPermissionChange?:boolean; irreversible?:boolean; unknownWorkflow?:boolean; productionBrowserExecutionEnabled?:boolean; browserRuntimeApprovalRequired?:boolean; continuationApprovalRequired?:boolean; hasIdempotencyKey?:boolean } }
function validReason(r?:BrowserReasonEvidence){ if(!r) return false; return browserReasons.includes(r.reason) }
function mk(input:SelectInput,cap:Capability,code:ExecutionDecisionCode,channel:ExecutionChannel,extra:Partial<ExecutionDecision>={}):ExecutionDecision{ const exp=new Date(input.now.getTime()+(input.decisionTtlMs??60000)); return {decisionId:`decision-${input.workItemId}-${input.fencingToken}-${code}`,workItemId:input.workItemId,selectedChannel:channel,executionMode:input.executionMode,decisionCode:code,apiFailureCategory:input.apiFailureCategory,browserReason:extra.browserReason,capabilityId:cap.capabilityId,capabilityVersion:cap.capabilityVersion,policyVersion:cap.policyVersion,riskClass:cap.riskClass,maturity:cap.maturity,approvedStepIds:[...cap.approvedStepIds],requiresHumanApproval:code==='require_human_approval'||cap.requiresHumanApproval,verificationProfileId:cap.verificationProfileId,ownerInstanceId:input.ownerInstanceId,ownerRuntimeId:input.ownerRuntimeId,fencingToken:input.fencingToken,decidedAt:input.now.toISOString(),expiresAt:exp.toISOString(),auditMetadata:{decisionCode:code,environment:input.environment},schemaVersion:'execution-channel-decision-v1'} }
export class ExecutionChannelSelector { private registry: CapabilityRegistry
 private activePolicyVersion: string
 constructor(registry:CapabilityRegistry, activePolicyVersion='ha-policy-v1'){ this.registry=registry; this.activePolicyVersion=activePolicyVersion } select(input:SelectInput):ExecutionDecision{ if(!executionModes.includes(input.executionMode)) throw new PolicyError('invalid_execution_mode','invalid execution mode'); if(input.apiFailureCategory&&!apiFailureCategories.includes(input.apiFailureCategory)) throw new PolicyError('invalid_api_failure','invalid api failure'); if(input.browserReason&&!validReason(input.browserReason)) throw new PolicyError('invalid_browser_reason','invalid browser reason'); const cap=this.registry.getCapability(input.capabilityId,input.capabilityVersion); if(!cap) throw new PolicyError('unknown_capability','unknown capability'); if(cap.policyVersion!==this.activePolicyVersion) return mk(input,cap,'block','none'); if(cap.suspendedReason||cap.maturity==='suspended'||cap.riskClass==='forbidden') return mk(input,cap,'block','none'); if(input.executionMode==='api_only'){ if(cap.channels.api&&!input.apiFailureCategory) return mk(input,cap,'use_api','api'); if(input.apiFailureCategory==='rate_limited'||input.apiFailureCategory==='timeout'||input.apiFailureCategory==='temporarily_unavailable') return mk(input,cap,'retry_api','api'); return mk(input,cap,cap.channels.manual?'use_manual_operator':'block',cap.channels.manual?'manual':'none') }
 if(input.executionMode==='browser_on_demand'){ if(!input.browserReason||input.browserReason.reason!=='human_requested') throw new PolicyError('invalid_browser_reason','browser on demand requires human_requested'); if(!cap.supportsBrowserOnDemand||!cap.channels.browser) return mk(input,cap,'require_human_approval','manual',{browserReason:input.browserReason}); if(input.environment==='production'&&!input.flags?.productionBrowserExecutionEnabled) return mk(input,cap,'require_human_approval','manual',{browserReason:input.browserReason}); if(cap.requiresHumanApproval||cap.riskClass==='medium'||cap.riskClass==='high') return mk(input,cap,'use_browser_with_guardrails','browser',{browserReason:input.browserReason}); return mk(input,cap,'use_browser_with_guardrails','browser',{browserReason:input.browserReason}) }
 if(!input.apiFailureCategory && cap.channels.api) return mk(input,cap,'use_api','api'); if(input.apiFailureCategory==='succeeded_verified') return mk(input,cap,'use_api','api'); if(input.apiFailureCategory==='rate_limited'||((input.apiFailureCategory==='timeout'||input.apiFailureCategory==='temporarily_unavailable')&&input.retryCount<input.maxRetries)) return mk(input,cap,'retry_api','api'); if(['authentication_failed','permission_denied','invalid_request','unknown_failure','permanent_failure','provider_outage'].includes(input.apiFailureCategory||'')) return mk(input,cap,'block','none'); const reason=input.browserReason; const eligibleFailure=input.apiFailureCategory==='capability_missing'||input.apiFailureCategory==='result_inconsistent'||((input.apiFailureCategory==='timeout'||input.apiFailureCategory==='temporarily_unavailable')&&input.retryCount>=input.maxRetries); if(!eligibleFailure||!reason) return mk(input,cap,'block','none'); const human=input.flags?.captcha||input.flags?.twoFactor||input.flags?.credentialMutation||input.flags?.billingAction||input.flags?.ownershipOrPermissionChange||input.flags?.irreversible||input.flags?.unknownWorkflow||cap.requiresHumanApproval||cap.riskClass==='medium'||cap.riskClass==='high'; if(human) return mk(input,cap,'require_human_approval','manual',{browserReason:reason}); const auto=cap.channels.browser&&cap.supportsAutoFailover&&cap.maturity==='auto_failover_ready'&&(cap.riskClass==='read_only'||cap.riskClass==='low_risk_reversible')&&cap.approvedOrigins.length>0&&!!cap.verificationProfileId&&!!cap.browserAdapterId&&(cap.allowedEnvironments??['sandbox','preview','production']).includes(input.environment); if(!auto) return mk(input,cap,cap.maturity==='experimental'||cap.maturity==='sandbox_verified'?'require_human_approval':'block',cap.channels.manual?'manual':'none',{browserReason:reason}); if(input.environment==='production'&&!input.flags?.productionBrowserExecutionEnabled) return mk(input,cap,'require_human_approval','manual',{browserReason:reason}); return mk(input,cap,'use_browser_automatically','browser',{browserReason:reason}) } }
export function classifyApiFailure(input:{ok?:boolean;verified?:boolean;status?:number;category?:string;capabilityMissing?:boolean;inconsistent?:boolean;timeout?:boolean}):ApiFailureCategory{ if(input.category&&apiFailureCategories.includes(input.category as ApiFailureCategory)) return input.category as ApiFailureCategory; if(input.ok) return input.verified?'succeeded_verified':'succeeded_unverified'; if(input.timeout) return 'timeout'; if(input.capabilityMissing) return 'capability_missing'; if(input.inconsistent) return 'result_inconsistent'; if(input.status===401) return 'authentication_failed'; if(input.status===403) return 'permission_denied'; if(input.status===400||input.status===422) return 'invalid_request'; if(input.status===429) return 'rate_limited'; if(input.status&&input.status>=500) return 'temporarily_unavailable'; return 'unknown_failure' }
