import { BPAL_SCHEMA_VERSION } from '../provider-version.ts'
const providerId='vercel', adapterVersion='vercel-browser-adapter-v1', capabilityVersion='vercel-browser-capabilities-v1'
export const vercelCapabilityIds=['read_deployment_status','inspect_deployment_failure','inspect_deployment_logs','inspect_domain_status','inspect_project_metadata','inspect_environment_variable_metadata','capture_dashboard_evidence','compare_dashboard_with_api'] as const
const all=[...vercelCapabilityIds]
export const vercelOrigins=[{originId:'vercel_dashboard',providerId,labelKey:'browserProvider.vercel.origins.dashboard',exactOrigin:'https://vercel.com',environments:['sandbox','preview'] as const,readOnlyAllowed:true,browserOnDemandAllowed:true,autoFailoverAllowed:false,productionAllowed:false,schemaVersion:BPAL_SCHEMA_VERSION}]
export const vercelNavigationProfiles=[
{navigationProfileId:'vercel_deployments',providerId,labelKey:'browserProvider.vercel.navigation.deployments',originId:'vercel_dashboard',routeTemplate:'/dashboard/:team/:project/deployments',requiredParameters:['team','project'],readOnly:true,supportedCapabilities:['read_deployment_status'],schemaVersion:BPAL_SCHEMA_VERSION},
{navigationProfileId:'vercel_deployment_details',providerId,labelKey:'browserProvider.vercel.navigation.deploymentDetails',originId:'vercel_dashboard',routeTemplate:'/dashboard/:team/:project/deployments/:deploymentId',requiredParameters:['team','project','deploymentId'],readOnly:true,supportedCapabilities:['inspect_deployment_failure','capture_dashboard_evidence','compare_dashboard_with_api'],schemaVersion:BPAL_SCHEMA_VERSION},
{navigationProfileId:'vercel_deployment_logs',providerId,labelKey:'browserProvider.vercel.navigation.logs',originId:'vercel_dashboard',routeTemplate:'/dashboard/:team/:project/deployments/:deploymentId/logs',requiredParameters:['team','project','deploymentId'],readOnly:true,supportedCapabilities:['inspect_deployment_logs'],schemaVersion:BPAL_SCHEMA_VERSION},
{navigationProfileId:'vercel_domains',providerId,labelKey:'browserProvider.vercel.navigation.domains',originId:'vercel_dashboard',routeTemplate:'/dashboard/:team/:project/settings/domains',requiredParameters:['team','project'],readOnly:true,supportedCapabilities:['inspect_domain_status'],schemaVersion:BPAL_SCHEMA_VERSION},
{navigationProfileId:'vercel_project_settings',providerId,labelKey:'browserProvider.vercel.navigation.projectSettings',originId:'vercel_dashboard',routeTemplate:'/dashboard/:team/:project/settings',requiredParameters:['team','project'],readOnly:true,supportedCapabilities:['inspect_project_metadata'],schemaVersion:BPAL_SCHEMA_VERSION},
{navigationProfileId:'vercel_environment_variables',providerId,labelKey:'browserProvider.vercel.navigation.environmentVariables',originId:'vercel_dashboard',routeTemplate:'/dashboard/:team/:project/settings/environment-variables',requiredParameters:['team','project'],readOnly:true,supportedCapabilities:['inspect_environment_variable_metadata'],schemaVersion:BPAL_SCHEMA_VERSION}]
const verificationRows: readonly (readonly [string, 'ready'|'failed'|'visible'|'configured'|'issue_visible'|'matches_api'|'differs_from_api', readonly string[]])[] = [
['deployment_ready','ready',['read_deployment_status']],['deployment_failed','failed',['inspect_deployment_failure']],['deployment_status_visible','visible',['read_deployment_status']],['domain_configured','configured',['inspect_domain_status']],['domain_issue_visible','issue_visible',['inspect_domain_status']],['project_metadata_visible','visible',['inspect_project_metadata']],['environment_metadata_visible','visible',['inspect_environment_variable_metadata']],['dashboard_matches_api','matches_api',['compare_dashboard_with_api']],['dashboard_differs_from_api','differs_from_api',['compare_dashboard_with_api']]
]
export const vercelVerificationProfiles=verificationRows.map(([verificationProfileId,expectedStateCategory,supportedCapabilities])=>({verificationProfileId,providerId,requiredReads:['api_state','dashboard_state'],expectedStateCategory,requiredEvidenceTypes:['metadata'],deterministicComparisonRules:['exact_status_match','redacted_metadata_only'],supportedCapabilities,schemaVersion:BPAL_SCHEMA_VERSION} as const))
export const vercelEvidenceProfiles=['deployment_failure','deployment_success','deployment_overview','deployment_logs','domain_status','project_metadata','environment_metadata','dashboard_api_comparison'].map(evidenceProfileId=>({evidenceProfileId,providerId,requiredScreenshots:[`${evidenceProfileId}_screenshot`],requiredReads:[`${evidenceProfileId}_read`],requiredMetadata:['providerId','capturedAt','redactionPolicy'],sensitiveFieldPolicy:'redact',supportedCapabilities:all,schemaVersion:BPAL_SCHEMA_VERSION} as const))
export const vercelSelectors=[
{selectorId:'vercel_projects_title',providerId,area:'projects',targetType:'text',selector:{strategy:'role',role:'heading',name:'Projects'},readOnly:true,supportedCapabilities:all,adapterVersion,schemaVersion:BPAL_SCHEMA_VERSION},
{selectorId:'vercel_deployments_status',providerId,area:'deployments',targetType:'status',selector:{strategy:'testId',testId:'deployment-status'},readOnly:true,supportedCapabilities:all,adapterVersion,schemaVersion:BPAL_SCHEMA_VERSION},
{selectorId:'vercel_deployment_details_status',providerId,area:'deploymentDetails',targetType:'status',selector:{strategy:'testId',testId:'deployment-detail-status'},readOnly:true,supportedCapabilities:all,adapterVersion,schemaVersion:BPAL_SCHEMA_VERSION},
{selectorId:'vercel_logs_output',providerId,area:'logs',targetType:'panel',selector:{strategy:'testId',testId:'deployment-logs'},readOnly:true,supportedCapabilities:all,adapterVersion,schemaVersion:BPAL_SCHEMA_VERSION},
{selectorId:'vercel_domains_status',providerId,area:'domains',targetType:'status',selector:{strategy:'testId',testId:'domain-status'},readOnly:true,supportedCapabilities:all,adapterVersion,schemaVersion:BPAL_SCHEMA_VERSION},
{selectorId:'vercel_settings_project_name',providerId,area:'settings',targetType:'metadata',selector:{strategy:'label',label:'Project Name'},readOnly:true,supportedCapabilities:all,adapterVersion,schemaVersion:BPAL_SCHEMA_VERSION},
{selectorId:'vercel_environment_variables_table',providerId,area:'environmentVariables',targetType:'table',selector:{strategy:'testId',testId:'env-vars-table'},readOnly:true,supportedCapabilities:all,adapterVersion,schemaVersion:BPAL_SCHEMA_VERSION},
{selectorId:'vercel_authentication_login_form',providerId,area:'authentication',targetType:'form',selector:{strategy:'role',role:'form',name:'Log in'},readOnly:true,supportedCapabilities:all,adapterVersion,schemaVersion:BPAL_SCHEMA_VERSION},
{selectorId:'vercel_dashboard_shell',providerId,area:'dashboard',targetType:'panel',selector:{strategy:'testId',testId:'dashboard-shell'},readOnly:true,supportedCapabilities:all,adapterVersion,schemaVersion:BPAL_SCHEMA_VERSION}
] as const
const profile=(id:string)=> id.includes('logs')?'deployment_logs':id.includes('failure')?'deployment_failure':id.includes('domain')?'domain_status':id.includes('project')?'project_metadata':id.includes('environment')?'environment_metadata':id.includes('compare')?'dashboard_api_comparison':id.includes('capture')?'deployment_overview':'deployment_success'
const verification=(id:string)=> id.includes('failure')?'deployment_failed':id.includes('domain')?'domain_configured':id.includes('project')?'project_metadata_visible':id.includes('environment')?'environment_metadata_visible':id.includes('compare')?'dashboard_matches_api':'deployment_status_visible'
const nav=(id:string)=> id.includes('logs')?'vercel_deployment_logs':id.includes('domain')?'vercel_domains':id.includes('project')?'vercel_project_settings':id.includes('environment')?'vercel_environment_variables':id.includes('failure')||id.includes('capture')||id.includes('compare')?'vercel_deployment_details':'vercel_deployments'
export const vercelCapabilities=vercelCapabilityIds.map(capabilityId=>({capabilityId,providerId,operation:capabilityId,displayNameKey:`browserProvider.vercel.capabilities.${capabilityId}.name`,descriptionKey:`browserProvider.vercel.capabilities.${capabilityId}.description`,riskClass:'read_only',maturity:'sandbox_verified',readOnly:true,supportsApi:capabilityId==='compare_dashboard_with_api',supportsBrowser:true,supportsAutoFailover:false,supportsBrowserOnDemand:true,requiresHumanApproval:true,reversible:true,idempotent:true,allowedOriginIds:['vercel_dashboard'],navigationProfileId:nav(capabilityId),verificationProfileId:verification(capabilityId),evidenceProfileId:profile(capabilityId),adapterVersion,capabilityVersion,policyVersion:'ha-policy-v1',schemaVersion:BPAL_SCHEMA_VERSION} as const))
export const vercelVersion={adapterVersion,capabilityVersion,schemaVersion:BPAL_SCHEMA_VERSION,updatedAt:'2026-07-16T00:00:00.000Z'} as const
