import { redirect } from 'next/navigation'
import { cookies } from 'next/headers'
import { getAccess } from '@/lib/auth/access'
import { getCurrentUser } from '@/utils/supabase/server'
import { defaultApprovalQueueStore } from '@/lib/supervisor/approvals'
import en from '@/locales/en.json'; import es from '@/locales/es.json'; import pt from '@/locales/pt.json'; import pl from '@/locales/pl.json'; import ru from '@/locales/ru.json'
const dicts = { en, es, pt, pl, ru } as const
function pickLocale(v?: string) { const l=String(v||'en').slice(0,2).toLowerCase(); return (l in dicts ? l : 'en') as keyof typeof dicts }
export default async function SupervisorApprovalsPage() { const user=await getCurrentUser(); const access=await getAccess(); if(!user) redirect('/login'); const locale=pickLocale((await cookies()).get('sb_locale')?.value); const t=(dicts[locale] as any).supervisorApprovals; if(!access.isAdmin) return <main style={page}><h1>{t.approvalQueue}</h1><p>{t.sessionNoLongerAvailable}</p></main>; const items=(await defaultApprovalQueueStore.listPendingRequests()).filter(i=>i.environment==='sandbox'); return <main style={page}><section style={panel}><p style={kicker}>{t.sandboxExecution}</p><h1>{t.approvalQueue}</h1><p style={muted}>{t.pendingApproval}</p>{items.length===0?<p style={muted}>{t.noPendingApprovals}</p>:<div style={{display:'grid',gap:16}}>{items.map(item=><article key={item.executionId} style={card}><div style={{display:'flex',justifyContent:'space-between',gap:12,flexWrap:'wrap'}}><div><p style={kicker}>{t.pendingApproval}</p><h2 style={{margin:'4px 0'}}>{t.executionId}: <code>{item.executionId}</code></h2></div><span style={badge}>{t.sandboxExecution}</span></div><dl style={grid}><Field k={t.provider} v={item.provider}/><Field k={t.targetOrigin} v={item.targetOrigin}/><Field k={t.checkpointReached} v={item.checkpointId}/><Field k={t.expires} v={item.expiresAt}/><Field k={t.approvalStatus} v={item.status}/></dl><h3>{t.remainingSteps}</h3><ul>{item.protectedStepSummaries.map(s=><li key={s.stepId}><strong>{s.stepId}</strong> — {s.summary}<br/><span style={muted}>{t.expectedResult}: {s.expectedResult || '—'} · {t.verificationRequirements}: {s.verificationRequirement || '—'} · {t.riskLevel}: {s.riskLevel || '—'}</span></li>)}</ul><h3>{t.evidence}</h3><ul>{item.evidenceReferences.map(e=><li key={e.evidenceId}>{e.kind}: {e.summary || e.artifactReference || e.evidenceId}</li>)}</ul><form action={`/api/internal/supervisor/approvals/${encodeURIComponent(item.executionId)}/approve`} method="post" style={{display:'inline-block',marginRight:8}}><button style={primary}>{t.approve}</button></form><form action={`/api/internal/supervisor/approvals/${encodeURIComponent(item.executionId)}/reject`} method="post" style={{display:'inline-block'}}><input type="hidden" name="reasonCode" value="operator_rejected"/><button style={secondary}>{t.reject}</button></form></article>)}</div>}</section></main> }
function Field({k,v}:{k:string;v:string}){return <div><dt style={muted}>{k}</dt><dd style={{margin:0,wordBreak:'break-all'}}>{v}</dd></div>}
const page={minHeight:'100vh',padding:32,color:'#fff',background:'linear-gradient(135deg,#06111f,#05070c)'}
const panel={border:'1px solid rgba(255,255,255,.12)',borderRadius:24,padding:24,background:'rgba(255,255,255,.06)'}
const card={border:'1px solid rgba(255,255,255,.12)',borderRadius:18,padding:18,background:'rgba(0,0,0,.24)'}
const grid={display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(220px,1fr))',gap:12}
const muted={color:'rgba(255,255,255,.68)'}
const kicker={color:'#1af0ff',fontWeight:800,textTransform:'uppercase' as const,letterSpacing:1}
const badge={border:'1px solid rgba(26,240,255,.35)',borderRadius:999,padding:'6px 10px',color:'#1af0ff'}
const primary={background:'#ffc300',border:0,borderRadius:999,padding:'10px 16px',fontWeight:800}
const secondary={background:'transparent',border:'1px solid rgba(255,255,255,.3)',borderRadius:999,padding:'10px 16px',color:'#fff',fontWeight:800}
