import type { SupabaseClient } from '@supabase/supabase-js'
import { SupervisorValidationError } from '../errors.ts'
import { fingerprintDecision, fingerprintPolicyBinding, fingerprintRepairPlan } from './fingerprints.ts'
import { decisionEnvelopeSchema, missionSchema, policyDecisionBindingSchema, type DecisionEnvelope, type Mission, type PolicyDecisionBinding } from './models.ts'

export type MissionManualReviewStatus = 'routed'
export interface MissionManualReview { reviewId: string; missionId: string; missionRevision: number; decisionId: string; decisionFingerprint: string; planFingerprint: string; bindingFingerprint: string; status: MissionManualReviewStatus; title: string; summary: string; createdAt: string; routedAt: string; schemaVersion: string }
export interface RouteManualReviewInput { reviewId: string; decision: DecisionEnvelope; binding: PolicyDecisionBinding; title: string; summary: string; routedAt: string; schemaVersion: string }
export interface MissionManualReviewListInput { status?: MissionManualReviewStatus; missionId?: string; limit: number; cursor?: string }
export interface MissionManualReviewDiagnostics { total: number; routed: number; oldestRoutedAt?: string; newestRoutedAt?: string; duplicateRoutesPrevented?: number }
export interface MissionManualReviewStore { route(input: RouteManualReviewInput): Promise<MissionManualReview>; get(reviewId: string): Promise<MissionManualReview | null>; list(input: MissionManualReviewListInput): Promise<{ items: MissionManualReview[]; nextCursor?: string }>; diagnostics(): Promise<MissionManualReviewDiagnostics> }
type MissionReader = { get(missionId: string): Promise<Mission | null> }
const copy = <T>(value: T): T => JSON.parse(JSON.stringify(value)) as T
const nonEmpty = (value: string, field: string) => { if (!value?.trim()) throw new SupervisorValidationError(`${field} must be a non-empty string`); return value }
const reviewColumns = 'review_id,mission_id,mission_revision,decision_id,decision_fingerprint,plan_fingerprint,binding_fingerprint,status,title,summary,created_at,routed_at,schema_version'
const toReview = (row: any): MissionManualReview => ({ reviewId:nonEmpty(row.review_id,'review_id'), missionId:nonEmpty(row.mission_id,'mission_id'), missionRevision:Number(row.mission_revision), decisionId:nonEmpty(row.decision_id,'decision_id'), decisionFingerprint:nonEmpty(row.decision_fingerprint,'decision_fingerprint'), planFingerprint:nonEmpty(row.plan_fingerprint,'plan_fingerprint'), bindingFingerprint:nonEmpty(row.binding_fingerprint,'binding_fingerprint'), status:row.status, title:nonEmpty(row.title,'title'), summary:nonEmpty(row.summary,'summary'), createdAt:nonEmpty(row.created_at,'created_at'), routedAt:nonEmpty(row.routed_at,'routed_at'), schemaVersion:nonEmpty(row.schema_version,'schema_version') })
export const missionManualReviewCursor = {
  encode(review: Pick<MissionManualReview, 'createdAt' | 'reviewId'>): string { return Buffer.from(JSON.stringify({ createdAt: review.createdAt, reviewId: review.reviewId })).toString('base64url') },
  decode(cursor: string): { createdAt: string; reviewId: string } { try { const parsed=JSON.parse(Buffer.from(cursor,'base64url').toString('utf8')); if (!parsed || typeof parsed.createdAt!=='string' || !Number.isFinite(Date.parse(parsed.createdAt)) || typeof parsed.reviewId!=='string' || !/^[A-Za-z0-9][A-Za-z0-9._:-]{0,199}$/.test(parsed.reviewId)) throw new Error('invalid'); return parsed } catch { throw new SupervisorValidationError('invalid_manual_review_cursor') } },
}
function validateListInput(input: MissionManualReviewListInput): void { if (!Number.isInteger(input.limit) || input.limit < 1 || input.limit > 100) throw new SupervisorValidationError('invalid_manual_review_limit'); if (input.status && input.status !== 'routed') throw new SupervisorValidationError('invalid_manual_review_status'); if (input.cursor) missionManualReviewCursor.decode(input.cursor) }
function parseRouteInput(input: RouteManualReviewInput): RouteManualReviewInput {
 const decision=decisionEnvelopeSchema.parse(input.decision), binding=policyDecisionBindingSchema.parse(input.binding)
 nonEmpty(input.reviewId,'reviewId'); nonEmpty(input.title,'title'); nonEmpty(input.summary,'summary'); nonEmpty(input.schemaVersion,'schemaVersion'); nonEmpty(input.routedAt,'routedAt')
 if (binding.policyOutcome !== 'approved' || decision.externalSideEffect !== false) throw new SupervisorValidationError('manual_review_not_approved')
 if (binding.decisionId !== decision.decisionId || binding.missionId !== decision.missionId || binding.missionRevision !== decision.missionRevision || binding.decisionFingerprint !== decision.decisionFingerprint || binding.planFingerprint !== decision.planFingerprint) throw new SupervisorValidationError('manual_review_binding_mismatch')
 return { ...input, decision, binding }
}
function validate(input: RouteManualReviewInput, mission: Mission, now: string): void {
 const { decision, binding }=parseRouteInput(input); missionSchema.parse(mission)
 if(mission.missionId!==decision.missionId||mission.revision!==decision.missionRevision) throw new SupervisorValidationError('stale_or_missing_mission')
 if(['COMPLETED','CANCELED','FAILED','BLOCKED'].includes(mission.status)) throw new SupervisorValidationError('mission_not_eligible')
 if(Date.parse(decision.expiresAt)<=Date.parse(now)||Date.parse(binding.expiresAt)<=Date.parse(now)) throw new SupervisorValidationError('manual_review_authorization_expired')
 if(binding.policyOutcome!=='approved'||decision.externalSideEffect!==false) throw new SupervisorValidationError('manual_review_not_approved')
 if(binding.decisionId!==decision.decisionId||binding.missionId!==decision.missionId||binding.missionRevision!==decision.missionRevision||binding.decisionFingerprint!==decision.decisionFingerprint||binding.planFingerprint!==decision.planFingerprint) throw new SupervisorValidationError('manual_review_binding_mismatch')
 if(decision.planFingerprint!==fingerprintRepairPlan({missionId:decision.missionId,missionRevision:decision.missionRevision,decisionId:decision.decisionId,environment:decision.targetEnvironment,actionType:decision.actionType,plan:decision.repairPlan})||decision.decisionFingerprint!==fingerprintDecision(decision)) throw new SupervisorValidationError('manual_review_decision_fingerprint_mismatch')
 const base={decisionId:binding.decisionId,missionId:binding.missionId,missionRevision:binding.missionRevision,decisionFingerprint:binding.decisionFingerprint,planFingerprint:binding.planFingerprint,policyVersion:binding.policyVersion,policyOutcome:binding.policyOutcome,approvedStepIds:binding.approvedStepIds,evaluatedAt:binding.evaluatedAt,expiresAt:binding.expiresAt,schemaVersion:binding.schemaVersion}
 if(binding.bindingFingerprint!==fingerprintPolicyBinding(base)) throw new SupervisorValidationError('manual_review_binding_fingerprint_mismatch')
}
export class InMemoryMissionManualReviewStore implements MissionManualReviewStore { private readonly reviews=new Map<string,MissionManualReview>(); private readonly byBinding=new Map<string,string>(); private readonly byDecisionRevision=new Map<string,string>(); constructor(private readonly missions:MissionReader,private readonly now:()=>string=()=>new Date().toISOString()) {} async route(input:RouteManualReviewInput){const existing=this.byBinding.get(input.binding.bindingFingerprint)??this.byDecisionRevision.get(`${input.decision.decisionId}:${input.decision.missionRevision}`);if(existing)return copy(this.reviews.get(existing)!);const mission=await this.missions.get(input.decision.missionId);if(!mission)throw new SupervisorValidationError('stale_or_missing_mission');validate(input,mission,this.now());const raced=this.byBinding.get(input.binding.bindingFingerprint)??this.byDecisionRevision.get(`${input.decision.decisionId}:${input.decision.missionRevision}`);if(raced)return copy(this.reviews.get(raced)!);const review:MissionManualReview={reviewId:input.reviewId,missionId:input.decision.missionId,missionRevision:input.decision.missionRevision,decisionId:input.decision.decisionId,decisionFingerprint:input.decision.decisionFingerprint,planFingerprint:input.decision.planFingerprint,bindingFingerprint:input.binding.bindingFingerprint,status:'routed',title:input.title,summary:input.summary,createdAt:input.routedAt,routedAt:input.routedAt,schemaVersion:input.schemaVersion};this.reviews.set(review.reviewId,copy(review));this.byBinding.set(review.bindingFingerprint,review.reviewId);this.byDecisionRevision.set(`${review.decisionId}:${review.missionRevision}`,review.reviewId);return copy(review)} async get(reviewId:string){const review=this.reviews.get(reviewId);return review?copy(review):null} async list(input:MissionManualReviewListInput){validateListInput(input);const cursor=input.cursor?missionManualReviewCursor.decode(input.cursor):undefined;const items=[...this.reviews.values()].filter(review=>(!input.status||review.status===input.status)&&(!input.missionId||review.missionId===input.missionId)).sort((a,b)=>b.createdAt.localeCompare(a.createdAt)||b.reviewId.localeCompare(a.reviewId)).filter(review=>!cursor||review.createdAt<cursor.createdAt||(review.createdAt===cursor.createdAt&&review.reviewId<cursor.reviewId)).slice(0,input.limit);return {items:copy(items),nextCursor:items.length===input.limit?missionManualReviewCursor.encode(items[items.length-1]):undefined}} async diagnostics(){const routed=[...this.reviews.values()].filter(review=>review.status==='routed').sort((a,b)=>a.routedAt.localeCompare(b.routedAt));return {total:this.reviews.size,routed:routed.length,...(routed.length?{oldestRoutedAt:routed[0].routedAt,newestRoutedAt:routed.at(-1)!.routedAt}: {})}} }
type Db=SupabaseClient<any,any,any>
export class SupabaseMissionManualReviewStore implements MissionManualReviewStore { constructor(private readonly db:Db) {} async route(input:RouteManualReviewInput){const parsed=parseRouteInput(input);const {data,error}=await this.db.rpc('mission_route_manual_review',{p_review_id:parsed.reviewId,p_mission_id:parsed.decision.missionId,p_mission_revision:parsed.decision.missionRevision,p_decision_id:parsed.decision.decisionId,p_decision_fingerprint:parsed.decision.decisionFingerprint,p_plan_fingerprint:parsed.decision.planFingerprint,p_binding_fingerprint:parsed.binding.bindingFingerprint,p_title:parsed.title,p_summary:parsed.summary,p_routed_at:parsed.routedAt,p_schema_version:parsed.schemaVersion,p_decision:parsed.decision,p_binding:parsed.binding});if(error)throw new SupervisorValidationError(error.message);const row=Array.isArray(data)?data[0]:data;if(!row)throw new SupervisorValidationError('manual_review_route_missing');return toReview(row)} async get(reviewId:string){const {data,error}=await this.db.from('mission_manual_reviews').select(reviewColumns).eq('review_id',reviewId).maybeSingle();if(error)throw new SupervisorValidationError(error.message);return data?toReview(data):null} async list(input:MissionManualReviewListInput){validateListInput(input);const cursor=input.cursor?missionManualReviewCursor.decode(input.cursor):undefined;let query=this.db.from('mission_manual_reviews').select(reviewColumns).order('created_at',{ascending:false}).order('review_id',{ascending:false}).limit(input.limit);if(input.status)query=query.eq('status',input.status);if(input.missionId)query=query.eq('mission_id',input.missionId);if(cursor)query=query.or(`created_at.lt.${cursor.createdAt},and(created_at.eq.${cursor.createdAt},review_id.lt.${cursor.reviewId})`);const {data,error}=await query;if(error)throw new SupervisorValidationError(error.message);const items=(data??[]).map(toReview);return {items,nextCursor:items.length===input.limit?missionManualReviewCursor.encode(items[items.length-1]):undefined}} async diagnostics(){const total=await this.db.from('mission_manual_reviews').select('review_id',{count:'exact',head:true});const routed=await this.db.from('mission_manual_reviews').select('review_id',{count:'exact',head:true}).eq('status','routed');const oldest=await this.db.from('mission_manual_reviews').select('routed_at').eq('status','routed').order('routed_at',{ascending:true}).limit(1).maybeSingle();const newest=await this.db.from('mission_manual_reviews').select('routed_at').eq('status','routed').order('routed_at',{ascending:false}).limit(1).maybeSingle();for(const result of [total,routed,oldest,newest])if(result.error)throw new SupervisorValidationError(result.error.message);return {total:total.count??0,routed:routed.count??0,...(oldest.data?.routed_at?{oldestRoutedAt:oldest.data.routed_at}:{}),...(newest.data?.routed_at?{newestRoutedAt:newest.data.routed_at}:{})}} }
