import type { SupabaseClient } from '@supabase/supabase-js'
import { SupervisorValidationError } from '../errors.ts'
import { fingerprintDecision, fingerprintPolicyBinding, fingerprintRepairPlan } from './fingerprints.ts'
import { decisionEnvelopeSchema, missionSchema, policyDecisionBindingSchema, type DecisionEnvelope, type Mission, type PolicyDecisionBinding } from './models.ts'

export interface MissionManualReview { reviewId: string; missionId: string; missionRevision: number; decisionId: string; decisionFingerprint: string; planFingerprint: string; bindingFingerprint: string; status: 'routed'; title: string; summary: string; createdAt: string; routedAt: string; schemaVersion: string }
export interface RouteManualReviewInput { reviewId: string; decision: DecisionEnvelope; binding: PolicyDecisionBinding; title: string; summary: string; routedAt: string; schemaVersion: string }
export interface MissionManualReviewStore { route(input: RouteManualReviewInput): Promise<MissionManualReview>; get(reviewId: string): Promise<MissionManualReview | null> }
type MissionReader = { get(missionId: string): Promise<Mission | null> }
const copy = <T>(value: T): T => JSON.parse(JSON.stringify(value)) as T
const nonEmpty = (value: string, field: string) => { if (!value?.trim()) throw new SupervisorValidationError(`${field} must be a non-empty string`); return value }
const toReview = (row: any): MissionManualReview => ({ reviewId:nonEmpty(row.review_id,'review_id'), missionId:nonEmpty(row.mission_id,'mission_id'), missionRevision:Number(row.mission_revision), decisionId:nonEmpty(row.decision_id,'decision_id'), decisionFingerprint:nonEmpty(row.decision_fingerprint,'decision_fingerprint'), planFingerprint:nonEmpty(row.plan_fingerprint,'plan_fingerprint'), bindingFingerprint:nonEmpty(row.binding_fingerprint,'binding_fingerprint'), status:row.status, title:nonEmpty(row.title,'title'), summary:nonEmpty(row.summary,'summary'), createdAt:nonEmpty(row.created_at,'created_at'), routedAt:nonEmpty(row.routed_at,'routed_at'), schemaVersion:nonEmpty(row.schema_version,'schema_version') })
function validate(input: RouteManualReviewInput, mission: Mission, now: string): void {
 const decision=decisionEnvelopeSchema.parse(input.decision), binding=policyDecisionBindingSchema.parse(input.binding); missionSchema.parse(mission)
 nonEmpty(input.reviewId,'reviewId'); nonEmpty(input.title,'title'); nonEmpty(input.summary,'summary'); nonEmpty(input.schemaVersion,'schemaVersion')
 if(mission.missionId!==decision.missionId||mission.revision!==decision.missionRevision) throw new SupervisorValidationError('stale_or_missing_mission')
 if(['COMPLETED','CANCELED','FAILED','BLOCKED'].includes(mission.status)) throw new SupervisorValidationError('mission_not_eligible')
 if(Date.parse(decision.expiresAt)<=Date.parse(now)||Date.parse(binding.expiresAt)<=Date.parse(now)) throw new SupervisorValidationError('manual_review_authorization_expired')
 if(binding.policyOutcome!=='approved'||decision.externalSideEffect!==false) throw new SupervisorValidationError('manual_review_not_approved')
 if(binding.decisionId!==decision.decisionId||binding.missionId!==decision.missionId||binding.missionRevision!==decision.missionRevision||binding.decisionFingerprint!==decision.decisionFingerprint||binding.planFingerprint!==decision.planFingerprint) throw new SupervisorValidationError('manual_review_binding_mismatch')
 if(decision.planFingerprint!==fingerprintRepairPlan({missionId:decision.missionId,missionRevision:decision.missionRevision,decisionId:decision.decisionId,environment:decision.targetEnvironment,actionType:decision.actionType,plan:decision.repairPlan})||decision.decisionFingerprint!==fingerprintDecision(decision)) throw new SupervisorValidationError('manual_review_decision_fingerprint_mismatch')
 const base={decisionId:binding.decisionId,missionId:binding.missionId,missionRevision:binding.missionRevision,decisionFingerprint:binding.decisionFingerprint,planFingerprint:binding.planFingerprint,policyVersion:binding.policyVersion,policyOutcome:binding.policyOutcome,approvedStepIds:binding.approvedStepIds,evaluatedAt:binding.evaluatedAt,expiresAt:binding.expiresAt,schemaVersion:binding.schemaVersion}
 if(binding.bindingFingerprint!==fingerprintPolicyBinding(base)) throw new SupervisorValidationError('manual_review_binding_fingerprint_mismatch')
}
export class InMemoryMissionManualReviewStore implements MissionManualReviewStore { private readonly reviews=new Map<string,MissionManualReview>(); private readonly byBinding=new Map<string,string>(); private readonly byDecisionRevision=new Map<string,string>(); constructor(private readonly missions:MissionReader,private readonly now:()=>string=()=>new Date().toISOString()) {} async route(input:RouteManualReviewInput){const existing=this.byBinding.get(input.binding.bindingFingerprint)??this.byDecisionRevision.get(`${input.decision.decisionId}:${input.decision.missionRevision}`);if(existing)return copy(this.reviews.get(existing)!);const mission=await this.missions.get(input.decision.missionId);if(!mission)throw new SupervisorValidationError('stale_or_missing_mission');validate(input,mission,this.now());const raced=this.byBinding.get(input.binding.bindingFingerprint)??this.byDecisionRevision.get(`${input.decision.decisionId}:${input.decision.missionRevision}`);if(raced)return copy(this.reviews.get(raced)!);const review:MissionManualReview={reviewId:input.reviewId,missionId:input.decision.missionId,missionRevision:input.decision.missionRevision,decisionId:input.decision.decisionId,decisionFingerprint:input.decision.decisionFingerprint,planFingerprint:input.decision.planFingerprint,bindingFingerprint:input.binding.bindingFingerprint,status:'routed',title:input.title,summary:input.summary,createdAt:input.routedAt,routedAt:input.routedAt,schemaVersion:input.schemaVersion};this.reviews.set(review.reviewId,copy(review));this.byBinding.set(review.bindingFingerprint,review.reviewId);this.byDecisionRevision.set(`${review.decisionId}:${review.missionRevision}`,review.reviewId);return copy(review)} async get(reviewId:string){const review=this.reviews.get(reviewId);return review?copy(review):null} }
type Db=SupabaseClient<any,any,any>
export class SupabaseMissionManualReviewStore implements MissionManualReviewStore { constructor(private readonly db:Db) {} async route(input:RouteManualReviewInput){const {data,error}=await this.db.rpc('mission_route_manual_review',{p_review_id:input.reviewId,p_mission_id:input.decision.missionId,p_mission_revision:input.decision.missionRevision,p_decision_id:input.decision.decisionId,p_decision_fingerprint:input.decision.decisionFingerprint,p_plan_fingerprint:input.decision.planFingerprint,p_binding_fingerprint:input.binding.bindingFingerprint,p_title:input.title,p_summary:input.summary,p_routed_at:input.routedAt,p_schema_version:input.schemaVersion,p_decision:input.decision,p_binding:input.binding});if(error)throw new SupervisorValidationError(error.message);return toReview(Array.isArray(data)?data[0]:data)} async get(reviewId:string){const {data,error}=await this.db.from('mission_manual_reviews').select('*').eq('review_id',reviewId).maybeSingle();if(error)throw new SupervisorValidationError(error.message);return data?toReview(data):null} }
