import { SupervisorValidationError } from '../errors.ts'
import { isPlainSerializable, type SerializableValue, supervisorEnvironments } from '../incident-schema.ts'

export const missionStatuses = ['NEW', 'IN_PROGRESS', 'PAUSED', 'COMPLETED', 'FAILED', 'BLOCKED', 'CANCELED'] as const
export type MissionStatus = (typeof missionStatuses)[number]
export type MissionEnvironment = (typeof supervisorEnvironments)[number]
export type MissionRiskLevel = 'low' | 'medium' | 'high' | 'critical'

export interface Mission { missionId: string; missionType: string; revision: number; status: MissionStatus; environment: MissionEnvironment; title: string; objective: string; correlationId: string; sourceEventIds: string[]; riskLevel: MissionRiskLevel; createdAt: string; updatedAt: string; metadata: Record<string, SerializableValue>; schemaVersion: string }
export interface MissionEvent { eventId: string; eventType: 'ci.failure.detected'; occurredAt: string; correlationId: string; environment: MissionEnvironment; payload: Record<string, SerializableValue>; schemaVersion: string }
export interface DecisionEnvelope { decisionId: string; missionId: string; missionRevision: number; actionType: 'route_to_manual_review'; riskLevel: 'low'; targetProvider: null; targetEnvironment: MissionEnvironment; proposedAction: string; shellCommand: null; url: null; credentials: null; externalSideEffect: false; createdAt: string; schemaVersion: string }
export interface GuardrailOutcome { outcomeId: string; missionId: string; decisionId: string; missionRevision: number; status: 'approved' | 'approval_required' | 'blocked'; reasons: string[]; evaluatedAt: string; policyVersion: string; schemaVersion: string }
export interface ExecutionFeedback { feedbackId: string; missionId: string; decisionId: string; missionRevision: number; status: 'manual_review_routed'; recordedAt: string; schemaVersion: string }

const secretKey = /(password|api[_-]?key|token|secret|private[_-]?key|access[_-]?token|credential)/i
const secretValue = /(bearer\s+\S+|(?:sk|ghp|xoxb)_[A-Za-z0-9_-]{8,}|-----BEGIN)/i
function string(v: unknown, p: string) { if (typeof v !== 'string' || !v.trim()) throw new SupervisorValidationError(`${p} must be a non-empty string`); return v }
function timestamp(v: unknown, p: string) { const s = string(v, p); if (Number.isNaN(Date.parse(s))) throw new SupervisorValidationError(`${p} must be a valid date string`); return s }
function plainMetadata(v: unknown, p: string): Record<string, SerializableValue> { if (!v || typeof v !== 'object' || Array.isArray(v) || !isPlainSerializable(v)) throw new SupervisorValidationError(`${p} must be a plain serializable object`); scan(v, p); return v as Record<string, SerializableValue> }
function scan(v: unknown, p: string): void { if (typeof v === 'string' && secretValue.test(v)) throw new SupervisorValidationError(`${p} must not contain plaintext secret material`); if (Array.isArray(v)) return v.forEach((x, i) => scan(x, `${p}[${i}]`)); if (v && typeof v === 'object') for (const [k, x] of Object.entries(v as Record<string, unknown>)) { if (secretKey.test(k) && !k.endsWith('Ref')) throw new SupervisorValidationError(`${p}.${k} must not contain plaintext secret material`); scan(x, `${p}.${k}`) } }
function object(v: unknown, p: string) { if (!v || typeof v !== 'object' || Array.isArray(v) || Object.getPrototypeOf(v) !== Object.prototype) throw new SupervisorValidationError(`${p} must be a plain object`); return v as Record<string, unknown> }

export const missionSchema = { parse(candidate: unknown): Mission { const x=object(candidate,'mission'); const source=x.sourceEventIds; if (!Array.isArray(source)||!source.length) throw new SupervisorValidationError('sourceEventIds must be a non-empty array'); const mission: Mission={missionId:string(x.missionId,'missionId'),missionType:string(x.missionType,'missionType'),revision:x.revision as number,status:x.status as MissionStatus,environment:x.environment as MissionEnvironment,title:string(x.title,'title'),objective:string(x.objective,'objective'),correlationId:string(x.correlationId,'correlationId'),sourceEventIds:source.map((v,i)=>string(v,`sourceEventIds[${i}]`)),riskLevel:x.riskLevel as MissionRiskLevel,createdAt:timestamp(x.createdAt,'createdAt'),updatedAt:timestamp(x.updatedAt,'updatedAt'),metadata:plainMetadata(x.metadata,'metadata'),schemaVersion:string(x.schemaVersion,'schemaVersion')}; if(!Number.isInteger(mission.revision)||mission.revision<1) throw new SupervisorValidationError('revision must be a positive integer'); if(!missionStatuses.includes(mission.status)) throw new SupervisorValidationError('status is not supported'); if(!supervisorEnvironments.includes(mission.environment)) throw new SupervisorValidationError('environment is not supported'); if(!['low','medium','high','critical'].includes(mission.riskLevel)) throw new SupervisorValidationError('riskLevel is not supported'); return mission } }
export const missionEventSchema = { parse(candidate: unknown): MissionEvent { const x=object(candidate,'mission event'); const event:MissionEvent={eventId:string(x.eventId,'eventId'),eventType:x.eventType as MissionEvent['eventType'],occurredAt:timestamp(x.occurredAt,'occurredAt'),correlationId:string(x.correlationId,'correlationId'),environment:x.environment as MissionEnvironment,payload:plainMetadata(x.payload,'payload'),schemaVersion:string(x.schemaVersion,'schemaVersion')}; if(event.eventType!=='ci.failure.detected') throw new SupervisorValidationError('eventType is not supported'); if(!supervisorEnvironments.includes(event.environment)) throw new SupervisorValidationError('environment is not supported'); return event } }
export const decisionEnvelopeSchema = { parse(candidate: unknown): DecisionEnvelope { const x=object(candidate,'decision'); const d:DecisionEnvelope={decisionId:string(x.decisionId,'decisionId'),missionId:string(x.missionId,'missionId'),missionRevision:x.missionRevision as number,actionType:x.actionType as DecisionEnvelope['actionType'],riskLevel:x.riskLevel as 'low',targetProvider:x.targetProvider as null,targetEnvironment:x.targetEnvironment as MissionEnvironment,proposedAction:string(x.proposedAction,'proposedAction'),shellCommand:x.shellCommand as null,url:x.url as null,credentials:x.credentials as null,externalSideEffect:x.externalSideEffect as false,createdAt:timestamp(x.createdAt,'createdAt'),schemaVersion:string(x.schemaVersion,'schemaVersion')}; if(!Number.isInteger(d.missionRevision)||d.missionRevision<1) throw new SupervisorValidationError('missionRevision must be positive'); if(d.actionType!=='route_to_manual_review'||d.riskLevel!=='low'||d.targetProvider!==null||d.shellCommand!==null||d.url!==null||d.credentials!==null||d.externalSideEffect!==false) throw new SupervisorValidationError('decision is not a safe manual-review proposal'); if(!supervisorEnvironments.includes(d.targetEnvironment)) throw new SupervisorValidationError('targetEnvironment is not supported'); return d } }
export const guardrailOutcomeSchema = { parse(candidate: unknown): GuardrailOutcome { const x=object(candidate,'guardrail outcome'); const result:GuardrailOutcome={outcomeId:string(x.outcomeId,'outcomeId'),missionId:string(x.missionId,'missionId'),decisionId:string(x.decisionId,'decisionId'),missionRevision:x.missionRevision as number,status:x.status as GuardrailOutcome['status'],reasons:(x.reasons as unknown[]).map((v,i)=>string(v,`reasons[${i}]`)),evaluatedAt:timestamp(x.evaluatedAt,'evaluatedAt'),policyVersion:string(x.policyVersion,'policyVersion'),schemaVersion:string(x.schemaVersion,'schemaVersion')}; if(!Number.isInteger(result.missionRevision)||result.missionRevision<1||!['approved','approval_required','blocked'].includes(result.status)||!result.reasons.length) throw new SupervisorValidationError('invalid guardrail outcome'); return result } }
export const executionFeedbackSchema = { parse(candidate: unknown): ExecutionFeedback { const x=object(candidate,'execution feedback'); const result:ExecutionFeedback={feedbackId:string(x.feedbackId,'feedbackId'),missionId:string(x.missionId,'missionId'),decisionId:string(x.decisionId,'decisionId'),missionRevision:x.missionRevision as number,status:x.status as 'manual_review_routed',recordedAt:timestamp(x.recordedAt,'recordedAt'),schemaVersion:string(x.schemaVersion,'schemaVersion')}; if(!Number.isInteger(result.missionRevision)||result.missionRevision<1||result.status!=='manual_review_routed') throw new SupervisorValidationError('invalid execution feedback'); return result } }
const transitions: Record<MissionStatus, MissionStatus[]>={NEW:['IN_PROGRESS','PAUSED','BLOCKED','CANCELED'],IN_PROGRESS:['PAUSED','COMPLETED','FAILED','BLOCKED','CANCELED'],PAUSED:['IN_PROGRESS','CANCELED','BLOCKED'],COMPLETED:[],FAILED:[],BLOCKED:[],CANCELED:[]}
export function transitionMission(mission: Mission, status: MissionStatus, updatedAt: string): Mission { missionSchema.parse(mission); timestamp(updatedAt,'updatedAt'); if(!transitions[mission.status].includes(status)) throw new SupervisorValidationError(`invalid mission transition: ${mission.status} -> ${status}`); return missionSchema.parse({...mission,status,revision:mission.revision+1,updatedAt}) }
