// saas/app/api/cos-primary/route.ts
// Live COS-first entrypoint. Provenance fields in this route are assembled from execution state, never generated by a model.

import { NextRequest, NextResponse } from 'next/server'
import { POST as legacyConciergePost } from '@/app/api/concierge/route'
import { tryCOSFirstAnswer } from '@/lib/ai/cos/cosFirstAnswer'
import { tryDeterministicUtility } from '@/lib/ai/cos/deterministicUtilities'
import { requiresFreshExternalEvidence } from '@/lib/ai/cos/cosFreshnessPolicy'
import {
  classifyAuthoritativeVolatileFact,
  groundAuthoritativeVolatileFact,
  renderAuthoritativeGroundedReply,
} from '@/lib/ai/cos/authoritativeFactGrounding'
import {
  attachFreshEvidenceProvenance,
  freshEvidenceMeetsAuthority,
  freshEvidenceSearchQuery,
  prepareFreshEvidence,
  type FreshEvidenceSource,
} from '@/lib/ai/cos/cosFreshGrounding'
import { writeVolatileAnswerCache } from '@/lib/ai/cos/cosVolatileAnswerCache'
import { buildCosLiveTelemetry, emitCosLiveTelemetry, type CosLiveResponseSource } from '@/lib/ai/cos/cosLiveTelemetry'
import { readCosPrimaryPriorProvenance, writeCosPrimaryProvenance } from '@/lib/ai/cos/cosPrimaryTurnProvenance'
import { recordTeacherEscalation } from '@/lib/ai/cos/teacherLearning'
import { synthesizeFreshEvidenceLocally } from '@/lib/ai/cos/freshEvidenceLocalSynthesis'
import { synthesizeFreshEvidenceExternally } from '@/lib/ai/cos/freshEvidenceExternalSynthesis'
import { callCosReasoner, resolveCosReasoner } from '@/lib/ai/cos/cosReasoner'
import { parseLocalResult } from '@/lib/ai/cos/reasonerOutput'
import { getExternalInfo } from '@/lib/ai/tools/getExternalInfo'
import { listRepoFiles, readRepoFile } from '@/lib/ai/tools/repoReader'
import { withCosProviderExecutionTrace, type ProviderExecutionTrace } from '@/lib/cos/textGateway'
import { getAccess } from '@/lib/auth/access'
import {
  isProvenanceIntrospection,
  requestsExternalAction,
  authoritativeProvenance,
  formatAuthoritativeProvenance,
  escalationReason,
  logEscalation,
  confidenceThreshold,
  externalFallbackEnabled,
  independentReasonerHealth,
} from '@/lib/ai/cos/cosOrchestration'

export const runtime = 'nodejs'
export const dynamic = 'force-dynamic'
export const maxDuration = 300

function latestUserText(body:any):string{const messages=Array.isArray(body?.messages)?body.messages:[];for(let i=messages.length-1;i>=0;i-=1){if(messages[i]?.role!=='user')continue;const content=messages[i]?.content;if(typeof content==='string')return content;if(Array.isArray(content))return content.map((block:any)=>String(block?.text||'')).join('\n').trim()}return''}
function isOwnerRepoScanRequest(input:string):boolean{return /\\b(?:scan|audit|review|inspect|analy[sz]e|look through)\\b[\\s\\S]{0,80}\\b(?:repo|repository|codebase|github)\\b|\\b(?:repo|repository|codebase|github)\\b[\\s\\S]{0,80}\\b(?:scan|audit|review|inspect|analy[sz]e)\\b/i.test(input)}
function requestsSelfHealingAssessment(input:string):boolean{return /\\bself[ -]?healing(?:\\s+supervisor)?\\b/i.test(input)&&/\\b(?:evaluate|evaluation|report|better|improve|sellable|fortune\\s*500|enterprise)\\b/i.test(input)}
async function scanRepositoryForOwner():Promise<{ok:boolean;reply:string;error?:string}>{
  const [root,app,lib,onboard,rootPackage,saasPackage]=await Promise.all([listRepoFiles(),listRepoFiles('saas/app'),listRepoFiles('saas/lib'),readRepoFile('ONBOARD.md'),readRepoFile('package.json'),readRepoFile('saas/package.json')])
  const failed=[root,app,lib,onboard,rootPackage,saasPackage].find((item:any)=>!item.ok) as any
  if(failed)return{ok:false,reply:'',error:failed?.error||'Read-only repository scan failed.'}
  const routes=[...new Set((app.files||[]).filter((path:string)=>path.includes('/api/')).slice(0,20))]
  return{ok:true,reply:['Repository scan completed: SignalBoost/signalboost-live@main (read-only).','Verified '+root.files.length+' indexed root files, '+app.files.length+' application files, and '+lib.files.length+' library files in the scanned views.','Inspected canonical files: ONBOARD.md, package.json, saas/package.json.',routes.length?'Representative API routes found: '+routes.join(', ')+'.':'','I can now analyze the existing products, architecture, and improvement opportunities from this verified repository context.'].filter(Boolean).join('\\n')}
}
async function assessSelfHealingSupervisor(request:string):Promise<string|null>{
  const paths=['docs/portables/self-healing-evaluation-brief.md','docs/portables/self-healing-technical-walkthrough.md','docs/portables/self-healing-security-and-data-handling.md','saas/lib/portable-products/manifests/selfHealingSupervisor.ts']
  const files=await Promise.all(paths.map(path=>readRepoFile(path)))
  if(files.some(file=>!file.ok))return null
  const evidence=files.map((file,index)=>`FILE: ${paths[index]}\n${file.content.slice(0,9000)}`).join('\n\n')
  const result=await callCosReasoner({
    temperature:.1,maxTokens:5000,
    systemPrompt:'You are COS performing a Fortune-500 product assessment. Return ONLY strict JSON: {"answer":"...","confidence":0.0}. Use only the supplied repository evidence. Write an executive report for the Self-Healing Supervisor: current strengths, enterprise-sale blockers, prioritized improvements, why each matters, proof required for a buyer, and a 90-day delivery sequence. Do not claim a capability unless it appears in the evidence.',
    prompt:`OWNER REQUEST:\n${request}\n\nVERIFIED REPOSITORY EVIDENCE:\n${evidence}`,
  }).catch(()=>null)
  const parsed=result?.text?parseLocalResult(result.text):null
  return parsed?.answer?.trim()||null
}
function previousAssistantText(body:any):string{const messages=Array.isArray(body?.messages)?body.messages:[];for(let i=messages.length-1;i>=0;i-=1){if(messages[i]?.role==='assistant'&&typeof messages[i]?.content==='string'&&messages[i].content.trim())return messages[i].content.trim()}return''}
function languageFrom(body:any):string{const value=String(body?.context?.language||'en').toLowerCase();return['en','es','pt','pl','ru'].includes(value)?value:'en'}
function providerFromPayload(payload:any):{provider:string|null;model:string|null}{for(const item of[payload?.execution,payload?.metadata,payload?.provenance,payload]){if(!item||typeof item!=='object')continue;const provider=typeof item.provider==='string'?item.provider:typeof item.ai_provider==='string'?item.ai_provider:typeof item.external_provider==='string'?item.external_provider:null;const model=typeof item.model==='string'?item.model:typeof item.ai_model==='string'?item.ai_model:typeof item.external_model==='string'?item.external_model:null;if(provider||model)return{provider,model}}return{provider:null,model:null}}
function normalizeProvider(value:string|null):string|null{return value==='claude'?'anthropic':value}
function externalExecution(payload:any,trace:ProviderExecutionTrace,isPrivileged:boolean):{provider:string|null;model:string|null;invoked:boolean;source:'provider'|'cache'|null}{
  const explicit=providerFromPayload(payload),source=String(payload?.source||'')
  const directAnthropic=source==='anthropic-chief'||source==='anthropic-concierge'
  if(explicit.provider||explicit.model)return{provider:normalizeProvider(explicit.provider),model:explicit.model,invoked:payload?.external_ai_invoked!==false,source:'provider'}
  if(directAnthropic)return{provider:'anthropic',model:isPrivileged?'claude-sonnet-4-6':'claude-haiku-4-5',invoked:true,source:'provider'}
  return{provider:normalizeProvider(trace.provider),model:trace.model,invoked:trace.invoked,source:trace.source}
}
function legacyContinuityFailure(payload:any):boolean{const text=JSON.stringify(payload??{}).toLowerCase();return text.includes('both reasoning providers are temporarily unavailable')||text.includes('continuity protection detected a primary failure')}
function noPriorReply(language:string):string{return language==='es'?'No tengo un registro de procedencia real para la respuesta inmediatamente anterior. No voy a inventarlo.':language==='pt'?'Não tenho um registro de proveniência real para a resposta imediatamente anterior. Não vou inventá-lo.':"I don't have a real provenance record for the immediately preceding answer. I won't fabricate one."}
function emitRequestTelemetry(args:{startedAt:number;input:string;reply?:string|null;source:CosLiveResponseSource;confidence?:number|null;provenance?:any;externalAiInvoked:boolean}){const p=args.provenance??null,observation=buildCosLiveTelemetry({responseSource:args.source,latencyMs:Math.max(0,Date.now()-args.startedAt),confidence:args.confidence??null,reasonerLabel:p?.reasonerLabel??null,localModelInvoked:p?.localModelInvoked??false,externalAiInvoked:args.externalAiInvoked,knowledgeFactsUsed:p?.knowledgeFactsUsed??0,learnedItemsUsed:p?.learnedItemsUsed??0,userMemoriesUsed:p?.userMemoriesUsed??0,similarityScore:p?.similarityScore,promptChars:args.input.length,replyChars:String(args.reply??'').length});emitCosLiveTelemetry(observation);return observation}
function freshEvidenceUnavailableReply(language:string):string{const messages:Record<string,string>={en:'COS requires live authoritative evidence for this current fact, but live verification is unavailable or insufficient right now. No model-memory answer was used.',es:'COS requiere evidencia autorizada en vivo para este hecho actual, pero la verificación en vivo no está disponible o es insuficiente en este momento. No se utilizó una respuesta de memoria del modelo.',pt:'O COS exige evidência autorizada ao vivo para este fato atual, mas a verificação em vivo está indisponível ou insuficiente neste momento. Nenhuma resposta da memória do modelo foi usada.',pl:'COS wymaga aktualnego, wiarygodnego źródła dla tego bieżącego faktu, ale w tej chwili weryfikacja na żywo jest niedostępna lub niewystarczająca. Nie użyto odpowiedzi z pamięci modelu.',ru:'COS требует актуального авторитетного источника для этого текущего факта, но сейчас живая проверка недоступна или недостаточна. Ответ из памяти модели не использовался.'};return messages[language]||messages.en}
function freshSynthesisRejectedReply(language:string):string{const messages:Record<string,string>={en:'COS retrieved live evidence, but the synthesis did not prove that its current-fact answer was grounded in that evidence. The answer was rejected instead of guessing.',es:'COS obtuvo evidencia en vivo, pero la síntesis no demostró que su respuesta sobre el hecho actual estuviera basada en esa evidencia. La respuesta fue rechazada en lugar de adivinar.',pt:'O COS obteve evidência em vivo, mas a síntese não comprovou que a resposta sobre o fato atual estava fundamentada nessa evidência. A resposta foi rejeitada em vez de adivinhar.',pl:'COS pobrał aktualne dowody, ale synteza nie wykazała, że odpowiedź dotycząca bieżącego faktu była na nich oparta. Odpowiedź została odrzucona zamiast zgadywania.',ru:'COS получил актуальные данные, но синтез не подтвердил, что ответ о текущем факте основан на них. Ответ был отклонён вместо догадки.'};return messages[language]||messages.en}

function lowConfidenceDraftReply(cos: Awaited<ReturnType<typeof tryCOSFirstAnswer>>, reason: { detail: string }): string | null {
  if (!cos || cos.handled || !('bestEffortReply' in cos) || !cos.bestEffortReply) return null
  return [`⚠️ Low-confidence draft (COS confidence ${cos.confidence.toFixed(2)}, below the ${confidenceThreshold().toFixed(2)} threshold; no external model was available to do better). ${reason.detail}`,'',cos.bestEffortReply].join('\n')
}
function localDraft(cos:Awaited<ReturnType<typeof tryCOSFirstAnswer>>|null):string|null{if(!cos)return null;if(cos.handled)return cos.reply;return 'bestEffortReply' in cos&&typeof cos.bestEffortReply==='string'?cos.bestEffortReply:null}
function localReasonerLabel():string{const resolved=resolveCosReasoner();return resolved.config?.label??`independent-local:${(process.env.LOCAL_AI_MODEL||'local-model').trim()}`}
function markFreshLocalReasoning(provenance:any,args:{invoked:boolean;model?:string|null;confidence?:number|null;accepted?:boolean|null}){
  if(!args.invoked)return provenance
  provenance.local_reasoning={...(provenance.local_reasoning||{}),invoked:true,model:args.model||localReasonerLabel(),confidence:args.confidence??null,threshold:confidenceThreshold()}
  provenance.fresh_local_synthesis={attempted:true,accepted:args.accepted??null}
  return provenance
}
function freshTelemetryProvenance(invoked:boolean,reasonerLabel:string|null){return{localModelInvoked:invoked,reasonerLabel}}

export async function POST(req:NextRequest){
  const startedAt=Date.now(),body=await req.clone().json().catch(()=>({})),input=latestUserText(body),language=languageFrom(body)
  if(!input)return legacyConciergePost(new NextRequest(req.clone()))
  const access=await getAccess().catch(()=>null),userId=access?.userId||null,precedingAssistant=previousAssistantText(body),isPrivileged=Boolean(access?.isOwner||access?.isAdmin)

  // Repository inspection is an owner-authorized, read-only operation. Execute it here so a model/tool-choice loop cannot skip it.
  if(access?.isOwner&&isOwnerRepoScanRequest(input)){
    const scan=await scanRepositoryForOwner()
    const assessment=scan.ok&&requestsSelfHealingAssessment(input)?await assessSelfHealingSupervisor(input):null
    const reply=assessment||(scan.ok?scan.reply:`COS could not complete the read-only repository scan: ${scan.error||'unknown repository reader failure'}`)
    const executionProvenance=authoritativeProvenance(null,{invoked:false})
    const liveTelemetry=emitRequestTelemetry({startedAt,input,reply,source:scan.ok?'deterministic':'failed_closed',confidence:scan.ok?1:0,externalAiInvoked:false})
    await writeCosPrimaryProvenance(userId,reply,executionProvenance,assessment?'cos-self-healing-assessment':scan.ok?'cos-repository-scan':'cos-repository-scan-failed')
    return NextResponse.json({ok:scan.ok,reply,source:assessment?'cos-self-healing-assessment':scan.ok?'cos-repository-scan':'cos-repository-scan-failed',confidence_score:scan.ok?1:0,confidence_threshold:confidenceThreshold(),external_ai_invoked:false,external_fallback_invoked:false,local_model_invoked:Boolean(assessment),execution_provenance:executionProvenance,live_telemetry:liveTelemetry,execution_allowed:false,external_action_taken:false},{status:scan.ok?200:503})
  }

  if(isProvenanceIntrospection(input)){
    const prior=await readCosPrimaryPriorProvenance(userId,precedingAssistant||undefined)
    const reply=prior?formatAuthoritativeProvenance(prior as any,language):noPriorReply(language)
    const liveTelemetry=emitRequestTelemetry({startedAt,input,reply,source:'deterministic',confidence:1,externalAiInvoked:false})
    return NextResponse.json({reply,source:prior?'cos-authoritative-provenance':'cos-no-provenance-record',confidence_score:1,confidence_threshold:confidenceThreshold(),external_ai_invoked:false,external_fallback_invoked:false,local_model_invoked:false,execution_provenance:prior??undefined,live_telemetry:liveTelemetry,execution_allowed:false,external_action_taken:false})
  }

  const deterministic=tryDeterministicUtility({prompt:input,timezone:body?.context?.timezone||body?.context?.timeZone,locale:language==='pt'?'pt-BR':language==='es'?'es':language==='pl'?'pl':language==='ru'?'ru':'en-US',confidenceThreshold:confidenceThreshold()})
  if(deterministic){const liveTelemetry=emitRequestTelemetry({startedAt,input,reply:deterministic.reply,source:'deterministic',confidence:deterministic.confidence,externalAiInvoked:false});await writeCosPrimaryProvenance(userId,deterministic.reply,deterministic.executionProvenance,deterministic.source);return NextResponse.json({reply:deterministic.reply,source:deterministic.source,confidence_score:deterministic.confidence,confidence_threshold:confidenceThreshold(),external_ai_invoked:false,external_fallback_invoked:false,local_model_invoked:false,execution_provenance:deterministic.executionProvenance,live_telemetry:liveTelemetry,execution_allowed:false,external_action_taken:false})}

  const requiresFreshEvidence=requiresFreshExternalEvidence(input),requestedAction=requestsExternalAction(input)

  const directCategory=requiresFreshEvidence?classifyAuthoritativeVolatileFact(input):null
  if(directCategory){
    const attemptedAt=new Date().toISOString()
    const grounded=await groundAuthoritativeVolatileFact(input,{fetch:(url,headers)=>fetch(url,{headers,cache:'no-store'})})
    if(!grounded){
      const detail='The configured authoritative source did not yield a verifiable current fact. Model-memory fallback is prohibited for this fact category.'
      const executionProvenance=attachFreshEvidenceProvenance(authoritativeProvenance(null,{invoked:false}),{sources:[],retrievedAt:attemptedAt,error:detail,synthesisAccepted:null})
      ;(executionProvenance as any).authoritative_source={used:false,attempted:true,category:directCategory.id,source_urls:directCategory.sources.map(source=>source.url),fetched_at:attemptedAt,error:detail}
      const reply=freshEvidenceUnavailableReply(language)
      const liveTelemetry=emitRequestTelemetry({startedAt,input,reply,source:'failed_closed',confidence:0,externalAiInvoked:false})
      logEscalation({event:'authoritative_direct_fact_miss',category:directCategory.id,source_urls:directCategory.sources.map(source=>source.url),external_ai_invoked:false,local_model_invoked:false})
      await writeCosPrimaryProvenance(userId,reply,executionProvenance,'cos-authoritative-source-unavailable')
      return NextResponse.json({ok:false,reply,error:reply,source:'cos-authoritative-source-unavailable',confidence_score:0,confidence_threshold:confidenceThreshold(),external_ai_invoked:false,external_fallback_invoked:false,local_model_invoked:false,execution_provenance:executionProvenance,authoritative_source_attempted:true,authoritative_source_urls:directCategory.sources.map(source=>source.url),live_telemetry:liveTelemetry,execution_allowed:false,external_action_taken:false},{status:503})
    }
    const directSource:FreshEvidenceSource={id:'LIVE1',title:grounded.sourceLabel,url:grounded.sourceUrl,snippet:grounded.answer}
    const reply=renderAuthoritativeGroundedReply(grounded)
    const executionProvenance=attachFreshEvidenceProvenance(authoritativeProvenance(null,{invoked:false}),{sources:[directSource],retrievedAt:grounded.fetchedAt,error:null,synthesisAccepted:null})
    ;(executionProvenance as any).authoritative_source={used:true,attempted:true,category:grounded.categoryId,id:grounded.sourceId,label:grounded.sourceLabel,url:grounded.sourceUrl,fetched_at:grounded.fetchedAt}
    ;(executionProvenance as any).answer_origin={from_cache:false,provider:null,model:null,authoritative_source:grounded.sourceId,grounded_at:grounded.fetchedAt}
    const volatileCacheWritten=await writeVolatileAnswerCache({prompt:input,language,value:{reply,groundedAt:grounded.fetchedAt,liveSources:[directSource],externalProvider:null,externalModel:null}})
    const liveTelemetry=emitRequestTelemetry({startedAt,input,reply,source:'authoritative_source',confidence:1,externalAiInvoked:false})
    logEscalation({event:'authoritative_direct_fact_hit',category:grounded.categoryId,provider:'authoritative_source',model:grounded.sourceId,status:200,source_url:grounded.sourceUrl,external_ai_invoked:false,local_model_invoked:false})
    await writeCosPrimaryProvenance(userId,reply,executionProvenance,'cos-authoritative-source')
    return NextResponse.json({ok:true,reply,source:'cos-authoritative-source',confidence_score:1,confidence_threshold:confidenceThreshold(),external_ai_invoked:false,external_fallback_invoked:false,local_model_invoked:false,execution_provenance:executionProvenance,authoritative_source:{id:grounded.sourceId,label:grounded.sourceLabel,url:grounded.sourceUrl,fetched_at:grounded.fetchedAt},volatile_cache_written:volatileCacheWritten,live_evidence_retrieved_this_turn:true,live_evidence_sources:[{id:directSource.id,title:directSource.title,url:directSource.url}],live_telemetry:liveTelemetry,execution_allowed:false,external_action_taken:false})
  }

  let freshSources:FreshEvidenceSource[]=[],freshRetrievedAt:string|null=null,freshError:string|null=null
  let freshLocalAttempted=false,freshLocalModel:string|null=null
  if(requiresFreshEvidence){
    freshRetrievedAt=new Date().toISOString()
    const query=freshEvidenceSearchQuery(input)
    const live=await getExternalInfo(query,8,{bypassCache:true})
    freshError=live.ok?null:live.error||'Live search returned no usable evidence.'
    freshSources=live.ok?prepareFreshEvidence(live.results,8):[]
    const authoritySatisfied=freshEvidenceMeetsAuthority(input,freshSources)
    logEscalation({event:'fresh_external_evidence_result',query,documents_acquired:freshSources.length,authority_satisfied:authoritySatisfied,error:freshError,source_urls:freshSources.map(source=>source.url)})
    if(!authoritySatisfied){
      const detail=freshError||'Live search did not return authoritative evidence required for this current fact.'
      const executionProvenance=attachFreshEvidenceProvenance(authoritativeProvenance(null,{invoked:false}),{sources:freshSources,retrievedAt:freshRetrievedAt,error:detail,synthesisAccepted:false})
      const reply=freshEvidenceUnavailableReply(language),liveTelemetry=emitRequestTelemetry({startedAt,input,reply,source:'failed_closed',confidence:0,externalAiInvoked:false})
      await writeCosPrimaryProvenance(userId,reply,executionProvenance,'cos-fresh-evidence-unavailable')
      return NextResponse.json({ok:false,reply,error:reply,source:'cos-fresh-evidence-unavailable',confidence_score:0,confidence_threshold:confidenceThreshold(),external_ai_invoked:false,external_fallback_invoked:false,local_model_invoked:false,execution_provenance:executionProvenance,live_telemetry:liveTelemetry,execution_allowed:false,external_action_taken:false},{status:503})
    }

    if(!requestedAction){
      freshLocalAttempted=true
      freshLocalModel=localReasonerLabel()
      const localSynthesis=await synthesizeFreshEvidenceLocally({input,sources:freshSources,retrievedAt:freshRetrievedAt,language})
      if(localSynthesis){
        freshLocalModel=localSynthesis.reasonerLabel
        const baseProvenance=markFreshLocalReasoning(authoritativeProvenance(null,{invoked:false}),{invoked:true,model:localSynthesis.reasonerLabel,confidence:1,accepted:true})
        const executionProvenance=attachFreshEvidenceProvenance(baseProvenance,{sources:freshSources,retrievedAt:freshRetrievedAt,error:null,synthesisAccepted:true})
        ;(executionProvenance as any).answer_origin={...(executionProvenance as any).answer_origin,from_cache:false,provider:null,model:localSynthesis.reasonerLabel,grounded_at:freshRetrievedAt}
        logEscalation({event:'fresh_local_synthesis_accepted',documents_acquired:freshSources.length,reasoner:localSynthesis.reasonerLabel,external_ai_invoked:false,local_model_invoked:true})
        const liveTelemetry=emitRequestTelemetry({startedAt,input,reply:localSynthesis.reply,source:'local_cos_reasoning',confidence:1,provenance:freshTelemetryProvenance(true,localSynthesis.reasonerLabel),externalAiInvoked:false})
        const volatileCacheWritten=await writeVolatileAnswerCache({prompt:input,language,value:{reply:localSynthesis.reply,groundedAt:freshRetrievedAt,liveSources:freshSources,externalProvider:null,externalModel:null}})
        await writeCosPrimaryProvenance(userId,localSynthesis.reply,executionProvenance,'cos-fresh-local-grounded')
        return NextResponse.json({ok:true,reply:localSynthesis.reply,source:'cos-fresh-local-grounded',confidence_score:1,confidence_threshold:confidenceThreshold(),external_ai_invoked:false,external_fallback_invoked:false,local_model_invoked:true,execution_provenance:executionProvenance,volatile_cache_written:volatileCacheWritten,live_evidence_retrieved_this_turn:true,live_evidence_sources:freshSources.map(source=>({id:source.id,title:source.title,url:source.url})),live_telemetry:liveTelemetry,execution_allowed:false,external_action_taken:false})
      }
      logEscalation({event:'fresh_local_synthesis_declined',documents_acquired:freshSources.length,external_ai_invoked:false,local_model_invoked:true})
    }
  }

  let cos:Awaited<ReturnType<typeof tryCOSFirstAnswer>>|null=null,localError:string|null=null
  // Fresh facts already completed live retrieval plus their one local synthesis attempt above.
  // Re-entering generic COS here caused a second search and a second local call on the same turn.
  if(!requestedAction&&!requiresFreshEvidence){
    try{cos=await tryCOSFirstAnswer({prompt:input,userId,language,privileged:isPrivileged})}catch(error){localError=error instanceof Error?error.message:String(error);console.error('[cos-local-reasoner-error]',localError)}
  }
  if(cos?.handled){const executionProvenance=authoritativeProvenance(cos,{invoked:false}),source:CosLiveResponseSource=cos.provenance.responseSource as CosLiveResponseSource,liveTelemetry=emitRequestTelemetry({startedAt,input,reply:cos.reply,source,confidence:cos.confidence,provenance:cos.provenance,externalAiInvoked:false}),responseSource=cos.provenance.responseSource==='semantic_cache'||cos.provenance.responseSource==='semantic_similarity'?'cos-semantic-cache':'cos-local-primary';await writeCosPrimaryProvenance(userId,cos.reply,executionProvenance,responseSource);return NextResponse.json({reply:cos.reply,source:responseSource,confidence_score:cos.confidence,confidence_threshold:confidenceThreshold(),external_ai_invoked:false,external_fallback_invoked:false,local_model_invoked:cos.provenance.localModelInvoked,execution_provenance:executionProvenance,provenance:cos.provenance,live_telemetry:liveTelemetry,execution_allowed:false,external_action_taken:false})}

  const reason=requiresFreshEvidence?{code:'fresh_external_evidence_required',detail:'Current or volatile fact requires this-turn live evidence before synthesis.'}:escalationReason(cos,localError,requestedAction)
  logEscalation({event:'external_escalation_decision',reason_code:reason.code,reason:reason.detail,confidence:cos?.confidence??null,threshold:confidenceThreshold(),local_model_invoked:requiresFreshEvidence?freshLocalAttempted:(cos?.provenance?.localModelInvoked??false),local_model:requiresFreshEvidence?freshLocalModel:(cos?.provenance?.reasonerLabel??null),semantic_cache_hit:cos?.provenance?.responseSource==='semantic_cache'||cos?.provenance?.responseSource==='semantic_similarity',knowledge_facts_used:cos?.provenance?.knowledgeFactsUsed??0,learned_items_used:cos?.provenance?.learnedItemsUsed??0,external_action_requested:requestedAction,fallback_enabled:externalFallbackEnabled(),fresh_evidence_required:requiresFreshEvidence,fresh_documents_acquired:freshSources.length})

  if(!externalFallbackEnabled()){
    let baseProvenance=authoritativeProvenance(cos,{invoked:false})
    if(requiresFreshEvidence)baseProvenance=markFreshLocalReasoning(baseProvenance,{invoked:freshLocalAttempted,model:freshLocalModel,accepted:false})
    const executionProvenance=requiresFreshEvidence&&freshRetrievedAt?attachFreshEvidenceProvenance(baseProvenance,{sources:freshSources,retrievedAt:freshRetrievedAt,error:'External synthesis is disabled.',synthesisAccepted:false}):baseProvenance
    const reply=requiresFreshEvidence?freshSynthesisRejectedReply(language):(lowConfidenceDraftReply(cos,reason)??'COS could not complete this request independently and external AI fallback is disabled.'),liveTelemetry=emitRequestTelemetry({startedAt,input,reply,source:'failed_closed',confidence:cos?.confidence??0,provenance:requiresFreshEvidence?freshTelemetryProvenance(freshLocalAttempted,freshLocalModel):cos?.provenance,externalAiInvoked:false})
    await writeCosPrimaryProvenance(userId,reply,executionProvenance,'failed_closed')
    return NextResponse.json({ok:false,reply,error:reply,cos_first_attempted:requiresFreshEvidence?freshLocalAttempted:(Boolean(cos)||Boolean(localError)),cos_first_handled:false,cos_first_confidence:cos?.confidence??0,confidence_threshold:confidenceThreshold(),cos_first_reason:reason.detail,escalation_reason_code:reason.code,independent_reasoner:await independentReasonerHealth(),external_ai_invoked:false,external_fallback_invoked:false,isolation_mode:true,execution_provenance:executionProvenance,live_telemetry:liveTelemetry},{status:503})
  }

  // Fresh/current facts never enter the legacy Concierge fallback. That route has its own COS-first
  // loop and would repeat freshness retrieval. Use the COS text gateway directly as a constrained
  // sources-only phraser, then fail closed if its evidence-id contract is not satisfied.
  if(requiresFreshEvidence&&freshRetrievedAt){
    const externalFresh=await synthesizeFreshEvidenceExternally({input,sources:freshSources,retrievedAt:freshRetrievedAt,language})
    const externalInvoked=externalFresh.source==='provider'||(externalFresh.source===null&&externalFresh.attempted)
    const externalProvider=normalizeProvider(externalFresh.provider)
    let baseProvenance=authoritativeProvenance(null,{invoked:externalInvoked,provider:externalProvider,model:externalFresh.model})
    baseProvenance=markFreshLocalReasoning(baseProvenance,{invoked:freshLocalAttempted,model:freshLocalModel,accepted:false})
    const executionProvenance=attachFreshEvidenceProvenance(baseProvenance,{sources:freshSources,retrievedAt:freshRetrievedAt,error:externalFresh.accepted?null:'External fresh-evidence synthesis was unavailable or rejected by the evidence contract.',synthesisAccepted:externalFresh.accepted})
    logEscalation({event:'fresh_external_synthesis_result',provider:externalProvider,model:externalFresh.model,provider_source:externalFresh.source,external_ai_invoked:externalInvoked,local_model_invoked:freshLocalAttempted,fresh_documents_acquired:freshSources.length,fresh_synthesis_accepted:externalFresh.accepted})

    if(!externalFresh.accepted||!externalFresh.reply){
      const reply=freshSynthesisRejectedReply(language)
      const liveTelemetry=emitRequestTelemetry({startedAt,input,reply,source:'failed_closed',confidence:0,provenance:freshTelemetryProvenance(freshLocalAttempted,freshLocalModel),externalAiInvoked:externalInvoked})
      await writeCosPrimaryProvenance(userId,reply,executionProvenance,'cos-fresh-evidence-synthesis-rejected')
      return NextResponse.json({ok:false,reply,error:reply,source:'cos-fresh-evidence-synthesis-rejected',confidence_score:0,confidence_threshold:confidenceThreshold(),external_ai_invoked:externalInvoked,external_provider:externalProvider,external_model:externalFresh.model,external_provider_source:externalFresh.source,external_fallback_invoked:externalInvoked,external_fallback_succeeded:false,local_model_invoked:freshLocalAttempted,execution_provenance:executionProvenance,live_telemetry:liveTelemetry,execution_allowed:false,external_action_taken:false},{status:503})
    }

    const reply=externalFresh.reply
    ;(executionProvenance as any).answer_origin={...(executionProvenance as any).answer_origin,from_cache:false,provider:externalProvider,model:externalFresh.model,grounded_at:freshRetrievedAt}
    const volatileCacheWritten=await writeVolatileAnswerCache({prompt:input,language,value:{reply,groundedAt:freshRetrievedAt,liveSources:freshSources,externalProvider,externalModel:externalFresh.model}})
    const liveTelemetry=emitRequestTelemetry({startedAt,input,reply,source:'external_fallback',confidence:1,provenance:freshTelemetryProvenance(freshLocalAttempted,freshLocalModel),externalAiInvoked:externalInvoked})
    await writeCosPrimaryProvenance(userId,reply,executionProvenance,'external_fresh_grounded')
    return NextResponse.json({ok:true,reply,source:'external_fresh_grounded',confidence_score:1,confidence_threshold:confidenceThreshold(),cos_first_attempted:freshLocalAttempted,cos_first_handled:false,cos_first_confidence:null,cos_first_reason:reason.detail,escalation_reason_code:reason.code,execution_provenance:executionProvenance,external_ai_invoked:externalInvoked,external_provider:externalProvider,external_model:externalFresh.model,external_provider_source:externalFresh.source,external_fallback_invoked:externalInvoked,external_fallback_succeeded:true,local_model_invoked:freshLocalAttempted,isolation_mode:false,volatile_cache_written:volatileCacheWritten,live_evidence_retrieved_this_turn:true,live_evidence_sources:freshSources.map(source=>({id:source.id,title:source.title,url:source.url})),live_telemetry:liveTelemetry,execution_allowed:false,external_action_taken:false})
  }

  // Non-volatile requests retain the existing legacy provider/tool fallback path.
  const traced=await withCosProviderExecutionTrace(()=>legacyConciergePost(new NextRequest(req.clone()))),response=traced.result
  try{
    const payload=await response.clone().json(),continuityFailed=legacyContinuityFailure(payload),external=externalExecution(payload,traced.trace,isPrivileged),externalInvoked=!continuityFailed&&external.invoked,reasonerHealth=continuityFailed?await independentReasonerHealth():null,rawReply=String(payload?.reply||'')
    logEscalation({event:'external_escalation_result',reason_code:reason.code,provider:external.provider,model:external.model,status:response.status,continuity_failed:continuityFailed,external_ai_invoked:externalInvoked,provider_source:external.source,independent_reasoner:reasonerHealth,fresh_evidence_required:false})
    const executionProvenance=authoritativeProvenance(cos,{invoked:externalInvoked,provider:external.provider,model:external.model})
    const reply=continuityFailed?(lowConfidenceDraftReply(cos,reason)??`COS independent reasoning could not complete this request: ${reason.detail} External fallback was also unavailable. No action was executed.`):rawReply
    const responseSource=continuityFailed?'cos-independent-reasoner-unavailable':'external_fallback'
    const liveTelemetry=emitRequestTelemetry({startedAt,input,reply,source:continuityFailed?'failed_closed':'external_fallback',confidence:cos?.confidence??null,provenance:cos?.provenance,externalAiInvoked:externalInvoked})
    if(externalInvoked&&!continuityFailed&&reply){await recordTeacherEscalation({prompt:input,localAnswer:localDraft(cos),localConfidence:cos?.confidence??null,escalationReason:reason.detail,teacherAnswer:reply,teacherProvider:external.provider,teacherModel:external.model,metadata:{reasonCode:reason.code,responseStatus:response.status}})}
    if(reply)await writeCosPrimaryProvenance(userId,reply,executionProvenance,responseSource)
    return NextResponse.json({...payload,reply,source:responseSource,cos_first_attempted:Boolean(cos)||Boolean(localError),cos_first_handled:Boolean(cos?.handled),cos_first_confidence:cos?.confidence??null,confidence_threshold:confidenceThreshold(),cos_first_reason:reason.detail,escalation_reason_code:reason.code,independent_reasoner:reasonerHealth,cos_first_provenance:cos?.provenance??null,execution_provenance:executionProvenance,external_ai_invoked:externalInvoked,external_provider:external.provider,external_model:external.model,external_provider_source:external.source,external_fallback_invoked:true,external_fallback_succeeded:!continuityFailed,isolation_mode:false,live_telemetry:liveTelemetry},{status:response.status})
  }catch(error){logEscalation({event:'external_escalation_result_unparsed',reason_code:reason.code,provider:normalizeProvider(traced.trace.provider),model:traced.trace.model,status:response.status,error:error instanceof Error?error.message:String(error)});emitRequestTelemetry({startedAt,input,source:'external_fallback',confidence:cos?.confidence??null,provenance:cos?.provenance,externalAiInvoked:traced.trace.invoked});return response}
}
