// saas/app/api/cos-primary/route.ts
// Live COS-first entrypoint. Provenance fields in this route are assembled from execution state, never generated by a model.

import { NextRequest, NextResponse } from 'next/server'
import { POST as legacyConciergePost } from '@/app/api/concierge/route'
import { tryCOSFirstAnswer } from '@/lib/ai/cos/cosFirstAnswer'
import { tryDeterministicUtility } from '@/lib/ai/cos/deterministicUtilities'
import { buildCosLiveTelemetry, emitCosLiveTelemetry, type CosLiveResponseSource } from '@/lib/ai/cos/cosLiveTelemetry'
import { getAccess } from '@/lib/auth/access'
import {
  isProvenanceIntrospection,
  requestsExternalAction,
  authoritativeProvenance,
  escalationReason,
  logEscalation,
  confidenceThreshold,
  externalFallbackEnabled,
  independentReasonerHealth,
} from '@/lib/ai/cos/cosOrchestration'

export const runtime = 'nodejs'
export const dynamic = 'force-dynamic'
export const maxDuration = 300

// Route-specific only. Not in the shared module because BOTH parse the LEGACY
// /api/concierge JSON response shape, which is meaningless outside this route's
// own escalation path — support/route.ts talks to Anthropic directly, never
// through this legacy payload.
function latestUserText(body: any): string { const messages=Array.isArray(body?.messages)?body.messages:[]; for(let i=messages.length-1;i>=0;i-=1){if(messages[i]?.role!=='user')continue;const content=messages[i]?.content;if(typeof content==='string')return content;if(Array.isArray(content))return content.map((block:any)=>String(block?.text||'')).join('\n').trim()} return '' }
function languageFrom(body:any):string{const value=String(body?.context?.language||'en').toLowerCase();return ['en','es','pt','pl','ru'].includes(value)?value:'en'}
function providerFromPayload(payload:any):{provider:string|null;model:string|null}{const candidates=[payload?.execution,payload?.metadata,payload?.provenance,payload];for(const item of candidates){if(!item||typeof item!=='object')continue;const provider=typeof item.provider==='string'?item.provider:typeof item.ai_provider==='string'?item.ai_provider:null;const model=typeof item.model==='string'?item.model:typeof item.ai_model==='string'?item.ai_model:null;if(provider||model)return{provider,model}}return{provider:null,model:null}}
function legacyContinuityFailure(payload:any):boolean{const text=JSON.stringify(payload??{}).toLowerCase();return text.includes('both reasoning providers are temporarily unavailable')||text.includes('continuity protection detected a primary failure')}

function emitRequestTelemetry(args:{startedAt:number;input:string;reply?:string|null;source:CosLiveResponseSource;confidence?:number|null;provenance?:any;externalAiInvoked:boolean}){
  const p=args.provenance??null
  const observation=buildCosLiveTelemetry({responseSource:args.source,latencyMs:Math.max(0,Date.now()-args.startedAt),confidence:args.confidence??null,reasonerLabel:p?.reasonerLabel??null,localModelInvoked:p?.localModelInvoked??false,externalAiInvoked:args.externalAiInvoked,knowledgeFactsUsed:p?.knowledgeFactsUsed??0,learnedItemsUsed:p?.learnedItemsUsed??0,userMemoriesUsed:p?.userMemoriesUsed??0,similarityScore:p?.similarityScore,promptChars:args.input.length,replyChars:String(args.reply??'').length})
  emitCosLiveTelemetry(observation)
  return observation
}

export async function POST(req:NextRequest){
  const startedAt=Date.now();const body=await req.clone().json().catch(()=>({}));const input=latestUserText(body);const language=languageFrom(body);if(!input)return legacyConciergePost(new NextRequest(req.clone()))
  const deterministic=tryDeterministicUtility({prompt:input,timezone:body?.context?.timezone||body?.context?.timeZone,locale:language==='pt'?'pt-BR':language==='es'?'es':language==='pl'?'pl':language==='ru'?'ru':'en-US',confidenceThreshold:confidenceThreshold()})
  if(deterministic){const liveTelemetry=emitRequestTelemetry({startedAt,input,reply:deterministic.reply,source:'deterministic',confidence:deterministic.confidence,externalAiInvoked:false});return NextResponse.json({reply:deterministic.reply,source:deterministic.source,confidence_score:deterministic.confidence,confidence_threshold:confidenceThreshold(),external_ai_invoked:false,external_fallback_invoked:false,local_model_invoked:false,execution_provenance:deterministic.executionProvenance,live_telemetry:liveTelemetry,execution_allowed:false,external_action_taken:false})}

  // PROVENANCE INTROSPECTION GUARD — added Aug 12 after this exact route fabricated a
  // report claiming specific evidence counts (12 learned items, 5 user memories) for a
  // question that was actually about semantic caching/knowledge graphs IN THE ABSTRACT.
  // Root cause: before this guard, a provenance question fell through to the ORDINARY
  // tryCOSFirstAnswer call below like any other question. COS's own foundational-
  // learning curriculum includes a study question about "semantic caches, embeddings,
  // knowledge graphs, confidence gates" — so retrieval genuinely finds real stored
  // background material on those exact terms, and the reasoner then confidently
  // misreports that retrieved GENERAL KNOWLEDGE as first-person execution telemetry
  // about the immediately preceding turn. This route has no persisted prior-turn
  // record to consult — each POST here is a single, stateless request, unlike
  // support/route.ts's multi-turn conversation — so a provenance question on THIS
  // route can only ever be answered honestly by saying so, never by asking the
  // reasoner to guess. Checked before tryCOSFirstAnswer is ever called, so the
  // fabrication-prone path is never reached at all.
  if(isProvenanceIntrospection(input)){
    const reply=language==='es'?'Esta ruta no conserva un turno anterior real para consultar — cada solicitud aquí es independiente. No voy a inventar una procedencia para una respuesta que esta ruta no recuerda.'
      :language==='pt'?'Esta rota não mantém um turno anterior real para consultar — cada solicitação aqui é independente. Não vou inventar uma proveniência para uma resposta que esta rota não lembra.'
      :'This route does not retain a real prior turn to consult — each request here is independent. I\u2019m not going to invent a provenance report for an answer this route has no memory of.'
    const liveTelemetry=emitRequestTelemetry({startedAt,input,reply,source:'deterministic',confidence:1,externalAiInvoked:false})
    return NextResponse.json({reply,source:'cos-no-provenance-record',confidence_score:1,confidence_threshold:confidenceThreshold(),external_ai_invoked:false,external_fallback_invoked:false,local_model_invoked:false,live_telemetry:liveTelemetry,execution_allowed:false,external_action_taken:false})
  }

  const access=await getAccess().catch(()=>null);let cos:Awaited<ReturnType<typeof tryCOSFirstAnswer>>|null=null;let localError:string|null=null
  try{cos=await tryCOSFirstAnswer({prompt:input,userId:access?.userId||null,language,privileged:Boolean(access?.isOwner||access?.isAdmin)})}catch(error){localError=error instanceof Error?error.message:String(error);console.error('[cos-local-reasoner-error]',localError)}
  const requestedAction=requestsExternalAction(input)
  if(cos?.handled&&!requestedAction){const executionProvenance=authoritativeProvenance(cos,{invoked:false});const source:CosLiveResponseSource=cos.provenance.responseSource as CosLiveResponseSource;const liveTelemetry=emitRequestTelemetry({startedAt,input,reply:cos.reply,source,confidence:cos.confidence,provenance:cos.provenance,externalAiInvoked:false});return NextResponse.json({reply:cos.reply,source:cos.provenance.responseSource==='semantic_cache'||cos.provenance.responseSource==='semantic_similarity'?'cos-semantic-cache':'cos-local-primary',confidence_score:cos.confidence,confidence_threshold:confidenceThreshold(),external_ai_invoked:false,external_fallback_invoked:false,local_model_invoked:cos.provenance.localModelInvoked,execution_provenance:executionProvenance,provenance:cos.provenance,live_telemetry:liveTelemetry,execution_allowed:false,external_action_taken:false})}

  const reason=escalationReason(cos,localError,requestedAction);const auditBase={event:'external_escalation_decision',reason_code:reason.code,reason:reason.detail,confidence:cos?.confidence??null,threshold:confidenceThreshold(),local_model_invoked:cos?.provenance?.localModelInvoked??false,local_model:cos?.provenance?.reasonerLabel??null,semantic_cache_hit:cos?.provenance?.responseSource==='semantic_cache'||cos?.provenance?.responseSource==='semantic_similarity',knowledge_facts_used:cos?.provenance?.knowledgeFactsUsed??0,learned_items_used:cos?.provenance?.learnedItemsUsed??0,external_action_requested:requestedAction,fallback_enabled:externalFallbackEnabled()};logEscalation(auditBase)
  if(!externalFallbackEnabled()){const liveTelemetry=emitRequestTelemetry({startedAt,input,source:'failed_closed',confidence:cos?.confidence??0,provenance:cos?.provenance,externalAiInvoked:false});return NextResponse.json({ok:false,error:'COS could not complete this request independently and external AI fallback is disabled.',cos_first_attempted:Boolean(cos)||Boolean(localError),cos_first_handled:false,cos_first_confidence:cos?.confidence??0,confidence_threshold:confidenceThreshold(),cos_first_reason:reason.detail,escalation_reason_code:reason.code,independent_reasoner:await independentReasonerHealth(),external_ai_invoked:false,external_fallback_invoked:false,isolation_mode:true,execution_provenance:authoritativeProvenance(cos,{invoked:false}),live_telemetry:liveTelemetry},{status:503})}

  const response=await legacyConciergePost(new NextRequest(req.clone()))
  try{const payload=await response.clone().json();const external=providerFromPayload(payload);const continuityFailed=legacyContinuityFailure(payload);const reasonerHealth=continuityFailed?await independentReasonerHealth():null;logEscalation({event:'external_escalation_result',reason_code:reason.code,provider:external.provider,model:external.model,status:response.status,continuity_failed:continuityFailed,independent_reasoner:reasonerHealth});const executionProvenance=authoritativeProvenance(cos,{invoked:!continuityFailed,...external});const reply=continuityFailed?`COS independent reasoning could not complete this request: ${reason.detail} External fallback was also unavailable. No action was executed.`:payload?.reply;const liveTelemetry=emitRequestTelemetry({startedAt,input,reply,source:continuityFailed?'failed_closed':'external_fallback',confidence:cos?.confidence??null,provenance:cos?.provenance,externalAiInvoked:!continuityFailed});return NextResponse.json({...payload,...(continuityFailed?{reply,source:'cos-independent-reasoner-unavailable'}:{}),cos_first_attempted:Boolean(cos)||Boolean(localError),cos_first_handled:Boolean(cos?.handled),cos_first_confidence:cos?.confidence??null,confidence_threshold:confidenceThreshold(),cos_first_reason:reason.detail,escalation_reason_code:reason.code,independent_reasoner:reasonerHealth,cos_first_provenance:cos?.provenance??null,execution_provenance:executionProvenance,external_ai_invoked:!continuityFailed,external_fallback_invoked:true,external_fallback_succeeded:!continuityFailed,isolation_mode:false,live_telemetry:liveTelemetry},{status:response.status})}catch(error){logEscalation({event:'external_escalation_result_unparsed',reason_code:reason.code,provider:null,model:null,status:response.status,error:error instanceof Error?error.message:String(error)});emitRequestTelemetry({startedAt,input,source:'external_fallback',confidence:cos?.confidence??null,provenance:cos?.provenance,externalAiInvoked:true});return response}
}
