// saas/app/api/cos-primary/route.ts
// Live COS-first entrypoint. Provenance fields in this route are assembled from execution state, never generated by a model.

import { NextRequest, NextResponse } from 'next/server'
import { POST as legacyConciergePost } from '@/app/api/concierge/route'
import { tryCOSFirstAnswer } from '@/lib/ai/cos/cosFirstAnswer'
import { buildHonestRefusalReply } from '@/lib/ai/cos/honestRefusalReply'
import { buildFreshVerificationUnavailableReply } from '@/lib/ai/cos/freshVerificationUnavailableReply'
import { tryDeterministicUtility } from '@/lib/ai/cos/deterministicUtilities'
import { requiresFreshExternalEvidence } from '@/lib/ai/cos/cosFreshnessPolicy'
import {
  classifyAuthoritativeVolatileFact,
  groundAuthoritativeVolatileFact,
  renderAuthoritativeGroundedReply,
} from '@/lib/ai/cos/authoritativeFactGrounding'
import {
  attachFreshEvidenceProvenance,
  freshEvidenceSearchQuery,
  prepareFreshEvidence,
  resolveDeterministicDirectFlight,
  type FreshEvidenceSource,
} from '@/lib/ai/cos/cosFreshGrounding'
import { freshEvidenceMeetsQuestionAuthority } from '@/lib/ai/cos/cosFreshAuthority'
import { resolveFreshConversationContext } from '@/lib/ai/cos/cosFreshConversationContext'
import { writeVolatileAnswerCache } from '@/lib/ai/cos/cosVolatileAnswerCache'
import { buildCosLiveTelemetry, emitCosLiveTelemetry, type CosLiveResponseSource } from '@/lib/ai/cos/cosLiveTelemetry'
import { readCosPrimaryPriorProvenance, writeCosPrimaryProvenance } from '@/lib/ai/cos/cosPrimaryTurnProvenance'
import { asksWhereTheAnswerCameFrom } from '@/lib/ai/cos/provenanceIntrospectionIntent'
import { readStrategyProfile } from '@/lib/ai/cos/strategyProfileReport'
import { appliedStrategyOverrides } from '@/lib/ai/cos/strategyProfile'
import { recordTeacherEscalation } from '@/lib/ai/cos/teacherLearning'
import { synthesizeFreshEvidenceLocally } from '@/lib/ai/cos/freshEvidenceLocalSynthesis'
import { freshFailureReply, type FreshEvidenceInternalFailureCode } from '@/lib/ai/cos/freshEvidenceFailureRecovery'
import { synthesizeFreshEvidenceExternally } from '@/lib/ai/cos/freshEvidenceExternalSynthesis'
import { callCosReasoner, resolveCosReasoner } from '@/lib/ai/cos/cosReasoner'
import { parseLocalResult } from '@/lib/ai/cos/reasonerOutput'
import { getExternalInfo } from '@/lib/ai/tools/getExternalInfo'
import { listRepoFiles, readRepoFile } from '@/lib/ai/tools/repoReader'
import { withCosProviderExecutionTrace, type ProviderExecutionTrace } from '@/lib/cos/textGateway'
import { getAccess } from '@/lib/auth/access'
import {
  isProvenanceIntrospection,
  requestsExternalAction,
  authoritativeProvenance,
  formatAuthoritativeProvenance,
  restrictedProvenanceReply,
  escalationReason,
  logEscalation,
  confidenceThreshold,
  externalFallbackEnabled,
  independentReasonerHealth,
} from '@/lib/ai/cos/cosOrchestration'

export const runtime = 'nodejs'
export const dynamic = 'force-dynamic'
export const maxDuration = 300

function latestUserText(body:any):string{const messages=Array.isArray(body?.messages)?body.messages:[];for(let i=messages.length-1;i>=0;i-=1){if(messages[i]?.role!=='user')continue;const content=messages[i]?.content;if(typeof content==='string')return content;if(Array.isArray(content))return content.map((block:any)=>String(block?.text||'')).join('\n').trim()}return''}
function isOwnerRepoScanRequest(input:string):boolean{return /\b(?:scan|audit|review|inspect|analy[sz]e|look through)\b[\s\S]{0,80}\b(?:repo|repository|codebase|github)\b|\b(?:repo|repository|codebase|github)\b[\s\S]{0,80}\b(?:scan|audit|review|inspect|analy[sz]e)\b/i.test(input)}
function requestsSelfHealingAssessment(input:string):boolean{return /\bself[ -]?healing(?:\s+supervisor)?\b/i.test(input)&&/\b(?:evaluate|evaluation|report|better|improve|sellable|fortune\s*500|enterprise)\b/i.test(input)}
async function scanRepositoryForOwner():Promise<{ok:boolean;reply:string;error?:string}>{
  const [root,app,lib,onboard,rootPackage,saasPackage]=await Promise.all([listRepoFiles(),listRepoFiles('saas/app'),listRepoFiles('saas/lib'),readRepoFile('ONBOARD.md'),readRepoFile('package.json'),readRepoFile('saas/package.json')])
  const failed=[root,app,lib,onboard,rootPackage,saasPackage].find((item:any)=>!item.ok) as any
  if(failed)return{ok:false,reply:'',error:failed?.error||'Read-only repository scan failed.'}
  const routes=[...new Set((app.files||[]).filter((path:string)=>path.includes('/api/')).slice(0,20))]
  return{ok:true,reply:['Repository scan completed: SignalBoost/signalboost-live@main (read-only).','Verified '+root.files.length+' indexed root files, '+app.files.length+' application files, and '+lib.files.length+' library files in the scanned views.','Inspected canonical files: ONBOARD.md, package.json, saas/package.json.',routes.length?'Representative API routes found: '+routes.join(', ')+'.':'','I can now analyze the existing products, architecture, and improvement opportunities from this verified repository context.'].filter(Boolean).join('\n')}
}
async function assessSelfHealingSupervisor(request:string):Promise<string|null>{
  const paths=['docs/portables/self-healing-evaluation-brief.md','docs/portables/self-healing-technical-walkthrough.md','docs/portables/self-healing-security-and-data-handling.md','saas/lib/portable-products/manifests/selfHealingSupervisor.ts']
  const files=await Promise.all(paths.map(path=>readRepoFile(path)))
  if(files.some(file=>!file.ok))return null
  const evidence=files.map((file,index)=>`FILE: ${paths[index]}\n${file.content.slice(0,9000)}`).join('\n\n')
  const result=await callCosReasoner({
    temperature:.1,maxTokens:5000,
    systemPrompt:'You are COS performing a Fortune-500 product assessment. Return ONLY strict JSON: {"answer":"...","confidence":0.0}. Use only the supplied repository evidence. Write an executive report for the Self-Healing Supervisor with: current strengths; exact ideal buyer and urgent use case; enterprise-sale blockers; defensible positioning against the existing IT-operations, observability, and automation categories; prioritized integration roadmap; measurable buyer proof (for example MTTR, prevented incidents, approval-to-remediation time, rollback success); enterprise packaging (deployment, SLA/support, security questionnaire material, commercial model); prioritized improvements and why each matters; proof required for a buyer; a realistic 90-day design-partner plan; and a separate longer compliance path. Do not promise SOC 2 Type II or ISO certification in 90 days: distinguish readiness work from the operating period and external audit required for certification. Do not claim a capability unless it appears in the evidence.',
    prompt:`OWNER REQUEST:\n${request}\n\nVERIFIED REPOSITORY EVIDENCE:\n${evidence}`,
  }).catch(()=>null)
  const parsed=result?.text?parseLocalResult(result.text):null
  return parsed?.answer?.trim()||null
}
function previousAssistantText(body:any):string{const messages=Array.isArray(body?.messages)?body.messages:[];for(let i=messages.length-1;i>=0;i-=1){if(messages[i]?.role==='assistant'&&typeof messages[i]?.content==='string'&&messages[i].content.trim())return messages[i].content.trim()}return''}
function languageFrom(body:any):string{const value=String(body?.context?.language||'en').toLowerCase();return['en','es','pt','pl','ru'].includes(value)?value:'en'}
function providerFromPayload(payload:any):{provider:string|null;model:string|null}{for(const item of[payload?.execution,payload?.metadata,payload?.provenance,payload]){if(!item||typeof item!=='object')continue;const provider=typeof item.provider==='string'?item.provider:typeof item.ai_provider==='string'?item.ai_provider:typeof item.external_provider==='string'?item.external_provider:null;const model=typeof item.model==='string'?item.model:typeof item.ai_model==='string'?item.ai_model:typeof item.external_model==='string'?item.external_model:null;if(provider||model)return{provider,model}}return{provider:null,model:null}}
function normalizeProvider(value:string|null):string|null{return value==='claude'?'anthropic':value}
function externalExecution(payload:any,trace:ProviderExecutionTrace,isPrivileged:boolean):{provider:string|null;model:string|null;invoked:boolean;source:'provider'|'cache'|null}{
  const explicit=providerFromPayload(payload),source=String(payload?.source||'')
  const directAnthropic=source==='anthropic-chief'||source==='anthropic-concierge'
  if(explicit.provider||explicit.model)return{provider:normalizeProvider(explicit.provider),model:explicit.model,invoked:payload?.external_ai_invoked!==false,source:'provider'}
  if(directAnthropic)return{provider:'anthropic',model:isPrivileged?'claude-sonnet-4-6':'claude-haiku-4-5',invoked:true,source:'provider'}
  return{provider:normalizeProvider(trace.provider),model:trace.model,invoked:trace.invoked,source:trace.source}
}
function embeddedExecutionProvenance(payload:any):Record<string,unknown>|null{const value=payload?.execution_provenance;return value&&typeof value==='object'&&!Array.isArray(value)?value as Record<string,unknown>:null}
function finiteNumber(value:unknown):number|null{const parsed=Number(value);return Number.isFinite(parsed)?parsed:null}
function legacyContinuityFailure(payload:any):boolean{const text=JSON.stringify(payload??{}).toLowerCase();return text.includes('both reasoning providers are temporarily unavailable')||text.includes('continuity protection detected a primary failure')}
function noPriorReply(language:string):string{return language==='es'?'No tengo un registro de procedencia real para la respuesta inmediatamente anterior. No voy a inventarlo.':language==='pt'?'Não tenho um registro de proveniência real para a resposta imediatamente anterior. Não vou inventá-lo.':"I don't have a real provenance record for the immediately preceding answer. I won't fabricate one."}
function isRecordedProvenanceReport(text:string):boolean{return /(?:This is the real, recorded provenance|Recorded Influence Interpretation|LIVE SYSTEM STATE)/i.test(String(text||''))}
function provenanceReportFollowupReply(language:string):string{
  if(language==='es')return 'La respuesta inmediatamente anterior ya es el informe de procedencia registrado de la respuesta anterior. Sus secciones “Primary Reasoner” y “Material Contributors” identifican la fuente; no es una nueva respuesta sustantiva que requiera otro registro de procedencia.'
  if(language==='pt')return 'A resposta imediatamente anterior já é o relatório de proveniência registrado da resposta anterior. As seções “Primary Reasoner” e “Material Contributors” identificam a fonte; ela não é uma nova resposta substantiva que exija outro registro de proveniência.'
  return 'The immediately preceding reply is already the recorded provenance report for the answer before it. Its “Primary Reasoner” and “Material Contributors” sections identify the source; it is not a new substantive answer that needs a second provenance record.'
}
function emitRequestTelemetry(args:{startedAt:number;input:string;reply?:string|null;source:CosLiveResponseSource;confidence?:number|null;provenance?:any;externalAiInvoked:boolean}){const p=args.provenance??null,observation=buildCosLiveTelemetry({responseSource:args.source,latencyMs:Math.max(0,Date.now()-args.startedAt),confidence:args.confidence??null,reasonerLabel:p?.reasonerLabel??p?.local_reasoning?.model??null,localModelInvoked:p?.localModelInvoked??p?.local_reasoning?.invoked??false,externalAiInvoked:args.externalAiInvoked,knowledgeFactsUsed:p?.knowledgeFactsUsed??p?.knowledge_graph?.evidence_count??0,learnedItemsUsed:p?.learnedItemsUsed??p?.learned_corpus?.evidence_count??0,userMemoriesUsed:p?.userMemoriesUsed??p?.user_memory?.evidence_count??0,similarityScore:p?.similarityScore,promptChars:args.input.length,replyChars:String(args.reply??'').length});emitCosLiveTelemetry(observation);return observation}
function securityReleaseContinuityReply(input:string):string|null{if(!/\b(?:zero[- ]day|vulnerabilit|infosec|tenant\s+metadata)\b/i.test(input)||!/\b(?:launch|release|go\/no-go|go no-go|conference)\b/i.test(input))return null;return 'GO/NO-GO: NO-GO until the security incident authority documents containment or an accepted risk decision. Preserve evidence; stop release promotion; identify the affected dependency/version and exposure path; determine whether tenant metadata was accessible; apply or isolate the mitigation; assess notification and contractual obligations with Legal/Privacy; and reconvene the launch decision on recorded remediation evidence. Live verification or model synthesis was unavailable, so COS is not asserting exploitability, scope, or legal duties beyond the scenario facts.'}
function freshEvidenceUnavailableReply(language:string,input=''):string{const continuity=securityReleaseContinuityReply(input);if(continuity)return continuity;const messages:Record<string,string>={en:'COS requires live authoritative evidence for this current fact, but live verification is unavailable or insufficient right now. No model-memory answer was used.',es:'COS requiere evidencia autorizada en vivo para este hecho actual, pero la verificación en vivo no está disponible o es insuficiente en este momento. No se utilizó una respuesta de memoria del modelo.',pt:'O COS exige evidência autorizada ao vivo para este fato atual, mas a verificação em vivo está indisponível ou insuficiente neste momento. Nenhuma resposta da memória do modelo fue usada.',pl:'COS wymaga aktualnego, wiarygodnego źródła dla tego bieżącego faktu, ale w tej chwili weryfikacja na żywo jest niedostępna lub niewystarczająca. Nie użyto odpowiedzi z pamięci modelu.',ru:'COS требует актуального авторитетного источника для этого текущего факта, но сейчас живая проверка недоступна или недостаточна. Ответ из памяти модели не использовался.'};return messages[language]||messages.en}
function freshSynthesisRejectedReply(language:string,input=''):string{const continuity=securityReleaseContinuityReply(input);if(continuity)return continuity;return buildFreshVerificationUnavailableReply({prompt:input,language})}
function securityScenarioEvidenceIsSpecific(input:string,sources:FreshEvidenceSource[]):boolean{if(!/\b(?:zero[- ]day|vulnerabilit|infosec|tenant\s+metadata)\b/i.test(input))return true;const locator=input.match(/\bCVE-\d{4}-\d{4,}\b|\b(?:npm|pypi|maven|cargo|gem|composer)\s*[:/]\s*[@\w./-]+/i)?.[0];if(!locator)return false;return sources.some(source=>new RegExp(locator.replace(/[.*+?^${}()|[\]\\]/g,'\\$&'),'i').test(`${source.title}\n${source.snippet}\n${source.url}`))}

function lowConfidenceDraftReply(cos: Awaited<ReturnType<typeof tryCOSFirstAnswer>>, reason: { detail: string }): string | null {
  if (!cos || cos.handled || !('bestEffortReply' in cos) || !cos.bestEffortReply) return null
  return [`⚠️ Low-confidence draft (COS confidence ${cos.confidence.toFixed(2)}, below the ${confidenceThreshold().toFixed(2)} threshold; no external model was available to do better). ${reason.detail}`,'',cos.bestEffortReply].join('\n')
}
function localDraft(cos:Awaited<ReturnType<typeof tryCOSFirstAnswer>>|null):string|null{if(!cos)return null;if(cos.handled)return cos.reply;return 'bestEffortReply' in cos&&typeof cos.bestEffortReply==='string'?cos.bestEffortReply:null}
function localReasonerLabel():string{const resolved=resolveCosReasoner();return resolved.config?.label??`independent-local:${(process.env.LOCAL_AI_MODEL||'local-model').trim()}`}
function markFreshLocalReasoning(provenance:any,args:{invoked:boolean;model?:string|null;confidence?:number|null;accepted?:boolean|null}){
  if(!args.invoked)return provenance
  provenance.local_reasoning={...(provenance.local_reasoning||{}),invoked:true,model:args.model||localReasonerLabel(),confidence:args.confidence??null,threshold:confidenceThreshold()}
  provenance.fresh_local_synthesis={attempted:true,accepted:args.accepted??null}
  return provenance
}
function freshTelemetryProvenance(invoked:boolean,reasonerLabel:string|null){return{localModelInvoked:invoked,reasonerLabel}}

export async function POST(req:NextRequest){
  const startedAt=Date.now(),body=await req.clone().json().catch(()=>({})),input=latestUserText(body),language=languageFrom(body)
  if(!input)return legacyConciergePost(new NextRequest(req.clone()))
  const access=await getAccess().catch(()=>null),userId=access?.userId||null,precedingAssistant=previousAssistantText(body),isPrivileged=Boolean(access?.isOwner||access?.isAdmin)
  const freshConversationContext=resolveFreshConversationContext(body, input)
  const lookupInput=freshConversationContext.lookupInput

  if(access?.isOwner&&isOwnerRepoScanRequest(input)){
    const scan=await scanRepositoryForOwner()
    const assessmentRequested=scan.ok&&requestsSelfHealingAssessment(input)
    const assessment=assessmentRequested?await assessSelfHealingSupervisor(input):null
    const reply=assessment||(!scan.ok?`COS could not complete the read-only repository scan: ${scan.error||'unknown repository reader failure'}`:assessmentRequested?'COS completed the repository scan but could not produce the requested Self-Healing Supervisor assessment from the verified evidence. No scan inventory is being presented as a substitute for the report.':scan.reply)
    const executionProvenance=authoritativeProvenance(null,{invoked:false})
    const liveTelemetry=emitRequestTelemetry({startedAt,input,reply,source:assessment||(!assessmentRequested&&scan.ok)?'deterministic':'failed_closed',confidence:assessment||(!assessmentRequested&&scan.ok)?1:0,externalAiInvoked:false})
    await writeCosPrimaryProvenance(userId,reply,executionProvenance,assessment?'cos-self-healing-assessment':scan.ok?'cos-repository-scan':'cos-repository-scan-failed',{prompt:input,answered:Boolean(assessment)||(!assessmentRequested&&scan.ok),confidence:assessment||(!assessmentRequested&&scan.ok)?1:0,branch:assessment?'self_healing_assessment':scan.ok?'repository_scan':'repository_scan_failed'})
    return NextResponse.json({ok:Boolean(assessment)||(!assessmentRequested&&scan.ok),reply,source:assessment?'cos-self-healing-assessment':!scan.ok?'cos-repository-scan-failed':assessmentRequested?'cos-self-healing-assessment-failed':'cos-repository-scan',confidence_score:assessment||(!assessmentRequested&&scan.ok)?1:0,confidence_threshold:confidenceThreshold(),external_ai_invoked:false,external_fallback_invoked:false,local_model_invoked:Boolean(assessment),execution_provenance:executionProvenance,live_telemetry:liveTelemetry,execution_allowed:false,external_action_taken:false},{status:assessment||(!assessmentRequested&&scan.ok)?200:503})
  }

  if(isProvenanceIntrospection(input) || asksWhereTheAnswerCameFrom(input)){
    if(!isPrivileged){
      const reply=restrictedProvenanceReply(language)
      const liveTelemetry=emitRequestTelemetry({startedAt,input,reply,source:'deterministic',confidence:1,externalAiInvoked:false})
      return NextResponse.json({reply,source:'cos-provenance-restricted',confidence_score:1,confidence_threshold:confidenceThreshold(),external_ai_invoked:false,external_fallback_invoked:false,local_model_invoked:false,live_telemetry:liveTelemetry,execution_allowed:false,external_action_taken:false})
    }
    if(isRecordedProvenanceReport(precedingAssistant||'')){
      const reply=provenanceReportFollowupReply(language)
      const liveTelemetry=emitRequestTelemetry({startedAt,input,reply,source:'deterministic',confidence:1,externalAiInvoked:false})
      return NextResponse.json({reply,source:'cos-provenance-report-followup',confidence_score:1,confidence_threshold:confidenceThreshold(),external_ai_invoked:false,external_fallback_invoked:false,local_model_invoked:false,live_telemetry:liveTelemetry,execution_allowed:false,external_action_taken:false})
    }
    const prior=await readCosPrimaryPriorProvenance(userId,precedingAssistant||undefined)
    const reply=prior?formatAuthoritativeProvenance(prior as any,language):noPriorReply(language)
    const liveTelemetry=emitRequestTelemetry({startedAt,input,reply,source:'deterministic',confidence:1,externalAiInvoked:false})
    return NextResponse.json({reply,source:prior?'cos-authoritative-provenance':'cos-no-provenance-record',confidence_score:1,confidence_threshold:confidenceThreshold(),external_ai_invoked:false,external_fallback_invoked:false,local_model_invoked:false,execution_provenance:prior??undefined,live_telemetry:liveTelemetry,execution_allowed:false,external_action_taken:false})
  }

  const deterministic=tryDeterministicUtility({prompt:input,timezone:body?.context?.timezone||body?.context?.timeZone,locale:language==='pt'?'pt-BR':language==='es'?'es':language==='pl'?'pl':language==='ru'?'ru':'en-US',confidenceThreshold:confidenceThreshold()})
  if(deterministic){const liveTelemetry=emitRequestTelemetry({startedAt,input,reply:deterministic.reply,source:'deterministic',confidence:deterministic.confidence,externalAiInvoked:false});await writeCosPrimaryProvenance(userId,deterministic.reply,deterministic.executionProvenance,deterministic.source,{prompt:input,answered:true,confidence:deterministic.confidence,branch:'deterministic'});return NextResponse.json({reply:deterministic.reply,source:deterministic.source,confidence_score:deterministic.confidence,confidence_threshold:confidenceThreshold(),external_ai_invoked:false,external_fallback_invoked:false,local_model_invoked:false,execution_provenance:deterministic.executionProvenance,live_telemetry:liveTelemetry,execution_allowed:false,external_action_taken:false})}

  const requiresFreshEvidence=requiresFreshExternalEvidence(input),requestedAction=requestsExternalAction(input)

  const directCategory=requiresFreshEvidence?classifyAuthoritativeVolatileFact(input):null
  if(directCategory){
    const attemptedAt=new Date().toISOString()
    const grounded=await groundAuthoritativeVolatileFact(input,{fetch:(url,headers)=>fetch(url,{headers,cache:'no-store'})})
    if(!grounded){
      const detail='The configured authoritative source did not yield a verifiable current fact. Model-memory fallback is prohibited for this fact category.'
      const executionProvenance=attachFreshEvidenceProvenance(authoritativeProvenance(null,{invoked:false}),{sources:[],retrievedAt:attemptedAt,error:detail,synthesisAccepted:null})
      ;(executionProvenance as any).authoritative_source={used:false,attempted:true,category:directCategory.id,source_urls:directCategory.sources.map(source=>source.url),fetched_at:attemptedAt,error:detail}
      const reply=freshEvidenceUnavailableReply(language)
      const liveTelemetry=emitRequestTelemetry({startedAt,input,reply,source:'failed_closed',confidence:0,externalAiInvoked:false})
      logEscalation({event:'authoritative_direct_fact_miss',category:directCategory.id,source_urls:directCategory.sources.map(source=>source.url),external_ai_invoked:false,local_model_invoked:false})
      await writeCosPrimaryProvenance(userId,reply,executionProvenance,'cos-authoritative-source-unavailable',{prompt:input,answered:false,confidence:0,branch:'authoritative_source_unavailable'})
      return NextResponse.json({ok:false,reply,error:reply,source:'cos-authoritative-source-unavailable',confidence_score:0,confidence_threshold:confidenceThreshold(),external_ai_invoked:false,external_fallback_invoked:false,local_model_invoked:false,execution_provenance:executionProvenance,authoritative_source_attempted:true,authoritative_source_urls:directCategory.sources.map(source=>source.url),live_telemetry:liveTelemetry,execution_allowed:false,external_action_taken:false},{status:503})
    }
    const directSource:FreshEvidenceSource={id:'LIVE1',title:grounded.sourceLabel,url:grounded.sourceUrl,snippet:grounded.answer}
    const reply=renderAuthoritativeGroundedReply(grounded)
    const executionProvenance=attachFreshEvidenceProvenance(authoritativeProvenance(null,{invoked:false}),{sources:[directSource],retrievedAt:grounded.fetchedAt,error:null,synthesisAccepted:null})
    ;(executionProvenance as any).authoritative_source={used:true,attempted:true,category:grounded.categoryId,id:grounded.sourceId,label:grounded.sourceLabel,url:grounded.sourceUrl,fetched_at:grounded.fetchedAt}
    ;(executionProvenance as any).answer_origin={from_cache:false,provider:null,model:null,authoritative_source:grounded.sourceId,grounded_at:grounded.fetchedAt}
    const volatileCacheWritten=await writeVolatileAnswerCache({prompt:lookupInput,language,value:{reply,groundedAt:grounded.fetchedAt,liveSources:[directSource],externalProvider:null,externalModel:null}})
    const liveTelemetry=emitRequestTelemetry({startedAt,input,reply,source:'authoritative_source',confidence:1,externalAiInvoked:false})
    logEscalation({event:'authoritative_direct_fact_hit',category:grounded.categoryId,provider:'authoritative_source',model:grounded.sourceId,status:200,source_url:grounded.sourceUrl,external_ai_invoked:false,local_model_invoked:false})
    await writeCosPrimaryProvenance(userId,reply,executionProvenance,'cos-authoritative-source',{prompt:input,answered:true,confidence:1,branch:'authoritative_source'})
    return NextResponse.json({ok:true,reply,source:'cos-authoritative-source',confidence_score:1,confidence_threshold:confidenceThreshold(),external_ai_invoked:false,external_fallback_invoked:false,local_model_invoked:false,execution_provenance:executionProvenance,authoritative_source:{id:grounded.sourceId,label:grounded.sourceLabel,url:grounded.sourceUrl,fetched_at:grounded.fetchedAt},volatile_cache_written:volatileCacheWritten,live_evidence_retrieved_this_turn:true,live_evidence_sources:[{id:directSource.id,title:directSource.title,url:directSource.url}],live_telemetry:liveTelemetry,execution_allowed:false,external_action_taken:false})
  }

  let freshSources:FreshEvidenceSource[]=[],freshRetrievedAt:string|null=null,freshError:string|null=null
  let freshLocalAttempted=false,freshLocalModel:string|null=null
  let freshLocalFailureCode: FreshEvidenceInternalFailureCode | null = null
  if(requiresFreshEvidence){
    freshRetrievedAt=new Date().toISOString()
    const query=freshEvidenceSearchQuery(lookupInput)
    const live=await getExternalInfo(query,8,{bypassCache:true})
    freshError=live.ok?null:live.error||'Live search returned no usable evidence.'
    freshSources=live.ok?prepareFreshEvidence(live.results,8):[]
    const sources=freshSources
    const authoritySatisfied=freshEvidenceMeetsQuestionAuthority(lookupInput, sources)&&securityScenarioEvidenceIsSpecific(lookupInput,freshSources)
    logEscalation({event:'fresh_external_evidence_result',query,documents_acquired:freshSources.length,authority_satisfied:authoritySatisfied,error:freshError,source_urls:freshSources.map(source=>source.url),assistant_text_used_for_resolution:false,fresh_context_used:freshConversationContext.contextUsed})
    if(!authoritySatisfied){
      const detail=freshError||'Live search did not return authoritative evidence required for this current fact.'
      const executionProvenance=attachFreshEvidenceProvenance(authoritativeProvenance(null,{invoked:false}),{sources:freshSources,retrievedAt:freshRetrievedAt,error:detail,synthesisAccepted:false})
      ;Object.assign(executionProvenance as any, {policy:'fresh_live_data_local_first', assistant_text_used_for_resolution:false})
      const reply=freshEvidenceUnavailableReply(language,lookupInput),liveTelemetry=emitRequestTelemetry({startedAt,input,reply,source:'failed_closed',confidence:0,externalAiInvoked:false})
      await writeCosPrimaryProvenance(userId,reply,executionProvenance,'cos-fresh-evidence-unavailable',{prompt:lookupInput,answered:false,confidence:0,branch:'fresh_evidence_unavailable'})
      return NextResponse.json({ok:false,reply,error:reply,source:'cos-fresh-evidence-unavailable',confidence_score:0,confidence_threshold:confidenceThreshold(),escalation_reason_code:'insufficient_live_authority',fresh_failure_class:'insufficient_live_authority',external_ai_invoked:false,external_fallback_invoked:false,local_model_invoked:false,execution_provenance:executionProvenance,live_evidence_retrieved_this_turn:true,live_evidence_sources:freshSources.map(source=>({id:source.id,title:source.title,url:source.url})),live_telemetry:liveTelemetry,execution_allowed:false,external_action_taken:false},{status:503})
    }

    const deterministicFresh=resolveDeterministicDirectFlight(lookupInput,freshSources)
    if(deterministicFresh){
      const reply=deterministicFresh.reply
      const executionProvenance=attachFreshEvidenceProvenance(authoritativeProvenance(null,{invoked:false}),{sources:deterministicFresh.sources,retrievedAt:freshRetrievedAt,error:null,synthesisAccepted:null})
      ;Object.assign(executionProvenance as any,{policy:'fresh_live_data_deterministic_first',assistant_text_used_for_resolution:false,deterministic_fresh_fact:{used:true,kind:deterministicFresh.kind??'direct_flight',retrieval_documents_acquired:freshSources.length,evidence_selected:deterministicFresh.sources.length}})
      ;(executionProvenance as any).answer_origin={...(executionProvenance as any).answer_origin,from_cache:false,provider:null,model:null,grounded_at:freshRetrievedAt}
      logEscalation({event:'fresh_deterministic_resolution_accepted',documents_acquired:freshSources.length,evidence_selected:deterministicFresh.sources.length,kind:deterministicFresh.kind??'direct_flight',external_ai_invoked:false,local_model_invoked:false,assistant_text_used_for_resolution:false,fresh_context_used:freshConversationContext.contextUsed})
      const liveTelemetry=emitRequestTelemetry({startedAt,input,reply,source:'deterministic',confidence:deterministicFresh.confidence,provenance:freshTelemetryProvenance(false,null),externalAiInvoked:false})
      const volatileCacheWritten=await writeVolatileAnswerCache({prompt:lookupInput,language,value:{reply,groundedAt:freshRetrievedAt,liveSources:deterministicFresh.sources,externalProvider:null,externalModel:null}})
      await writeCosPrimaryProvenance(userId,reply,executionProvenance,'cos-fresh-deterministic-grounded',{prompt:lookupInput,answered:true,confidence:deterministicFresh.confidence,branch:'fresh_deterministic_grounded'})
      return NextResponse.json({ok:true,reply,source:'cos-fresh-deterministic-grounded',confidence_score:deterministicFresh.confidence,confidence_threshold:confidenceThreshold(),external_ai_invoked:false,external_fallback_invoked:false,local_model_invoked:false,execution_provenance:executionProvenance,volatile_cache_written:volatileCacheWritten,live_evidence_retrieved_this_turn:true,live_evidence_sources:deterministicFresh.sources.map(source=>({id:source.id,title:source.title,url:source.url})),live_telemetry:liveTelemetry,execution_allowed:false,external_action_taken:false})
    }

    if(!requestedAction){
      freshLocalAttempted=true
      freshLocalModel=localReasonerLabel()
      const localSynthesis=await synthesizeFreshEvidenceLocally({input:lookupInput,sources:freshSources,retrievedAt:freshRetrievedAt,language})
      if(localSynthesis.kind === 'accepted'){
        freshLocalModel=localSynthesis.reasonerLabel
        const baseProvenance=markFreshLocalReasoning(authoritativeProvenance(null,{invoked:false}),{invoked:true,model:localSynthesis.reasonerLabel,confidence:1,accepted:true})
        const executionProvenance=attachFreshEvidenceProvenance(baseProvenance,{sources:freshSources,retrievedAt:freshRetrievedAt,error:null,synthesisAccepted:true})
        ;Object.assign(executionProvenance as any,{policy:'fresh_live_data_local_first',assistant_text_used_for_resolution:false})
        ;(executionProvenance as any).answer_origin={...(executionProvenance as any).answer_origin,from_cache:false,provider:null,model:localSynthesis.reasonerLabel,grounded_at:freshRetrievedAt}
        logEscalation({event:'fresh_local_synthesis_accepted',documents_acquired:freshSources.length,reasoner:localSynthesis.reasonerLabel,external_ai_invoked:false,local_model_invoked:true,assistant_text_used_for_resolution:false,fresh_context_used:freshConversationContext.contextUsed})
        const liveTelemetry=emitRequestTelemetry({startedAt,input,reply:localSynthesis.reply,source:'local_cos_reasoning',confidence:1,provenance:freshTelemetryProvenance(true,localSynthesis.reasonerLabel),externalAiInvoked:false})
        const volatileCacheWritten=await writeVolatileAnswerCache({prompt:lookupInput,language,value:{reply:localSynthesis.reply,groundedAt:freshRetrievedAt,liveSources:freshSources,externalProvider:null,externalModel:null}})
        await writeCosPrimaryProvenance(userId,localSynthesis.reply,executionProvenance,'cos-fresh-local-grounded',{prompt:lookupInput,answered:true,confidence:0.8,branch:'fresh_local_grounded'})
        return NextResponse.json({ok:true,reply:localSynthesis.reply,source:'cos-fresh-local-grounded',confidence_score:1,confidence_threshold:confidenceThreshold(),external_ai_invoked:false,external_fallback_invoked:false,local_model_invoked:true,execution_provenance:executionProvenance,volatile_cache_written:volatileCacheWritten,live_evidence_retrieved_this_turn:true,live_evidence_sources:freshSources.map(source=>({id:source.id,title:source.title,url:source.url})),live_telemetry:liveTelemetry,execution_allowed:false,external_action_taken:false})
      }
      freshLocalFailureCode=localSynthesis.kind
      logEscalation({event:'fresh_local_synthesis_declined',failure_code:freshLocalFailureCode,documents_acquired:freshSources.length,external_ai_invoked:false,local_model_invoked:true,assistant_text_used_for_resolution:false,fresh_context_used:freshConversationContext.contextUsed})
    }
  }

  let reasoningPrompt=input
  const strategyProfileRequest=/\b(?:generate|write|create|draft)\b[\s\S]{0,100}\b(?:current )?strategy profile(?: weights?| heuristics?)?\b/i.test(input)
  if(strategyProfileRequest){
    const profile=await readStrategyProfile({privileged:isPrivileged,organizationId:body?.context?.organizationId,workspace:body?.context?.workspace})
    if('error' in profile){const reply=`COS could not read the current strategy profile: ${profile.error}`;return NextResponse.json({ok:false,reply,error:reply,source:'cos-strategy-profile-unavailable',external_ai_invoked:false,external_fallback_invoked:false,local_model_invoked:false,execution_allowed:false,external_action_taken:false},{status:503})}
    const overrides=appliedStrategyOverrides(profile.profile)
    reasoningPrompt=`${input}\n\nCURRENT DERIVED STRATEGY PROFILE (internal system of record): ${JSON.stringify(profile.profile)}\nAPPLIED OVERRIDES: ${JSON.stringify(overrides)}\nGenerate the requested content. Then add an Evidence Used section: for every learned override, name its dimension, winning value, performance score, measured-campaign count, runner-up comparison, and supporting campaign IDs from the profile. If overrides is empty, state that measured outcomes did not justify changing defaults; do not claim missing configuration.`
  }
  let cos:Awaited<ReturnType<typeof tryCOSFirstAnswer>>|null=null,localError:string|null=null
  if(!requestedAction&&!requiresFreshEvidence){
    try{cos=await tryCOSFirstAnswer({prompt:reasoningPrompt,previousAssistant:precedingAssistant||null,userId,language,privileged:isPrivileged,disableCache:strategyProfileRequest})}catch(error){localError=error instanceof Error?error.message:String(error);console.error('[cos-local-reasoner-error]',localError)}
  }
  if(cos?.handled){const executionProvenance=authoritativeProvenance(cos,{invoked:false}),source:CosLiveResponseSource=cos.provenance.responseSource as CosLiveResponseSource,liveTelemetry=emitRequestTelemetry({startedAt,input,reply:cos.reply,source,confidence:cos.confidence,provenance:cos.provenance,externalAiInvoked:false}),responseSource=cos.provenance.responseSource==='semantic_cache'||cos.provenance.responseSource==='semantic_similarity'?'cos-semantic-cache':'cos-local-primary';await writeCosPrimaryProvenance(userId,cos.reply,executionProvenance,responseSource);return NextResponse.json({reply:cos.reply,source:responseSource,confidence_score:cos.confidence,confidence_threshold:confidenceThreshold(),external_ai_invoked:false,external_fallback_invoked:false,local_model_invoked:cos.provenance.localModelInvoked,execution_provenance:executionProvenance,provenance:cos.provenance,live_telemetry:liveTelemetry,execution_allowed:false,external_action_taken:false})}

  const freshFailureCode: FreshEvidenceInternalFailureCode | null = requiresFreshEvidence
    ? (freshLocalFailureCode ?? 'local_synthesis_unparseable')
    : null
  const reason=requiresFreshEvidence?{code:freshFailureCode!,detail:freshFailureCode === 'local_synthesis_failed'
    ? 'Authoritative live evidence was retrieved, but bounded local synthesis failed after transport retries.'
    : 'Authoritative live evidence was retrieved, but no completed synthesis satisfied the grounding contract.'}:escalationReason(cos,localError,requestedAction)
  logEscalation({event:'external_escalation_decision',reason_code:reason.code,reason:reason.detail,confidence:cos?.confidence??null,threshold:confidenceThreshold(),local_model_invoked:requiresFreshEvidence?freshLocalAttempted:(cos?.provenance?.localModelInvoked??false),local_model:requiresFreshEvidence?freshLocalModel:(cos?.provenance?.reasonerLabel??null),semantic_cache_hit:cos?.provenance?.responseSource==='semantic_cache'||cos?.provenance?.responseSource==='semantic_similarity',knowledge_facts_used:cos?.provenance?.knowledgeFactsUsed??0,learned_items_used:cos?.provenance?.learnedItemsUsed??0,external_action_requested:requestedAction,fallback_enabled:externalFallbackEnabled(),fresh_evidence_required:requiresFreshEvidence,fresh_documents_acquired:freshSources.length})

  if(!externalFallbackEnabled()){
    let baseProvenance=authoritativeProvenance(cos,{invoked:false})
    if(requiresFreshEvidence)baseProvenance=markFreshLocalReasoning(baseProvenance,{invoked:freshLocalAttempted,model:freshLocalModel,accepted:false})
    const executionProvenance=requiresFreshEvidence&&freshRetrievedAt?attachFreshEvidenceProvenance(baseProvenance,{sources:freshSources,retrievedAt:freshRetrievedAt,error:freshFailureCode === 'local_synthesis_failed'
      ? 'Authoritative live evidence was retrieved, but local fresh-evidence synthesis failed after bounded transport retries.'
      : 'Authoritative live evidence was retrieved, but the completed fresh-evidence synthesis did not satisfy the grounding contract.',synthesisAccepted:false}):baseProvenance
    if(requiresFreshEvidence)Object.assign(executionProvenance as any,{policy:'fresh_live_data_local_first',assistant_text_used_for_resolution:false})
    const reply=requiresFreshEvidence?(freshFailureReply(freshFailureCode!,language) ?? freshEvidenceUnavailableReply(language,lookupInput)):(lowConfidenceDraftReply(cos,reason)??buildHonestRefusalReply({prompt:input,language})),liveTelemetry=emitRequestTelemetry({startedAt,input,reply,source:'failed_closed',confidence:cos?.confidence??0,provenance:requiresFreshEvidence?freshTelemetryProvenance(freshLocalAttempted,freshLocalModel):cos?.provenance,externalAiInvoked:false})
    await writeCosPrimaryProvenance(userId,reply,executionProvenance,'failed_closed',{prompt:requiresFreshEvidence?lookupInput:input,answered:false,confidence:0,branch:'failed_closed'})
    return NextResponse.json({ok:false,reply,error:reply,source:freshFailureCode === 'local_synthesis_failed' ? 'cos-fresh-local-synthesis-failed' : 'cos-fresh-evidence-ungrounded',cos_first_attempted:requiresFreshEvidence?freshLocalAttempted:(Boolean(cos)||Boolean(localError)),cos_first_handled:false,cos_first_confidence:cos?.confidence??0,confidence_threshold:confidenceThreshold(),cos_first_reason:reason.detail,escalation_reason_code:reason.code,fresh_failure_class:freshFailureCode,independent_reasoner:await independentReasonerHealth(),external_ai_invoked:false,external_fallback_invoked:false,isolation_mode:true,execution_provenance:executionProvenance,live_evidence_retrieved_this_turn:requiresFreshEvidence,live_evidence_sources:requiresFreshEvidence?freshSources.map(source=>({id:source.id,title:source.title,url:source.url})):[],live_telemetry:liveTelemetry,execution_allowed:false,external_action_taken:false},{status:503})
  }

  if(requiresFreshEvidence&&freshRetrievedAt){
    const externalFresh=await synthesizeFreshEvidenceExternally({ input: lookupInput, sources:freshSources,retrievedAt:freshRetrievedAt,language})
    const externalInvoked=externalFresh.source==='provider'||(externalFresh.source===null&&externalFresh.attempted)
    const externalProvider=normalizeProvider(externalFresh.provider)
    let baseProvenance=authoritativeProvenance(null,{invoked:externalInvoked,provider:externalProvider,model:externalFresh.model})
    baseProvenance=markFreshLocalReasoning(baseProvenance,{invoked:freshLocalAttempted,model:freshLocalModel,accepted:false})
    const executionProvenance=attachFreshEvidenceProvenance(baseProvenance,{sources:freshSources,retrievedAt:freshRetrievedAt,error:externalFresh.accepted?null:'Fresh-evidence synthesis was unavailable or rejected by the evidence contract.',synthesisAccepted:externalFresh.accepted})
    ;Object.assign(executionProvenance as any, {policy:'fresh_live_data_local_first', assistant_text_used_for_resolution:false})
    logEscalation({event:'fresh_external_synthesis_result',provider:externalProvider,model:externalFresh.model,provider_source:externalFresh.source,external_ai_invoked:externalInvoked,local_model_invoked:freshLocalAttempted,fresh_documents_acquired:freshSources.length,fresh_synthesis_accepted:externalFresh.accepted})

    if(!externalFresh.accepted||!externalFresh.reply){
      const freshFailureCode: FreshEvidenceInternalFailureCode = 'citation_grounding_rejected'
      const reply=freshFailureReply(freshFailureCode,language)!
      const liveTelemetry=emitRequestTelemetry({startedAt,input,reply,source:'failed_closed',confidence:0,provenance:freshTelemetryProvenance(freshLocalAttempted,freshLocalModel),externalAiInvoked:externalInvoked})
      await writeCosPrimaryProvenance(userId,reply,executionProvenance,'cos-fresh-evidence-synthesis-rejected',{prompt:lookupInput,answered:false,confidence:0,branch:'fresh_evidence_synthesis_rejected'})
      return NextResponse.json({ok:false,reply,error:reply,source:'cos-fresh-evidence-ungrounded',confidence_score:0,confidence_threshold:confidenceThreshold(),escalation_reason_code:freshFailureCode,fresh_failure_class:freshFailureCode,external_ai_invoked:externalInvoked,external_provider:externalProvider,external_model:externalFresh.model,external_provider_source:externalFresh.source,external_fallback_invoked:externalInvoked,external_fallback_succeeded:false,local_model_invoked:freshLocalAttempted,execution_provenance:executionProvenance,live_evidence_retrieved_this_turn:true,live_evidence_sources:freshSources.map(source=>({id:source.id,title:source.title,url:source.url})),live_telemetry:liveTelemetry,execution_allowed:false,external_action_taken:false},{status:503})
    }

    const reply=externalFresh.reply
    ;(executionProvenance as any).answer_origin={...(executionProvenance as any).answer_origin,from_cache:false,provider:externalProvider,model:externalFresh.model,grounded_at:freshRetrievedAt}
    const volatileCacheWritten=await writeVolatileAnswerCache({prompt:lookupInput,language,value:{reply,groundedAt:freshRetrievedAt,liveSources:freshSources,externalProvider,externalModel:externalFresh.model}})
    const liveTelemetry=emitRequestTelemetry({startedAt,input,reply,source:externalInvoked?'external_fallback':'local_cos_reasoning',confidence:1,provenance:freshTelemetryProvenance(freshLocalAttempted||externalFresh.source==='local',freshLocalModel||externalFresh.model),externalAiInvoked:externalInvoked})
    await writeCosPrimaryProvenance(userId,reply,executionProvenance,externalInvoked?'external_fresh_grounded':'cos-fresh-local-grounded',{prompt:lookupInput,answered:true,confidence:0.9,branch:externalInvoked?'external_fresh_grounded':'fresh_local_grounded'})
    return NextResponse.json({ok:true,reply,source:externalInvoked?'external_fresh_grounded':'cos-fresh-local-grounded',confidence_score:1,confidence_threshold:confidenceThreshold(),cos_first_attempted:freshLocalAttempted,cos_first_handled:false,cos_first_confidence:null,cos_first_reason:reason.detail,escalation_reason_code:reason.code,execution_provenance:executionProvenance,external_ai_invoked:externalInvoked,external_provider:externalInvoked?externalProvider:null,external_model:externalInvoked?externalFresh.model:null,external_provider_source:externalInvoked?externalFresh.source:null,external_fallback_invoked:externalInvoked,external_fallback_succeeded:externalInvoked,local_model_invoked:freshLocalAttempted||externalFresh.source==='local',isolation_mode:false,volatile_cache_written:volatileCacheWritten,live_evidence_retrieved_this_turn:true,live_evidence_sources:freshSources.map(source=>({id:source.id,title:source.title,url:source.url})),live_telemetry:liveTelemetry,execution_allowed:false,external_action_taken:false})
  }

  const traced=await withCosProviderExecutionTrace(()=>legacyConciergePost(new NextRequest(req.clone()))),response=traced.result
  try{
    const payload=await response.clone().json(),continuityFailed=legacyContinuityFailure(payload),external=externalExecution(payload,traced.trace,isPrivileged),externalInvoked=!continuityFailed&&external.invoked,reasonerHealth=continuityFailed?await independentReasonerHealth():null,rawReply=String(payload?.reply||'')
    const embedded=embeddedExecutionProvenance(payload)
    const embeddedExternalInvoked=Boolean((embedded as any)?.external_ai?.invoked)
    const embeddedMatchesGenerator=Boolean(embedded)&&(!externalInvoked||embeddedExternalInvoked)
    const executionProvenance=continuityFailed
      ? authoritativeProvenance(cos,{invoked:false})
      : embeddedMatchesGenerator
        ? embedded!
        : authoritativeProvenance(cos,{invoked:externalInvoked,provider:external.provider,model:external.model})
    const reply=continuityFailed?(lowConfidenceDraftReply(cos,reason)??`COS independent reasoning could not complete this request: ${reason.detail} External fallback was also unavailable. No action was executed.`):rawReply
    const innerSource=String(payload?.source||'').trim()
    const responseSource=continuityFailed?'cos-independent-reasoner-unavailable':externalInvoked?'external_fallback':innerSource&&innerSource!=='external_fallback'?innerSource:'cos-local-retry'
    const finalConfidence=finiteNumber(payload?.confidence_score)??finiteNumber((executionProvenance as any)?.local_reasoning?.confidence)??(continuityFailed?cos?.confidence??0:null)
    const finalLocalModelInvoked=Boolean((executionProvenance as any)?.local_reasoning?.invoked??payload?.local_model_invoked??cos?.provenance?.localModelInvoked)
    const telemetrySource:CosLiveResponseSource=continuityFailed?'failed_closed':externalInvoked?'external_fallback':'local_cos_reasoning'
    const liveTelemetry=emitRequestTelemetry({startedAt,input,reply,source:telemetrySource,confidence:finalConfidence,provenance:executionProvenance,externalAiInvoked:externalInvoked})
    logEscalation({event:'external_escalation_result',reason_code:reason.code,provider:external.provider,model:external.model,status:response.status,continuity_failed:continuityFailed,external_ai_invoked:externalInvoked,provider_source:external.source,independent_reasoner:reasonerHealth,fresh_evidence_required:false,final_response_source:responseSource,final_confidence:finalConfidence,embedded_response_provenance:embeddedMatchesGenerator})
    if(externalInvoked&&!continuityFailed&&reply){await recordTeacherEscalation({prompt:input,localAnswer:localDraft(cos),localConfidence:cos?.confidence??null,escalationReason:reason.detail,teacherAnswer:reply,teacherProvider:external.provider,teacherModel:external.model,metadata:{reasonCode:reason.code,responseStatus:response.status}})}
    if(reply)await writeCosPrimaryProvenance(userId,reply,executionProvenance,responseSource)
    return NextResponse.json({...payload,reply,source:responseSource,confidence_score:finalConfidence,cos_first_attempted:Boolean(cos)||Boolean(localError),cos_first_handled:Boolean(cos?.handled),cos_first_confidence:cos?.confidence??null,confidence_threshold:confidenceThreshold(),cos_first_reason:reason.detail,escalation_reason_code:reason.code,independent_reasoner:reasonerHealth,cos_first_provenance:cos?.provenance??null,execution_provenance:executionProvenance,external_ai_invoked:externalInvoked,external_provider:externalInvoked?external.provider:null,external_model:externalInvoked?external.model:null,external_provider_source:externalInvoked?external.source:null,external_fallback_invoked:externalInvoked,external_fallback_succeeded:externalInvoked&&!continuityFailed,local_model_invoked:finalLocalModelInvoked,isolation_mode:false,live_telemetry:liveTelemetry},{status:response.status})
  }catch(error){const externalInvoked=Boolean(traced.trace.invoked);logEscalation({event:'external_escalation_result_unparsed',reason_code:reason.code,provider:normalizeProvider(traced.trace.provider),model:traced.trace.model,status:response.status,error:error instanceof Error?error.message:String(error),external_ai_invoked:externalInvoked});emitRequestTelemetry({startedAt,input,source:externalInvoked?'external_fallback':'local_cos_reasoning',confidence:cos?.confidence??null,provenance:cos?.provenance,externalAiInvoked:externalInvoked});return response}
}
