import type { RiskLevel, TenantContext } from './types.ts';

export const EAE_ENTERPRISE_CONTEXT_SCHEMA_VERSION = '2.0.0' as const;
export type EntityType = 'organization' | 'business_unit' | 'team' | 'user' | 'role' | 'system' | 'application' | 'infrastructure' | 'provider' | 'workflow' | 'business_process' | 'policy' | 'objective' | 'dependency' | 'risk' | 'control' | 'capability';
export type RelationshipType = 'owns' | 'operates' | 'depends_on' | 'provides' | 'consumes' | 'governed_by' | 'approved_by' | 'monitored_by' | 'executes' | 'verifies' | 'affects' | 'blocks' | 'supports' | 'conflicts_with';
type Json = null | boolean | number | string | readonly Json[] | { readonly [key: string]: Json };

export interface Provenance { readonly source: string; readonly observedBy?: string; readonly evidenceRefs: readonly string[]; }
export interface DigitalTwinEntity { readonly schemaVersion: typeof EAE_ENTERPRISE_CONTEXT_SCHEMA_VERSION; readonly entityId: string; readonly tenant: TenantContext; readonly entityType: EntityType; readonly displayName: string; readonly status: string; readonly provenance: Provenance; readonly observedAt: string; readonly effectiveAt: string; readonly metadata: Readonly<Record<string, Json>>; readonly region?: string; readonly critical?: boolean; }
export interface EnterpriseRelationship { readonly schemaVersion: typeof EAE_ENTERPRISE_CONTEXT_SCHEMA_VERSION; readonly relationshipId: string; readonly tenant: TenantContext; readonly type: RelationshipType; readonly fromEntityId: string; readonly toEntityId: string; readonly provenance: Provenance; readonly observedAt: string; readonly effectiveAt: string; readonly metadata: Readonly<Record<string, Json>>; }
export interface EnterpriseObjective extends DigitalTwinEntity { readonly entityType: 'objective'; readonly ownerEntityId: string; readonly priority: number; readonly targetMetrics: Readonly<Record<string, number>>; readonly constraints: readonly string[]; readonly deadline?: string; readonly affectedBusinessUnitIds: readonly string[]; readonly affectedSystemIds: readonly string[]; }
export interface EnterprisePolicy extends DigitalTwinEntity { readonly entityType: 'policy'; readonly scope: { readonly region?: string; readonly businessUnitId?: string; readonly systemId?: string; readonly workflowId?: string; readonly actionCategory?: string; readonly riskLevel?: RiskLevel }; readonly precedence: number; readonly effect: 'allow' | 'deny' | 'require_review'; }
export interface EnterpriseCapability extends DigitalTwinEntity { readonly entityType: 'capability'; readonly category: 'cos_orchestration' | 'portable' | 'customer_provided' | 'human_approval' | 'verification' | 'reporting'; readonly reference: string; }
export interface ContextGap { readonly code: string; readonly severity: 'warning' | 'critical'; readonly entityId?: string; readonly detail: string; }
export interface RelevanceResult { readonly includedEntityIds: readonly string[]; readonly excludedEntityIds: readonly string[]; readonly inclusionReasons: Readonly<Record<string, readonly string[]>>; readonly relationshipPaths: readonly (readonly string[])[]; readonly scores: Readonly<Record<string, number>>; readonly truncated: boolean; }
export interface ContextSnapshot { readonly schemaVersion: typeof EAE_ENTERPRISE_CONTEXT_SCHEMA_VERSION; readonly snapshotId: string; readonly tenant: TenantContext; readonly snapshotAt: string; readonly entities: readonly DigitalTwinEntity[]; readonly relationships: readonly EnterpriseRelationship[]; readonly activeObjectives: readonly EnterpriseObjective[]; readonly applicablePolicies: readonly EnterprisePolicy[]; readonly systemDependencies: readonly EnterpriseRelationship[]; readonly risks: readonly DigitalTwinEntity[]; readonly capabilities: readonly EnterpriseCapability[]; readonly evidenceReferences: readonly string[]; readonly relevance: RelevanceResult; readonly gaps: readonly ContextGap[]; }
export interface ContextRequest { readonly tenant: TenantContext; readonly observationSubjects?: readonly string[]; readonly affectedEntityIds?: readonly string[]; readonly affectedBusinessUnitIds?: readonly string[]; readonly activeObjectiveIds?: readonly string[]; readonly actionCategory?: string; readonly riskLevel?: RiskLevel; readonly maxDepth: number; readonly maxEntities: number; readonly snapshotAt: string; }

const secret = /(secret|token|password|credential|authorization|private.?key|api.?key)/i;
const metadataAllowed = new Set(['classification', 'criticality', 'lifecycle', 'tags', 'externalReference', 'riskLevel', 'actionCategory', 'description']);
function canonical(v: unknown): string { if (Array.isArray(v)) return `[${v.map(canonical).join(',')}]`; if (v && typeof v === 'object') return `{${Object.entries(v as Record<string, unknown>).sort(([a],[b]) => a.localeCompare(b)).map(([k,x]) => `${JSON.stringify(k)}:${canonical(x)}`).join(',')}}`; const encoded = JSON.stringify(v); if (encoded === undefined) throw new Error('non_json_value_rejected'); return encoded; }
function hash(v: unknown): string { let h=2166136261; for (const c of canonical(v)) { h ^= c.charCodeAt(0); h=Math.imul(h,16777619); } return (h>>>0).toString(16).padStart(8,'0'); }
function freeze<T>(v:T):T { if (!v || typeof v !== 'object' || Object.isFrozen(v)) return v; Object.freeze(v); for (const x of Object.values(v as Record<string, unknown>)) freeze(x); return v; }
function safe(v: unknown, p='value'): asserts v is Json { if (typeof v === 'function'||typeof v === 'symbol'||typeof v === 'bigint') throw new Error(`${p}_executable_rejected`); if(typeof v==='number'&&!Number.isFinite(v)) throw new Error(`${p}_non_finite_number`); if(!v||typeof v!=='object') return; for(const [k,x] of Object.entries(v as Record<string,unknown>)){ if(secret.test(k)) throw new Error(`${p}_secret_rejected`); safe(x,`${p}.${k}`); } }
function tenantKey(t:TenantContext) { return `${t.tenantId}:${t.environmentId}`; }
function validateEntity(e:DigitalTwinEntity, tenant:TenantContext) { if(e.schemaVersion!==EAE_ENTERPRISE_CONTEXT_SCHEMA_VERSION) throw new Error('unsupported_schema'); if(!e.entityId||!e.displayName||!e.status||!e.provenance?.source) throw new Error('invalid_entity'); if(tenantKey(e.tenant)!==tenantKey(tenant)) throw new Error('tenant_environment_boundary_violation'); if(!Number.isFinite(Date.parse(e.observedAt))||!Number.isFinite(Date.parse(e.effectiveAt))) throw new Error('invalid_timestamp'); for(const k of Object.keys(e.metadata)){if(!metadataAllowed.has(k)) throw new Error('metadata_not_allowlisted');} safe(e.metadata,'metadata'); }

export class EnterpriseRelationshipGraph {
  readonly tenant: TenantContext; private readonly entities = new Map<string,DigitalTwinEntity>(); private readonly edges = new Map<string,EnterpriseRelationship>();
  constructor(tenant: TenantContext, entities: readonly DigitalTwinEntity[] = [], relationships: readonly EnterpriseRelationship[] = []) { if(!tenant.tenantId||!tenant.environmentId) throw new Error('tenant_required'); this.tenant=freeze({...tenant}); entities.forEach(e=>this.addEntity(e)); relationships.forEach(e=>this.addRelationship(e)); }
  addEntity(entity:DigitalTwinEntity):void { validateEntity(entity,this.tenant); if(this.entities.has(entity.entityId)) throw new Error('duplicate_entity_id'); this.entities.set(entity.entityId,freeze({...entity})); }
  addRelationship(edge:EnterpriseRelationship):void { if(edge.schemaVersion!==EAE_ENTERPRISE_CONTEXT_SCHEMA_VERSION) throw new Error('unsupported_schema'); if(tenantKey(edge.tenant)!==tenantKey(this.tenant)) throw new Error('tenant_environment_boundary_violation'); if(!this.entities.has(edge.fromEntityId)||!this.entities.has(edge.toEntityId)) throw new Error('unknown_entity'); if(!edge.relationshipId||!edge.provenance?.source) throw new Error('invalid_relationship'); safe(edge.metadata,'relationship_metadata'); const key=`${edge.type}:${edge.fromEntityId}:${edge.toEntityId}`; if(this.edges.has(key)||[...this.edges.values()].some(x=>x.relationshipId===edge.relationshipId)) throw new Error('duplicate_relationship'); this.edges.set(key,freeze({...edge})); }
  snapshot(): { readonly entities: readonly DigitalTwinEntity[]; readonly relationships: readonly EnterpriseRelationship[] } { return freeze({entities:[...this.entities.values()].sort((a,b)=>a.entityId.localeCompare(b.entityId)),relationships:[...this.edges.values()].sort((a,b)=>a.relationshipId.localeCompare(b.relationshipId))}); }
  traverse(startIds:readonly string[], maxDepth:number): readonly (readonly string[])[] { if(!Number.isInteger(maxDepth)||maxDepth<0||maxDepth>8) throw new Error('unbounded_traversal_rejected'); startIds.forEach(x=>{if(!this.entities.has(x)) throw new Error('unknown_entity');}); const paths:string[][]=[]; const queue=startIds.slice().sort().map(x=>[x]); while(queue.length){const path=queue.shift()!; paths.push(path); if(path.length-1===maxDepth) continue; const last=path.at(-1)!; for(const edge of [...this.edges.values()].filter(e=>e.fromEntityId===last).sort((a,b)=>a.relationshipId.localeCompare(b.relationshipId))){if(!path.includes(edge.toEntityId)) queue.push([...path,edge.toEntityId]);}} return freeze(paths.map(x=>freeze(x))); }
}

export function resolvePolicies(policies:readonly EnterprisePolicy[], request:ContextRequest): { readonly policies:readonly EnterprisePolicy[]; readonly conflicts:readonly string[]; readonly blocked:boolean } { const matching=policies.filter(p=>{const s=p.scope; return (!s.region||s.region===request.tenant.region)&&(!s.actionCategory||s.actionCategory===request.actionCategory)&&(!s.riskLevel||s.riskLevel===request.riskLevel);}).sort((a,b)=>b.precedence-a.precedence||a.entityId.localeCompare(b.entityId)); const conflicts=[...new Set(matching.flatMap((p,i)=>matching.slice(i+1).filter(q=>q.precedence===p.precedence&&q.effect!==p.effect).flatMap(q=>[p.entityId,q.entityId])))] .sort(); return freeze({policies:matching,conflicts,blocked:conflicts.some(id=>matching.find(p=>p.entityId===id)?.scope.riskLevel==='critical')}); }
export function buildEnterpriseContextSnapshot(graph:EnterpriseRelationshipGraph, request:ContextRequest):ContextSnapshot { if(!Number.isInteger(request.maxEntities)||request.maxEntities<1||request.maxEntities>256) throw new Error('unbounded_context_request_rejected'); const all=graph.snapshot(); const seeds=[...(request.affectedEntityIds??[]),...(request.activeObjectiveIds??[])].sort(); const paths=graph.traverse(seeds,request.maxDepth); const score=new Map<string,number>(); const reasons:Record<string,string[]>={}; for(const path of paths){const id=path.at(-1)!; score.set(id,Math.max(score.get(id)??0,100-path.length)); (reasons[id]??=[]).push(path.length===1?'directly_affected':'dependency_path');} for(const e of all.entities){if((request.observationSubjects??[]).includes(e.entityId)|| (request.affectedBusinessUnitIds??[]).includes(e.entityId)){score.set(e.entityId,120); (reasons[e.entityId]??=[]).push('request_subject');}} const ordered=[...score.entries()].sort((a,b)=>b[1]-a[1]||a[0].localeCompare(b[0])); const ids=ordered.slice(0,request.maxEntities).map(x=>x[0]); const set=new Set(ids); const entities=all.entities.filter(e=>set.has(e.entityId)); const relationships=all.relationships.filter(e=>set.has(e.fromEntityId)&&set.has(e.toEntityId)); const objectives=entities.filter((x):x is EnterpriseObjective=>x.entityType==='objective'&&x.status==='active'); const policies=entities.filter((x):x is EnterprisePolicy=>x.entityType==='policy'); const resolved=resolvePolicies(policies,request); const gaps:ContextGap[]=[]; for(const e of entities){if(e.entityType==='system'&&!all.relationships.some(r=>r.type==='owns'&&r.toEntityId===e.entityId)) gaps.push({code:'unknown_system_owner',severity:e.critical?'critical':'warning',entityId:e.entityId,detail:'No owning entity is modeled'}); if(e.status==='conflicting') gaps.push({code:'conflicting_entity_status',severity:'critical',entityId:e.entityId,detail:'Entity status is conflicting'});} if(resolved.conflicts.length) gaps.push({code:'policy_conflict',severity:resolved.blocked?'critical':'warning',detail:resolved.conflicts.join(',')}); const relevance:RelevanceResult={includedEntityIds:ids,excludedEntityIds:all.entities.filter(e=>!set.has(e.entityId)).map(e=>e.entityId),inclusionReasons:reasons,relationshipPaths:paths.filter(p=>set.has(p.at(-1)!)),scores:Object.fromEntries(ordered),truncated:ordered.length>request.maxEntities}; const base={schemaVersion:EAE_ENTERPRISE_CONTEXT_SCHEMA_VERSION,tenant:graph.tenant,snapshotAt:request.snapshotAt,entities,relationships,activeObjectives:objectives,applicablePolicies:resolved.policies,systemDependencies:relationships.filter(x=>x.type==='depends_on'),risks:entities.filter(x=>x.entityType==='risk'),capabilities:entities.filter((x):x is EnterpriseCapability=>x.entityType==='capability'),evidenceReferences:[...new Set(entities.flatMap(x=>x.provenance.evidenceRefs))].sort(),relevance,gaps}; return freeze({...base,snapshotId:`eae_context_${hash(base)}`}); }

export interface EaeEnterpriseMemoryPorts { readonly entityLookup:{lookup(tenant:TenantContext, ids:readonly string[]):Promise<readonly DigitalTwinEntity[]>}; readonly relationshipLookup:{lookup(tenant:TenantContext, entityIds:readonly string[]):Promise<readonly EnterpriseRelationship[]>}; readonly historicalContextLookup:{lookup(tenant:TenantContext, subject:string):Promise<readonly Json[]>}; readonly historicalDecisionLookup:{lookup(tenant:TenantContext, subject:string):Promise<readonly Json[]>}; readonly historicalVerificationLookup:{lookup(tenant:TenantContext, subject:string):Promise<readonly Json[]>}; readonly objectiveLookup:{lookup(tenant:TenantContext, ids:readonly string[]):Promise<readonly EnterpriseObjective[]>}; readonly policyLookup:{lookup(tenant:TenantContext):Promise<readonly EnterprisePolicy[]>}; }
