'use client'

import { createContext, useContext, useEffect, useMemo, useState } from 'react'
import { detectLanguage } from '@/lib/i18n/detectLanguage'

type Dict = Record<string, string>
type Lang = 'en' | 'es' | 'pt' | 'pl' | 'ru'

const en: Dict = {
  'nav.home': 'Home', 'nav.marketplace': 'Marketplace', 'nav.podcasters': 'Podcasters', 'nav.pricing': 'Pricing', 'nav.docs': 'Docs', 'nav.dashboard': 'Dashboard', 'nav.logout': 'Log out',
  'nav.promote': 'Promote Business', 'nav.reviews': 'Reviews', 'nav.calendar': 'Calendar', 'nav.spreadsheets': 'Spreadsheets', 'nav.outreach': 'Outreach', 'nav.assistant': 'Personal Assistant',
  'landing.kicker': 'Native multilingual growth', 'landing.title': 'SignalBoost creates websites, reviews, audio, and video for every market.', 'landing.subtitle': 'Launch localized workflows in English, Spanish, Portuguese, Polish, and Russian with English fallback.', 'landing.cta': 'Open dashboard', 'landing.secondary': 'View pricing',
  'pages.podcasters.title': 'Podcaster information', 'pages.pricing.title': 'Subscription pricing', 'pages.docs.title': 'Documentation', 'pages.support.title': 'Support', 'pages.faq.title': 'FAQ',
  'pricing.kicker': 'Marketplace + SaaS in one SignalBoost cockpit', 'pricing.subtitle': 'Every plan links SaaS modules inside SignalBoost: Promote Business, Reviews, Calendar, Spreadsheets, Outreach, and Personal Assistant.', 'pricing.modules.title': 'Open SaaS modules in SignalBoost', 'pricing.modules.subtitle': 'No separate SaaS repo is required; Vercel deploys these routes when main is merged.', 'pricing.tier.launch': 'Launch', 'pricing.tier.growth': 'Growth', 'pricing.tier.command': 'Command',
  'dashboard.overview': 'Cockpit Overview', 'dashboard.telemetryActive': 'Telemetry active', 'dashboard.telemetryCopy': 'Module usage, Concierge intents, and Marketplace context are logged in SignalBoost Admin Console.',
  'cockpit.kicker': 'Unified SignalBoost cockpit', 'cockpit.wireframe.missionSignal': 'Mission signal summary across Marketplace and SaaS modules', 'cockpit.wireframe.coreSystems': 'Core systems: Reviews, Promote Business, Calendar, Spreadsheets, Outreach, Assistant', 'cockpit.wireframe.conciergeBand': 'Concierge band routes questions to the best module and next action', 'cockpit.askConcierge': 'Ask Concierge AI', 'cockpit.missionRole': 'Mission role', 'cockpit.telemetryChecklist': 'Telemetry checklist', 'cockpit.event': 'Event', 'cockpit.allModules': 'All cockpit modules',
  'module.promote.label': 'Promote Business', 'module.promote.description': 'Plan multilingual campaigns, launch offers, and connect promotions to Marketplace demand signals.', 'module.promote.role': 'Growth launch control',
  'module.reviews.label': 'Reviews', 'module.reviews.description': 'Collect, triage, translate, and reuse customer proof inside brand and Marketplace workflows.', 'module.reviews.role': 'Trust and reputation desk',
  'module.calendar.label': 'Calendar', 'module.calendar.description': 'Schedule SaaS launches, outreach windows, local holidays, review asks, and Marketplace booking moments.', 'module.calendar.role': 'Mission timeline',
  'module.spreadsheets.label': 'Spreadsheets', 'module.spreadsheets.description': 'Import CSV lists, normalize contacts, track KPIs, and route spreadsheet rows into Outreach.', 'module.spreadsheets.role': 'Data operations grid',
  'module.outreach.label': 'Outreach', 'module.outreach.description': 'Coordinate email, partner notifications, social prompts, and review follow-ups from one cockpit.', 'module.outreach.role': 'Communications console',
  'module.assistant.label': 'Personal Assistant', 'module.assistant.description': 'Use one Concierge AI layer to route questions across Marketplace, SaaS modules, pricing, and next actions.', 'module.assistant.role': 'Concierge AI automations',
  'reviews.stage': 'Reviews Stage 1', 'reviews.title': 'Collect multilingual customer reviews with smart routing.', 'reviews.subtitle': 'Invite customers to leave star ratings, comments, and optional photo or video proof. SignalBoost stores the review, alerts your team, and routes low scores for recovery before publishing.',
  'reviews.formTitle': 'Collect a review', 'reviews.name': 'Customer name', 'reviews.email': 'Customer email', 'reviews.rating': 'Star rating', 'reviews.comment': 'Comment', 'reviews.upload': 'Photo or video proof', 'reviews.language': 'Review language', 'reviews.route': 'Smart route', 'reviews.public': 'Ready for public proof', 'reviews.recovery': 'Route to recovery workflow', 'reviews.submit': 'Save review', 'reviews.success': 'Review captured and routed.', 'reviews.error': 'Could not save review yet.',
  'reviews.stage1': 'Collect reviews with Supabase + Resend alerts', 'reviews.stage2': 'Display Google reviews after API approval', 'reviews.stage3': 'Monitor sentiment and respond with approval',
  'reviews.preview1': 'Positive reviews become proof cards for Promote Business and Marketplace pages.', 'reviews.preview2': 'Three-star and lower reviews are routed privately to recovery.', 'reviews.preview3': 'Uploads accept photo/video evidence for richer testimonials.',
  'marketplace.title': 'SignalBoost Marketplace', 'marketplace.subtitle': 'Browse verified growth partners with region-aware links and logos that load from live brand domains.', 'marketplace.region': 'Region', 'marketplace.open': 'Open partner', 'marketplace.featured': 'Featured partners', 'marketplace.audit': 'Affiliate links are monitored safely; failures are logged without deleting partners.'
}

const dictionaries: Record<Lang, Dict> = {
  en,
  es: { ...en, 'nav.home':'Inicio','nav.marketplace':'Marketplace','nav.pricing':'Precios','nav.dashboard':'Dashboard','nav.logout':'Cerrar sesión','nav.promote':'Promocionar negocio','nav.reviews':'Reseñas','nav.calendar':'Calendario','nav.spreadsheets':'Hojas de cálculo','nav.outreach':'Difusión','nav.assistant':'Asistente personal','landing.kicker':'Crecimiento multilingüe nativo','landing.cta':'Abrir dashboard','landing.secondary':'Ver precios','pricing.tier.launch':'Lanzamiento','pricing.tier.growth':'Crecimiento','pricing.tier.command':'Comando','cockpit.askConcierge':'Preguntar a Concierge AI','cockpit.wireframe.missionSignal':'Resumen de señal de misión para Marketplace y SaaS','cockpit.wireframe.coreSystems':'Sistemas centrales: Reseñas, Promoción, Calendario, Hojas, Difusión y Asistente','cockpit.wireframe.conciergeBand':'La banda Concierge enruta preguntas al mejor módulo y próxima acción','cockpit.missionRole':'Señal de misión','cockpit.telemetryChecklist':'Lista de telemetría','cockpit.allModules':'Todos los módulos','module.reviews.label':'Reseñas','module.reviews.role':'Mesa de confianza y reputación','module.assistant.role':'Automatizaciones Concierge AI','reviews.title':'Recoge reseñas multilingües con enrutamiento inteligente.','reviews.subtitle':'Invita clientes a dejar estrellas, comentarios y pruebas opcionales en foto o video. SignalBoost guarda la reseña, avisa al equipo y enruta puntuaciones bajas para recuperación antes de publicar.','reviews.formTitle':'Recoger una reseña','reviews.name':'Nombre del cliente','reviews.email':'Email del cliente','reviews.rating':'Calificación','reviews.comment':'Comentario','reviews.upload':'Foto o video','reviews.language':'Idioma de la reseña','reviews.route':'Ruta inteligente','reviews.public':'Lista para prueba pública','reviews.recovery':'Enviar a recuperación','reviews.submit':'Guardar reseña','reviews.success':'Reseña capturada y enrutada.','marketplace.title':'Marketplace de SignalBoost','marketplace.subtitle':'Explora partners verificados con enlaces regionales y logos desde dominios reales.' },
  pt: { ...en, 'nav.home':'Início','nav.marketplace':'Marketplace','nav.pricing':'Preços','nav.dashboard':'Dashboard','nav.logout':'Sair','nav.promote':'Promover negócio','nav.reviews':'Avaliações','nav.calendar':'Calendário','nav.spreadsheets':'Planilhas','nav.outreach':'Outreach','nav.assistant':'Assistente pessoal','landing.kicker':'Crescimento multilíngue nativo','landing.cta':'Abrir dashboard','landing.secondary':'Ver preços','pricing.tier.launch':'Lançamento','pricing.tier.growth':'Crescimento','pricing.tier.command':'Comando','cockpit.askConcierge':'Perguntar ao Concierge AI','cockpit.wireframe.missionSignal':'Resumo do sinal da missão para Marketplace e SaaS','cockpit.wireframe.coreSystems':'Sistemas centrais: Avaliações, Promoção, Calendário, Planilhas, Outreach e Assistente','cockpit.wireframe.conciergeBand':'A faixa Concierge direciona perguntas ao melhor módulo e próxima ação','cockpit.missionRole':'Sinal da missão','cockpit.telemetryChecklist':'Checklist de telemetria','cockpit.allModules':'Todos os módulos','module.reviews.label':'Avaliações','module.reviews.role':'Mesa de confiança e reputação','module.assistant.role':'Automações Concierge AI','reviews.title':'Colete avaliações multilíngues com roteamento inteligente.','reviews.formTitle':'Coletar avaliação','reviews.name':'Nome do cliente','reviews.email':'Email do cliente','reviews.rating':'Classificação','reviews.comment':'Comentário','reviews.upload':'Foto ou vídeo','reviews.language':'Idioma da avaliação','reviews.route':'Rota inteligente','reviews.public':'Pronta para prova pública','reviews.recovery':'Enviar para recuperação','reviews.submit':'Salvar avaliação','reviews.success':'Avaliação capturada e roteada.','marketplace.title':'Marketplace SignalBoost' },
  pl: { ...en, 'nav.home':'Start','nav.marketplace':'Marketplace','nav.pricing':'Cennik','nav.dashboard':'Dashboard','nav.logout':'Wyloguj','nav.promote':'Promuj firmę','nav.reviews':'Opinie','nav.calendar':'Kalendarz','nav.spreadsheets':'Arkusze','nav.outreach':'Outreach','nav.assistant':'Osobisty asystent','landing.kicker':'Natywny wzrost wielojęzyczny','landing.cta':'Otwórz dashboard','landing.secondary':'Zobacz cennik','pricing.tier.launch':'Start','pricing.tier.growth':'Wzrost','pricing.tier.command':'Centrum dowodzenia','cockpit.askConcierge':'Zapytaj Concierge AI','cockpit.wireframe.missionSignal':'Podsumowanie sygnału misji dla Marketplace i SaaS','cockpit.wireframe.coreSystems':'Systemy główne: Opinie, Promocja, Kalendarz, Arkusze, Outreach i Asystent','cockpit.wireframe.conciergeBand':'Pas Concierge kieruje pytania do najlepszego modułu i kolejnej akcji','cockpit.missionRole':'Sygnał misji','cockpit.telemetryChecklist':'Lista telemetryczna','cockpit.allModules':'Wszystkie moduły','module.reviews.label':'Opinie','module.reviews.role':'Centrum zaufania i reputacji','module.assistant.role':'Automatyzacje Concierge AI','reviews.title':'Zbieraj wielojęzyczne opinie z inteligentnym routingiem.','reviews.formTitle':'Zbierz opinię','reviews.name':'Imię klienta','reviews.email':'Email klienta','reviews.rating':'Ocena','reviews.comment':'Komentarz','reviews.upload':'Zdjęcie lub wideo','reviews.language':'Język opinii','reviews.route':'Inteligentna ścieżka','reviews.public':'Gotowe jako publiczny dowód','reviews.recovery':'Wyślij do odzyskania','reviews.submit':'Zapisz opinię','reviews.success':'Opinia zapisana i skierowana.','marketplace.title':'Marketplace SignalBoost' },
  ru: { ...en, 'nav.home':'Главная','nav.marketplace':'Маркетплейс','nav.pricing':'Цены','nav.dashboard':'Панель','nav.logout':'Выйти','nav.promote':'Продвигать бизнес','nav.reviews':'Отзывы','nav.calendar':'Календарь','nav.spreadsheets':'Таблицы','nav.outreach':'Рассылки','nav.assistant':'Личный ассистент','landing.kicker':'Нативный многоязычный рост','landing.cta':'Открыть панель','landing.secondary':'Смотреть цены','pricing.tier.launch':'Запуск','pricing.tier.growth':'Рост','pricing.tier.command':'Командный центр','cockpit.askConcierge':'Спросить Concierge AI','cockpit.wireframe.missionSignal':'Сводка сигнала миссии для Marketplace и SaaS','cockpit.wireframe.coreSystems':'Основные системы: отзывы, продвижение, календарь, таблицы, рассылки и ассистент','cockpit.wireframe.conciergeBand':'Полоса Concierge направляет вопросы в лучший модуль и следующее действие','cockpit.missionRole':'Сигнал миссии','cockpit.telemetryChecklist':'Чеклист телеметрии','cockpit.allModules':'Все модули','module.reviews.label':'Отзывы','module.reviews.role':'Центр доверия и репутации','module.assistant.role':'Автоматизации Concierge AI','reviews.title':'Собирайте многоязычные отзывы с умной маршрутизацией.','reviews.formTitle':'Собрать отзыв','reviews.name':'Имя клиента','reviews.email':'Email клиента','reviews.rating':'Оценка','reviews.comment':'Комментарий','reviews.upload':'Фото или видео','reviews.language':'Язык отзыва','reviews.route':'Умный маршрут','reviews.public':'Готово для публикации','reviews.recovery':'Отправить на восстановление','reviews.submit':'Сохранить отзыв','reviews.success':'Отзыв сохранен и направлен.','marketplace.title':'Маркетплейс SignalBoost' },
}

interface I18nContextProps { dict: Dict; lang: Lang; setLang: (lang: string) => void }
const I18nContext = createContext<I18nContextProps>({ dict: dictionaries.en, lang: 'en', setLang: () => {} })
const supported = ['en', 'es', 'pt', 'pl', 'ru'] as const
function normalize(lang: string): Lang { const short = lang.toLowerCase().slice(0,2); return supported.includes(short as Lang) ? short as Lang : 'en' }

export function I18nProvider({ children }: { children: React.ReactNode }) {
  const [lang, setLangState] = useState<Lang>('en')
  useEffect(() => setLangState(normalize(detectLanguage())), [])
  const setLang = (next: string) => { const safe = normalize(next); localStorage.setItem('site-language', safe); setLangState(safe) }
  const dict = useMemo(() => ({ ...dictionaries.en, ...dictionaries[lang] }), [lang])
  return <I18nContext.Provider value={{ dict, lang, setLang }}>{children}</I18nContext.Provider>
}

export function useI18n() { return useContext(I18nContext) }
