'use client'

import React, { createContext, useContext, useEffect, useMemo, useState } from 'react'
import { detectLanguage } from '@/lib/i18n/detectLanguage'

type Dict = Record<string, string>
type Lang = 'en' | 'es' | 'pt' | 'pl' | 'ru'

const dictionaries: Record<Lang, Dict> = {
  en: {
    'nav.home': 'Home', 'nav.podcasters': 'Podcasters', 'nav.pricing': 'Pricing', 'nav.docs': 'Docs', 'nav.dashboard': 'Dashboard',
    'nav.promote': 'Promote Business', 'nav.reviews': 'Reviews', 'nav.calendar': 'Calendar', 'nav.spreadsheets': 'Spreadsheets', 'nav.outreach': 'Outreach', 'nav.assistant': 'Personal Assistant',
    'landing.kicker': 'Native multilingual growth', 'landing.title': 'SignalBoost builds websites, reviews, audio, and video for every market.', 'landing.subtitle': 'Launch localized marketing workflows across English, Spanish, Portuguese, Polish, and Russian with English fallback.',
    'landing.cta': 'Open dashboard', 'landing.secondary': 'View pricing', 'pages.podcasters.title': 'Podcaster plan info', 'pages.pricing.title': 'Subscription pricing', 'pages.docs.title': 'Documentation', 'pages.support.title': 'Support', 'pages.faq.title': 'FAQ',
    'pricing.kicker': 'Marketplace + SaaS in one SignalBoost cockpit', 'pricing.subtitle': 'Every plan links directly to SaaS modules deployed inside SignalBoost: Promote Business, Reviews, Calendar, Spreadsheets, Outreach, and Personal Assistant.', 'pricing.modules.title': 'Open SaaS modules inside SignalBoost', 'pricing.modules.subtitle': 'No separate SaaS repo is required; Vercel deploys these routes when SignalBoost main is merged.', 'pricing.tier.launch': 'Launch', 'pricing.tier.growth': 'Growth', 'pricing.tier.command': 'Command',
    'dashboard.title': 'Workspace modules', 'dashboard.subtitle': 'Choose a functional SignalBoost module.', 'projects.create': 'Create project', 'editor.preview': 'Preview', 'projects.title': 'Projects', 'projects.empty': 'No projects yet', 'billing.title': 'Billing', 'billing.current': 'Free plan', 'nav.automations': 'Automations', 'common.loading': 'Ready', 'nav.video': 'Video Studio', 'video.kicker': 'Video Studio', 'video.title': 'Canvas video editor + caption exporter', 'video.subtitle': 'Upload video, sync SRT/VTT captions, drag styled overlays on canvas, and enqueue FFmpeg renders for downloadable MP4 files.',
  },
  es: { 'nav.home':'Inicio','nav.podcasters':'Podcasters','nav.pricing':'Precios','nav.docs':'Docs','nav.dashboard':'Dashboard','nav.promote':'Promocionar negocio','nav.reviews':'Reseñas','nav.calendar':'Calendario','nav.spreadsheets':'Hojas de cálculo','nav.outreach':'Difusión','nav.assistant':'Asistente personal','landing.kicker':'Crecimiento multilingüe nativo','landing.title':'SignalBoost crea sitios, reseñas, audio y video para cada mercado.','landing.subtitle':'Lanza flujos localizados en inglés, español, portugués, polaco y ruso con respaldo en inglés.','landing.cta':'Abrir dashboard','landing.secondary':'Ver precios','pages.podcasters.title':'Información para podcasters','pages.pricing.title':'Precios de suscripción','pages.docs.title':'Documentación','pages.support.title':'Soporte','pages.faq.title':'FAQ','pricing.kicker':'Marketplace + SaaS en un cockpit SignalBoost','pricing.subtitle':'Cada plan enlaza módulos SaaS dentro de SignalBoost: Promocionar negocio, Reseñas, Calendario, Hojas de cálculo, Difusión y Asistente personal.','pricing.modules.title':'Abrir módulos SaaS en SignalBoost','pricing.modules.subtitle':'No se requiere un repo SaaS separado; Vercel despliega estas rutas al fusionar main.','pricing.tier.launch':'Lanzamiento','pricing.tier.growth':'Crecimiento','pricing.tier.command':'Comando','nav.video':'Estudio de video','video.kicker':'Estudio de video','video.title':'Editor de video en canvas + exportador de subtítulos','video.subtitle':'Sube video, sincroniza subtítulos SRT/VTT, arrastra capas con estilo y encola renders FFmpeg para MP4 descargables.' },
  pt: { 'nav.home':'Início','nav.podcasters':'Podcasters','nav.pricing':'Preços','nav.docs':'Docs','nav.dashboard':'Dashboard','nav.promote':'Promover negócio','nav.reviews':'Avaliações','nav.calendar':'Calendário','nav.spreadsheets':'Planilhas','nav.outreach':'Outreach','nav.assistant':'Assistente pessoal','landing.kicker':'Crescimento multilíngue nativo','landing.title':'SignalBoost cria sites, avaliações, áudio e vídeo para cada mercado.','landing.subtitle':'Lance fluxos localizados em inglês, espanhol, português, polonês e russo com fallback em inglês.','landing.cta':'Abrir dashboard','landing.secondary':'Ver preços','pages.podcasters.title':'Informações para podcasters','pages.pricing.title':'Preços de assinatura','pages.docs.title':'Documentação','pages.support.title':'Suporte','pages.faq.title':'FAQ','pricing.kicker':'Marketplace + SaaS em um cockpit SignalBoost','pricing.subtitle':'Cada plano aponta para módulos SaaS dentro do SignalBoost: Promover negócio, Avaliações, Calendário, Planilhas, Outreach e Assistente pessoal.','pricing.modules.title':'Abrir módulos SaaS no SignalBoost','pricing.modules.subtitle':'Nenhum repo SaaS separado é necessário; a Vercel implanta essas rotas quando main é mesclada.','pricing.tier.launch':'Lançamento','pricing.tier.growth':'Crescimento','pricing.tier.command':'Comando','nav.video':'Estúdio de vídeo','video.kicker':'Estúdio de vídeo','video.title':'Editor de vídeo em canvas + exportador de legendas','video.subtitle':'Envie vídeo, sincronize legendas SRT/VTT, arraste sobreposições estilizadas e enfileire renders FFmpeg para MP4 baixáveis.' },
  pl: { 'nav.home':'Start','nav.podcasters':'Podcasterzy','nav.pricing':'Cennik','nav.docs':'Dokumenty','nav.dashboard':'Dashboard','nav.promote':'Promuj firmę','nav.reviews':'Opinie','nav.calendar':'Kalendarz','nav.spreadsheets':'Arkusze','nav.outreach':'Outreach','nav.assistant':'Osobisty asystent','landing.kicker':'Natywny wzrost wielojęzyczny','landing.title':'SignalBoost tworzy strony, opinie, audio i wideo dla każdego rynku.','landing.subtitle':'Uruchamiaj lokalne workflow po angielsku, hiszpańsku, portugalsku, polsku i rosyjsku z fallbackiem do angielskiego.','landing.cta':'Otwórz dashboard','landing.secondary':'Zobacz cennik','pages.podcasters.title':'Informacje dla podcasterów','pages.pricing.title':'Cennik subskrypcji','pages.docs.title':'Dokumentacja','pages.support.title':'Pomoc','pages.faq.title':'FAQ','pricing.kicker':'Marketplace + SaaS w jednym kokpicie SignalBoost','pricing.subtitle':'Każdy plan linkuje do modułów SaaS w SignalBoost: Promuj firmę, Opinie, Kalendarz, Arkusze, Outreach i Osobisty asystent.','pricing.modules.title':'Otwórz moduły SaaS w SignalBoost','pricing.modules.subtitle':'Oddzielne repo SaaS nie jest potrzebne; Vercel wdraża te trasy po scaleniu main.','pricing.tier.launch':'Start','pricing.tier.growth':'Wzrost','pricing.tier.command':'Centrum dowodzenia','nav.video':'Studio wideo','video.kicker':'Studio wideo','video.title':'Edytor canvas + eksport napisów','video.subtitle':'Prześlij wideo, zsynchronizuj napisy SRT/VTT, przeciągaj stylizowane nakładki i kolekuj rendery FFmpeg do plików MP4.' },
  ru: { 'nav.home':'Главная','nav.podcasters':'Подкастеры','nav.pricing':'Цены','nav.docs':'Документы','nav.dashboard':'Панель','nav.promote':'Продвигать бизнес','nav.reviews':'Отзывы','nav.calendar':'Календарь','nav.spreadsheets':'Таблицы','nav.outreach':'Рассылки','nav.assistant':'Личный ассистент','landing.kicker':'Нативный многоязычный рост','landing.title':'SignalBoost создает сайты, отзывы, аудио и видео для каждого рынка.','landing.subtitle':'Запускайте локализованные workflows на английском, испанском, португальском, польском и русском с fallback на английский.','landing.cta':'Открыть панель','landing.secondary':'Смотреть цены','pages.podcasters.title':'Информация для подкастеров','pages.pricing.title':'Цены подписки','pages.docs.title':'Документация','pages.support.title':'Поддержка','pages.faq.title':'FAQ','pricing.kicker':'Marketplace + SaaS в едином кокпите SignalBoost','pricing.subtitle':'Каждый план ведет к SaaS-модулям внутри SignalBoost: Продвигать бизнес, Отзывы, Календарь, Таблицы, Рассылки и Личный ассистент.','pricing.modules.title':'Открыть SaaS-модули в SignalBoost','pricing.modules.subtitle':'Отдельный SaaS-репозиторий не нужен; Vercel развернет эти маршруты после слияния main.','pricing.tier.launch':'Запуск','pricing.tier.growth':'Рост','pricing.tier.command':'Командный центр','nav.video':'Видео-студия','video.kicker':'Видео-студия','video.title':'Canvas-редактор видео + экспорт субтитров','video.subtitle':'Загружайте видео, синхронизируйте SRT/VTT, перетаскивайте стилизованные слои и ставьте FFmpeg-рендеры MP4 в очередь.' },
}

interface I18nContextProps { dict: Dict; lang: Lang; setLang: (lang: string) => void }
const I18nContext = createContext<I18nContextProps>({ dict: dictionaries.en, lang: 'en', setLang: () => {} })
const supported = ['en', 'es', 'pt', 'pl', 'ru'] as const
function normalize(lang: string): Lang { const short = lang.toLowerCase().slice(0,2); return supported.includes(short as Lang) ? short as Lang : 'en' }

export function I18nProvider({ children }: { children: React.ReactNode }) {
  const [lang, setLangState] = useState<Lang>('en')
  useEffect(() => setLangState(normalize(detectLanguage())), [])
  const setLang = (next: string) => { const safe = normalize(next); localStorage.setItem('site-language', safe); setLangState(safe) }
  const dict = useMemo(() => ({ ...dictionaries.en, ...dictionaries[lang] }), [lang])
  return <I18nContext.Provider value={{ dict, lang, setLang }}>{children}</I18nContext.Provider>
}

export function useI18n() { return useContext(I18nContext) }
