'use client'

import React, { createContext, useContext, useEffect, useMemo, useState } from 'react'
import { detectLanguage } from '@/lib/i18n/detectLanguage'

type Dict = Record<string, string>
type Lang = 'en' | 'es' | 'pt' | 'pl' | 'ru'

const dictionaries: Record<Lang, Dict> = {
  en: {
    'nav.home': 'Home', 'nav.podcasters': 'Podcasters', 'nav.pricing': 'Pricing', 'nav.docs': 'Docs', 'nav.dashboard': 'Dashboard',
    'nav.promote': 'Promote Business', 'nav.reviews': 'Reviews', 'nav.calendar': 'Calendar', 'nav.spreadsheets': 'Spreadsheets', 'nav.outreach': 'Outreach', 'nav.assistant': 'Personal Assistant',
    'landing.kicker': 'Native multilingual growth', 'landing.title': 'SignalBoost builds websites, reviews, audio, and video for every market.', 'landing.subtitle': 'Launch localized marketing workflows across English, Spanish, Portuguese, Polish, and Russian with English fallback.',
    'landing.cta': 'Open dashboard', 'landing.secondary': 'View pricing', 'pages.podcasters.title': 'Podcaster plan info', 'pages.pricing.title': 'Subscription pricing', 'pages.docs.title': 'Documentation', 'pages.support.title': 'Support', 'pages.faq.title': 'FAQ',
    'pricing.kicker': 'Marketplace + SaaS in one SignalBoost cockpit', 'pricing.subtitle': 'Every plan links directly to SaaS modules deployed inside SignalBoost: Promote Business, Reviews, Calendar, Spreadsheets, Outreach, and Personal Assistant.', 'pricing.modules.title': 'Open SaaS modules inside SignalBoost', 'pricing.modules.subtitle': 'No separate SaaS repo is required; Vercel deploys these routes when SignalBoost main is merged.', 'pricing.tier.launch': 'Launch', 'pricing.tier.growth': 'Growth', 'pricing.tier.command': 'Command',
    'dashboard.title': 'Workspace modules', 'dashboard.subtitle': 'Choose a functional SignalBoost module.', 'projects.create': 'Create project', 'editor.preview': 'Preview', 'projects.title': 'Projects', 'projects.empty': 'No projects yet', 'billing.title': 'Billing', 'billing.current': 'Free plan', 'nav.automations': 'Automations', 'common.loading': 'Ready',
  },
  es: { 'nav.home':'Inicio','nav.podcasters':'Podcasters','nav.pricing':'Precios','nav.docs':'Docs','nav.dashboard':'Dashboard','nav.promote':'Promocionar negocio','nav.reviews':'Reseñas','nav.calendar':'Calendario','nav.spreadsheets':'Hojas de cálculo','nav.outreach':'Difusión','nav.assistant':'Asistente personal','landing.kicker':'Crecimiento multilingüe nativo','landing.title':'SignalBoost crea sitios, reseñas, audio y video para cada mercado.','landing.subtitle':'Lanza flujos localizados en inglés, español, portugués, polaco y ruso con respaldo en inglés.','landing.cta':'Abrir dashboard','landing.secondary':'Ver precios','pages.podcasters.title':'Información para podcasters','pages.pricing.title':'Precios de suscripción','pages.docs.title':'Documentación','pages.support.title':'Soporte','pages.faq.title':'FAQ','pricing.kicker':'Marketplace + SaaS en un cockpit SignalBoost','pricing.subtitle':'Cada plan enlaza módulos SaaS dentro de SignalBoost: Promocionar negocio, Reseñas, Calendario, Hojas de cálculo, Difusión y Asistente personal.','pricing.modules.title':'Abrir módulos SaaS en SignalBoost','pricing.modules.subtitle':'No se requiere un repo SaaS separado; Vercel despliega estas rutas al fusionar main.','pricing.tier.launch':'Lanzamiento','pricing.tier.growth':'Crecimiento','pricing.tier.command':'Comando' },
  pt: { 'nav.home':'Início','nav.podcasters':'Podcasters','nav.pricing':'Preços','nav.docs':'Docs','nav.dashboard':'Dashboard','nav.promote':'Promover negócio','nav.reviews':'Avaliações','nav.calendar':'Calendário','nav.spreadsheets':'Planilhas','nav.outreach':'Outreach','nav.assistant':'Assistente pessoal','landing.kicker':'Crescimento multilíngue nativo','landing.title':'SignalBoost cria sites, avaliações, áudio e vídeo para cada mercado.','landing.subtitle':'Lance fluxos localizados em inglês, espanhol, português, polonês e russo com fallback em inglês.','landing.cta':'Abrir dashboard','landing.secondary':'Ver preços','pages.podcasters.title':'Informações para podcasters','pages.pricing.title':'Preços de assinatura','pages.docs.title':'Documentação','pages.support.title':'Suporte','pages.faq.title':'FAQ','pricing.kicker':'Marketplace + SaaS em um cockpit SignalBoost','pricing.subtitle':'Cada plano aponta para módulos SaaS dentro do SignalBoost: Promover negócio, Avaliações, Calendário, Planilhas, Outreach e Assistente pessoal.','pricing.modules.title':'Abrir módulos SaaS no SignalBoost','pricing.modules.subtitle':'Nenhum repo SaaS separado é necessário; a Vercel implanta essas rotas quando main é mesclada.','pricing.tier.launch':'Lançamento','pricing.tier.growth':'Crescimento','pricing.tier.command':'Comando' },
  pl: { 'nav.home':'Start','nav.podcasters':'Podcasterzy','nav.pricing':'Cennik','nav.docs':'Dokumenty','nav.dashboard':'Dashboard','nav.promote':'Promuj firmę','nav.reviews':'Opinie','nav.calendar':'Kalendarz','nav.spreadsheets':'Arkusze','nav.outreach':'Outreach','nav.assistant':'Osobisty asystent','landing.kicker':'Natywny wzrost wielojęzyczny','landing.title':'SignalBoost tworzy strony, opinie, audio i wideo dla każdego rynku.','landing.subtitle':'Uruchamiaj lokalne workflow po angielsku, hiszpańsku, portugalsku, polsku i rosyjsku z fallbackiem do angielskiego.','landing.cta':'Otwórz dashboard','landing.secondary':'Zobacz cennik','pages.podcasters.title':'Informacje dla podcasterów','pages.pricing.title':'Cennik subskrypcji','pages.docs.title':'Dokumentacja','pages.support.title':'Pomoc','pages.faq.title':'FAQ','pricing.kicker':'Marketplace + SaaS w jednym kokpicie SignalBoost','pricing.subtitle':'Każdy plan linkuje do modułów SaaS w SignalBoost: Promuj firmę, Opinie, Kalendarz, Arkusze, Outreach i Osobisty asystent.','pricing.modules.title':'Otwórz moduły SaaS w SignalBoost','pricing.modules.subtitle':'Oddzielne repo SaaS nie jest potrzebne; Vercel wdraża te trasy po scaleniu main.','pricing.tier.launch':'Start','pricing.tier.growth':'Wzrost','pricing.tier.command':'Centrum dowodzenia' },
  ru: { 'nav.home':'Главная','nav.podcasters':'Подкастеры','nav.pricing':'Цены','nav.docs':'Документы','nav.dashboard':'Панель','nav.promote':'Продвигать бизнес','nav.reviews':'Отзывы','nav.calendar':'Календарь','nav.spreadsheets':'Таблицы','nav.outreach':'Рассылки','nav.assistant':'Личный ассистент','landing.kicker':'Нативный многоязычный рост','landing.title':'SignalBoost создает сайты, отзывы, аудио и видео для каждого рынка.','landing.subtitle':'Запускайте локализованные workflows на английском, испанском, португальском, польском и русском с fallback на английский.','landing.cta':'Открыть панель','landing.secondary':'Смотреть цены','pages.podcasters.title':'Информация для подкастеров','pages.pricing.title':'Цены подписки','pages.docs.title':'Документация','pages.support.title':'Поддержка','pages.faq.title':'FAQ','pricing.kicker':'Marketplace + SaaS в едином кокпите SignalBoost','pricing.subtitle':'Каждый план ведет к SaaS-модулям внутри SignalBoost: Продвигать бизнес, Отзывы, Календарь, Таблицы, Рассылки и Личный ассистент.','pricing.modules.title':'Открыть SaaS-модули в SignalBoost','pricing.modules.subtitle':'Отдельный SaaS-репозиторий не нужен; Vercel развернет эти маршруты после слияния main.','pricing.tier.launch':'Запуск','pricing.tier.growth':'Рост','pricing.tier.command':'Командный центр' },
}


const websiteDictionaries: Record<Lang, Dict> = {
  en: {
    'nav.websites':'Websites','nav.admin':'Admin','nav.getStarted':'Get Started','websites.language':'Language','websites.kicker':'SaaS Station','websites.title':'Website Optimization System','websites.subtitle':'Analyze, optimize, and rebuild websites with multilingual SEO, accessibility, conversion, mobile, performance, and security checks.','websites.analyzer.title':'Website Analyzer','websites.analyzer.urlPlaceholder':'https://example.com','websites.analyzer.analyze':'Analyze','websites.analyzer.analyzing':'Analyzing…','websites.analyzer.lastAudits':'Last audits','websites.analyzer.noAudits':'No audits yet.','websites.scores.performance':'Performance','websites.scores.seo':'SEO','websites.scores.accessibility':'Accessibility','websites.scores.mobile':'Mobile','websites.scores.conversion':'Conversion','websites.scores.security':'Security','websites.recommendations.title':'Recommendations','websites.recommendations.apply':'Apply via Optimizer','websites.optimizer.title':'Website Optimizer','websites.optimizer.section':'Section','websites.optimizer.currentContent':'Current content','websites.optimizer.optimize':'Optimize content','websites.optimizer.aiOptimized':'AI-optimized content','websites.optimizer.applyChanges':'Apply changes','websites.optimizer.empty':'Optimization output will appear here.','websites.sections.hero':'Hero','websites.sections.about':'About','websites.sections.services':'Services','websites.sections.pricing':'Pricing','websites.sections.footer':'Footer','websites.sections.contact':'Contact','websites.rebuild.title':'Rebuild Engine','websites.rebuild.banner':'This site is slow, outdated, or conversion-limited. A rebuild is recommended.','websites.rebuild.generate':'Generate rebuild','websites.rebuild.siteMap':'Site map','websites.rebuild.sections':'Sections','websites.rebuild.copy':'Copy preview','websites.rebuild.downloadJson':'Download JSON','websites.footer.status':'Status','websites.footer.health':'Sync health','websites.footer.ready':'Ready','websites.footer.syncing':'Syncing','websites.footer.synced':'Synced','websites.footer.ok':'Healthy','websites.footer.error':'Needs attention','concierge.input.placeholder':'Ask Concierge about audits, optimization, rebuilds, pricing, or modules…'
  },
  es: {
    'nav.websites':'Sitios web','nav.admin':'Admin','nav.getStarted':'Comenzar','websites.language':'Idioma','websites.kicker':'Estación SaaS','websites.title':'Sistema de optimización web','websites.subtitle':'Analiza, optimiza y reconstruye sitios con SEO, accesibilidad, conversión, móvil, rendimiento y seguridad multilingües.','websites.analyzer.title':'Analizador web','websites.analyzer.urlPlaceholder':'https://ejemplo.com','websites.analyzer.analyze':'Analizar','websites.analyzer.analyzing':'Analizando…','websites.analyzer.lastAudits':'Últimas auditorías','websites.analyzer.noAudits':'Aún no hay auditorías.','websites.scores.performance':'Rendimiento','websites.scores.seo':'SEO','websites.scores.accessibility':'Accesibilidad','websites.scores.mobile':'Móvil','websites.scores.conversion':'Conversión','websites.scores.security':'Seguridad','websites.recommendations.title':'Recomendaciones','websites.recommendations.apply':'Aplicar con Optimizador','websites.optimizer.title':'Optimizador web','websites.optimizer.section':'Sección','websites.optimizer.currentContent':'Contenido actual','websites.optimizer.optimize':'Optimizar contenido','websites.optimizer.aiOptimized':'Contenido optimizado por IA','websites.optimizer.applyChanges':'Aplicar cambios','websites.optimizer.empty':'La salida de optimización aparecerá aquí.','websites.sections.hero':'Hero','websites.sections.about':'Nosotros','websites.sections.services':'Servicios','websites.sections.pricing':'Precios','websites.sections.footer':'Pie','websites.sections.contact':'Contacto','websites.rebuild.title':'Motor de reconstrucción','websites.rebuild.banner':'Este sitio es lento, antiguo o limitado en conversión. Se recomienda reconstruir.','websites.rebuild.generate':'Generar reconstrucción','websites.rebuild.siteMap':'Mapa del sitio','websites.rebuild.sections':'Secciones','websites.rebuild.copy':'Vista de copy','websites.rebuild.downloadJson':'Descargar JSON','websites.footer.status':'Estado','websites.footer.health':'Salud de sincronización','websites.footer.ready':'Listo','websites.footer.syncing':'Sincronizando','websites.footer.synced':'Sincronizado','websites.footer.ok':'Saludable','websites.footer.error':'Requiere atención','concierge.input.placeholder':'Pregunta al Concierge sobre auditorías, optimización, reconstrucciones, precios o módulos…'
  },
  pt: {
    'nav.websites':'Sites','nav.admin':'Admin','nav.getStarted':'Começar','websites.language':'Idioma','websites.kicker':'Estação SaaS','websites.title':'Sistema de otimização de sites','websites.subtitle':'Analise, otimize e reconstrua sites com SEO, acessibilidade, conversão, mobile, desempenho e segurança multilíngues.','websites.analyzer.title':'Analisador de sites','websites.analyzer.urlPlaceholder':'https://exemplo.com','websites.analyzer.analyze':'Analisar','websites.analyzer.analyzing':'Analisando…','websites.analyzer.lastAudits':'Últimas auditorias','websites.analyzer.noAudits':'Ainda não há auditorias.','websites.scores.performance':'Desempenho','websites.scores.seo':'SEO','websites.scores.accessibility':'Acessibilidade','websites.scores.mobile':'Mobile','websites.scores.conversion':'Conversão','websites.scores.security':'Segurança','websites.recommendations.title':'Recomendações','websites.recommendations.apply':'Aplicar no Otimizador','websites.optimizer.title':'Otimizador de sites','websites.optimizer.section':'Seção','websites.optimizer.currentContent':'Conteúdo atual','websites.optimizer.optimize':'Otimizar conteúdo','websites.optimizer.aiOptimized':'Conteúdo otimizado por IA','websites.optimizer.applyChanges':'Aplicar mudanças','websites.optimizer.empty':'A saída de otimização aparecerá aqui.','websites.sections.hero':'Hero','websites.sections.about':'Sobre','websites.sections.services':'Serviços','websites.sections.pricing':'Preços','websites.sections.footer':'Rodapé','websites.sections.contact':'Contato','websites.rebuild.title':'Motor de reconstrução','websites.rebuild.banner':'Este site é lento, antigo ou limitado em conversão. Uma reconstrução é recomendada.','websites.rebuild.generate':'Gerar reconstrução','websites.rebuild.siteMap':'Mapa do site','websites.rebuild.sections':'Seções','websites.rebuild.copy':'Prévia do texto','websites.rebuild.downloadJson':'Baixar JSON','websites.footer.status':'Status','websites.footer.health':'Saúde da sincronização','websites.footer.ready':'Pronto','websites.footer.syncing':'Sincronizando','websites.footer.synced':'Sincronizado','websites.footer.ok':'Saudável','websites.footer.error':'Requer atenção','concierge.input.placeholder':'Pergunte ao Concierge sobre auditorias, otimização, reconstruções, preços ou módulos…'
  },
  pl: {
    'nav.websites':'Strony','nav.admin':'Admin','nav.getStarted':'Zacznij','websites.language':'Język','websites.kicker':'Stacja SaaS','websites.title':'System optymalizacji stron','websites.subtitle':'Analizuj, optymalizuj i przebudowuj strony z wielojęzycznym SEO, dostępnością, konwersją, mobile, wydajnością i bezpieczeństwem.','websites.analyzer.title':'Analizator stron','websites.analyzer.urlPlaceholder':'https://przyklad.com','websites.analyzer.analyze':'Analizuj','websites.analyzer.analyzing':'Analizowanie…','websites.analyzer.lastAudits':'Ostatnie audyty','websites.analyzer.noAudits':'Brak audytów.','websites.scores.performance':'Wydajność','websites.scores.seo':'SEO','websites.scores.accessibility':'Dostępność','websites.scores.mobile':'Mobile','websites.scores.conversion':'Konwersja','websites.scores.security':'Bezpieczeństwo','websites.recommendations.title':'Rekomendacje','websites.recommendations.apply':'Zastosuj w optymalizatorze','websites.optimizer.title':'Optymalizator stron','websites.optimizer.section':'Sekcja','websites.optimizer.currentContent':'Aktualna treść','websites.optimizer.optimize':'Optymalizuj treść','websites.optimizer.aiOptimized':'Treść zoptymalizowana przez AI','websites.optimizer.applyChanges':'Zastosuj zmiany','websites.optimizer.empty':'Wynik optymalizacji pojawi się tutaj.','websites.sections.hero':'Hero','websites.sections.about':'O nas','websites.sections.services':'Usługi','websites.sections.pricing':'Cennik','websites.sections.footer':'Stopka','websites.sections.contact':'Kontakt','websites.rebuild.title':'Silnik przebudowy','websites.rebuild.banner':'Ta strona jest wolna, przestarzała lub ogranicza konwersję. Zalecana jest przebudowa.','websites.rebuild.generate':'Generuj przebudowę','websites.rebuild.siteMap':'Mapa strony','websites.rebuild.sections':'Sekcje','websites.rebuild.copy':'Podgląd treści','websites.rebuild.downloadJson':'Pobierz JSON','websites.footer.status':'Status','websites.footer.health':'Stan synchronizacji','websites.footer.ready':'Gotowe','websites.footer.syncing':'Synchronizacja','websites.footer.synced':'Zsynchronizowano','websites.footer.ok':'Zdrowy','websites.footer.error':'Wymaga uwagi','concierge.input.placeholder':'Zapytaj Concierge o audyty, optymalizację, przebudowę, ceny lub moduły…'
  },
  ru: {
    'nav.websites':'Сайты','nav.admin':'Админ','nav.getStarted':'Начать','websites.language':'Язык','websites.kicker':'SaaS Station','websites.title':'Система оптимизации сайтов','websites.subtitle':'Анализируйте, оптимизируйте и перестраивайте сайты с многоязычным SEO, доступностью, конверсией, mobile, производительностью и безопасностью.','websites.analyzer.title':'Анализатор сайтов','websites.analyzer.urlPlaceholder':'https://example.com','websites.analyzer.analyze':'Анализировать','websites.analyzer.analyzing':'Анализ…','websites.analyzer.lastAudits':'Последние аудиты','websites.analyzer.noAudits':'Аудитов пока нет.','websites.scores.performance':'Производительность','websites.scores.seo':'SEO','websites.scores.accessibility':'Доступность','websites.scores.mobile':'Мобильность','websites.scores.conversion':'Конверсия','websites.scores.security':'Безопасность','websites.recommendations.title':'Рекомендации','websites.recommendations.apply':'Применить в оптимизаторе','websites.optimizer.title':'Оптимизатор сайта','websites.optimizer.section':'Секция','websites.optimizer.currentContent':'Текущий контент','websites.optimizer.optimize':'Оптимизировать контент','websites.optimizer.aiOptimized':'AI-оптимизированный контент','websites.optimizer.applyChanges':'Применить изменения','websites.optimizer.empty':'Результат оптимизации появится здесь.','websites.sections.hero':'Hero','websites.sections.about':'О нас','websites.sections.services':'Услуги','websites.sections.pricing':'Цены','websites.sections.footer':'Футер','websites.sections.contact':'Контакты','websites.rebuild.title':'Модуль перестройки','websites.rebuild.banner':'Этот сайт медленный, устаревший или ограничивает конверсию. Рекомендуется перестройка.','websites.rebuild.generate':'Создать перестройку','websites.rebuild.siteMap':'Карта сайта','websites.rebuild.sections':'Секции','websites.rebuild.copy':'Предпросмотр текста','websites.rebuild.downloadJson':'Скачать JSON','websites.footer.status':'Статус','websites.footer.health':'Синхронизация','websites.footer.ready':'Готово','websites.footer.syncing':'Синхронизация','websites.footer.synced':'Синхронизировано','websites.footer.ok':'Исправно','websites.footer.error':'Требует внимания','concierge.input.placeholder':'Спросите Concierge об аудитах, оптимизации, перестройке, ценах или модулях…'
  }
}

interface I18nContextProps { dict: Dict; lang: Lang; setLang: (lang: string) => void }
const I18nContext = createContext<I18nContextProps>({ dict: dictionaries.en, lang: 'en', setLang: () => {} })
const supported = ['en', 'es', 'pt', 'pl', 'ru'] as const
function normalize(lang: string): Lang { const short = lang.toLowerCase().slice(0,2); return supported.includes(short as Lang) ? short as Lang : 'en' }

export function I18nProvider({ children }: { children: React.ReactNode }) {
  const [lang, setLangState] = useState<Lang>('en')
  useEffect(() => setLangState(normalize(detectLanguage())), [])
  const setLang = (next: string) => { const safe = normalize(next); localStorage.setItem('site-language', safe); setLangState(safe) }
  const dict = useMemo(() => ({ ...dictionaries.en, ...websiteDictionaries.en, ...dictionaries[lang], ...websiteDictionaries[lang] }), [lang])
  return <I18nContext.Provider value={{ dict, lang, setLang }}>{children}</I18nContext.Provider>
}

export function useI18n() { return useContext(I18nContext) }
