{ href: '/dashboard/builder',  icon: '🌐', label: 'Site builder' },
{ href: '/dashboard/reviews',  icon: '⭐', label: 'Review collector' },
{ href: '/dashboard/audio',    icon: '🎙️', label: 'Native audio' },
{ href: '/dashboard/video',    icon: '🎬', label: 'Video editor' },
{ href: '/dashboard/feedback', icon: '💬', label: 'Feedback' },