import type { ContinuousLearningSourceAdapter } from '@/lib/cos-core/layers/learning/cycle'
import { ContinuousLearningCycle } from '@/lib/cos-core/layers/learning/cycle'
import { ContinuousLearningDirector,type ContinuousLearningStore,type KnowledgeGap } from '@/lib/cos-core/layers/learning'
import { createLiveLearningAdapters } from '@/lib/cos-core/layers/learning/liveSources'
import { createSupabaseCOSStores } from '@/lib/cos-core/storage/supabase'
import { generateKnowledgeGaps,type KnowledgeGapSignal } from '@/lib/cos-core/layers/learning/gaps'
import type { MiningRunSummary } from './mining/types'
export type DailyLearningResult={status:'skipped'|'learned';skipReason?:string;approvedUrls:number;autonomousGaps:number;curriculumGaps:number;liveSourceAdapters:number;gapsConsidered:number;documentsAcquired:number;accepted:number;rejected:Record<string,number>;sourceErrors:Record<string,number>;externalCostUsd:number}
export type ContinuousLearningTelemetrySink={record(metric:Record<string,unknown>):Promise<void>|void}
const ZERO_LLM_POLICY={allowedSourceKinds:new Set(['work_experience','engineering_history','official_documentation','research_paper','scientific_journal','library_material','news_article','public_dataset','video_transcript','approved_public_web'] as const),minimumConfidence:0.72,maxCandidatesPerCycle:80,maxExternalCostUsdPerCycle:0}
const CURRICULUM=[
 ['distributed-systems','Distributed systems and multi-tenant SaaS architecture','What current verified practices explain tenant-specific latency, noisy-neighbor effects, connection-pool contention, queueing, sharding, caching, rate limiting, and workload isolation?'],
 ['sre-observability','Site reliability engineering and observability','What current verified practices improve production diagnosis using traces, percentiles, saturation, queues, dependency latency, error budgets, and read-only differential analysis?'],
 ['cloud-kubernetes','Cloud platforms and Kubernetes','What current verified operational knowledge about AWS Azure GCP Kubernetes networking storage scheduling autoscaling and service meshes should COS retain?'],
 ['database-performance','Database and data-system performance','What current verified knowledge about query plans locks connection pools replicas indexes partitions caches and tenant data skew should COS retain?'],
 ['security','Enterprise cybersecurity and software supply chain','What current verified security knowledge about identity authorization zero trust vulnerabilities dependencies secrets and cloud security should COS retain?'],
 ['ai-engineering','AI systems and agent engineering','What current verified knowledge about local models inference RAG memory agents evaluation provenance safety and AI infrastructure should COS retain?'],
 ['software-engineering','Software architecture and engineering','What current verified software engineering knowledge about APIs distributed applications testing reliability performance and architecture should COS retain?'],
 ['enterprise-technology','Enterprise technology industry','What important current enterprise technology developments from technical news publications official engineering sources and research should COS understand?'],
] as const
export function continuousLearningCurriculum(day=new Date()):KnowledgeGap[]{const offset=Math.floor(day.getTime()/86400000);return CURRICULUM.map((item,index)=>({id:`curriculum:${item[0]}:${day.toISOString().slice(0,10)}`,subject:item[1],question:item[2],portableIds:['cos'],expectedReuse:10,expectedAvoidedCostUsd:.5,urgency:55+((index+offset)%8),evidence:['scheduled autonomous curriculum','cross-source validation required']}))}
export function autonomousLearningReadiness(env:NodeJS.ProcessEnv=process.env){const autonomousEnabled=env.COS_AUTONOMOUS_LEARNING_ENABLED==='true',liveSourcesEnabled=env.COS_LIVE_SOURCES_ENABLED==='true',approvedUrls=String(env.COS_APPROVED_LEARNING_URLS||'').split(',').map(v=>v.trim()).filter(Boolean).length,liveAdapters=createLiveLearningAdapters(env).length;return{autonomousEnabled,liveSourcesEnabled,approvedUrls,liveAdapters,youtubeEnabled:Boolean(env.YOUTUBE_API_KEY),youtubeTranscriptEnabled:Boolean(env.YOUTUBE_API_KEY&&env.YOUTUBE_TRANSCRIPT_API_URL),techFeedsConfigured:Boolean(String(env.COS_TECH_RSS_FEEDS||'').trim()),ready:autonomousEnabled&&(liveAdapters>0||approvedUrls>0),warnings:[...(!autonomousEnabled?['COS_AUTONOMOUS_LEARNING_ENABLED is not true']:[]),...(autonomousEnabled&&!liveSourcesEnabled&&approvedUrls===0?['No public learning sources are enabled']:[]),...(liveSourcesEnabled&&!env.YOUTUBE_API_KEY?['YouTube learning unavailable: YOUTUBE_API_KEY missing']:[])]}}
function autonomousLearningIsExplicitlyEnabled(){return process.env.COS_AUTONOMOUS_LEARNING_ENABLED==='true'}
export function parseApprovedLearningUrls(){return String(process.env.COS_APPROVED_LEARNING_URLS||'').split(',').map(v=>v.trim()).filter(Boolean)}
function miningGap(summary:MiningRunSummary):KnowledgeGap{return{id:`daily-mining-${summary.run_id}`,subject:'SignalBoost operational behavior',question:'What reusable operational knowledge can COS learn from the latest mining run?',portableIds:['cos'],expectedReuse:5,expectedAvoidedCostUsd:.25,urgency:40,evidence:[`users_processed=${summary.users_processed}`,`rules_found=${summary.rules_found}`]}}
function miningAdapter(summary:MiningRunSummary):ContinuousLearningSourceAdapter{return{kind:'work_experience',async acquire(gap){if(!gap.id.startsWith('daily-mining-'))return[];return[{sourceKind:'work_experience',sourceUri:`signalboost://mining/${summary.run_id}`,sourceTitle:'SignalBoost daily mining run',observedAt:new Date().toISOString(),subject:gap.subject,text:JSON.stringify(summary),evidence:gap.evidence}]}}}
export function approvedUrlLearningAdapter(urls:string[]):ContinuousLearningSourceAdapter{return{kind:'approved_public_web',async acquire(gap){if(gap.id.startsWith('daily-mining-'))return[];const documents:any[]=[];for(const url of urls.slice(0,10)){try{const response=await fetch(url,{signal:AbortSignal.timeout(10000)});if(!response.ok)continue;const text=(await response.text()).replace(/\s+/g,' ').trim().slice(0,12000);if(text)documents.push({sourceKind:'approved_public_web',sourceUri:url,sourceTitle:url,observedAt:new Date().toISOString(),subject:gap.subject,text,evidence:[url]})}catch(error){console.warn('cosLearning: approved URL acquisition failed',{url,error:error instanceof Error?error.message:String(error)})}}return documents}}}
async function runLearningCycleWithTelemetry(run:()=>Promise<any>,telemetry:ContinuousLearningTelemetrySink){const startedAt=Date.now(),result=await run();await telemetry.record({event:'cos_continuous_learning_cycle',latencyMs:Date.now()-startedAt,...result});return result}
async function loadQueuedReasoningGaps():Promise<{ids:string[];signals:KnowledgeGapSignal[]}>{const db=createSupabaseCOSStores()?(await import('@/lib/cos-core/storage/supabase')).cosServiceDb():null;if(!db)return{ids:[],signals:[]};try{const{data}=await db.from('cos_learning_gaps').select('*').in('status',['pending','failed']).order('last_seen_at',{ascending:false}).limit(25);const rows=data??[];return{ids:rows.map((r:any)=>String(r.id)),signals:rows.map((r:any)=>({taskId:String(r.task_id||'support'),subject:String(r.subject||''),capability:String(r.capability||'general_reasoning'),objective:String(r.question||''),confidence:Number(r.confidence||0),escalated:true,succeeded:false,repeatedCount:Number(r.repeated_count||1),evidence:r.escalation_reason?[String(r.escalation_reason)]:[],portableIds:['cos']}))}}catch{return{ids:[],signals:[]}}}
async function markQueuedReasoningGaps(ids:string[],accepted:number){if(!ids.length)return;const db=(await import('@/lib/cos-core/storage/supabase')).cosServiceDb();if(!db)return;try{await db.from('cos_learning_gaps').update({status:accepted>0?'resolved':'failed',resolved_at:accepted>0?new Date().toISOString():null,last_seen_at:new Date().toISOString()}).in('id',ids)}catch{}}
const consoleTelemetry:ContinuousLearningTelemetrySink={record(metric){console.info('[cos-daily-learning]',JSON.stringify(metric))}}
export async function runDailyAutonomousLearning(input:{miningSummary:MiningRunSummary;store?:ContinuousLearningStore;adapters?:ContinuousLearningSourceAdapter[];telemetry?:ContinuousLearningTelemetrySink;approvedUrls?:string[];gapSignals?:KnowledgeGapSignal[]}):Promise<DailyLearningResult>{const readiness=autonomousLearningReadiness();if(!autonomousLearningIsExplicitlyEnabled()){console.warn('[cos-daily-learning-skipped]',JSON.stringify(readiness));return{status:'skipped',skipReason:'autonomous_learning_disabled',approvedUrls:readiness.approvedUrls,autonomousGaps:0,curriculumGaps:0,liveSourceAdapters:readiness.liveAdapters,gapsConsidered:0,documentsAcquired:0,accepted:0,rejected:{},sourceErrors:{},externalCostUsd:0}}const persistentStore=input.store??createSupabaseCOSStores()?.continuousLearning;if(!persistentStore){return{status:'skipped',skipReason:'persistent_store_unavailable',approvedUrls:readiness.approvedUrls,autonomousGaps:0,curriculumGaps:0,liveSourceAdapters:readiness.liveAdapters,gapsConsidered:0,documentsAcquired:0,accepted:0,rejected:{},sourceErrors:{},externalCostUsd:0}}const queued=input.gapSignals?{ids:[],signals:input.gapSignals}:await loadQueuedReasoningGaps(),approvedUrls=input.approvedUrls??parseApprovedLearningUrls(),autonomousGaps=generateKnowledgeGaps(queued.signals),curriculum=continuousLearningCurriculum(),gaps=[miningGap(input.miningSummary),...autonomousGaps,...curriculum],liveAdapters=createLiveLearningAdapters(),adapters=[miningAdapter(input.miningSummary),...(approvedUrls.length?[approvedUrlLearningAdapter(approvedUrls)]:[]),...liveAdapters,...(input.adapters??[])];console.info('[cos-learning-readiness]',JSON.stringify({...readiness,queuedGaps:queued.signals.length,generatedGaps:autonomousGaps.length,curriculumGaps:curriculum.length,adapterKinds:adapters.map(a=>a.id??a.kind)}));const director=new ContinuousLearningDirector(persistentStore,ZERO_LLM_POLICY),cycle=new ContinuousLearningCycle(director,adapters),result=await runLearningCycleWithTelemetry(()=>cycle.run(gaps,0),input.telemetry??consoleTelemetry);await markQueuedReasoningGaps(queued.ids,result.accepted);return{status:'learned',approvedUrls:approvedUrls.length,autonomousGaps:autonomousGaps.length,curriculumGaps:curriculum.length,liveSourceAdapters:liveAdapters.length,...result,externalCostUsd:0}}
