// saas/lib/cos/video-compose.ts
// Branded final-video assembly via JSON2Video.
// The brand is rendered as an SVG image overlay, not text generated by the video engine.

const J2V_ENDPOINT = 'https://api.json2video.com/v2/movies'
const BRAND_NAME = 'SignalBoostAi'
const BRAND_URL = 'www.saas.signalboostapp.com'
const TOTAL = 60
const VOICE_MODEL = 'elevenlabs-flash-v2-5'
const VOICE_NAME = 'Adam'

const SCRIPT_BY_LANG: Record<string, string> = {
  en: `SignalBoostAi is your AI-powered growth department. It builds professional websites in minutes, creates branded content and videos, turns reviews into marketing posts, and prepares outreach campaigns across every channel. From websites to content to growth workflows, SignalBoost gives small businesses, agencies, hotels, restaurants, and entrepreneurs one AI system to look sharper and move faster. Every campaign is drafted for you and kept behind your approval before anything goes live. Automate your marketing, launch faster, and grow with confidence. Start building smarter today with SignalBoostAi.`,
  es: `SignalBoostAi es tu departamento de crecimiento con inteligencia artificial. Crea sitios web profesionales en minutos, genera contenido y videos de marca, convierte reseñas en publicaciones de marketing y prepara campañas de difusión en todos los canales. SignalBoost ofrece a pequeñas empresas, agencias, hoteles, restaurantes y emprendedores un solo sistema de inteligencia artificial para verse mejor y avanzar más rápido. Empieza a construir de forma más inteligente hoy con SignalBoostAi.`,
  pt: `A SignalBoostAi é o seu departamento de crescimento com inteligência artificial. Cria sites profissionais em minutos, gera conteúdo e vídeos de marca, transforma avaliações em publicações de marketing e prepara campanhas de prospecção em todos os canais. Comece a construir de forma mais inteligente hoje com a SignalBoostAi.`,
  pl: `SignalBoostAi to twój dział wzrostu napędzany sztuczną inteligencją. Tworzy profesjonalne strony w kilka minut, generuje treści i filmy marki, zamienia opinie w posty marketingowe i przygotowuje kampanie docierania do klientów we wszystkich kanałach. Zacznij budować mądrzej już dziś z SignalBoostAi.`,
  ru: `SignalBoostAi — это ваш отдел роста на основе искусственного интеллекта. Он создаёт профессиональные сайты за минуты, генерирует брендированный контент и видео, превращает отзывы в маркетинговые посты и готовит кампании по всем каналам. Начните строить умнее уже сегодня с SignalBoostAi.`,
}

function stripUrls(text: string): string {
  return String(text || '')
    .replace(/https?:\/\/\S+/gi, ' ')
    .replace(/\bwww\.\S+/gi, ' ')
    .replace(/\b[\w-]+\.(?:com|net|org|ai|app|io|co)\b\S*/gi, ' ')
    .replace(/\s+/g, ' ')
    .trim()
}

function scriptFor(campaign: any, lang: string): string {
  const items = Array.isArray(campaign?.work_items) ? campaign.work_items : []
  const match = items.find((it: any) => it?.input?.language === lang && it?.output) || items.find((it: any) => it?.output)
  const o = (match && match.output) || {}
  const parts = [o.title, o.opening, o.draft, o.call_to_action]
    .map((v: any) => String(v || '').replace(/\s+/g, ' ').trim())
    .filter(Boolean)
  let text = parts.join('. ').replace(/\.\s*\.+/g, '.').replace(/\s+/g, ' ').trim()
  if (text.split(/\s+/).filter(Boolean).length < 90) text = SCRIPT_BY_LANG[lang] || SCRIPT_BY_LANG.en
  text = stripUrls(text)
  if (text.length > 1000) {
    text = text.slice(0, 1000)
    const cut = Math.max(text.lastIndexOf('. '), text.lastIndexOf('! '), text.lastIndexOf('? '))
    if (cut > 600) text = text.slice(0, cut + 1)
  }
  return text
}

function bannerDataUri(vertical: boolean): string {
  const w = vertical ? 960 : 1500
  const h = vertical ? 250 : 210
  const nameSize = vertical ? 92 : 84
  const urlSize = vertical ? 48 : 44
  const urlY = vertical ? 170 : 145
  const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="${w}" height="${h}" viewBox="0 0 ${w} ${h}"><rect x="0" y="0" width="${w}" height="${h}" rx="28" fill="rgba(0,0,0,0.78)"/><text x="${w / 2}" y="95" text-anchor="middle" font-family="Arial, Helvetica, sans-serif" font-size="${nameSize}" font-weight="900" fill="#ffc300">${BRAND_NAME}</text><text x="${w / 2}" y="${urlY}" text-anchor="middle" font-family="Arial, Helvetica, sans-serif" font-size="${urlSize}" font-weight="900" fill="#1af0ff">${BRAND_URL}</text></svg>`
  return `data:image/svg+xml;base64,${Buffer.from(svg).toString('base64')}`
}

function brandImage(vertical: boolean) {
  const canvasWidth = vertical ? 1080 : 1920
  const width = vertical ? 960 : 1500
  const height = vertical ? 250 : 210
  return {
    type: 'image',
    src: bannerDataUri(vertical),
    start: 0,
    duration: TOTAL,
    x: Math.round((canvasWidth - width) / 2),
    y: vertical ? 70 : 44,
    width,
    height,
    'z-index': 100,
  }
}

function buildBrandedMovie(opts: { brollUrl: string; aspect: '16:9' | '9:16'; script: string; lang: string; campaignId: string }) {
  const vertical = opts.aspect === '9:16'
  const width = vertical ? 1080 : 1920
  const height = vertical ? 1920 : 1080
  const capSize = vertical ? '64' : '52'
  return {
    width,
    height,
    quality: 'high',
    'client-data': { campaign_id: opts.campaignId, language: opts.lang, brand_name: BRAND_NAME, brand_url: BRAND_URL },
    scenes: [
      {
        duration: TOTAL,
        elements: [
          { type: 'video', src: opts.brollUrl, duration: TOTAL, loop: -1, resize: 'cover', muted: true, 'z-index': 0 },
          { type: 'voice', model: VOICE_MODEL, voice: VOICE_NAME, text: opts.script, 'model-settings': { language_code: opts.lang } },
          { type: 'subtitles', language: opts.lang, settings: { 'font-family': 'Montserrat', 'font-weight': '800', 'font-size': capSize, 'word-color': '#FFFFFF', 'line-color': '#FFFFFF', 'outline-color': '#000000', 'outline-width': 6, 'max-words-per-line': 6, position: 'bottom', style: 'classic' } },
          brandImage(vertical),
        ],
      },
    ],
  }
}

async function j2vHeaders() {
  const key = process.env.JSON2VIDEO_API_KEY
  if (!key) throw new Error('JSON2VIDEO_API_KEY not set')
  return { 'Content-Type': 'application/json', 'x-api-key': key }
}

export async function renderBrandedVideo(opts: { campaign: any; brollUrl: string; aspect: '16:9' | '9:16'; lang: string }): Promise<{ ok: boolean; url?: string; error?: string }> {
  try {
    if (!opts.brollUrl) return { ok: false, error: 'No b-roll URL to brand.' }
    const script = scriptFor(opts.campaign, opts.lang)
    const movie = buildBrandedMovie({ brollUrl: opts.brollUrl, aspect: opts.aspect, script, lang: opts.lang, campaignId: String(opts.campaign?.id || '') })
    const headers = await j2vHeaders()
    const submitRes = await fetch(J2V_ENDPOINT, { method: 'POST', headers, body: JSON.stringify(movie) })
    const submitData: any = await submitRes.json().catch(() => ({}))
    if (!submitRes.ok || submitData?.success === false) return { ok: false, error: submitData?.message || submitData?.error || `submit failed (${submitRes.status})` }
    const project = submitData?.project || submitData?.movie?.project || submitData?.id
    if (!project) return { ok: false, error: 'No project id returned from JSON2Video.' }
    const deadline = Date.now() + 240_000
    while (Date.now() < deadline) {
      await new Promise((r) => setTimeout(r, 8000))
      const pollRes = await fetch(`${J2V_ENDPOINT}?project=${encodeURIComponent(project)}`, { headers })
      const pollData: any = await pollRes.json().catch(() => ({}))
      const m = pollData?.movie || {}
      const status = String(m?.status || '')
      if (status === 'done' && m?.url) return { ok: true, url: String(m.url) }
      if (status === 'error' || m?.success === false) return { ok: false, error: m?.message || 'render error' }
    }
    return { ok: false, error: 'JSON2Video render timed out.' }
  } catch (e: any) {
    return { ok: false, error: e?.message || 'branded compose failed' }
  }
}
