export const approvalRequestSchemaVersion = 'supervisor-approval-request-v1'
export const approvalStatuses = ['pending','approved','rejected','expired','invalidated','consumed'] as const
export type ApprovalStatus = typeof approvalStatuses[number]
export interface ProtectedStepSummary { stepId: string; summary: string; expectedResult?: string; verificationRequirement?: string; riskLevel?: string }
export interface EvidenceReference { evidenceId: string; stepId?: string; kind: string; artifactReference?: string; summary?: string; capturedAt?: string }
export interface SupervisorApprovalRequest { approvalRequestId: string; executionId: string; dispatchId: string; incidentId: string; planId: string; packageId: string; packageFingerprint: string; provider: string; environment: 'sandbox'; targetOrigin: string; checkpointId: string; remainingStepIds: string[]; protectedStepSummaries: ProtectedStepSummary[]; evidenceReferences: EvidenceReference[]; phaseOneApprovalDigest: string; requestedAt: string; expiresAt: string; status: ApprovalStatus; schemaVersion: typeof approvalRequestSchemaVersion; operatorId?: string; decidedAt?: string; consumedAt?: string; rejectionReasonCode?: string; operatorNote?: string }
const safe = /^[A-Za-z0-9._:/#?=&@| -]{1,512}$/
function text(v: unknown, f: string) { if (typeof v !== 'string' || !v.trim() || v.length > 512 || !safe.test(v)) throw new Error(`${f}_invalid`); return v }
function iso(v: unknown, f: string) { const s = text(v, f); if (new Date(s).toISOString() !== s) throw new Error(`${f}_invalid`); return s }
function arr(v: unknown, f: string) { if (!Array.isArray(v)) throw new Error(`${f}_invalid`); return v.map((x,i)=>text(x, `${f}_${i}`)) }
export function parseApprovalRequest(v: unknown): SupervisorApprovalRequest { if (!v || typeof v !== 'object' || Array.isArray(v)) throw new Error('approval_request_invalid'); const r = v as SupervisorApprovalRequest; if (r.schemaVersion !== approvalRequestSchemaVersion) throw new Error('schema_invalid'); if (!approvalStatuses.includes(r.status)) throw new Error('status_invalid'); if (r.environment !== 'sandbox') throw new Error('environment_invalid'); const req: SupervisorApprovalRequest = { approvalRequestId:text(r.approvalRequestId,'approvalRequestId'), executionId:text(r.executionId,'executionId'), dispatchId:text(r.dispatchId,'dispatchId'), incidentId:text(r.incidentId,'incidentId'), planId:text(r.planId,'planId'), packageId:text(r.packageId,'packageId'), packageFingerprint:text(r.packageFingerprint,'packageFingerprint'), provider:text(r.provider,'provider'), environment:'sandbox', targetOrigin:new URL(text(r.targetOrigin,'targetOrigin')).origin, checkpointId:text(r.checkpointId,'checkpointId'), remainingStepIds:arr(r.remainingStepIds,'remainingStepIds'), protectedStepSummaries:Array.isArray(r.protectedStepSummaries)?r.protectedStepSummaries.map((s:any)=>({ stepId:text(s.stepId,'stepId'), summary:text(s.summary,'summary'), expectedResult:s.expectedResult?text(s.expectedResult,'expectedResult'):undefined, verificationRequirement:s.verificationRequirement?text(s.verificationRequirement,'verificationRequirement'):undefined, riskLevel:s.riskLevel?text(s.riskLevel,'riskLevel'):undefined })):[], evidenceReferences:Array.isArray(r.evidenceReferences)?r.evidenceReferences.map((e:any)=>({ evidenceId:text(e.evidenceId,'evidenceId'), stepId:e.stepId?text(e.stepId,'stepId'):undefined, kind:text(e.kind,'kind'), artifactReference:e.artifactReference?text(e.artifactReference,'artifactReference'):undefined, summary:e.summary?text(e.summary,'summary'):undefined, capturedAt:e.capturedAt?iso(e.capturedAt,'capturedAt'):undefined })):[], phaseOneApprovalDigest:text(r.phaseOneApprovalDigest,'phaseOneApprovalDigest'), requestedAt:iso(r.requestedAt,'requestedAt'), expiresAt:iso(r.expiresAt,'expiresAt'), status:r.status, schemaVersion:approvalRequestSchemaVersion }
 if (r.operatorId) req.operatorId=text(r.operatorId,'operatorId'); if (r.decidedAt) req.decidedAt=iso(r.decidedAt,'decidedAt'); if (r.consumedAt) req.consumedAt=iso(r.consumedAt,'consumedAt'); if (r.rejectionReasonCode) req.rejectionReasonCode=text(r.rejectionReasonCode,'rejectionReasonCode'); if (r.operatorNote) req.operatorNote=String(r.operatorNote).replace(/[<>]/g,'').slice(0,500); return req }
export function sanitizeApprovalRequest(r: SupervisorApprovalRequest) { return parseApprovalRequest(JSON.parse(JSON.stringify(r))) }
