export * from './provider-adapter.ts'
export * from './provider-registry.ts'
export * from './provider-capability.ts'
export * from './provider-origin.ts'
export * from './provider-navigation.ts'
export * from './provider-selector.ts'
export * from './provider-verification.ts'
export * from './provider-evidence.ts'
export * from './provider-health.ts'
export * from './provider-version.ts'
export * from './provider-errors.ts'
export * from './supervisor-integration.ts'
export * from './vercel/index.ts'
import { BrowserProviderRegistry } from './provider-registry.ts'
import { VercelBrowserAdapter } from './vercel/vercel-browser-adapter.ts'
export function createDefaultBrowserProviderRegistry(){ const registry=new BrowserProviderRegistry(); registry.register(VercelBrowserAdapter); return registry }
