import { BrowserProviderError } from './provider-errors.ts'
import { BPAL_SCHEMA_VERSION, type BrowserProviderVersion, assertBrowserProviderVersion } from './provider-version.ts'
export const browserProviderCapabilityMaturities=['experimental','sandbox_verified','human_approved','auto_failover_ready','suspended'] as const
export const browserProviderRiskClasses=['read_only','low_risk_reversible','medium','high','forbidden'] as const
export type BrowserProviderCapabilityMaturity=typeof browserProviderCapabilityMaturities[number]
export type BrowserProviderRiskClass=typeof browserProviderRiskClasses[number]
export type CapabilityMaturity=BrowserProviderCapabilityMaturity
export type RiskClass=BrowserProviderRiskClass
export interface BrowserProviderCapability { capabilityId:string; providerId:string; operation:string; displayNameKey:string; descriptionKey?:string; riskClass:BrowserProviderRiskClass; maturity:BrowserProviderCapabilityMaturity; readOnly:boolean; supportsApi:boolean; supportsBrowser:boolean; supportsAutoFailover:boolean; supportsBrowserOnDemand:boolean; requiresHumanApproval:boolean; reversible:boolean; idempotent:boolean; allowedOriginIds:readonly string[]; navigationProfileId?:string; verificationProfileId:string; evidenceProfileId:string; adapterVersion:string; capabilityVersion:string; policyVersion?:string; schemaVersion:typeof BPAL_SCHEMA_VERSION; suspendedReasonCode?:string }
export type ProviderCapability = BrowserProviderCapability
export function assertBrowserProviderCapability(capability:BrowserProviderCapability):Readonly<BrowserProviderCapability>{if(!capability.capabilityId||!capability.providerId||!browserProviderRiskClasses.includes(capability.riskClass)||!browserProviderCapabilityMaturities.includes(capability.maturity)||capability.schemaVersion!==BPAL_SCHEMA_VERSION)throw new BrowserProviderError('unknown_capability');if(!capability.readOnly||capability.riskClass!=='read_only')throw new BrowserProviderError('immutable_read_only');assertBrowserProviderVersion({adapterVersion:capability.adapterVersion,capabilityVersion:capability.capabilityVersion,schemaVersion:capability.schemaVersion});return Object.freeze({...capability,allowedOriginIds:Object.freeze([...capability.allowedOriginIds].sort())})}
export function createCapabilityRegistry(items:readonly BrowserProviderCapability[]){const seen=new Set<string>();const values=items.map(assertBrowserProviderCapability).sort((a,b)=>a.capabilityId.localeCompare(b.capabilityId));for(const item of values){if(seen.has(item.capabilityId))throw new BrowserProviderError('duplicate_capability');seen.add(item.capabilityId)}const map=new Map(values.map(item=>[item.capabilityId,item] as const));return Object.freeze({get(id:string){const value=map.get(id);if(!value)throw new BrowserProviderError('unknown_capability');if(value.maturity==='suspended'||value.suspendedReasonCode)throw new BrowserProviderError('capability_suspended');return value},list(){return [...values]},toJSON(){return [...values]}})}
export function capabilityVersion(capability:BrowserProviderCapability):BrowserProviderVersion{return {adapterVersion:capability.adapterVersion,capabilityVersion:capability.capabilityVersion,schemaVersion:capability.schemaVersion}}
