// saas/app/api/hub/cyber/report-pdf/route.ts
// Server-side PDF export for Cybersecurity Center issue review reports.

import { NextResponse } from 'next/server'
import { requireAdmin } from '@/lib/auth/access'
import { createSimplePdf, type PdfDoc } from '@/lib/audit/simplePdf'

export const dynamic = 'force-dynamic'
export const runtime = 'nodejs'
export const maxDuration = 60

type Advisory = {
  id?: string
  packageName?: string
  version?: string
  sourceFile?: string
  severity?: string
  summary?: string
  detailsUrl?: string
}

type CyberReport = {
  generatedAt?: string
  target?: string
  repo?: string
  branch?: string
  advisories?: Advisory[]
  summary?: {
    packagesScanned?: number
    advisories?: number
    critical?: number
    high?: number
    medium?: number
    low?: number
    unknown?: number
  }
}

function issueExplanation(a: Advisory) {
  if (a.severity === 'critical') return 'Critical severity. Review immediately because vulnerable dependency versions can create serious exposure when reachable in production code.'
  if (a.severity === 'high') return 'High severity. Prioritize remediation and test carefully before deployment.'
  if (a.severity === 'medium') return 'Medium severity. Plan remediation after confirming whether the package is used in a reachable part of the application.'
  if (a.severity === 'low') return 'Low severity. Track and remediate during normal maintenance unless exposed in a sensitive path.'
  return 'Severity was not clearly classified by the advisory source. A human should review the advisory details before deciding whether an update is needed.'
}

function recommendedAction(a: Advisory) {
  if (a.severity === 'critical' || a.severity === 'high') return 'Prepare a dependency update plan, test the application, and require human approval before opening or merging any fix.'
  if (a.severity === 'medium') return 'Review patched versions, create a safe update plan, and test before deployment.'
  if (a.severity === 'low') return 'Track the issue and include the dependency update in the next maintenance cycle.'
  return 'Review the advisory manually, confirm the safe patched version, then decide whether SignalBoost should prepare a fix request.'
}

function buildCyberPdfDoc(report: CyberReport): PdfDoc {
  const advisories = Array.isArray(report.advisories) ? report.advisories : []
  const summary = report.summary || {}
  const repo = report.repo || report.target || 'Repository'
  const lines: string[] = [
    `Repository: ${repo}`,
    `Branch: ${report.branch || 'default branch'}`,
    `Scan generated: ${report.generatedAt || 'unknown'}`,
    `Packages scanned: ${summary.packagesScanned ?? 0}`,
    `Advisories found: ${summary.advisories ?? advisories.length}`,
    `Severity counts: critical ${summary.critical ?? 0}, high ${summary.high ?? 0}, medium ${summary.medium ?? 0}, low ${summary.low ?? 0}, unknown ${summary.unknown ?? 0}`,
  ]

  const issueLines: string[] = []
  advisories.forEach((a, i) => {
    issueLines.push(`Issue ${i + 1}: ${a.packageName || 'package'}@${a.version || 'unknown version'}`)
    issueLines.push(`Severity: ${a.severity || 'unknown'}`)
    issueLines.push(`Advisory: ${a.id || 'unknown advisory id'}`)
    issueLines.push(`Where found: ${a.sourceFile || 'source file not provided'}`)
    issueLines.push(`What was found: ${a.summary || 'Dependency advisory found.'}`)
    issueLines.push(`Why it matters: ${issueExplanation(a)}`)
    issueLines.push(`Recommended next step: ${recommendedAction(a)}`)
    if (a.detailsUrl) issueLines.push(`Advisory URL: ${a.detailsUrl}`)
    issueLines.push('')
  })

  return {
    title: 'SignalBoost Cybersecurity Issue Review',
    subtitle: 'Dependency advisory report. No fix has been requested, approved, or performed automatically. Human approval is required before any code change or pull request.',
    sections: [
      { heading: 'Executive Summary', lines },
      { heading: 'Detected Issues', lines: issueLines.length ? issueLines : ['No dependency advisories were included in this report.'] },
      { heading: 'Human Approval Control', lines: [
        'SignalBoost may prepare a remediation request only after the user asks for help.',
        'A human/admin must approve the remediation request before any fix, code change, pull request, or assisted remediation is performed.',
      ] },
    ],
    footer: 'Generated by SignalBoost Cybersecurity Center.',
  }
}

export async function POST(req: Request) {
  const guard = await requireAdmin()
  if (!guard.ok) return NextResponse.json({ ok: false, error: guard.error }, { status: guard.status })

  try {
    const body = await req.json().catch(() => ({}))
    const report = (body?.report || {}) as CyberReport
    const pdf = createSimplePdf(buildCyberPdfDoc(report))
    const pdfBody = new Uint8Array(pdf.length)
    pdfBody.set(pdf)
    const repoName = String(report.repo || report.target || 'cybersecurity-report').replace(/[^a-z0-9_-]+/gi, '-').replace(/^-+|-+$/g, '').slice(0, 80) || 'cybersecurity-report'
    const filename = `${repoName}-issue-review-${new Date().toISOString().slice(0, 10)}.pdf`

    return new Response(pdfBody, {
      status: 200,
      headers: {
        'Content-Type': 'application/pdf',
        'Content-Disposition': `attachment; filename="${filename}"`,
        'Cache-Control': 'no-store',
      },
    })
  } catch (err) {
    const message = err instanceof Error ? err.message : 'Failed to generate cybersecurity PDF.'
    return NextResponse.json({ ok: false, error: message }, { status: 500 })
  }
}
