import type { PortableProductDescriptor } from './product-types.ts'
import { validatePortableProductRegistry } from './product-validation.ts'

function product(descriptor: PortableProductDescriptor): PortableProductDescriptor {
  return Object.freeze({ ...descriptor, documentationReferences: Object.freeze([...descriptor.documentationReferences]), capabilityTags: Object.freeze([...descriptor.capabilityTags]), architectureReferences: Object.freeze([...descriptor.architectureReferences]) })
}

export const portableProductRegistry: readonly PortableProductDescriptor[] = Object.freeze([
  product({ productId: 'campaign-studio', localizationKey: 'campaign', fallbackName: 'Campaign Studio', fallbackDescription: 'One short request becomes a finished campaign.', glyph: '✦', status: 'live', implementationStatus: 'implemented', category: 'growth', sortOrder: 10, publicVisible: true, licensingAvailable: true, route: '/agency', documentationReferences: ['docs/portables/README.md'], capabilityTags: ['campaign-generation', 'byok', 'owner-approval'], architectureReferences: ['saas/app/agency/', 'saas/lib/agency/'] }),
  product({ productId: 'integrations-hub', localizationKey: 'integrations', fallbackName: 'Integrations Hub', fallbackDescription: 'Secure connections for websites, payments, calendars, AI systems, and APIs.', glyph: '⛓', status: 'live', implementationStatus: 'implemented', category: 'integrations', sortOrder: 20, publicVisible: true, licensingAvailable: true, documentationReferences: ['docs/portables/README.md'], capabilityTags: ['provider-neutral', 'secure-connections'], architectureReferences: ['saas/lib/providers/', 'saas/console-core/'] }),
  product({ productId: 'video-maker', localizationKey: 'render', fallbackName: 'Video Maker', fallbackDescription: 'Voice and branded video with governed prepaid use.', glyph: '◍', status: 'live', implementationStatus: 'implemented', category: 'media', sortOrder: 30, publicVisible: true, licensingAvailable: true, documentationReferences: ['docs/portables/render-module.md'], capabilityTags: ['video-rendering', 'voice', 'approval-gated'], architectureReferences: ['saas/render-core/', 'saas/render-host/'] }),
  product({ productId: 'control-center', localizationKey: 'console', fallbackName: 'Control Center', fallbackDescription: 'Keys, webhooks, logs, releases, and activity controls.', glyph: '◈', status: 'live', implementationStatus: 'implemented', category: 'governance', sortOrder: 40, publicVisible: true, licensingAvailable: true, documentationReferences: ['docs/portables/README.md'], capabilityTags: ['audit', 'webhooks', 'releases'], architectureReferences: ['saas/console-core/', 'saas/console-host/'] }),
  product({ productId: 'marketing-sales', localizationKey: 'marketingSales', fallbackName: 'Marketing + Sales', fallbackDescription: 'Marketing and sales workflows in one portable engine.', glyph: '◎', status: 'live', implementationStatus: 'implemented', category: 'growth', sortOrder: 50, publicVisible: true, licensingAvailable: true, documentationReferences: ['docs/portables/README.md'], capabilityTags: ['marketing', 'sales', 'workflows'], architectureReferences: ['saas/marketing-sales-core/', 'saas/marketing-sales-host/'] }),
  product({ productId: 'press-media', localizationKey: 'press', fallbackName: 'Press & Media', fallbackDescription: 'Governed outreach to verified editors and paid distribution services.', glyph: '◉', status: 'live', implementationStatus: 'implemented', category: 'media', sortOrder: 60, publicVisible: true, licensingAvailable: true, documentationReferences: ['docs/portables/press-media-portable-design.md'], capabilityTags: ['press-outreach', 'owner-approval', 'media-distribution'], architectureReferences: ['saas/press-media-core/', 'saas/press-media-host/'] }),
  product({ productId: 'portable-ai-chief-of-staff', localizationKey: 'chiefOfStaff', fallbackName: 'Portable AI Chief of Staff', fallbackDescription: 'Plans and carries out only approved work through buyer-supplied ports.', glyph: '❖', status: 'preview', implementationStatus: 'preview', category: 'operations', sortOrder: 70, publicVisible: true, licensingAvailable: false, documentationReferences: ['docs/portables/cos-host-integration-guide.md'], capabilityTags: ['planning', 'approval-gated', 'portable-ports'], architectureReferences: ['saas/lib/cos/', 'saas/portable-kernel/'] }),
  product({ productId: 'browser-agent-ecosystem', localizationKey: 'browserAgents', fallbackName: 'Browser Agent Ecosystem', fallbackDescription: 'Plug-and-play ports pre-staged for managed, self-hosted, and future browser-agent stacks.', glyph: '◇', status: 'preview', implementationStatus: 'descriptor_only', category: 'automation', sortOrder: 80, publicVisible: true, licensingAvailable: false, documentationReferences: ['docs/portables/browser-agent-host-integration-guide.md'], capabilityTags: ['browser-ports', 'compatibility', 'provider-neutral'], architectureReferences: ['saas/lib/portable-browser/', 'saas/lib/browser-provider/'] }),
  product({ productId: 'agent-operations-platform', localizationKey: 'agentOperations', fallbackName: 'Agent Operations Platform', fallbackDescription: 'Guarded workflows with quotas, audit, idempotency, recovery, and provider-neutral adapters.', glyph: '⌁', status: 'preview', implementationStatus: 'preview', category: 'operations', sortOrder: 90, publicVisible: true, licensingAvailable: false, documentationReferences: ['docs/portables/self-healing-integration-guide.md'], capabilityTags: ['durable-workflows', 'audit', 'idempotency'], architectureReferences: ['saas/lib/agent-runtime/', 'saas/lib/portable-browser/', 'docs/portables/self-healing-integration-guide.md'] }),
  product({ productId: 'self-healing-supervisor', localizationKey: 'selfHealing', fallbackName: 'Self-Healing Supervisor', fallbackDescription: 'Detects failures, diagnoses them, and proposes bounded repairs for approval.', glyph: '⟲', status: 'preview', implementationStatus: 'preview', category: 'operations', sortOrder: 100, publicVisible: true, licensingAvailable: false, documentationReferences: ['docs/portables/self-healing-integration-guide.md'], capabilityTags: ['diagnostics', 'repair-proposals', 'human-approval'], architectureReferences: ['saas/lib/supervisor/', 'saas/lib/agent-runtime/'] }),
])

validatePortableProductRegistry(portableProductRegistry)
