import type { PortableProductDescriptor } from './product-types.ts'
import { validatePortableProductRegistry } from './product-validation.ts'

function product(descriptor: PortableProductDescriptor): PortableProductDescriptor {
  return Object.freeze({
    ...descriptor,
    documentationReferences: Object.freeze([...descriptor.documentationReferences]),
    capabilityTags: Object.freeze([...descriptor.capabilityTags]),
    architectureReferences: Object.freeze([...descriptor.architectureReferences]),
  })
}

/** Canonical metadata-only catalog. Architecture references are documentation, never imports. */
export const portableProductRegistry = Object.freeze([
  product({ productId: 'campaign-studio', localizationKey: 'campaign', fallbackName: 'Campaign Studio', fallbackDescription: 'One short request becomes a finished campaign.', glyph: '✦', status: 'live', category: 'growth', sortOrder: 10, publicVisible: true, licensingAvailable: true, route: '/agency', documentationReferences: ['saas/docs/developer-guide.md'], capabilityTags: ['campaign-generation', 'byok', 'approval-gates'], architectureReferences: ['saas/lib/cos/', 'saas/lib/agency/'], implementationClassification: 'implemented_product' }),
  product({ productId: 'integrations-hub', localizationKey: 'integrations', fallbackName: 'Integrations Hub', fallbackDescription: 'Secure connections for websites, payments, calendars, AI systems, and APIs.', glyph: '⛓', status: 'live', category: 'integrations', sortOrder: 20, publicVisible: true, licensingAvailable: true, documentationReferences: ['saas/docs/provider-integration.md'], capabilityTags: ['provider-catalog', 'configuration', 'approval-gates'], architectureReferences: ['saas/lib/engine/', 'saas/lib/provider-framework/'], implementationClassification: 'implemented_product' }),
  product({ productId: 'video-maker', localizationKey: 'render', fallbackName: 'Video Maker', fallbackDescription: 'Voice and branded video with governed prepaid use.', glyph: '◍', status: 'live', category: 'media', sortOrder: 30, publicVisible: true, licensingAvailable: true, documentationReferences: ['docs/portables/render-module.md'], capabilityTags: ['video-rendering', 'voice', 'human-approval'], architectureReferences: ['saas/render-core/', 'saas/render-host/'], implementationClassification: 'implemented_product' }),
  product({ productId: 'control-center', localizationKey: 'console', fallbackName: 'Control Center', fallbackDescription: 'Keys, webhooks, logs, releases, and activity controls.', glyph: '◈', status: 'live', category: 'governance', sortOrder: 40, publicVisible: true, licensingAvailable: true, documentationReferences: ['saas/docs/console/TESTING.md'], capabilityTags: ['key-management', 'audit-logs', 'release-controls'], architectureReferences: ['saas/console-core/', 'saas/console-host/'], implementationClassification: 'implemented_product' }),
  product({ productId: 'marketing-sales', localizationKey: 'marketingSales', fallbackName: 'Marketing + Sales', fallbackDescription: 'Marketing and sales workflows in one portable engine.', glyph: '◎', status: 'live', category: 'growth', sortOrder: 50, publicVisible: true, licensingAvailable: true, documentationReferences: ['saas/docs/marketing-sales-module-design.md'], capabilityTags: ['marketing-workflows', 'sales-workflows', 'approval-gates'], architectureReferences: ['saas/marketing-sales-core/', 'saas/marketing-sales-host/'], implementationClassification: 'implemented_product' }),
  product({ productId: 'press-media', localizationKey: 'press', fallbackName: 'Press & Media', fallbackDescription: 'Governed outreach to verified editors and paid distribution services.', glyph: '◉', status: 'live', category: 'media', sortOrder: 60, publicVisible: true, licensingAvailable: true, documentationReferences: ['docs/portables/press-media-portable-design.md'], capabilityTags: ['press-outreach', 'owner-approval', 'distribution'], architectureReferences: ['saas/press-media-core/', 'saas/press-media-host/'], implementationClassification: 'implemented_product' }),
  product({ productId: 'portable-ai-chief-of-staff', localizationKey: 'chiefOfStaff', fallbackName: 'Portable AI Chief of Staff', fallbackDescription: 'Plans and carries out only approved work through buyer-supplied ports.', glyph: '❖', status: 'preview', category: 'operations', sortOrder: 70, publicVisible: true, licensingAvailable: false, documentationReferences: ['docs/portables/cos-host-integration-guide.md'], capabilityTags: ['planning', 'buyer-supplied-ports', 'approval-gates'], architectureReferences: ['saas/lib/cos/', 'saas/portable-kernel/'], implementationClassification: 'preview_product' }),
  product({ productId: 'browser-agent-ecosystem', localizationKey: 'browserAgents', fallbackName: 'Browser Agent Ecosystem', fallbackDescription: 'Plug-and-play ports pre-staged for managed, self-hosted, and future browser-agent stacks.', glyph: '◇', status: 'preview', category: 'automation', sortOrder: 80, publicVisible: true, licensingAvailable: false, documentationReferences: ['docs/portables/browser-agent-host-integration-guide.md'], capabilityTags: ['browser-ports', 'adapter-catalog', 'non-production'], architectureReferences: ['saas/lib/portable-browser/', 'saas/lib/browser-provider/'], implementationClassification: 'preview_product' }),
  product({ productId: 'agent-operations-platform', localizationKey: 'agentOperations', fallbackName: 'Agent Operations Platform', fallbackDescription: 'Guarded workflows with quotas, audit, idempotency, recovery, and provider-neutral adapters.', glyph: '⌁', status: 'preview', category: 'operations', sortOrder: 90, publicVisible: true, licensingAvailable: false, documentationReferences: ['docs/portables/enterprise-portables-and-blank-cos.md'], capabilityTags: ['durable-workflows', 'audit', 'idempotency'], architectureReferences: ['saas/lib/agent-runtime/', 'saas/lib/portable-browser/', 'docs/portables/enterprise-portables-and-blank-cos.md'], implementationClassification: 'preview_product' }),
  product({ productId: 'self-healing-supervisor', localizationKey: 'selfHealing', fallbackName: 'Self-Healing Supervisor', fallbackDescription: 'Detects failures, diagnoses them, and proposes bounded repairs for approval.', glyph: '⟲', status: 'preview', category: 'infrastructure', sortOrder: 100, publicVisible: true, licensingAvailable: false, documentationReferences: ['docs/portables/self-healing-integration-guide.md'], capabilityTags: ['failure-detection', 'repair-proposals', 'approval-gates'], architectureReferences: ['saas/lib/supervisor/', 'saas/lib/supervisor/portable/host-context.ts'], implementationClassification: 'preview_product' }),
])

validatePortableProductRegistry(portableProductRegistry)
