// saas/lib/provider-framework/aws.ts
import { randomUUID } from 'node:crypto'
import { UNIVERSAL_PROVIDER_SCHEMA_VERSION, type UniversalProviderCapability, type UniversalProviderHealth, type UniversalProviderMetadata, type UniversalProviderSdk } from './types.ts'

export const AWS_PROVIDER_ID = 'aws' as const
export const awsCapabilities = ['aws.connection.validate','aws.account.read','aws.regions.list','aws.ec2.instances.list','aws.s3.buckets.list','aws.lambda.functions.list','aws.rds.instances.list','aws.cloudwatch.alarms.list','aws.iam.account_summary.read','aws.cloudtrail.trails.list'] as const
export type AwsCapability = typeof awsCapabilities[number]
export type AwsRuntimeConfig = { readonly organizationId:string; readonly accessKeyId:string; readonly secretAccessKey:string; readonly sessionToken?:string; readonly region?:string; readonly apiBaseUrl?:string }
export type AwsEvidence = { readonly evidenceId:string; readonly summary:string; readonly metadata:Readonly<Record<string,string|number|boolean|null>> }
export type AwsProviderError = { readonly kind:'authentication'|'authorization'|'not_found'|'rate_limited'|'timeout'|'provider_outage'|'malformed_response'|'unsupported_mutation'|'configuration'|'unknown'; readonly message:string; readonly retryable:boolean; readonly status?:number }
export type AwsProviderResult<T> = { readonly ok:true; readonly value:T; readonly evidence:readonly AwsEvidence[] } | { readonly ok:false; readonly error:AwsProviderError; readonly evidence:readonly AwsEvidence[] }
export type AwsObservation = { readonly providerId:typeof AWS_PROVIDER_ID; readonly organizationId:string; readonly capabilityId:AwsCapability; readonly resourceType:string; readonly resourceId:string; readonly observedAt:string; readonly state:'available'|'empty'; readonly metadata:Readonly<Record<string,string|number|boolean|null>>; readonly evidence:readonly AwsEvidence[] }
type FetchLike = (url:string, init:RequestInit)=>Promise<Response>
const ev=(summary:string,metadata:AwsEvidence['metadata']={}):AwsEvidence=>({evidenceId:`evidence_${randomUUID()}`,summary,metadata})
function cap(id:AwsCapability):UniversalProviderCapability{return{capabilityId:id,displayNameKey:`universalProvider.aws.capabilities.${id}.title`,descriptionKey:`universalProvider.aws.capabilities.${id}.description`,version:'1.0.0',maturity:'sandbox_verified',riskClass:'read_only',channels:['api','scheduler'],environments:['sandbox','preview','production'],authentication:['api_key','signature'],requiresApproval:false,readOnly:true,rateLimit:{windowSeconds:1,maxRequests:20,scope:'credential'},timeout:{connectMs:3000,readMs:10000,totalMs:15000},retryPolicy:{maxAttempts:3,backoff:'exponential',baseDelayMs:500,maxDelayMs:10000},scheduler:{supported:true,minimumIntervalSeconds:300,jitterSupported:true,localizationKey:'universalProvider.aws.scheduler'},evidenceProviderIds:['aws_api_snapshot'],verificationProviderIds:['aws_current_state']}}
export const awsProviderMetadata=Object.freeze<UniversalProviderMetadata>({providerId:AWS_PROVIDER_ID,displayNameKey:'universalProvider.aws.displayName',descriptionKey:'universalProvider.aws.description',version:{providerVersion:'1.0.0',sdkVersion:'aws-query-readonly-v1',capabilityCatalogVersion:'aws-readonly-1',schemaVersion:UNIVERSAL_PROVIDER_SCHEMA_VERSION,compatibleSchemaVersions:[UNIVERSAL_PROVIDER_SCHEMA_VERSION]},health:{lifecycle:'registered',checkedAt:'1970-01-01T00:00:00.000Z'},capabilities:awsCapabilities.map(cap),supportedChannels:['api','scheduler'],supportedAuthentication:['api_key','signature'],supportedEnvironments:['sandbox','preview','production'],supportedRegions:['global'],configurationSchema:{schemaId:'aws.connection.v1',version:'1.0.0',fields:[{key:'access_key_ref',type:'secret_ref',required:true,labelKey:'universalProvider.aws.config.accessKeyRef'},{key:'secret_key_ref',type:'secret_ref',required:true,labelKey:'universalProvider.aws.config.secretKeyRef'},{key:'session_token_ref',type:'secret_ref',required:false,labelKey:'universalProvider.aws.config.sessionTokenRef'},{key:'region',type:'string',required:false,labelKey:'universalProvider.aws.config.region'}]},webhook:{supported:false,eventTypes:[],signatureSchemes:[],replayProtection:false},scheduler:{supported:true,minimumIntervalSeconds:300,jitterSupported:true,localizationKey:'universalProvider.aws.scheduler'},operator:{ownerTeamKey:'universalProvider.operator.ownerTeam',documentationKey:'universalProvider.aws.documentation'}})
function err(error:unknown,status?:number):AwsProviderError{if(error instanceof DOMException&&error.name==='AbortError')return{kind:'timeout',message:'AWS request timed out',retryable:true};if(status===401)return{kind:'authentication',message:'AWS credentials are invalid or revoked',retryable:false,status};if(status===403)return{kind:'authorization',message:'AWS credentials lack read permission',retryable:false,status};if(status===404)return{kind:'not_found',message:'AWS resource was not found',retryable:false,status};if(status===429)return{kind:'rate_limited',message:'AWS rate limit reached',retryable:true,status};if(status&&status>=500)return{kind:'provider_outage',message:'AWS API is unavailable',retryable:true,status};return{kind:'unknown',message:'AWS request failed',retryable:false,status}}
function endpoint(id:AwsCapability,region:string):string{switch(id){case'aws.connection.validate':case'aws.account.read':return'/sts?Action=GetCallerIdentity&Version=2011-06-15';case'aws.regions.list':return`/ec2/${region}?Action=DescribeRegions&Version=2016-11-15`;case'aws.ec2.instances.list':return`/ec2/${region}?Action=DescribeInstances&Version=2016-11-15`;case'aws.s3.buckets.list':return'/s3?Action=ListBuckets';case'aws.lambda.functions.list':return`/lambda/${region}/2015-03-31/functions`;case'aws.rds.instances.list':return`/rds/${region}?Action=DescribeDBInstances&Version=2014-10-31`;case'aws.cloudwatch.alarms.list':return`/cloudwatch/${region}?Action=DescribeAlarms&Version=2010-08-01`;case'aws.iam.account_summary.read':return'/iam?Action=GetAccountSummary&Version=2010-05-08';case'aws.cloudtrail.trails.list':return`/cloudtrail/${region}?Action=DescribeTrails&Version=2013-11-01`}}
export class AwsReadOnlyAdapter implements UniversalProviderSdk{readonly metadata=awsProviderMetadata;private readonly fetcher: FetchLike;constructor(fetcher: FetchLike = fetch){this.fetcher = fetcher;}listCapabilities(){return this.metadata.capabilities}getCapability(id:string){return this.metadata.capabilities.find(c=>c.capabilityId===id)}getHealth():UniversalProviderHealth{return this.metadata.health}getVersion(){return this.metadata.version}rejectMutation(operation:string):AwsProviderResult<never>{return{ok:false,error:{kind:'unsupported_mutation',message:`AWS mutation '${operation}' is not supported by the read-only adapter`,retryable:false},evidence:[ev('Rejected unsupported AWS mutation',{operation})]}}
private async request(config:AwsRuntimeConfig,path:string):Promise<AwsProviderResult<unknown>>{if(!config.accessKeyId||!config.secretAccessKey)return{ok:false,error:{kind:'configuration',message:'Missing AWS credential',retryable:false},evidence:[ev('Missing AWS credential')]};const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),15000);try{const headers:Record<string,string>={'x-signalboost-aws-access-key':config.accessKeyId,'x-signalboost-aws-secret-key':config.secretAccessKey,accept:'application/json'};if(config.sessionToken)headers['x-amz-security-token']=config.sessionToken;const response=await this.fetcher(`${config.apiBaseUrl??'https://aws-readonly.invalid'}${path}`,{method:'GET',headers,signal:controller.signal});if(!response.ok)return{ok:false,error:err(undefined,response.status),evidence:[ev('AWS API returned an error',{status:response.status,path})]};return{ok:true,value:await response.json(),evidence:[ev('AWS read completed',{path})]}}catch(error){return{ok:false,error:err(error),evidence:[ev('AWS read failed',{path})]}}finally{clearTimeout(timer)}}
async validateConnection(config:AwsRuntimeConfig):Promise<AwsProviderResult<{accountId:string}>>{const result=await this.request(config,endpoint('aws.connection.validate',config.region??'us-east-1'));if(result.ok===false)return{ok:false,error:result.error,evidence:result.evidence};const payload=result.value as Record<string,unknown>;const accountId=typeof payload.accountId==='string'?payload.accountId:typeof payload.Account==='string'?payload.Account:undefined;if(!accountId)return{ok:false,error:{kind:'malformed_response',message:'AWS identity response was malformed',retryable:false},evidence:result.evidence};return{ok:true,value:{accountId},evidence:result.evidence}}
async observe(config:AwsRuntimeConfig,capabilityId:AwsCapability):Promise<AwsProviderResult<readonly AwsObservation[]>>{if(!awsCapabilities.includes(capabilityId))return{ok:false,error:{kind:'configuration',message:'Unsupported AWS capability',retryable:false},evidence:[ev('Unsupported AWS capability',{capabilityId})]};const result=await this.request(config,endpoint(capabilityId,config.region??'us-east-1'));if(result.ok===false)return{ok:false,error:result.error,evidence:result.evidence};const payload=result.value as Record<string,unknown>;const rows=Object.values(payload).find(Array.isArray) as unknown[]|undefined;return{ok:true,value:[{providerId:AWS_PROVIDER_ID,organizationId:config.organizationId,capabilityId,resourceType:capabilityId.split('.')[1]??'aws',resourceId:config.region??'global',observedAt:new Date().toISOString(),state:rows&&rows.length===0?'empty':'available',metadata:{count:rows?.length??1,region:config.region??'us-east-1'},evidence:result.evidence}],evidence:result.evidence}}}
export const AwsProvider=new AwsReadOnlyAdapter()
