import { randomUUID } from 'node:crypto'
import { UNIVERSAL_PROVIDER_SCHEMA_VERSION, type UniversalProviderCapability, type UniversalProviderHealth, type UniversalProviderMetadata, type UniversalProviderSdk } from './types.ts'

export const AZURE_PROVIDER_ID = 'azure' as const
export const azureCapabilities = ['azure.connection.validate','azure.subscriptions.list','azure.resource_groups.list','azure.resources.list','azure.compute.virtual_machines.list','azure.web.sites.list','azure.storage.accounts.list','azure.database.servers.list','azure.monitor.activity_logs.read','azure.advisor.recommendations.list'] as const
export type AzureCapability = typeof azureCapabilities[number]
export type AzureRuntimeConfig = { readonly organizationId:string; readonly accessToken:string; readonly subscriptionId?:string; readonly apiBaseUrl?:string }
export type AzureEvidence = { readonly evidenceId:string; readonly summary:string; readonly metadata:Readonly<Record<string,string|number|boolean|null>> }
export type AzureProviderError = { readonly kind:'authentication'|'authorization'|'not_found'|'rate_limited'|'timeout'|'provider_outage'|'malformed_response'|'unsupported_mutation'|'configuration'|'unknown'; readonly message:string; readonly retryable:boolean; readonly status?:number }
export type AzureProviderResult<T> = { readonly ok:true; readonly value:T; readonly evidence:readonly AzureEvidence[] } | { readonly ok:false; readonly error:AzureProviderError; readonly evidence:readonly AzureEvidence[] }
export type AzureObservation = { readonly providerId:typeof AZURE_PROVIDER_ID; readonly organizationId:string; readonly capabilityId:AzureCapability; readonly resourceType:string; readonly resourceId:string; readonly observedAt:string; readonly state:'available'|'empty'; readonly metadata:Readonly<Record<string,string|number|boolean|null>>; readonly evidence:readonly AzureEvidence[] }
type FetchLike = (url:string, init:RequestInit)=>Promise<Response>
const ev=(summary:string,metadata:AzureEvidence['metadata']={}):AzureEvidence=>({evidenceId:`evidence_${randomUUID()}`,summary,metadata})
function cap(id:AzureCapability):UniversalProviderCapability{return{capabilityId:id,displayNameKey:`universalProvider.azure.capabilities.${id}.title`,descriptionKey:`universalProvider.azure.capabilities.${id}.description`,version:'1.0.0',maturity:'sandbox_verified',riskClass:'read_only',channels:['api','scheduler'],environments:['sandbox','preview','production'],authentication:['oauth2'],requiresApproval:false,readOnly:true,rateLimit:{windowSeconds:300,maxRequests:15000,scope:'credential'},timeout:{connectMs:3000,readMs:10000,totalMs:15000},retryPolicy:{maxAttempts:3,backoff:'exponential',baseDelayMs:500,maxDelayMs:10000},scheduler:{supported:true,minimumIntervalSeconds:300,jitterSupported:true,localizationKey:'universalProvider.azure.scheduler'},evidenceProviderIds:['azure_management_snapshot'],verificationProviderIds:['azure_current_state']}}
export const azureProviderMetadata=Object.freeze<UniversalProviderMetadata>({providerId:AZURE_PROVIDER_ID,displayNameKey:'universalProvider.azure.displayName',descriptionKey:'universalProvider.azure.description',version:{providerVersion:'1.0.0',sdkVersion:'azure-management-readonly-v1',capabilityCatalogVersion:'azure-readonly-1',schemaVersion:UNIVERSAL_PROVIDER_SCHEMA_VERSION,compatibleSchemaVersions:[UNIVERSAL_PROVIDER_SCHEMA_VERSION]},health:{lifecycle:'registered',checkedAt:'1970-01-01T00:00:00.000Z'},capabilities:azureCapabilities.map(cap),supportedChannels:['api','scheduler'],supportedAuthentication:['oauth2'],supportedEnvironments:['sandbox','preview','production'],supportedRegions:['global'],configurationSchema:{schemaId:'azure.connection.v1',version:'1.0.0',fields:[{key:'credential_ref',type:'secret_ref',required:true,labelKey:'universalProvider.azure.config.credentialRef'},{key:'subscription_id',type:'string',required:false,labelKey:'universalProvider.azure.config.subscriptionId'}]},webhook:{supported:false,eventTypes:[],signatureSchemes:[],replayProtection:false},scheduler:{supported:true,minimumIntervalSeconds:300,jitterSupported:true,localizationKey:'universalProvider.azure.scheduler'},operator:{ownerTeamKey:'universalProvider.operator.ownerTeam',documentationKey:'universalProvider.azure.documentation'}})
function err(error:unknown,status?:number):AzureProviderError{if(error instanceof DOMException&&error.name==='AbortError')return{kind:'timeout',message:'Azure request timed out',retryable:true};if(status===401)return{kind:'authentication',message:'Azure credentials are invalid or expired',retryable:false,status};if(status===403)return{kind:'authorization',message:'Azure credentials lack read permission',retryable:false,status};if(status===404)return{kind:'not_found',message:'Azure resource was not found',retryable:false,status};if(status===429)return{kind:'rate_limited',message:'Azure rate limit reached',retryable:true,status};if(status&&status>=500)return{kind:'provider_outage',message:'Azure API is unavailable',retryable:true,status};return{kind:'unknown',message:'Azure request failed',retryable:false,status}}
function endpoint(id:AzureCapability,config:AzureRuntimeConfig):string{const sub=config.subscriptionId??'';switch(id){case'azure.connection.validate':case'azure.subscriptions.list':return'/subscriptions?api-version=2022-12-01';case'azure.resource_groups.list':return`/subscriptions/${sub}/resourcegroups?api-version=2021-04-01`;case'azure.resources.list':return`/subscriptions/${sub}/resources?api-version=2021-04-01`;case'azure.compute.virtual_machines.list':return`/subscriptions/${sub}/providers/Microsoft.Compute/virtualMachines?api-version=2023-09-01`;case'azure.web.sites.list':return`/subscriptions/${sub}/providers/Microsoft.Web/sites?api-version=2023-01-01`;case'azure.storage.accounts.list':return`/subscriptions/${sub}/providers/Microsoft.Storage/storageAccounts?api-version=2023-01-01`;case'azure.database.servers.list':return`/subscriptions/${sub}/providers/Microsoft.DBforPostgreSQL/flexibleServers?api-version=2023-06-01-preview`;case'azure.monitor.activity_logs.read':return`/subscriptions/${sub}/providers/microsoft.insights/eventtypes/management/values?api-version=2015-04-01`;case'azure.advisor.recommendations.list':return`/subscriptions/${sub}/providers/Microsoft.Advisor/recommendations?api-version=2023-01-01`}}
export class AzureReadOnlyAdapter implements UniversalProviderSdk{readonly metadata=azureProviderMetadata;constructor(private readonly fetcher:FetchLike=fetch){}listCapabilities(){return this.metadata.capabilities}getCapability(id:string){return this.metadata.capabilities.find(c=>c.capabilityId===id)}getHealth():UniversalProviderHealth{return this.metadata.health}getVersion(){return this.metadata.version}rejectMutation(operation:string):AzureProviderResult<never>{return{ok:false,error:{kind:'unsupported_mutation',message:`Azure mutation '${operation}' is not supported by the read-only adapter`,retryable:false},evidence:[ev('Rejected unsupported Azure mutation',{operation})]}}
private async request(config:AzureRuntimeConfig,path:string):Promise<AzureProviderResult<unknown>>{if(!config.accessToken)return{ok:false,error:{kind:'configuration',message:'Missing Azure credential',retryable:false},evidence:[ev('Missing Azure credential')]};const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),15000);try{const response=await this.fetcher(`${config.apiBaseUrl??'https://management.azure.com'}${path}`,{method:'GET',headers:{authorization:`Bearer ${config.accessToken}`,accept:'application/json'},signal:controller.signal});if(!response.ok)return{ok:false,error:err(undefined,response.status),evidence:[ev('Azure API returned an error',{status:response.status,path})]};return{ok:true,value:await response.json(),evidence:[ev('Azure read completed',{path})]}}catch(error){return{ok:false,error:err(error),evidence:[ev('Azure read failed',{path})]}}finally{clearTimeout(timer)}}
async validateConnection(config:AzureRuntimeConfig):Promise<AzureProviderResult<{subscriptions:number}>>{const result=await this.request(config,'/subscriptions?api-version=2022-12-01');if(result.ok===false)return{ok:false,error:result.error,evidence:result.evidence};const payload=result.value as Record<string,unknown>;const rows=Array.isArray(payload.value)?payload.value:null;if(!rows)return{ok:false,error:{kind:'malformed_response',message:'Azure subscriptions response was malformed',retryable:false},evidence:result.evidence};return{ok:true,value:{subscriptions:rows.length},evidence:result.evidence}}
async observe(config:AzureRuntimeConfig,capabilityId:AzureCapability):Promise<AzureProviderResult<readonly AzureObservation[]>>{if(!azureCapabilities.includes(capabilityId))return{ok:false,error:{kind:'configuration',message:'Unsupported Azure capability',retryable:false},evidence:[ev('Unsupported Azure capability',{capabilityId})]};if(capabilityId!=='azure.connection.validate'&&capabilityId!=='azure.subscriptions.list'&&!config.subscriptionId)return{ok:false,error:{kind:'configuration',message:'Missing Azure subscription id',retryable:false},evidence:[ev('Missing Azure subscription id',{capabilityId})]};const result=await this.request(config,endpoint(capabilityId,config));if(result.ok===false)return{ok:false,error:result.error,evidence:result.evidence};const payload=result.value as Record<string,unknown>;const rows=Array.isArray(payload.value)?payload.value:null;return{ok:true,value:[{providerId:AZURE_PROVIDER_ID,organizationId:config.organizationId,capabilityId,resourceType:capabilityId.split('.')[1]??'azure',resourceId:config.subscriptionId??capabilityId,observedAt:new Date().toISOString(),state:rows&&rows.length===0?'empty':'available',metadata:{count:rows?rows.length:1},evidence:result.evidence}],evidence:result.evidence}}}
export const AzureProvider=new AzureReadOnlyAdapter()
