// saas/lib/provider-framework/cloudflare.ts
import { randomUUID } from 'node:crypto'
import { UNIVERSAL_PROVIDER_SCHEMA_VERSION, type UniversalProviderCapability, type UniversalProviderHealth, type UniversalProviderMetadata, type UniversalProviderSdk } from './types.ts'

export const CLOUDFLARE_PROVIDER_ID = 'cloudflare' as const
export const cloudflareCapabilities = ['cloudflare.connection.validate','cloudflare.accounts.list','cloudflare.zones.list','cloudflare.zone.read','cloudflare.dns.records.list','cloudflare.ssl.settings.read','cloudflare.rulesets.list','cloudflare.workers.scripts.list','cloudflare.pages.projects.list','cloudflare.analytics.read'] as const
export type CloudflareCapability = typeof cloudflareCapabilities[number]
export type CloudflareRuntimeConfig = { readonly organizationId:string; readonly apiToken:string; readonly accountId?:string; readonly zoneId?:string; readonly apiBaseUrl?:string }
export type CloudflareEvidence = { readonly evidenceId:string; readonly summary:string; readonly metadata:Readonly<Record<string,string|number|boolean|null>> }
export type CloudflareProviderError = { readonly kind:'authentication'|'authorization'|'not_found'|'rate_limited'|'timeout'|'provider_outage'|'malformed_response'|'unsupported_mutation'|'configuration'|'unknown'; readonly message:string; readonly retryable:boolean; readonly status?:number }
export type CloudflareProviderResult<T> = { readonly ok:true; readonly value:T; readonly evidence:readonly CloudflareEvidence[] } | { readonly ok:false; readonly error:CloudflareProviderError; readonly evidence:readonly CloudflareEvidence[] }
export type CloudflareObservation = { readonly providerId:typeof CLOUDFLARE_PROVIDER_ID; readonly organizationId:string; readonly capabilityId:CloudflareCapability; readonly resourceType:string; readonly resourceId:string; readonly observedAt:string; readonly state:'available'|'empty'; readonly metadata:Readonly<Record<string,string|number|boolean|null>>; readonly evidence:readonly CloudflareEvidence[] }
type FetchLike = (url:string, init:RequestInit)=>Promise<Response>
const ev=(summary:string,metadata:CloudflareEvidence['metadata']={}):CloudflareEvidence=>({evidenceId:`evidence_${randomUUID()}`,summary,metadata})
function cap(id:CloudflareCapability):UniversalProviderCapability{return{capabilityId:id,displayNameKey:`universalProvider.cloudflare.capabilities.${id}.title`,descriptionKey:`universalProvider.cloudflare.capabilities.${id}.description`,version:'1.0.0',maturity:'sandbox_verified',riskClass:'read_only',channels:['api','scheduler'],environments:['sandbox','preview','production'],authentication:['api_key'],requiresApproval:false,readOnly:true,rateLimit:{windowSeconds:300,maxRequests:1200,scope:'credential'},timeout:{connectMs:3000,readMs:10000,totalMs:15000},retryPolicy:{maxAttempts:3,backoff:'exponential',baseDelayMs:500,maxDelayMs:10000},scheduler:{supported:true,minimumIntervalSeconds:300,jitterSupported:true,localizationKey:'universalProvider.cloudflare.scheduler'},evidenceProviderIds:['cloudflare_api_snapshot'],verificationProviderIds:['cloudflare_current_state']}}
export const cloudflareProviderMetadata=Object.freeze<UniversalProviderMetadata>({providerId:CLOUDFLARE_PROVIDER_ID,displayNameKey:'universalProvider.cloudflare.displayName',descriptionKey:'universalProvider.cloudflare.description',version:{providerVersion:'1.0.0',sdkVersion:'cloudflare-rest-readonly-v1',capabilityCatalogVersion:'cloudflare-readonly-1',schemaVersion:UNIVERSAL_PROVIDER_SCHEMA_VERSION,compatibleSchemaVersions:[UNIVERSAL_PROVIDER_SCHEMA_VERSION]},health:{lifecycle:'registered',checkedAt:'1970-01-01T00:00:00.000Z'},capabilities:cloudflareCapabilities.map(cap),supportedChannels:['api','scheduler'],supportedAuthentication:['api_key'],supportedEnvironments:['sandbox','preview','production'],supportedRegions:['global'],configurationSchema:{schemaId:'cloudflare.connection.v1',version:'1.0.0',fields:[{key:'credential_ref',type:'secret_ref',required:true,labelKey:'universalProvider.cloudflare.config.credentialRef'},{key:'account_id',type:'string',required:false,labelKey:'universalProvider.cloudflare.config.accountId'},{key:'zone_id',type:'string',required:false,labelKey:'universalProvider.cloudflare.config.zoneId'}]},webhook:{supported:false,eventTypes:[],signatureSchemes:[],replayProtection:false},scheduler:{supported:true,minimumIntervalSeconds:300,jitterSupported:true,localizationKey:'universalProvider.cloudflare.scheduler'},operator:{ownerTeamKey:'universalProvider.operator.ownerTeam',documentationKey:'universalProvider.cloudflare.documentation'}})
function err(error:unknown,status?:number):CloudflareProviderError{if(error instanceof DOMException&&error.name==='AbortError')return{kind:'timeout',message:'Cloudflare request timed out',retryable:true};if(status===401)return{kind:'authentication',message:'Cloudflare credentials are invalid or revoked',retryable:false,status};if(status===403)return{kind:'authorization',message:'Cloudflare credentials lack read permission',retryable:false,status};if(status===404)return{kind:'not_found',message:'Cloudflare resource was not found',retryable:false,status};if(status===429)return{kind:'rate_limited',message:'Cloudflare rate limit reached',retryable:true,status};if(status&&status>=500)return{kind:'provider_outage',message:'Cloudflare API is unavailable',retryable:true,status};return{kind:'unknown',message:'Cloudflare request failed',retryable:false,status}}
function endpoint(id:CloudflareCapability,config:CloudflareRuntimeConfig):string{switch(id){case'cloudflare.connection.validate':return'/user/tokens/verify';case'cloudflare.accounts.list':return'/accounts';case'cloudflare.zones.list':return'/zones';case'cloudflare.zone.read':return`/zones/${config.zoneId??''}`;case'cloudflare.dns.records.list':return`/zones/${config.zoneId??''}/dns_records`;case'cloudflare.ssl.settings.read':return`/zones/${config.zoneId??''}/settings/ssl`;case'cloudflare.rulesets.list':return`/zones/${config.zoneId??''}/rulesets`;case'cloudflare.workers.scripts.list':return`/accounts/${config.accountId??''}/workers/scripts`;case'cloudflare.pages.projects.list':return`/accounts/${config.accountId??''}/pages/projects`;case'cloudflare.analytics.read':return`/zones/${config.zoneId??''}/analytics/dashboard`}}
export class CloudflareReadOnlyAdapter implements UniversalProviderSdk{readonly metadata=cloudflareProviderMetadata;private readonly fetcher: FetchLike;constructor(fetcher: FetchLike = fetch){this.fetcher = fetcher;}listCapabilities(){return this.metadata.capabilities}getCapability(id:string){return this.metadata.capabilities.find(c=>c.capabilityId===id)}getHealth():UniversalProviderHealth{return this.metadata.health}getVersion(){return this.metadata.version}rejectMutation(operation:string):CloudflareProviderResult<never>{return{ok:false,error:{kind:'unsupported_mutation',message:`Cloudflare mutation '${operation}' is not supported by the read-only adapter`,retryable:false},evidence:[ev('Rejected unsupported Cloudflare mutation',{operation})]}}
private async request(config:CloudflareRuntimeConfig,path:string):Promise<CloudflareProviderResult<unknown>>{if(!config.apiToken)return{ok:false,error:{kind:'configuration',message:'Missing Cloudflare credential',retryable:false},evidence:[ev('Missing Cloudflare credential')]};const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),15000);try{const response=await this.fetcher(`${config.apiBaseUrl??'https://api.cloudflare.com/client/v4'}${path}`,{method:'GET',headers:{authorization:`Bearer ${config.apiToken}`,accept:'application/json'},signal:controller.signal});if(!response.ok)return{ok:false,error:err(undefined,response.status),evidence:[ev('Cloudflare API returned an error',{status:response.status,path})]};const json=await response.json() as unknown;return{ok:true,value:json,evidence:[ev('Cloudflare read completed',{path})]}}catch(error){return{ok:false,error:err(error),evidence:[ev('Cloudflare read failed',{path})]}}finally{clearTimeout(timer)}}
async validateConnection(config:CloudflareRuntimeConfig):Promise<CloudflareProviderResult<{status:string}>>{const result=await this.request(config,'/user/tokens/verify');if(result.ok===false)return{ok:false,error:result.error,evidence:result.evidence};const payload=result.value as Record<string,unknown>;const value=payload.result as Record<string,unknown>|undefined;if(typeof value?.status!=='string')return{ok:false,error:{kind:'malformed_response',message:'Cloudflare token response was malformed',retryable:false},evidence:result.evidence};return{ok:true,value:{status:value.status},evidence:result.evidence}}
async observe(config:CloudflareRuntimeConfig,capabilityId:CloudflareCapability):Promise<CloudflareProviderResult<readonly CloudflareObservation[]>>{if(!cloudflareCapabilities.includes(capabilityId))return{ok:false,error:{kind:'configuration',message:'Unsupported Cloudflare capability',retryable:false},evidence:[ev('Unsupported Cloudflare capability',{capabilityId})]};const result=await this.request(config,endpoint(capabilityId,config));if(result.ok===false)return{ok:false,error:result.error,evidence:result.evidence};const payload=result.value as Record<string,unknown>;const data=payload.result;const rows=Array.isArray(data)?data:null;return{ok:true,value:[{providerId:CLOUDFLARE_PROVIDER_ID,organizationId:config.organizationId,capabilityId,resourceType:capabilityId.split('.')[1]??'cloudflare',resourceId:config.zoneId??config.accountId??capabilityId,observedAt:new Date().toISOString(),state:rows&&rows.length===0?'empty':'available',metadata:{count:rows?rows.length:1},evidence:result.evidence}],evidence:result.evidence}}}
export const CloudflareProvider=new CloudflareReadOnlyAdapter()
