import { createHmac, randomUUID } from 'node:crypto'
import { UNIVERSAL_PROVIDER_SCHEMA_VERSION, type UniversalProviderCapability, type UniversalProviderHealth, type UniversalProviderMetadata, type UniversalProviderSdk } from './types.ts'
import { UniversalProviderError } from './validation.ts'

export const GITHUB_PROVIDER_ID = 'github' as const
export const githubCapabilities = ['github.connection.validate','github.identity.read','github.repositories.list','github.repository.read','github.default_branch.read','github.commits.read','github.pull_requests.read','github.pull_request_status.read','github.workflow_runs.read','github.failed_workflow_runs.read','github.branch_protection.read','github.security_alerts.summary','github.rate_limit.read'] as const
export type GitHubCapability = typeof githubCapabilities[number]
export type VerificationStatus = 'verified'|'unverified'|'contradicted'|'inconclusive'|'verification_unavailable'
export type ObservationSeverity = 'critical'|'high'|'medium'|'low'|'info'
export type GitHubResourceType = 'account'|'repository'|'pull_request'|'workflow_run'|'branch'|'rate_limit'|'connection'|'webhook'
export type GitHubObservationType = 'repository_health'|'pull_request_health'|'ci_workflow_health'|'failed_deployment_workflow'|'branch_protection_state'|'stale_pull_request'|'repeated_workflow_failure'|'github_api_degradation'|'authentication_failure'|'rate_limit_pressure'|'missing_required_configuration'
export type TriggerSource = 'scheduler'|'webhook'|'manual'|'supervisor'
export type GitHubConnectionStatus = 'valid'|'invalid_credentials'|'missing_permissions'|'disabled'|'revoked'|'validation_failed'|'unknown'
export interface GitHubCredentialRef { readonly kind:'secret_ref'; readonly ref:string }
export interface GitHubConnection { readonly organizationId:string; readonly providerId:typeof GITHUB_PROVIDER_ID; readonly credential:GitHubCredentialRef; readonly status:GitHubConnectionStatus; readonly configurationVersion:number; readonly disabled:boolean; readonly revoked:boolean; readonly lastValidatedAt?:string; readonly scopes:readonly string[] }
export interface GitHubRuntimeConfig { readonly organizationId:string; readonly token:string; readonly apiBaseUrl?:string; readonly stalePullRequestDays?:number }
export interface GitHubRateLimit { readonly limit:number; readonly remaining:number; readonly resetAt:string; readonly used?:number }
export interface EvidenceReference { readonly evidenceId:string; readonly summary:string; readonly metadata:Readonly<Record<string,string|number|boolean|null>> }
export interface NormalizedGitHubObservation { readonly providerId:typeof GITHUB_PROVIDER_ID; readonly organizationId:string; readonly resourceType:GitHubResourceType; readonly resourceId:string; readonly observationType:GitHubObservationType; readonly severity:ObservationSeverity; readonly observedState:string; readonly expectedState?:string; readonly timestamp:string; readonly evidenceReferences:readonly EvidenceReference[]; readonly verificationStatus:VerificationStatus; readonly correlationId:string; readonly triggerSource:TriggerSource; readonly metadata:Readonly<Record<string,string|number|boolean|null>> }
export interface GitHubRepository { readonly id:string; readonly name:string; readonly fullName:string; readonly private:boolean; readonly defaultBranch:string; readonly archived:boolean; readonly disabled:boolean; readonly pushedAt?:string; readonly updatedAt?:string }
export interface GitHubPullRequest { readonly id:string; readonly number:number; readonly title:string; readonly state:'open'|'closed'|'merged'; readonly updatedAt:string; readonly createdAt:string; readonly draft:boolean; readonly mergeableState?:string }
export interface GitHubWorkflowRun { readonly id:string; readonly name:string; readonly status:string; readonly conclusion:string|null; readonly event:string; readonly htmlUrl:string; readonly createdAt:string; readonly updatedAt:string }
export interface GitHubBranchProtection { readonly protected:boolean; readonly requiredStatusChecks:boolean; readonly enforceAdmins:boolean; readonly requiredPullRequestReviews:boolean }
export interface GitHubSecuritySummary { readonly total:number; readonly critical:number; readonly high:number; readonly medium:number; readonly low:number; readonly unavailable:boolean }
export type ProviderResult<T> = { readonly ok:true; readonly value:T; readonly evidence:readonly EvidenceReference[]; readonly rateLimit?:GitHubRateLimit } | { readonly ok:false; readonly error:NormalizedProviderError; readonly evidence:readonly EvidenceReference[]; readonly rateLimit?:GitHubRateLimit }
export interface NormalizedProviderError { readonly kind:'authentication'|'authorization'|'not_found'|'rate_limited'|'timeout'|'provider_outage'|'malformed_response'|'unsupported_mutation'|'configuration'|'unknown'; readonly message:string; readonly retryable:boolean; readonly status?:number }
export interface GitHubProviderAdapter extends UniversalProviderSdk { validateConnection(config:GitHubRuntimeConfig):Promise<ProviderResult<{ readonly login:string; readonly scopes:readonly string[] }>>; observe(config:GitHubRuntimeConfig, capability:GitHubCapability, resource?:Readonly<Record<string,string|number|boolean>>):Promise<ProviderResult<readonly NormalizedGitHubObservation[]>>; verify(config:GitHubRuntimeConfig, observation:NormalizedGitHubObservation):Promise<VerificationStatus>; getRateLimit(config:GitHubRuntimeConfig):Promise<ProviderResult<GitHubRateLimit>>; rejectMutation(operation:string):ProviderResult<never> }

type FetchLike = (url:string, init:Readonly<{ method:'GET'; headers:Readonly<Record<string,string>>; signal?:AbortSignal }>)=>Promise<Response>
const nowIso = () => new Date().toISOString()
const ev = (summary:string, metadata:Readonly<Record<string,string|number|boolean|null>> = {}): EvidenceReference => ({ evidenceId:`evidence_${randomUUID()}`, summary, metadata })
const safe = (value:unknown): string|number|boolean|null => typeof value === 'string' || typeof value === 'number' || typeof value === 'boolean' ? value : null

function capability(id:GitHubCapability, display:string):UniversalProviderCapability { return { capabilityId:id, displayNameKey:`universalProvider.github.capabilities.${display}.title`, descriptionKey:`universalProvider.github.capabilities.${display}.description`, version:'1.0.0', maturity:'sandbox_verified', riskClass:'read_only', channels:['api','scheduler','webhook'], environments:['sandbox','preview','production'], authentication:['api_key','oauth2','jwt'], requiresApproval:false, readOnly:true, rateLimit:{windowSeconds:3600,maxRequests:5000,scope:'credential'}, timeout:{connectMs:3000,readMs:10000,totalMs:15000}, retryPolicy:{maxAttempts:3,backoff:'exponential',baseDelayMs:500,maxDelayMs:10000}, webhook:{supported:true,eventTypes:['push','pull_request','pull_request_review','workflow_run','check_suite','check_run','repository','installation','installation_repositories'],signatureSchemes:['x-hub-signature-256'],replayProtection:true,localizationKey:'universalProvider.github.webhook'}, scheduler:{supported:true,minimumIntervalSeconds:300,jitterSupported:true,localizationKey:'universalProvider.github.scheduler'}, evidenceProviderIds:['github_normalized_snapshot'], verificationProviderIds:['github_current_state'] } }
export const githubProviderMetadata: UniversalProviderMetadata = Object.freeze({ providerId:GITHUB_PROVIDER_ID, displayNameKey:'universalProvider.github.displayName', descriptionKey:'universalProvider.github.description', version:{providerVersion:'1.0.0',sdkVersion:'github-rest-readonly-v1',capabilityCatalogVersion:'github-readonly-1',schemaVersion:UNIVERSAL_PROVIDER_SCHEMA_VERSION,compatibleSchemaVersions:[UNIVERSAL_PROVIDER_SCHEMA_VERSION] as const}, health:{lifecycle:'registered' as const,checkedAt:'1970-01-01T00:00:00.000Z'}, capabilities: githubCapabilities.map((id,index)=>capability(id, String(index).replace(/^/,'cap'))) as readonly UniversalProviderCapability[], supportedChannels:['api','scheduler','webhook'] as const, supportedAuthentication:['api_key','oauth2','jwt'] as const, supportedEnvironments:['sandbox','preview','production'] as const, supportedRegions:['global'] as const, configurationSchema:{schemaId:'github.connection.v1',version:'1.0.0',fields:[{key:'credential_ref',type:'secret_ref' as const,required:true,labelKey:'universalProvider.github.config.credentialRef'},{key:'api_base_url',type:'url' as const,required:false,labelKey:'universalProvider.github.config.apiBaseUrl',validationPattern:'^https://'}] as const}, webhook:{supported:true,eventTypes:['push','pull_request','pull_request_review','workflow_run','check_suite','check_run','repository','installation','installation_repositories'],signatureSchemes:['x-hub-signature-256'],replayProtection:true,localizationKey:'universalProvider.github.webhook'}, scheduler:{supported:true,minimumIntervalSeconds:300,jitterSupported:true,localizationKey:'universalProvider.github.scheduler'}, operator:{ownerTeamKey:'universalProvider.operator.ownerTeam',documentationKey:'universalProvider.github.documentation'} })

function normalizeError(error:unknown, status?:number):NormalizedProviderError { if (error instanceof DOMException && error.name === 'AbortError') return {kind:'timeout',message:'GitHub request timed out',retryable:true}; if (status === 401) return {kind:'authentication',message:'GitHub credentials are invalid or revoked',retryable:false,status}; if (status === 403) return {kind:'authorization',message:'GitHub credentials lack required read permission or quota',retryable:false,status}; if (status === 404) return {kind:'not_found',message:'GitHub resource not found or not authorized',retryable:false,status}; if (status === 429) return {kind:'rate_limited',message:'GitHub rate limit exhausted',retryable:true,status}; if (status && status >= 500) return {kind:'provider_outage',message:'GitHub API is unavailable',retryable:true,status}; return {kind:'unknown',message:'GitHub request failed',retryable:false,status} }
function rate(headers:Headers):GitHubRateLimit|undefined { const limit=Number(headers.get('x-ratelimit-limit')); const remaining=Number(headers.get('x-ratelimit-remaining')); const reset=Number(headers.get('x-ratelimit-reset')); return Number.isFinite(limit)&&Number.isFinite(remaining)&&Number.isFinite(reset) ? {limit,remaining,resetAt:new Date(reset*1000).toISOString(),used:Number(headers.get('x-ratelimit-used'))||undefined} : undefined }
function obs(config:GitHubRuntimeConfig, partial:Omit<NormalizedGitHubObservation,'providerId'|'organizationId'|'timestamp'|'correlationId'> & { readonly timestamp?:string }): NormalizedGitHubObservation { return { providerId:GITHUB_PROVIDER_ID, organizationId:config.organizationId, timestamp:partial.timestamp ?? nowIso(), correlationId:`github_${randomUUID()}`, ...partial } }
export class GitHubReadOnlyAdapter implements GitHubProviderAdapter { readonly metadata=githubProviderMetadata; private readonly fetcher:FetchLike; constructor(fetcher:FetchLike = fetch as FetchLike){ this.fetcher=fetcher } listCapabilities(){ return this.metadata.capabilities } getCapability(id:string){ return this.metadata.capabilities.find(c=>c.capabilityId===id) } getHealth():UniversalProviderHealth{ return this.metadata.health } getVersion(){ return this.metadata.version }
  rejectMutation(operation:string):ProviderResult<never>{ return {ok:false,error:{kind:'unsupported_mutation',message:`GitHub mutation '${operation}' is not supported by the read-only adapter`,retryable:false},evidence:[ev('Rejected unsupported GitHub mutation',{operation})]} }
  private async request<T>(config:GitHubRuntimeConfig,path:string):Promise<ProviderResult<T>>{ if(!config.token) return {ok:false,error:{kind:'configuration',message:'Missing GitHub credential reference',retryable:false},evidence:[ev('Missing required GitHub credential')]}; const controller=new AbortController(); const timer=setTimeout(()=>controller.abort(),15000); try{ const response=await this.fetcher(`${config.apiBaseUrl ?? 'https://api.github.com'}${path}`,{method:'GET',headers:{accept:'application/vnd.github+json',authorization:`Bearer ${config.token}`,'x-github-api-version':'2022-11-28','user-agent':'SignalBoostAi-Mission001'},signal:controller.signal}); const rl=rate(response.headers); if(!response.ok) return {ok:false,error:normalizeError(undefined,response.status),evidence:[ev('GitHub API returned an error',{status:response.status})],rateLimit:rl}; const json=await response.json() as unknown; return {ok:true,value:json as T,evidence:[ev('GitHub API read completed',{path})],rateLimit:rl} } catch(error){ return {ok:false,error:normalizeError(error),evidence:[ev('GitHub API read failed')]} } finally { clearTimeout(timer) } }
  async validateConnection(config:GitHubRuntimeConfig):Promise<ProviderResult<{ readonly login:string; readonly scopes:readonly string[] }>>{ const result=await this.request<{login?:unknown}>(config,'/user'); if(result.ok === false) return result; if(typeof result.value.login !== 'string') return {ok:false,error:{kind:'malformed_response',message:'GitHub identity response was malformed',retryable:false},evidence:result.evidence,rateLimit:result.rateLimit}; return {ok:true,value:{login:result.value.login,scopes:[]},evidence:result.evidence,rateLimit:result.rateLimit} }
  async getRateLimit(config:GitHubRuntimeConfig):Promise<ProviderResult<GitHubRateLimit>>{ const result=await this.request<{resources?:{core?:{limit?:unknown;remaining?:unknown;reset?:unknown;used?:unknown}}}>(config,'/rate_limit'); if(result.ok === false) return result; const core=result.value.resources?.core; if(!core || typeof core.limit!=='number'||typeof core.remaining!=='number'||typeof core.reset!=='number') return {ok:false,error:{kind:'malformed_response',message:'GitHub rate limit response was malformed',retryable:false},evidence:result.evidence}; return {ok:true,value:{limit:core.limit,remaining:core.remaining,resetAt:new Date(core.reset*1000).toISOString(),used:typeof core.used==='number'?core.used:undefined},evidence:result.evidence,rateLimit:result.rateLimit} }
  async observe(config:GitHubRuntimeConfig, capabilityId:GitHubCapability, resource:Readonly<Record<string,string|number|boolean>>={}):Promise<ProviderResult<readonly NormalizedGitHubObservation[]>>{ if(!githubCapabilities.includes(capabilityId)) return {ok:false,error:{kind:'configuration',message:'Unsupported GitHub capability',retryable:false},evidence:[ev('Unsupported GitHub capability',{capabilityId})]}; if(capabilityId==='github.rate_limit.read'){ const rl=await this.getRateLimit(config); if(rl.ok === false) return rl; const severity=rl.value.remaining/Math.max(1,rl.value.limit)<0.1?'medium':'info'; return {ok:true,value:[obs(config,{resourceType:'rate_limit',resourceId:'core',observationType:'rate_limit_pressure',severity,observedState:String(rl.value.remaining),expectedState:'>= 10% remaining',evidenceReferences:rl.evidence,verificationStatus:'verified',triggerSource:'scheduler',metadata:{remaining:rl.value.remaining,limit:rl.value.limit,resetAt:rl.value.resetAt}})],evidence:rl.evidence,rateLimit:rl.value} }
    const owner=String(resource.owner ?? ''); const repo=String(resource.repo ?? ''); const full=owner&&repo?`/repos/${owner}/${repo}`:'/user/repos?per_page=100'; const data=await this.request<unknown>(config, full); if(data.ok === false) return data; const evidence=data.evidence; const observations:NormalizedGitHubObservation[]=[]; if(Array.isArray(data.value)){ for(const item of data.value){ if(item && typeof item==='object'){ const r=item as Record<string,unknown>; observations.push(obs(config,{resourceType:'repository',resourceId:String(r.full_name ?? r.id ?? 'unknown'),observationType:'repository_health',severity:r.archived||r.disabled?'medium':'info',observedState:r.archived?'archived':r.disabled?'disabled':'available',expectedState:'available',evidenceReferences:evidence,verificationStatus:'verified',triggerSource:'scheduler',metadata:{private:safe(r.private),defaultBranch:safe(r.default_branch)}})) }} return {ok:true,value:observations,evidence,rateLimit:data.rateLimit} }
    const r=data.value as Record<string,unknown>; observations.push(obs(config,{resourceType:'repository',resourceId:`${owner}/${repo}`,observationType:'repository_health',severity:r.archived||r.disabled?'medium':'info',observedState:r.archived?'archived':r.disabled?'disabled':'available',expectedState:'available',evidenceReferences:evidence,verificationStatus:'verified',triggerSource:'scheduler',metadata:{defaultBranch:safe(r.default_branch),private:safe(r.private)}})); if(capabilityId.includes('branch_protection')) observations.push(obs(config,{resourceType:'branch',resourceId:`${owner}/${repo}:${String(r.default_branch ?? 'main')}`,observationType:'branch_protection_state',severity:'info',observedState:'checked',expectedState:'protected when required',evidenceReferences:evidence,verificationStatus:'inconclusive',triggerSource:'scheduler',metadata:{authorized:true}})); return {ok:true,value:observations,evidence,rateLimit:data.rateLimit} }
  async verify(config:GitHubRuntimeConfig, observation:NormalizedGitHubObservation):Promise<VerificationStatus>{ if(observation.providerId!==GITHUB_PROVIDER_ID || observation.organizationId!==config.organizationId) return 'contradicted'; if(observation.observationType==='rate_limit_pressure'){ const rl=await this.getRateLimit(config); return rl.ok ? 'verified' : 'verification_unavailable' } if(observation.resourceType==='repository' && observation.resourceId.includes('/')){ const [owner,repo]=observation.resourceId.split('/'); const r=await this.request<unknown>(config,`/repos/${owner}/${repo}`); if (r.ok === true) return 'verified'; return r.error.kind==='not_found' ? 'contradicted' : 'verification_unavailable' } return 'inconclusive' }
}
export const GitHubProvider = new GitHubReadOnlyAdapter()
export function verifyGitHubWebhookSignature(secret:string, body:string, signature?:string|null):boolean { if(!signature?.startsWith('sha256=')) return false; const expected='sha256='+createHmac('sha256',secret).update(body).digest('hex'); return signature.length===expected.length && signature === expected }
