// saas/lib/provider-framework/google-cloud.ts
import { randomUUID } from 'node:crypto'
import { UNIVERSAL_PROVIDER_SCHEMA_VERSION, type UniversalProviderCapability, type UniversalProviderHealth, type UniversalProviderMetadata, type UniversalProviderSdk } from './types.ts'

export const GOOGLE_CLOUD_PROVIDER_ID = 'google-cloud' as const
export const googleCloudCapabilities = ['google_cloud.connection.validate','google_cloud.projects.read','google_cloud.compute.instances.list','google_cloud.storage.buckets.list','google_cloud.cloud_run.services.list','google_cloud.functions.list','google_cloud.sql.instances.list','google_cloud.pubsub.topics.list','google_cloud.logging.entries.list','google_cloud.monitoring.alert_policies.list'] as const
export type GoogleCloudCapability = typeof googleCloudCapabilities[number]
export type GoogleCloudRuntimeConfig = { readonly organizationId:string; readonly accessToken:string; readonly projectId:string; readonly region?:string; readonly zone?:string }
export type GoogleCloudEvidence = { readonly evidenceId:string; readonly summary:string; readonly metadata:Readonly<Record<string,string|number|boolean|null>> }
export type GoogleCloudProviderError = { readonly kind:'authentication'|'authorization'|'not_found'|'rate_limited'|'timeout'|'provider_outage'|'malformed_response'|'unsupported_mutation'|'configuration'|'unknown'; readonly message:string; readonly retryable:boolean; readonly status?:number }
export type GoogleCloudProviderResult<T> = { readonly ok:true; readonly value:T; readonly evidence:readonly GoogleCloudEvidence[] } | { readonly ok:false; readonly error:GoogleCloudProviderError; readonly evidence:readonly GoogleCloudEvidence[] }
export type GoogleCloudObservation = { readonly providerId:typeof GOOGLE_CLOUD_PROVIDER_ID; readonly organizationId:string; readonly capabilityId:GoogleCloudCapability; readonly resourceType:string; readonly resourceId:string; readonly observedAt:string; readonly state:'available'|'empty'; readonly metadata:Readonly<Record<string,string|number|boolean|null>>; readonly evidence:readonly GoogleCloudEvidence[] }
type FetchLike = (url:string, init:RequestInit)=>Promise<Response>
const ev=(summary:string,metadata:GoogleCloudEvidence['metadata']={}):GoogleCloudEvidence=>({evidenceId:`evidence_${randomUUID()}`,summary,metadata})
function cap(id:GoogleCloudCapability):UniversalProviderCapability{return{capabilityId:id,displayNameKey:`universalProvider.googleCloud.capabilities.${id}.title`,descriptionKey:`universalProvider.googleCloud.capabilities.${id}.description`,version:'1.0.0',maturity:'sandbox_verified',riskClass:'read_only',channels:['api','scheduler'],environments:['sandbox','preview','production'],authentication:['oauth2','service_role'],requiresApproval:false,readOnly:true,rateLimit:{windowSeconds:60,maxRequests:600,scope:'credential'},timeout:{connectMs:3000,readMs:10000,totalMs:15000},retryPolicy:{maxAttempts:3,backoff:'exponential',baseDelayMs:500,maxDelayMs:10000},scheduler:{supported:true,minimumIntervalSeconds:300,jitterSupported:true,localizationKey:'universalProvider.googleCloud.scheduler'},evidenceProviderIds:['google_cloud_api_snapshot'],verificationProviderIds:['google_cloud_current_state']}}
export const googleCloudProviderMetadata=Object.freeze<UniversalProviderMetadata>({providerId:GOOGLE_CLOUD_PROVIDER_ID,displayNameKey:'universalProvider.googleCloud.displayName',descriptionKey:'universalProvider.googleCloud.description',version:{providerVersion:'1.0.0',sdkVersion:'google-cloud-rest-readonly-v1',capabilityCatalogVersion:'google-cloud-readonly-1',schemaVersion:UNIVERSAL_PROVIDER_SCHEMA_VERSION,compatibleSchemaVersions:[UNIVERSAL_PROVIDER_SCHEMA_VERSION]},health:{lifecycle:'registered',checkedAt:'1970-01-01T00:00:00.000Z'},capabilities:googleCloudCapabilities.map(cap),supportedChannels:['api','scheduler'],supportedAuthentication:['oauth2','service_role'],supportedEnvironments:['sandbox','preview','production'],supportedRegions:['global'],configurationSchema:{schemaId:'google-cloud.connection.v1',version:'1.0.0',fields:[{key:'credential_ref',type:'secret_ref',required:true,labelKey:'universalProvider.googleCloud.config.credentialRef'},{key:'project_id',type:'string',required:true,labelKey:'universalProvider.googleCloud.config.projectId'},{key:'region',type:'string',required:false,labelKey:'universalProvider.googleCloud.config.region'},{key:'zone',type:'string',required:false,labelKey:'universalProvider.googleCloud.config.zone'}]},webhook:{supported:false,eventTypes:[],signatureSchemes:[],replayProtection:false},scheduler:{supported:true,minimumIntervalSeconds:300,jitterSupported:true,localizationKey:'universalProvider.googleCloud.scheduler'},operator:{ownerTeamKey:'universalProvider.operator.ownerTeam',documentationKey:'universalProvider.googleCloud.documentation'}})
function err(error:unknown,status?:number):GoogleCloudProviderError{if(error instanceof DOMException&&error.name==='AbortError')return{kind:'timeout',message:'Google Cloud request timed out',retryable:true};if(status===401)return{kind:'authentication',message:'Google Cloud credentials are invalid or revoked',retryable:false,status};if(status===403)return{kind:'authorization',message:'Google Cloud credentials lack read permission',retryable:false,status};if(status===404)return{kind:'not_found',message:'Google Cloud resource was not found',retryable:false,status};if(status===429)return{kind:'rate_limited',message:'Google Cloud rate limit reached',retryable:true,status};if(status&&status>=500)return{kind:'provider_outage',message:'Google Cloud API is unavailable',retryable:true,status};return{kind:'unknown',message:'Google Cloud request failed',retryable:false,status}}
function endpoint(id:GoogleCloudCapability,config:GoogleCloudRuntimeConfig):string{const project=encodeURIComponent(config.projectId);const region=encodeURIComponent(config.region??'-');const zone=encodeURIComponent(config.zone??'-');switch(id){case'google_cloud.connection.validate':case'google_cloud.projects.read':return`https://cloudresourcemanager.googleapis.com/v3/projects/${project}`;case'google_cloud.compute.instances.list':return`https://compute.googleapis.com/compute/v1/projects/${project}/zones/${zone}/instances`;case'google_cloud.storage.buckets.list':return`https://storage.googleapis.com/storage/v1/b?project=${project}`;case'google_cloud.cloud_run.services.list':return`https://run.googleapis.com/v2/projects/${project}/locations/${region}/services`;case'google_cloud.functions.list':return`https://cloudfunctions.googleapis.com/v2/projects/${project}/locations/${region}/functions`;case'google_cloud.sql.instances.list':return`https://sqladmin.googleapis.com/sql/v1beta4/projects/${project}/instances`;case'google_cloud.pubsub.topics.list':return`https://pubsub.googleapis.com/v1/projects/${project}/topics`;case'google_cloud.logging.entries.list':return`https://logging.googleapis.com/v2/entries:list`;case'google_cloud.monitoring.alert_policies.list':return`https://monitoring.googleapis.com/v3/projects/${project}/alertPolicies`}}
export class GoogleCloudReadOnlyAdapter implements UniversalProviderSdk{readonly metadata=googleCloudProviderMetadata;private readonly fetcher: FetchLike;constructor(fetcher: FetchLike = fetch){this.fetcher = fetcher;}listCapabilities(){return this.metadata.capabilities}getCapability(id:string){return this.metadata.capabilities.find(c=>c.capabilityId===id)}getHealth():UniversalProviderHealth{return this.metadata.health}getVersion(){return this.metadata.version}rejectMutation(operation:string):GoogleCloudProviderResult<never>{return{ok:false,error:{kind:'unsupported_mutation',message:`Google Cloud mutation '${operation}' is not supported by the read-only adapter`,retryable:false},evidence:[ev('Rejected unsupported Google Cloud mutation',{operation})]}}
private async request(config:GoogleCloudRuntimeConfig,url:string):Promise<GoogleCloudProviderResult<unknown>>{if(!config.accessToken||!config.projectId)return{ok:false,error:{kind:'configuration',message:'Missing Google Cloud credential or project',retryable:false},evidence:[ev('Missing Google Cloud configuration')]};const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),15000);try{const response=await this.fetcher(url,{method:'GET',headers:{authorization:`Bearer ${config.accessToken}`,accept:'application/json'},signal:controller.signal});if(!response.ok)return{ok:false,error:err(undefined,response.status),evidence:[ev('Google Cloud API returned an error',{status:response.status})]};return{ok:true,value:await response.json(),evidence:[ev('Google Cloud read completed',{capabilityUrl:url.split('?')[0]})]}}catch(error){return{ok:false,error:err(error),evidence:[ev('Google Cloud read failed')]}}finally{clearTimeout(timer)}}
async validateConnection(config:GoogleCloudRuntimeConfig):Promise<GoogleCloudProviderResult<{projectId:string}>>{const result=await this.request(config,endpoint('google_cloud.connection.validate',config));if(result.ok===false)return{ok:false,error:result.error,evidence:result.evidence};const value=result.value as Record<string,unknown>;const id=typeof value.projectId==='string'?value.projectId:typeof value.name==='string'?value.name.split('/').pop():undefined;if(!id)return{ok:false,error:{kind:'malformed_response',message:'Google Cloud project response was malformed',retryable:false},evidence:result.evidence};return{ok:true,value:{projectId:id},evidence:result.evidence}}
async observe(config:GoogleCloudRuntimeConfig,capabilityId:GoogleCloudCapability):Promise<GoogleCloudProviderResult<readonly GoogleCloudObservation[]>>{if(!googleCloudCapabilities.includes(capabilityId))return{ok:false,error:{kind:'configuration',message:'Unsupported Google Cloud capability',retryable:false},evidence:[ev('Unsupported Google Cloud capability',{capabilityId})]};const result=await this.request(config,endpoint(capabilityId,config));if(result.ok===false)return{ok:false,error:result.error,evidence:result.evidence};const payload=result.value as Record<string,unknown>;const rows=Object.values(payload).find(Array.isArray) as unknown[]|undefined;return{ok:true,value:[{providerId:GOOGLE_CLOUD_PROVIDER_ID,organizationId:config.organizationId,capabilityId,resourceType:capabilityId.split('.')[1]??'google_cloud',resourceId:config.projectId,observedAt:new Date().toISOString(),state:rows&&rows.length===0?'empty':'available',metadata:{count:rows?rows.length:1,region:config.region??null,zone:config.zone??null},evidence:result.evidence}],evidence:result.evidence}}}
export const GoogleCloudProvider=new GoogleCloudReadOnlyAdapter()
