// saas/lib/provider-framework/namecheap.ts
import { randomUUID } from 'node:crypto'
import { UNIVERSAL_PROVIDER_SCHEMA_VERSION, type UniversalProviderCapability, type UniversalProviderHealth, type UniversalProviderMetadata, type UniversalProviderSdk } from './types.ts'

export const NAMECHEAP_PROVIDER_ID = 'namecheap' as const
export const namecheapCapabilities = ['namecheap.connection.validate','namecheap.domains.list','namecheap.domains.info.read','namecheap.domains.dns.hosts.read','namecheap.domains.dns.email_forwarding.read','namecheap.domains.nameservers.read','namecheap.ssl.certificates.list','namecheap.users.addresses.list','namecheap.account.balance.read','namecheap.whoisguard.status.read'] as const
export type NamecheapCapability = typeof namecheapCapabilities[number]
export type NamecheapRuntimeConfig = { readonly organizationId:string; readonly apiUser:string; readonly apiKey:string; readonly userName:string; readonly clientIp:string; readonly domainName?:string; readonly apiBaseUrl?:string; readonly sandbox?:boolean }
export type NamecheapEvidence = { readonly evidenceId:string; readonly summary:string; readonly metadata:Readonly<Record<string,string|number|boolean|null>> }
export type NamecheapProviderError = { readonly kind:'authentication'|'authorization'|'not_found'|'rate_limited'|'timeout'|'provider_outage'|'malformed_response'|'unsupported_mutation'|'configuration'|'unknown'; readonly message:string; readonly retryable:boolean; readonly status?:number }
export type NamecheapProviderResult<T> = { readonly ok:true; readonly value:T; readonly evidence:readonly NamecheapEvidence[] } | { readonly ok:false; readonly error:NamecheapProviderError; readonly evidence:readonly NamecheapEvidence[] }
export type NamecheapObservation = { readonly providerId:typeof NAMECHEAP_PROVIDER_ID; readonly organizationId:string; readonly capabilityId:NamecheapCapability; readonly resourceType:string; readonly resourceId:string; readonly observedAt:string; readonly state:'available'|'empty'; readonly metadata:Readonly<Record<string,string|number|boolean|null>>; readonly evidence:readonly NamecheapEvidence[] }
type FetchLike = (url:string, init:RequestInit)=>Promise<Response>
const ev=(summary:string,metadata:NamecheapEvidence['metadata']={}):NamecheapEvidence=>({evidenceId:`evidence_${randomUUID()}`,summary,metadata})
function cap(id:NamecheapCapability):UniversalProviderCapability{return{capabilityId:id,displayNameKey:`universalProvider.namecheap.capabilities.${id}.title`,descriptionKey:`universalProvider.namecheap.capabilities.${id}.description`,version:'1.0.0',maturity:'sandbox_verified',riskClass:'read_only',channels:['api','scheduler'],environments:['sandbox','preview','production'],authentication:['api_key'],requiresApproval:false,readOnly:true,rateLimit:{windowSeconds:60,maxRequests:20,scope:'credential'},timeout:{connectMs:3000,readMs:10000,totalMs:15000},retryPolicy:{maxAttempts:3,backoff:'exponential',baseDelayMs:500,maxDelayMs:10000},scheduler:{supported:true,minimumIntervalSeconds:300,jitterSupported:true,localizationKey:'universalProvider.namecheap.scheduler'},evidenceProviderIds:['namecheap_api_snapshot'],verificationProviderIds:['namecheap_current_state']}}
export const namecheapProviderMetadata=Object.freeze<UniversalProviderMetadata>({providerId:NAMECHEAP_PROVIDER_ID,displayNameKey:'universalProvider.namecheap.displayName',descriptionKey:'universalProvider.namecheap.description',version:{providerVersion:'1.0.0',sdkVersion:'namecheap-readonly-v1',capabilityCatalogVersion:'namecheap-readonly-1',schemaVersion:UNIVERSAL_PROVIDER_SCHEMA_VERSION,compatibleSchemaVersions:[UNIVERSAL_PROVIDER_SCHEMA_VERSION]},health:{lifecycle:'registered',checkedAt:'1970-01-01T00:00:00.000Z'},capabilities:namecheapCapabilities.map(cap),supportedChannels:['api','scheduler'],supportedAuthentication:['api_key'],supportedEnvironments:['sandbox','preview','production'],supportedRegions:['global'],configurationSchema:{schemaId:'namecheap.connection.v1',version:'1.0.0',fields:[{key:'credential_ref',type:'secret_ref',required:true,labelKey:'universalProvider.namecheap.config.credentialRef'},{key:'client_ip',type:'string',required:true,labelKey:'universalProvider.namecheap.config.clientIp'},{key:'domain_name',type:'string',required:false,labelKey:'universalProvider.namecheap.config.domainName'}]},webhook:{supported:false,eventTypes:[],signatureSchemes:[],replayProtection:false},scheduler:{supported:true,minimumIntervalSeconds:300,jitterSupported:true,localizationKey:'universalProvider.namecheap.scheduler'},operator:{ownerTeamKey:'universalProvider.operator.ownerTeam',documentationKey:'universalProvider.namecheap.documentation'}})
function err(error:unknown,status?:number):NamecheapProviderError{if(error instanceof DOMException&&error.name==='AbortError')return{kind:'timeout',message:'Namecheap request timed out',retryable:true};if(status===401)return{kind:'authentication',message:'Namecheap credentials are invalid',retryable:false,status};if(status===403)return{kind:'authorization',message:'Namecheap credentials lack read permission',retryable:false,status};if(status===404)return{kind:'not_found',message:'Namecheap resource was not found',retryable:false,status};if(status===429)return{kind:'rate_limited',message:'Namecheap rate limit reached',retryable:true,status};if(status&&status>=500)return{kind:'provider_outage',message:'Namecheap API is unavailable',retryable:true,status};return{kind:'unknown',message:'Namecheap request failed',retryable:false,status}}
function splitDomain(domainName:string):{sld:string;tld:string}{const parts=domainName.trim().toLowerCase().split('.');if(parts.length<2)throw new Error('invalid domain');return{sld:parts.slice(0,-1).join('.'),tld:parts.at(-1)??''}}
function command(id:NamecheapCapability,config:NamecheapRuntimeConfig):{name:string;extra:Record<string,string>}{switch(id){case'namecheap.connection.validate':case'namecheap.domains.list':return{name:'namecheap.domains.getList',extra:{}};case'namecheap.domains.info.read':return{name:'namecheap.domains.getInfo',extra:{DomainName:config.domainName??''}};case'namecheap.domains.dns.hosts.read':{const d=splitDomain(config.domainName??'');return{name:'namecheap.domains.dns.getHosts',extra:{SLD:d.sld,TLD:d.tld}}}case'namecheap.domains.dns.email_forwarding.read':{const d=splitDomain(config.domainName??'');return{name:'namecheap.domains.dns.getEmailForwarding',extra:{DomainName:`${d.sld}.${d.tld}`}}}case'namecheap.domains.nameservers.read':return{name:'namecheap.domains.getInfo',extra:{DomainName:config.domainName??''}};case'namecheap.ssl.certificates.list':return{name:'namecheap.ssl.getList',extra:{}};case'namecheap.users.addresses.list':return{name:'namecheap.users.address.getList',extra:{}};case'namecheap.account.balance.read':return{name:'namecheap.users.getBalances',extra:{}};case'namecheap.whoisguard.status.read':return{name:'namecheap.domains.getInfo',extra:{DomainName:config.domainName??''}}}}
export class NamecheapReadOnlyAdapter implements UniversalProviderSdk{readonly metadata=namecheapProviderMetadata;private readonly fetcher: FetchLike
constructor(fetcher: FetchLike = fetch){ this.fetcher = fetcher;}listCapabilities(){return this.metadata.capabilities}getCapability(id:string){return this.metadata.capabilities.find(c=>c.capabilityId===id)}getHealth():UniversalProviderHealth{return this.metadata.health}getVersion(){return this.metadata.version}rejectMutation(operation:string):NamecheapProviderResult<never>{return{ok:false,error:{kind:'unsupported_mutation',message:`Namecheap mutation '${operation}' is not supported by the read-only adapter`,retryable:false},evidence:[ev('Rejected unsupported Namecheap mutation',{operation})]}}
private async request(config:NamecheapRuntimeConfig,capabilityId:NamecheapCapability):Promise<NamecheapProviderResult<string>>{if(!config.apiUser||!config.apiKey||!config.userName||!config.clientIp)return{ok:false,error:{kind:'configuration',message:'Missing Namecheap API configuration',retryable:false},evidence:[ev('Missing Namecheap API configuration')]};let selected:{name:string;extra:Record<string,string>};try{selected=command(capabilityId,config)}catch{return{ok:false,error:{kind:'configuration',message:'A valid domain name is required',retryable:false},evidence:[ev('Invalid Namecheap domain name',{capabilityId})]}}const query=new URLSearchParams({ApiUser:config.apiUser,ApiKey:config.apiKey,UserName:config.userName,ClientIp:config.clientIp,Command:selected.name,...selected.extra});const base=config.apiBaseUrl??(config.sandbox?'https://api.sandbox.namecheap.com/xml.response':'https://api.namecheap.com/xml.response');const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),15000);try{const response=await this.fetcher(`${base}?${query.toString()}`,{method:'GET',headers:{accept:'application/xml'},signal:controller.signal});if(!response.ok)return{ok:false,error:err(undefined,response.status),evidence:[ev('Namecheap API returned an error',{status:response.status,command:selected.name})]};const text=await response.text();if(!text.includes('<ApiResponse'))return{ok:false,error:{kind:'malformed_response',message:'Namecheap response was malformed',retryable:false},evidence:[ev('Malformed Namecheap response',{command:selected.name})]};if(/Status="ERROR"/i.test(text))return{ok:false,error:{kind:'unknown',message:'Namecheap API returned an application error',retryable:false},evidence:[ev('Namecheap application error',{command:selected.name})]};return{ok:true,value:text,evidence:[ev('Namecheap read completed',{command:selected.name})]}}catch(error){return{ok:false,error:err(error),evidence:[ev('Namecheap read failed',{command:selected.name})]}}finally{clearTimeout(timer)}}
async validateConnection(config:NamecheapRuntimeConfig):Promise<NamecheapProviderResult<{connected:true}>>{const result=await this.request(config,'namecheap.connection.validate');if(result.ok===false)return{ok:false,error:result.error,evidence:result.evidence};return{ok:true,value:{connected:true},evidence:result.evidence}}
async observe(config:NamecheapRuntimeConfig,capabilityId:NamecheapCapability):Promise<NamecheapProviderResult<readonly NamecheapObservation[]>>{if(!namecheapCapabilities.includes(capabilityId))return{ok:false,error:{kind:'configuration',message:'Unsupported Namecheap capability',retryable:false},evidence:[ev('Unsupported Namecheap capability',{capabilityId})]};const needsDomain=['namecheap.domains.info.read','namecheap.domains.dns.hosts.read','namecheap.domains.dns.email_forwarding.read','namecheap.domains.nameservers.read','namecheap.whoisguard.status.read'].includes(capabilityId);if(needsDomain&&!config.domainName)return{ok:false,error:{kind:'configuration',message:'Missing Namecheap domain name',retryable:false},evidence:[ev('Missing Namecheap domain name',{capabilityId})]};const result=await this.request(config,capabilityId);if(result.ok===false)return{ok:false,error:result.error,evidence:result.evidence};const empty=!/[A-Za-z]+Result|<Domain|<host|<Address|<SSL|AvailableBalance/i.test(result.value);return{ok:true,value:[{providerId:NAMECHEAP_PROVIDER_ID,organizationId:config.organizationId,capabilityId,resourceType:capabilityId.split('.')[1]??'namecheap',resourceId:config.domainName??capabilityId,observedAt:new Date().toISOString(),state:empty?'empty':'available',metadata:{responseBytes:result.value.length},evidence:result.evidence}],evidence:result.evidence}}}
export const NamecheapProvider=new NamecheapReadOnlyAdapter()
