import { randomUUID } from 'node:crypto'
import { UNIVERSAL_PROVIDER_SCHEMA_VERSION, type UniversalProviderCapability, type UniversalProviderHealth, type UniversalProviderMetadata, type UniversalProviderSdk } from './types.ts'

export const STRIPE_PROVIDER_ID = 'stripe' as const
export const stripeCapabilities = ['stripe.connection.validate','stripe.account.read','stripe.balance.read','stripe.charges.list','stripe.payment_intents.list','stripe.refunds.list','stripe.disputes.list','stripe.subscriptions.list','stripe.invoices.list','stripe.events.list'] as const
export type StripeCapability = typeof stripeCapabilities[number]
export type StripeRuntimeConfig = { readonly organizationId:string; readonly secretKey:string; readonly apiBaseUrl?:string; readonly stripeAccount?:string }
export type StripeEvidence = { readonly evidenceId:string; readonly summary:string; readonly metadata:Readonly<Record<string,string|number|boolean|null>> }
export type StripeProviderError = { readonly kind:'authentication'|'authorization'|'not_found'|'rate_limited'|'timeout'|'provider_outage'|'malformed_response'|'unsupported_mutation'|'configuration'|'unknown'; readonly message:string; readonly retryable:boolean; readonly status?:number }
export type StripeProviderResult<T> = { readonly ok:true; readonly value:T; readonly evidence:readonly StripeEvidence[] } | { readonly ok:false; readonly error:StripeProviderError; readonly evidence:readonly StripeEvidence[] }
export type StripeObservation = { readonly providerId:typeof STRIPE_PROVIDER_ID; readonly organizationId:string; readonly capabilityId:StripeCapability; readonly resourceType:string; readonly resourceId:string; readonly observedAt:string; readonly state:'available'|'empty'; readonly metadata:Readonly<Record<string,string|number|boolean|null>>; readonly evidence:readonly StripeEvidence[] }
type FetchLike = (url:string, init:RequestInit)=>Promise<Response>
const ev=(summary:string,metadata:StripeEvidence['metadata']={}):StripeEvidence=>({evidenceId:`evidence_${randomUUID()}`,summary,metadata})
function cap(id:StripeCapability):UniversalProviderCapability{return{capabilityId:id,displayNameKey:`universalProvider.stripe.capabilities.${id}.title`,descriptionKey:`universalProvider.stripe.capabilities.${id}.description`,version:'1.0.0',maturity:'sandbox_verified',riskClass:'read_only',channels:['api','scheduler'],environments:['sandbox','preview','production'],authentication:['api_key'],requiresApproval:false,readOnly:true,rateLimit:{windowSeconds:1,maxRequests:100,scope:'credential'},timeout:{connectMs:3000,readMs:10000,totalMs:15000},retryPolicy:{maxAttempts:3,backoff:'exponential',baseDelayMs:500,maxDelayMs:10000},scheduler:{supported:true,minimumIntervalSeconds:300,jitterSupported:true,localizationKey:'universalProvider.stripe.scheduler'},evidenceProviderIds:['stripe_api_snapshot'],verificationProviderIds:['stripe_current_state']}}
export const stripeProviderMetadata:UniversalProviderMetadata=Object.freeze({providerId:STRIPE_PROVIDER_ID,displayNameKey:'universalProvider.stripe.displayName',descriptionKey:'universalProvider.stripe.description',version:{providerVersion:'1.0.0',sdkVersion:'stripe-rest-readonly-v1',capabilityCatalogVersion:'stripe-readonly-1',schemaVersion:UNIVERSAL_PROVIDER_SCHEMA_VERSION,compatibleSchemaVersions:[UNIVERSAL_PROVIDER_SCHEMA_VERSION]},health:{lifecycle:'registered' as const,checkedAt:'1970-01-01T00:00:00.000Z'},capabilities:stripeCapabilities.map(cap),supportedChannels:['api','scheduler'],supportedAuthentication:['api_key'],supportedEnvironments:['sandbox','preview','production'],supportedRegions:['global'],configurationSchema:{schemaId:'stripe.connection.v1',version:'1.0.0',fields:[{key:'credential_ref',type:'secret_ref',required:true,labelKey:'universalProvider.stripe.config.credentialRef'},{key:'stripe_account',type:'string',required:false,labelKey:'universalProvider.stripe.config.connectedAccount'},{key:'api_base_url',type:'url',required:false,labelKey:'universalProvider.stripe.config.apiBaseUrl',validationPattern:'^https://'}]},webhook:{supported:false,eventTypes:[],signatureSchemes:[],replayProtection:false,localizationKey:'universalProvider.stripe.webhook'},scheduler:{supported:true,minimumIntervalSeconds:300,jitterSupported:true,localizationKey:'universalProvider.stripe.scheduler'},operator:{ownerTeamKey:'universalProvider.operator.ownerTeam',documentationKey:'universalProvider.stripe.documentation'}})
function err(error:unknown,status?:number):StripeProviderError{if(error instanceof DOMException&&error.name==='AbortError')return{kind:'timeout',message:'Stripe request timed out',retryable:true};if(status===401)return{kind:'authentication',message:'Stripe credentials are invalid or revoked',retryable:false,status};if(status===403)return{kind:'authorization',message:'Stripe credentials lack read permission',retryable:false,status};if(status===404)return{kind:'not_found',message:'Stripe resource was not found',retryable:false,status};if(status===429)return{kind:'rate_limited',message:'Stripe rate limit reached',retryable:true,status};if(status&&status>=500)return{kind:'provider_outage',message:'Stripe API is unavailable',retryable:true,status};return{kind:'unknown',message:'Stripe request failed',retryable:false,status}}
function path(id:StripeCapability):string{switch(id){case'stripe.connection.validate':case'stripe.account.read':return'/v1/account';case'stripe.balance.read':return'/v1/balance';case'stripe.charges.list':return'/v1/charges?limit=100';case'stripe.payment_intents.list':return'/v1/payment_intents?limit=100';case'stripe.refunds.list':return'/v1/refunds?limit=100';case'stripe.disputes.list':return'/v1/disputes?limit=100';case'stripe.subscriptions.list':return'/v1/subscriptions?limit=100&status=all';case'stripe.invoices.list':return'/v1/invoices?limit=100';case'stripe.events.list':return'/v1/events?limit=100'}}
export class StripeReadOnlyAdapter implements UniversalProviderSdk{readonly metadata=stripeProviderMetadata;constructor(private readonly fetcher:FetchLike=fetch){}listCapabilities(){return this.metadata.capabilities}getCapability(id:string){return this.metadata.capabilities.find(c=>c.capabilityId===id)}getHealth():UniversalProviderHealth{return this.metadata.health}getVersion(){return this.metadata.version}rejectMutation(operation:string):StripeProviderResult<never>{return{ok:false,error:{kind:'unsupported_mutation',message:`Stripe mutation '${operation}' is not supported by the read-only adapter`,retryable:false},evidence:[ev('Rejected unsupported Stripe mutation',{operation})]}}
private async request(config:StripeRuntimeConfig,endpoint:string):Promise<StripeProviderResult<unknown>>{if(!config.secretKey)return{ok:false,error:{kind:'configuration',message:'Missing Stripe credential',retryable:false},evidence:[ev('Missing Stripe credential')]};const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),15000);try{const headers:Record<string,string>={authorization:`Bearer ${config.secretKey}`,accept:'application/json','user-agent':'SignalBoost-UniversalProvider/1.0'};if(config.stripeAccount)headers['stripe-account']=config.stripeAccount;const response=await this.fetcher(`${config.apiBaseUrl??'https://api.stripe.com'}${endpoint}`,{method:'GET',headers,signal:controller.signal});if(!response.ok)return{ok:false,error:err(undefined,response.status),evidence:[ev('Stripe API returned an error',{status:response.status,endpoint})]};return{ok:true,value:await response.json(),evidence:[ev('Stripe read completed',{endpoint})]}}catch(error){return{ok:false,error:err(error),evidence:[ev('Stripe read failed',{endpoint})]}}finally{clearTimeout(timer)}}
async validateConnection(config:StripeRuntimeConfig):Promise<StripeProviderResult<{id:string}>>{const result=await this.request(config,'/v1/account');if(!result.ok)return result;const value=result.value as Record<string,unknown>;if(typeof value?.id!=='string')return{ok:false,error:{kind:'malformed_response',message:'Stripe account response was malformed',retryable:false},evidence:result.evidence};return{ok:true,value:{id:value.id},evidence:result.evidence}}
async observe(config:StripeRuntimeConfig,capabilityId:StripeCapability):Promise<StripeProviderResult<readonly StripeObservation[]>>{if(!stripeCapabilities.includes(capabilityId))return{ok:false,error:{kind:'configuration',message:'Unsupported Stripe capability',retryable:false},evidence:[ev('Unsupported Stripe capability',{capabilityId})]};const result=await this.request(config,path(capabilityId));if(!result.ok)return result;const payload=result.value as Record<string,unknown>;const rows=Array.isArray(payload?.data)?payload.data:null;return{ok:true,value:[{providerId:STRIPE_PROVIDER_ID,organizationId:config.organizationId,capabilityId,resourceType:capabilityId.split('.')[1]??'stripe',resourceId:typeof payload?.id==='string'?payload.id:capabilityId,observedAt:new Date().toISOString(),state:rows&&rows.length===0?'empty':'available',metadata:{count:rows?rows.length:1,hasMore:typeof payload?.has_more==='boolean'?payload.has_more:false},evidence:result.evidence}],evidence:result.evidence}}}
export const StripeProvider=new StripeReadOnlyAdapter()