// saas/lib/provider-framework/supabase.ts
import { randomUUID } from 'node:crypto'
import { UNIVERSAL_PROVIDER_SCHEMA_VERSION, type UniversalProviderCapability, type UniversalProviderHealth, type UniversalProviderMetadata, type UniversalProviderSdk } from './types.ts'

export const SUPABASE_PROVIDER_ID = 'supabase' as const
export const supabaseCapabilities = [
  'supabase.connection.validate',
  'supabase.project.read',
  'supabase.tables.list',
  'supabase.functions.list',
  'supabase.storage.buckets.list',
  'supabase.auth.settings.read',
  'supabase.logs.read',
  'supabase.database.health.read',
] as const
export type SupabaseCapability = typeof supabaseCapabilities[number]
export type SupabaseRuntimeConfig = { readonly organizationId:string; readonly projectUrl:string; readonly serviceRoleKey:string; readonly managementApiBaseUrl?:string }
export type SupabaseEvidence = { readonly evidenceId:string; readonly summary:string; readonly metadata:Readonly<Record<string,string|number|boolean|null>> }
export type SupabaseProviderError = { readonly kind:'authentication'|'authorization'|'not_found'|'rate_limited'|'timeout'|'provider_outage'|'malformed_response'|'unsupported_mutation'|'configuration'|'unknown'; readonly message:string; readonly retryable:boolean; readonly status?:number }
export type SupabaseProviderResult<T> = { readonly ok:true; readonly value:T; readonly evidence:readonly SupabaseEvidence[] } | { readonly ok:false; readonly error:SupabaseProviderError; readonly evidence:readonly SupabaseEvidence[] }
export type SupabaseObservation = { readonly providerId:typeof SUPABASE_PROVIDER_ID; readonly organizationId:string; readonly capabilityId:SupabaseCapability; readonly resourceType:string; readonly resourceId:string; readonly observedAt:string; readonly state:'available'|'empty'; readonly metadata:Readonly<Record<string,string|number|boolean|null>>; readonly evidence:readonly SupabaseEvidence[] }
type FetchLike = (url:string, init:RequestInit)=>Promise<Response>
const ev=(summary:string,metadata:SupabaseEvidence['metadata']={}):SupabaseEvidence=>({evidenceId:`evidence_${randomUUID()}`,summary,metadata})
function cap(id:SupabaseCapability):UniversalProviderCapability{return{capabilityId:id,displayNameKey:`universalProvider.supabase.capabilities.${id}.title`,descriptionKey:`universalProvider.supabase.capabilities.${id}.description`,version:'1.0.0',maturity:'sandbox_verified',riskClass:'read_only',channels:['api','scheduler'],environments:['sandbox','preview','production'],authentication:['service_role'],requiresApproval:false,readOnly:true,rateLimit:{windowSeconds:60,maxRequests:120,scope:'credential'},timeout:{connectMs:3000,readMs:10000,totalMs:15000},retryPolicy:{maxAttempts:3,backoff:'exponential',baseDelayMs:500,maxDelayMs:10000},scheduler:{supported:true,minimumIntervalSeconds:300,jitterSupported:true,localizationKey:'universalProvider.supabase.scheduler'},evidenceProviderIds:['supabase_api_snapshot'],verificationProviderIds:['supabase_current_state']}}
export const supabaseProviderMetadata=Object.freeze<UniversalProviderMetadata>({providerId:SUPABASE_PROVIDER_ID,displayNameKey:'universalProvider.supabase.displayName',descriptionKey:'universalProvider.supabase.description',version:{providerVersion:'1.0.0',sdkVersion:'supabase-rest-readonly-v1',capabilityCatalogVersion:'supabase-readonly-1',schemaVersion:UNIVERSAL_PROVIDER_SCHEMA_VERSION,compatibleSchemaVersions:[UNIVERSAL_PROVIDER_SCHEMA_VERSION]},health:{lifecycle:'registered',checkedAt:'1970-01-01T00:00:00.000Z'},capabilities:supabaseCapabilities.map(cap),supportedChannels:['api','scheduler'],supportedAuthentication:['service_role'],supportedEnvironments:['sandbox','preview','production'],supportedRegions:['global'],configurationSchema:{schemaId:'supabase.connection.v1',version:'1.0.0',fields:[{key:'project_url',type:'url',required:true,labelKey:'universalProvider.supabase.config.projectUrl',validationPattern:'^https://'},{key:'credential_ref',type:'secret_ref',required:true,labelKey:'universalProvider.supabase.config.credentialRef'}]},webhook:{supported:false,eventTypes:[],signatureSchemes:[],replayProtection:false,localizationKey:'universalProvider.supabase.webhook'},scheduler:{supported:true,minimumIntervalSeconds:300,jitterSupported:true,localizationKey:'universalProvider.supabase.scheduler'},operator:{ownerTeamKey:'universalProvider.operator.ownerTeam',documentationKey:'universalProvider.supabase.documentation'}})
function err(error:unknown,status?:number):SupabaseProviderError{if(error instanceof DOMException&&error.name==='AbortError')return{kind:'timeout',message:'Supabase request timed out',retryable:true};if(status===401)return{kind:'authentication',message:'Supabase credentials are invalid or revoked',retryable:false,status};if(status===403)return{kind:'authorization',message:'Supabase credentials lack read permission',retryable:false,status};if(status===404)return{kind:'not_found',message:'Supabase resource was not found',retryable:false,status};if(status===429)return{kind:'rate_limited',message:'Supabase rate limit reached',retryable:true,status};if(status&&status>=500)return{kind:'provider_outage',message:'Supabase API is unavailable',retryable:true,status};return{kind:'unknown',message:'Supabase request failed',retryable:false,status}}
function endpoint(config:SupabaseRuntimeConfig,id:SupabaseCapability):string{switch(id){case'supabase.connection.validate':case'supabase.project.read':return`${config.projectUrl}/rest/v1/`;case'supabase.tables.list':return`${config.projectUrl}/rest/v1/`;case'supabase.functions.list':return`${config.projectUrl}/functions/v1/`;case'supabase.storage.buckets.list':return`${config.projectUrl}/storage/v1/bucket`;case'supabase.auth.settings.read':return`${config.projectUrl}/auth/v1/settings`;case'supabase.logs.read':return`${config.managementApiBaseUrl??'https://api.supabase.com'}/v1/projects`;case'supabase.database.health.read':return`${config.projectUrl}/rest/v1/`}}
export class SupabaseReadOnlyAdapter implements UniversalProviderSdk{readonly metadata=supabaseProviderMetadata;private readonly fetcher: FetchLike
constructor(fetcher: FetchLike = fetch){ this.fetcher = fetcher;}listCapabilities(){return this.metadata.capabilities}getCapability(id:string){return this.metadata.capabilities.find(c=>c.capabilityId===id)}getHealth():UniversalProviderHealth{return this.metadata.health}getVersion(){return this.metadata.version}rejectMutation(operation:string):SupabaseProviderResult<never>{return{ok:false,error:{kind:'unsupported_mutation',message:`Supabase mutation '${operation}' is not supported by the read-only adapter`,retryable:false},evidence:[ev('Rejected unsupported Supabase mutation',{operation})]}}
private async request(config:SupabaseRuntimeConfig,url:string):Promise<SupabaseProviderResult<unknown>>{if(!config.projectUrl||!config.serviceRoleKey)return{ok:false,error:{kind:'configuration',message:'Missing Supabase project URL or credential',retryable:false},evidence:[ev('Missing Supabase configuration')]};const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),15000);try{const response=await this.fetcher(url,{method:'GET',headers:{apikey:config.serviceRoleKey,authorization:`Bearer ${config.serviceRoleKey}`,accept:'application/json','user-agent':'SignalBoost-UniversalProvider/1.0'},signal:controller.signal});if(!response.ok)return{ok:false,error:err(undefined,response.status),evidence:[ev('Supabase API returned an error',{status:response.status,url})]};const text=await response.text();const value=text?JSON.parse(text):{};return{ok:true,value,evidence:[ev('Supabase read completed',{url})]}}catch(error){return{ok:false,error:err(error),evidence:[ev('Supabase read failed',{url})]}}finally{clearTimeout(timer)}}
async validateConnection(config:SupabaseRuntimeConfig):Promise<SupabaseProviderResult<{projectUrl:string}>>{const result=await this.request(config,endpoint(config,'supabase.connection.validate'));if(result.ok===false)return{ok:false,error:result.error,evidence:result.evidence};return{ok:true,value:{projectUrl:config.projectUrl},evidence:result.evidence}}
async observe(config:SupabaseRuntimeConfig,capabilityId:SupabaseCapability):Promise<SupabaseProviderResult<readonly SupabaseObservation[]>>{if(!supabaseCapabilities.includes(capabilityId))return{ok:false,error:{kind:'configuration',message:'Unsupported Supabase capability',retryable:false},evidence:[ev('Unsupported Supabase capability',{capabilityId})]};const result=await this.request(config,endpoint(config,capabilityId));if(result.ok===false)return{ok:false,error:result.error,evidence:result.evidence};const payload=result.value;const rows=Array.isArray(payload)?payload:null;return{ok:true,value:[{providerId:SUPABASE_PROVIDER_ID,organizationId:config.organizationId,capabilityId,resourceType:capabilityId.split('.')[1]??'supabase',resourceId:config.projectUrl,observedAt:new Date().toISOString(),state:rows&&rows.length===0?'empty':'available',metadata:{count:rows?rows.length:1},evidence:result.evidence}],evidence:result.evidence}}}
export const SupabaseProvider=new SupabaseReadOnlyAdapter()
